"""Extra questions: Deutschland spezial (format: see tools/content/merge_extra.py)."""
KAT = "deutschland_spezial"
REGION = "de"
DATA = r"""
@ alltag_buerokratie
C E | Welche Notrufnummer wählt man in Deutschland für Feuerwehr und Rettungsdienst? | 112 | 110 ; 115 ; 116 | Sie gilt in der ganzen EU. ; Die Polizei hat eine andere Nummer. ; Die Ziffern ergeben zusammen 4. | Die 112 funktioniert in der ganzen EU kostenlos — auch vom Handy.
C E | Welche Nummer wählt man in Deutschland, um die Polizei zu rufen? | 110 | 112 ; 111 ; 119 | Sie endet auf null. ; Feuerwehr und Rettungsdienst haben die 112. ; „Eins-Eins-Null“. | Die 110 ist bundesweit kostenlos erreichbar.
C E | Welche Stadt hat das Autokennzeichen „HH“? | Hamburg | Hannover ; Halle ; Heidelberg | Das zweite H steht für „Hansestadt“. ; Die Stadt hat einen großen Hafen. ; Sie liegt an der Elbe. | HH steht für „Hansestadt Hamburg“; Bremen hat entsprechend HB.
C E | Welche Stadt hat das Autokennzeichen „M“? | München | Mainz ; Magdeburg ; Mannheim | Die Stadt ist bayerische Landeshauptstadt. ; Große Städte bekamen einstellige Kürzel. ; Hier findet das Oktoberfest statt. | Einbuchstabige Kennzeichen gibt es nur für große Städte wie B, M, K, F oder S.
C E | Welche Stadt hat das Autokennzeichen „K“? | Köln | Kiel ; Kassel ; Karlsruhe | Ihr Dom ist weltberühmt. ; Sie liegt am Rhein. ; Hier feiert man „Kölle Alaaf“. | Kiel hat KI, Kassel KS und Karlsruhe KA.
C E | Welche Farbe hat in den meisten deutschen Städten die Papiertonne? | Blau | Gelb ; Braun ; Schwarz | Die Gelbe ist für Verpackungen. ; Die Braune für Bioabfall. ; Die Farbe des Himmels. | In vielen Kommunen gilt: blau für Papier, gelb für Verpackungen, braun für Bio, grau oder schwarz für Restmüll.
C E | Was bedeutet der Behördenbegriff „Lichtzeichenanlage“? | Ampel | Straßenlaterne ; Leuchtreklame ; Blitzer | Sie zeigt Rot, Gelb und Grün. ; Sie regelt den Verkehr an Kreuzungen. ; Das Ampelmännchen gehört dazu. | Die Straßenverkehrs-Ordnung spricht offiziell von „Lichtzeichenanlagen“.
C E | Was meint die Behörde mit einem „Postwertzeichen“? | Briefmarke | Postleitzahl ; Paketschein ; Stempel | Man klebt es auf einen Brief. ; Es ist meist gezahnt. ; Sammler nennen sich Philatelisten. | Die erste deutsche Briefmarke war 1849 der „Schwarze Einser“ aus Bayern.
C E | Welches Land hat die internationale Telefonvorwahl +49? | Deutschland | Österreich ; Schweiz ; Niederlande | Österreich hat +43, die Schweiz +41. ; Es ist das Land, in dem du wahrscheinlich gerade spielst. ; Die Nummer liegt knapp unter 50. | Aus dem Ausland ersetzt +49 die erste Null der Ortsvorwahl.
C E | Was meint das Amtsdeutsch mit „Beförderungserschleichung“? | Schwarzfahren | Taxifahren ohne Quittung ; Vordrängeln an der Haltestelle ; Trampen | Es geht um Bus und Bahn. ; Man hat kein Ticket. ; Der Kontrolleur verlangt dann ein „erhöhtes Beförderungsentgelt“. | Schwarzfahren gilt in Deutschland nach § 265a StGB als Straftat.
C M | Wie viele Urlaubstage stehen Vollzeitbeschäftigten bei einer Fünf-Tage-Woche gesetzlich mindestens zu? | 20 | 24 ; 25 ; 30 | Das Gesetz nennt 24 Werktage — Samstage zählen mit. ; Umgerechnet auf fünf Arbeitstage sind es weniger. ; Vier volle Wochen. | Viele Tarifverträge gewähren mehr — gesetzlich vorgeschrieben sind aber nur vier Wochen.
C E | Ab welchem Alter darf man in Deutschland beim begleiteten Fahren Auto fahren? | 17 | 16 ; 18 ; 15 | Eine erfahrene Begleitperson muss dabei sein. ; Ein Jahr vor der Volljährigkeit. ; Das Modell heißt „BF17“. | Beim begleiteten Fahren muss die Begleitperson mindestens 30 Jahre alt sein.
C M | Wie lange dauert die Probezeit nach dem ersten Führerschein in Deutschland normalerweise? | Zwei Jahre | Ein Jahr ; Sechs Monate ; Drei Jahre | Wer schwer gegen Regeln verstößt, dem wird sie verlängert. ; Dann gilt sie vier Jahre. ; Eine gerade Zahl an Jahren. | Während der Probezeit gilt ein striktes Alkoholverbot am Steuer.
C M | In welchen Altglas-Container gehören blaue Glasflaschen? | Grünglas | Weißglas ; Braunglas ; Restmüll | Für Blau gibt es keinen eigenen Container. ; Diese Farbe verträgt am meisten Fremdfarben. ; Auch rote Flaschen gehören dorthin. | Grünglas-Schmelzen vertragen andere Farben am besten.
C M | Was bezeichnet der Behördenbegriff „raumübergreifendes Großgrün“ scherzhaft? | Einen Baum | Einen Stadtpark ; Eine Hecke ; Einen Rasen | Es ist groß und grün. ; Es hat Äste. ; Im Herbst verliert es oft Blätter. | Der Ausdruck gilt als Paradebeispiel für kompliziertes Amtsdeutsch.
C H | Wie heißt die Bescheinigung, die der Vermieter beim Einzug für die Meldebehörde ausstellen muss? | Wohnungsgeberbestätigung | Mietschuldenfreiheitsbescheinigung ; Einzugsgenehmigung ; Meldeschein A | Sie wurde 2015 wieder eingeführt. ; Man braucht sie zur Anmeldung beim Bürgeramt. ; Im Wort steckt der Geber der Wohnung. | Ohne Wohnungsgeberbestätigung kann man sich in Deutschland nicht ummelden.
C H | Wie viele Zeichen hat eine deutsche IBAN? | 22 | 20 ; 18 ; 24 | Sie beginnt mit DE. ; Danach folgen zwei Prüfziffern. ; Mehr als 20. | DE, zwei Prüfziffern, acht Stellen Bankleitzahl und zehn Stellen Kontonummer ergeben 22 Zeichen.
C H | Wie lange ist ein deutscher Personalausweis für Personen ab 24 Jahren gültig? | Zehn Jahre | Fünf Jahre ; Sechs Jahre ; Fünfzehn Jahre | Für Jüngere gelten sechs Jahre. ; Ein ganzes Jahrzehnt. ; Beim Reisepass ist es genauso. | Wer unter 24 ist, bekommt einen Ausweis mit sechs Jahren Gültigkeit.
C H | Was bedeutet in Deutschland der „Blaue Brief“ in der Schule? | Warnung, dass die Versetzung gefährdet ist | Einladung zum Elternabend ; Zeugnis mit Auszeichnung ; Schulverweis | Früher kam er in einem blauen Umschlag. ; Er kommt oft zum Halbjahr. ; Es geht ums Sitzenbleiben. | Der Name stammt von den blauen Umschlägen, in denen früher auch preußische Offiziere ihre Entlassung erhielten.
C H | Was ist in der deutschen Verwaltung eine „nicht lebende Einfriedung“? | Ein Zaun oder eine Mauer | Ein Friedhof ; Ein Parkplatz ; Ein Stoppschild | Das Gegenstück ist eine Hecke. ; Es trennt Grundstücke. ; Es ist nicht grün. | Eine Hecke wäre entsprechend eine „lebende Einfriedung“.
C U | Wie hieß die erste Briefmarke Deutschlands, die 1849 in Bayern erschien? | Schwarzer Einser | Blaue Mauritius ; Roter Kreuzer ; Sächsischer Dreier | Sie kostete einen Kreuzer. ; Sie war schwarz gedruckt. ; Der Name nennt Farbe und Wert. | Der „Schwarze Einser“ erschien am 1. November 1849.
C U | Welcher Artikel des Grundgesetzes enthält den Satz „Männer und Frauen sind gleichberechtigt“? | Artikel 3 | Artikel 1 ; Artikel 5 ; Artikel 20 | Er steht unter den Grundrechten weit vorn. ; Er regelt die Gleichheit vor dem Gesetz. ; Eine Primzahl. | Die Juristin Elisabeth Selbert setzte den Satz 1949 im Parlamentarischen Rat durch.
W E | In Deutschland darf man mit 18 Jahren den Bundestag wählen. | wahr | Das aktive Wahlrecht für den Bundestag liegt seit 1970 bei 18 Jahren.
W M | Schwarzfahren ist in Deutschland nur eine Ordnungswidrigkeit. | falsch | Schwarzfahren ist nach § 265a StGB („Erschleichen von Leistungen“) eine Straftat.
W M | Einwegpfandflaschen erkennt man am Pfandlogo mit einer Flasche und einer Dose. | wahr | Das DPG-Logo zeigt einen Pfeil, eine Flasche und eine Dose — darauf gibt es 25 Cent Pfand.
W H | Die Sommerzeit wurde in Deutschland erstmals im Jahr 1980 eingeführt. | falsch | Schon 1916 gab es in Deutschland eine Sommerzeit — 1980 wurde sie nur wieder eingeführt.
S M | Wie viele Cent Pfand gibt es auf eine normale Mehrweg-Bierflasche aus Glas? | 8 | Cent | 20 | 1 | 50 | Deutlich weniger als bei Einwegflaschen. ; Bügelverschlussflaschen bringen mehr. ; Eine einstellige Zahl. | Mehrweg-Bierflaschen bringen 8 Cent, Bügelflaschen meist 15 Cent.
S U | Wie viele Buchstaben- bzw. Ziffernstellen darf ein deutsches Autokennzeichen höchstens haben (ohne Leerzeichen)? | 8 | Zeichen | 15 | 3 | 15 | Bis zu drei Buchstaben für den Ort. ; Dazu bis zu zwei Buchstaben und vier Ziffern. ; Mit E- oder H-Zusatz kommt noch eines hinzu. | Ohne Sonderzusatz sind höchstens acht Zeichen erlaubt — mit E oder H für Elektro- bzw. Oldtimerfahrzeuge gibt es ein neuntes.
O M | Sortiere diese Tonnen-Inhalte richtig zu — in der Reihenfolge Blau, Gelb, Braun, Schwarz. | Zeitungen = Blaue Tonne ; Joghurtbecher = Gelbe Tonne ; Kartoffelschalen = Braune Tonne ; Zigarettenkippen = Restmüll | Papier kommt in die erste. ; Verpackungen in die zweite. ; Bioabfälle in die dritte, der Rest zum Schluss. | Die Farben können je nach Kommune variieren, dieses Schema ist aber am weitesten verbreitet.
M E | Welche ZWEI dieser Nummern sind in Deutschland Notrufnummern? | 110 ; 112 | 111 ; 115 ; 118 ; 119 | Eine ist für die Polizei. ; Die andere für Feuerwehr und Rettungsdienst. ; Die 115 ist die Behördennummer. | Unter 115 erreicht man in vielen Regionen die Behördenauskunft — ein Notruf ist sie nicht.

@ dialekte_sprache
C E | Wie nennt man in Bayern ein Brötchen? | Semmel | Schrippe ; Rundstück ; Knifte | In Österreich heißt es genauso. ; In Berlin sagt man Schrippe. ; Es gibt sie auch als Brezen-Variante. | Die Semmel kommt vom lateinischen „simila“ für feines Weizenmehl.
C E | Wie heißt in Berlin der Berliner (das Fettgebäck)? | Pfannkuchen | Krapfen ; Kreppel ; Berliner | Man isst ihn zu Silvester und Fasching. ; In Bayern heißt er Krapfen. ; In Hessen Kreppel. | Was Berliner „Pfannkuchen“ nennen, heißt im Rest der Republik meist „Berliner“.
C E | Wie sagt man in Norddeutschland oft statt „Samstag“? | Sonnabend | Sonntag ; Samsdi ; Wochenend | Der Tag vor dem Sonntag. ; Das Wort bedeutet „Vorabend des Sonntags“. ; Es beginnt mit „Sonn“. | Sonnabend ist vor allem im Norden und Osten Deutschlands verbreitet.
C E | Was bedeutet das bayerische Wort „Schmarrn“ im übertragenen Sinn? | Unsinn | Wetter ; Kuchen ; Streit | „So ein ...!“ ; Es ist auch eine Süßspeise. ; Kaiser- ... ist berühmt. | Der Kaiserschmarrn ist eine zerrissene Pfannkuchen-Süßspeise — übertragen heißt Schmarrn „Quatsch“.
C E | Welche Sprache ist neben Deutsch in Teilen Schleswig-Holsteins als Minderheitensprache geschützt? | Dänisch | Schwedisch ; Polnisch ; Niederländisch | Die Grenze liegt im Norden. ; Flensburg hat eine große Minderheit. ; Das Nachbarland heißt Dänemark. | Deutschland erkennt vier nationale Minderheiten an: Dänen, Friesen, Sorben sowie Sinti und Roma.
C E | Was bedeutet „Tschüss“ ursprünglich? | Es kommt von „adieu“ | Es kommt von „Schuss“ ; Es kommt von „Tschechien“ ; Es kommt von „Tusch“ | Es stammt aus dem Französischen. ; Über das spanische „adiós“ bzw. flämische „adjus“ kam es zu uns. ; Wörtlich bedeutet das Ursprungswort „zu Gott“. | „Adieu“ wurde über „adjüs“ zu „tschüs“.
C M | Was bedeutet das hessische Wort „babbeln“? | Reden, schwätzen | Essen ; Schlafen ; Tanzen | „Hesse babbeln gern.“ ; Es hat mit dem Mund zu tun. ; Im Schwäbischen sagt man „schwätza“. | Babbeln ist im Hessischen das Alltagswort für sprechen und plaudern.
C E | Was bezeichnet man im Süden Deutschlands und in Österreich als „Erdapfel“? | Kartoffel | Rübe ; Zwiebel ; Topinambur | Sie wächst unter der Erde. ; In Frankreich heißt sie ähnlich: „pomme de terre“. ; Man macht Pommes daraus. | Auch „Grumbeere“ (Grundbirne) ist in der Pfalz und im Saarland ein Name für die Kartoffel.
C M | Was ist in Sachsen eine „Bemme“? | Ein belegtes Brot | Ein Bonbon ; Eine Beule ; Ein Bier | Man isst sie in der Pause. ; In Berlin heißt sie Stulle. ; Oft ist sie mit Butter bestrichen. | Die „Fettbemme“ ist ein Brot mit Schmalz.
C M | Was ist in Berlin ein „Kiez“? | Ein Wohnviertel | Ein Imbiss ; Eine Kneipe ; Ein Spielplatz | Man sagt: „mein ...“. ; Kreuzberg hat viele davon. ; Ursprünglich bezeichnete es eine Fischersiedlung. | Das Wort stammt aus dem Slawischen und meinte ursprünglich eine kleine Siedlung.
C M | Was bedeutet der Ausdruck „Tacheles reden“? | Offen und ehrlich sprechen | Laut schreien ; Leise flüstern ; Um den heißen Brei reden | Das Wort stammt aus dem Jiddischen. ; Es bedeutet „Zweck“ oder „Ziel“. ; Man redet Klartext. | Viele deutsche Wörter wie „Schlamassel“ oder „meschugge“ stammen aus dem Jiddischen.
C M | Welches bairische Wort testet man gern bei Zugezogenen, weil es kaum auszusprechen ist? | Oachkatzlschwoaf | Grüß Gott ; Servus ; Weißwurst | Es beschreibt einen Körperteil eines Tieres. ; Das Tier sammelt Nüsse. ; Auf Hochdeutsch: Eichhörnchenschwanz. | Das „Oachkatzlschwoaf“ gilt als klassischer bairischer Zungenbrecher.
C M | Was ist im Ruhrgebiet eine „Knifte“? | Eine Scheibe Brot | Ein Messer ; Eine Kneipe ; Ein Fußball | Bergleute nahmen sie in der Blechdose mit. ; In Berlin sagt man Stulle. ; In Sachsen Bemme. | Bergleute nahmen ihre Knifte früher mit unter Tage.
C H | Welche Organisation kürt jedes Jahr das „Wort des Jahres“? | Gesellschaft für deutsche Sprache | Duden-Redaktion ; Goethe-Institut ; Deutscher Bundestag | Sie sitzt in Wiesbaden. ; Die Wahl gibt es seit 1971. ; Die Abkürzung ist GfdS. | Das erste Wort des Jahres war 1971 „aufmüpfig“.
C H | Welche Sprache sprechen die Sorben in der Lausitz? | Eine westslawische Sprache | Einen deutschen Dialekt ; Eine germanische Sprache ; Eine baltische Sprache | Sie ist mit Tschechisch und Polnisch verwandt. ; Es gibt Ober- und Niedersorbisch. ; Straßenschilder sind dort oft zweisprachig. | Etwa 60.000 Sorben leben in Sachsen und Brandenburg.
C U | Was ist „Nordfriesisch“? | Eine eigene Sprache mit vielen Dialekten | Ein plattdeutscher Dialekt ; Eine Variante des Dänischen ; Ein Hamburger Stadtdialekt | Es wird an der Westküste und auf Inseln wie Föhr gesprochen. ; Es ist mit dem Englischen eng verwandt. ; Es hat zehn Dialekte. | Nordfriesisch hat nur noch einige Tausend Sprecher und gilt als bedroht.
C H | Wie nennt man scherzhaft die gedachte Kulturgrenze, die etwa entlang des Mains Nord- und Süddeutschland trennt? | Weißwurstäquator | Brezelgrenze ; Maingraben ; Bratwurstlinie | Südlich davon isst man eine bayerische Wurstspezialität. ; Es ist keine echte Grenze. ; Der Begriff spielt auf den Erdäquator an. | Die Grenze wird mal am Main, mal an der Donau verortet — ganz wie es gerade passt.
C U | Welches war 1971 das allererste „Wort des Jahres“? | aufmüpfig | Wirtschaftswunder ; Ostpolitik ; Umweltschutz | Es beschreibt Menschen, die aufbegehren. ; Es war die Zeit der Studentenbewegung. ; Es beginnt mit „auf“. | Seitdem wählt die Gesellschaft für deutsche Sprache jährlich Wörter, die die Debatten prägten.
C U | Welches Wort wurde 1991 zum ersten „Unwort des Jahres“ gekürt? | ausländerfrei | Wendehals ; Besserwessi ; Abwicklung | Es tauchte nach Ausschreitungen in Hoyerswerda auf. ; Es drückte Fremdenhass aus. ; Es endet auf „frei“. | Die Aktion „Unwort des Jahres“ will auf menschenverachtende Sprache aufmerksam machen.
W E | Plattdeutsch wird vor allem in Bayern gesprochen. | falsch | Plattdeutsch (Niederdeutsch) ist vor allem in Norddeutschland verbreitet und in acht Bundesländern als Regionalsprache geschützt.
W M | Im Schwäbischen bedeutet „schaffen“ vor allem „arbeiten“. | wahr | „Schaffe, schaffe, Häusle baue“ — das Motto der Schwaben.
W H | Das Wort „Handy“ für Mobiltelefon ist im Englischen genauso üblich wie im Deutschen. | falsch | Englischsprachige sagen „mobile“ oder „cell phone“ — „Handy“ ist ein deutscher Scheinanglizismus.
S H | Wie viele nationale Minderheiten erkennt Deutschland offiziell an? | 4 | Minderheiten | 25 | 1 | 15 | Dänen gehören dazu. ; Auch Friesen und Sorben. ; Weniger als fünf. | Anerkannt sind Dänen, Friesen, Sorben sowie deutsche Sinti und Roma.
O H | Sortiere diese Grußformeln von Nord nach Süd nach ihrer typischen Region. | Moin = Ostfriesland ; Tach = Ruhrgebiet ; Grüß Gott = Bayern ; Grüezi = Schweiz | Ganz oben grüßt man zu jeder Tageszeit gleich. ; Der Pott grüßt knapp. ; Die Schweizer sind ganz im Süden. | „Moin“ kommt vermutlich vom niederdeutschen „mooi“ für schön.
M M | Welche ZWEI dieser Wörter bezeichnen in deutschen Regionen ein belegtes Brot? | Stulle ; Bemme | Schrippe ; Semmel ; Weck ; Kreppel | Eines sagt man in Berlin. ; Das andere in Sachsen. ; Brötchen scheiden aus. | Schrippe, Semmel und Weck sind Brötchen, Kreppel ist ein Berliner.

@ made_in_germany
C E | Welche Firma aus Trossingen ist weltbekannt für Mundharmonikas? | Hohner | Steiff ; Yamaha ; Faber-Castell | Auch Akkordeons baut sie. ; Sie wurde 1857 gegründet. ; Die Firma sitzt in Baden-Württemberg. | Matthias Hohner machte die Mundharmonika zum Massenprodukt — Bob Dylan spielte später Hohner.
C E | Welches Gartenfigur-Symbol deutscher Gemütlichkeit wurde im 19. Jahrhundert in Thüringen in Serie hergestellt? | Gartenzwerg | Kuckucksuhr ; Nussknacker ; Räuchermann | Er trägt eine rote Zipfelmütze. ; Oft hat er eine Schubkarre oder Laterne. ; Gräfenroda gilt als Geburtsort. | In Gräfenroda begann um 1874 die Serienproduktion von Gartenzwergen aus Ton.
C M | Wer erfand 1854 in Berlin die nach ihm benannte runde Werbesäule? | Ernst Litfaß | Werner von Siemens ; Carl Bechstein ; Max Planck | Er war Drucker und Verleger. ; Die Säule trägt bis heute seinen Namen. ; Sie diente gegen wildes Plakatieren. | Die erste Litfaßsäule wurde am 1. Juli 1855 in Berlin aufgestellt.
C M | Aus welchem Thüringer Ort stammen die ersten gläsernen Christbaumkugeln? | Lauscha | Seiffen ; Meißen ; Sonneberg | Der Ort liegt im Thüringer Schiefergebirge. ; Er ist für Glasbläserei berühmt. ; Die Kugeln entstanden um 1847. | Arme Glasbläser in Lauscha ersetzten der Legende nach teure Äpfel durch gläserne Kugeln.
C E | In welchem Mittelgebirge wurde die Kuckucksuhr berühmt? | Schwarzwald | Harz ; Erzgebirge ; Allgäu | Dort gibt es auch Kirschtorte und Bollenhüte. ; In Triberg steht eine riesige Uhr. ; Es liegt in Baden-Württemberg. | Die Kuckucksuhr wurde im 18. Jahrhundert im Schwarzwald bekannt.
C M | Welche Firma aus Stein bei Nürnberg gilt als einer der ältesten Bleistifthersteller der Welt? | Faber-Castell | Staedtler ; Stabilo ; Lamy | Sie wurde 1761 gegründet. ; Ein Graf gehört zur Familie. ; Der Name ist ein Doppelname. | Faber-Castell produziert jährlich über zwei Milliarden Bleistifte.
C H | Aus welcher Region stammen die hölzernen Nussknacker und Räuchermännchen? | Erzgebirge | Schwarzwald ; Allgäu ; Eifel | Die Region liegt in Sachsen an der Grenze zu Tschechien. ; Früher gab es dort viel Bergbau. ; Seiffen ist das „Spielzeugdorf“. | Als der Bergbau zurückging, schnitzten viele Erzgebirger Holzspielzeug.
C U | Welches Unternehmen brachte 1936 den durchsichtigen Klebefilm „Tesa“ auf den Markt? | Beiersdorf | Henkel ; BASF ; Bayer | Die Firma sitzt in Hamburg. ; Sie stellt auch Nivea her. ; Der Name „Tesa“ geht auf eine Sekretärin zurück. | „Tesa“ kombiniert die Anfangsbuchstaben von Elsa Tesmer, einer Mitarbeiterin von Beiersdorf.
W M | Der Teddybär wurde von der Firma Steiff mitentwickelt. | wahr | Richard Steiff entwarf 1902 einen beweglichen Stoffbären — zeitgleich mit einem US-Hersteller.
O H | Sortiere diese deutschen Erfindungen nach ihrem Entstehungsjahr — die älteste zuerst. | Litfaßsäule = 1854 ; Automobil (Benz) = 1886 ; Tesafilm = 1936 ; MP3 = 1990er | Die Werbesäule kam zuerst. ; Das Auto folgte drei Jahrzehnte später. ; Das Audioformat ist die jüngste. | Das MP3-Format wurde am Fraunhofer-Institut in Erlangen entwickelt.

@ promis_boulevard
C M | Aus welcher Stadt stammte der Modeschöpfer Karl Lagerfeld? | Hamburg | Berlin ; München ; Düsseldorf | Die Stadt liegt an der Elbe. ; Er leitete jahrzehntelang Chanel. ; Er trug immer Sonnenbrille und weißen Zopf. | Lagerfeld (1933–2019) war über 35 Jahre Chefdesigner bei Chanel.
C U | Aus welcher niederrheinischen Stadt stammt das Supermodel Claudia Schiffer? | Rheinberg | Krefeld ; Moers ; Wesel | Sie wurde in einer Diskothek in Düsseldorf entdeckt. ; Die Stadt liegt im Kreis Wesel. ; Sie wurde durch Guess-Werbung berühmt. | Claudia Schiffer wurde 1987 mit 17 Jahren in Düsseldorf von einer Modelagentur angesprochen.

@ politik_bundestag
C E | In welcher Stadt sitzt der Deutsche Bundestag? | Berlin | Bonn ; Frankfurt ; Karlsruhe | Er tagt im Reichstagsgebäude. ; Er zog 1999 dorthin. ; Es ist die Hauptstadt. | Seit 1999 tagt der Bundestag im umgebauten Reichstagsgebäude.

@ tv_shows
C M | In welcher Stadt spielte die ARD-Serie „Lindenstraße“? | München | Köln ; Berlin ; Hamburg | Produziert wurde sie in Köln — gespielt hat sie woanders. ; Die Stadt liegt in Bayern. ; Die Serie lief von 1985 bis 2020. | Die fiktive Lindenstraße lag im Münchner Stadtteil Lindenhausen — gedreht wurde in Köln-Bocklemünd.
W M | Die ZDF-Krimiserie „Derrick“ wurde in über 100 Länder verkauft. | wahr | Derrick lief in rund 100 Ländern und gilt als einer der erfolgreichsten deutschen TV-Exporte.
O M | Sortiere diese TV-Klassiker nach ihrem Start — den ältesten zuerst. | Tagesschau = 1952 ; Tatort = 1970 ; Wetten, dass..? = 1981 ; Germany's Next Topmodel = 2006 | Die Nachrichten kamen zuerst. ; Der Sonntagskrimi folgte. ; Die Castingshow ist die jüngste. | „Wetten, dass..?“ startete 1981 mit Frank Elstner.

@ werbung_slogans
C M | Welche Marke warb mit dem Slogan „Nicht immer, aber immer öfter“? | Clausthaler | Beck's ; Bitburger ; Jever | Es ist ein alkoholfreies Bier. ; Der Slogan spielt auf gelegentlichen Verzicht an. ; Der Name erinnert an eine Harzer Bergstadt. | Clausthaler kam 1979 als eines der ersten alkoholfreien Biere Deutschlands auf den Markt.
W H | Der Werbespruch „Wir können alles. Außer Hochdeutsch.“ stammt aus Baden-Württemberg. | wahr | Die Imagekampagne des Landes startete 1999 und wurde zum geflügelten Wort.
@ feiertage_traditionen
O E | Sortiere diese Feiertage in ihrer Reihenfolge im Kalenderjahr. | Neujahr = 1. Januar ; Tag der Arbeit = 1. Mai ; Tag der Deutschen Einheit = 3. Oktober ; Erster Weihnachtstag = 25. Dezember | Das Jahr beginnt mit einem Feiertag. ; Im Mai wird die Arbeit gefeiert. ; Weihnachten kommt zuletzt. | Der Tag der Deutschen Einheit ist der einzige Feiertag, der durch Bundesrecht festgelegt ist.

@ politik_bundestag
M E | Welche ZWEI dieser Städte sind neben Berlin Stadtstaaten? | Hamburg ; Bremen | München ; Köln ; Frankfurt ; Stuttgart | Beide sind Hansestädte. ; Eine hat den größten Hafen Deutschlands. ; Die andere ist das kleinste Bundesland. | Das Land Bremen besteht aus Bremen und Bremerhaven.
M M | Welche ZWEI Parteien bildeten ab Dezember 2021 zusammen mit der SPD die „Ampel“-Koalition? | Bündnis 90/Die Grünen ; FDP | CDU ; CSU ; Die Linke ; AfD | Die Farben sind Rot, Gelb und Grün. ; Eine Partei ist grün. ; Die andere gelb. | Die Ampel-Koalition unter Olaf Scholz zerbrach im November 2024.
S U | Welche Nummer trägt der letzte Artikel des Grundgesetzes? | 146 | Artikel | 5 | 50 | 300 | Mehr als 100. ; Er regelt die Geltungsdauer des Grundgesetzes. ; Weniger als 150. | Artikel 146 sieht vor, dass eine vom Volk beschlossene Verfassung das Grundgesetz ablösen kann.

@ alltag_buerokratie
C U | Wie heißt das amtliche Blatt, in dem Bundesgesetze verkündet werden? | Bundesgesetzblatt | Bundesanzeiger ; Amtsblatt der EU ; Staatsanzeiger | Erst mit der Verkündung dort tritt ein Gesetz in Kraft. ; Es erscheint seit 2023 elektronisch. ; Der Name ist selbsterklärend. | Die Abkürzung lautet BGBl.

"""
