"""Extra questions: Essen & Trinken (format: see tools/content/merge_extra.py)."""
KAT = "essen_trinken"
REGION = "global"
DATA = r"""
@ obst_gemuese
C E | Welches Obst ist gelb, krumm und wird von Affen angeblich besonders geliebt? | Banane | Zitrone ; Mango ; Birne | Man schält es vor dem Essen. ; Es wächst in Stauden in den Tropen. ; Monkey Money ohne dieses Obst? Undenkbar! | Bananen wachsen an Stauden, die botanisch zu den Kräutern zählen.
C E | Welches Gemüse lässt einem beim Schneiden oft die Tränen in die Augen steigen? | Zwiebel | Gurke ; Karotte ; Zucchini | Es hat viele Schichten. ; Es gibt rote, weiße und gelbe Sorten. ; Es gehört zu den Lauchgewächsen. | Beim Schneiden entsteht ein schwefelhaltiges Gas, das die Augen reizt.
C E | Aus welchem Gemüse schnitzt man zu Halloween Fratzen? | Kürbis | Melone ; Kohlrabi ; Rote Bete | Er ist meist orange. ; Innen ist er hohl und voller Kerne. ; Er wird oft zu Suppe verarbeitet. | Ursprünglich schnitzte man in Irland Rüben — in Amerika setzte sich der Kürbis durch.
C E | Welche Frucht hat eine braune, haarige Schale und grünes Fruchtfleisch mit kleinen schwarzen Kernen? | Kiwi | Feige ; Avocado ; Passionsfrucht | Sie ist nach einem Vogel benannt. ; Viel kommt aus Neuseeland. ; Man kann sie halbieren und auslöffeln. | Die Kiwi stammt ursprünglich aus China und hieß früher „Chinesische Stachelbeere“.
C E | Welches Gemüse ist orange und soll gut für die Augen sein? | Karotte | Paprika ; Kürbis ; Süßkartoffel | Hasen knabbern sie gern. ; Sie wächst unter der Erde. ; Man nennt sie auch Möhre. | Karotten enthalten viel Beta-Carotin, aus dem der Körper Vitamin A bildet.
C E | Welche gelbe Frucht ist sehr sauer und wird oft für Limonade gepresst? | Zitrone | Banane ; Mango ; Ananas | Sie wächst am Baum. ; Man verziert damit Tee. ; Sie ist eine Zitrusfrucht. | Zitronen enthalten viel Zitronensäure und Vitamin C.
C E | Welche Frucht ist außen grün, innen rot und hat viele schwarze Kerne? | Wassermelone | Granatapfel ; Honigmelone ; Drachenfrucht | Sie ist groß und schwer. ; Sie besteht zu über 90 Prozent aus Wasser. ; Sie ist ein Sommer-Klassiker. | Wassermelonen gehören zu den Kürbisgewächsen.
C E | Welches Obst wächst in Trauben an Reben? | Weintrauben | Kirschen ; Pflaumen ; Johannisbeeren | Aus ihnen macht man Wein. ; Getrocknet heißen sie Rosinen. ; Sie wachsen an Hängen am Rhein und an der Mosel. | Getrocknete Weintrauben heißen je nach Sorte Rosinen, Sultaninen oder Korinthen.
C E | Welches Gemüse ist rund, grün und wird gern mit Kartoffelbrei und Fischstäbchen gegessen? | Erbsen | Linsen ; Bohnen ; Oliven | Sie stecken in einer Schote. ; Man kann sie tiefgekühlt kaufen. ; Sie sind klein und kugelig. | Erbsen gehören wie Bohnen und Linsen zu den Hülsenfrüchten.
C E | Nach welcher Frucht mit vielen roten Kernen ist die Handgranate benannt? | Granatapfel | Feige ; Quitte ; Maracuja | Ihr lateinischer Name bedeutet „körnig“. ; Sie ist innen voller roter Kerne. ; Sie hat eine ledrige rote Schale. | Die Granate erhielt ihren Namen, weil sie wie die Frucht mit „Körnern“ gefüllt war.
C E | Welches Gemüse wird in Deutschland wegen seiner Saison im Frühjahr auch „weißes Gold“ genannt? | Spargel | Chicorée ; Blumenkohl ; Kohlrabi | Die Saison endet traditionell am Johannistag. ; Er wird gestochen. ; Man isst ihn oft mit Sauce hollandaise. | Die Spargelsaison endet am 24. Juni, damit die Pflanzen sich bis zum nächsten Jahr erholen.
C M | Welches Gemüse ist eigentlich ein Stängel und wird trotzdem meist wie Obst zu Kuchen verarbeitet? | Rhabarber | Sellerie ; Fenchel ; Mangold | Seine Stangen sind oft rot. ; Die Saison endet ebenfalls am Johannistag. ; Die Blätter sind giftig. | Rhabarber enthält viel Oxalsäure — deshalb isst man ihn nur gekocht und die Blätter gar nicht.
C H | Welche Frucht gilt wegen ihres Geruchs als „Stinkfrucht“ und ist in Singapurs U-Bahn verboten? | Durian | Jackfrucht ; Papaya ; Litschi | Sie ist mit großen Stacheln besetzt. ; Man nennt sie auch „Königin der Früchte“ in Südostasien. ; Der Geruch erinnert an Zwiebeln und Käse. | Viele Hotels in Südostasien verbieten die Mitnahme von Durians aufs Zimmer.
C M | Aus welchem Land stammt ursprünglich die Kartoffel? | Aus Südamerika (Anden) | Aus Irland ; Aus China ; Aus Nordafrika | Die Inka bauten sie an. ; Spanische Seefahrer brachten sie nach Europa. ; Peru ist bis heute ein Kartoffelparadies. | In den Anden gibt es über 3000 Kartoffelsorten.
C M | Welche Nuss ist botanisch gesehen gar keine Nuss, sondern der Samen einer Steinfrucht? | Mandel | Haselnuss ; Walnuss ; Esskastanie | Sie ist mit Pfirsich und Kirsche verwandt. ; Aus ihr macht man Marzipan. ; Kalifornien produziert den Großteil. | Mandeln sind die Kerne einer Steinfrucht — wie beim Pfirsich, nur ohne süßes Fruchtfleisch.
C M | Welches Gemüse ist eine Kreuzung aus Kohl und Rübe und wird in Deutschland besonders geschätzt? | Kohlrabi | Pastinake ; Steckrübe ; Rote Bete | Der Name ist aus Kohl und Rübe zusammengesetzt. ; Man isst die verdickte Sprossknolle. ; Es gibt ihn hellgrün und violett. | Kohlrabi gilt im Ausland als typisch deutsches Gemüse — im Englischen sagt man sogar „kohlrabi“.
C E | Welche Frucht wächst an Palmen und hat innen Wasser und weißes Fruchtfleisch? | Kokosnuss | Dattel ; Mango ; Papaya | Sie hat eine harte, haarige Schale. ; Sie kann übers Meer treiben und keimen. ; Aus dem Fleisch presst man Öl und Milch. | Botanisch ist die Kokosnuss eine Steinfrucht, keine echte Nuss.
C M | Welche dunkelblaue, längliche Steinfrucht ist Grundlage für Powidl und den bayerischen Datschi-Kuchen? | Zwetschge | Mirabelle ; Schlehe ; Aprikose | Sie wird im Spätsommer geerntet. ; Sie ist eine Unterart der Pflaume. ; Ihr Kern löst sich gut vom Fruchtfleisch. | Zwetschgen haben festeres Fleisch als runde Pflaumen — ideal zum Backen.
C U | Wie heißt die festkochende, krumm gewachsene Kartoffelsorte aus Oberfranken? | Bamberger Hörnla | Linda ; Sieglinde ; Annabelle | Sie ist EU-weit geschützt. ; Sie stammt aus einer fränkischen Domstadt. ; Der Name beschreibt ihre gebogene Form. | Die kleinen Bamberger Hörnla schmecken nussig und gelten als Delikatesse für Kartoffelsalat.
C U | Aus welchen zwei Zitrusfrüchten entstand die Grapefruit durch natürliche Kreuzung? | Orange und Pampelmuse | Zitrone und Limette ; Mandarine und Kumquat ; Bergamotte und Zitrone | Sie entstand im 18. Jahrhundert auf Barbados. ; Eine Elternfrucht ist riesig und dickschalig. ; Die andere presst man oft zum Frühstück. | Die Grapefruit wurde im 18. Jahrhundert auf Barbados entdeckt — eine Zufallskreuzung aus Orange und Pampelmuse.
C H | Welches Land ist der weltweit größte Avocado-Produzent? | Mexiko | Peru ; Spanien ; Kenia | Dort liegt das Ursprungsgebiet der Avocado. ; Der Bundesstaat Michoacán ist das Zentrum. ; Das Land grenzt an die USA. | Mexiko erntet rund ein Drittel aller Avocados weltweit.
C H | Welches Gemüse gilt botanisch als Frucht, weil es aus der Blüte entsteht und Samen enthält? | Gurke | Möhre ; Spinat ; Porree | Sie ist lang und grün. ; Sie gehört zu den Kürbisgewächsen. ; In sauer eingelegter Form liegt sie in Spreewald-Gläsern. | Gurken, Tomaten, Paprika und Kürbisse sind botanisch Früchte.
C H | Wie heißen die Tomaten, die an einem Rispenstiel wachsen und im Supermarkt oft noch daran hängen? | Rispentomaten | Kirschtomaten ; Fleischtomaten ; Flaschentomaten | Mehrere Früchte hängen an einem Stiel. ; Der Stiel verströmt den typischen Tomatenduft. ; Der Name nennt den Blütenstand. | Der Duft von Rispentomaten kommt vor allem vom grünen Stiel, nicht von der Frucht.
C U | Welches Land ist der weltweit größte Bananenproduzent? | Indien | Ecuador ; Costa Rica ; Brasilien | Das Land hat über eine Milliarde Einwohner. ; Es verzehrt fast alles selbst. ; Ecuador ist dagegen größter Exporteur. | Indien produziert rund ein Viertel aller Bananen weltweit, exportiert aber kaum.
C H | Aus welcher Pflanze wird Tofu hergestellt? | Sojabohne | Kichererbse ; Reis ; Lupine | Es ist eine Hülsenfrucht. ; Auch Sojasoße entsteht daraus. ; Der Quark aus ihrer „Milch“ wird gepresst. | Tofu entsteht, indem Sojamilch gerinnt — ähnlich wie bei der Käseherstellung.
C U | Welche Zitrusfrucht ist Hauptzutat der englischen Orangenmarmelade und schmeckt roh sehr bitter? | Bitterorange (Pomeranze) | Blutorange ; Mandarine ; Kumquat | Sie heißt auch Sevilla-Orange. ; In Spanien steht sie als Straßenbaum. ; Aus ihren Blüten gewinnt man Neroliöl. | Die berühmte Marmalade wird traditionell aus Sevilla-Bitterorangen gekocht.
C U | Welche Frucht gewinnt man von einer Kaktusart und nennt sie auch „Kaktusfeige“? | Opuntie | Pitahaya ; Feige ; Kaki | Sie ist mit feinen Stacheln besetzt. ; Man findet sie rund ums Mittelmeer. ; Sie ist im mexikanischen Wappen abgebildet. | Im Wappen Mexikos sitzt ein Adler mit Schlange auf einem Opuntien-Kaktus.
C U | Welche Pflanze liefert Kapern, die man eingelegt kauft? | Den Kapernstrauch — Kapern sind Blütenknospen | Einen Wacholderbusch — es sind Beeren ; Eine Zwiebelpflanze — es sind Brutzwiebeln ; Eine Senfpflanze — es sind Samen | Es sind noch geschlossene Knospen. ; Der Strauch wächst im Mittelmeerraum in Mauerritzen. ; Die größeren Früchte heißen Kapernäpfel. | Kapern werden als Knospen gepflückt und in Salz oder Essig eingelegt.
W E | Erdnüsse wachsen unter der Erde. | wahr | Nach der Befruchtung bohren sich die Fruchtstiele in den Boden, wo die Hülsen reifen.
W E | Ananas wachsen an hohen Bäumen. | falsch | Ananas wachsen auf dem Boden aus der Mitte einer niedrigen, stacheligen Staude.
W M | Paprika enthält mehr Vitamin C als eine Zitrone. | wahr | Rote Paprika enthält etwa zwei- bis dreimal so viel Vitamin C wie Zitronensaft.
W M | Grüne und rote Paprika sind unterschiedliche Pflanzenarten. | falsch | Grüne Paprika ist meist einfach unreif — reif wird sie gelb, orange oder rot.
W H | Cashewkerne werden fast nie in der Schale verkauft, weil die Schale ein hautreizendes Öl enthält. | wahr | Die Schale enthält Stoffe, die mit dem Gift des Giftefeus verwandt sind — Cashews werden deshalb erhitzt und geschält.
W H | Himbeeren sind botanisch gesehen Sammelsteinfrüchte. | wahr | Jede kleine Kugel der Himbeere ist ein eigenes Steinfrüchtchen mit Kern.
S M | Wie viel Prozent Wasser enthält eine Wassermelone ungefähr? | 92 | Prozent | 5 | 50 | 99 | Mehr als 90 Prozent. ; Der Name verrät viel. ; Gurken liegen sogar noch etwas höher. | Wassermelonen bestehen zu rund 92 Prozent aus Wasser.
S U | Wie viele Kilogramm Kartoffeln isst ein Mensch in Deutschland durchschnittlich pro Jahr (inkl. Pommes, Chips)? | 60 | kg | 25 | 5 | 300 | Deutlich mehr als 30. ; Weniger als 100. ; Etwa ein Kilo pro Woche. | Der Pro-Kopf-Verbrauch liegt je nach Jahr bei rund 55 bis 65 Kilogramm.
O M | Sortiere diese Früchte nach ihrem typischen Gewicht — die leichteste zuerst. | Kirsche = ≈ 8 g ; Pflaume = ≈ 40 g ; Apfel = ≈ 180 g ; Honigmelone = ≈ 1,5 kg | Die leichteste hat einen Stiel und einen Kern. ; Die Pflaume ist kleiner als der Apfel. ; Die schwerste muss man mit beiden Händen tragen. | Ein durchschnittlicher Apfel wiegt etwa 150 bis 200 Gramm.
O H | Sortiere diese Obstsorten nach ihrem Vitamin-C-Gehalt pro 100 g — den niedrigsten zuerst. | Banane = ≈ 10 mg ; Orange = ≈ 50 mg ; Kiwi = ≈ 80 mg ; Sanddorn = ≈ 450 mg | Die Tropenfrucht mit Schale ist Schlusslicht. ; Die Kiwi schlägt die Orange. ; Die kleine orange Ostseebeere ist Vitamin-C-Rekordhalter. | Sanddorn gehört zu den Vitamin-C-reichsten heimischen Früchten.
M E | Welche ZWEI dieser Lebensmittel sind Obst? | Apfel ; Kirsche | Karotte ; Brokkoli ; Spinat ; Kartoffel | Beide wachsen an Bäumen. ; Einer ist rot und hat einen Stiel. ; Gemüse scheidet aus. | Äpfel und Kirschen wachsen an Bäumen und zählen klar zum Obst.
M M | Welche ZWEI dieser Früchte zählen zu den Zitrusfrüchten? | Limette ; Pampelmuse | Kiwi ; Mango ; Litschi ; Papaya | Beide sind sauer. ; Eine ist klein und grün. ; Die andere ist riesig und gelb. | Zu den Zitrusfrüchten zählen Orange, Zitrone, Limette, Grapefruit, Pampelmuse und Mandarine.
M H | Welche ZWEI dieser Gemüse sind botanisch Früchte? | Aubergine ; Zucchini | Spinat ; Lauch ; Rote Bete ; Blumenkohl | Beide entstehen aus Blüten und enthalten Samen. ; Eine ist ein Nachtschattengewächs. ; Die andere ist ein Kürbisgewächs. | Blattgemüse, Stängel, Wurzeln und Blütenstände sind keine Früchte im botanischen Sinn.

@ fastfood_marken
C E | Wofür steht die Abkürzung KFC? | Kentucky Fried Chicken | King Fresh Chicken ; Kansas Food Company ; Kitchen Fried Chips | Ein US-Bundesstaat steckt drin. ; Es geht um frittiertes Geflügel. ; Gründer war ein „Colonel“. | Colonel Harland Sanders begann in den 1930ern in Kentucky mit seinem Brathähnchen.
C E | Wie heißt der rote Clown, der lange das Maskottchen von McDonald's war? | Ronald McDonald | Bozo der Clown ; Krusty ; Pennywise | Er trägt einen gelben Overall. ; Sein Vorname beginnt mit R. ; Sein Nachname ist der der Kette. | Ronald McDonald trat 1963 zum ersten Mal auf — gespielt von Willard Scott.
C E | Wie heißt die rote Tomatensauce, die man in Flaschen zu Pommes bekommt? | Ketchup | Mayonnaise ; Senf ; Remoulade | Sie ist rot. ; Heinz ist eine bekannte Marke. ; Oft steht sie neben der Mayo. | Die bekannteste Flasche ist die von Heinz mit der „57“ auf dem Etikett.
C E | Aus welchem Land stammt der Energy-Drink Red Bull? | Österreich | Deutschland ; Thailand ; USA | Die Firma sitzt in Fuschl am See. ; Gründer war Dietrich Mateschitz. ; Das Land hat Wien als Hauptstadt. | Vorbild war der thailändische Drink „Krating Daeng“ — roter Bulle.
C M | In welchem Land wurde das Getränk Fanta erfunden? | Deutschland | USA ; Italien ; Spanien | Es entstand im Zweiten Weltkrieg. ; Coca-Cola-Sirup war damals knapp. ; Der Name kommt von „Fantasie“. | Die deutsche Coca-Cola-Tochter entwickelte Fanta 1940 aus Molke und Apfeltrester.
C M | In welchem US-Bundesstaat wurde Pepsi-Cola erfunden? | North Carolina | Georgia ; Texas ; Kalifornien | Der Erfinder war ein Apotheker. ; Die Stadt heißt New Bern. ; Nicht der Staat von Coca-Cola. | Caleb Bradham nannte das Getränk 1893 zuerst „Brad's Drink“.
C H | Wer brachte 1886 die berühmte Würzsauce aus der Schweiz auf den Markt, deren Flasche braun und eckig ist? | Julius Maggi | Carl Heinrich Knorr ; Henri Nestlé ; Justus von Liebig | Die Würze trägt seinen Namen. ; Das Liebstöckel heißt deshalb auch nach ihr. ; Er stammte aus Kemptthal. | Liebstöckel heißt umgangssprachlich „Maggikraut“, weil es ähnlich duftet — enthalten ist es in der Würze aber nicht.
C H | In welcher Stadt gründete Carl Heinrich Knorr 1838 seine Firma, heute bekannt für Suppen? | Heilbronn | Hamburg ; Stuttgart ; Bremen | Die Stadt liegt am Neckar. ; Sie ist in Baden-Württemberg. ; Sie ist für Wein und Salzbergwerke bekannt. | Knorr gehört heute zum Konzern Unilever.
C M | Wie nennt die britische Zeitschrift „The Economist“ ihren Vergleich der Kaufkraft über Burgerpreise? | Big-Mac-Index | Whopper-Rate ; Burger-Barometer ; Fast-Food-Faktor | Er erscheint seit 1986. ; Er vergleicht einen weltweit einheitlichen Burger. ; Der Burger stammt von McDonald's. | Der Big-Mac-Index vergleicht Burgerpreise, um Wechselkurse spielerisch zu bewerten.
C H | Welche deutsche Fisch-Restaurantkette wurde 1896 in Bremen gegründet? | Nordsee | Gosch ; Fischer's Fritz ; Seeteufel | Sie ist nach einem Meer benannt. ; Ursprünglich war sie eine Hochseefischerei. ; Sie verkauft Backfisch-Brötchen. | Die „Deutsche Dampffischerei-Gesellschaft Nordsee“ eröffnete ihre ersten Fischläden schon Anfang des 20. Jahrhunderts.
C M | Nach wem ist die Fast-Food-Kette Wendy's benannt? | Nach der Tochter des Gründers | Nach der Frau des Gründers ; Nach einer Comicfigur ; Nach einer Stadt in Ohio | Das Logo zeigt ein Mädchen mit roten Zöpfen. ; Gründer war Dave Thomas. ; Ihr echter Spitzname war Wendy. | Dave Thomas benannte die Kette 1969 nach seiner Tochter Melinda Lou, genannt Wendy.
C H | In welcher Stadt soll der Döner im Brot in den frühen 1970ern erfunden worden sein? | Berlin | Istanbul ; Hamburg ; Köln | Kadir Nurman soll ihn am Bahnhof Zoo verkauft haben. ; Die Stadt hat eine große türkische Gemeinde. ; Es ist die deutsche Hauptstadt. | Der Döner Kebab im Fladenbrot gilt als deutsch-türkische Erfindung — der genaue Erfinder ist umstritten.
C H | In welcher US-Stadt gründete Henry John Heinz 1869 sein Unternehmen? | Pittsburgh | Chicago ; Detroit ; Boston | Die Stadt liegt in Pennsylvania. ; Die Footballmannschaft heißt Steelers. ; Das Stadion hieß lange „Heinz Field“. | Heinz verkaufte zuerst geriebenen Meerrettich — Ketchup kam 1876 dazu.
C U | Auf welcher Insel in Louisiana wird die Tabasco-Sauce seit 1868 hergestellt? | Avery Island | Grand Isle ; Key West ; Nantucket | Die Insel ist ein Salzdom. ; Dort lebt auch eine Vogelkolonie. ; Der Name ist ein Nachname. | Tabasco reift bis zu drei Jahre in Eichenfässern, bevor Essig dazukommt.
C H | Wie heißt der Burger von McDonald's mit zwei Patties, „Spezialsauce“ und drei Brötchenhälften? | Big Mac | Royal TS ; Quarter Pounder ; McRib | Er kam 1968 landesweit auf den Markt. ; Er hat eine Brötchenmitte. ; Ein Index ist nach ihm benannt. | Der Big Mac wurde 1967 von Franchisenehmer Jim Delligatti erfunden.
C U | Welcher Apotheker aus Bielefeld verkaufte ab 1891 Backpulver in kleinen Tütchen? | August Oetker | Hermann Bahlsen ; Heinrich Kaiser ; Rudolf Wild | Die Tütchen hießen „Backin“. ; Er trug einen Doktortitel. ; Die Firma ist heute ein Weltkonzern. | Dr. August Oetker verkaufte das portionierte Backpulver „Backin“ — genau richtig für ein Pfund Mehl.
C U | Wie hieß die DDR-Cola, die heute wieder im Handel ist? | Vita Cola | Club-Cola ; Ost-Cola ; Spree-Cola | Sie stammt aus Thüringen. ; Sie schmeckt leicht nach Zitrone. ; Der Name bedeutet „Leben“. | Vita Cola wurde 1958 erfunden und ist heute in Ostdeutschland Marktführer unter den Colas.
W E | Die Kaffee-Kette Starbucks stammt aus Italien. | falsch | Starbucks wurde 1971 in Seattle (USA) gegründet — inspiriert von italienischen Espressobars.
W M | Red Bull wurde nach dem Vorbild eines thailändischen Energy-Drinks entwickelt. | wahr | Dietrich Mateschitz lernte in Thailand den Drink „Krating Daeng“ kennen und passte ihn an.
W H | Die erste Fanta enthielt Orangen. | falsch | Die Kriegs-Fanta von 1940 bestand aus Molke, Apfeltrester und was sonst verfügbar war — Orangen gab es kaum.
S H | In welchem Jahr wurde Burger King gegründet? | 1954 | Jahr | 3 | 1900 | 2000 | Mitte der Fünfziger. ; Ein Jahr vor dem Einstieg von Ray Kroc bei McDonald's. ; Das Jahr des „Wunders von Bern“. | Der Vorläufer „Insta-Burger King“ entstand 1953 in Jacksonville, Burger King selbst 1954 in Miami.
O M | Sortiere diese Getränkemarken nach ihrem Erfindungsjahr — die älteste zuerst. | Coca-Cola = 1886 ; Pepsi = 1893 ; Fanta = 1940 ; Red Bull = 1987 | Die älteste kommt aus Atlanta. ; Der ewige Rivale folgte wenige Jahre später. ; Der Energy-Drink ist der jüngste. | Red Bull kam 1987 in Österreich auf den Markt.
M M | Welche ZWEI dieser Marken stammen ursprünglich aus der Schweiz? | Maggi ; Ovomaltine | Knorr ; Dr. Oetker ; Nutella ; Heinz | Eine ist eine Würze. ; Die andere ein Malzgetränk. ; Nutella ist italienisch, Heinz amerikanisch. | Ovomaltine entstand 1904 in Bern; Maggi 1886 in Kemptthal bei Zürich.

@ kochen_zutaten
C E | Mit welchem Küchengerät schlägt man Sahne steif? | Schneebesen bzw. Rührgerät | Nudelholz ; Sieb ; Pfannenwender | Es hat viele Drahtschlaufen. ; Man benutzt es auch für Eischnee. ; Elektrisch geht es schneller. | Sahne wird steif, wenn Fetttröpfchen Luftbläschen einschließen — am besten gut gekühlt.
C E | Was gibt man ins Wasser, damit Nudeln nicht fad schmecken? | Salz | Zucker ; Essig ; Mehl | Es ist weiß und körnig. ; Italiener sagen, das Wasser soll schmecken wie das Meer. ; Es liegt neben dem Pfeffer. | Salz im Kochwasser würzt die Nudeln von innen.
C E | Wie heißt das italienische Gericht aus Teigboden mit Tomaten und Käse, das im Ofen gebacken wird? | Pizza | Lasagne ; Risotto ; Calzone | Ein Klassiker heißt Margherita. ; Sie wird in Stücke geschnitten. ; Neapel gilt als ihre Heimat. | Die Pizza Margherita soll 1889 zu Ehren der Königin Margherita kreiert worden sein.
C E | Welche Zutat macht Pfannkuchen, Rührei und Kuchen gleichermaßen möglich — sie kommt von Hühnern? | Eier | Milch ; Butter ; Mehl | Sie haben eine Schale. ; Innen gibt es Gelb und Weiß. ; Zu Ostern werden sie bemalt. | Ein Hühnerei der Größe M wiegt etwa 53 bis 63 Gramm.
C E | Bei welcher Temperatur gart man Nudeln? | Im sprudelnd kochenden Wasser (ca. 100 °C) | Bei 60 °C im Ofen ; In lauwarmem Wasser ; Im Kühlschrank quellen lassen | Das Wasser soll blubbern. ; Es ist der Siedepunkt. ; Deckel runter, damit es nicht überkocht. | Italiener kochen Pasta „al dente“ — bissfest im sprudelnden Salzwasser.
C E | Was bedeutet der italienische Ausdruck „al dente“ bei Nudeln? | Bissfest | Sehr weich ; Mit Knoblauch ; Mit Soße serviert | Wörtlich: „für den Zahn“. ; Die Nudeln haben noch leichten Biss. ; Das Gegenteil wäre verkocht. | Al dente gekochte Nudeln haben einen niedrigeren glykämischen Index als verkochte.
C E | Welches Gewürz wird aus der Rinde eines Baumes gewonnen? | Zimt | Nelken ; Pfeffer ; Vanille | Es rollt sich beim Trocknen zu Stangen. ; Es gehört auf Milchreis. ; Ceylon und Cassia sind Sorten. | Zimt ist die getrocknete Innenrinde des Zimtbaums.
C M | Welches Gewürz sind getrocknete Blütenknospen? | Gewürznelken | Kardamom ; Muskat ; Kümmel | Sie sehen aus wie kleine Nägel. ; Man steckt sie in Orangen oder Zwiebeln. ; Sie gehören in Glühwein. | Der Name „Nelke“ kommt vom mittelhochdeutschen „negelkin“, kleiner Nagel.
C E | Welche Soße gehört klassisch zu Spargel? | Sauce hollandaise | Sauce béarnaise ; Bolognese ; Aioli | Sie ist aus Eigelb und Butter aufgeschlagen. ; Sie ist gelb. ; Ihr Name deutet auf ein Nachbarland. | Die Hollandaise ist eine der fünf klassischen französischen Grundsaucen.
C H | Wie nennt man die französische Kochtechnik, Speisen in viel Fett bei niedriger Temperatur zu garen? | Confit | Flambieren ; Pochieren ; Gratinieren | Entenkeulen werden oft so zubereitet. ; Das Fett dient auch zum Konservieren. ; Das Wort kommt von „confire“, einlegen. | Beim Confit gart man z. B. Ente langsam im eigenen Fett.
C M | Was macht man beim „Flambieren“? | Man übergießt Speisen mit Alkohol und zündet ihn an | Man backt sie bei Oberhitze ; Man räuchert sie ; Man friert sie schockartig | Es gibt eine sichtbare Flamme. ; Crêpes Suzette werden so serviert. ; Der Name kommt vom französischen Wort für Flamme. | Beim Flambieren verbrennt der Alkohol größtenteils, das Aroma bleibt.
C H | Welches Getreide steckt in Bulgur? | Weizen | Reis ; Hirse ; Gerste | Er wird vorgekocht und geschrotet. ; Er ist Basis für Taboulé. ; Aus diesem Getreide backt man auch Brot. | Bulgur wird aus Hartweizen gekocht, getrocknet und geschrotet.
C H | Welches Gewürz verleiht der ungarischen Küche ihre rote Farbe? | Paprikapulver | Kurkuma ; Safran ; Zimt | Es gibt es edelsüß und rosenscharf. ; Es wird aus getrockneten Schoten gemahlen. ; Gulasch wäre ohne es blass. | Ungarn gilt als Paprika-Land — besonders die Regionen um Szeged und Kalocsa.
C H | Aus welchem Land stammt die Sauce Worcestershire? | England | Indien ; USA ; Irland | Sie ist nach einer Grafschaft benannt. ; Die Apotheker hießen Lea und Perrins. ; Sie enthält Sardellen. | Lea & Perrins brachten die Sauce 1837 in Worcester auf den Markt.
C U | Wie heißt die Mischung aus Zwiebeln, Karotten und Sellerie, die Basis vieler französischer Saucen ist? | Mirepoix | Roux ; Bouquet garni ; Duxelles | In Italien heißt es Soffritto. ; Es ist nach einem Herzog benannt. ; Das Gemüse wird gewürfelt. | Die Mirepoix wurde nach dem Herzog von Lévis-Mirepoix aus dem 18. Jahrhundert benannt.
C U | Welche Temperatur hat ein medium gegartes Rindersteak ungefähr im Kern? | 55–58 °C | 40–42 °C ; 70–72 °C ; 85–88 °C | Rare liegt darunter. ; Well done liegt bei über 65 Grad. ; Innen ist es noch rosa. | Als Faustregel: rare ca. 50 °C, medium ca. 56 °C, well done über 65 °C.
W E | Kartoffeln kann man roh gut essen. | falsch | Rohe Kartoffeln enthalten schwer verdauliche Stärke und etwas Solanin — man isst sie gekocht, gebraten oder frittiert.
W M | Beim Nudelkochen verhindert Öl im Wasser zuverlässig, dass die Nudeln verkleben. | falsch | Öl schwimmt oben; gegen Verkleben hilft Umrühren und genug Wasser.
W H | Vanille ist nach Safran eines der teuersten Gewürze der Welt. | wahr | Vanilleblüten müssen oft von Hand bestäubt werden — das macht die Schoten sehr teuer.
S M | Wie viel Gramm Mehl sind in einem klassischen Pfund Mehl? | 500 | Gramm | 5 | 100 | 1000 | Ein halbes Kilogramm. ; Es ist eine runde Zahl. ; Genau die Mitte zwischen 0 und 1000. | Das Pfund ist in Deutschland keine amtliche Einheit mehr, steht umgangssprachlich aber für 500 Gramm.
O M | Sortiere diese Garstufen eines Steaks — von der rohesten zur am stärksten durchgegarten. | Rare = ≈ 50 °C ; Medium rare = ≈ 54 °C ; Medium = ≈ 57 °C ; Well done = ≈ 68 °C | Englisch für „selten“ steht am Anfang. ; Medium rare liegt vor medium. ; „Gut gemacht“ ist am Ende. | Die Kerntemperatur entscheidet über die Garstufe.
M M | Welche ZWEI dieser Zutaten lassen Teig aufgehen? | Hefe ; Backpulver | Salz ; Zucker ; Speisestärke ; Gelatine | Einer ist ein Pilz. ; Der andere ein Pulver im Tütchen. ; Beide erzeugen Gasbläschen. | Hefe und Backpulver bilden Kohlendioxid, das den Teig lockert.

@ deutsche_kueche de
C E | Wie heißt das panierte Schnitzel, das eigentlich aus Kalbfleisch sein muss? | Wiener Schnitzel | Jägerschnitzel ; Zigeunerschnitzel ; Cordon bleu | Es ist nach einer Hauptstadt benannt. ; Aus Schweinefleisch heißt es „nach Wiener Art“. ; Man serviert es mit Zitrone. | Nur aus Kalbfleisch darf es „Wiener Schnitzel“ heißen.
C E | Wie nennt man in Norddeutschland ein Brötchen? | Rundstück | Weckle ; Semmel ; Schrippe | Der Name beschreibt die Form. ; In Berlin sagt man Schrippe. ; In Bayern Semmel. | Brötchen heißen je nach Region Rundstück, Semmel, Weckle, Schrippe oder Weck.
C E | Welcher Kuchen aus dem Schwarzwald besteht aus Schokobiskuit, Kirschen, Sahne und Kirschwasser? | Schwarzwälder Kirschtorte | Frankfurter Kranz ; Bienenstich ; Donauwelle | Sie ist nach einer Mittelgebirgsregion benannt. ; Oben liegen Schokoraspel. ; Kirschwasser darf nicht fehlen. | Die Schwarzwälder Kirschtorte muss laut Leitsätzen deutlich nach Kirschwasser schmecken.
C M | Was ist ein „Frankfurter Kranz“? | Ein ringförmiger Buttercremekuchen mit Krokant | Eine Wurstspezialität ; Ein Kräuterkranz für Grüne Soße ; Ein Laugengebäck | Er hat die Form einer Krone. ; Oben sind Kirschen. ; Außen ist er mit Krokant bedeckt. | Der Kranz soll an die Kaiserkrone der Krönungsstadt Frankfurt erinnern.
C H | Welche Stadt ist für ihre „Printen“, ein würziges Lebkuchengebäck, berühmt? | Aachen | Nürnberg ; Lübeck ; Dresden | Karl der Große regierte dort. ; Die Stadt liegt an der Grenze zu Belgien und den Niederlanden. ; Ihr Dom ist UNESCO-Welterbe. | Aachener Printen sind EU-weit als geografische Angabe geschützt.
W H | Bayerischer Leberkäse enthält traditionell Leber. | falsch | Bayerischer Leberkäs besteht aus Rind- und Schweinebrät — nur „Stuttgarter Leberkäse“ muss Leber enthalten.
S M | Bei wie viel Grad Celsius backt man einen klassischen Rührkuchen im Umluftofen ungefähr? | 160 | °C | 10 | 50 | 300 | Bei Ober- und Unterhitze sind es etwa 20 Grad mehr. ; Weniger als 200. ; Mehr als 150. | Umluft verteilt die Wärme besser, daher reichen rund 160 °C statt 180 °C.

@ internationale_kueche
C E | Aus welchem Land stammen Tacos und Burritos? | Mexiko | Spanien ; Brasilien ; Argentinien | Man isst sie mit Tortillas. ; Die Hauptstadt heißt genauso wie das Land. ; Das Land liegt südlich der USA. | Burritos kommen eher aus dem Norden Mexikos und wurden in den USA populär.
C E | Wie heißt die griechische Joghurtsoße mit Gurke und Knoblauch? | Tsatsiki | Hummus ; Taramas ; Skordalia | Sie wird kalt serviert. ; Sie passt zu Gyros und Souvlaki. ; In der Türkei heißt ein ähnliches Gericht Cacık. | Für gutes Tsatsiki wird die geraspelte Gurke gesalzen und ausgedrückt.
C H | Aus welchem Land stammt das Gericht „Poutine“ aus Pommes, Käsebruch und Bratensoße? | Kanada | USA ; Belgien ; Irland | Es stammt aus der französischsprachigen Provinz. ; Die Provinz heißt Québec. ; Das Land hat ein Ahornblatt auf der Flagge. | Poutine entstand in den 1950er-Jahren in ländlichen Imbissen Québecs.
W M | Der Cappuccino ist nach dem Kapuzinerorden benannt. | wahr | Die Farbe des Getränks erinnert an die braunen Kutten der Kapuzinermönche.
O U | Sortiere diese Länder nach ihrem Pro-Kopf-Bierkonsum — den niedrigsten zuerst. | Italien = ≈ 35 Liter ; Deutschland = ≈ 90 Liter ; Österreich = ≈ 100 Liter ; Tschechien = ≈ 130 Liter | Das Weinland trinkt am wenigsten Bier. ; Deutschland liegt knapp hinter seinem Alpennachbarn. ; Pilsener-Weltmeister ist ein östlicher Nachbar. | Tschechien führt seit Jahrzehnten die Weltrangliste beim Pro-Kopf-Bierkonsum an.

@ bier_wein_getraenke
C E | Aus welcher Frucht wird Wein gemacht? | Weintrauben | Äpfeln ; Kirschen ; Pflaumen | Sie wachsen an Reben. ; Getrocknet heißen sie Rosinen. ; Es gibt rote und weiße. | Rotwein bekommt seine Farbe von den Schalen roter Trauben.
C M | Welches Getränk ist in Großbritannien als „Ale“ bekannt? | Obergäriges Bier | Apfelwein ; Whisky ; Tee mit Milch | Es wird in Pubs gezapft. ; Die Hefe schwimmt oben. ; Es ist ein Bier. | Ales werden mit obergäriger Hefe bei wärmeren Temperaturen vergoren.
S H | Wie viele Liter fasst ein klassischer Maßkrug auf dem Oktoberfest? | 1 | Liter | 20 | 0.2 | 5 | Mehr als ein halber. ; Er ist aus Glas. ; Eine ganze Einheit. | Eine Maß ist ein Liter — der Verein gegen betrügerisches Einschenken kontrolliert das.
@ internationale_kueche
M E | Welche ZWEI dieser Gerichte stammen aus Italien? | Lasagne ; Risotto | Paella ; Sushi ; Gulasch ; Tacos | Eines besteht aus Nudelplatten. ; Das andere aus Reis. ; Spanien, Japan, Ungarn und Mexiko scheiden aus. | Risotto kocht man klassisch mit Arborio- oder Carnaroli-Reis.
M U | Welche ZWEI dieser Käse werden traditionell aus Schafsmilch hergestellt? | Roquefort ; Pecorino | Gouda ; Emmentaler ; Camembert ; Parmesan | Einer ist ein französischer Blauschimmelkäse. ; Der andere ein italienischer Hartkäse. ; „Pecora“ heißt Schaf. | Die übrigen vier werden aus Kuhmilch gemacht.
O M | Sortiere diese Käse nach der Lage ihres Herkunftslandes — von West nach Ost. | Cheddar = England ; Camembert = Frankreich ; Emmentaler = Schweiz ; Feta = Griechenland | Der erste kommt von der Insel. ; Der Weichkäse aus der Normandie folgt. ; Der Salzlakenkäse liegt am östlichsten. | Feta ist seit 2002 eine geschützte Ursprungsbezeichnung Griechenlands.
C U | Aus welchem Land stammt der Käse Gruyère? | Schweiz | Frankreich ; Italien ; Österreich | Er ist nach einer Region im Kanton Freiburg benannt. ; Er gehört ins klassische Käsefondue. ; Die Region heißt auf Deutsch Greyerzerland. | Gruyère ist seit 2001 in der Schweiz als Ursprungsbezeichnung geschützt.

@ kochen_zutaten
C E | Welche Farbe hat klassisches Pistazieneis? | Grün | Gelb ; Rosa ; Braun | Die Nüsse haben diese Farbe. ; Wie Gras. ; Oft wird zusätzlich gefärbt. | Echte Pistazienkerne sind grünlich — viele Eisdielen helfen farblich nach.
M H | Welche ZWEI dieser Gewürze sind Samen bzw. Früchte? | Senf ; Kreuzkümmel | Zimt ; Nelken ; Safran ; Ingwer | Einer steckt in einer gelben Paste. ; Der andere prägt Currys und Chili. ; Rinde, Knospe, Blütennarbe und Wurzel scheiden aus. | Zimt ist Rinde, Nelken sind Knospen, Safran sind Narben, Ingwer ist ein Wurzelstock.
C U | Aus welcher Stadt stammt der traditionelle Aceto Balsamico? | Modena | Parma ; Bologna ; Neapel | Die Stadt liegt in der Emilia-Romagna. ; Auch Ferrari hat seinen Sitz in der Nähe. ; Der echte reift mindestens zwölf Jahre. | Der „Aceto Balsamico Tradizionale di Modena“ reift in Holzfässern aus verschiedenen Holzarten.
"""
