"""Extra questions: Filme & Serien (format: see tools/content/merge_extra.py)."""
KAT = "filme_serien"
REGION = "global"
DATA = r"""
@ blockbuster_hollywood
C E | Welcher Preis ist die bekannteste Auszeichnung der US-Filmindustrie? | Oscar | Emmy ; Grammy ; Golden Globe | Die Statue ist goldfarben. ; Offiziell heißt er „Academy Award“. ; Der Emmy ist fürs Fernsehen. | Die erste Oscar-Verleihung fand 1929 statt und dauerte nur 15 Minuten.
C E | Welcher Preis wird beim Filmfestival von Cannes als Hauptpreis vergeben? | Goldene Palme | Goldener Bär ; Goldener Löwe ; Goldene Kamera | Cannes liegt an der Côte d'Azur. ; Eine Pflanze der Riviera ist das Symbol. ; Es ist kein Tier. | Die Goldene Palme wird seit 1955 vergeben.
C E | Welcher Preis wird bei der Berlinale als Hauptpreis vergeben? | Goldener Bär | Goldene Palme ; Goldener Löwe ; Silberner Adler | Das Tier ist Berlins Wappentier. ; Er ist aus Metall und brummt nicht. ; Die Berlinale findet im Februar statt. | Die Berlinale wurde 1951 gegründet und ist eines der größten Publikumsfestivals der Welt.
C E | Welcher Preis ist der Hauptpreis der Filmfestspiele von Venedig? | Goldener Löwe | Goldener Bär ; Goldene Palme ; Goldener Adler | Das Tier ist das Symbol des heiligen Markus. ; Es ist eine Raubkatze. ; Venedig ist das älteste Filmfestival der Welt. | Die Filmfestspiele von Venedig fanden erstmals 1932 statt.
C E | Welche Figur des Warner-Bros.-Zeichentricks fragt „Was geht ab, Doc?“ | Bugs Bunny | Daffy Duck ; Porky Pig ; Speedy Gonzales | Er isst gern Karotten. ; Er ist ein Hase. ; Sein Jäger heißt Elmer Fudd. | Im Original lautet sein Spruch „What's up, Doc?“.
C E | Welche beiden Tiere sind die Titelfiguren von „Tom und Jerry“? | Katze und Maus | Hund und Katze ; Kater und Vogel ; Fuchs und Hase | Tom jagt Jerry. ; Jerry entkommt fast immer. ; Einer ist grau-blau, der andere braun. | „Tom und Jerry“ gewann sieben Oscars für den besten animierten Kurzfilm.
C E | Welche Hunderasse ist Scooby-Doo? | Deutsche Dogge | Bernhardiner ; Beagle ; Golden Retriever | Er ist sehr groß. ; Die Rasse stammt aus Deutschland. ; Er hat Angst vor Gespenstern. | Scooby-Doo liebt „Scooby-Snacks“ und fährt mit seinen Freunden in der „Mystery Machine“.
C M | Mit wie vielen Bildern pro Sekunde werden klassische Kinofilme gezeigt? | 24 | 12 ; 30 ; 60 | Mehr als 20. ; Diese Rate setzte sich mit dem Tonfilm durch. ; Zwei Dutzend. | 24 Bilder pro Sekunde wurden mit dem Tonfilm Ende der 1920er zum Standard.
C M | Welches Filmstudio zeigt in seinem Logo einen Jungen, der auf einer Mondsichel angelt? | DreamWorks | Pixar ; Paramount ; Universal | Steven Spielberg gründete es mit. ; Von ihm stammt „Shrek“. ; Der Name verbindet Traum und Arbeit. | DreamWorks wurde 1994 von Spielberg, Jeffrey Katzenberg und David Geffen gegründet.
C M | Welches Filmstudio hat einen Berg mit Sternen im Logo? | Paramount | Universal ; Columbia ; Warner Bros. | Es ist das älteste noch bestehende Hollywood-Studio. ; Der Berg soll einem Gipfel in Utah nachempfunden sein. ; Die Sterne standen einst für Vertragsschauspieler. | Paramount Pictures wurde 1912 gegründet.
C E | Wer spielte den Archäologen Indiana Jones? | Harrison Ford | Kevin Costner ; Mel Gibson ; Tom Selleck | Er spielte auch Han Solo. ; Er war zuvor Zimmermann. ; Sein Vorname ist Harrison. | Tom Selleck war ursprünglich vorgesehen, konnte aber wegen „Magnum“ nicht.
C E | Welcher Comic-Verleger hatte in fast jedem Marvel-Film einen kurzen Gastauftritt? | Stan Lee | Jack Kirby ; Steve Ditko ; Bob Kane | Er schuf Spider-Man mit. ; Er starb 2018. ; Sein Markenzeichen war eine große Sonnenbrille. | Stan Lees Cameos wurden zu einem liebevollen Running Gag.
C H | Welcher Film über einen Außerirdischen enthält den Satz „nach Hause telefonieren“? | E.T. – Der Außerirdische | Unheimliche Begegnung der dritten Art ; Alien ; Der Tag, an dem die Erde stillstand | Regie führte Steven Spielberg. ; Ein Junge versteckt das Wesen im Kleiderschrank. ; Er fliegt mit dem Fahrrad am Mond vorbei. | Das Bild mit dem Fahrrad vor dem Mond wurde zum Logo von Spielbergs Firma Amblin.
C H | Wie heißt der Weiße Hai in „Findet Nemo“, der sich vorgenommen hat, keine Fische mehr zu fressen? | Bruce | Jaws ; Chum ; Anchor | Sein Motto: „Fische sind Freunde, kein Futter.“ ; Er ist nach dem Spitznamen des Hai-Modells aus „Der weiße Hai“ benannt. ; Der Name hat fünf Buchstaben. | Das mechanische Hai-Modell in Spielbergs „Der weiße Hai“ nannte das Team „Bruce“.
C U | In welchem Jahr fand die allererste Oscar-Verleihung statt? | 1929 | 1927 ; 1932 ; 1939 | Noch vor dem großen Börsenkrach. ; In einem Hotel in Hollywood. ; Das Jahr endet auf 9. | Die erste Verleihung im Hollywood Roosevelt Hotel dauerte nur rund 15 Minuten.
W M | Filmtrailer wurden ursprünglich nach dem Hauptfilm gezeigt — daher der Name. | wahr | „Trailer“ heißt Anhänger — die Vorschauen liefen anfangs im Anschluss an den Film.
W H | Die Oscar-Statuette besteht aus massivem Gold. | falsch | Die Statue besteht aus Bronze mit einer Goldschicht — massiv golden wäre sie viel zu teuer.
S M | Wie viele Filme umfasst die klassische „Star Wars“-Saga um die Skywalker-Familie (Episoden I–IX)? | 9 | Filme | 15 | 1 | 20 | Es sind drei Trilogien. ; Drei mal drei. ; Mehr als sechs. | Die Saga reicht von „Die dunkle Bedrohung“ bis „Der Aufstieg Skywalkers“.
S H | In welchem Jahr kam der erste „Harry Potter“-Film in die Kinos? | 2001 | Jahr | 1 | 1990 | 2015 | Kurz nach der Jahrtausendwende. ; Im selben Jahr startete auch der erste „Herr der Ringe“-Film. ; Das Jahr endet auf 1. | „Harry Potter und der Stein der Weisen“ startete im November 2001 — Daniel Radcliffe war damals zwölf.
O M | Sortiere diese Filme nach ihrem Kinostart — den ältesten zuerst. | E.T. = 1982 ; Jurassic Park = 1993 ; Titanic = 1997 ; Avatar = 2009 | Der Außerirdische kam zuerst. ; Die Dinosaurier folgten. ; Das 3D-Spektakel ist der jüngste. | Zwei der vier Filme stammen von James Cameron, zwei von Steven Spielberg.
M M | Welche ZWEI dieser Filme drehte Steven Spielberg? | Jurassic Park ; Der weiße Hai | Titanic ; Avatar ; Der Pate ; Pulp Fiction | Einer handelt von Dinosauriern. ; Der andere von einem Hai. ; James Cameron, Coppola und Tarantino scheiden aus. | Spielbergs „Der weiße Hai“ (1975) gilt als erster Sommer-Blockbuster.

@ animationsfilme
C E | Welches Tier ist Peppa Wutz? | Ein Schwein | Ein Hund ; Ein Schaf ; Ein Hase | Sie grunzt gern. ; Sie springt in Matschpfützen. ; Ihr Bruder heißt Schorsch. | Die britische Serie „Peppa Pig“ läuft seit 2004.
C E | Wie heißt der Cowboy aus „Toy Story“? | Woody | Buzz ; Rex ; Slinky | Er hat eine Zugschnur am Rücken. ; Sein Spruch: „In meinem Stiefel ist eine Schlange!“ ; Er ist Andys Lieblingsspielzeug. | Tom Hanks spricht Woody im Original.
C M | Wie heißt der Kojote, der in den Cartoons vergeblich den Road Runner jagt? | Wile E. Coyote | Bugs Bunny ; Sylvester ; Elmer Fudd | Er bestellt Geräte bei der Firma ACME. ; Er fällt oft von Klippen. ; Sein Name klingt nach einem Wildtier. | Wile E. Coyote spricht in den Road-Runner-Cartoons fast nie.
C M | Welcher Disney-Film von 1937 war der erste abendfüllende Zeichentrickfilm des Studios? | Schneewittchen und die sieben Zwerge | Pinocchio ; Bambi ; Dornröschen | Er basiert auf einem Grimm-Märchen. ; Eine böse Königin befragt einen Spiegel. ; Sieben kleine Männer spielen mit. | Kritiker nannten das Projekt vorab „Disneys Wahnsinn“ — es wurde ein Welterfolg.
S U | Wie viele Oscars gewann „Tom und Jerry“ für den besten animierten Kurzfilm? | 7 | Oscars | 20 | 1 | 20 | Mehr als fünf. ; Weniger als zehn. ; Eine Primzahl. | Die sieben Oscars holte das Duo zwischen 1943 und 1953.

@ streaming_serien
C M | In welcher Stadt spielt die Krankenhausserie „Grey's Anatomy“? | Seattle | Chicago ; Boston ; San Francisco | Die Stadt liegt im Nordwesten der USA. ; Dort sitzen Amazon und Starbucks. ; Die Space Needle ist ihr Wahrzeichen. | Das Krankenhaus hieß anfangs „Seattle Grace“.
C M | Wie viele Staffeln hat „Breaking Bad“? | 5 | 4 ; 6 ; 7 | Die letzte Staffel wurde in zwei Hälften ausgestrahlt. ; Die Serie lief von 2008 bis 2013. ; Weniger als sechs. | Das Spin-off „Better Call Saul“ hat sechs Staffeln.
W M | „Die Simpsons“ ist die am längsten laufende animierte US-Serie zur Hauptsendezeit. | wahr | Die Simpsons laufen seit 1989 als eigenständige Serie und haben über 750 Folgen.
S H | Wie viele Folgen hat eine klassische Sitcom-Staffel im US-Fernsehen ungefähr? | 22 | Folgen | 20 | 5 | 50 | Deutlich mehr als bei Streaming-Serien. ; Mehr als 20. ; Etwa eine Folge pro Woche von Herbst bis Frühling. | Streaming-Serien haben oft nur 8 bis 10 Folgen pro Staffel.

@ scifi_fantasy
C M | Welcher Schauspieler spielte in der Original-Trilogie von „Star Wars“ Luke Skywalker? | Mark Hamill | Harrison Ford ; Carrie Fisher ; Alec Guinness | Er lieh später dem Joker in Zeichentrickserien seine Stimme. ; Harrison Ford spielte Han Solo. ; Sein Vorname ist Mark. | Mark Hamill kehrte 2017 in „Die letzten Jedi“ als Luke zurück.
C E | Welche Farbe hat das Lichtschwert von Yoda? | Grün | Blau ; Rot ; Lila | Luke hat später auch diese Farbe. ; Die Sith nutzen Rot. ; Es ist die Farbe von Yodas Haut. | Mace Windu ist mit seinem lila Lichtschwert eine Ausnahme.
C H | Wie heißt der kreiselnde Gegenstand, mit dem Cobb in „Inception“ prüft, ob er träumt? | Kreisel (Totem) | Würfel ; Münze ; Schachfigur | Er dreht sich auf dem Tisch. ; Im Traum hört er nie auf. ; In der Schlussszene wackelt er. | Das offene Ende mit dem Kreisel wird bis heute diskutiert.
W H | In „Der Herr der Ringe“ wird Gandalf nach seinem Kampf gegen den Balrog zu „Gandalf dem Weißen“. | wahr | Gandalf der Graue kehrt nach dem Kampf in Moria als Gandalf der Weiße zurück.

@ deutsche_filme_serien de
C E | Welche kleine Hexe ruft „Hex-hex!“ und reitet auf dem Besen Kartoffelbrei? | Bibi Blocksberg | Die kleine Hexe ; Hexe Lilli ; Petronella Apfelmus | Ihre beste Freundin heißt Tina. ; Sie lebt in Neustadt. ; Ihr Nachname ist ein berühmter Hexenberg. | Bibi Blocksberg gibt es seit 1980 als Hörspiel.
C E | Welches Tier ist Benjamin Blümchen? | Ein Elefant | Ein Nilpferd ; Ein Nashorn ; Ein Walross | Er sagt „Törööö!“. ; Er wohnt im Neustädter Zoo. ; Sein Freund heißt Otto. | Benjamin Blümchen erschien 1977 erstmals als Hörspiel.
C E | In welchem fiktiven Küstenort ermitteln die „drei ???“? | Rocky Beach | Seaside ; Sunny Bay ; Palm Harbor | Der Ort liegt in Kalifornien. ; Die Zentrale ist ein Campingwagen auf dem Schrottplatz. ; Der Name enthält „Strand“ auf Englisch. | Justus, Peter und Bob ermitteln seit 1979 als deutsche Hörspielserie — erfolgreicher als im US-Original.
C M | Welcher Film von Leander Haußmann spielt am kurzen Ende einer Ost-Berliner Straße direkt an der Mauer? | Sonnenallee | Good Bye, Lenin! ; Das Leben der Anderen ; Berlin is in Germany | Er erschien 1999. ; Die Straße gab es wirklich. ; Das kurze Ende lag im Osten. | Die echte Sonnenallee verlief durch West- und Ost-Berlin.
C M | Welcher Film von 2008 zeigt ein Schulexperiment, das in eine autoritäre Bewegung umschlägt? | Die Welle | Das Experiment ; Die fetten Jahre sind vorbei ; Der Club der toten Dichter | Jürgen Vogel spielt den Lehrer. ; Die Vorlage beruht auf einem US-Schulversuch von 1967. ; Der Titel beschreibt eine Bewegung. | Das Original-Experiment „The Third Wave“ fand an einer Highschool in Kalifornien statt.
C H ab12 | In welchem Fritz-Lang-Film von 1931 verrät sich ein Mörder durch das Pfeifen einer Melodie? | M – Eine Stadt sucht einen Mörder | Metropolis ; Dr. Mabuse ; Die Nibelungen | Es war Langs erster Tonfilm. ; Der Täter pfeift Grieg. ; Ein Buchstabe wird ihm auf den Mantel gezeichnet. | Die gepfiffene Melodie stammt aus Griegs „In der Halle des Bergkönigs“.
W M | Die deutsche Hörspielserie „Die drei ???“ basiert auf US-amerikanischen Jugendbüchern. | wahr | Die Buchreihe „The Three Investigators“ begann 1964 in den USA — in Deutschland wurde sie zum Kult.
S H | In welchem Jahr erschien das erste Hörspiel von „Die drei ???“ in Deutschland? | 1979 | Jahr | 2 | 1960 | 2000 | Ende der 1970er. ; Ein Jahr vor Bibi Blocksberg. ; Das Jahr endet auf 9. | Die erste Folge hieß „Die drei ??? und der Super-Papagei“.
O M | Sortiere diese Kinder-Hörspielhelden nach ihrem ersten Hörspiel — den ältesten zuerst. | Benjamin Blümchen = 1977 ; Die drei ??? = 1979 ; Bibi Blocksberg = 1980 ; Bibi & Tina = 1991 | Der Elefant kam zuerst. ; Die Detektive folgten zwei Jahre später. ; Das Pferde-Spin-off ist das jüngste. | Alle vier Serien gehören zu den erfolgreichsten Hörspielen Deutschlands.
@ blockbuster_hollywood
O E | Sortiere diese Star-Wars-Filme nach ihrem Kinostart — den ältesten zuerst. | Eine neue Hoffnung = 1977 ; Das Imperium schlägt zurück = 1980 ; Die Rückkehr der Jedi-Ritter = 1983 ; Die dunkle Bedrohung = 1999 | Die Originaltrilogie kam zuerst. ; Das Imperium folgte drei Jahre später. ; Das Prequel ist der jüngste. | „Die dunkle Bedrohung“ ist Episode I, kam aber als vierter Film ins Kino.
M H | Welche ZWEI dieser Filme gewannen den Oscar als bester Film? | Titanic ; Forrest Gump | Avatar ; Krieg der Sterne ; Jurassic Park ; E.T. | Einer handelt von einem sinkenden Schiff. ; Der andere von einem Mann mit einer Pralinenschachtel. ; Die anderen waren Kassenhits ohne Hauptpreis. | „Krieg der Sterne“ unterlag 1978 „Der Stadtneurotiker“.
M U | Welche ZWEI dieser Regisseure stammen aus Deutschland? | Tom Tykwer ; Wim Wenders | Alfred Hitchcock ; Stanley Kubrick ; Federico Fellini ; Akira Kurosawa | Einer drehte „Lola rennt“. ; Der andere „Der Himmel über Berlin“. ; Großbritannien, USA, Italien und Japan scheiden aus. | Wim Wenders erhielt 1984 die Goldene Palme für „Paris, Texas“.
S H | Wie viele Filme umfassen die „Herr der Ringe“- und die „Hobbit“-Trilogie von Peter Jackson zusammen? | 6 | Filme | 15 | 1 | 20 | Zwei Trilogien. ; Zwei mal drei. ; Weniger als acht. | Alle sechs Filme wurden in Neuseeland gedreht.

@ animationsfilme
C E | Welche Farbe hat der Oger Shrek? | Grün | Blau ; Grau ; Braun | Er lebt im Sumpf. ; Seine Ohren sehen aus wie Trompeten. ; Die Farbe von Gras. | Shrek basiert auf einem Bilderbuch von William Steig aus dem Jahr 1990.
C E | Welches Tier ist Dumbo aus dem Disney-Film von 1941? | Ein Elefant | Eine Maus ; Ein Esel ; Ein Nashorn | Er hat riesige Ohren. ; Er kann damit fliegen. ; Er arbeitet im Zirkus. | Sein bester Freund ist die Maus Timothy.
M E | Welche ZWEI dieser Figuren sind Disney-Prinzessinnen? | Arielle ; Cinderella | Hermine Granger ; Pippi Langstrumpf ; Wednesday Addams ; Lara Croft | Eine lebt unter dem Meer. ; Die andere verliert einen gläsernen Schuh. ; Die übrigen stammen aus Büchern, Serien oder Spielen. | Arielle erschien 1989, Cinderella 1950.
"""
