"""Extra questions: Gaming (non-LoL; format: see tools/content/merge_extra.py)."""
KAT = "gaming"
REGION = "global"
DATA = r"""
@ esport_gaming_kultur
C E | Welches Unternehmen stellt die Xbox-Konsolen her? | Microsoft | Sony ; Nintendo ; Sega | Die Firma ist vor allem für Windows bekannt. ; Die erste Konsole kam 2001. ; Der Gründer heißt Bill Gates. | Die erste Xbox erschien 2001, im selben Jahr wie „Halo“.
C E | Welches Unternehmen stellt die PlayStation her? | Sony | Microsoft ; Nintendo ; Samsung | Die Firma stammt aus Japan. ; Sie baute auch den Walkman. ; Das Logo der Konsole besteht aus den Buchstaben P und S. | Die erste PlayStation erschien 1994 in Japan.
C E | In welchem Spiel steuert man Menschen im Alltag, die über einem grünen Kristall schweben und „Simlisch“ sprechen? | Die Sims | Second Life ; Animal Crossing ; Stardew Valley | Der Kristall heißt Plumbob. ; Man baut Häuser und erfüllt Bedürfnisse. ; Erfunden hat es Will Wright. | „Die Sims“ erschien im Jahr 2000 und wurde zu einem der meistverkauften PC-Spiele.
C E | Welche wütenden Vögel schleudert man mit einer Schleuder auf Schweine? | Angry Birds | Flappy Bird ; Tiny Wings ; Crossy Road | Das Spiel stammt aus Finnland. ; Es erschien 2009 für Smartphones. ; Die Schweine klauen die Eier. | Das Studio Rovio landete mit Angry Birds einen der ersten großen Handy-Hits.
C E | In welchem Handyspiel tauscht man bunte Bonbons, um Dreierreihen zu bilden? | Candy Crush Saga | Bejeweled ; Fruit Ninja ; Cut the Rope | Es stammt von King. ; Der Name enthält „Süßigkeit“ auf Englisch. ; Es erschien 2012. | Candy Crush wurde zu einem der umsatzstärksten Handyspiele überhaupt.
C M ab12 | Wie heißt die fiktive Stadt, in der „GTA V“ spielt und die Los Angeles nachempfunden ist? | Los Santos | Vice City ; Liberty City ; San Fierro | Der Name klingt spanisch. ; Vice City ist Miami nachempfunden. ; Die Heiligen stecken im Namen. | GTA V erschien 2013 und gehört zu den meistverkauften Spielen aller Zeiten.
C M | Wie heißt die weltgrößte Download-Plattform für PC-Spiele von Valve? | Steam | Origin ; Epic Games Store ; GOG | Sie startete 2003. ; Der Name bedeutet „Dampf“. ; Valve entwickelte auch „Half-Life“. | Steam hat regelmäßig Dutzende Millionen Nutzer gleichzeitig online.
C M ab12 | Wie heißt der grüne Supersoldat aus der „Halo“-Reihe? | Master Chief | Doomguy ; Marcus Fenix ; Commander Shepard | Seine Kennung ist John-117. ; Er trägt eine grüne Rüstung mit goldenem Visier. ; Seine KI-Begleiterin heißt Cortana. | Cortana gab später auch Microsofts Sprachassistentin ihren Namen.
C M | In welchem Spiel spielen Autos Fußball mit einem riesigen Ball? | Rocket League | Mario Strikers ; Trackmania ; FIFA Street | Die Autos können mit Raketenantrieb fliegen. ; Es stammt vom Studio Psyonix. ; Es erschien 2015. | Rocket League wurde 2020 kostenlos spielbar.
C E | Wie heißt die Heldin der Spielreihe „Tomb Raider“? | Lara Croft | Samus Aran ; Jill Valentine ; Aloy | Sie ist britische Archäologin. ; Angelina Jolie spielte sie im Film. ; Sie trägt meist zwei Pistolen. | Das erste Tomb Raider erschien 1996.
C M | Welches Online-Rollenspiel von Blizzard spielt in der Welt Azeroth? | World of Warcraft | Diablo ; Guild Wars ; EverQuest | Es startete 2004. ; Horde und Allianz bekriegen sich. ; Die Abkürzung ist WoW. | World of Warcraft hatte zu Spitzenzeiten über zwölf Millionen Abonnenten.
C H | In welchem Rollenspiel von Bethesda kämpft man als „Drachenblut“ in der Provinz Himmelsrand? | The Elder Scrolls V: Skyrim | The Witcher 3 ; Dragon Age ; Oblivion | Es erschien am 11.11.2011. ; Ein berühmtes Meme: „Pfeil ins Knie“. ; Die Provinz heißt im Original Skyrim. | Skyrim wurde für fast jede erdenkliche Plattform neu veröffentlicht.
C H | Aus welchem Land stammt das Studio CD Projekt Red, Entwickler von „The Witcher 3“? | Polen | Tschechien ; Ukraine ; Russland | Die Hauptstadt ist Warschau. ; Die Witcher-Romane stammen von Andrzej Sapkowski. ; Das Studio machte auch „Cyberpunk 2077“. | Die Vorlage für Geralt stammt aus Andrzej Sapkowskis Büchern.
C U | Wie hieß das erste Spiel, das Valve 1998 veröffentlichte? | Half-Life | Portal ; Counter-Strike ; Team Fortress | Der Held heißt Gordon Freeman. ; Er trägt einen HEV-Anzug. ; Später wurde es Basis für viele Mods. | Aus einer Half-Life-Mod entstand 1999 Counter-Strike.
W M | Die erste Xbox erschien vor der ersten PlayStation. | falsch | Die PlayStation erschien 1994, die Xbox erst 2001.
W M | „Die Sims“ wurde von Nintendo entwickelt. | falsch | Die Sims stammen von Will Wright und dem Studio Maxis und erschienen bei Electronic Arts.
W H | Das Spiel „Minecraft“ wurde ursprünglich von Microsoft entwickelt. | falsch | Minecraft wurde von Markus „Notch“ Persson entwickelt; Microsoft kaufte das Studio Mojang 2014.
S M | In welchem Jahr erschien die erste PlayStation in Japan? | 1994 | Jahr | 2 | 1980 | 2010 | Mitte der 1990er. ; Zwei Jahre vor dem Nintendo 64. ; Das Jahr endet auf 4. | Die PlayStation verkaufte sich über 100 Millionen Mal.
S U | Wie viele Millionen Abonnenten hatte World of Warcraft zu Spitzenzeiten ungefähr? | 12 | Mio. | 20 | 1 | 100 | Mehr als zehn. ; Der Höhepunkt lag um 2010. ; Etwa ein Dutzend. | Rund zwölf Millionen Menschen zahlten Ende 2010 ein WoW-Abo.
O M | Sortiere diese Spielkonsolen nach ihrem Erscheinen — die älteste zuerst. | PlayStation = 1994 ; Xbox = 2001 ; Wii = 2006 ; Nintendo Switch = 2017 | Sony kam zuerst. ; Microsoft stieg nach der Jahrtausendwende ein. ; Die Hybridkonsole ist die jüngste. | Die Wii machte mit Bewegungssteuerung auch Großeltern zu Gamern.
O H | Sortiere diese Spiele nach ihrem Erscheinen — das älteste zuerst. | Tetris = 1984 ; Doom = 1993 ; Tomb Raider = 1996 ; World of Warcraft = 2004 | Das Puzzle kam aus der Sowjetunion. ; Der Ego-Shooter folgte fast ein Jahrzehnt später. ; Das Online-Rollenspiel ist das jüngste. | Doom machte 1993 das Shooter-Genre massentauglich.
M M | Welche ZWEI dieser Spielereihen stammen von Nintendo? | The Legend of Zelda ; Mario Kart | Halo ; Gran Turismo ; Tomb Raider ; Sonic | Eine hat einen Helden namens Link. ; Die andere ist ein Rennspiel mit Bananen. ; Sonic gehört zu Sega. | Halo gehört zu Microsoft, Gran Turismo zu Sony, Tomb Raider zu Crystal Dynamics.

@ retro_arcade
C E ab12 | Welcher Ego-Shooter von 1993 machte das Genre berühmt und spielt auf dem Mars und in der Hölle? | Doom | Quake ; Wolfenstein 3D ; Duke Nukem | Entwickelt wurde es von id Software. ; Der Held heißt „Doomguy“. ; Es läuft angeblich auf fast jedem Gerät, sogar Taschenrechnern. | „Can it run Doom?“ ist bis heute ein Running Gag unter Bastlern.
C M | Welche Spielfigur von Naughty Dog galt als inoffizielles Maskottchen der ersten PlayStation? | Crash Bandicoot | Spyro ; Rayman ; Sonic | Er ist ein Beuteltier. ; Er dreht sich wie ein Wirbelwind. ; Er sammelt Wumpa-Früchte. | Crash Bandicoot erschien 1996.
C H | Welcher Jump'n'Run-Held von Ubisoft hat weder Arme noch Beine? | Rayman | Crash ; Spyro ; Gex | Seine Hände und Füße schweben frei. ; Er stammt aus Frankreich. ; Das erste Spiel erschien 1995. | Rayman bekam später die verrückten „Rabbids“ als Gegner.
W M | „Doom“ erschien zuerst als Shareware, bei der die erste Episode kostenlos war. | wahr | id Software verbreitete die erste Episode kostenlos — ein Erfolgsrezept.
S H | In welchem Jahr erschien das erste „Tomb Raider“? | 1996 | Jahr | 2 | 1980 | 2010 | Mitte der 1990er. ; Kurz nach dem Start der PlayStation. ; Das Jahr endet auf 6. | Lara Croft wurde schnell zu einer der bekanntesten Spielfiguren der Welt.

@ fortnite_battle_royale
C M ab12 | Welches Battle-Royale-Spiel von 2017 machte das Genre populär, noch bevor Fortnite es übernahm? | PUBG | Apex Legends ; Warzone ; H1Z1 | Die Abkürzung steht für „PlayerUnknown's Battlegrounds“. ; Man springt aus einem Flugzeug auf eine Insel. ; Der Sieger bekommt ein „Chicken Dinner“. | „Winner Winner Chicken Dinner“ wurde zum Kultspruch.
C U | Welches Studio entwickelte „Apex Legends“? | Respawn Entertainment | Epic Games ; Infinity Ward ; DICE | Es gehört zu Electronic Arts. ; Die Gründer arbeiteten zuvor an „Call of Duty“. ; Auch „Titanfall“ stammt von dort. | Apex Legends erschien 2019 überraschend ohne große Vorankündigung.
W M ab12 | Beim Battle-Royale-Prinzip gewinnt der letzte überlebende Spieler oder das letzte Team. | wahr | Der Name geht auf den japanischen Film „Battle Royale“ aus dem Jahr 2000 zurück.
S M | Aus wie vielen Spielern besteht ein „Squad“ in klassischen Battle-Royale-Modi wie PUBG? | 4 | Spieler | 25 | 1 | 10 | Mehr als ein Duo. ; Weniger als fünf. ; Eine Zweierpotenz. | Neben Solo und Duo ist der Vierer-Squad der beliebteste Teammodus.
@ esport_gaming_kultur
O E | Sortiere diese PlayStation-Konsolen nach ihrem Erscheinen — die älteste zuerst. | PlayStation = 1994 ; PlayStation 2 = 2000 ; PlayStation 3 = 2006 ; PlayStation 4 = 2013 | Die Zahl verrät es. ; Die PS2 kam zur Jahrtausendwende. ; Die PS4 ist die jüngste der vier. | Die PlayStation 2 ist mit über 150 Millionen Geräten die meistverkaufte Konsole aller Zeiten.
M E ab12 | Welche ZWEI dieser Spiele sind Ego-Shooter? | Doom ; Halo | Tetris ; Die Sims ; Candy Crush ; Mario Kart | Man sieht durch die Augen der Figur. ; Einer spielt auf dem Mars. ; Der andere hat den Master Chief. | Ego-Shooter heißen im Englischen „First-Person Shooter“.
M U | Welche ZWEI dieser Spiele stammen von deutschen Studios? | Anno 1602 ; Crysis | Tetris ; Minecraft ; The Witcher 3 ; Fortnite | Eines ist ein Aufbauspiel. ; Das andere ein grafisch bahnbrechender Shooter. ; Russland, Schweden, Polen und die USA scheiden aus. | Anno 1602 stammt von Max Design aus Österreich und Sunflowers aus Hessen — Crysis von Crytek aus Frankfurt.
C E | Welches Unternehmen stellt die Nintendo Switch her? | Nintendo | Sony ; Microsoft ; Sega | Der Name steckt schon in der Konsole. ; Die Firma stammt aus Kyōto. ; Mario ist ihr Maskottchen. | Nintendo wurde 1889 als Hersteller von Spielkarten gegründet.
C H | Welcher Konsolenhersteller nennt seine Controller „DualShock“ bzw. „DualSense“? | Sony | Microsoft ; Nintendo ; Sega | Der Controller hat Kreis, Kreuz, Dreieck und Quadrat. ; Er gehört zur PlayStation. ; Die Firma stammt aus Japan. | „DualShock“ bezog sich auf die zwei Vibrationsmotoren.
"""
