"""Extra questions: Geographie (format: see tools/content/merge_extra.py)."""
KAT = "geographie"
REGION = "global"
DATA = r"""
@ erd_rekorde
C E | Welches Land hat die meisten Einwohner in Südamerika? | Brasilien | Argentinien ; Kolumbien ; Peru | Dort spricht man Portugiesisch. ; Samba und Karneval sind berühmt. ; Die größte Stadt ist São Paulo. | Brasilien hat über 200 Millionen Einwohner.
C E | Welcher ist der größte Regenwald der Erde? | Amazonas-Regenwald | Kongo-Regenwald ; Borneo-Regenwald ; Daintree-Regenwald | Er liegt in Südamerika. ; Ein riesiger Fluss fließt hindurch. ; Brasilien besitzt den größten Anteil. | Der Amazonas-Regenwald bedeckt rund 5,5 Millionen Quadratkilometer.
C E | Welches ist die längste Gebirgskette der Erde über dem Meeresspiegel? | Anden | Himalaya ; Rocky Mountains ; Alpen | Sie zieht sich an der Westküste Südamerikas entlang. ; Hier lebten die Inka. ; Der Aconcagua ist ihr höchster Gipfel. | Die Anden sind rund 7000 Kilometer lang — vom Karibischen Meer bis Feuerland.
C M | Welcher Berg gilt als höchster Europas, wenn man den Kaukasus zu Europa zählt? | Elbrus | Mont Blanc ; Matterhorn ; Großglockner | Er liegt in Russland. ; Er ist ein erloschener Vulkan mit zwei Gipfeln. ; Er ist über 5600 Meter hoch. | Ohne Kaukasus gilt der Mont Blanc mit rund 4806 Metern als höchster Berg Europas.
C E | Welcher Kontinent ist fast vollständig von Eis bedeckt? | Antarktis | Arktis ; Grönland ; Sibirien | Dort leben Kaiserpinguine. ; Er liegt rund um den Südpol. ; Kein Land besitzt ihn. | Der antarktische Eispanzer ist im Schnitt rund 2000 Meter dick.
C E | Welcher Ozean liegt zwischen Europa und Amerika? | Atlantischer Ozean | Pazifischer Ozean ; Indischer Ozean ; Arktischer Ozean | Die Titanic sank darin. ; Kolumbus überquerte ihn 1492. ; Er ist der zweitgrößte Ozean. | Der Atlantik bedeckt rund ein Fünftel der Erdoberfläche.
C M | Welches ist der höchste Berg Südamerikas? | Aconcagua | Chimborazo ; Huascarán ; Illimani | Er liegt in Argentinien. ; Er ist knapp 7000 Meter hoch. ; Er ist der höchste Berg außerhalb Asiens. | Der Aconcagua ist 6961 Meter hoch.
C M | Welches ist der höchste Berg Nordamerikas? | Denali | Mount Whitney ; Mount Logan ; Pico de Orizaba | Er liegt in Alaska. ; Er hieß lange Mount McKinley. ; Sein Name bedeutet „der Hohe“. | Der Denali ist 6190 Meter hoch.
C H | Welcher ist der größte Süßwassersee der Erde nach Fläche? | Oberer See | Baikalsee ; Victoriasee ; Michigansee | Er gehört zu den Großen Seen Nordamerikas. ; Er liegt zwischen den USA und Kanada. ; Sein Name verrät, dass er ganz oben liegt. | Der Obere See ist rund 82.000 Quadratkilometer groß — der Baikalsee enthält dafür mehr Wasser.
C M | Welches ist die größte Halbinsel der Erde? | Arabische Halbinsel | Iberische Halbinsel ; Skandinavische Halbinsel ; Halbinsel Indien | Dort liegt Saudi-Arabien. ; Sie ist überwiegend Wüste. ; Sie grenzt an das Rote Meer. | Die Arabische Halbinsel umfasst rund 3 Millionen Quadratkilometer.
C M | Welches ist das zweitgrößte Land Südamerikas nach Brasilien? | Argentinien | Peru ; Kolumbien ; Bolivien | Es reicht bis Feuerland. ; Tango stammt von dort. ; Die Hauptstadt ist Buenos Aires. | Argentinien ist mit 2,8 Millionen Quadratkilometern das achtgrößte Land der Erde.
C H | Welches ist die zweitgrößte Insel der Erde nach Grönland? | Neuguinea | Borneo ; Madagaskar ; Sumatra | Sie liegt nördlich von Australien. ; Sie ist politisch zweigeteilt. ; Ein Teil gehört zu Indonesien. | Neuguinea ist zwischen Indonesien und Papua-Neuguinea aufgeteilt.
C M | Welcher ist der längste Fluss Asiens? | Jangtsekiang | Gelber Fluss ; Mekong ; Ganges | Er fließt durch China. ; An ihm steht der Drei-Schluchten-Damm. ; Er mündet bei Shanghai. | Der Jangtse ist rund 6300 Kilometer lang — der drittlängste Fluss der Erde.
C H | Welches Land hat die meisten Einwohner unter den Staaten, die komplett in Europa liegen? | Deutschland | Frankreich ; Großbritannien ; Italien | Russland und die Türkei liegen teils in Asien. ; Rund 84 Millionen Menschen. ; Die Hauptstadt ist Berlin. | Frankreich folgt mit rund 68 Millionen Einwohnern.
C M | Welche Meerenge trennt Asien von Nordamerika? | Beringstraße | Straße von Gibraltar ; Bosporus ; Drakestraße | Sie ist nach einem dänischen Seefahrer benannt. ; Auf der einen Seite liegt Russland, auf der anderen Alaska. ; Sie ist nur rund 85 Kilometer breit. | In der Eiszeit verband hier eine Landbrücke Asien und Amerika.
C H | Welche ist die südlichste Hauptstadt eines unabhängigen Staates? | Wellington | Canberra ; Buenos Aires ; Kapstadt | Sie liegt in Neuseeland. ; Sie ist berüchtigt windig. ; Sie liegt am Südende der Nordinsel. | Wellington liegt auf etwa 41 Grad südlicher Breite.
C M | Welcher See gilt als höchstgelegener schiffbarer See der Welt? | Titicacasee | Baikalsee ; Victoriasee ; Tanganjikasee | Er liegt zwischen Peru und Bolivien. ; Auf rund 3800 Metern Höhe. ; Die Uros leben auf schwimmenden Schilfinseln. | Der Titicacasee ist rund 8300 Quadratkilometer groß.
C M | Welcher Salzsee in Bolivien ist die größte Salzfläche der Erde? | Salar de Uyuni | Großer Salzsee ; Etosha-Pfanne ; Totes Meer | Er liegt auf über 3600 Metern Höhe. ; Nach Regen wird er zu einem riesigen Spiegel. ; Unter ihm liegen große Lithiumvorkommen. | Der Salar de Uyuni misst über 10.000 Quadratkilometer.
C U | Welches ist der höchste Vulkan der Erde? | Ojos del Salado | Kilimandscharo ; Cotopaxi ; Mauna Loa | Er liegt an der Grenze zwischen Chile und Argentinien. ; Er ist knapp 6900 Meter hoch. ; Sein Name bedeutet „Augen des Salzigen“. | Der Ojos del Salado ist 6893 Meter hoch und gilt als ruhender Vulkan.
C H | Welches ist der höchste Berg Australiens (Festland)? | Mount Kosciuszko | Uluru ; Mount Cook ; Mount Wellington | Er ist nur gut 2200 Meter hoch. ; Er ist nach einem polnischen Freiheitskämpfer benannt. ; Er liegt in den Snowy Mountains. | Der Mount Kosciuszko ist mit 2228 Metern der niedrigste der „Seven Summits“ nach klassischer Liste.
C U | Welches ist der höchste Berg der Antarktis? | Mount Vinson | Mount Erebus ; Mount Kirkpatrick ; Mount Terror | Er ist knapp 4900 Meter hoch. ; Er liegt im Ellsworthgebirge. ; Er wurde erst 1966 erstmals bestiegen. | Das Vinson-Massiv ist 4892 Meter hoch.
C H | Welcher ist der größte See, der vollständig in der Schweiz liegt? | Neuenburgersee | Vierwaldstättersee ; Zürichsee ; Thunersee | Genfersee und Bodensee teilt die Schweiz mit Nachbarn. ; Er liegt in der französischsprachigen Schweiz. ; Eine Stadt am Ufer ist Sitz einer bekannten Uhrenindustrie-Region. | Der Neuenburgersee ist rund 218 Quadratkilometer groß.
C U | Welcher Kontinent hat die höchste durchschnittliche Höhe über dem Meeresspiegel? | Antarktis | Asien ; Südamerika ; Afrika | Das liegt an einem riesigen Eispanzer. ; Dort ist es am kältesten. ; Er liegt am Südpol. | Mit der Eisschicht liegt die Antarktis im Schnitt rund 2500 Meter hoch.
C H | Welches ist der höchste frei stehende Berg der Erde, der nicht Teil einer Gebirgskette ist? | Kilimandscharo | Mount Everest ; Elbrus ; Aconcagua | Er erhebt sich fast 5000 Meter über die Savanne. ; Er liegt in Ostafrika. ; Auf ihm gibt es noch Gletscher. | Der Kilimandscharo ragt einzeln aus der Ebene Tansanias empor.
C H | Welcher ist der größte Binnensee Afrikas? | Victoriasee | Tanganjikasee ; Malawisee ; Tschadsee | Er liegt in Uganda, Kenia und Tansania. ; Er ist nach einer britischen Königin benannt. ; Der Weiße Nil entspringt ihm. | Der Victoriasee ist mit knapp 69.000 Quadratkilometern der größte See Afrikas.
C H | Welches Land hat die meisten aktiven Vulkane? | Indonesien | Japan ; Island ; Italien | Es besteht aus Tausenden Inseln. ; Der Krakatau liegt dort. ; Die Hauptstadt ist Jakarta. | Indonesien liegt auf dem Pazifischen Feuerring und hat rund 130 aktive Vulkane.
C H | Welches Land ist rund 4300 Kilometer lang, im Schnitt aber nur etwa 180 Kilometer breit? | Chile | Norwegen ; Peru ; Vietnam | Es liegt an der Westküste Südamerikas. ; Die Atacama-Wüste liegt dort. ; Die Hauptstadt ist Santiago. | Chile reicht von der Wüste im Norden bis nach Feuerland im Süden.
C U | Welcher Fluss hat das größte Einzugsgebiet Afrikas? | Kongo | Nil ; Niger ; Sambesi | Er überquert zweimal den Äquator. ; Er ist der tiefste Fluss der Erde. ; Zwei Länder tragen seinen Namen. | Das Einzugsgebiet des Kongo umfasst rund 3,7 Millionen Quadratkilometer.
C U | Welcher ist der größte Binnenstaat Südamerikas? | Bolivien | Paraguay ; Peru ; Ecuador | Er hat zwei Hauptstädte. ; Er verlor 1884 seinen Meereszugang. ; Der Salar de Uyuni liegt dort. | Bolivien und Paraguay sind die einzigen Binnenstaaten Südamerikas.
W E | Der Mount Everest liegt in den Anden. | falsch | Der Everest liegt im Himalaya auf der Grenze zwischen Nepal und China.
W E | Afrika ist flächenmäßig der größte Kontinent. | falsch | Asien ist mit rund 44 Millionen Quadratkilometern größer; Afrika folgt mit rund 30 Millionen.
W M | Der Baikalsee enthält mehr Süßwasser als alle fünf Großen Seen Nordamerikas zusammen. | wahr | Der Baikalsee fasst rund ein Fünftel des flüssigen Oberflächensüßwassers der Erde.
W H | Die Antarktis ist größer als Europa. | wahr | Die Antarktis misst rund 14 Millionen Quadratkilometer, Europa etwa 10 Millionen.
W H | Der Äquator verläuft durch Kenia. | wahr | Der Äquator durchquert Kenia — ebenso Ecuador, Brasilien, Kongo, Uganda und Indonesien.
S M | Wie viele Meter hoch ist der Aconcagua ungefähr? | 6961 | Meter | 5 | 3000 | 9000 | Knapp unter 7000. ; Er ist der höchste Berg Amerikas. ; Höher als der Kilimandscharo. | Der Aconcagua in Argentinien ist der höchste Berg außerhalb Asiens.
S E | Wie viele Kontinente gibt es nach der in Deutschland üblichen Zählung? | 7 | Kontinente | 15 | 3 | 12 | Nord- und Südamerika zählen einzeln. ; Die Antarktis gehört dazu. ; Eine ungerade Zahl. | Europa, Asien, Afrika, Nordamerika, Südamerika, Australien und Antarktis.
S H | Wie viele Millionen Quadratkilometer groß ist Russland ungefähr? | 17 | Mio. km² | 15 | 1 | 100 | Mehr als zehn. ; Kanada hat rund zehn. ; Weniger als 20. | Russland ist mit rund 17,1 Millionen Quadratkilometern das größte Land der Erde.
S U | Wie viele Kilometer lang ist die Grenze zwischen Kanada und den USA ungefähr? | 8900 | km | 15 | 1000 | 30000 | log | Mehr als 5000. ; Weniger als 10.000. ; Etwa doppelt so lang wie die Strecke Lissabon–Moskau. | Die Grenze misst rund 8891 Kilometer, einschließlich der Grenze zu Alaska.
S U | Auf wie vielen Metern über dem Meeresspiegel liegt der Titicacasee ungefähr? | 3812 | Meter | 5 | 1000 | 6000 | Höher als die Zugspitze. ; Knapp unter 4000. ; Er liegt auf dem Altiplano. | Auf 3812 Metern ist die Luft so dünn, dass Besucher oft Höhenkrankheit spüren.
O M | Sortiere diese Berge nach ihrer Höhe — den niedrigsten zuerst. | Zugspitze = 2962 m ; Mont Blanc = 4806 m ; Kilimandscharo = 5895 m ; Mount Everest = 8849 m | Der deutsche Gipfel ist der niedrigste. ; Der Alpengipfel liegt unter 5000 Metern. ; Das Dach der Welt steht am Ende. | Der Everest wurde 2020 von Nepal und China gemeinsam auf 8848,86 Meter vermessen.
O M | Sortiere diese Ozeane nach ihrer Fläche — den kleinsten zuerst. | Arktischer Ozean = ≈ 14 Mio. km² ; Indischer Ozean = ≈ 70 Mio. km² ; Atlantischer Ozean = ≈ 85 Mio. km² ; Pazifischer Ozean = ≈ 165 Mio. km² | Der kleinste liegt rund um den Nordpol. ; Der Indische ist kleiner als der Atlantik. ; Der größte ist fast doppelt so groß wie der Atlantik. | Der Pazifik ist größer als alle Landflächen der Erde zusammen.
O H | Sortiere diese Seen nach ihrer Fläche — den kleinsten zuerst. | Bodensee = ≈ 536 km² ; Titicacasee = ≈ 8300 km² ; Victoriasee = ≈ 69.000 km² ; Kaspisches Meer = ≈ 371.000 km² | Der deutsche See ist mit Abstand der kleinste. ; Der Andensee folgt. ; Das „Meer“ ist eigentlich der größte See. | Das Kaspische Meer ist mit Abstand der größte See der Erde.
O U | Sortiere diese Wüsten nach ihrer Fläche — die kleinste zuerst. | Atacama = ≈ 105.000 km² ; Kalahari = ≈ 900.000 km² ; Gobi = ≈ 1,3 Mio. km² ; Sahara = ≈ 9 Mio. km² | Die trockenste ist die kleinste. ; Die afrikanische Savannenwüste folgt. ; Die größte heiße Wüste steht am Ende. | Rechnet man Kältewüsten mit, wären Antarktis und Arktis noch größer als die Sahara.
M M | Welche ZWEI dieser Länder werden vom Äquator durchquert? | Ecuador ; Kenia | Ägypten ; Mexiko ; Indien ; Australien | Eines ist sogar nach ihm benannt. ; Das andere liegt in Ostafrika. ; Die übrigen liegen alle nördlich oder südlich davon. | Der Äquator durchquert 13 Staaten, darunter Ecuador, Kolumbien, Brasilien, Kenia und Indonesien.
M H | Welche ZWEI dieser Länder sind Binnenstaaten ohne Meereszugang? | Mongolei ; Bolivien | Chile ; Portugal ; Vietnam ; Marokko | Eines liegt zwischen Russland und China. ; Das andere in Südamerika. ; Küstenstaaten scheiden aus. | Die Mongolei ist nach Kasachstan der zweitgrößte Binnenstaat der Erde.

@ deutschland_geographie de
C E | Welcher Fluss ist der längste Deutschlands (auf deutschem Gebiet)? | Rhein | Elbe ; Donau ; Main | An ihm liegen Köln und Düsseldorf. ; Er entspringt in der Schweiz. ; Die Loreley steht an seinem Ufer. | Der Rhein fließt rund 865 Kilometer durch Deutschland.
C E | An welchen beiden Meeren liegt Deutschland? | Nordsee und Ostsee | Ostsee und Mittelmeer ; Nordsee und Atlantik ; Nordsee und Schwarzes Meer | Eines hat starke Gezeiten. ; Das andere ist fast ein Binnenmeer. ; Beide liegen im Norden. | Die Nordsee hat Ebbe und Flut mit Wattenmeer, die Ostsee kaum Gezeiten.
C E | In welchem Bundesland liegt die Insel Rügen? | Mecklenburg-Vorpommern | Schleswig-Holstein ; Niedersachsen ; Brandenburg | Das Land liegt an der Ostsee. ; Die Hauptstadt ist Schwerin. ; Der Name hat zwei Teile. | Rügen ist mit rund 926 Quadratkilometern Deutschlands größte Insel.
C E | In welchem Bundesland liegt der Harz größtenteils? | Sachsen-Anhalt | Bayern ; Hessen ; Thüringen | Auch Niedersachsen und Thüringen haben Anteile. ; Der Brocken liegt darin. ; Die Hauptstadt ist Magdeburg. | Der Harz erstreckt sich über Niedersachsen, Sachsen-Anhalt und Thüringen.
C M | Welche Stadt ist die Landeshauptstadt von Rheinland-Pfalz? | Mainz | Koblenz ; Trier ; Kaiserslautern | Sie liegt am Rhein gegenüber von Wiesbaden. ; Sie ist für Fastnacht bekannt. ; Gutenberg stammte von dort. | Mainz und Wiesbaden sind Landeshauptstädte direkt gegenüber am Rhein.
C M | Welche Landeshauptstadt liegt direkt gegenüber von Mainz auf der anderen Rheinseite? | Wiesbaden | Frankfurt ; Darmstadt ; Koblenz | Sie ist hessische Landeshauptstadt. ; Sie ist eine Kurstadt mit heißen Quellen. ; Nicht die größte Stadt Hessens. | Wiesbaden hat 26 Thermal- und Mineralquellen.
C H | Wie heißt das Mittelgebirge zwischen Hessen, Bayern und Thüringen mit der Wasserkuppe? | Rhön | Taunus ; Spessart ; Vogelsberg | Die Wasserkuppe gilt als Wiege des Segelflugs. ; Es heißt „Land der offenen Fernen“. ; Der Name hat nur vier Buchstaben. | Die Wasserkuppe ist mit 950 Metern der höchste Berg Hessens.
C M | Welche deutsche Stadt hat die meisten Brücken? | Hamburg | Berlin ; Bremen ; Potsdam | Sie hat mehr Brücken als Venedig und Amsterdam zusammen. ; Sie hat einen großen Hafen. ; Sie liegt an der Elbe. | Hamburg zählt rund 2500 Brücken — mehr als jede andere europäische Stadt.
C H | Welcher Fluss entsteht im Fichtelgebirge und Frankenjura und mündet bei Mainz in den Rhein? | Main | Neckar ; Mosel ; Lahn | An ihm liegen Würzburg und Frankfurt. ; Er ist der längste rechte Nebenfluss des Rheins. ; Er fließt in vielen Schleifen durch Franken. | Der Main entsteht aus Weißem und Rotem Main bei Kulmbach.
C U | Wie heißt die höchste Erhebung Nordrhein-Westfalens? | Langenberg | Kahler Asten ; Brocken ; Feldberg | Er liegt im Rothaargebirge. ; Er ist nur gut einen Meter höher als ein berühmterer Nachbarberg. ; Der Nachbar heißt Kahler Asten. | Der Langenberg misst 843 Meter, der bekanntere Kahle Asten 841 Meter.
C U | Welche ist die älteste Stadt Deutschlands, gegründet von den Römern um 16 v. Chr.? | Trier | Köln ; Augsburg ; Worms | Sie liegt an der Mosel. ; Die Porta Nigra steht dort. ; Karl Marx wurde dort geboren. | Trier wurde als Augusta Treverorum gegründet; auch Worms, Köln und Augsburg beanspruchen hohes Alter.
W E | Hamburg ist die größte Stadt Deutschlands. | falsch | Berlin ist mit rund 3,7 Millionen Einwohnern fast doppelt so groß wie Hamburg.
W M | Die Elbe mündet in die Ostsee. | falsch | Die Elbe mündet bei Cuxhaven in die Nordsee.
S M | Wie viele Einwohner hat Deutschland ungefähr (in Millionen)? | 84 | Mio. | 5 | 10 | 200 | Mehr als 80 Millionen. ; Deutschland ist das bevölkerungsreichste EU-Land. ; Weniger als 90. | Deutschland hat rund 84 Millionen Einwohner (Stand 2023).
O M | Sortiere diese Städte von Norden nach Süden — die nördlichste zuerst. | Kiel = Schleswig-Holstein ; Hannover = Niedersachsen ; Frankfurt am Main = Hessen ; München = Bayern | Die erste liegt an der Ostsee. ; Die zweite ist Messestadt an der Leine. ; Die Bayern-Metropole liegt am südlichsten. | Kiel und München trennen rund 700 Kilometer Luftlinie.
M M | Welche ZWEI dieser Bundesländer grenzen an Frankreich? | Saarland ; Rheinland-Pfalz | Nordrhein-Westfalen ; Hessen ; Bayern ; Sachsen | Eines ist das kleinste Flächenland. ; Das andere hat Mainz als Hauptstadt. ; Baden-Württemberg fehlt in der Liste. | An Frankreich grenzen das Saarland, Rheinland-Pfalz und Baden-Württemberg.

@ europa
C E | In welchem Land leben Kängurus und Koalas in freier Wildbahn? | Australien | Neuseeland ; Südafrika ; Brasilien | Es ist ein Kontinent und ein Land zugleich. ; Die Hauptstadt ist Canberra. ; Der Uluru steht dort. | Kängurus und Koalas sind Beuteltiere und kommen natürlicherweise nur in Australien (und teils Neuguinea) vor.
C E | In welchem Land liegt die Stadt Amsterdam? | Niederlande | Belgien ; Dänemark ; Luxemburg | Die Stadt hat viele Grachten. ; Es ist die Hauptstadt des Landes. ; Das Land ist für Tulpen berühmt. | Amsterdam ist Hauptstadt der Niederlande, Regierungssitz ist aber Den Haag.
C E | Welches Land hat die meisten Einwohner in der EU? | Deutschland | Frankreich ; Italien ; Spanien | Das Land hat 16 Bundesländer. ; Rund 84 Millionen Menschen leben dort. ; Die Hauptstadt ist Berlin. | Nach Deutschland folgen Frankreich und Italien.
C M | Welcher Fluss bildet einen großen Teil der Grenze zwischen Deutschland und Polen? | Oder | Elbe ; Weichsel ; Spree | Zusammen mit der Neiße bildet er die Grenze. ; Frankfurt liegt auch an ihm. ; Der Name hat vier Buchstaben. | Die Oder-Neiße-Grenze wurde 1990 im Grenzvertrag endgültig anerkannt.
C H | Welches Land grenzt gleichzeitig an Deutschland, Frankreich und Belgien? | Luxemburg | Niederlande ; Schweiz ; Österreich | Es ist ein Großherzogtum. ; Die Hauptstadt trägt denselben Namen. ; Im Ort Schengen treffen sich die drei Grenzen. | Das Dreiländereck Deutschland–Frankreich–Luxemburg liegt bei Schengen an der Mosel.
C H | Welches europäische Land hat keinen eigenen Flughafen? | Liechtenstein | Luxemburg ; Malta ; Island | Es liegt zwischen der Schweiz und Österreich. ; Die Hauptstadt ist Vaduz. ; Man fliegt meist nach Zürich. | Auch Andorra, Monaco, San Marino und der Vatikan haben keinen eigenen Verkehrsflughafen.
C U | Welches ist das jüngste Mitglied der EU (Beitritt 2013)? | Kroatien | Bulgarien ; Rumänien ; Slowenien | Das Land liegt an der Adria. ; Dubrovnik liegt dort. ; Seit 2023 zahlt man dort mit Euro. | Kroatien trat am 1. Juli 2013 als 28. Mitglied bei.
W M | Island gehört zur Europäischen Union. | falsch | Island ist Mitglied im Europäischen Wirtschaftsraum und im Schengen-Raum, aber nicht in der EU.
S E | Wie viele Mitgliedstaaten hat die EU seit dem Brexit? | 27 | Staaten | 5 | 10 | 40 | Vorher waren es 28. ; Großbritannien ging 2020. ; Knapp unter 30. | Seit dem Austritt des Vereinigten Königreichs am 31. Januar 2020 hat die EU 27 Mitglieder.
O H | Sortiere diese Hauptstädte von West nach Ost — die westlichste zuerst. | Lissabon = Portugal ; Paris = Frankreich ; Berlin = Deutschland ; Warschau = Polen | Die erste liegt am Atlantik. ; Die zweite an der Seine. ; Die östlichste an der Weichsel. | Lissabon ist die westlichste Hauptstadt auf dem europäischen Festland.

@ laender_hauptstaedte
C E | Welche Sprache spricht man in Brasilien hauptsächlich? | Portugiesisch | Spanisch ; Brasilianisch ; Französisch | Das Land war eine Kolonie eines kleinen europäischen Landes. ; Es ist nicht Spanisch. ; Man spricht sie auch in Lissabon. | Brasilien ist das größte portugiesischsprachige Land der Welt.
C M | In welchem Land liegt der Kilimandscharo? | Tansania | Kenia ; Uganda ; Äthiopien | Das Land liegt in Ostafrika. ; Auch Sansibar gehört dazu. ; Der Berg liegt nahe der Grenze zu Kenia. | Der Kilimandscharo ist der höchste Berg Afrikas.
C M | In welchem Land liegt die legendäre Wüstenstadt Timbuktu? | Mali | Niger ; Mauretanien ; Tschad | Sie liegt am Rand der Sahara nahe dem Niger. ; Das Land liegt in Westafrika. ; Der Name hat vier Buchstaben. | Timbuktu war im Mittelalter ein Zentrum des Handels und der Gelehrsamkeit.
C H | Welches Land besteht aus über 17.000 Inseln? | Indonesien | Philippinen ; Japan ; Malaysia | Die Hauptstadt liegt auf Java. ; Bali gehört dazu. ; Es ist das größte Inselreich der Welt. | Von den rund 17.000 Inseln Indonesiens sind etwa 6000 bewohnt.
W M | Kanada ist das Land mit den meisten Seen der Welt. | wahr | Kanada hat mehr Seen als alle anderen Länder zusammen — geschätzt über zwei Millionen.
S H | An wie viele Länder grenzt die Schweiz? | 5 | Länder | 20 | 1 | 15 | Deutschland ist eines davon. ; Auch ein Fürstentum gehört dazu. ; Weniger als sechs. | Deutschland, Frankreich, Italien, Österreich und Liechtenstein.

@ staedte_wahrzeichen
C E | In welcher Stadt steht die Frauenkirche, die nach dem Krieg als Ruine blieb und 2005 wieder geweiht wurde? | Dresden | München ; Leipzig ; Nürnberg | Die Stadt liegt an der Elbe. ; Sie ist sächsische Landeshauptstadt. ; Die Kirche steht am Neumarkt. | Beim Wiederaufbau wurden viele originale Steine der Ruine wiederverwendet.
C E | In welchem Land liegt die Stadt Venedig mit ihren vielen Kanälen? | Italien | Frankreich ; Griechenland ; Kroatien | Man fährt dort Gondel. ; Die Hauptstadt ist Rom. ; Es hat die Form eines Stiefels. | Venedig besteht aus über 100 Inseln, die durch rund 400 Brücken verbunden sind.
C E | In welcher Stadt steht der Kreml? | Moskau | Sankt Petersburg ; Kiew ; Minsk | Direkt daneben liegt der Rote Platz. ; Dort ist der Amtssitz des russischen Präsidenten. ; Es ist die Hauptstadt Russlands. | „Kreml“ bedeutet Festung — auch andere russische Städte haben einen, der Moskauer ist aber der berühmteste.
C H | In welcher Stadt steht die Hängebrücke „Ponte 25 de Abril“, die der Golden Gate Bridge ähnelt? | Lissabon | Porto ; Rio de Janeiro ; Barcelona | Sie überspannt den Tejo. ; Gegenüber steht eine Christusstatue. ; Der Name erinnert an die Nelkenrevolution. | Die Brücke wurde 1966 eröffnet und trug zuerst den Namen des Diktators Salazar.
O M | Sortiere diese Städte nach ihrer Höhenlage über dem Meeresspiegel — die tiefste zuerst. | Amsterdam = ≈ 0 m ; Berlin = ≈ 34 m ; München = ≈ 519 m ; La Paz = ≈ 3600 m | Die erste liegt teils unter dem Meeresspiegel. ; Die deutsche Hauptstadt liegt im Flachland. ; Die südamerikanische Stadt liegt in den Anden. | München ist die höchstgelegene deutsche Millionenstadt.
@ europa
O E | Sortiere diese Hauptstädte von Norden nach Süden — die nördlichste zuerst. | Oslo = ≈ 60° N ; Berlin = ≈ 52° N ; Rom = ≈ 42° N ; Kairo = ≈ 30° N | Die erste liegt in Skandinavien. ; Die deutsche Hauptstadt folgt. ; Die afrikanische Stadt liegt am südlichsten. | Kairo liegt ungefähr auf demselben Breitengrad wie Florida.
M H | Welche ZWEI dieser Inseln gehören zu Griechenland? | Kreta ; Rhodos | Sardinien ; Korsika ; Malta ; Mallorca | Eine ist die größte griechische Insel. ; Auf der anderen stand ein antikes Weltwunder. ; Italien, Frankreich, ein Inselstaat und Spanien scheiden aus. | Auf Rhodos stand einst der Koloss von Rhodos.
C U | Wie heißt der höchste Berg Spaniens, ein Vulkan auf Teneriffa? | Pico del Teide | Mulhacén ; Aneto ; Roque Nublo | Er ist 3715 Meter hoch. ; Er liegt auf den Kanaren. ; Sein Name beginnt mit „Pico“. | Der Teide ist vom Meeresboden aus gemessen einer der höchsten Vulkane der Erde.
C U | Wie heißt der längste Fluss Frankreichs? | Loire | Seine ; Rhône ; Garonne | Er ist über 1000 Kilometer lang. ; An ihm stehen berühmte Schlösser. ; Er mündet bei Saint-Nazaire in den Atlantik. | Das Loiretal mit seinen Schlössern ist UNESCO-Welterbe.
S U | Wie viele Nachbarländer hat Österreich? | 8 | Länder | 15 | 2 | 15 | Deutschland ist eines davon. ; Auch Liechtenstein zählt. ; Mehr als sieben. | Deutschland, Tschechien, Slowakei, Ungarn, Slowenien, Italien, Schweiz und Liechtenstein.

@ laender_hauptstaedte
M E | Welche ZWEI dieser Länder liegen in Afrika? | Kenia ; Marokko | Peru ; Thailand ; Norwegen ; Kanada | Eines liegt am Äquator. ; Das andere gegenüber von Spanien. ; Südamerika, Asien, Europa und Nordamerika scheiden aus. | Afrika hat 54 Staaten.
M U | In welchen ZWEI dieser Länder sitzt die Regierung nicht in der offiziellen Hauptstadt? | Niederlande ; Bolivien | Frankreich ; Italien ; Japan ; Kanada | In einem ist Amsterdam Hauptstadt, Den Haag aber Regierungssitz. ; Im anderen ist Sucre Hauptstadt, La Paz Regierungssitz. ; Eines liegt in Europa, eines in Südamerika. | Auch in Côte d'Ivoire und Benin fallen Hauptstadt und Regierungssitz auseinander.

@ erd_rekorde
O H | Sortiere diese Flüsse nach ihrer Länge — den kürzesten zuerst. | Themse = ≈ 346 km ; Rhein = ≈ 1230 km ; Donau = ≈ 2850 km ; Nil = ≈ 6650 km | Der Londoner Fluss ist der kürzeste. ; Der Rhein ist kürzer als die Donau. ; Der afrikanische Strom ist der längste. | Der Nil gilt klassisch als längster Fluss der Erde, knapp vor dem Amazonas.

@ deutschland_geographie de
M U | Welche ZWEI dieser Bundesländer grenzen an Polen, haben aber keine Meeresküste? | Brandenburg ; Sachsen | Bayern ; Hessen ; Thüringen ; Niedersachsen | Eines umschließt Berlin. ; Das andere hat Dresden als Hauptstadt. ; Mecklenburg-Vorpommern grenzt auch an Polen — aber mit Küste. | Die deutsch-polnische Grenze verläuft entlang von Oder und Neiße.
"""
