"""Extra questions: Geschichte (format: see tools/content/merge_extra.py)."""
KAT = "geschichte"
REGION = "global"
DATA = r"""
@ mittelalter_ritter
C E | Wie nennt man die zahnartigen Aufsätze oben auf einer Burgmauer? | Zinnen | Erker ; Gauben ; Giebel | Dahinter konnten sich Verteidiger ducken. ; Sie sehen aus wie eine Zahnreihe. ; Das Wort reimt sich auf „drinnen“. | Durch die Lücken zwischen den Zinnen schossen die Verteidiger, hinter den Mauerzähnen fanden sie Deckung.
C E | Wie heißt der mit Wasser gefüllte Graben rund um viele Burgen? | Burggraben | Burgbach ; Wallsee ; Zwingerteich | Man überquerte ihn über eine Zugbrücke. ; Er sollte Angreifer fernhalten. ; Nicht jede Burg hatte Wasser darin. | Viele Burggräben waren gar nicht mit Wasser gefüllt — auch trockene Gräben hielten Belagerungstürme fern.
C E | Womit kämpften Ritter bei einem Turnier zu Pferd gegeneinander? | Mit einer Lanze | Mit einem Bogen ; Mit einer Schleuder ; Mit einer Armbrust | Es ist eine lange Stangenwaffe. ; Man versucht, den Gegner vom Pferd zu stoßen. ; Beim Tjost bricht sie oft. | Turnierlanzen waren oft hohl oder hatten stumpfe Spitzen, damit sie beim Aufprall brachen.
C E | Welches Tier war für einen Ritter am wichtigsten? | Das Pferd | Der Hund ; Der Falke ; Der Esel | Das Wort „Ritter“ kommt von „reiten“. ; Schwere Rüstung verlangte ein starkes Tier. ; Ein Streitross war sehr teuer. | Ein gutes Schlachtross war extrem teuer — oft ein Vielfaches des Jahreseinkommens eines Bauern.
C E | Wie hieß die Sprache, in der im Mittelalter Gelehrte und Kirche vor allem schrieben? | Latein | Griechisch ; Hebräisch ; Französisch | Es war die Sprache der Römer. ; In ihr wurde die Messe gelesen. ; Viele Fremdwörter der Medizin stammen daraus. | Latein blieb bis weit in die Neuzeit Sprache der Wissenschaft und Kirche.
C E | Welcher sagenhafte Held mit Pfeil und Bogen soll im Sherwood Forest die Reichen bestohlen haben? | Robin Hood | Wilhelm Tell ; Lancelot ; Ivanhoe | Er trägt oft Grün. ; Sein Gegner ist der Sheriff von Nottingham. ; Seine Geliebte heißt Marian. | Die ältesten Balladen über Robin Hood stammen aus dem 15. Jahrhundert.
C M | Welches Dokument musste der englische König Johann Ohneland 1215 unterzeichnen? | Magna Carta | Bill of Rights ; Goldene Bulle ; Habeas-Corpus-Akte | Der Name ist lateinisch. ; Es heißt „Große Urkunde“. ; Es beschränkte die Macht des Königs. | Die Magna Carta gilt als ein Meilenstein auf dem Weg zu Grundrechten und Rechtsstaat.
C M | Welcher berühmte, rund 70 Meter lange Bildteppich zeigt die Schlacht von Hastings? | Teppich von Bayeux | Teppich von Aachen ; Teppich von Chartres ; Teppich von Canterbury | Er hängt in der Normandie. ; Genau genommen ist er eine Stickerei. ; Auch der Halleysche Komet ist darauf zu sehen. | Der Teppich von Bayeux entstand um 1070 und ist UNESCO-Weltdokumentenerbe.
C H | In welcher Schlacht besiegte Otto der Große 955 die Ungarn? | Schlacht auf dem Lechfeld | Schlacht bei Tours ; Schlacht bei Hastings ; Schlacht am Kahlenberg | Sie fand bei Augsburg statt. ; Ein Fluss gab ihr den Namen. ; Danach endeten die Ungarneinfälle. | Nach dem Sieg auf dem Lechfeld wurde Otto 962 zum Kaiser gekrönt.
C M | Welche Stadt fiel 1453 an die Osmanen — ein Datum, das oft als Ende des Mittelalters gilt? | Konstantinopel | Rom ; Athen ; Venedig | Heute heißt sie Istanbul. ; Sie war Hauptstadt des Byzantinischen Reiches. ; Sultan Mehmed II. eroberte sie. | Mit dem Fall Konstantinopels endete das Oströmische Reich nach über 1000 Jahren.
C M | Welche Äbtissin des 12. Jahrhunderts schrieb über Heilkunde und komponierte geistliche Musik? | Hildegard von Bingen | Elisabeth von Thüringen ; Katharina von Siena ; Roswitha von Gandersheim | Ihr Kloster lag am Rhein. ; Sie gilt als Kirchenlehrerin. ; Ihre Kräuterkunde ist bis heute beliebt. | Hildegard von Bingen (1098–1179) wurde 2012 zur Kirchenlehrerin erhoben.
C M | Wie nannte man den Gefolgsmann, der im Lehnswesen Land von einem Herrn erhielt und ihm Treue schuldete? | Vasall | Leibeigener ; Knappe ; Vogt | Das Wort bedeutet ursprünglich „Knecht“. ; Er schwor seinem Lehnsherrn Treue. ; Heute spricht man noch von „Vasallenstaaten“. | Das Lehen war ursprünglich auf Lebenszeit verliehen, wurde aber später erblich.
C M | Wie hieß die Anbaumethode, bei der Felder abwechselnd mit Winterkorn, Sommerkorn und Brache bestellt wurden? | Dreifelderwirtschaft | Zweifelderwechsel ; Fruchtwechselwirtschaft ; Terrassenbau | Die Zahl steckt im Namen. ; Ein Drittel blieb jeweils unbestellt. ; Sie verbreitete sich ab dem 8. Jahrhundert. | Die Dreifelderwirtschaft steigerte die Erträge im Mittelalter deutlich.
C M | Zu welchem Pilgerziel in Spanien führt der Jakobsweg? | Santiago de Compostela | Sevilla ; Toledo ; Montserrat | Dort soll der Apostel Jakobus begraben sein. ; Es liegt in Galicien. ; Die Pilger tragen eine Muschel. | Die Jakobsmuschel ist bis heute das Erkennungszeichen der Pilger.
C H | Welcher Welfenherzog gründete 1158 München und später Lübeck neu? | Heinrich der Löwe | Friedrich Barbarossa ; Otto der Große ; Heinrich IV. | Sein Wappentier steht in Braunschweig. ; Er war Herzog von Sachsen und Bayern. ; Er stritt sich mit Barbarossa. | Heinrich zerstörte eine Zollbrücke bei Freising und baute bei den „Mönchen“ eine neue — so entstand München.
C H | Welcher Frankenherrscher stoppte 732 zwischen Tours und Poitiers ein arabisches Heer? | Karl Martell | Karl der Große ; Pippin der Kurze ; Chlodwig | Sein Beiname bedeutet „der Hammer“. ; Er war der Großvater Karls des Großen. ; Er war Hausmeier, kein König. | Karl Martell wurde nach der Schlacht zum mächtigsten Mann im Frankenreich.
C H | Mit dem Überfall auf welches englische Kloster 793 beginnt traditionell die Wikingerzeit? | Lindisfarne | Canterbury ; Iona ; Whitby | Es liegt auf einer Gezeiteninsel. ; Die Insel heißt auch „Holy Island“. ; Ein berühmtes Evangeliar stammt von dort. | Der Überfall auf Lindisfarne am 8. Juni 793 schockierte das christliche Europa.
C H | Welche ist die älteste Universität auf dem Gebiet des heutigen Deutschland? | Heidelberg | Köln ; Leipzig ; Tübingen | Sie wurde 1386 gegründet. ; Sie liegt am Neckar. ; Über der Stadt thront eine Schlossruine. | Ältere deutschsprachige Universitäten gab es in Prag (1348) und Wien (1365).
C U | Welcher Habsburger wurde 1273 zum König gewählt und beendete das sogenannte Interregnum? | Rudolf von Habsburg | Maximilian I. ; Karl V. ; Albrecht I. | Er war der erste Habsburger auf dem Thron. ; Er besiegte 1278 Ottokar von Böhmen. ; Sein Vorname ist Rudolf. | Mit Rudolf I. begann der Aufstieg der Habsburger zur mächtigsten Dynastie Europas.
C H | Wie nannte man den Vorbau an einer Burgmauer, durch dessen Bodenöffnung man Steine oder heißes Wasser auf Angreifer warf? | Pechnase | Schießscharte ; Wehrgang ; Barbakane | Der Name enthält eine klebrige schwarze Masse. ; Er hängt wie ein Erker an der Mauer. ; Auch ein Gesichtsteil steckt im Namen. | Heißes Pech war teuer — meist warf man eher Steine oder kochendes Wasser.
C H | An welchem Tag ließ der französische König 1307 die Tempelritter verhaften — Ursprung eines Aberglaubens? | Freitag, der 13. | Montag, der 1. ; Sonntag, der 7. ; Mittwoch, der 11. | Das Datum gilt vielen als Unglückstag. ; Es war im Oktober. ; Die Zahl ist eine Primzahl über zehn. | Der Zusammenhang mit dem Unglückstag ist populär, historisch aber nicht belegt.
C U | Auf welcher Burg in der Pfalz wurde der englische König Richard Löwenherz 1193 gefangen gehalten? | Burg Trifels | Burg Eltz ; Wartburg ; Burg Hohenzollern | Hier wurden auch die Reichskleinodien aufbewahrt. ; Sie liegt bei Annweiler. ; Zuvor saß er in Dürnstein an der Donau. | Für Richard wurde ein gewaltiges Lösegeld von 150.000 Mark Silber gezahlt.
C U | Wie hieß die heilige Landgräfin und Wohltäterin, die auf der Wartburg lebte und das „Rosenwunder“ bewirkt haben soll? | Elisabeth von Thüringen | Hildegard von Bingen ; Kunigunde von Luxemburg ; Mathilde von Tuszien | Brot in ihrem Korb verwandelte sich in Rosen. ; Sie starb mit 24 Jahren in Marburg. ; Sie stammte aus Ungarn. | Elisabeth wurde schon 1235, vier Jahre nach ihrem Tod, heiliggesprochen.
C U | Welcher Rechtsgrundsatz besagte, dass Leibeigene nach „Jahr und Tag“ in einer Stadt frei wurden? | Stadtluft macht frei | Wer zuerst kommt, mahlt zuerst ; Wo kein Kläger, da kein Richter ; Gleiches Recht für alle | Es geht um die Flucht in die Stadt. ; Man musste ein Jahr und einen Tag bleiben. ; Das Sprichwort nennt die Luft. | Der Grundsatz galt nicht überall, war aber ein wichtiger Anreiz für den Zuzug in mittelalterliche Städte.
W E | Ritter trugen in der Schlacht immer schwere Plattenrüstungen. | falsch | Lange Zeit trugen Ritter Kettenhemden; vollständige Plattenrüstungen kamen erst im Spätmittelalter auf.
W M | Die großen Hexenverfolgungen erreichten ihren Höhepunkt erst in der frühen Neuzeit, nicht im Mittelalter. | wahr | Die meisten Hexenprozesse fanden zwischen etwa 1550 und 1650 statt.
W M | Die Menschen im Mittelalter badeten niemals. | falsch | Öffentliche Badehäuser waren in mittelalterlichen Städten weit verbreitet und beliebte Treffpunkte.
W H | Karl der Große konnte zeitlebens wohl nicht fließend schreiben. | wahr | Sein Biograf Einhard berichtet, dass Karl das Schreiben erst spät übte und es nie richtig beherrschte.
S M | Um welches Jahr endet das Mittelalter nach gängiger Einteilung ungefähr? | 1500 | Jahr | 3 | 1000 | 2000 | Kolumbus erreichte kurz zuvor Amerika. ; Der Buchdruck war gerade erfunden. ; Eine runde Zahl. | Als Epochengrenze gelten meist Ereignisse um 1450–1517: Buchdruck, Fall Konstantinopels, Entdeckung Amerikas, Reformation.
S H | In welchem Jahr unterzeichnete König Johann Ohneland die Magna Carta? | 1215 | Jahr | 3 | 1000 | 1500 | Anfang des 13. Jahrhunderts. ; Es war auf einer Wiese namens Runnymede. ; Das Jahr endet auf 15. | Die Magna Carta wurde am 15. Juni 1215 besiegelt.
O M | Sortiere diese Ereignisse chronologisch — das früheste zuerst. | Kaiserkrönung Karls des Großen = 800 ; Schlacht von Hastings = 1066 ; Magna Carta = 1215 ; Fall Konstantinopels = 1453 | Zuerst krönte der Papst in Rom. ; Dann eroberten die Normannen England. ; Die Osmanen kommen zum Schluss. | Diese vier Daten spannen das Mittelalter von der Karolingerzeit bis zu seinem Ende auf.
O H | Sortiere diese Herrscher nach dem Beginn ihrer Regierung — den frühesten zuerst. | Karl der Große = 768 ; Otto der Große = 936 ; Friedrich Barbarossa = 1152 ; Rudolf von Habsburg = 1273 | Der Frankenkönig kommt zuerst. ; Der Sieger vom Lechfeld folgt. ; Der erste Habsburger ist der letzte. | Rund 500 Jahre liegen zwischen Karls Herrschaftsantritt und dem ersten Habsburger auf dem Thron.
M M | Welche ZWEI dieser Gebäudeteile gehören typischerweise zu einer mittelalterlichen Burg? | Bergfried ; Zugbrücke | Minarett ; Kuppelbau ; Glockenturm aus Stahl ; Wintergarten | Einer ist der höchste Turm. ; Der andere lässt sich hochziehen. ; Moderne oder orientalische Bauteile scheiden aus. | Bergfried, Palas, Ringmauer und Zugbrücke sind typische Elemente einer Burg.

@ zwanzigstes_jahrhundert
C E | Welche Königin regierte das Vereinigte Königreich von 1952 bis 2022? | Elizabeth II. | Victoria ; Anne ; Margaret | Sie regierte 70 Jahre lang. ; Ihr Nachfolger ist ihr Sohn Charles. ; Ihr Vater war Georg VI. | Elizabeth II. war die am längsten regierende Monarchin der britischen Geschichte.
C E | Welches Land schickte 1961 den ersten Menschen ins All? | Sowjetunion | USA ; China ; Großbritannien | Der Kosmonaut hieß Juri Gagarin. ; Das Land zerfiel 1991. ; Seine Hauptstadt war Moskau. | Gagarin umrundete die Erde am 12. April 1961 in 108 Minuten.
C E | In welcher Stadt wurde 1961 eine Mauer gebaut, die bis 1989 stand? | Berlin | Wien ; Prag ; Warschau | Die Mauer teilte Ost und West. ; Sie fiel im November 1989. ; Es ist die deutsche Hauptstadt. | Die Berliner Mauer wurde am 13. August 1961 errichtet.
C E ab12 | Auf welche japanische Stadt wurde am 6. August 1945 die erste Atombombe abgeworfen? | Hiroshima | Nagasaki ; Tokio ; Osaka | Drei Tage später folgte eine zweite Bombe auf eine andere Stadt. ; Heute steht dort ein Friedenspark. ; Die Stadt liegt im Westen der Hauptinsel Honshū. | Der Friedenspark und die Atombombenkuppel in Hiroshima erinnern an die Opfer.
C M ab12 | Welches britische Passagierschiff wurde 1915 von einem deutschen U-Boot versenkt? | Lusitania | Titanic ; Britannic ; Queen Mary | Fast 1200 Menschen starben, darunter viele Amerikaner. ; Es sank vor der Südküste Irlands. ; Der Name ist die lateinische Bezeichnung für Portugal. | Die Versenkung der Lusitania trug dazu bei, die öffentliche Meinung in den USA gegen Deutschland zu wenden.
C M | Wie hieß der Friedensvertrag, der 1919 den Ersten Weltkrieg für Deutschland formell beendete? | Vertrag von Versailles | Vertrag von Locarno ; Vertrag von Rapallo ; Frieden von Brest-Litowsk | Er wurde in einem Schloss bei Paris unterzeichnet. ; Im Spiegelsaal. ; Genau dort war 1871 das Deutsche Kaiserreich ausgerufen worden. | Der Versailler Vertrag wurde am 28. Juni 1919 unterzeichnet — fünf Jahre nach dem Attentat von Sarajevo.
C M | Welcher Revolutionär führte 1917 die Bolschewiki in Russland an die Macht? | Wladimir Lenin | Josef Stalin ; Leo Trotzki ; Nikita Chruschtschow | Er war zuvor im Schweizer Exil. ; Die Stadt Sankt Petersburg trug später seinen Namen. ; Sein Leichnam liegt in einem Mausoleum in Moskau. | Lenin reiste im April 1917 mit deutscher Hilfe im „plombierten Wagen“ aus der Schweiz nach Russland.
C M | Wie nennt man den Börsenkrach von 1929, der die Weltwirtschaftskrise auslöste? | Schwarzer Donnerstag | Blauer Montag ; Roter Freitag ; Grauer Mittwoch | Er begann an der New Yorker Wall Street. ; Er war im Oktober. ; In Europa sprach man vom „Schwarzen Freitag“. | Am 24. Oktober 1929 brachen die Kurse ein — wegen der Zeitverschiebung sprach man in Europa vom Freitag.
C M | Welcher US-Präsident wurde als einziger viermal gewählt? | Franklin D. Roosevelt | Theodore Roosevelt ; Harry S. Truman ; Dwight D. Eisenhower | Er führte die USA durch die Große Depression. ; Er saß im Rollstuhl. ; Sein „New Deal“ ist berühmt. | Seit 1951 begrenzt der 22. Verfassungszusatz die Präsidentschaft auf zwei Amtszeiten.
C M ab12 | In welcher Stadt wurde US-Präsident John F. Kennedy 1963 erschossen? | Dallas | Houston ; Washington ; Chicago | Die Stadt liegt in Texas. ; Er fuhr im offenen Wagen. ; Der Platz heißt Dealey Plaza. | Kennedy wurde am 22. November 1963 in Dallas ermordet.
C M | Welcher US-Präsident trat 1974 wegen der Watergate-Affäre zurück? | Richard Nixon | Gerald Ford ; Lyndon B. Johnson ; Jimmy Carter | Er war Republikaner. ; Er ist bislang der einzige zurückgetretene US-Präsident. ; Er hatte zuvor China besucht. | Nixon trat am 9. August 1974 zurück, um einer Amtsenthebung zuvorzukommen.
C M | Welches Land wurde im Mai 1948 gegründet? | Israel | Indien ; Pakistan ; Jordanien | Der erste Ministerpräsident hieß David Ben-Gurion. ; Die Staatsgründung wurde in Tel Aviv ausgerufen. ; Auf der Flagge steht ein Davidstern. | Ben-Gurion verlas die Unabhängigkeitserklärung am 14. Mai 1948.
C H ab12 | Welcher US-Hafen auf Hawaii wurde am 7. Dezember 1941 von Japan angegriffen? | Pearl Harbor | Honolulu Bay ; Midway ; Guam | Der Name enthält ein Schmuckstück. ; Danach traten die USA in den Zweiten Weltkrieg ein. ; Er liegt auf der Insel Oʻahu. | Präsident Roosevelt nannte den Tag „a date which will live in infamy“.
C H | Wer rief 1949 in Peking die Volksrepublik China aus? | Mao Zedong | Sun Yat-sen ; Deng Xiaoping ; Chiang Kai-shek | Sein Porträt hängt am Tor des Himmlischen Friedens. ; Er führte den „Langen Marsch“. ; Man nannte ihn „den Großen Vorsitzenden“. | Mao proklamierte die Volksrepublik am 1. Oktober 1949.
C H | Wie hieß die Reformbewegung in der Tschechoslowakei 1968, die von Truppen des Warschauer Pakts beendet wurde? | Prager Frühling | Samtene Revolution ; Solidarność ; Tauwetter | Sie wollte einen „Sozialismus mit menschlichem Antlitz“. ; An ihrer Spitze stand Alexander Dubček. ; Eine Jahreszeit steckt im Namen. | Im August 1968 marschierten Truppen des Warschauer Pakts ein und beendeten die Reformen.
C H | Wie hieß die polnische Gewerkschaft, die ab 1980 unter Lech Wałęsa gegen die Regierung kämpfte? | Solidarność | Charta 77 ; Neues Forum ; Glasnost | Sie entstand auf der Danziger Werft. ; Der Name bedeutet „Solidarität“. ; Ihr Anführer wurde später Präsident. | Wałęsa erhielt 1983 den Friedensnobelpreis und war 1990–1995 Präsident Polens.
C H | Wer wurde 1979 die erste Premierministerin Großbritanniens? | Margaret Thatcher | Theresa May ; Barbara Castle ; Indira Gandhi | Man nannte sie die „Eiserne Lady“. ; Sie war Konservative. ; Sie regierte bis 1990. | Thatcher war mit elf Jahren die am längsten amtierende britische Premierministerin des 20. Jahrhunderts.
C H | Welche Stadt fiel 1975 an Nordvietnam und markierte das Ende des Vietnamkriegs? | Saigon | Hanoi ; Huế ; Da Nang | Sie heißt heute Ho-Chi-Minh-Stadt. ; Hubschrauber evakuierten die US-Botschaft. ; Sie liegt im Süden. | Mit dem Fall Saigons am 30. April 1975 endete der Vietnamkrieg.
C U | Wer wurde 1960 in Sri Lanka (Ceylon) die erste gewählte Regierungschefin der Welt? | Sirimavo Bandaranaike | Indira Gandhi ; Golda Meir ; Benazir Bhutto | Ihr Mann war zuvor ermordet worden. ; Ihre Tochter wurde später Präsidentin. ; Ihr Nachname beginnt mit B. | Bandaranaike war insgesamt dreimal Premierministerin ihres Landes.
C U ab12 | In welcher Stadt marschierten Mussolinis Anhänger 1922, bevor er Regierungschef wurde? | Rom | Mailand ; Neapel ; Turin | Das Ereignis heißt „Marsch auf ...“. ; Es ist die Hauptstadt Italiens. ; König Viktor Emanuel III. gab nach. | Nach dem „Marsch auf Rom“ ernannte der König Mussolini Ende Oktober 1922 zum Ministerpräsidenten.
C U | In welchem Schloss berieten Truman, Stalin und Churchill bzw. Attlee im Sommer 1945 über Deutschlands Zukunft? | Schloss Cecilienhof | Schloss Sanssouci ; Schloss Bellevue ; Schloss Charlottenburg | Es liegt in Potsdam. ; Es sieht aus wie ein englisches Landhaus. ; Es ist nach einer Kronprinzessin benannt. | Im Potsdamer Abkommen vom 2. August 1945 legten die Siegermächte die Grundsätze der Besatzungspolitik fest.
W E | Die Sowjetunion zerfiel bereits im Jahr 1989. | falsch | 1989 fiel die Berliner Mauer; die Sowjetunion löste sich erst am 26. Dezember 1991 auf.
W E | Die erste Mondlandung fand im Jahr 1972 statt. | falsch | Apollo 11 landete 1969; 1972 flog mit Apollo 17 die bislang letzte bemannte Mondmission.
W M | Fidel Castro übernahm nach der Revolution 1959 die Macht in Kuba. | wahr | Castro regierte Kuba fast 50 Jahre lang, bis er die Macht 2008 an seinen Bruder Raúl übergab.
W H | Che Guevara stammte ursprünglich aus Kuba. | falsch | Ernesto „Che“ Guevara wurde 1928 in Argentinien geboren und war ausgebildeter Arzt.
S E | In welchem Jahr begann der Zweite Weltkrieg? | 1939 | Jahr | 1 | 1900 | 1960 | Ende der 1930er-Jahre. ; Am 1. September. ; Das Jahr endet auf 9. | Der Krieg begann am 1. September 1939 mit dem deutschen Überfall auf Polen.
S U | Wie viele Tage dauerte die Berliner Luftbrücke ungefähr? | 462 | Tage | 15 | 30 | 2000 | Mehr als ein Jahr. ; Sie ging von Juni 1948 bis Mai 1949 (Flüge noch bis September). ; Etwa 15 Monate. | Die Flüge liefen vom 26. Juni 1948 bis zum 30. September 1949 — rund 462 Tage.
O M | Sortiere diese Ereignisse des 20. Jahrhunderts chronologisch. | Russische Oktoberrevolution = 1917 ; Börsenkrach in New York = 1929 ; Gründung Israels = 1948 ; Mondlandung = 1969 | Zuerst kam eine Revolution in Russland. ; Dann ein Crash an der Wall Street. ; Ganz zuletzt ein Schritt auf dem Mond. | Zwischen Oktoberrevolution und Mondlandung liegen nur 52 Jahre.
O H | Sortiere diese Staatschefs nach Beginn ihrer Amtszeit — den frühesten zuerst. | Winston Churchill (1. Amtszeit) = 1940 ; John F. Kennedy = 1961 ; Margaret Thatcher = 1979 ; Michail Gorbatschow = 1985 | Der Brite mit Zigarre kam im Krieg ins Amt. ; Der US-Präsident folgte zwei Jahrzehnte später. ; Der sowjetische Reformer war der Letzte. | Gorbatschow wurde im März 1985 Generalsekretär der KPdSU.
M M | Welche ZWEI dieser Länder waren im Zweiten Weltkrieg Verbündete der USA? | Großbritannien ; Sowjetunion | Japan ; Italien ; Ungarn ; Rumänien | Eines ist eine Insel in Europa. ; Das andere war später Gegner im Kalten Krieg. ; Die Achsenmächte scheiden aus. | Großbritannien, die USA und die Sowjetunion bildeten die „Großen Drei“ der Anti-Hitler-Koalition.

@ antike
C E | Welches Tier säugte der Sage nach die Gründer Roms, Romulus und Remus? | Eine Wölfin | Eine Bärin ; Eine Ziege ; Eine Löwin | Die „Kapitolinische ...“ ist eine berühmte Bronzefigur. ; Das Tier heult den Mond an. ; Es ist ein Raubtier. | Die Bronzefigur der Kapitolinischen Wölfin ist ein Symbol Roms.
C E | Welche Sprache sprachen die alten Römer? | Latein | Griechisch ; Italienisch ; Etruskisch | Viele Fremdwörter stammen daraus. ; Aus ihr entstanden Französisch und Spanisch. ; Man lernt sie oft im Gymnasium. | Aus dem Vulgärlatein entwickelten sich die romanischen Sprachen.
C M | Welchen Fluss überschritt Julius Cäsar 49 v. Chr. mit den Worten „Die Würfel sind gefallen“? | Rubikon | Tiber ; Rhein ; Po | Der Fluss markierte die Grenze Italiens. ; Heute sagt man „den ... überschreiten“ für einen Punkt ohne Umkehr. ; Er liegt bei Rimini. | Mit der Überschreitung begann der Bürgerkrieg gegen Pompeius.
C M | Welcher Sklave führte ab 73 v. Chr. einen großen Aufstand gegen Rom an? | Spartacus | Vercingetorix ; Hannibal ; Arminius | Er war Gladiator. ; Er stammte aus Thrakien. ; Kirk Douglas spielte ihn 1960 im Film. | Der Aufstand wurde 71 v. Chr. von Crassus niedergeschlagen.
C M | Welcher römische Kaiser ließ im Norden Britanniens einen 117 Kilometer langen Wall bauen? | Hadrian | Trajan ; Augustus ; Nero | Der Wall trägt seinen Namen. ; Er reiste durch das ganze Reich. ; Er trug als einer der ersten Kaiser einen Bart. | Der Hadrianswall entstand ab 122 n. Chr. und ist heute UNESCO-Welterbe.
C M | Wessen Grab entdeckte Howard Carter 1922 im Tal der Könige? | Tutanchamun | Ramses II. ; Cheops ; Echnaton | Er war ein junger Pharao. ; Seine goldene Totenmaske ist weltberühmt. ; Das Grab war fast unberührt. | Tutanchamun starb mit etwa 19 Jahren; sein Grab enthielt über 5000 Objekte.
C H | In welchem Berliner Museum steht die Büste der ägyptischen Königin Nofretete? | Neues Museum | Pergamonmuseum ; Altes Museum ; Bode-Museum | Es liegt auf der Museumsinsel. ; Es wurde nach Kriegszerstörung 2009 wiedereröffnet. ; Der Name ist das Gegenteil eines anderen Museums. | Die Büste wurde 1912 bei Ausgrabungen in Amarna gefunden.
C H | Welcher chinesische Kaiser ließ sich mit Tausenden Terrakotta-Kriegern begraben? | Qin Shi Huang | Kublai Khan ; Kaiser Wu ; Puyi | Er einte China 221 v. Chr. ; Nach seiner Dynastie ist China vermutlich benannt. ; Die Armee steht bei Xi'an. | Die Terrakotta-Armee wurde 1974 von Bauern beim Brunnenbohren entdeckt.
C H | Unter welchem Kaiser brannte Rom im Jahr 64 n. Chr.? | Nero | Caligula ; Tiberius ; Claudius | Er soll während des Brandes gesungen haben — eine Legende. ; Er gab den Christen die Schuld. ; Danach baute er einen goldenen Palast. | Nero ließ nach dem Brand die prachtvolle „Domus Aurea“ errichten.
C U | Wofür steht die römische Abkürzung „SPQR“? | Senatus Populusque Romanus | Salus Publica Quirites Romae ; Senatus Pax Quinta Roma ; Sacra Porta Quirinalis Romae | Es geht um Senat und Volk. ; Die Abkürzung steht noch heute auf Kanaldeckeln in Rom. ; Das Q steht für „-que“, also „und“. | SPQR bedeutet „Der Senat und das Volk von Rom“.
W M | Die Olympischen Spiele der Antike fanden alle vier Jahre statt. | wahr | Die Olympiade, der Zeitraum von vier Jahren, war sogar eine griechische Zeitrechnung.
S U | In welchem Jahr fanden der Überlieferung nach die ersten antiken Olympischen Spiele statt (v. Chr.)? | 776 | Jahr v. Chr. | 10 | 100 | 1500 | Es war im 8. Jahrhundert vor Christus. ; Rund 20 Jahre vor der sagenhaften Gründung Roms. ; Die Zahl beginnt mit 7. | Die Siegerliste von Olympia beginnt 776 v. Chr. mit dem Läufer Koroibos.

@ deutsche_geschichte de
C E | Welches Bundesland hat Hannover als Landeshauptstadt? | Niedersachsen | Hessen ; Sachsen ; Schleswig-Holstein | Das Wappen zeigt ein weißes Pferd. ; Es ist flächenmäßig das zweitgrößte Bundesland. ; Es grenzt an die Nordsee. | Das Sachsenross im Wappen erinnert an die alten Welfen.
C E | An welchem Datum wurde 1961 mit dem Bau der Berliner Mauer begonnen? | 13. August | 9. November ; 3. Oktober ; 17. Juni | Es war ein Sonntag im Sommer. ; Ulbricht hatte kurz zuvor gesagt, niemand habe die Absicht, eine Mauer zu errichten. ; Die Zahl ist eine Unglückszahl. | In der Nacht zum 13. August 1961 riegelten DDR-Kräfte die Sektorengrenze ab.
C M | In welchem Jahr wurde die Bundeswehr gegründet? | 1955 | 1949 ; 1961 ; 1950 | Im selben Jahr trat die Bundesrepublik der NATO bei. ; Zehn Jahre nach Kriegsende. ; Das Jahr endet auf 5. | Die ersten 101 Freiwilligen erhielten am 12. November 1955 ihre Ernennungsurkunden.
C M | Vor welchem Kaiser musste Martin Luther 1521 auf dem Reichstag zu Worms seine Schriften verteidigen? | Karl V. | Maximilian I. ; Friedrich III. ; Ferdinand I. | In seinem Reich ging die Sonne nie unter. ; Er war auch König von Spanien. ; Er war ein Habsburger. | Luther weigerte sich zu widerrufen und wurde mit der Reichsacht belegt.
C M | In welchem Jahr fand die erste Wahl zum Deutschen Bundestag statt? | 1949 | 1945 ; 1950 ; 1953 | Im selben Jahr trat das Grundgesetz in Kraft. ; Konrad Adenauer wurde danach Kanzler. ; Es war vier Jahre nach Kriegsende. | Die erste Bundestagswahl fand am 14. August 1949 statt.
C H | Welcher Kaiser regierte das Deutsche Reich von 1888 bis 1918? | Wilhelm II. | Wilhelm I. ; Friedrich III. ; Friedrich Wilhelm IV. | Er entließ 1890 Bismarck. ; Er trug einen gezwirbelten Schnurrbart. ; Er ging 1918 ins niederländische Exil. | Wilhelm II. lebte bis zu seinem Tod 1941 in Doorn in den Niederlanden.
C H | Wie hieß die Stadt, in der 1949 der Parlamentarische Rat das Grundgesetz beschloss? | Bonn | Frankfurt am Main ; Weimar ; Berlin | Sie liegt am Rhein. ; Sie wurde danach vorläufige Hauptstadt. ; Beethoven wurde dort geboren. | Das Grundgesetz trat am 23. Mai 1949 in Kraft.
C U | Welcher Politiker war erster Ministerpräsident von Nordrhein-Westfalen? | Rudolf Amelunxen | Karl Arnold ; Johannes Rau ; Heinrich Lübke | Er wurde 1946 von der britischen Besatzungsmacht ernannt. ; Er gehörte zunächst keiner Partei an. ; Sein Nachfolger Karl Arnold war der erste gewählte. | Amelunxen war 1946/47 Ministerpräsident, später Minister unter Karl Arnold.
W M | Die Bundesrepublik Deutschland und die DDR wurden beide im Jahr 1949 gegründet. | wahr | Die Bundesrepublik entstand am 23. Mai 1949, die DDR am 7. Oktober 1949.
O M | Sortiere diese Ereignisse der deutschen Geschichte chronologisch. | Reformation (Thesenanschlag) = 1517 ; Gründung des Kaiserreichs = 1871 ; Grundgesetz tritt in Kraft = 1949 ; Mauerfall = 1989 | Zuerst predigte ein Mönch in Wittenberg. ; Dann wurde in Versailles ein Kaiser ausgerufen. ; Zuletzt öffnete sich die Grenze in Berlin. | Diese vier Daten gehören zu den bekanntesten Wendepunkten der deutschen Geschichte.

@ ddr_wiedervereinigung de
C M | Wie hieß die feierliche Aufnahme 14-Jähriger ins Erwachsenenleben, die in der DDR die Konfirmation ersetzte? | Jugendweihe | Pioniertaufe ; Staatsfirmung ; FDJ-Weihe | Sie findet bis heute in Ostdeutschland statt. ; Man bekam oft Geschenke und ein Buch. ; Das Wort enthält „Jugend“. | Die Jugendweihe ist in Ostdeutschland bis heute verbreitet.
C M | Wie hieß die Armee der DDR? | Nationale Volksarmee | Rote Armee ; Volkspolizei ; Deutsche Volkswehr | Die Abkürzung ist NVA. ; Sie wurde 1956 gegründet. ; 1990 wurde sie teils in die Bundeswehr übernommen. | Die NVA hatte zuletzt rund 170.000 Soldaten.
C U | Wie hieß die Schulform, die in der DDR alle Kinder zehn Jahre lang besuchten? | Polytechnische Oberschule | Gesamtschule ; Realschule ; Volksschule | Die Abkürzung war POS. ; Praktischer Unterricht in Betrieben gehörte dazu. ; Danach ging es zur EOS oder in die Lehre. | Wer Abitur machte, wechselte auf die Erweiterte Oberschule (EOS).
W U | Das Sandmännchen des DDR-Fernsehens lief erstmals einige Tage vor dem westdeutschen Sandmännchen. | wahr | Das Ost-Sandmännchen startete am 22. November 1959, das West-Sandmännchen des SFB am 1. Dezember 1959.
S M | Wie viele Jahre bestand die DDR ungefähr? | 41 | Jahre | 10 | 10 | 100 | Sie wurde 1949 gegründet. ; Sie endete 1990. ; Mehr als 40. | Die DDR bestand vom 7. Oktober 1949 bis zum 3. Oktober 1990 — knapp 41 Jahre.
M M | Welche ZWEI dieser Städte lagen auf dem Gebiet der DDR? | Leipzig ; Rostock | Hannover ; Kassel ; Lübeck ; Nürnberg | Eine ist für die Montagsdemonstrationen bekannt. ; Die andere hat einen großen Ostseehafen. ; Die westdeutschen Städte scheiden aus. | Leipzig in Sachsen und Rostock in Mecklenburg gehörten zur DDR.

@ persoenlichkeiten_entdecker
C E | Welcher französische König nannte sich „Sonnenkönig“? | Ludwig XIV. | Ludwig XVI. ; Napoleon ; Karl der Große | Er ließ Schloss Versailles ausbauen. ; Er regierte 72 Jahre lang. ; Ihm wird „Der Staat bin ich“ zugeschrieben. | Ludwig XIV. regierte von 1643 bis 1715 — länger als jeder andere europäische Monarch.
C E | Wie wurde Kaiserin Elisabeth von Österreich-Ungarn genannt? | Sisi | Lilly ; Liesl ; Betty | Sie stammte aus Bayern. ; Romy Schneider spielte sie im Film. ; Ihr Spitzname hat vier Buchstaben. | Elisabeth wurde 1898 in Genf von einem Anarchisten ermordet.
C M | Welche britische Krankenschwester wurde im Krimkrieg als „Lady mit der Lampe“ bekannt? | Florence Nightingale | Mary Seacole ; Edith Cavell ; Clara Barton | Sie ist nach einer italienischen Stadt benannt. ; Sie gilt als Begründerin der modernen Krankenpflege. ; Ihr Nachname bedeutet „Nachtigall“. | Der Internationale Tag der Pflege am 12. Mai ist ihr Geburtstag.
C H ab12 | In welcher Stadt versteckte sich Anne Frank mit ihrer Familie vor den Nationalsozialisten? | Amsterdam | Frankfurt am Main ; Rotterdam ; Brüssel | Das Versteck lag in einem Hinterhaus an einer Gracht. ; Heute ist es ein Museum. ; Die Stadt ist die Hauptstadt der Niederlande. | Anne Franks Tagebuch ist eines der meistgelesenen Bücher der Welt.
C H | Welche Königin von Frankreich soll angeblich „Dann sollen sie doch Kuchen essen!“ gesagt haben — was nicht belegt ist? | Marie Antoinette | Katharina von Medici ; Eleonore von Aquitanien ; Joséphine de Beauharnais | Sie stammte aus Österreich. ; Ihre Mutter war Maria Theresia. ; Sie wurde 1793 hingerichtet. | Das Zitat taucht schon bei Rousseau auf, bevor Marie Antoinette nach Frankreich kam.
W E | Napoleon Bonaparte wurde in Paris geboren. | falsch | Napoleon kam 1769 in Ajaccio auf Korsika zur Welt — ein Jahr nachdem die Insel französisch geworden war.
O M | Sortiere diese Persönlichkeiten nach ihrem Geburtsjahr — die früheste zuerst. | Karl der Große = 747/748 ; Martin Luther = 1483 ; Napoleon Bonaparte = 1769 ; Albert Einstein = 1879 | Der Frankenkaiser kommt zuerst. ; Der Reformator lebte im 16. Jahrhundert. ; Der Physiker ist der jüngste. | Zwischen Karl dem Großen und Einstein liegen über 1100 Jahre.
@ antike
O E | Sortiere diese Epochen chronologisch — die früheste zuerst. | Steinzeit = bis ca. 2200 v. Chr. (Mitteleuropa) ; Antike = ca. 800 v. Chr. – 500 n. Chr. ; Mittelalter = ca. 500–1500 ; Neuzeit = ab ca. 1500 | Zuerst gab es Werkzeuge aus Stein. ; Dann Griechen und Römer. ; Ritter kamen vor der Neuzeit. | Die Epochengrenzen sind Konventionen und unterscheiden sich je nach Region.
M E | Welche ZWEI dieser Personen waren römische Kaiser? | Augustus ; Nero | Perikles ; Ramses II. ; Hannibal ; Alexander der Große | Einer war der allererste Kaiser. ; Der andere soll beim Brand Roms gesungen haben. ; Griechen, Ägypter und Karthager scheiden aus. | Augustus regierte von 27 v. Chr. bis 14 n. Chr.

@ persoenlichkeiten_entdecker
O H | Sortiere diese US-Präsidenten nach ihrem Amtsantritt — den frühesten zuerst. | Abraham Lincoln = 1861 ; Franklin D. Roosevelt = 1933 ; John F. Kennedy = 1961 ; Barack Obama = 2009 | Der Präsident des Bürgerkriegs kommt zuerst. ; Der New-Deal-Präsident folgt. ; Der erste afroamerikanische Präsident ist der jüngste. | Zwischen Lincoln und Obama liegen fast 150 Jahre.

@ zwanzigstes_jahrhundert
M H | Welche ZWEI dieser Länder gehörten 1949 zu den Gründungsmitgliedern der NATO? | Kanada ; Norwegen | Deutschland ; Spanien ; Schweden ; Österreich | Eines liegt in Nordamerika. ; Das andere in Skandinavien. ; Die Bundesrepublik trat erst 1955 bei. | Zu den zwölf Gründern gehörten u. a. die USA, Großbritannien, Frankreich, Italien und die Benelux-Staaten.
C U | Wie hieß der letzte Kaiser Chinas? | Puyi | Cixi ; Guangxu ; Sun Yat-sen | Er bestieg den Thron als Kleinkind. ; Er dankte 1912 ab. ; Bernardo Bertolucci verfilmte sein Leben. | Der Film „Der letzte Kaiser“ gewann 1988 neun Oscars.

@ mittelalter_ritter
M M | Welche ZWEI dieser Städte gehörten zur Hanse? | Lübeck ; Stralsund | München ; Nürnberg ; Stuttgart ; Augsburg | Beide liegen an der Ostsee. ; Eine galt als „Königin der Hanse“. ; Süddeutsche Handelsstädte scheiden aus. | Zur Hanse gehörten zeitweise rund 200 Städte.
C U | Wie hieß der Vertrag, mit dem Spanien und Portugal 1494 die neu entdeckten Gebiete der Welt aufteilten? | Vertrag von Tordesillas | Vertrag von Utrecht ; Frieden von Lodi ; Vertrag von Zaragoza | Er ist nach einer spanischen Kleinstadt benannt. ; Eine Linie im Atlantik trennte die Einflussgebiete. ; Deshalb spricht man in Brasilien Portugiesisch. | Der Vertrag erklärt, warum Brasilien portugiesisch und der Rest Südamerikas spanisch geprägt ist.

@ deutsche_geschichte de
C E | Worauf schrieben Schulkinder im 19. Jahrhundert meist? | Auf einer Schiefertafel | Auf Tablets ; Auf Papyrus ; Auf Wachstafeln aus Holz | Man schrieb mit einem Griffel. ; Mit einem Schwamm konnte man alles wegwischen. ; Sie war dunkelgrau. | Papier war teuer — die Schiefertafel ließ sich immer wieder verwenden.
O U | Sortiere diese Bundespräsidenten nach ihrem Amtsantritt — den frühesten zuerst. | Theodor Heuss = 1949 ; Richard von Weizsäcker = 1984 ; Joachim Gauck = 2012 ; Frank-Walter Steinmeier = 2017 | Der erste Bundespräsident kommt zuerst. ; Der Redner vom 8. Mai 1985 folgt. ; Der frühere Außenminister ist der jüngste. | Weizsäckers Rede zum 40. Jahrestag des Kriegsendes 1985 wurde berühmt.
"""
