"""Extra questions: Internet & Memes (format: see tools/content/merge_extra.py)."""
KAT = "internet_memes"
REGION = "global"
DATA = r"""
@ internet_geschichte
C E | Aus welchem Land stammen die Emojis ursprünglich? | Japan | USA ; Südkorea ; China | Das Wort setzt sich aus „e“ (Bild) und „moji“ (Schriftzeichen) zusammen. ; Die ersten entwarf Shigetaka Kurita. ; Das Land ist auch Heimat des Tamagotchi. | Kuritas erste 176 Emojis von 1999 stehen heute im Museum of Modern Art in New York.
C E | Wofür steht die Abkürzung „WLAN“? | Wireless Local Area Network | World Line Access Node ; Wide Link Area Net ; Wireless Long Access Network | Es ist ein Funknetz. ; „Wireless“ heißt drahtlos. ; Es ist ein lokales Netzwerk. | Im Englischen sagt man meist „Wi-Fi“ statt WLAN.
C E | Wofür steht die Abkürzung „FAQ“ auf Webseiten? | Frequently Asked Questions | Fast Answer Quiz ; File Access Queue ; Free Available Query | Es ist eine Liste mit Fragen. ; „Häufig gestellte Fragen“. ; Man findet sie oft im Hilfebereich. | FAQs gab es schon in den Usenet-Foren der 1980er-Jahre.
C E | Welches Online-Lexikon gründeten Jimmy Wales und Larry Sanger 2001? | Wikipedia | Brockhaus Online ; Encarta ; Quora | Jeder kann mitschreiben. ; Das Logo ist eine Puzzle-Kugel. ; Der Name enthält das hawaiianische „wiki“ für schnell. | „Wiki wiki“ heißt auf Hawaiianisch „schnell“.
C E | Was ist ein „Captcha“? | Ein Test, der Menschen von Computern unterscheiden soll | Ein Computervirus ; Ein Online-Spiel ; Ein Passwort-Speicher | Man muss verzerrte Buchstaben abtippen. ; Oder Bilder mit Ampeln anklicken. ; Er soll Bots aussperren. | CAPTCHA steht für „Completely Automated Public Turing test to tell Computers and Humans Apart“.
C E | Wofür steht die Abkürzung „PDF“? | Portable Document Format | Personal Data File ; Printed Digital Form ; Public Document Folder | Adobe entwickelte es 1993. ; Das Dokument sieht überall gleich aus. ; „Portable“ heißt tragbar. | PDF ist seit 2008 ein offener ISO-Standard.
C M | Wie nennt man betrügerische E-Mails, die Passwörter oder Bankdaten abgreifen wollen? | Phishing | Spamming ; Hacking ; Cookies | Der Name spielt auf das Angeln an. ; Oft tun sie so, als kämen sie von der Bank. ; „Password fishing“. | Echte Banken fragen nie per E-Mail nach PIN oder Passwort.
C H | Wofür steht das Dateiformat „GIF“? | Graphics Interchange Format | Graphic Image File ; General Internet Format ; Global Image Frame | Es wurde 1987 von CompuServe eingeführt. ; Es kann kurze Animationen zeigen. ; Über die Aussprache wird bis heute gestritten. | Der Erfinder Steve Wilhite bestand auf der Aussprache mit weichem „G“ wie in „Jif“.
C M | Welches Emoji kürten die Oxford Dictionaries 2015 zum „Wort des Jahres“? | Gesicht mit Freudentränen 😂 | Herz ❤️ ; Daumen hoch 👍 ; Kackhaufen 💩 | Man lacht so sehr, dass man weint. ; Es war 2015 das weltweit meistgenutzte Emoji. ; Es ist gelb und hat Tränen. | Es war das erste Mal, dass ein Bildzeichen „Wort des Jahres“ wurde.
C E | Welche Kryptowährung startete 2009 unter dem Pseudonym Satoshi Nakamoto? | Bitcoin | Ethereum ; Dogecoin ; Litecoin | Ihr Kürzel ist BTC. ; Die Menge ist auf 21 Millionen begrenzt. ; Der Name enthält „Bit“. | 2010 kaufte jemand zwei Pizzen für 10.000 Bitcoin — der „Bitcoin Pizza Day“.
C E | Welcher Dienst startete 1997 als DVD-Verleih per Post und streamt heute Serien und Filme? | Netflix | Amazon Prime ; Hulu ; Disney+ | Gründer waren Reed Hastings und Marc Randolph. ; Das Logo ist rot. ; „House of Cards“ war ein frühes Eigenformat. | Netflix startete 2007 mit Streaming in den USA.
C E | Wie heißt der zweidimensionale Code aus schwarzen Quadraten, den ein japanischer Autozulieferer 1994 erfand? | QR-Code | Barcode ; Data Matrix ; NFC-Tag | „QR“ steht für „Quick Response“. ; Er wurde für die Autoindustrie entwickelt. ; Man scannt ihn mit dem Handy. | Denso Wave, eine Toyota-Tochter, gab den QR-Code frei — deshalb ist er heute überall.
C H | Wofür stand die Chat-Abkürzung „ROFL“? | Rolling on the floor laughing | Really outstanding fun, lol ; Rest of forum laughing ; Right on, friends, love | Es ist eine Steigerung von LOL. ; Man lacht so sehr, dass man sich auf dem Boden wälzt. ; Das R steht für „rolling“. | Noch eine Stufe drüber: „ROFLMAO“.
C U | Wie viele verschiedene Emojis entwarf Shigetaka Kurita 1999 ursprünglich? | 176 | 26 ; 64 ; 500 | Sie waren nur 12 × 12 Pixel groß. ; Es waren mehr als 100. ; Weniger als 200. | Die ersten Emojis entstanden für den japanischen Mobilfunkdienst i-mode.
C U | Wofür steht die Abkürzung „HTTP“ am Anfang von Webadressen? | Hypertext Transfer Protocol | Hyperlink Text Transport Program ; High Traffic Transfer Path ; Home Terminal Text Protocol | Es regelt, wie Webseiten übertragen werden. ; Das S in HTTPS steht für „Secure“. ; Das letzte Wort heißt „Protokoll“. | Tim Berners-Lee entwickelte HTTP zusammen mit HTML und dem ersten Webserver.
W E | Das erste Emoji-Set wurde in Japan entwickelt. | wahr | Shigetaka Kurita entwarf 1999 die ersten Emojis für den Mobilfunkanbieter NTT Docomo.
W M | Die Anzahl aller Bitcoins ist auf 21 Millionen begrenzt. | wahr | Das Protokoll legt diese Obergrenze fest — die letzten Bitcoins werden voraussichtlich um das Jahr 2140 erzeugt.
W H | Die Wikipedia wurde ursprünglich von Google gegründet. | falsch | Jimmy Wales und Larry Sanger starteten die Wikipedia 2001; heute betreibt sie die gemeinnützige Wikimedia Foundation.
S M | Aus wie vielen Bit besteht eine IPv4-Adresse? | 32 | Bit | 10 | 4 | 128 | Sie wird in vier Zahlenblöcken geschrieben. ; Jeder Block hat 8 Bit. ; IPv6 hat 128 Bit. | Mit 32 Bit gibt es nur rund 4,3 Milliarden Adressen — deshalb wurde IPv6 eingeführt.
S H | In welchem Jahr wurde der erste Bitcoin-Block („Genesis-Block“) erzeugt? | 2009 | Jahr | 1 | 2000 | 2020 | Kurz nach der Finanzkrise. ; Ende der 2000er. ; Das Jahr endet auf 9. | Der Genesis-Block vom 3. Januar 2009 enthält eine Schlagzeile der „Times“ zur Bankenrettung.
O M | Sortiere diese Internet-Dienste nach ihrem Start — den ältesten zuerst. | Wikipedia = 2001 ; YouTube = 2005 ; WhatsApp = 2009 ; TikTok (international) = 2017 | Das Lexikon kam zuerst. ; Die Videoplattform folgte vier Jahre später. ; Die Kurzvideo-App ist die jüngste. | TikTok ging 2018 mit der App Musical.ly zusammen.
O H | Sortiere diese Dateiformate nach ihrer Einführung — das älteste zuerst. | GIF = 1987 ; JPEG = 1992 ; PDF = 1993 ; MP3 = 1995 | Das Animationsformat ist das älteste. ; Das Foto-Format folgte. ; Das Audioformat aus Erlangen ist das jüngste. | Die Dateiendung „.mp3“ wurde am 14. Juli 1995 intern festgelegt.
M M | Welche ZWEI dieser Abkürzungen gehören zur Chat-Sprache? | BRB ; IMHO | PDF ; USB ; HTML ; WLAN | Die eine heißt „bin gleich zurück“. ; Die andere „meiner bescheidenen Meinung nach“. ; Technik-Kürzel scheiden aus. | BRB steht für „be right back“, IMHO für „in my humble opinion“.

@ meme_klassiker
C E | Wie nennt man jemanden, der in Online-Diskussionen absichtlich provoziert? | Troll | Bot ; Noob ; Lurker | Er will andere ärgern. ; „Don't feed the ...“ ; In Märchen lebt er unter Brücken. | Der Tipp „Don't feed the troll“ heißt: nicht darauf eingehen.
C E | Wie nennt man eine reißerische Überschrift, die nur zum Klicken verleiten soll? | Clickbait | Pop-up ; Spoiler ; Newsfeed | „Bait“ heißt Köder. ; „Du wirst nicht glauben, was dann passierte!“ ; Es ist ein Klick-Köder. | Clickbait-Überschriften versprechen oft mehr, als der Artikel hält.
C E | Wie nennt man es, wenn jemand das Ende eines Films oder einer Serie vorzeitig verrät? | Spoiler | Trailer ; Teaser ; Cliffhanger | Man sollte davor warnen. ; Englisch „to spoil“ heißt verderben. ; Viele schreiben „Achtung, ...!“ | Das Wort „Spoiler“ ist in dieser Bedeutung seit den 1970ern belegt.
C E | Was bedeutet der Netzbegriff „Noob“? | Ein Anfänger | Ein Profi ; Ein Betrüger ; Ein Moderator | Er stammt von „Newbie“. ; Er wird oft abwertend benutzt. ; Man hört ihn vor allem beim Zocken. | Aus „newbie“ wurde „noob“ — oft auch „n00b“ geschrieben.
C H | Was ist ein „Lurker“ in einem Forum? | Jemand, der nur mitliest und nie schreibt | Ein besonders aktiver Poster ; Ein gesperrter Nutzer ; Ein Administrator | Man nennt sie auch stille Mitleser. ; Das englische Wort heißt „lauern“. ; Die meisten Nutzer gehören dazu. | Laut der „90-9-1-Regel“ lesen rund 90 Prozent der Nutzer nur mit.
W M | Das Meme „Doge“ zeigt einen Mops. | falsch | Doge zeigt die Shiba-Inu-Hündin Kabosu aus Japan.
S H | Wie viele Zeichen durfte ein Tweet ab 2017 standardmäßig haben? | 280 | Zeichen | 10 | 50 | 1000 | Vorher waren es 140. ; Das Limit wurde verdoppelt. ; Knapp unter 300. | Das Limit von 140 Zeichen stammte ursprünglich von der Länge einer SMS.
O M | Sortiere diese Memes nach ihrem Entstehungsjahr — das älteste zuerst. | Dancing Baby = 1996 ; Rickroll = 2007 ; Doge = 2013 ; Distracted Boyfriend = 2017 | Das erste ist ein 3D-Baby aus den 90ern. ; Rick Astley kam vor dem Hund. ; Der abgelenkte Freund ist der jüngste. | Das Stockfoto zum „Distracted Boyfriend“ stammt von 2015, zum Meme wurde es 2017.

@ virale_trends
C E | Welcher Hype brachte im Sommer 2016 Menschen dazu, auf Straßen virtuelle Monster zu fangen? | Pokémon GO | Minecraft Earth ; Angry Birds ; Candy Crush | Es war ein Augmented-Reality-Spiel. ; Pikachu gehört dazu. ; Man läuft mit dem Handy herum. | Pokémon GO wurde in den ersten Monaten Hunderte Millionen Mal heruntergeladen.
W M | Beim Worträtsel Wordle muss man ein Wort mit sechs Buchstaben erraten. | falsch | Gesucht ist ein Wort mit fünf Buchstaben; grüne Felder zeigen richtige Buchstaben an der richtigen Stelle.
S M | Wie viele Versuche hat man bei Wordle, um das Wort zu erraten? | 6 | Versuche | 15 | 1 | 20 | Mehr als fünf. ; Weniger als zehn. ; Eine gerade Zahl. | Wordle wurde 2022 von der New York Times gekauft.

@ youtuber_streamer
C E | Welche Farbe hat das Logo der Streaming-Plattform YouTube überwiegend? | Rot | Blau ; Grün ; Lila | Das Play-Symbol ist weiß darauf. ; Die Farbe der Liebe. ; Twitch ist dagegen lila. | Das rote Rechteck mit weißem Play-Dreieck ist eines der bekanntesten Logos der Welt.
S U | Wie viele Stunden Videomaterial wurden 2019 laut YouTube pro Minute hochgeladen? | 500 | Stunden | 30 | 10 | 5000 | log | Mehr als 100. ; Weniger als 1000. ; Eine runde Zahl. | YouTube meldete 2019 rund 500 Stunden neues Material pro Minute.
@ internet_geschichte
O E | Sortiere diese Datenmengen nach ihrer Größe — die kleinste zuerst. | Kilobyte = 10³ Byte ; Megabyte = 10⁶ Byte ; Gigabyte = 10⁹ Byte ; Terabyte = 10¹² Byte | Kilo kommt zuerst. ; Mega kennt man von Fotos. ; Tera von Festplatten. | Danach folgen Petabyte und Exabyte.
M E | Welche ZWEI dieser Dienste sind Messenger zum Chatten? | WhatsApp ; Telegram | Wikipedia ; Google Maps ; Netflix ; eBay | Beide verschicken Nachrichten. ; Einer gehört zu Meta. ; Lexikon, Karten, Streaming und Auktionen scheiden aus. | WhatsApp wurde 2014 von Facebook (heute Meta) gekauft.
M H | Welche ZWEI dieser Firmen wurden der Legende nach in einer Garage gegründet? | Apple ; Amazon | Facebook ; Twitter ; Netflix ; Wikipedia | Einer davon gehört Steve Jobs' Elternhaus. ; Der andere begann als Online-Buchhandel. ; Facebook entstand im Studentenwohnheim. | Jeff Bezos startete Amazon 1994 in seiner Garage in Seattle.
C E | Welche Länderendung haben deutsche Internetadressen? | .de | .ge ; .dt ; .ger | Sie besteht aus zwei Buchstaben. ; Es sind die Anfangsbuchstaben von „Deutschland“. ; Österreich hat .at. | .de ist eine der meistregistrierten Länderendungen der Welt.
C U | Welcher Inselstaat verdient viel Geld mit seiner Internet-Endung „.tv“? | Tuvalu | Tonga ; Tahiti ; Trinidad und Tobago | Der Staat liegt im Pazifik. ; Er ist einer der kleinsten Staaten der Erde. ; Streamingseiten nutzen die Endung gern. | Die Lizenzeinnahmen machen einen spürbaren Teil des Staatshaushalts von Tuvalu aus.
"""
