"""Extra questions: Kunst & Literatur (format: see tools/content/merge_extra.py)."""
KAT = "kunst_literatur"
REGION = "global"
DATA = r"""
@ maerchen_sagen
C E | In welchem Grimm-Märchen lässt ein Mädchen sein langes Haar aus einem Turm herab? | Rapunzel | Schneewittchen ; Dornröschen ; Frau Holle | „... lass dein Haar herunter!“ ; Sie ist nach einer Salatpflanze benannt. ; Eine Zauberin hält sie gefangen. | Rapunzel ist nach dem Feldsalat benannt, den ihre Mutter in der Schwangerschaft so begehrte.
C E | Wie viele Zwerge leben im Märchen bei Schneewittchen? | Sieben | Fünf ; Neun ; Zwölf | Die gleiche Zahl wie Wochentage. ; Auch die Geißlein hatten so viele. ; Eine Primzahl zwischen 5 und 10. | Die sieben Zwerge wohnen hinter den sieben Bergen — die Sieben ist eine typische Märchenzahl.
C E | Was fragt die böse Königin in „Schneewittchen“ immer wieder? | Ihren Zauberspiegel | Ihren Raben ; Ihre Kristallkugel ; Ihren Hofnarren | „... an der Wand, wer ist die Schönste im ganzen Land?“ ; Er hängt an der Wand. ; Man sieht sich selbst darin. | Der Spiegel antwortet ehrlich — und verrät so, dass Schneewittchen noch lebt.
C E | In welches Tier verwandelt sich der Prinz im Grimm-Märchen, den eine Prinzessin an die Wand wirft? | Er war ein Frosch | Er war ein Bär ; Er war ein Schwan ; Er war ein Esel | Das Märchen heißt „Der ...könig“. ; Er holt ihre goldene Kugel aus dem Brunnen. ; Er quakt. | Im Original wird der Frosch nicht geküsst, sondern von der Prinzessin an die Wand geworfen.
C E | Wie lange schläft Dornröschen im Märchen der Brüder Grimm? | Hundert Jahre | Sieben Jahre ; Tausend Jahre ; Ein Jahr | Eine Dornenhecke wächst in der Zeit ums Schloss. ; Es ist eine runde Zahl. ; Ein ganzes Jahrhundert. | Der Fluch der dreizehnten Fee wird abgemildert: statt Tod ein hundertjähriger Schlaf.
C E | Welche vier Tiere ziehen als „Bremer Stadtmusikanten“ los? | Esel, Hund, Katze, Hahn | Pferd, Hund, Katze, Gans ; Esel, Schaf, Katze, Hahn ; Kuh, Hund, Maus, Hahn | Sie stehen am Ende übereinander. ; Das unterste Tier ist das größte. ; Ganz oben kräht einer. | In Bremen erinnert eine Bronzestatue von Gerhard Marcks an die vier Tiere.
C E | Was tut Frau Holle im Märchen, wenn es auf der Erde schneit? | Sie schüttelt ihre Betten aus | Sie weint ; Sie siebt Mehl ; Sie rupft Gänse | Die Goldmarie hilft ihr dabei. ; Federn fliegen durch die Luft. ; Es passiert bei der Hausarbeit. | In Hessen sagte man früher bei Schneefall: „Frau Holle schüttelt die Betten.“
C E | Was bekommt die fleißige Marie im Märchen „Frau Holle“ zur Belohnung? | Einen Goldregen | Einen Prinzen ; Ein Schloss ; Einen Zauberstab | Beim Gehen durch ein Tor passiert es. ; Ihre Schwester erlebt das Gegenteil. ; Danach heißt sie Gold-... | Die faule Schwester wird mit Pech übergossen und heißt fortan Pechmarie.
C E | Welchen Namen muss die Königin im Märchen erraten, um ihr Kind zu behalten? | Rumpelstilzchen | Rübezahl ; Rumpelpumpel ; Hans im Glück | Das Männlein tanzt ums Feuer. ; Es kann Stroh zu Gold spinnen. ; „Ach, wie gut, dass niemand weiß ...“ | Als die Königin den Namen nennt, reißt sich Rumpelstilzchen vor Wut selbst entzwei.
C M | Was tauscht Hans im Grimm-Märchen „Hans im Glück“ zuerst ein? | Einen Goldklumpen | Eine Kuh ; Ein Pferd ; Einen Schleifstein | Er bekommt ihn als Lohn für sieben Jahre Arbeit. ; Er ist ihm zu schwer. ; Er ist so groß wie sein Kopf. | Hans tauscht Gold gegen Pferd, Kuh, Schwein, Gans und Schleifstein — und ist am Ende glücklich ohne alles.
C E | Welche Stadt ist durch die Sage vom Rattenfänger bekannt? | Hameln | Hannover ; Göttingen ; Goslar | Sie liegt an der Weser. ; 130 Kinder verschwanden der Sage nach 1284. ; Ein Pfeifer lockte zuerst die Ratten fort. | In Hameln darf in der Bungelosenstraße bis heute keine Musik gespielt werden.
C M | Welcher Berggeist herrscht der Sage nach über das Riesengebirge? | Rübezahl | Rumpelstilzchen ; Alberich ; Der Erlkönig | Er foppt Wanderer. ; In seinem Namen stecken ein Gemüse und das Zählen. ; Das Gebirge liegt zwischen Polen und Tschechien. | Der Legende nach ließ eine entführte Prinzessin ihn Rüben zählen und floh währenddessen.
C M | Welcher Schelm spiegelt den Menschen ihre Dummheiten vor und stammt der Legende nach aus Kneitlingen? | Till Eulenspiegel | Baron Münchhausen ; Hans Wurst ; Der Hauptmann von Köpenick | Er trägt eine Narrenkappe. ; Sein Name enthält einen Vogel und einen Gegenstand. ; Sein Grab soll in Mölln liegen. | Die Volksbuch-Streiche des Till Eulenspiegel erschienen erstmals um 1510.
C E | Welcher „Lügenbaron“ ritt angeblich auf einer Kanonenkugel? | Baron Münchhausen | Baron Frankenstein ; Graf Dracula ; Freiherr von Knigge | Er zog sich an den eigenen Haaren aus dem Sumpf. ; Er lebte wirklich, im 18. Jahrhundert. ; Seine Heimat Bodenwerder liegt an der Weser. | Hieronymus von Münchhausen erzählte seine Geschichten beim Wein; andere schrieben sie auf.
C E | Wer tötet in der Nibelungensage einen Drachen und badet in dessen Blut? | Siegfried | Hagen ; Gunther ; Dietrich | Er wird dadurch fast unverwundbar. ; Ein Lindenblatt lässt eine Stelle frei. ; Er heiratet Kriemhild. | Hagen von Tronje ersticht Siegfried später genau an der Stelle, auf die das Lindenblatt fiel.
C M | Wo versenkt Hagen von Tronje den Nibelungenschatz? | Im Rhein | In der Donau ; Im Bodensee ; In der Nordsee | Ein großer deutscher Fluss. ; An seinem Ufer sitzt die Loreley. ; Worms liegt an ihm. | Der Sage nach liegt das Rheingold bis heute irgendwo im Fluss.
C E | Wie heißt das Schwert von König Artus? | Excalibur | Durendal ; Balmung ; Anduril | In manchen Versionen erhält er es von der Dame vom See. ; Es ist das berühmteste Schwert der Artussage. ; Es beginnt mit „Ex“. | Nach Artus' Tod wird Excalibur der Dame vom See zurückgegeben.
C E | Wie heißt der Zauberer an der Seite von König Artus? | Merlin | Gandalf ; Morgana ; Lancelot | Er soll rückwärts durch die Zeit gelebt haben. ; Er erzog den jungen Artus. ; Der Name hat sechs Buchstaben. | Merlin taucht erstmals bei Geoffrey von Monmouth im 12. Jahrhundert auf.
C H | Wie heißt die Tafel, an der König Artus und seine Ritter gleichberechtigt sitzen? | Tafelrunde | Ritterbank ; Königstafel ; Gralstisch | Es ist ein runder Tisch. ; Keiner sitzt am Kopfende. ; Der Name verbindet Tisch und Kreis. | Die runde Form sollte zeigen, dass kein Ritter über dem anderen steht.
C H | Welches Gefäß suchen die Ritter der Tafelrunde? | Den Heiligen Gral | Das Goldene Vlies ; Die Bundeslade ; Den Stein der Weisen | Es soll ein Kelch vom Abendmahl sein. ; Parzival findet es. ; Der Name beginnt mit G. | Die Gralssuche wurde von Chrétien de Troyes und Wolfram von Eschenbach berühmt gemacht.
C H | Welcher griechische Held tötet das Ungeheuer Minotaurus im Labyrinth? | Theseus | Herakles ; Perseus ; Achilles | Ariadne gibt ihm einen Faden. ; Er ist später König von Athen. ; Das Labyrinth stand auf Kreta. | Mit Ariadnes Faden fand Theseus wieder aus dem Labyrinth des Königs Minos.
C H | Welcher Held schlägt der Gorgone Medusa den Kopf ab? | Perseus | Theseus ; Jason ; Odysseus | Er benutzt einen spiegelnden Schild. ; Ihr Blick lässt Menschen versteinern. ; Aus ihrem Blut springt Pegasus. | Perseus sah Medusa nur im Spiegelbild seines Schildes an, um nicht zu versteinern.
C H | Wie viele Arbeiten muss Herakles in der griechischen Sage vollbringen? | Zwölf | Sieben ; Zehn ; Dreizehn | So viele wie Monate im Jahr. ; Eine davon ist das Ausmisten der Augiasställe. ; Ein Dutzend. | Ursprünglich sollten es zehn sein, doch zwei wurden nicht anerkannt.
C H | Wer öffnet in der griechischen Mythologie ein Gefäß, aus dem alle Übel der Welt entweichen? | Pandora | Persephone ; Medea ; Helena | Heute spricht man von ihrer „Büchse“. ; Nur die Hoffnung bleibt darin. ; Ihr Name heißt „die Allbeschenkte“. | Ursprünglich war es ein Krug (pithos) — erst Erasmus machte daraus eine „Büchse“.
C U | In welchem Grimm-Märchen wird ein Mädchen im Winter im Papierkleid zum Erdbeersuchen in den Wald geschickt? | Die drei Männlein im Walde | Sterntaler ; Schneeweißchen und Rosenrot ; Das Waldhaus | Die Stiefmutter will sie loswerden. ; Kleine Helfer beschenken sie. ; Der Titel nennt eine Zahl. | Zur Belohnung fallen dem Mädchen fortan bei jedem Wort Goldstücke aus dem Mund.
C U | Welcher früh verstorbene Autor schrieb die Kunstmärchen „Zwerg Nase“ und „Kalif Storch“? | Wilhelm Hauff | Ludwig Bechstein ; Theodor Storm ; Clemens Brentano | Er starb schon mit 24 Jahren. ; Auch „Das kalte Herz“ stammt von ihm. ; Er schrieb den Roman „Lichtenstein“. | Wilhelm Hauff (1802–1827) veröffentlichte seine Märchen in Almanachen; „Das kalte Herz“ spielt im Schwarzwald.
C U | Wie heißt der Zwergenkönig, der in der Nibelungensage die Tarnkappe hütet? | Alberich | Mime ; Laurin ; Oberon | Siegfried besiegt ihn. ; Bei Wagner stiehlt er das Rheingold. ; Der Name steckt im französischen „Oberon“. | Alberich bewacht im Nibelungenlied den Hort; Siegfried erringt von ihm die Tarnkappe.
C U | Welcher dänische Autor schrieb „Des Kaisers neue Kleider“? | Hans Christian Andersen | Søren Kierkegaard ; Karen Blixen ; Ludwig Holberg | Er stammte aus Odense. ; Auch „Die kleine Meerjungfrau“ ist von ihm. ; Er hatte zwei Vornamen. | In Andersens Märchen spricht erst ein Kind aus, dass der Kaiser nackt ist.
C U | Wie heißt das Grimm-Märchen, in dem ein Soldat sieben Jahre lang ein Bärenfell tragen muss? | Der Bärenhäuter | Der Wolfspelz ; Allerleirauh ; Der Teufel mit den drei goldenen Haaren | Er darf sich in der Zeit nicht waschen. ; Er schließt einen Pakt mit dem Teufel. ; Das Tier brummt. | Nach sieben Jahren wird der Bärenhäuter reich, schön und heiratet die treue jüngste Tochter.
W E | Im Märchen „Hänsel und Gretel“ streuen die Kinder zuerst Kieselsteine, um den Heimweg zu finden. | wahr | Beim ersten Mal helfen die Kieselsteine, beim zweiten Mal fressen Vögel die Brotkrumen.
W M | In der Grimm-Erstausgabe ist bei „Schneewittchen“ und „Hänsel und Gretel“ die leibliche Mutter die Böse. | wahr | Erst in späteren Auflagen machten die Grimms aus den Müttern Stiefmütter.
W M | Der Rattenfänger von Hameln soll der Sage nach Kinder mit einer Trommel fortgelockt haben. | falsch | Er spielte der Sage nach auf einer Flöte bzw. Pfeife.
W H | Die Brüder Grimm haben alle ihre Märchen selbst erfunden. | falsch | Die Grimms sammelten Erzählungen — etwa von Dorothea Viehmann oder aus befreundeten Kasseler Familien.
S M | Wie viele Kinder verschwanden der Sage nach 1284 mit dem Rattenfänger aus Hameln? | 130 | Kinder | 20 | 10 | 1000 | Es waren über hundert. ; Weniger als 200. ; Die Zahl endet auf 0. | Eine alte Inschrift nennt 130 Kinder — die Hintergründe sind bis heute umstritten.
O E | Sortiere diese Grimm-Märchen nach der Zahl in ihrem Titel — von klein nach groß. | Die zwei Brüder = 2 ; Die drei Federn = 3 ; Die sieben Raben = 7 ; Die zwölf Brüder = 12 | Brüder kommen zweimal vor. ; Die Vögel sind mehr als die Federn. ; Die größte Zahl ist ein Dutzend. | Alle vier sind echte Grimm-Märchen — Zahlen wie 3, 7 und 12 prägen viele Märchen.
M M | Welche ZWEI dieser Figuren stammen aus den Märchen der Brüder Grimm? | Rumpelstilzchen ; Rapunzel | Die kleine Meerjungfrau ; Pinocchio ; Aladin ; Peter Pan | Beide haben mit Gold oder Haar zu tun. ; Eine Figur hat einen Pflanzennamen. ; Andersen, Collodi, Tausendundeine Nacht und Barrie scheiden aus. | Die kleine Meerjungfrau ist von Andersen, Pinocchio von Collodi, Aladin aus „Tausendundeine Nacht“.

@ gemaelde_erkennen
C E | Welcher Maler schnitt sich 1888 einen Teil seines Ohrs ab und malte berühmte Sonnenblumen? | Vincent van Gogh | Claude Monet ; Paul Gauguin ; Rembrandt | Er war Niederländer. ; Er lebte zeitweise in Arles. ; Sein Bruder hieß Theo. | Van Gogh malte mehrere Sonnenblumen-Bilder, um das Gästezimmer für Gauguin zu schmücken.
C E | Welcher Maler ist berühmt für seine Seerosen-Bilder aus seinem Garten in Giverny? | Claude Monet | Paul Cézanne ; Edgar Degas ; Henri Matisse | Er war Impressionist. ; Der Garten liegt nördlich von Paris. ; Sein Name klingt ähnlich wie der von Manet. | Monet malte rund 250 Seerosen-Bilder in seinem eigenen Wassergarten.
C E | Welcher Künstler machte Bilder von Suppendosen und Marilyn Monroe berühmt? | Andy Warhol | Roy Lichtenstein ; Keith Haring ; Jackson Pollock | Er ist der bekannteste Pop-Art-Künstler. ; Seine Werkstatt hieß „The Factory“. ; Die Dosen waren von Campbell's. | Warhol sagte, jeder werde in Zukunft 15 Minuten lang weltberühmt sein.
C E | Aus welchem Land stammte der Maler Pablo Picasso? | Spanien | Frankreich ; Italien ; Portugal | Geboren wurde er in Málaga. ; Er lebte später in Frankreich. ; „Guernica“ zeigt eine Stadt seines Heimatlandes. | Picasso (1881–1973) war Mitbegründer des Kubismus.
C E | Welche Kunstrichtung verbindet man mit Pablo Picasso und Georges Braque? | Kubismus | Impressionismus ; Barock ; Pop-Art | Formen werden in geometrische Flächen zerlegt. ; Der Name kommt von einer Würfelform. ; Ein Kritiker spottete über „kleine Würfel“. | Der Kubismus entstand um 1907; ein Kritiker verspottete die Bilder als aus „Würfeln“ gebaut.
C M | Welcher niederländische Maler malte „Die Nachtwache“ und über 80 Selbstporträts? | Rembrandt | Vermeer ; Frans Hals ; Rubens | Sein Nachname war van Rijn. ; Er lebte in Amsterdam. ; Man kennt ihn meist nur beim Vornamen. | Rembrandt dokumentierte sein Altern in Dutzenden Selbstbildnissen.
C M | Welcher Maler ist für Gemälde mit schwarzen Linien und Rechtecken in Rot, Gelb und Blau bekannt? | Piet Mondrian | Wassily Kandinsky ; Paul Klee ; Kasimir Malewitsch | Er war Niederländer. ; Er gehörte zur Gruppe „De Stijl“. ; Ein Modehaus entwarf danach ein berühmtes Kleid. | Yves Saint Laurent machte Mondrians Rasterbilder 1965 zu einer Kleiderkollektion.
C M | Wie heißt das berühmte Gemälde von Leonardo da Vinci mit Jesus und den zwölf Aposteln? | Das Abendmahl | Die Schule von Athen ; Die Erschaffung Adams ; Die Geburt der Venus | Es befindet sich in Mailand. ; Es zeigt eine Mahlzeit. ; Es ist das letzte gemeinsame Essen. | Leonardo malte das Wandbild 1494–1498 im Refektorium von Santa Maria delle Grazie.
C M | Wer malte „Die Geburt der Venus“, auf der die Göttin auf einer Muschel steht? | Sandro Botticelli | Raffael ; Tizian ; Caravaggio | Er lebte in Florenz. ; Das Bild hängt in den Uffizien. ; Sein Spitzname bedeutet „Fässchen“. | Botticelli malte das Bild um 1485 für die Medici-Familie.
C H | Welcher Maler gründete 1911 mit Franz Marc den „Blauen Reiter“ und gilt als Pionier der abstrakten Malerei? | Wassily Kandinsky | August Macke ; Emil Nolde ; Paul Klee | Er stammte aus Moskau. ; Er lehrte später am Bauhaus. ; Er schrieb „Über das Geistige in der Kunst“. | Kandinsky malte um 1910 einige der ersten rein abstrakten Bilder.
C M | Welcher deutsche Expressionist malte besonders gern blaue Pferde? | Franz Marc | Ernst Ludwig Kirchner ; Max Beckmann ; Otto Dix | Er gehörte zum „Blauen Reiter“. ; Er fiel 1916 bei Verdun. ; Auch ein „Tiger“ und „Rehe im Walde“ stammen von ihm. | Für Franz Marc stand Blau für das Männliche und Geistige.
C M | Welcher Street-Art-Künstler ließ 2018 sein Bild „Girl with Balloon“ direkt nach der Versteigerung schreddern? | Banksy | Shepard Fairey ; Keith Haring ; Jean-Michel Basquiat | Seine Identität ist offiziell unbekannt. ; Er stammt vermutlich aus Bristol. ; Das halb zerstörte Werk heißt nun „Love is in the Bin“. | 2021 wurde „Love is in the Bin“ für rund 18,6 Millionen Pfund erneut versteigert.
C H | Welcher spanische Hofmaler schuf „Las Meninas“? | Diego Velázquez | Francisco de Goya ; El Greco ; Bartolomé Murillo | Er diente König Philipp IV. ; Er malte sich selbst mit ins Bild. ; Das Bild hängt im Prado. | „Las Meninas“ (1656) zeigt die Infantin Margarita mit ihren Hofdamen und den Maler selbst.
C H | Welcher Maler schuf das Triptychon „Der Garten der Lüste“? | Hieronymus Bosch | Pieter Bruegel ; Jan van Eyck ; Albrecht Dürer | Er war Niederländer. ; Seine Bilder sind voller seltsamer Fabelwesen. ; Er benannte sich nach seiner Heimatstadt ’s-Hertogenbosch. | Das Werk entstand um 1500 und hängt heute im Prado in Madrid.
C H | Welcher spanische Maler schuf „Die nackte Maja“ und „Die Erschießung der Aufständischen“? | Francisco de Goya | Diego Velázquez ; El Greco ; Bartolomé Murillo | Er war Hofmaler um 1800. ; Er wurde im Alter taub. ; Seine „Schwarzen Malereien“ zeigen Saturn. | Goyas „Der 3. Mai 1808“ zeigt die Erschießung spanischer Aufständischer durch Napoleons Truppen.
C H | Welcher belgische Surrealist malte eine Pfeife mit dem Satz „Ceci n'est pas une pipe“? | René Magritte | Salvador Dalí ; Paul Delvaux ; Max Ernst | Er malte auch Männer mit Melone. ; Das Bild heißt „Der Verrat der Bilder“. ; Sein Vorname ist René. | Magritte meinte: Es ist ja nur das Bild einer Pfeife — man kann es nicht stopfen.
C H | Welcher Künstler ist für seine „Drip Paintings“ bekannt, bei denen er Farbe auf am Boden liegende Leinwände tropfen ließ? | Jackson Pollock | Mark Rothko ; Willem de Kooning ; Andy Warhol | Er war Amerikaner. ; Sein Spitzname lautete „Jack the Dripper“. ; Er gehört zum Abstrakten Expressionismus. | Pollock arbeitete ab 1947 mit der Tropftechnik auf dem Boden seines Ateliers.
C U | Welcher Maler aus der Gruppe „Die Brücke“ malte Straßenszenen am Potsdamer Platz? | Ernst Ludwig Kirchner | Franz Marc ; Max Liebermann ; Paul Klee | Die Gruppe wurde 1905 in Dresden gegründet. ; Er zog später nach Davos. ; Seine Kokotten-Bilder zeigen Berlin. | Kirchner gründete „Die Brücke“ 1905 mit Erich Heckel, Karl Schmidt-Rottluff und Fritz Bleyl.
C U | Welcher Maler schuf den Genter Altar, der als eines der meistgestohlenen Kunstwerke gilt? | Jan van Eyck | Rogier van der Weyden ; Hans Memling ; Pieter Bruegel | Er galt lange als Erfinder der Ölmalerei. ; Er malte auch die „Arnolfini-Hochzeit“. ; Sein Bruder Hubert begann das Werk. | Eine Tafel des Genter Altars, „Die gerechten Richter“, ist seit 1934 verschwunden.
C U | Welcher Maler malte „Die Toteninsel“, von der er fünf Versionen schuf? | Arnold Böcklin | Caspar David Friedrich ; Max Klinger ; Franz von Stuck | Er war Schweizer. ; Er gehört zum Symbolismus. ; Hitler besaß eine Version des Bildes. | Böcklins „Toteninsel“ war um 1900 als Kunstdruck in unzähligen deutschen Wohnzimmern zu finden.
C U | Wie heißt der Kunststil, zu dem Gustav Klimt mit „Der Kuss“ gehört und der in Wien „Secession“ hieß? | Jugendstil | Expressionismus ; Art déco ; Biedermeier | Der deutsche Name kommt von einer Münchner Zeitschrift. ; In Frankreich heißt er „Art nouveau“. ; Er blühte um 1900. | Die Zeitschrift „Jugend“ gab dem Stil seinen deutschen Namen.
W E | Die Mona Lisa hängt in den Uffizien in Florenz. | falsch | Die Mona Lisa hängt im Louvre in Paris — in den Uffizien hängt Botticellis „Geburt der Venus“.
W M | Pablo Picassos „Guernica“ ist ein farbenfrohes Bild in leuchtendem Rot und Gelb. | falsch | „Guernica“ ist fast ausschließlich in Schwarz, Weiß und Grautönen gehalten.
W H | Claude Monet litt im Alter am Grauen Star, was die Farben seiner Spätwerke veränderte. | wahr | Monets späte Bilder wurden rötlich-braun; nach einer Operation 1923 übermalte er einige davon.
S U log | Wie viele Gemälde malte Vincent van Gogh ungefähr in seinem Leben? | 860 | Gemälde | 30 | 50 | 5000 | Er malte nur rund zehn Jahre lang. ; Es sind deutlich mehr als 500. ; Fast täglich entstand ein Bild. | Van Gogh schuf in rund zehn Jahren etwa 860 Gemälde und über 1000 Zeichnungen.
O H | Sortiere diese Gemälde nach ihrer Entstehung — das älteste zuerst. | Die Geburt der Venus (Botticelli) = um 1485 ; Mona Lisa (Leonardo) = um 1503 ; Die Nachtwache (Rembrandt) = 1642 ; Der Schrei (Munch) = 1893 | Zwei stammen aus der italienischen Renaissance. ; Venus kam vor Lisa. ; Das norwegische Bild ist das jüngste. | Zwischen Botticellis Venus und Munchs Schrei liegen gut 400 Jahre.
M M | Welche ZWEI dieser Maler gehören zum Impressionismus? | Claude Monet ; Edgar Degas | Rembrandt ; Andy Warhol ; Salvador Dalí ; Albrecht Dürer | Beide waren Franzosen des 19. Jahrhunderts. ; Einer malte gern Balletttänzerinnen. ; Der andere Seerosen. | Degas malte Tänzerinnen, Monet Seerosen — beide stellten in den Impressionisten-Ausstellungen ab 1874 aus.

@ architektur_bauwerke
C E | Welches Hamburger Viertel aus Backstein-Lagerhäusern auf Eichenpfählen ist UNESCO-Welterbe? | Speicherstadt | Schanzenviertel ; Blankenese ; St. Georg | Hier lagerten früher Kaffee, Tee und Gewürze. ; Das Miniatur Wunderland liegt darin. ; Der Name verrät die Nutzung. | Die Speicherstadt entstand ab 1883 und ist der größte Lagerhauskomplex der Welt.
C M | Wie heißt die Felsenstadt in Jordanien, deren Fassaden direkt in roten Sandstein gehauen sind? | Petra | Palmyra ; Karthago ; Persepolis | Sie war Hauptstadt der Nabatäer. ; Indiana Jones sucht dort den Heiligen Gral. ; Der Name bedeutet auf Griechisch „Fels“. | Das „Schatzhaus“ von Petra ist rund 40 Meter hoch und direkt aus der Felswand gemeißelt.
C E | Wie heißt der gotische Dom im Herzen Wiens, dessen Südturm „Steffl“ genannt wird? | Stephansdom | Karlskirche ; Votivkirche ; Peterskirche | Er ist nach einem Heiligen benannt. ; Der Platz davor heißt genauso. ; Seine Glocke „Pummerin“ ist berühmt. | Der Südturm des Stephansdoms ist rund 136 Meter hoch.
C E | Welches Schloss in Bayern diente als Vorbild für das Disney-Schloss? | Neuschwanstein | Linderhof ; Herrenchiemsee ; Nymphenburg | Es wurde von König Ludwig II. erbaut. ; Es liegt bei Füssen. ; Im Namen steckt ein Wasservogel. | Neuschwanstein zählt jährlich rund 1,4 Millionen Besucher.
C E | In welchem Land steht die Chinesische Mauer? | China | Japan ; Mongolei ; Korea | Der Name verrät es. ; Sie schützte vor Reitervölkern aus dem Norden. ; Ihre Hauptstadt ist Peking. | Alle Abschnitte der Mauer zusammen sind über 21.000 Kilometer lang.
C M | Welche Palast- und Festungsanlage in Granada erbauten die maurischen Nasriden-Herrscher? | Alhambra | Alcázar ; Mezquita ; Escorial | Der Name bedeutet „die Rote“. ; Berühmt ist der Löwenhof. ; Sie liegt in Andalusien. | Die Alhambra entstand vor allem im 13. und 14. Jahrhundert und ist UNESCO-Welterbe.
C E | In welcher Stadt steht die Elbphilharmonie? | Hamburg | Dresden ; Magdeburg ; Dessau | Sie wurde 2017 eröffnet. ; Sie steht auf einem alten Kaispeicher. ; Die Stadt hat den größten Hafen Deutschlands. | Die Elbphilharmonie kostete rund 866 Millionen Euro — ein Vielfaches der ursprünglichen Planung.
C E | Welche Inka-Ruinenstadt liegt auf einem Bergsattel hoch in den Anden Perus? | Machu Picchu | Cusco ; Chichén Itzá ; Tikal | Hiram Bingham machte sie 1911 international bekannt. ; Sie liegt auf rund 2400 Metern Höhe. ; Der Name bedeutet „alter Gipfel“. | Machu Picchu wurde im 15. Jahrhundert unter Inka-Herrscher Pachacútec erbaut.
C M | Welches Pariser Monument ließ Napoleon ab 1806 zu Ehren seiner Armee errichten? | Arc de Triomphe | Panthéon ; Invalidendom ; Sacré-Cœur | Darunter liegt das Grab des unbekannten Soldaten. ; Zwölf Straßen laufen sternförmig darauf zu. ; Es ist ein Bogen. | Der Triumphbogen wurde erst 1836 fertig — lange nach Napoleons Sturz.
C E | Welche Londoner Brücke kann ihre beiden Fahrbahnteile für Schiffe hochklappen? | Tower Bridge | London Bridge ; Millennium Bridge ; Westminster Bridge | Sie wurde 1894 eröffnet. ; Zwei neugotische Türme prägen sie. ; Sie steht nahe einer berühmten Festung. | Die Tower Bridge wird oft mit der schlichten London Bridge verwechselt.
C E | Welches antike Weltwunder ist als einziges bis heute erhalten? | Die Pyramiden von Gizeh | Der Koloss von Rhodos ; Die Hängenden Gärten von Babylon ; Der Leuchtturm von Pharos | Es steht in Ägypten. ; Es ist das älteste der sieben Weltwunder. ; Pharaonen liegen darin begraben. | Die Cheops-Pyramide war rund 3800 Jahre lang das höchste Bauwerk der Welt.
C H | Welcher Architekt entwarf das Guggenheim-Museum in Bilbao? | Frank Gehry | Zaha Hadid ; Renzo Piano ; Norman Foster | Er ist Kanadier und lebt in Los Angeles. ; Seine Bauten wirken wie zerknittertes Metall. ; Auch das Tanzende Haus in Prag stammt von ihm. | Das Museum mit seiner Titanfassade wurde 1997 eröffnet — man spricht seitdem vom „Bilbao-Effekt“.
C H | Welcher Architekt entwarf die Wallfahrtskapelle in Ronchamp und die Wohnmaschine „Unité d'Habitation“? | Le Corbusier | Ludwig Mies van der Rohe ; Oscar Niemeyer ; Alvar Aalto | Er war Schweizer-Franzose. ; Sein Künstlername klingt nach einem Raben. ; Er erfand das Maßsystem „Modulor“. | Le Corbusier hieß eigentlich Charles-Édouard Jeanneret.
C H | In welchem Baustil ist der Kölner Dom errichtet? | Gotik | Romanik ; Barock ; Klassizismus | Spitzbögen prägen ihn. ; Der Bau begann 1248. ; Der Stil kam aus Frankreich. | Der Kölner Dom ist mit seinen 157 Meter hohen Türmen eine der größten gotischen Kathedralen.
C H | In welcher Stadt steht die Hagia Sophia? | Istanbul | Athen ; Rom ; Kairo | Sie war fast 1000 Jahre die größte Kirche der Welt. ; Die Stadt hieß früher Konstantinopel. ; Sie liegt am Bosporus. | Die Hagia Sophia wurde 537 unter Kaiser Justinian geweiht; später war sie Moschee und Museum.
C U | Welcher Architekt entwarf das Olympiastadion in München mit dem berühmten Zeltdach? | Günter Behnisch (mit Frei Otto) | Albert Speer ; Walter Gropius ; Gottfried Böhm | Das Dach besteht aus Acrylglas. ; Es wurde für die Spiele 1972 gebaut. ; Frei Otto war Experte für Leichtbau. | Das Zeltdach sollte ein heiteres, demokratisches Deutschland zeigen.
C U | Wie heißt der Architekt der Wieskirche, eines Rokoko-Meisterwerks im Pfaffenwinkel? | Dominikus Zimmermann | Balthasar Neumann ; Johann Michael Fischer ; Cosmas Damian Asam | Sein Bruder Johann Baptist malte die Fresken. ; Die Kirche ist UNESCO-Welterbe. ; Sein Nachname ist ein Handwerksberuf. | Die Wallfahrtskirche „Zum Gegeißelten Heiland auf der Wies“ entstand 1745–1754.
C U | Welcher Baumeister schuf die Würzburger Residenz mit dem berühmten Treppenhaus? | Balthasar Neumann | Dominikus Zimmermann ; Karl Friedrich Schinkel ; Matthäus Daniel Pöppelmann | Sein Porträt war auf dem 50-D-Mark-Schein. ; Das Deckenfresko malte Tiepolo. ; Er war ein Barockbaumeister aus Eger. | Das freitragende Gewölbe über dem Treppenhaus galt Kritikern als einsturzgefährdet — es hielt sogar den Bomben 1945 stand.
W M | Die Freiheitsstatue in New York war ein Geschenk Großbritanniens an die USA. | falsch | Die Statue war ein Geschenk Frankreichs; ihr inneres Stahlgerüst entwarf Gustave Eiffel.
W H | Der Schiefe Turm von Pisa ist ein freistehender Glockenturm. | wahr | Der Campanile gehört zum Dom von Pisa und neigt sich um knapp 4 Grad.
S M | Wie hoch ist der Eiffelturm ungefähr mit Antennen (in Metern)? | 330 | Meter | 10 | 100 | 1000 | Er ist deutlich höher als 300 Meter. ; Ursprünglich war er 312 Meter hoch. ; Etwa ein Drittel Kilometer. | Mit Antennen misst der Eiffelturm heute rund 330 Meter.
O M | Sortiere diese Bauwerke nach ihrer Fertigstellung — das älteste zuerst. | Kolosseum = 80 n. Chr. ; Kölner Dom = 1880 ; Eiffelturm = 1889 ; Burj Khalifa = 2010 | Das älteste ist antik. ; Der Dom wurde knapp vor dem Turm fertig. ; Der Wolkenkratzer steht in der Wüste. | Der Kölner Dom wurde nach über 600 Jahren 1880 vollendet — nur neun Jahre vor dem Eiffelturm.

@ deutsche_literatur de
C E | Wie heißt der weiße Glücksdrache in Michael Endes „Die unendliche Geschichte“? | Fuchur | Grisu ; Nepomuk ; Tabaluga | Er trägt Atréju durch Phantásien. ; In der Verfilmung sieht er aus wie ein Hund. ; Der Name beginnt mit F. | Im englischen Film heißt Fuchur „Falkor“.
C H | Wie heißt der Uhu, mit dem Otfried Preußlers „Kleines Gespenst“ befreundet ist? | Schuhu | Hedwig ; Kasimir ; Eulalia | Der Name klingt wie ein Eulenruf. ; Er wohnt auf Burg Eulenstein. ; Er reimt sich auf „Uhu“. | Das kleine Gespenst will einmal die Welt bei Tag sehen — und wird dabei von der Sonne schwarz.
C E | Wer schrieb „Das doppelte Lottchen“? | Erich Kästner | Astrid Lindgren ; James Krüss ; Paul Maar | Er schrieb auch „Emil und die Detektive“. ; Es geht um Zwillinge. ; Er stammte aus Dresden. | Die Zwillinge Luise und Lotte tauschen die Rollen, um ihre Eltern wieder zusammenzubringen.
C E | Wer schrieb die Kinderbücher um das „Sams“ mit den Wunschpunkten? | Paul Maar | Michael Ende ; Kirsten Boie ; Janosch | Das Sams liebt Herrn Taschenbier. ; Es hat blaue Punkte im Gesicht. ; Der Autor heißt mit Vornamen Paul. | „Eine Woche voller Samstage“ erschien 1973.
C E | Welcher Autor und Zeichner schrieb „Oh, wie schön ist Panama“ mit Tiger und Bär? | Janosch | Otfried Preußler ; Helme Heine ; Erich Kästner | Er malte auch die Tigerente. ; Sein bürgerlicher Name ist Horst Eckert. ; Er nannte sich mit nur einem Namen. | Janosch lebte lange auf Teneriffa; die Tigerente wurde zum Kult.
C M | Wer schrieb den Roman „Tintenherz“? | Cornelia Funke | Kerstin Gier ; Michael Ende ; Kai Meyer | Die Autorin stammt aus Dorsten. ; Sie schrieb auch „Die Wilden Hühner“. ; Figuren springen aus Büchern heraus. | „Tintenherz“ erschien 2003 und wurde 2008 mit Brendan Fraser verfilmt.
C H | Welcher Dichter schrieb die „Galgenlieder“ mit dem Nasobēm? | Christian Morgenstern | Joachim Ringelnatz ; Wilhelm Busch ; Kurt Tucholsky | Ein Gedicht heißt „Das ästhetische Wiesel“. ; Er schrieb Unsinnspoesie um 1900. ; Sein Nachname verbindet eine Tageszeit mit einem Himmelskörper. | Die „Galgenlieder“ erschienen 1905 und sind Klassiker der deutschen Nonsens-Dichtung.
C M | In welches Wesen verwandelt sich Gregor Samsa in Franz Kafkas „Die Verwandlung“? | Ein riesiges Ungeziefer | Einen schwarzen Hund ; Eine graue Maus ; Einen Raben | Er liegt eines Morgens auf seinem panzerartigen Rücken. ; Viele stellen es sich als Käfer vor. ; Kafka spricht von einem „ungeheueren“ Tier. | Kafka wollte nicht, dass das Insekt auf dem Buchumschlag abgebildet wird.
C M | Welche Stadt ist der Schauplatz von Alfred Döblins Roman über Franz Biberkopf? | Berlin | Hamburg ; München ; Wien | Der Titel nennt einen Platz. ; Der Platz heißt Alexanderplatz. ; Es ist die Hauptstadt. | „Berlin Alexanderplatz“ (1929) gilt als erster großer deutscher Großstadtroman.
C M | Wer schrieb den Roman „Der Vorleser“, der 2008 mit Kate Winslet verfilmt wurde? | Bernhard Schlink | Daniel Kehlmann ; Günter Grass ; Patrick Süskind | Der Autor ist auch Jurist. ; Der Roman erschien 1995. ; Er war als erster deutscher Roman Platz 1 der „New York Times“-Bestsellerliste. | Kate Winslet gewann für ihre Rolle als Hanna Schmitz den Oscar.
C H | Welcher Dichter schrieb das Gedicht „Der Panther“? | Rainer Maria Rilke | Stefan George ; Hermann Hesse ; Georg Trakl | „Sein Blick ist vom Vorübergehn der Stäbe ...“ ; Er wurde in Prag geboren. ; Er schrieb auch die „Duineser Elegien“. | Rilke schrieb „Der Panther“ um 1903 nach Besuchen im Pariser Jardin des Plantes.
C H | Wer schrieb das Lustspiel „Der zerbrochne Krug“ um den Dorfrichter Adam? | Heinrich von Kleist | Gotthold Ephraim Lessing ; Georg Büchner ; Friedrich Hebbel | Er stammte aus Frankfurt an der Oder. ; Er schrieb auch „Michael Kohlhaas“. ; Er starb 1811 am Wannsee. | Goethe brachte das Stück 1808 in Weimar auf die Bühne — mit wenig Erfolg.
C U | Welche Dichterin des 19. Jahrhunderts war auf dem 20-D-Mark-Schein abgebildet? | Annette von Droste-Hülshoff | Bettina von Arnim ; Clara Schumann ; Marie von Ebner-Eschenbach | Sie schrieb „Die Judenbuche“. ; Sie stammte aus Westfalen. ; Sie lebte zuletzt in Meersburg am Bodensee. | Die Novelle „Die Judenbuche“ erschien 1842.
C U | Wer schrieb den Schelmenroman „Simplicius Simplicissimus“ über den Dreißigjährigen Krieg? | Hans Jakob Christoffel von Grimmelshausen | Andreas Gryphius ; Martin Opitz ; Friedrich von Logau | Er war selbst Soldat im Krieg. ; Das Buch erschien 1668. ; Sein Nachname enthält „Grimm“. | Der „Simplicissimus“ gilt als erster großer Roman der deutschen Literatur.
W M | Heinrich Heine schrieb das Gedicht „Deutschland. Ein Wintermärchen“. | wahr | Heine schrieb es 1844 nach einer Reise aus dem Pariser Exil nach Hamburg.
S H | In welchem Jahr erschien Goethes Briefroman „Die Leiden des jungen Werthers“? | 1774 | Jahr | 3 | 1700 | 1850 | Goethe war damals Mitte zwanzig. ; Zwei Jahre vor der US-Unabhängigkeit. ; Es war die Zeit des Sturm und Drang. | Der „Werther“ machte Goethe über Nacht berühmt — und löste eine Werther-Mode aus.
O H | Sortiere diese deutschen Dichter nach ihrem Geburtsjahr — den ältesten zuerst. | Johann Wolfgang von Goethe = 1749 ; Friedrich Schiller = 1759 ; Heinrich Heine = 1797 ; Thomas Mann = 1875 | Die beiden Weimarer Klassiker kommen zuerst. ; Goethe war zehn Jahre älter als sein Freund. ; Der Nobelpreisträger ist der jüngste. | Goethe und Schiller verband ab 1794 eine enge Freundschaft.

@ comics_graphic_novels
C E | Wie heißt der kleine gallische Krieger, der durch einen Zaubertrank unbesiegbar wird? | Asterix | Idefix ; Majestix ; Miraculix | Er trägt einen Flügelhelm. ; Sein bester Freund trägt Hinkelsteine. ; Der Name endet auf -ix wie bei allen Galliern. | Asterix erschien erstmals 1959 im Magazin „Pilote“.
C E | Wie heißt der Druide, der im Asterix-Dorf den Zaubertrank braut? | Miraculix | Majestix ; Methusalix ; Troubadix | Er schneidet Misteln mit einer goldenen Sichel. ; Er trägt einen langen weißen Bart. ; Sein Name klingt nach „Wunder“. | Im französischen Original heißt der Druide Panoramix.
C E | Wie heißt Spider-Man mit bürgerlichem Namen? | Peter Parker | Bruce Wayne ; Clark Kent ; Tony Stark | Er lebt in New York bei Tante May. ; Seine Initialen sind gleich. ; Er arbeitet als Fotograf. | Stan Lee liebte Alliterationen: Peter Parker, Bruce Banner, Reed Richards.
C E | Welcher Marvel-Held trägt einen runden Schild mit Stern in den US-Farben? | Captain America | Iron Man ; Thor ; Black Panther | Er erschien erstmals 1941. ; Er boxt auf dem Cover Hitler. ; Sein Name ist Steve Rogers. | Der Schild von Captain America besteht im Marvel-Universum aus Vibranium.
W M | Der Comic-Kater Garfield hasst Montage. | wahr | Jim Davis' Garfield liebt Lasagne und Schlaf — und hasst Montage und Diäten.

@ weltliteratur
C E | Wer schrieb die Kinderbücher über die „Kinder aus Bullerbü“? | Astrid Lindgren | Selma Lagerlöf ; Tove Jansson ; Cornelia Funke | Sie war Schwedin. ; Sie erfand auch Michel aus Lönneberga. ; Pippi Langstrumpf ist ihre berühmteste Figur. | Astrid Lindgrens Bücher wurden in über 100 Sprachen übersetzt.
C E | Wie heißt der Piratenkapitän mit der Hakenhand, Gegenspieler von Peter Pan? | Käpt'n Hook | Kapitän Ahab ; Long John Silver ; Kapitän Nemo | Ein Krokodil hat seine Hand gefressen. ; Das Krokodil hat auch einen Wecker verschluckt. ; Sein Name bedeutet auf Englisch „Haken“. | James M. Barries Peter Pan erschien 1904 als Theaterstück, 1911 als Roman.
C H | Welcher Autor schrieb „Der Graf von Monte Christo“? | Alexandre Dumas | Victor Hugo ; Jules Verne ; Honoré de Balzac | Er schrieb auch „Die drei Musketiere“. ; Er war Franzose. ; Sein Sohn hieß genauso. | Edmond Dantès flieht aus dem Château d'If und rächt sich als Graf von Monte Christo.
C H | In welchem Roman von Jules Verne reisen Forscher durch einen Vulkan ins Erdinnere? | Reise zum Mittelpunkt der Erde | 20.000 Meilen unter dem Meer ; Die geheimnisvolle Insel ; Von der Erde zum Mond | Der Einstieg liegt auf Island. ; Professor Lidenbrock leitet die Expedition. ; Sie wollen ins Zentrum. | Der Roman erschien 1864; der Einstieg ist der isländische Vulkan Snæfellsjökull.
W H | Die Geschichten von „Tausendundeiner Nacht“ erzählt Scheherazade, um ihr Leben zu retten. | wahr | Sie erzählt dem König jede Nacht eine Geschichte und hört an der spannendsten Stelle auf.

@ theater_musical
C E | Wer schrieb das Drama „Hamlet“ mit dem Satz „Sein oder Nichtsein“? | William Shakespeare | Christopher Marlowe ; Ben Jonson ; Oscar Wilde | Er stammte aus Stratford-upon-Avon. ; Er schrieb auch „Macbeth“. ; Sein Theater hieß Globe. | Hamlet ist Shakespeares längstes Stück — ungekürzt dauert es über vier Stunden.
C H | Welche Figur ist in Mozarts „Zauberflöte“ ein Vogelfänger im Federkleid? | Papageno | Tamino ; Sarastro ; Monostatos | Seine Partnerin heißt ähnlich. ; Er spielt ein Glockenspiel. ; Sein Name erinnert an einen bunten Vogel. | Papageno und Papagena singen das berühmte „Pa-Pa-Pa“-Duett.
@ maerchen_sagen
C E | Welches Märchenmädchen trägt eine rote Kappe und besucht seine Großmutter im Wald? | Rotkäppchen | Schneewittchen ; Gretel ; Goldmarie | Ein Wolf lauert ihr auf. ; Sie bringt Kuchen und Wein. ; Die Kopfbedeckung gibt ihr den Namen. | Bei Charles Perrault endet die Geschichte ohne rettenden Jäger.
C U | Wie heißt die Hexe, die im russischen Märchen in einem Haus auf Hühnerbeinen lebt? | Baba Jaga | Frau Holle ; Morgana ; Kikimora | Sie fliegt in einem Mörser. ; Ihr Haus dreht sich. ; Ihr Name beginnt mit „Baba“. | Baba Jaga ist die berühmteste Hexe der slawischen Märchenwelt.
O E | Sortiere die Bremer Stadtmusikanten, wie sie im Märchen übereinanderstehen — von unten nach oben. | Esel = ganz unten ; Hund = zweiter von unten ; Katze = zweiter von oben ; Hahn = ganz oben | Das größte Tier trägt alle. ; Der Hund steht auf dem Esel. ; Das kleinste kräht ganz oben. | So erschreckten sie die Räuber und bekamen ihr Haus.
M M | Welche ZWEI dieser Märchen stammen von Hans Christian Andersen? | Das hässliche Entlein ; Die Prinzessin auf der Erbse | Hänsel und Gretel ; Rotkäppchen ; Frau Holle ; Rumpelstilzchen | Beide stammen aus Dänemark. ; In einem wird ein Vogel zum Schwan. ; Die übrigen sind Grimm-Märchen. | Andersen schrieb rund 160 Märchen.

@ gemaelde_erkennen
O H | Sortiere diese Maler nach ihrem Geburtsjahr — den frühesten zuerst. | Albrecht Dürer = 1471 ; Rembrandt = 1606 ; Vincent van Gogh = 1853 ; Pablo Picasso = 1881 | Der Nürnberger kommt zuerst. ; Der Niederländer mit der Nachtwache folgt. ; Der Spanier ist der jüngste. | Dürer und Picasso trennen über 400 Jahre.
M H | Welche ZWEI dieser Gemälde stammen von Leonardo da Vinci? | Mona Lisa ; Das Abendmahl | Die Geburt der Venus ; Die Nachtwache ; Der Schrei ; Sternennacht | Eines hängt im Louvre. ; Das andere ist ein Wandbild in Mailand. ; Botticelli, Rembrandt, Munch und van Gogh scheiden aus. | Von Leonardo sind nur rund 15 bis 20 Gemälde erhalten.
C U | Wer malte „Das Floß der Medusa“, das Schiffbrüchige nach einem realen Unglück von 1816 zeigt? | Théodore Géricault | Eugène Delacroix ; Jacques-Louis David ; Gustave Courbet | Er war französischer Romantiker. ; Das Bild hängt im Louvre. ; Er starb schon mit 32 Jahren. | Géricault studierte für das Bild sogar Leichen in Krankenhäusern.

@ architektur_bauwerke
O M | Sortiere diese Baustile chronologisch — den frühesten zuerst. | Romanik = ab ca. 1000 ; Gotik = ab ca. 1150 ; Renaissance = ab ca. 1420 ; Barock = ab ca. 1600 | Rundbögen kamen vor Spitzbögen. ; Die „Wiedergeburt“ der Antike folgte. ; Der prunkvolle Stil kam zuletzt. | Der Kölner Dom ist gotisch, der Speyerer Dom romanisch.
M U | Welche ZWEI dieser Architekten leiteten das Bauhaus als Direktor? | Walter Gropius ; Ludwig Mies van der Rohe | Le Corbusier ; Frank Lloyd Wright ; Antoni Gaudí ; Zaha Hadid | Einer gründete es 1919. ; Der andere war der letzte Direktor. ; Hannes Meyer war der dritte im Bunde. | Das Bauhaus wurde 1933 unter dem Druck der Nationalsozialisten aufgelöst.

@ weltliteratur
O E | Sortiere diese Harry-Potter-Bände in die richtige Reihenfolge. | Der Stein der Weisen = Band 1 ; Die Kammer des Schreckens = Band 2 ; Der Gefangene von Askaban = Band 3 ; Der Feuerkelch = Band 4 | Alles beginnt mit einem magischen Stein. ; Dann öffnet sich eine Kammer. ; Im vierten Band gibt es ein Turnier. | Die Reihe umfasst sieben Bände, der letzte erschien 2007.

@ deutsche_literatur de
C U | Welcher Roman von Thomas Mann spielt in einem Lungensanatorium in Davos? | Der Zauberberg | Buddenbrooks ; Doktor Faustus ; Tod in Venedig | Hans Castorp bleibt dort sieben Jahre. ; Der Roman erschien 1924. ; Ein Berg steckt im Titel. | Thomas Mann besuchte selbst seine Frau Katia in einem Davoser Sanatorium.
M M | Welche ZWEI dieser Werke schrieb Johann Wolfgang von Goethe? | Faust ; Die Leiden des jungen Werthers | Die Räuber ; Nathan der Weise ; Woyzeck ; Der Zauberberg | Eines handelt von einem Pakt mit dem Teufel. ; Das andere ist ein Briefroman. ; Schiller, Lessing, Büchner und Mann scheiden aus. | Goethe arbeitete fast 60 Jahre lang an „Faust“.
"""
