"""Extra questions: Kurioses & Mixed (format: see tools/content/merge_extra.py)."""
KAT = "kurioses_mixed"
REGION = "global"
DATA = r"""
@ schaetzmeister
S E | Wie viele Monate eines Jahres haben 31 Tage? | 7 | Monate | 15 | 1 | 12 | Januar gehört dazu. ; Juli und August liegen direkt hintereinander. ; Mehr als die Hälfte. | Januar, März, Mai, Juli, August, Oktober und Dezember haben 31 Tage.
S E | Wie viele Buchstaben hat „Monkey Money“ (ohne Leerzeichen)? | 11 | Buchstaben | 10 | 5 | 30 | Zähl einfach nach. ; Beide Wörter beginnen mit M. ; Eine Schnapszahl. | M-O-N-K-E-Y plus M-O-N-E-Y ergibt elf Buchstaben.
S E | Wie viele Stunden hat eine Woche? | 168 | Stunden | 10 | 24 | 1000 | Sieben mal 24. ; Mehr als 150. ; Weniger als 200. | Davon verschläft ein Mensch im Schnitt rund 50 Stunden.
S E | Wie viele Minuten hat ein Tag? | 1440 | Minuten | 10 | 100 | 10000 | 24 mal 60. ; Mehr als 1000. ; Weniger als 1500. | 24 Stunden à 60 Minuten ergeben 1440 Minuten.
S E | Wie viele Wochen hat ein Jahr ungefähr? | 52 | Wochen | 5 | 10 | 100 | 365 geteilt durch 7. ; Etwas mehr als 50. ; Genau so viele Karten hat ein Pokerblatt. | 52 Wochen und ein Tag — in Schaltjahren zwei Tage.
S E | Wie viele Tage hat ein Schaltjahr? | 366 | Tage | 1 | 300 | 400 | Einer mehr als normal. ; Der Februar hat dann 29 Tage. ; Es kommt alle vier Jahre. | Der 29. Februar gleicht aus, dass ein Sonnenjahr rund 365,25 Tage dauert.
S M | Wie viele Meter misst eine Runde auf der Innenbahn einer Standard-Leichtathletikbahn? | 400 | Meter | 5 | 100 | 1000 | Eine Stadionrunde. ; Mehr als 300. ; Eine glatte Hunderterzahl. | Weiter außen liegende Bahnen sind länger — darum starten Läufer versetzt.
S E | Aus wie vielen Kästchen besteht ein klassisches Sudoku? | 81 | Kästchen | 10 | 20 | 200 | Neun mal neun. ; Mehr als 80. ; Eine Quadratzahl. | Ein Sudoku hat neun Zeilen, neun Spalten und neun 3×3-Blöcke.
S H | Wie viele Stufen führen im Eiffelturm bis zur Spitze? | 1665 | Stufen | 25 | 100 | 5000 | log | Man darf nur bis zur zweiten Etage laufen. ; Deutlich mehr als 1000. ; Weniger als 2000. | Bis zur Spitze sind es 1665 Stufen — für Besucher ist ab der zweiten Etage aber der Aufzug Pflicht.
S M | Wie viele Karten hat ein klassisches Skatspiel? | 32 | Karten | 10 | 10 | 100 | Deutlich weniger als ein Pokerblatt. ; Vier Farben zu je acht Karten. ; Zwei hoch fünf. | Beim Skat liegen zwei Karten im „Skat“, jeder der drei Spieler bekommt zehn.
S M | Wie viele Kegel stehen beim klassischen Kegeln auf der Bahn? | 9 | Kegel | 15 | 1 | 20 | Beim Bowling ist es einer mehr. ; Sie stehen in Rautenform. ; Eine ungerade Zahl. | Beim Kegeln stehen neun Kegel in Rautenform, beim Bowling zehn Pins im Dreieck.
S E | Mit wie vielen Figuren beginnt jeder Spieler eine Schachpartie? | 16 | Figuren | 10 | 4 | 40 | Acht davon sind Bauern. ; Dazu kommen König, Dame, zwei Türme, zwei Läufer und zwei Springer. ; Eine Zweierpotenz. | Beide Spieler zusammen haben also 32 Figuren auf dem Brett.
S H | Wie viele Liter Wasser verbraucht eine Person in Deutschland durchschnittlich pro Tag? | 125 | Liter | 25 | 10 | 1000 | log | Duschen und Toilette verbrauchen am meisten. ; Mehr als 100. ; Weniger als 150. | Der Pro-Kopf-Verbrauch liegt seit Jahren bei rund 120 bis 130 Litern pro Tag.
S M | Wie viele Tage dauert es, bis ein Hühnerküken aus dem Ei schlüpft? | 21 | Tage | 15 | 3 | 60 | Drei Wochen. ; Mehr als 20. ; Eine Zahl aus dem Blackjack. | Das Brutei muss dafür 21 Tage bei rund 37,5 °C bebrütet werden.
S U | Wie viele Einwohner hat Liechtenstein ungefähr (in Tausend)? | 40 | Tausend | 20 | 5 | 500 | log | Weniger als eine deutsche Großstadt. ; Etwa so viele wie eine Kleinstadt. ; Knapp 40.000. | Liechtenstein ist mit rund 160 Quadratkilometern der sechstkleinste Staat der Erde.
S U | Wie viele Tasten hat eine normale deutsche Computertastatur (Standard-QWERTZ mit Ziffernblock)? | 105 | Tasten | 10 | 30 | 300 | Mehr als 100. ; Mit Ziffernblock. ; Die US-Version hat eine Taste weniger. | Die deutsche Volltastatur hat 105 Tasten, die US-Tastatur 104.
S H | Mit wie vielen Kilometern pro Sekunde rast die Erde ungefähr um die Sonne? | 30 | km/s | 20 | 1 | 500 | log | Viel schneller als jede Rakete. ; Mehr als 25. ; Rund 100.000 km/h. | Die Erde legt auf ihrer Bahn rund 29,8 Kilometer pro Sekunde zurück.
S H | Wie viele Jahre alt ist die Erde ungefähr (in Milliarden)? | 4.5 | Mrd. Jahre | 15 | 0.1 | 20 | log | Deutlich jünger als das Universum. ; Mehr als vier. ; Weniger als fünf. | Das Alter der Erde wird auf rund 4,54 Milliarden Jahre geschätzt.
S H | Wie viele Kilometer Durchmesser hat der Mond ungefähr? | 3474 | km | 15 | 100 | 20000 | log | Etwa ein Viertel der Erde. ; Mehr als 3000. ; Ungefähr die Strecke Lissabon–Moskau. | Der Mond ist mit 3474 Kilometern Durchmesser der fünftgrößte Mond im Sonnensystem.
S H | Um wie viel Grad ist die Erdachse ungefähr geneigt? | 23.4 | Grad | 10 | 1 | 90 | Deshalb gibt es Jahreszeiten. ; Mehr als 20. ; Weniger als 25. | Die Neigung von rund 23,4 Grad bestimmt auch die Lage der Wendekreise.
S U | Wie viele Einzelteile hat der klassische Zauberwürfel sichtbar (inklusive Mittelsteine)? | 26 | Teile | 15 | 5 | 60 | Ein 3×3×3-Würfel ohne den unsichtbaren Kern. ; 27 minus 1. ; Mehr als 20. | 8 Ecken, 12 Kanten und 6 Mittelsteine ergeben 26 sichtbare Teile.
S U | Wie viele Einwohner hat die Vatikanstadt ungefähr? | 800 | Einwohner | 30 | 10 | 100000 | log | Weniger als 1000. ; Mehr als 500. ; Kaum mehr als ein großes Dorf. | Die meisten Bewohner sind Geistliche oder Schweizergardisten.
S U | Wie viele Buchstaben hat das hawaiianische Alphabet? | 13 | Buchstaben | 15 | 5 | 30 | Es ist extrem kurz. ; Fünf Vokale gehören dazu. ; Eine Unglückszahl. | Neben A, E, I, O, U gibt es H, K, L, M, N, P, W und den Okina-Laut.
S U | Wie viele Grad Celsius heiß wird die Oberfläche der Venus ungefähr? | 465 | °C | 15 | 50 | 2000 | log | Heißer als ein Pizzaofen. ; Blei würde dort schmelzen. ; Mehr als 400. | Die dichte CO₂-Atmosphäre macht die Venus zum heißesten Planeten.
S U | Wie viele Millionen Erdkugeln würden ungefähr in die Sonne passen? | 1.3 | Mio. | 30 | 0.01 | 100 | log | Es sind mehr als eine Million. ; Der Sonnendurchmesser ist rund 109-mal so groß wie der der Erde. ; 109 hoch drei. | Rund 1,3 Millionen Erden hätten im Volumen der Sonne Platz.
S U | Wie viele Zeitzonen hat Frankreich einschließlich seiner Überseegebiete? | 12 | Zeitzonen | 15 | 1 | 30 | Mehr als Russland. ; Überseegebiete liegen im Pazifik, in der Karibik und im Indischen Ozean. ; Ein Dutzend. | Dank Gebieten wie Französisch-Polynesien und Réunion hat Frankreich die meisten Zeitzonen der Welt.

@ rekorde_superlative
C E | Welches ist der meistbesuchte Freizeitpark Deutschlands? | Europa-Park | Phantasialand ; Heide Park ; Movie Park | Er liegt in Rust in Baden-Württemberg. ; Die Themenbereiche sind europäischen Ländern nachempfunden. ; Sein Maskottchen ist eine Maus namens Euromaus. | Der Europa-Park zählt jährlich rund sechs Millionen Besucher.
C M | Welches Bauwerk gilt als meistbesuchtes kostenpflichtiges Monument der Welt? | Eiffelturm | Kolosseum ; Freiheitsstatue ; Tower of London | Es steht in einer europäischen Hauptstadt. ; Es wurde 1889 eröffnet. ; Es besteht aus rund 18.000 Eisenteilen. | Der Eiffelturm zählt pro Jahr rund sechs bis sieben Millionen zahlende Besucher.
C M | Welches Album gilt als das meistverkaufte Musikalbum aller Zeiten? | Thriller von Michael Jackson | Back in Black von AC/DC ; The Dark Side of the Moon von Pink Floyd ; Abbey Road von den Beatles | Es erschien 1982. ; Das Musikvideo zum Titelsong zeigt Zombies. ; Der Künstler heißt „King of Pop“. | „Thriller“ verkaufte sich weltweit schätzungsweise rund 70 Millionen Mal.
C E | Welche Buchreihe gilt als meistverkaufte aller Zeiten? | Harry Potter | Der Herr der Ringe ; Die Tribute von Panem ; Twilight | Sie hat sieben Bände. ; Es geht um eine Zauberschule. ; Die Autorin ist J. K. Rowling. | Die Harry-Potter-Bücher verkauften sich über 500 Millionen Mal.
C M | Welche Sprache hat die meisten Muttersprachler der Welt? | Mandarin-Chinesisch | Englisch ; Spanisch ; Hindi | Es ist eine tonale Sprache. ; Sie wird in Peking gesprochen. ; Über 900 Millionen Menschen sprechen sie als Muttersprache. | Englisch hat mehr Sprecher insgesamt, Mandarin aber die meisten Muttersprachler.
C H | Welches Land hat die meisten Pyramiden? | Sudan | Ägypten ; Mexiko ; Peru | Das Land liegt südlich von Ägypten. ; Die Pyramiden stammen vom Reich von Kusch. ; Viele stehen bei Meroe. | Im Sudan stehen rund 200 bis 250 nubische Pyramiden — mehr als in Ägypten.
C H | Welche Brücke ist das höchste Brückenbauwerk der Welt? | Viaduc de Millau | Golden Gate Bridge ; Øresundbrücke ; Köhlbrandbrücke | Sie steht in Südfrankreich. ; Mit Mast ist er höher als der Eiffelturm. ; Norman Foster hat sie entworfen. | Der höchste Pfeiler des Viaduc de Millau ist mit Mast 343 Meter hoch.
C U | Welches Restaurant gilt laut Guinness als ältestes noch betriebenes der Welt? | Sobrino de Botín in Madrid | Zum Arabischen Coffe Baum in Leipzig ; Rules in London ; Le Procope in Paris | Es eröffnete 1725. ; Hemingway aß dort gern Spanferkel. ; Es liegt in Spaniens Hauptstadt. | Im Botín brennt der Holzofen angeblich seit der Eröffnung.
C U | Welcher Bahnhof hat laut Guinness die meisten Bahnsteige der Welt? | Grand Central Terminal in New York | Leipzig Hauptbahnhof ; Gare du Nord in Paris ; Shinjuku in Tokio | Er hat 44 Bahnsteige. ; Die Haupthalle hat eine Sternbild-Decke. ; Er liegt in Manhattan. | Grand Central hat 44 Bahnsteige an 67 Gleisen auf zwei Ebenen.
C U | Welches Videospiel gilt (Stand 2024) als das meistverkaufte aller Zeiten? | Minecraft | Tetris ; GTA V ; Wii Sports | Es besteht aus Blöcken. ; Es gehört seit 2014 Microsoft. ; Ein Creeper explodiert darin. | Minecraft verkaufte sich über 300 Millionen Mal.
W M | Giraffen haben eine dunkle, blau-violette Zunge. | wahr | Die dunkle Farbe schützt die bis zu 50 Zentimeter lange Zunge vermutlich vor Sonnenbrand.
W H | Die Chinesische Mauer ist länger als der Erdumfang am Äquator. | falsch | Alle Abschnitte zusammen messen rund 21.000 Kilometer — der Äquator ist über 40.000 Kilometer lang.
O M | Sortiere diese Tiere nach ihrer Höchstgeschwindigkeit — das langsamste zuerst. | Weinbergschnecke = ≈ 0,003 km/h ; Mensch (Sprint) = ≈ 44 km/h ; Pferd = ≈ 70 km/h ; Gepard = ≈ 110 km/h | Das erste trägt sein Haus auf dem Rücken. ; Der Mensch liegt vor dem Pferd. ; Die Raubkatze gewinnt. | Usain Bolt erreichte beim Weltrekordlauf kurzzeitig rund 44 km/h.
O H | Sortiere diese Vögel nach ihrer Größe — den kleinsten zuerst. | Bienenelfe = ≈ 5 cm ; Rotkehlchen = ≈ 14 cm ; Weißstorch = ≈ 100 cm ; Strauß = ≈ 250 cm | Der kleinste ist ein Kolibri aus Kuba. ; Der Singvogel ist viel kleiner als der Storch. ; Der Laufvogel ist der größte. | Die Bienenelfe ist mit knapp zwei Gramm der kleinste Vogel der Welt.

@ wer_bin_ich
C E | Ich bin ein Kobold mit roten Haaren, wohne bei einem Münchner Schreinermeister und bin für andere Menschen unsichtbar — wer bin ich? | Pumuckl | Rumpelstilzchen ; Pittiplatsch ; Sams | Mein Meister heißt Eder. ; Ich reime gern. ; Ich bin an einem Leimtopf kleben geblieben. | Der Pumuckl wurde 1962 von Ellis Kaut als Hörspielfigur erfunden.
C E | Ich bin eine kleine gelb-schwarze Biene, fliege neugierig durch die Welt und mein bester Freund heißt Willi — wer bin ich? | Biene Maja | Puck die Stubenfliege ; Flip der Grashüpfer ; Summsi | Ein Lied besingt mich als „kleine, freche, schlaue“. ; Ich stamme aus einem Buch von Waldemar Bonsels. ; Mein Name hat vier Buchstaben. | Waldemar Bonsels schrieb „Die Biene Maja und ihre Abenteuer“ 1912.
C E | Ich bin eine schwarze Maus mit großen runden Ohren, roten Hosen und weißen Handschuhen — wer bin ich? | Micky Maus | Speedy Gonzales ; Jerry ; Mausi | Walt Disney hat mich erfunden. ; Meine Freundin heißt Minnie. ; Mein erster großer Auftritt war „Steamboat Willie“. | Micky Maus feierte 1928 im Film „Steamboat Willie“ Premiere.
C E | Ich bin ein grüner Oger, lebe in einem Sumpf und mein bester Freund ist ein redseliger Esel — wer bin ich? | Shrek | Hulk ; Grinch ; Yoda | Ich heirate Prinzessin Fiona. ; Mein Name bedeutet auf Jiddisch „Schrecken“. ; Mein Film erschien 2001. | Shrek gewann 2002 als erster Film den Oscar für den besten Animationsfilm.
C E | Ich bin ein gelber Familienvater aus Springfield, liebe Donuts und Bier und rufe gern „Nein!“ — wer bin ich? | Homer Simpson | Peter Griffin ; Fred Feuerstein ; Al Bundy | Meine Frau heißt Marge. ; Ich arbeite im Atomkraftwerk. ; Mein Sohn heißt Bart. | Im Original ruft Homer „D'oh!“ — das Wort steht inzwischen im Oxford English Dictionary.
C E | Ich bin ein kleiner, grünhäutiger Jedi-Meister, spreche mit verdrehtem Satzbau und bin rund 900 Jahre alt — wer bin ich? | Yoda | Obi-Wan Kenobi ; Grogu ; E.T. | „Tun oder nicht tun — es gibt kein Versuchen.“ ; Ich lebe im Exil auf Dagobah. ; Mein Name hat vier Buchstaben. | Yoda trat erstmals 1980 in „Das Imperium schlägt zurück“ auf.
C E | Ich bin ein dicker Gallier mit rotem Zopf, trage Hinkelsteine und bin als Baby in den Zaubertrank gefallen — wer bin ich? | Obelix | Majestix ; Troubadix ; Automatix | Mein Hund heißt Idefix. ; Ich liebe Wildschweine. ; „Die spinnen, die Römer!“ | Obelix darf keinen Zaubertrank mehr trinken, weil die Wirkung bei ihm dauerhaft ist.
C E | Ich bin ein Zauberer mit langem Bart und spitzem Hut, führe die Gefährten durch Mittelerde und rufe „Du kannst nicht vorbei!“ — wer bin ich? | Gandalf | Saruman ; Dumbledore ; Merlin | Erst bin ich der Graue, später der Weiße. ; Ich kämpfe gegen einen Balrog. ; Ian McKellen spielte mich. | Im Film ruft Gandalf auf der Brücke von Khazad-dûm: „Du kannst nicht vorbei!“
C E | Ich bin ein Apachen-Häuptling, reite auf Iltschi und mein Blutsbruder heißt Old Shatterhand — wer bin ich? | Winnetou | Tecumseh ; Sitting Bull ; Chingachgook | Karl May hat mich erfunden. ; Pierre Brice spielte mich im Film. ; Meine Schwester heißt Nscho-tschi. | Die Winnetou-Filme der 1960er wurden großteils in Kroatien gedreht.
C M | Ich wurde 1685 in Eisenach geboren, war Thomaskantor in Leipzig und schrieb die Matthäus-Passion — wer bin ich? | Johann Sebastian Bach | Georg Friedrich Händel ; Georg Philipp Telemann ; Joseph Haydn | Ich hatte 20 Kinder. ; Mein Nachname ist ein kleines Gewässer. ; Ich schrieb die Brandenburgischen Konzerte. | Beethoven soll gesagt haben: „Nicht Bach, Meer sollte er heißen.“
C M | Ich schrieb mit Friedrich Engels das „Kommunistische Manifest“ und wurde 1818 in Trier geboren — wer bin ich? | Karl Marx | Friedrich Nietzsche ; Wladimir Lenin ; Ferdinand Lassalle | Mein Hauptwerk heißt „Das Kapital“. ; Ich bin in London begraben. ; Chemnitz hieß in der DDR nach mir. | Der „Nischel“ in Chemnitz ist eine über sieben Meter hohe Büste von Marx.
C M | Ich reiste auf der „Beagle“ zu den Galápagos-Inseln und schrieb über die Entstehung der Arten — wer bin ich? | Charles Darwin | Alexander von Humboldt ; Gregor Mendel ; James Cook | Finken halfen mir beim Nachdenken. ; Ich war Engländer. ; Meine Theorie heißt Evolutionstheorie. | Darwins „Über die Entstehung der Arten“ erschien 1859.
C E | Ich bin der „King of Rock 'n' Roll“, lebte in Graceland und sang „Jailhouse Rock“ — wer bin ich? | Elvis Presley | Chuck Berry ; Little Richard ; Johnny Cash | Ich diente als Soldat in Deutschland. ; Mein Hüftschwung war berühmt. ; Mein Vorname hat fünf Buchstaben. | Elvis war 1958–1960 als US-Soldat im hessischen Friedberg stationiert.
C H | Ich wurde 1564 in Pisa geboren, entdeckte die großen Jupitermonde und musste meine Lehre vor der Inquisition widerrufen — wer bin ich? | Galileo Galilei | Johannes Kepler ; Nikolaus Kopernikus ; Giordano Bruno | „Und sie bewegt sich doch!“ soll ich gesagt haben. ; Ich baute ein verbessertes Fernrohr. ; Vor- und Nachname beginnen gleich. | 1992 rehabilitierte die katholische Kirche Galilei offiziell.
C H | Ich wurde als Cassius Clay geboren, gewann 1960 Olympia-Gold und sagte „Ich schwebe wie ein Schmetterling und steche wie eine Biene“ — wer bin ich? | Muhammad Ali | Joe Frazier ; George Foreman ; Mike Tyson | Ich nannte mich „The Greatest“. ; Ich kämpfte 1974 in Kinshasa. ; Ich verweigerte den Kriegsdienst in Vietnam. | Ali wurde dreimal Schwergewichtsweltmeister.
C U | Ich bin eine Figur von Ian Fleming, trinke Martini „geschüttelt, nicht gerührt“ und wurde zuerst im Kino von Sean Connery gespielt — wer bin ich? | James Bond | Jason Bourne ; Ethan Hunt ; Harry Palmer | Meine Nummer ist 007. ; Mein erster Kinofilm spielte auf Jamaika. ; Ich arbeite für den MI6. | Ian Fleming lieh sich den Namen von einem amerikanischen Vogelkundler.

@ buchstaben_woerter
C E | Wie nennt man das Zeichen „@“ im Deutschen umgangssprachlich? | Klammeraffe | Kringelschwanz ; Schneckenhaus ; Ohrwurm | Es steckt in jeder E-Mail-Adresse. ; Ein Tier steckt im Namen. ; Es sieht aus wie ein Affe mit Schwanz. | Im Englischen heißt das Zeichen schlicht „at“.
C E | Wie nennt man das Zeichen „#“ auf deutschen Telefontasten? | Raute | Stern ; Gitter ; Kreuzchen | In sozialen Medien heißt es Hashtag. ; Es ist nicht der Stern. ; Auch ein Kartenspielsymbol heißt so ähnlich. | In der Musik erhöht das ähnliche Zeichen ♯ einen Ton um einen Halbton.
C E | Wie heißt das Kinderspiel, bei dem man ein Wort mit zwei Bedeutungen erraten muss, etwa „Bank“ oder „Schloss“? | Teekesselchen | Stille Post ; Galgenmännchen ; Ich sehe was, was du nicht siehst | Die Spieler beschreiben „mein ...“ und „dein ...“. ; Der Name enthält ein Küchengerät. ; Es geht um Doppeldeutigkeiten. | Wörter mit mehreren Bedeutungen heißen in der Sprachwissenschaft Homonyme.
C E | Welcher Buchstabe steht im Alphabet zwischen „P“ und „R“? | Q | O ; S ; T | Er ist fast immer von einem „u“ gefolgt. ; Er kommt im Wort „Quark“ vor. ; Er sieht aus wie ein O mit Schwänzchen. | Das Q ist einer der seltensten Buchstaben der deutschen Sprache.
C M | Wie viele Buchstaben hat das griechische Alphabet? | 24 | 26 ; 22 ; 30 | Es beginnt mit Alpha. ; Es endet mit Omega. ; Zwei weniger als das lateinische. | Das Wort „Alphabet“ stammt von den ersten beiden griechischen Buchstaben Alpha und Beta.
C M | Welche Schrift verwendet die russische Sprache? | Kyrillisch | Glagolitisch ; Griechisch ; Lateinisch | Sie ist nach einem Heiligen benannt. ; Auch Bulgarisch und Serbisch nutzen sie. ; Das „R“ sieht dort aus wie ein „P“. | Die kyrillische Schrift ist nach dem Slawenapostel Kyrill benannt.
C M | Wie viele Zeilen hat ein Limerick? | 5 | 4 ; 6 ; 14 | Es ist ein lustiges Gedicht aus England. ; Das Reimschema ist aabba. ; Eine ungerade Zahl. | Limericks sind nach der irischen Stadt Limerick benannt.
C M | Wie viele Silben hat ein klassisches japanisches Haiku? | 17 | 14 ; 12 ; 21 | Die Zeilen haben 5, 7 und 5 Silben. ; Drei Zeilen. ; Eine Primzahl zwischen 10 und 20. | Das Haiku ist die kürzeste Gedichtform der Welt.
C M | Was ist ein Akronym? | Ein Kurzwort aus Anfangsbuchstaben, das man wie ein Wort spricht | Ein Wort mit gleichen Buchstaben vorwärts und rückwärts ; Ein Fremdwort aus dem Griechischen ; Ein Wort mit zwei Bedeutungen | Beispiele sind „Laser“ oder „UFO“. ; Man bildet es aus Anfangsbuchstaben. ; „NATO“ ist eines. | „Laser“ steht für „Light Amplification by Stimulated Emission of Radiation“.
C H | Welches dieser deutschen Wörter benutzen Englischsprachige NICHT in ihrer Sprache? | Handy | Angst ; Wanderlust ; Kitsch | Viele deutsche Wörter stehen im englischen Wörterbuch. ; Eines ist ein Scheinanglizismus. ; Es bezeichnet ein Telefon. | „Angst“, „Wanderlust“ und „Kitsch“ nutzen auch Englischsprachige.
C H | Wie heißt der letzte Buchstabe des griechischen Alphabets? | Omega | Omikron ; Ypsilon ; Zeta | Er ist Symbol für das Ende. ; „Das Alpha und das ...“. ; In der Physik steht er für den elektrischen Widerstand. | Das Zeichen Ω steht als Einheit für Ohm.
C U | Wie nennt man ein Wort, das rückwärts gelesen ein anderes sinnvolles Wort ergibt, etwa „Lager – Regal“ oder „Gras – Sarg“? | Ananym | Palindrom ; Anagramm ; Homonym | Ein Palindrom ergäbe dasselbe Wort. ; Die englische Bezeichnung ist „Palindromes“ rückwärts. ; „Lager“ rückwärts ist „Regal“. | Der englische Begriff „semordnilap“ ist selbst ein Beispiel.
W E | Hebräisch und Arabisch schreibt man von rechts nach links. | wahr | Beide Schriften werden von rechts nach links gelesen — Zahlen aber meist von links nach rechts.
W M | Das Wort „Kindergarten“ wird auch im Englischen verwendet. | wahr | Friedrich Fröbel gründete 1840 den ersten Kindergarten — das Wort wanderte in viele Sprachen.
W H | Im deutschen Alphabet ist „Y“ der seltenste Buchstabe in Texten. | falsch | In deutschen Texten sind Q und X seltener als Y — besonders Q ist fast immer an „u“ gebunden.
S E | Wie viele Buchstaben hat das lateinische Grundalphabet? | 26 | Buchstaben | 5 | 10 | 50 | Ohne Umlaute und ß. ; Mehr als 25. ; Zwei mehr als das griechische. | Mit Ä, Ö, Ü und ß kommt das deutsche Alphabet auf 30 Buchstaben.
O E | Sortiere diese Buchstaben in die Reihenfolge des Alphabets. | F = 6. Buchstabe ; K = 11. Buchstabe ; P = 16. Buchstabe ; W = 23. Buchstabe | Sag das ABC auf. ; K kommt vor P. ; W steht weit hinten. | Das Alphabet ist nach dem phönizischen Vorbild geordnet.
O H | Sortiere diese Alphabete nach der Anzahl ihrer Buchstaben — das kürzeste zuerst. | Hawaiianisch = 13 ; Griechisch = 24 ; Lateinisch = 26 ; Russisch (Kyrillisch) = 33 | Das kürzeste stammt von einer Inselgruppe im Pazifik. ; Die griechische Schrift hat zwei Buchstaben weniger als unsere. ; Die russische Schrift hat die meisten. | Das russische Alphabet hat 33 Buchstaben, darunter Zeichen wie Ж und Щ.
M E | Welche ZWEI dieser Wörter sind Palindrome? | Rentner ; Lagerregal | Regenwurm ; Bananen ; Lampe ; Kaffee | Vorwärts und rückwärts gleich. ; Eines ist ein Ruheständler. ; Das andere steht im Keller. | „Rentner“ und „Lagerregal“ lesen sich in beide Richtungen gleich.

@ stimmts_oder_quatsch
W E | Pluto gilt seit 2006 nicht mehr als Planet, sondern als Zwergplanet. | wahr | Die Internationale Astronomische Union stufte Pluto 2006 zum Zwergplaneten herab.
W M | Albert Einstein bekam den Nobelpreis für seine Relativitätstheorie. | falsch | Einstein erhielt den Physik-Nobelpreis 1921 für die Erklärung des photoelektrischen Effekts.
W M | Die Freiheitsstatue war ursprünglich kupferbraun und nicht grün. | wahr | Die Statue besteht aus Kupfer; die grüne Patina bildete sich erst in den Jahrzehnten nach 1886.
W M | Kaiser Nero spielte beim Brand Roms Geige. | falsch | Geigen gab es erst rund 1500 Jahre später — die Legende spricht von einer Leier, und auch das ist unbelegt.
W H | Vom Mond aus sieht man immer dieselbe Seite der Erde. | falsch | Umgekehrt stimmt es: Von der Erde sieht man immer dieselbe Mondseite, weil der Mond gebunden rotiert.
W H | Von der Erde aus sieht man immer dieselbe Seite des Mondes. | wahr | Der Mond dreht sich in derselben Zeit einmal um sich selbst, in der er die Erde umrundet.
W U | Albert Einstein war in der Schule schlecht in Mathematik. | falsch | Einstein war in Mathematik hervorragend — der Mythos entstand vermutlich durch eine Umstellung der Schweizer Notenskala.
@ stimmts_oder_quatsch
O E | Sortiere diese Tiere nach der Zahl ihrer Beine — die wenigsten zuerst. | Schlange = 0 ; Huhn = 2 ; Hund = 4 ; Spinne = 8 | Eine hat gar keine. ; Der Vogel hat zwei. ; Das Spinnentier hat die meisten. | Insekten hätten mit sechs Beinen zwischen Hund und Spinne gepasst.
O H | Sortiere diese Erfindungen nach ihrem Alter — die älteste zuerst. | Rad = ≈ 3500 v. Chr. ; Papier = ≈ 100 n. Chr. ; Buchdruck = ≈ 1450 ; Telefon = 1876 | Die älteste rollt. ; Die zweite kam aus China. ; Das Gerät zum Sprechen ist die jüngste. | Papier wird traditionell dem chinesischen Beamten Cai Lun zugeschrieben.

@ buchstaben_woerter
M E | Welche ZWEI dieser Länder enden auf „-stan“? | Kasachstan ; Pakistan | Iran ; Irak ; Nepal ; Oman | „Stan“ bedeutet auf Persisch „Land“. ; Eines ist der größte Binnenstaat der Erde. ; Das andere grenzt an Indien. | Es gibt sieben „-stan“-Staaten, etwa auch Usbekistan und Afghanistan.
C U | Wie nennt man die Angst vor der Zahl 13? | Triskaidekaphobie | Arachnophobie ; Klaustrophobie ; Akrophobie | Das Wort enthält die griechische Zahl dreizehn. ; Manche Hotels haben deshalb keinen 13. Stock. ; Es ist ein sehr langes Wort. | Die Angst vor Freitag, dem 13., heißt Paraskavedekatriaphobie.

@ rekorde_superlative
M E | Welche ZWEI dieser Zahlen sind Primzahlen? | 13 ; 29 | 21 ; 27 ; 33 ; 49 | Sie sind nur durch 1 und sich selbst teilbar. ; Eine ist die „Unglückszahl“. ; 21, 27, 33 und 49 lassen sich teilen. | 49 = 7 × 7, 21 = 3 × 7, 27 = 3 × 9, 33 = 3 × 11.
"""
