"""Extra questions: Musik (format: see tools/content/merge_extra.py)."""
KAT = "musik"
REGION = "global"
DATA = r"""
@ klassik_filmmusik
C E | Aus wie vielen Linien besteht ein normales Notensystem? | 5 | 4 ; 6 ; 7 | Die Noten sitzen auf und zwischen den Linien. ; Mehr als vier. ; So viele Finger hat eine Hand. | Die fünf Linien heißen Notenlinien; darüber und darunter helfen Hilfslinien.
C E | Wie heißt der Notenschlüssel, mit dem meist Melodien für Geige oder rechte Klavierhand notiert werden? | Violinschlüssel | Bassschlüssel ; Altschlüssel ; Tenorschlüssel | Er sieht aus wie ein verschnörkeltes G. ; Er heißt auch G-Schlüssel. ; Er ist nach einem Streichinstrument benannt. | Der Violinschlüssel legt fest, wo auf den Linien das g' liegt.
C E | Welches Instrument erfand der Belgier Adolphe Sax um 1840? | Saxofon | Tuba ; Klarinette ; Posaune | Das Instrument trägt seinen Namen. ; Es ist aus Metall, zählt aber zu den Holzblasinstrumenten. ; Es ist im Jazz sehr beliebt. | Das Saxofon zählt wegen seines Rohrblatts zu den Holzblasinstrumenten.
C E | Welches Instrument hat schwarze und weiße Tasten? | Klavier | Geige ; Trompete ; Schlagzeug | Man spielt es mit beiden Händen. ; Ein großes heißt Flügel. ; Ein Mann namens Cristofori baute es um 1700. | Bartolomeo Cristofori entwickelte um 1700 in Florenz das Hammerklavier.
C E | Von welchem Komponisten stammt das bekannte Klavierstück „Für Elise“? | Ludwig van Beethoven | Wolfgang Amadeus Mozart ; Frédéric Chopin ; Franz Schubert | Er wurde in Bonn geboren. ; Er wurde später taub. ; Er schrieb neun Sinfonien. | Wer „Elise“ war, ist bis heute nicht sicher geklärt.
C M | Wie viele Halbtöne umfasst eine Oktave? | 12 | 8 ; 7 ; 10 | Auf dem Klavier zählt man weiße und schwarze Tasten zusammen. ; Die Tonleiter hat nur acht Stammtöne inklusive Oktave. ; Ein Dutzend. | Sieben weiße und fünf schwarze Tasten ergeben die zwölf Halbtöne einer Oktave.
C M | Welches Gerät gibt Musikern mit gleichmäßigem Klicken das Tempo vor? | Metronom | Stimmgabel ; Taktstock ; Tonometer | Johann Nepomuk Mälzel machte es berühmt. ; Die Einheit ist „Schläge pro Minute“. ; Es hat oft ein schwingendes Pendel. | Beethoven gehörte zu den ersten Komponisten, die Metronomangaben in Noten schrieben.
C H | Welche Tonhöhe hat der Kammerton a' nach heutiger Norm? | 440 Hertz | 400 Hertz ; 432 Hertz ; 480 Hertz | Orchester stimmen danach. ; Es ist eine dreistellige Zahl. ; Sie liegt zwischen 430 und 450. | Viele Orchester stimmen heute etwas höher, etwa auf 442 oder 443 Hertz.
C M | Wer komponierte das Oratorium „Der Messias“ mit dem berühmten „Halleluja“? | Georg Friedrich Händel | Johann Sebastian Bach ; Joseph Haydn ; Felix Mendelssohn | Er wurde in Halle geboren. ; Er lebte später in London. ; Er schrieb auch die „Wassermusik“. | Beim „Halleluja“ steht das Publikum traditionell auf.
C H | Wer komponierte die Melodie der heutigen deutschen Nationalhymne? | Joseph Haydn | Ludwig van Beethoven ; Wolfgang Amadeus Mozart ; Johann Strauss | Sie war ursprünglich eine Hymne für den österreichischen Kaiser. ; Der Komponist gilt als „Vater der Sinfonie“. ; Der Text stammt von Hoffmann von Fallersleben. | Haydn schrieb 1797 „Gott erhalte Franz den Kaiser“ — die Melodie der heutigen Hymne.
C M | Welche Melodie aus Beethovens 9. Sinfonie ist die offizielle Hymne der Europäischen Union? | Ode an die Freude | Mondscheinsonate ; Pathétique ; Eroica | Der Text stammt ursprünglich von Schiller. ; Die EU nutzt die Melodie ohne Worte. ; „Freude, schöner Götterfunken …“ | Die EU verwendet seit 1985 nur die Melodie, ohne Text.
C M | Welches Musikstück von Richard Wagner wurde durch den Film „Apocalypse Now“ weltberühmt? | Walkürenritt | Brautchor ; Tristan-Akkord ; Pilgerchor | Er stammt aus dem „Ring des Nibelungen“. ; Hubschrauber greifen dazu an. ; Walküren sind Kriegerinnen der nordischen Sage. | Der Walkürenritt eröffnet den dritten Akt der Oper „Die Walküre“.
C H | Wie viele Sätze hat eine klassische Sinfonie üblicherweise? | 4 | 3 ; 5 ; 2 | Einer davon ist oft ein Menuett oder Scherzo. ; Mehr als drei. ; Eine gerade Zahl. | Das klassische Schema: schneller Satz, langsamer Satz, Menuett/Scherzo, Finale.
C H | Welcher Komponist schrieb den „Radetzky-Marsch“, zu dem beim Wiener Neujahrskonzert geklatscht wird? | Johann Strauss (Vater) | Johann Strauss (Sohn) ; Josef Strauss ; Richard Strauss | Sein Sohn schrieb den Donauwalzer. ; Der Marsch entstand 1848. ; Er gehört zur Wiener Walzerdynastie. | Der Radetzky-Marsch ehrt Feldmarschall Radetzky und ist traditionell das letzte Stück des Neujahrskonzerts.
C U | Welches Instrument ist das tiefste der Holzbläser im Orchester? | Kontrafagott | Oboe ; Klarinette ; Englischhorn | Es ist eine größere Version des Fagotts. ; Sein Rohr ist fast sechs Meter lang. ; Das Präfix „Kontra“ bedeutet tief. | Das Kontrafagott klingt eine Oktave tiefer als das Fagott.
C U | Wer baute um 1700 in Florenz das erste Hammerklavier? | Bartolomeo Cristofori | Antonio Stradivari ; Gottfried Silbermann ; Ignaz Pleyel | Er war Instrumentenbauer der Medici. ; Sein Instrument hieß „Gravicembalo col piano e forte“. ; Sein Vorname ist Bartolomeo. | Aus „piano e forte“ (leise und laut) wurde der Name Pianoforte.
W E | Die Tuba gehört zu den Holzblasinstrumenten. | falsch | Die Tuba ist ein Blechblasinstrument — das tiefste im Orchester.
W M | Das Saxofon gehört zu den Holzblasinstrumenten, obwohl es aus Metall besteht. | wahr | Entscheidend ist die Tonerzeugung über ein Rohrblatt aus Schilfrohr.
W H | Die Querflöte zählt zu den Blechblasinstrumenten, weil sie aus Metall ist. | falsch | Die Querflöte ist ein Holzblasinstrument — früher bestand sie aus Holz, und der Ton entsteht ohne Lippenschwingung.
S H | Wie viele Schläge pro Minute entsprechen dem Tempo „Allegro“ ungefähr? | 130 | BPM | 20 | 40 | 250 | Es ist ein schnelles Tempo. ; Langsamer als „Presto“. ; Mehr als 100. | Allegro liegt je nach Quelle bei etwa 120 bis 156 Schlägen pro Minute.
S U | In welchem Jahr wurde die Wiener Staatsoper am Ring eröffnet? | 1869 | Jahr | 3 | 1700 | 2000 | Im 19. Jahrhundert. ; Kaiser Franz Joseph regierte. ; Das Jahr endet auf 9. | Zur Eröffnung am 25. Mai 1869 spielte man Mozarts „Don Giovanni“.
O M | Sortiere diese Streichinstrumente nach ihrer Tonlage — das höchste zuerst. | Violine = höchste ; Bratsche = zweithöchste ; Violoncello = zweittiefste ; Kontrabass = tiefste | Das kleinste Instrument klingt am höchsten. ; Die Viola heißt auch Bratsche. ; Das größte steht auf dem Boden. | Alle vier gehören zur Familie der Streichinstrumente.
O H | Sortiere diese Musikträger nach ihrer Markteinführung — den ältesten zuerst. | Schallplatte = 1887 ; Musikkassette = 1963 ; Audio-CD = 1982 ; MP3-Player = 1998 | Die älteste erfand Emil Berliner. ; Philips brachte die Kassette heraus. ; Der erste MP3-Player kam kurz vor der Jahrtausendwende. | Der erste MP3-Player für den Massenmarkt hieß MPMan und kam 1998 aus Südkorea.
M M | Welche ZWEI dieser Instrumente gehören zu einem klassischen Streichquartett? | Bratsche ; Violoncello | Kontrabass ; Harfe ; Flöte ; Klavier | Neben zwei Violinen spielen zwei weitere Instrumente mit. ; Eines ist etwas größer als eine Geige. ; Das andere spielt man sitzend zwischen den Knien. | Das Streichquartett besteht aus zwei Violinen, einer Viola und einem Cello.

@ pop_international
C E | Wie viele Mitglieder hatten die Beatles in ihrer berühmten Besetzung? | 4 | 3 ; 5 ; 6 | John, Paul, George und … ; Der Schlagzeuger hieß Ringo. ; Man nannte sie die „Fab Four“. | John Lennon, Paul McCartney, George Harrison und Ringo Starr.
C E | Welche Sängerin landete 1984 mit „Like a Virgin“ einen Welthit? | Madonna | Cyndi Lauper ; Whitney Houston ; Kylie Minogue | Man nennt sie „Queen of Pop“. ; Sie stammt aus Michigan. ; Ihr Künstlername ist ihr echter Vorname. | Madonna gilt laut Guinness als meistverkaufte Musikerin aller Zeiten.
C E | Wie viele Mitglieder hatten die Spice Girls? | 5 | 4 ; 3 ; 6 | Jede hatte einen Spitznamen wie „Posh“ oder „Baby“. ; Ihr Hit hieß „Wannabe“. ; Mehr als vier. | Victoria Beckham war „Posh Spice“.
C M | Auf welchem Zebrastreifen-Foto überqueren die Beatles eine Straße in London? | Abbey Road | Penny Lane ; Carnaby Street ; Baker Street | Es ist auch ein Albumtitel von 1969. ; Dort steht ein berühmtes Tonstudio. ; Die Straße liegt in St John's Wood. | Der Zebrastreifen an der Abbey Road steht seit 2010 unter Denkmalschutz.
C M | Welche Sängerin wurde als „Queen of Soul“ berühmt? | Aretha Franklin | Tina Turner ; Diana Ross ; Whitney Houston | Ihr Hit hieß „Respect“. ; Sie stammte aus Memphis und wuchs in Detroit auf. ; Sie sang 2009 bei der Amtseinführung von Barack Obama. | Aretha Franklin war 1987 die erste Frau in der Rock and Roll Hall of Fame.
C M | Welches französische Elektro-Duo trat stets mit Roboterhelmen auf? | Daft Punk | Air ; Justice ; Kraftwerk | Ihr Hit „Get Lucky“ erschien 2013. ; Sie trennten sich 2021. ; Der Name enthält „Punk“. | Thomas Bangalter und Guy-Manuel de Homem-Christo zeigten sich fast nie ohne Helm.
C M | Aus welcher Stadt stammt der Rapper Eminem? | Detroit | Chicago ; New York ; Los Angeles | Die Stadt ist als „Motor City“ bekannt. ; Sein Film „8 Mile“ ist nach einer Straße dort benannt. ; Sie liegt in Michigan. | Die „8 Mile Road“ trennt Detroit von den nördlichen Vororten.
C H | Welche Band hat eine herausgestreckte Zunge als Logo? | The Rolling Stones | The Who ; Kiss ; Red Hot Chili Peppers | Das Logo entstand 1970. ; Es erinnert an Mick Jaggers Lippen. ; Die Band wurde 1962 gegründet. | Das „Hot Lips“-Logo entwarf der Student John Pasche für rund 50 Pfund.
C H | Welches Album von Adele erschien 2015 und enthielt den Hit „Hello“? | 25 | 21 ; 19 ; 30 | Ihre Alben sind nach ihrem Alter benannt. ; Es ist eine Zahl zwischen 21 und 30. ; Ein Vierteljahrhundert. | Adeles Alben heißen „19“, „21“, „25“ und „30“.
W M | Die Band Queen wurde in Liverpool gegründet. | falsch | Queen wurde 1970 in London gegründet — Liverpool ist die Heimat der Beatles.
W H | Elton John sang „Candle in the Wind 1997“ zu Ehren von Prinzessin Diana. | wahr | Die Neuaufnahme wurde zu einer der meistverkauften Singles aller Zeiten.
S M | In welchem Jahr veröffentlichte Michael Jackson das Album „Thriller“? | 1982 | Jahr | 2 | 1960 | 2010 | Anfang der 1980er. ; Drei Jahre nach „Off the Wall“. ; Das Jahr endet auf 2. | „Thriller“ erschien am 30. November 1982.
O M | Sortiere diese Bands nach ihrem Gründungsjahr — die älteste zuerst. | The Beatles = 1960 ; Queen = 1970 ; U2 = 1976 ; Coldplay = 1996 | Die Liverpooler kamen zuerst. ; Freddie Mercurys Band folgte ein Jahrzehnt später. ; Die jüngste Band stammt aus London der 90er. | U2 wurde 1976 in Dublin gegründet.
M M | Welche ZWEI dieser Künstler stammen aus Kanada? | Justin Bieber ; Céline Dion | Rihanna ; Shakira ; Ed Sheeran ; Adele | Einer wurde über YouTube entdeckt. ; Die andere sang den Titanic-Song. ; Barbados, Kolumbien und England scheiden aus. | Auch Drake, The Weeknd und Shania Twain stammen aus Kanada.

@ rock_metal
C E | Wie viele Saiten hat ein E-Bass normalerweise? | 4 | 6 ; 5 ; 8 | Weniger als eine Gitarre. ; Es gibt auch Varianten mit fünf. ; Eine gerade Zahl. | Die vier Saiten sind wie beim Kontrabass auf E-A-D-G gestimmt.
C E | Welches Instrument spielte Ringo Starr bei den Beatles? | Schlagzeug | Bass ; Gitarre ; Klavier | Er saß hinten. ; Er spielte mit Sticks. ; Er sang aber auch „Yellow Submarine“. | Ringo Starr ersetzte 1962 den ersten Beatles-Schlagzeuger Pete Best.
C H | Wie heißt die legendäre US-Band um Frontmann Anthony Kiedis? | Red Hot Chili Peppers | Pearl Jam ; Foo Fighters ; Linkin Park | Ihr Bassist heißt Flea. ; Sie stammt aus Los Angeles. ; Der Name enthält ein scharfes Gewürz. | Die Band wurde 1983 gegründet.
W E | Die Band Metallica stammt aus Schweden. | falsch | Metallica wurde 1981 in Los Angeles gegründet.
S E | Wie viele Saiten hat eine zwölfsaitige Gitarre? | 12 | Saiten | 10 | 4 | 30 | Der Name verrät es. ; Doppelt so viele wie normal. ; Ein Dutzend. | Die Saiten sind paarweise angeordnet, teils in Oktaven gestimmt.
O M | Sortiere diese Rock-Legenden nach ihrem Geburtsjahr — die früheste zuerst. | Elvis Presley = 1935 ; Mick Jagger = 1943 ; Freddie Mercury = 1946 ; Kurt Cobain = 1967 | Der „King“ ist der älteste. ; Der Stones-Sänger kam vor dem Queen-Sänger zur Welt. ; Der Grunge-Star ist der jüngste. | Kurt Cobain starb 1994 mit nur 27 Jahren.

@ charts_onehit_esc
C E | Wie heißt der Musikwettbewerb, bei dem vor allem europäische Länder gegeneinander antreten und sich Punkte geben? | Eurovision Song Contest | Grammy Awards ; MTV Music Awards ; Echo | Er findet jedes Jahr im Mai statt. ; Früher hieß er „Grand Prix Eurovision de la Chanson“. ; Die Abkürzung ist ESC. | Der Gewinner richtet traditionell den Wettbewerb im Folgejahr aus.
C E | Wie viele Punkte gibt ein Land beim ESC maximal an einen einzelnen Song (pro Wertung)? | 12 | 10 ; 15 ; 20 | Auf Französisch „douze“. ; Mehr als zehn. ; Ein Dutzend. | Seit 2016 vergeben Jury und Publikum getrennt je bis zu 12 Punkte.
W M | Beim ESC darf ein Song höchstens drei Minuten lang sein. | wahr | Die Drei-Minuten-Regel gilt seit Jahrzehnten — längere Songs müssen gekürzt werden.
S U | Wie viele Personen dürfen beim ESC höchstens gleichzeitig auf der Bühne stehen? | 6 | Personen | 20 | 1 | 20 | Eine Band mit Tänzern hat es schwer. ; Mehr als fünf. ; Ein halbes Dutzend. | Die Sechs-Personen-Regel gilt für Sänger, Musiker und Tänzer zusammen.

@ schlager_volksmusik de
C E | Welchen Tanz macht man auf Schlagerpartys, wenn alle einander an den Schultern fassen und durch den Raum ziehen? | Polonaise | Walzer ; Cha-Cha-Cha ; Tango | Sie stammt ursprünglich aus Polen. ; „Polonäse Blankenese“ ist ein Partyhit. ; Man läuft hintereinander in einer Schlange. | Die Polonaise war ursprünglich ein feierlicher polnischer Schreittanz.
W M | Das Wort „Schlager“ kam im 19. Jahrhundert in Wien für besonders erfolgreiche Musikstücke auf. | wahr | Der Begriff meinte einen „einschlagenden“ Erfolg — etwa bei Walzern von Johann Strauss.
S M | Wie viele Minuten dauert ein typischer Schlager ungefähr? | 3.5 | Minuten | 20 | 1 | 15 | Radiotauglich kurz. ; Mehr als drei. ; Weniger als fünf. | Die meisten Schlager und Popsongs dauern drei bis vier Minuten — ideal fürs Radio.

@ deutschrap_hiphop de
C M | Welcher Rapper landete 2012 mit „Easy“ seinen Durchbruch und tritt stets mit Pandamaske auf? | Cro | Sido ; Casper ; Marteria | Er stammt aus der Nähe von Stuttgart. ; Er nennt seinen Stil „Raop“ — Rap plus Pop. ; Sein Name hat drei Buchstaben. | Cro zeigt sich öffentlich fast nie ohne seine Pandamaske.
C H | Welcher deutsche Rapper trug in seinen frühen Jahren eine silberne Totenkopfmaske? | Sido | Bushido ; Kool Savas ; Cro | Sein Hit hieß „Mein Block“. ; Er stammt aus dem Märkischen Viertel in Berlin. ; Er war beim Label Aggro Berlin. | Später zeigte Sido sein Gesicht — die Maske blieb sein Markenzeichen.
W H | Der Rapper Casper verbrachte einen Teil seiner Kindheit in den USA. | wahr | Benjamin Griffey alias Casper lebte als Kind mehrere Jahre in den USA, bevor die Familie nach Ostwestfalen zog.
@ klassik_filmmusik
O E | Sortiere diese Töne in der Reihenfolge der C-Dur-Tonleiter. | C = 1. Ton ; D = 2. Ton ; E = 3. Ton ; F = 4. Ton | Die Tonleiter beginnt mit C. ; Dann geht es alphabetisch weiter. ; F kommt nach E. | Die C-Dur-Tonleiter besteht nur aus den weißen Tasten des Klaviers.
M E | Welche ZWEI dieser Instrumente sind Blasinstrumente? | Trompete ; Querflöte | Geige ; Gitarre ; Schlagzeug ; Harfe | Man bläst hinein. ; Eines ist aus Blech. ; Saiten- und Schlaginstrumente scheiden aus. | Die Querflöte zählt trotz Metall zu den Holzblasinstrumenten.
M H | Welche ZWEI dieser Komponisten stammen aus Österreich? | Wolfgang Amadeus Mozart ; Joseph Haydn | Johann Sebastian Bach ; Ludwig van Beethoven ; Frédéric Chopin ; Antonio Vivaldi | Einer wurde in Salzburg geboren. ; Der andere gilt als „Vater der Sinfonie“. ; Beethoven stammte aus Bonn. | Beethoven lebte zwar in Wien, wurde aber in Bonn geboren.
C E | Welches Instrument spielt man mit einem Bogen? | Geige | Trompete ; Klavier ; Trommel | Man hält es unter dem Kinn. ; Es hat vier Saiten. ; Man nennt es auch Violine. | Der Bogen ist mit Rosshaar bespannt.
C U | Welche Molltonart kommt wie C-Dur ganz ohne Vorzeichen aus? | a-Moll | e-Moll ; d-Moll ; c-Moll | Sie ist die Paralleltonart von C-Dur. ; Ihr Grundton liegt eine kleine Terz unter C. ; Sie beginnt mit dem ersten Buchstaben des Alphabets. | Jede Durtonart hat eine parallele Molltonart mit denselben Vorzeichen.
C U | Wie lautet die Tempobezeichnung für „sehr schnell“? | Presto | Adagio ; Andante ; Largo | Schneller als Allegro. ; Das Wort bedeutet auf Italienisch „schnell, bald“. ; Zauberer sagen es gern. | Noch schneller ist „Prestissimo“.
S H | Wie viele Saiten hat eine klassische Ukulele? | 4 | Saiten | 25 | 1 | 12 | Weniger als eine Gitarre. ; Genauso viele wie eine Geige. ; Eine gerade Zahl. | Die Ukulele stammt ursprünglich von einem portugiesischen Instrument und wurde auf Hawaii populär.

@ pop_international
M U | Welche ZWEI dieser Bands stammen aus Irland? | U2 ; The Cranberries | Oasis ; Coldplay ; ABBA ; Queen | Beide kommen von der Grünen Insel. ; Eine wurde in Dublin gegründet. ; Die andere in Limerick. | Die Cranberries landeten 1994 mit „Zombie“ einen Welthit.
"""
