"""Extra questions: Sport (format: see tools/content/merge_extra.py)."""
KAT = "sport"
REGION = "global"
DATA = r"""
@ fussball_international
C E | Welches Land wurde 2010 in Südafrika zum ersten Mal Fußball-Weltmeister? | Spanien | Niederlande ; Deutschland ; Brasilien | Das Finale endete 1:0 nach Verlängerung. ; Andrés Iniesta schoss das Siegtor. ; Das Team spielte „Tiki-Taka“. | Spanien besiegte im Finale von Johannesburg die Niederlande.
C E | Wofür steht die Abkürzung des Weltfußballverbands FIFA? | Fédération Internationale de Football Association | Football International Federation of America ; Federazione Italiana di Football Amatoriale ; Fußball-Internationale Freundschafts-Allianz | Der Name ist französisch. ; Der Verband wurde 1904 in Paris gegründet. ; Heute sitzt er in Zürich. | Die FIFA richtet die Fußball-Weltmeisterschaften aus.
C E | Welches Land gewann die EM 2021 (EURO 2020) im Elfmeterschießen gegen England? | Italien | Spanien ; Dänemark ; Belgien | Das Finale fand im Londoner Wembley-Stadion statt. ; Torhüter Donnarumma wurde bester Spieler des Turniers. ; Trainer war Roberto Mancini. | Das Turnier wurde wegen der Pandemie um ein Jahr verschoben, behielt aber den Namen EURO 2020.
C E | Wie heißt die Strafe, bei der ein Spieler aus elf Metern allein auf das Tor schießt? | Elfmeter | Freistoß ; Eckstoß ; Einwurf | Der Punkt liegt im Strafraum. ; Nur der Torwart darf abwehren. ; Die Zahl steckt im Namen. | Offiziell heißt der Elfmeter „Strafstoß“ — der Punkt liegt 11 Meter (12 Yards) vor dem Tor.
C E | Welche Farbe hat die Karte, mit der ein Spieler sofort vom Platz gestellt wird? | Rot | Gelb ; Blau ; Grün | Gelb ist nur eine Verwarnung. ; Die Farbe von Feuer und Stoppschildern. ; Zweimal Gelb ergibt sie auch. | Die Karten wurden 1970 zur WM in Mexiko eingeführt.
C M | Wie heißt der akrobatische Schuss, bei dem ein Spieler den Ball rückwärts über den eigenen Kopf ins Tor befördert? | Fallrückzieher | Seitfallzieher ; Volleyschuss ; Heber | Man liegt dabei fast waagerecht in der Luft. ; Klaus Fischer war berühmt dafür. ; Im Englischen heißt er „bicycle kick“. | Klaus Fischers Fallrückzieher gegen die Schweiz 1977 wurde zum „Tor des Jahrhunderts“ gewählt.
C M | Ab welchem Jahr wurden im Profifußball erstmals Gelbe und Rote Karten verwendet? | 1970 | 1954 ; 1982 ; 1990 | Es war bei einer WM in Mexiko. ; Pelé wurde damals zum dritten Mal Weltmeister. ; Erfinder war der englische Schiedsrichter Ken Aston. | Ken Aston kam die Idee angeblich an einer Ampel.
C M | In welchem Land fand die erste Fußball-Weltmeisterschaft 1930 statt? | Uruguay | Brasilien ; Italien ; Argentinien | Der Gastgeber wurde auch Weltmeister. ; Das Land feierte 100 Jahre Unabhängigkeit. ; Die Hauptstadt ist Montevideo. | Uruguay besiegte im Finale Argentinien mit 4:2.
C U | Welcher Spieler erzielte die meisten Tore bei einer einzigen WM — 13 Treffer im Jahr 1958? | Just Fontaine | Gerd Müller ; Pelé ; Miroslav Klose | Er spielte für Frankreich. ; Er wurde in Marokko geboren. ; Sein Nachname bedeutet „Brunnen“. | Just Fontaines 13 WM-Tore in einem Turnier sind bis heute Rekord.
C H | Wer wurde bei der WM 2014 als bester Spieler des Turniers ausgezeichnet? | Lionel Messi | Thomas Müller ; James Rodríguez ; Arjen Robben | Er verlor das Finale. ; Er war Kapitän Argentiniens. ; Er spielte damals beim FC Barcelona. | Der Goldene Ball ging trotz der Finalniederlage an Messi — eine umstrittene Wahl.
C U | Welches Land nahm als einziges an allen Fußball-Weltmeisterschaften der Männer teil? | Brasilien | Deutschland ; Italien ; Argentinien | Es ist Rekordweltmeister. ; Es trägt gelbe Trikots. ; Pelé stammt von dort. | Brasilien ist mit fünf Titeln Rekordweltmeister und war bei jeder WM dabei.
W M | Beim Fußball darf der Torwart den Ball nach einem absichtlichen Rückpass mit dem Fuß in die Hand nehmen. | falsch | Seit 1992 ist das verboten — die Rückpassregel sollte Zeitspiel verhindern.
W H | Bei der ersten WM 1930 nahm die deutsche Nationalmannschaft nicht teil. | wahr | Nur vier europäische Teams machten die weite Schiffsreise nach Uruguay — Deutschland war nicht dabei.
S M | Wie viele Meter ist der Elfmeterpunkt vom Tor entfernt? | 11 | Meter | 10 | 5 | 30 | Der Name verrät es. ; Genauer sind es zwölf Yards. ; Eine Schnapszahl. | Zwölf Yards entsprechen 10,97 Metern — man spricht von elf Metern.
S H | Wie viele Mannschaften nehmen ab der WM 2026 an der Endrunde teil? | 48 | Teams | 10 | 8 | 100 | Vorher waren es 32. ; Die Zahl wurde um die Hälfte erhöht. ; Mehr als 40. | Die WM 2026 findet in den USA, Kanada und Mexiko statt.
O M | Sortiere diese WM-Gastgeber chronologisch — den frühesten zuerst. | Uruguay = 1930 ; England = 1966 ; USA = 1994 ; Katar = 2022 | Die erste WM fand in Südamerika statt. ; Das Mutterland des Fußballs folgte später. ; Die Wüsten-WM war die jüngste. | Die WM 2022 in Katar fand erstmals im November und Dezember statt.

@ dfb_nationalelf de
C M | In welcher Stadt hat der Deutsche Fußball-Bund seinen Sitz? | Frankfurt am Main | München ; Köln ; Berlin | Dort steht auch der DFB-Campus. ; Die Stadt liegt am Main. ; Sie ist ein wichtiger Bankenstandort. | Der DFB wurde 1900 in Leipzig gegründet und sitzt heute in Frankfurt am Main.
C H | Gegen welches Land verlor Deutschland das EM-Finale 2008 in Wien? | Spanien | Italien ; Russland ; Türkei | Fernando Torres schoss das einzige Tor. ; Es war der Beginn einer goldenen Ära dieser Nation. ; 2010 wurde sie Weltmeister. | Spanien gewann 2008, 2010 und 2012 drei große Turniere in Folge.
C H | Wie heißt das Adler-Maskottchen der deutschen Nationalmannschaft? | Paule | Goleo ; Adlerich ; Fritz | Er wurde 2006 vorgestellt. ; Das Löwen-Maskottchen der Heim-WM hieß anders. ; Sein Name hat fünf Buchstaben. | Goleo war das Löwen-Maskottchen der WM 2006 — Paule ist das Maskottchen des DFB-Teams.
C H | In welcher Stadt gewann Deutschland 1972 das EM-Finale mit 3:0 gegen die Sowjetunion? | Brüssel | Amsterdam ; Rom ; Paris | Das Stadion hieß Heysel. ; Die Stadt ist Sitz der EU-Kommission. ; Gerd Müller traf doppelt. | Die Elf um Beckenbauer, Netzer und Müller gilt als eine der spielstärksten deutschen Mannschaften.
C H | Wer war Bundestrainer beim WM-Titel 1990 in Italien? | Franz Beckenbauer | Jupp Derwall ; Berti Vogts ; Helmut Schön | Er war bereits 1974 als Kapitän Weltmeister. ; Man nannte ihn „den Kaiser“. ; Offiziell hieß er „Teamchef“. | Beckenbauer spazierte nach dem Finale in Rom einsam über den Rasen — ein berühmtes Bild.
S M | Wie viele EM-Titel hat die deutsche Männer-Nationalmannschaft gewonnen? | 3 | Titel | 20 | 0 | 10 | 1972 war der erste. ; 1996 der bislang letzte. ; Weniger als Spanien. | Deutschland wurde 1972, 1980 und 1996 Europameister.

@ olympia_wintersport
C E | Welche Farben haben die fünf olympischen Ringe? | Blau, Gelb, Schwarz, Grün, Rot | Rot, Orange, Gelb, Grün, Blau ; Gold, Silber, Bronze, Weiß, Schwarz ; Blau, Weiß, Rot, Gelb, Lila | Zusammen mit dem weißen Hintergrund findet sich jede Nationalflagge darin wieder. ; Oben links beginnt es mit Blau. ; Schwarz ist in der Mitte. | Pierre de Coubertin entwarf die Ringe 1913.
C E | In welcher Stadt fanden die Olympischen Sommerspiele 2024 statt? | Paris | London ; Los Angeles ; Rom | Die Eröffnungsfeier fand auf einem Fluss statt. ; Der Eiffelturm war Kulisse für Beachvolleyball. ; Die Stadt richtete die Spiele schon 1900 und 1924 aus. | Paris war nach London der zweite Ort mit drei Sommerspielen.
C E | Aus welchem Material besteht ein Eishockey-Puck? | Hartgummi | Holz ; Kunststoff mit Metallkern ; Leder | Er wird vor dem Spiel gekühlt, damit er weniger springt. ; Er ist schwarz. ; Das Material kennt man auch von Autoreifen. | Ein Puck wiegt rund 160 Gramm und ist 2,54 Zentimeter dick.
C E | Wie heißt der Sportwettbewerb für Athletinnen und Athleten mit Behinderung, der nach den Olympischen Spielen stattfindet? | Paralympics | Special Olympics ; Invictus Games ; Deaflympics | Das Wort verbindet „parallel“ und „Olympics“. ; Sie finden am selben Ort statt. ; Ihr Symbol sind drei „Agitos“. | Die ersten Paralympics fanden 1960 in Rom statt.
C M | Seit welchen Winterspielen ist Snowboard olympisch? | Nagano 1998 | Lillehammer 1994 ; Albertville 1992 ; Salt Lake City 2002 | Die Spiele fanden in Japan statt. ; Ende der 1990er. ; Es gab Halfpipe und Riesenslalom. | Der Kanadier Ross Rebagliati gewann 1998 das erste olympische Snowboard-Gold.
C M | Wie heißt die Figur im Eiskunstlauf, bei der man sich auf der Stelle schnell um die eigene Achse dreht? | Pirouette | Axel ; Rittberger ; Salchow | Der Name kommt aus dem Ballett. ; Man springt dabei nicht. ; Die Arme werden zum Beschleunigen angezogen. | Axel, Rittberger und Salchow sind Sprünge — die Pirouette ist eine Drehung.
C E | Wie viele Personen sitzen beim großen olympischen Bob? | 4 | 2 ; 3 ; 5 | Es gibt auch den Zweierbob. ; Der vorderste lenkt. ; Der hinterste bremst. | Im Viererbob sitzen Pilot, zwei Anschieber und ein Bremser.
C M | Wie oft fanden in Deutschland bisher Olympische Sommerspiele statt? | Zweimal | Einmal ; Dreimal ; Noch nie | Einmal in den 1930ern, einmal in den 1970ern. ; Eine Stadt ist Berlin. ; Die andere München. | Berlin 1936 und München 1972 waren die bisher einzigen Sommerspiele in Deutschland.
C U | In welcher Stadt fanden die ersten Olympischen Sommerspiele der Neuzeit außerhalb Europas statt? | St. Louis | Los Angeles ; Melbourne ; Tokio | Es war im Jahr 1904. ; Die Stadt liegt am Mississippi. ; Gleichzeitig fand dort eine Weltausstellung statt. | Die Spiele von St. Louis 1904 waren fast nur von US-Athleten besetzt.
C H | Welche Stadt richtete 1964 als erste in Asien Olympische Sommerspiele aus? | Tokio | Seoul ; Peking ; Sapporo | Kurz davor startete dort der erste Hochgeschwindigkeitszug. ; Die Stadt ist Hauptstadt Japans. ; 2021 war sie erneut Gastgeber. | Die Spiele 1964 wurden als Symbol für Japans Wiederaufstieg gefeiert.
C U | Wie heißen die drei geschwungenen Symbole im Logo der Paralympics? | Agitos | Ringe ; Flammen ; Pinsel | Das Wort ist lateinisch und bedeutet „ich bewege mich“. ; Sie sind rot, blau und grün. ; Es sind drei. | Die Farben Rot, Blau und Grün sind die häufigsten Farben in Nationalflaggen.
W E | Bei Olympischen Spielen erhält der Drittplatzierte eine Silbermedaille. | falsch | Der Dritte bekommt Bronze, der Zweite Silber — diese Abstufung gibt es seit 1904.
W M | Curling wird mit Steinen aus Granit gespielt. | wahr | Die berühmtesten Curlingsteine stammen aus Granit der schottischen Insel Ailsa Craig.
S H | Wie viele Gramm wiegt ein Eishockey-Puck ungefähr? | 165 | Gramm | 20 | 20 | 1000 | Etwas mehr als eine Tafel Schokolade. ; Mehr als 150. ; Weniger als 200. | Ein regulärer Puck wiegt 156 bis 170 Gramm.
O M | Sortiere diese Olympia-Gastgeber chronologisch — den frühesten zuerst. | Athen = 1896 ; Berlin = 1936 ; München = 1972 ; Paris = 2024 | Die erste Neuzeit-Olympiade fand in Griechenland statt. ; Deutschland war zweimal Gastgeber. ; Die jüngste fand an der Seine statt. | Athen war 1896 und 2004 Gastgeber der Sommerspiele.

@ us_sport
C E | Wie viele Spieler einer Mannschaft stehen beim American Football gleichzeitig auf dem Feld? | 11 | 9 ; 12 ; 15 | Genauso viele wie beim Fußball. ; Es gibt Offense- und Defense-Teams. ; Eine Schnapszahl. | Je nach Spielsituation wechseln Offense, Defense und Special Teams komplett aus.
C M | Wie viele Innings hat ein reguläres Baseballspiel? | 9 | 7 ; 10 ; 12 | Bei Gleichstand geht es in Extra-Innings. ; Die Zahl ist ungerade. ; Drei mal drei. | In jedem Inning hat jedes Team einen Angriff mit drei Outs.
C M | Wie viele Punkte zählt im Basketball ein normaler Treffer aus dem Spiel innerhalb der Dreierlinie? | 2 | 1 ; 3 ; 4 | Freiwürfe zählen weniger. ; Würfe von weit außen zählen mehr. ; Eine gerade Zahl. | Freiwürfe bringen einen Punkt, Würfe jenseits der Dreierlinie drei.
S U | Wie viele Meter breit ist ein Basketballfeld nach FIBA-Regeln? | 15 | Meter | 15 | 5 | 50 | Es ist 28 Meter lang. ; Etwa halb so breit wie lang. ; Mehr als zehn. | Ein FIBA-Feld misst 28 mal 15 Meter.
O M | Sortiere diese Mannschaftssportarten nach der Zahl der Feldspieler pro Team — die kleinste zuerst. | Basketball = 5 ; Eishockey = 6 ; Handball = 7 ; Fußball = 11 | Beim Korbball sind es am wenigsten. ; Auf dem Eis steht einer mehr. ; Handball liegt vor Fußball. | Die Torhüter sind bei Eishockey, Handball und Fußball jeweils mitgezählt.

@ motorsport_formel1
C E | Welche Farbe haben die Formel-1-Autos von Ferrari traditionell? | Rot | Silber ; Blau ; Grün | Man nennt sie „Rosso Corsa“. ; Die Fans heißen „Tifosi“. ; Es ist die italienische Rennfarbe. | Die Nationalfarben im Motorsport: Italien Rot, Deutschland Silber, Großbritannien Grün, Frankreich Blau.
C M | Wie viele WM-Titel gewann Lewis Hamilton bis einschließlich 2020? | 7 | 6 ; 5 ; 8 | Genauso viele wie Michael Schumacher. ; Sechs davon mit Mercedes. ; Eine Primzahl. | Hamilton holte seinen ersten Titel 2008 mit McLaren und sechs weitere mit Mercedes.
C H | Wie nennt man in der Formel 1 die Startposition ganz vorne? | Pole-Position | Poleplatz ; Front Row One ; Grid Leader | Man erreicht sie durch die schnellste Qualifying-Runde. ; Der Name stammt aus dem Pferderennsport. ; Dort stand ein Pfahl an der Innenseite. | Früher begann beim Pferderennen der Innenplatz am Pfosten („pole“).
W H | Ein Formel-1-Rennen ist in der Regel auf eine Distanz von rund 305 Kilometern ausgelegt. | wahr | Nur Monaco ist mit rund 260 Kilometern deutlich kürzer.
S H | Wie viele Runden fährt man beim Großen Preis von Monaco ungefähr? | 78 | Runden | 10 | 20 | 200 | Die Strecke ist sehr kurz. ; Mehr als 70. ; Weniger als 80. | Der Stadtkurs ist nur 3,3 Kilometer lang — daher die vielen Runden.

@ sport_rekorde_kurioses
C E | In welcher Sportart gibt es einen „Strike“ und einen „Spare“? | Bowling | Golf ; Darts ; Billard | Man rollt eine Kugel. ; Zehn Pins stehen am Ende der Bahn. ; Ein perfektes Spiel hat 300 Punkte. | Ein „Spare“ bedeutet: alle Pins mit zwei Würfen abgeräumt.
C E | Welche Sportart spielt man mit Schläger und Federball? | Badminton | Squash ; Tischtennis ; Tennis | Man spielt über ein hohes Netz. ; Der Ball hat Federn. ; Sie ist nach einem englischen Landsitz benannt. | Badminton ist nach Badminton House in England benannt.
C E | Wie viele Disziplinen umfasst der Zehnkampf? | 10 | 7 ; 8 ; 12 | Der Name verrät es. ; Er dauert zwei Tage. ; Frauen bestreiten meist den Siebenkampf. | Der Zehnkampf endet traditionell mit dem 1500-Meter-Lauf.
C M | Welche Sportart erfand James Naismith 1891? | Basketball | Volleyball ; Handball ; Baseball | Er war Sportlehrer in Massachusetts. ; Die ersten Körbe waren Pfirsichkörbe. ; Man wirft einen Ball durch einen Ring. | Die ersten Körbe hatten noch einen Boden — der Ball musste herausgeholt werden.
C U | Wie lang ist ein Tischtennistisch? | 2,74 Meter | 2,00 Meter ; 3,20 Meter ; 2,50 Meter | Er ist 1,525 Meter breit. ; Das Netz ist 15,25 cm hoch. ; Die Länge entspricht neun Fuß. | Die ungeraden Maße stammen aus dem britischen Fuß-System.
C U | In welcher Sportart gibt es einen „Albatross“, der noch besser ist als ein „Eagle“? | Golf | Cricket ; Polo ; Squash | Er bedeutet drei Schläge unter Par. ; Ein „Birdie“ ist einer unter Par. ; Die Begriffe sind Vogelnamen. | Ein „Albatross“ ist seltener als ein Hole-in-One.
W M | Beim Badminton darf der Federball den Boden berühren, bevor man ihn zurückschlägt. | falsch | Berührt der Federball im Feld den Boden, gibt es einen Punkt für die Gegenseite.
S M | Wie viele Punkte hat ein perfektes Bowlingspiel? | 300 | Punkte | 10 | 50 | 1000 | Zwölf Strikes in Folge. ; Mehr als 200. ; Eine runde Hunderterzahl. | Für 300 Punkte braucht man zwölf Strikes in Folge.
S U | Wie viele Zentimeter hoch ist ein Tischtennisnetz? | 15.25 | cm | 20 | 5 | 50 | Etwa eine Handspanne. ; Mehr als 15. ; Weniger als 16. | Das Netz ist genau 15,25 Zentimeter hoch — ein halber Fuß.
O H | Sortiere diese Sportarten nach ihrer ersten Aufnahme ins olympische Programm — die früheste zuerst. | Fußball = 1900 ; Basketball = 1936 ; Beachvolleyball = 1996 ; Skateboard = 2020 (Tokio) | Der Klassiker war schon um 1900 dabei. ; Korbball kam in Berlin dazu. ; Das Brett mit Rollen ist die jüngste. | Die Spiele von Tokio 2020 fanden wegen der Pandemie erst 2021 statt.
M M | Welche ZWEI dieser Sportarten sind Rückschlagspiele mit Netz? | Badminton ; Tischtennis | Handball ; Wasserball ; Rugby ; Eishockey | Man schlägt ein Spielgerät hin und her. ; Eine wird an einer Platte gespielt. ; Die andere mit Federn. | Auch Tennis, Squash und Volleyball zählen zu den Rückschlagspielen.

@ bundesliga de
C E | Welcher Verein ist deutscher Rekordmeister? | FC Bayern München | Borussia Dortmund ; 1. FC Nürnberg ; Hamburger SV | Der Verein spielt in der Allianz Arena. ; Die Vereinsfarben sind Rot und Weiß. ; Er gewann ab 2013 elf Meisterschaften in Folge. | Der FC Bayern gewann seine erste Meisterschaft 1932.
S H | Seit welcher Saison gibt es in der Bundesliga drei Punkte für einen Sieg? | 1995 | Jahr | 2 | 1963 | 2020 | Mitte der 1990er. ; Zuvor gab es zwei Punkte. ; Nach der WM 1994 zog die Liga nach. | Die Drei-Punkte-Regel gilt in der Bundesliga seit der Saison 1995/96.
@ sport_rekorde_kurioses
O E | Sortiere diese Laufstrecken nach ihrer Länge — die kürzeste zuerst. | 100 Meter = Sprint ; 400 Meter = Stadionrunde ; 1500 Meter = Mittelstrecke ; Marathon = 42,195 km | Der Sprint ist am kürzesten. ; Eine Runde im Stadion folgt. ; Der Marathon ist mit Abstand am längsten. | Der Marathon ist gut hundertmal so lang wie eine Stadionrunde.
M E | Welche ZWEI dieser Sportarten spielt man mit einem Schläger? | Golf ; Eishockey | Fußball ; Basketball ; Handball ; Volleyball | Bei einer schlägt man einen kleinen weißen Ball. ; Bei der anderen einen Puck. ; Ballsportarten mit Hand oder Fuß scheiden aus. | Im Eishockey heißt der Schläger „Stock“.
M H | Welche ZWEI dieser Länder waren schon einmal Fußball-Weltmeister der Männer? | Uruguay ; England | Niederlande ; Portugal ; Belgien ; Mexiko | Eines gewann die erste WM. ; Das andere siegte 1966 im eigenen Land. ; Die Niederlande verloren drei Finals. | Nur acht Nationen wurden bisher Weltmeister.
M U | Welche ZWEI dieser Disziplinen gehören zum Siebenkampf der Frauen? | 100 Meter Hürden ; Speerwurf | Stabhochsprung ; Diskuswurf ; 400 Meter ; Hammerwurf | Eine ist ein Hürdenlauf. ; Die andere ein Wurf mit langem Gerät. ; Stabhochsprung, Diskus und 400 Meter gehören zum Zehnkampf der Männer. | Siebenkampf: 100 m Hürden, Hochsprung, Kugel, 200 m, Weitsprung, Speer, 800 m.
C E | In welcher Sportart wurde Usain Bolt weltberühmt? | Sprint (Leichtathletik) | Schwimmen ; Radsport ; Fußball | Er stammt aus Jamaika. ; Seine Siegerpose ist ein Blitz. ; Er lief 100 Meter in 9,58 Sekunden. | Bolt gewann acht olympische Goldmedaillen.
C U | Welches Land gewann 1987 die erste Rugby-Weltmeisterschaft? | Neuseeland | Australien ; England ; Südafrika | Die Mannschaft heißt „All Blacks“. ; Sie tanzt vor dem Spiel den Haka. ; Das Land liegt im Pazifik. | Neuseeland war 1987 gemeinsam mit Australien Gastgeber.
C U | In welcher Sportart wird der Ryder Cup zwischen Europa und den USA ausgetragen? | Golf | Tennis ; Segeln ; Leichtathletik | Er findet alle zwei Jahre statt. ; Gespielt wird auf Grün. ; Es gibt Birdies und Bogeys. | Der Ryder Cup wurde 1927 zum ersten Mal ausgetragen.
S U | Wie viele Meter lang ist der kurze Hürdensprint der Männer? | 110 | Meter | 5 | 50 | 500 | Die Frauen laufen 100 Meter. ; Etwas mehr als 100. ; Es gibt zehn Hürden. | Die Männerhürden sind 1,067 Meter hoch.
"""
