"""Extra questions: Technik & Autos (format: see tools/content/merge_extra.py)."""
KAT = "technik_autos"
REGION = "global"
DATA = r"""
@ ki_zukunftstechnik
C E | Wofür steht die Abkürzung „KI“? | Künstliche Intelligenz | Komplexe Informatik ; Kybernetische Integration ; Kontrollierte Interaktion | Es geht um denkende Maschinen. ; Das erste Wort beschreibt etwas, das nicht natürlich ist. ; Auf Englisch heißt es „Artificial Intelligence“. | KI steht für Künstliche Intelligenz — auf Englisch AI, Artificial Intelligence.
C E | Welches Unternehmen veröffentlichte im November 2022 den Chatbot ChatGPT? | OpenAI | Google ; Meta ; Apple | Die Firma sitzt in San Francisco. ; Ihr Name enthält das Wort „offen“. ; Sam Altman ist ihr bekanntester Chef. | ChatGPT von OpenAI erreichte in nur zwei Monaten rund 100 Millionen Nutzer.
C M | Welches Unternehmen entwickelte den Sprachassistenten Cortana? | Microsoft | Apple ; Samsung ; Amazon | Benannt ist er nach einer KI-Figur aus der Spielreihe „Halo“. ; Er war in Windows 10 eingebaut. ; Die Firma wurde von Bill Gates mitgegründet. | Cortana erschien 2014 und wurde nach der KI-Begleiterin aus Microsofts „Halo“-Spielen benannt.
C E | Wie nennt man einen Computer-Chatpartner, der automatisch auf Nachrichten antwortet? | Chatbot | Chatroom ; Hashtag ; Avatar | Das Wort setzt sich aus „plaudern“ und einer Kurzform für Roboter zusammen. ; ChatGPT ist ein bekanntes Beispiel. ; Er beginnt mit „Chat“. | Chatbots antworten automatisch — von einfachen Regelwerken bis zu modernen Sprachmodellen.
C M | Welcher britische Mathematiker schlug 1950 einen Test vor, ob eine Maschine denken kann? | Alan Turing | Charles Babbage ; John von Neumann ; Claude Shannon | Er knackte im Zweiten Weltkrieg deutsche Codes. ; Der Film „The Imitation Game“ erzählt sein Leben. ; Nach ihm ist der wichtigste Informatikpreis benannt. | Beim Turing-Test soll ein Mensch im Chat nicht erkennen können, ob er mit einer Maschine schreibt.
C M | Wie hieß der IBM-Computer, der 2011 in der US-Quizshow „Jeopardy!“ gegen menschliche Champions gewann? | Watson | Deep Blue ; Siri ; HAL | Er ist nach dem IBM-Gründer benannt. ; Denselben Namen trägt Sherlock Holmes' Assistent. ; Er schlug Ken Jennings und Brad Rutter. | Watson verstand Quizfragen in natürlicher Sprache und gewann 2011 deutlich gegen zwei Rekordchampions.
C M | Welches Programm von DeepMind schlug 2016 den Go-Profi Lee Sedol? | AlphaGo | Deep Blue ; Watson ; Stockfish | Der Name enthält das Spiel selbst. ; Davor steht der erste Buchstabe des griechischen Alphabets. ; DeepMind gehört zu Google. | AlphaGo gewann 4:1 gegen Lee Sedol — ein Meilenstein, da Go als viel schwerer als Schach galt.
C M | Wie nennt man KI-Modelle wie GPT, die mit riesigen Textmengen trainiert werden? | Large Language Model | Deep Blue Model ; Quantum Neural Grid ; Expert Rule System | Die Abkürzung lautet LLM. ; Es geht um Sprache. ; Das erste Wort bedeutet „groß“. | Large Language Models sagen Wort für Wort vorher, welcher Text am wahrscheinlichsten folgt.
C H | Wofür steht das „GPT“ in ChatGPT? | Generative Pre-trained Transformer | General Purpose Technology ; Global Processing Tool ; Graphic Prediction Tree | Das letzte Wort ist eine Netzwerk-Architektur. ; Das Modell wurde vorab trainiert. ; Es erzeugt, also generiert, Text. | Die Transformer-Architektur wurde 2017 von Google-Forschern im Paper „Attention Is All You Need“ vorgestellt.
C U | Wie heißt das 2017 erschienene Forschungspapier, das die Transformer-Architektur einführte? | Attention Is All You Need | Deep Learning Rises ; Neural Nets Reloaded ; Language Is Enough | Der Titel spielt auf einen Beatles-Song an. ; Ein Schlüsselbegriff heißt „Aufmerksamkeit“. ; Es stammt von Forschern bei Google. | Der Titel ist eine Anspielung auf „All You Need Is Love“; fast alle modernen Sprachmodelle bauen darauf auf.
C H | Wie hieß der erste Chatbot, den Joseph Weizenbaum in den 1960ern am MIT schrieb? | ELIZA | ALICE ; SIRI ; PARRY | Er spielte einen Psychotherapeuten. ; Benannt nach einer Figur aus „My Fair Lady“. ; Der Name ist ein Frauenname mit fünf Buchstaben. | ELIZA (1966) wiederholte Aussagen als Gegenfragen — viele Nutzer hielten sie trotzdem für verständnisvoll.
C U | Auf einer Konferenz in welchem US-College wurde 1956 der Begriff „Artificial Intelligence“ geprägt? | Dartmouth College | Harvard University ; Stanford University ; Yale University | Es liegt in New Hampshire. ; Es gehört zur Ivy League. ; John McCarthy organisierte den Sommer-Workshop. | Der Dartmouth-Workshop 1956 gilt als Geburtsstunde der KI-Forschung.
C H | Wie heißt der Effekt, wenn eine KI überzeugend klingende, aber erfundene Fakten ausgibt? | Halluzination | Spiegelung ; Rauschen ; Übersteuerung | Der Begriff kommt aus der Medizin. ; Man sieht oder hört dabei Dinge, die nicht da sind. ; Er beginnt mit H. | Sprachmodelle „halluzinieren“, weil sie wahrscheinliche statt geprüfte Wörter aneinanderreihen.
C H | Welcher Science-Fiction-Autor formulierte die drei Robotergesetze? | Isaac Asimov | Arthur C. Clarke ; Philip K. Dick ; Jules Verne | Er schrieb die „Foundation“-Reihe. ; Er wurde in Russland geboren und lebte in New York. ; Sein Buch heißt „Ich, der Robot“. | Asimovs Robotergesetze erschienen erstmals 1942 in der Kurzgeschichte „Runaround“.
C U | Wie hieß der Roboterhund, den Sony 1999 auf den Markt brachte? | AIBO | ASIMO ; Pepper ; Furby | Der Name klingt japanisch nach „Kumpel“. ; Er konnte mit einem Ball spielen. ; Die Abkürzung hat vier Buchstaben. | AIBO steht für „Artificial Intelligence Robot“ und bedeutet auf Japanisch zugleich „Partner“.
C U | Welcher KI-Forscher prägte 1956 den Begriff „Artificial Intelligence“? | John McCarthy | Marvin Minsky ; Alan Turing ; Herbert Simon | Er erfand später die Programmiersprache Lisp. ; Er organisierte den Dartmouth-Workshop. ; Sein Vorname ist John. | John McCarthy schrieb den Antrag für den Dartmouth-Workshop und erfand 1958 Lisp.
C U | Wie heißt der Suchalgorithmus, mit dem viele Schachprogramme Züge vorausberechnen und die schlechtesten Äste abschneiden? | Alpha-Beta-Suche | Dijkstra-Suche ; Monte-Carlo-Filter ; Bubble-Suche | Er baut auf Minimax auf. ; Zwei griechische Buchstaben stecken im Namen. ; Abgeschnittene Äste nennt man „Pruning“. | Alpha-Beta-Pruning spart gegenüber reinem Minimax riesige Mengen an Rechenarbeit ohne Ergebnisverlust.
C E | Wie nennt man ein Auto, das komplett ohne menschlichen Fahrer auskommt? | Autonomes Fahrzeug | Hybridfahrzeug ; Plug-in-Fahrzeug ; Kombi | Man spricht von Level 5. ; Das Wort bedeutet „selbstständig“. ; Waymo testet solche Robotaxis. | Beim autonomen Fahren unterscheidet man die Stufen 0 bis 5 — Level 5 heißt vollständig fahrerlos.
C E | Wie nennt man einen Roboter, der wie ein Mensch aussieht und sich bewegt? | Humanoider Roboter | Drohne ; Cyborg ; Nanobot | Er hat Kopf, Arme und Beine. ; Das Wort kommt vom lateinischen „humanus“. ; Ein bekanntes Beispiel heißt Asimo. | Hondas Asimo gehörte zu den bekanntesten humanoiden Robotern.
C M | Was bezeichnet man als „Deepfake“? | Mit KI gefälschtes Video oder Audio | Einen besonders tiefen Datenspeicher ; Einen Computervirus im Tiefschlaf ; Eine gefälschte Webseite einer Bank | Das Wort verbindet „Deep Learning“ mit einem englischen Wort für Fälschung. ; Gesichter oder Stimmen werden ausgetauscht. ; Es betrifft Bilder und Töne. | Deepfakes setzen täuschend echt Gesichter oder Stimmen in fremde Aufnahmen ein.
C E | Wie heißt die bekannte Roboterfigur aus „Star Wars“, die vor allem durch Pfeifen und Piepen kommuniziert? | R2-D2 | C-3PO ; BB-8 ; K-2SO | Er ist blau-weiß. ; Er hat die Nachricht von Prinzessin Leia gespeichert. ; Sein Name enthält zweimal eine 2. | R2-D2 ist ein Astromechdroide, C-3PO sein goldener, redseliger Begleiter.
C H | Welches Unternehmen entwickelte die KI AlphaFold, die Proteinstrukturen vorhersagt? | DeepMind | OpenAI ; IBM ; Nvidia | Es wurde in London gegründet. ; Es gehört zu Google. ; Auch AlphaGo stammt von dort. | Für AlphaFold erhielten Demis Hassabis und John Jumper 2024 den Chemie-Nobelpreis.
C M | Welcher Chip-Hersteller ist vor allem durch Grafikkarten bekannt, die heute KI-Modelle trainieren? | Nvidia | Intel ; Qualcomm ; Infineon | Die Marke heißt „GeForce“. ; Gründer Jensen Huang trägt meist Lederjacke. ; Der Name klingt nach dem lateinischen „invidia“ (Neid). | Nvidia-GPUs rechnen tausende Operationen parallel — ideal für das Training neuronaler Netze.
W E | Der Begriff „Roboter“ wurde durch einen Hollywood-Film bekannt. | falsch | Karel Čapeks Theaterstück „R.U.R.“ von 1920 brachte das Wort „Roboter“ in die Welt.
W M | Deep Blue besiegte Garri Kasparow bereits in ihrem allerersten Match 1996. | falsch | 1996 gewann Kasparow noch mit 4:2; erst die verbesserte Version besiegte ihn 1997.
W M | ChatGPT wurde zuerst von Google veröffentlicht. | falsch | ChatGPT stammt von OpenAI; Google brachte später eigene Chatbots wie Bard und Gemini.
W H | Die erste Version des Chatbots ELIZA entstand schon in den 1960er-Jahren. | wahr | Joseph Weizenbaum stellte ELIZA 1966 am MIT vor.
W H | Beim Turing-Test muss eine Maschine ein Schachspiel gegen einen Menschen gewinnen. | falsch | Beim Turing-Test geht es um ein Gespräch: Ein Mensch soll nicht erkennen, ob er mit einer Maschine schreibt.
S M | In welchem Jahr besiegte Deep Blue Garri Kasparow in einem Schachmatch? | 1997 | Jahr | 2 | 1970 | 2020 | Kurz vor der Jahrtausendwende. ; Titanic lief im selben Jahr in den Kinos. ; Das Jahr endet auf 7. | Im Mai 1997 gewann Deep Blue in New York mit 3,5 zu 2,5 Punkten.
S U | In welchem Jahr fand der Dartmouth-Workshop statt, der als Geburtsstunde der KI gilt? | 1956 | Jahr | 3 | 1920 | 2000 | Mitte des 20. Jahrhunderts. ; Elvis wurde gerade berühmt. ; Ein Jahr vor dem Sputnik-Start. | 1956 trafen sich in Dartmouth Forscher wie John McCarthy und Marvin Minsky.
O M | Sortiere diese KI-Meilensteine chronologisch — vom frühesten zum spätesten. | Chatbot ELIZA = 1966 ; Deep Blue schlägt Kasparow = 1997 ; AlphaGo schlägt Lee Sedol = 2016 ; ChatGPT erscheint = 2022 | Der Psychotherapeuten-Bot kam zuerst. ; Das Schach-Match lag in den Neunzigern. ; Der Chatbot für alle kam ganz zum Schluss. | Von ELIZA bis ChatGPT vergingen 56 Jahre KI-Geschichte.
M M | Welche ZWEI dieser Namen sind digitale Sprachassistenten großer Tech-Konzerne? | Siri ; Alexa | Tamagotchi ; Furby ; Clippy ; Tetris | Einer stammt von Apple. ; Der andere von Amazon. ; Ein Spielzeug-Ei und ein Plüschwesen sind keine Assistenten. | Siri (Apple) und Alexa (Amazon) hören aufs Wort; Clippy war Microsofts Büroklammer-Helfer, kein Sprachassistent.
C M | Was bezeichnet in der KI der Begriff „Prompt“? | Die Eingabe oder Anweisung an das Modell | Die Rechenleistung des Servers ; Ein Fehler im Trainingsdatensatz ; Die Ausgabe des Modells | Es kommt aus dem Theater — dort ist es das Soufflieren. ; Der Mensch schreibt ihn. ; Er steht am Anfang jeder Antwort. | Mit „Prompt Engineering“ bezeichnet man die Kunst, möglichst gute Anweisungen an eine KI zu formulieren.
C H | Wie heißt das Teilgebiet der KI, bei dem Programme aus Daten lernen statt fest programmierte Regeln zu befolgen? | Maschinelles Lernen | Symbolische Logik ; Relationale Datenbanken ; Objektorientierung | Auf Englisch: Machine Learning. ; Deep Learning ist ein Unterbereich davon. ; Das Programm wird mit Beispielen trainiert. | Maschinelles Lernen erkennt Muster in Beispieldaten; Deep Learning nutzt dafür tiefe neuronale Netze.
C U | Wie heißt die Humanoid-Roboterin der Firma Hanson Robotics, der Saudi-Arabien 2017 die Staatsbürgerschaft verlieh? | Sophia | Ameca ; Pepper ; Asimo | Ihr Name bedeutet auf Griechisch „Weisheit“. ; Ihr Gesicht wurde Audrey Hepburn nachempfunden. ; Sie war der erste Roboter mit einer Staatsbürgerschaft. | Sophia erhielt 2017 als erster Roboter weltweit eine Staatsbürgerschaft — eine viel kritisierte PR-Aktion.

@ autos_marken
C E | Aus welcher Stadt stammt der Autohersteller Porsche? | Stuttgart | München ; Wolfsburg ; Ingolstadt | Die Stadt liegt in Baden-Württemberg. ; Auch Mercedes-Benz hat dort seinen Sitz. ; Das Stadtwappen mit dem Pferd steckt im Porsche-Logo. | Das Porsche-Wappen zeigt das springende Stuttgarter Ross in der Mitte.
C M | In welchem italienischen Ort hat Ferrari seinen Sitz? | Maranello | Turin ; Sant'Agata Bolognese ; Mailand | Er liegt in der Nähe von Modena. ; Dort gibt es auch ein großes Firmenmuseum. ; Der Name beginnt mit M. | Ferrari produziert seit 1943 in Maranello; Lamborghini sitzt im nahen Sant'Agata Bolognese.
C M | Welche Automarke trägt einen Dreizack im Logo? | Maserati | Alfa Romeo ; Lancia ; Bugatti | Der Dreizack stammt vom Neptunbrunnen in Bologna. ; Die Firma sitzt heute in Modena. ; Die Gründer waren Brüder. | Die Maserati-Brüder übernahmen den Dreizack der Neptunstatue in Bologna, wo die Firma 1914 entstand.
C M | Welcher Konzern baut seit 2001 den neuen Mini? | BMW | Volkswagen ; Rover ; Mercedes-Benz | Der Konzern sitzt in München. ; Er übernahm 1994 die Rover-Gruppe. ; Sein Logo ist weiß-blau. | Der klassische Mini stammte von BMC bzw. Rover; seit 2001 baut BMW den modernen Mini, vor allem in Oxford.
C E | Welches VW-Modell kam 1974 als Nachfolger des Käfers auf den Markt? | Golf | Passat ; Polo ; Scirocco | Nach ihm ist eine ganze Generation benannt. ; Er ist nach einem Meeresstrom benannt. ; Die sportliche Version heißt GTI. | Der Golf wurde zum meistverkauften Auto Europas; Florian Illies schrieb das Buch „Generation Golf“.
C E | Wie heißt der legendäre Kleinwagen von VW mit dem runden Heck, der über 21 Millionen Mal gebaut wurde? | Käfer | Golf ; Polo ; Lupo | Er erinnert an ein Insekt. ; Im Film „Herbie“ spielt er die Hauptrolle. ; Das letzte Exemplar lief 2003 in Mexiko vom Band. | Der VW Käfer wurde von 1938 bis 2003 gebaut — über 21,5 Millionen Stück.
C E | Aus welchem Land stammt die Automarke Škoda? | Tschechien | Polen ; Slowakei ; Ungarn | Das Werk steht in Mladá Boleslav. ; Die Hauptstadt des Landes ist Prag. ; Die Marke gehört heute zum VW-Konzern. | Škoda wurde 1895 als Fahrradhersteller Laurin & Klement gegründet.
C E | Aus welchem Land stammt die Automarke Volvo? | Schweden | Norwegen ; Finnland ; Dänemark | Das Stammwerk steht in Göteborg. ; Heute gehört die Marke dem chinesischen Konzern Geely. ; Das Land ist auch die Heimat von IKEA. | Volvo bedeutet auf Latein „ich rolle“.
C U | Welche vier Marken schlossen sich 1932 zur Auto Union zusammen, deren Ringe Audi heute trägt? | Audi, DKW, Horch, Wanderer | Audi, BMW, Opel, Horch ; Audi, NSU, Borgward, DKW ; Audi, Maybach, Wanderer, Opel | Einer der Gründer war August Horch. ; Eine Marke baute Motorräder mit Zweitaktmotor. ; Eine hieß nach dem Wandern. | Aus der Auto Union entstand nach dem Krieg in Ingolstadt die heutige Audi AG.
C M | Welche Automarke hat einen „Blitz“ im Logo? | Opel | Audi ; Ford ; Seat | Der Stammsitz ist Rüsselsheim. ; Ein bekanntes Modell heißt Corsa. ; Der Lkw „Blitz“ gab dem Logo den Namen. | Das Blitz-Logo erinnert an den Opel-Lastwagen „Blitz“ aus den 1930er-Jahren.
C M | Welcher Autokonzern gilt gemessen an den Verkaufszahlen seit Jahren als größter der Welt (u. a. 2020–2023)? | Toyota | Volkswagen ; General Motors ; Hyundai | Das Unternehmen stammt aus Japan. ; Es erfand das „Just-in-time“-Prinzip. ; Der Prius war sein Hybrid-Pionier. | Toyota verkaufte 2023 über 11 Millionen Fahrzeuge und lag damit vor dem VW-Konzern.
C E | Welcher deutsche Ingenieur erfand den nach ihm benannten Selbstzünder-Motor? | Rudolf Diesel | Nikolaus Otto ; Wilhelm Maybach ; Robert Bosch | Er wurde 1858 in Paris geboren. ; Er verschwand 1913 bei einer Überfahrt nach England. ; Sein Name ist heute ein Kraftstoff. | Rudolf Diesel stellte seinen Motor 1897 in Augsburg vor.
C H | Wie hieß der erste Serien-Sportwagen des Herstellers Porsche aus dem Jahr 1948? | 356 | 911 ; 550 ; 912 | Es ist eine dreistellige Zahl. ; Er entstand im österreichischen Gmünd. ; Die Zahl beginnt mit 3. | Der Porsche 356 war das erste Serienauto unter dem Namen Porsche.
C H | Was ließ Bertha Benz auf ihrer Fernfahrt 1888 von einem Schuhmacher anbringen — der Legende nach die ersten ihrer Art? | Bremsbeläge aus Leder | Scheibenwischer ; eine Hupe ; einen Rückspiegel | Die Holzbremsen nutzten sich bergab ab. ; Ein Handwerker für Schuhe half. ; Es hat mit dem Anhalten zu tun. | Unterwegs reinigte sie außerdem eine verstopfte Benzinleitung mit ihrer Hutnadel.
C H | Nach wem ist die Marke Mercedes benannt? | Nach der Tochter eines Geschäftsmanns | Nach der Frau von Carl Benz ; Nach einer spanischen Stadt ; Nach einer römischen Göttin | Der Mann hieß Emil Jellinek. ; Er verkaufte Daimler-Wagen an der Riviera. ; Der Name ist spanisch und bedeutet „Gnaden“. | Emil Jellinek benannte seine Rennwagen nach seiner Tochter Mercedes — ab 1902 wurde es der Markenname.
C H | Aus welchem Land stammt die Automarke Seat? | Spanien | Italien ; Portugal ; Mexiko | Der Sitz ist in Martorell bei Barcelona. ; Modelle heißen Ibiza oder León. ; Heute gehört die Marke zum VW-Konzern. | Seat steht für „Sociedad Española de Automóviles de Turismo“.
C U | Unter welcher Typnummer wurde der Porsche 911 auf der IAA 1963 zuerst vorgestellt? | 901 | 910 ; 900 ; 991 | Peugeot erhob Einspruch. ; In der Mitte stand eine Null. ; Die Zahl endet auf 1. | Peugeot beanspruchte dreistellige Namen mit Null in der Mitte — also wurde aus dem 901 der 911.
C H | Welche Marke baut den Geländewagen „Defender“? | Land Rover | Jeep ; Toyota ; Mercedes-Benz | Die Marke ist britisch. ; Ihr Luxusableger heißt Range Rover. ; Der Name enthält das Wort „Land“. | Der Defender geht auf den Land Rover Series I von 1948 zurück.
C U | Wie hieß die Motorradmarke aus dem sächsischen Zschopau, die in der DDR weltweit exportierte? | MZ | Simson ; Jawa ; IFA | Die Abkürzung steht für Motorradwerk Zschopau. ; Die Maschinen gewannen viele Geländefahrten. ; Sie besteht aus zwei Buchstaben. | Zschopau war in den 1930ern mit DKW der größte Motorradhersteller der Welt.
C U | Welcher Hersteller brachte 1997 mit dem Prius das erste in Großserie gebaute Hybridauto auf den Markt? | Toyota | Honda ; Nissan ; Lexus | Die Firma stammt aus Japan. ; Der Name Prius bedeutet lateinisch „vorher“. ; Der Hersteller ist gemessen an Verkaufszahlen einer der größten der Welt. | Der Toyota Prius kam 1997 in Japan und 2000 nach Europa.
C M | In welcher Stadt hat Audi seinen Hauptsitz? | Ingolstadt | Neckarsulm ; Zwickau ; Regensburg | Die Stadt liegt an der Donau. ; Sie gehört zu Bayern. ; Der dortige Fußballverein heißt FC ... 04. | Audi sitzt seit 1949 in Ingolstadt; ein zweites großes Werk steht in Neckarsulm.
W E | Das Logo von Porsche zeigt einen Stier. | falsch | Das Porsche-Wappen zeigt das springende Stuttgarter Ross — der Stier ist das Wappentier von Lamborghini.
W M | Der Name Volvo stammt aus dem Lateinischen. | wahr | „Volvo“ heißt „ich rolle“ — ursprünglich war es ein Markenname für Kugellager.
W E | Ferrari wurde in Frankreich gegründet. | falsch | Enzo Ferrari gründete die Firma in Italien; ihr Sitz ist Maranello bei Modena.
W H | Der VW Käfer wurde länger gebaut als der VW Golf bisher. | wahr | Der Käfer lief von 1938 bis 2003 vom Band; den Golf gibt es erst seit 1974.
S H log | Wie viele PS hatte der erste Benz Patent-Motorwagen ungefähr? | 0.75 | PS | 40 | 0.1 | 100 | Weniger als ein Pferd. ; Heutige Rasenmäher sind stärker. ; Etwa drei Viertel. | Der Einzylinder leistete etwa 0,75 PS (knapp 0,6 kW) bei 400 Umdrehungen pro Minute.
S U | Wie viele Kilometer pro Stunde erreichte der Rekordwagen Thrust SSC 1997 als erstes Auto mit Überschallgeschwindigkeit? | 1228 | km/h | 15 | 300 | 3000 | Schneller als der Schall. ; Er hatte zwei Düsentriebwerke. ; Gut über 1200. | Andy Green fuhr 1997 in der Black-Rock-Wüste 1227,985 km/h — der bis heute gültige Landgeschwindigkeitsrekord.
O M | Sortiere diese Autos nach ihrem Marktstart — das älteste zuerst. | Ford Model T = 1908 ; VW Käfer (Serie) = 1945 ; VW Golf = 1974 ; Tesla Model S = 2012 | Das älteste war schwarz und kam vom Fließband. ; Das zweite rollte nach dem Krieg in Serie. ; Das Elektroauto ist das jüngste. | Die zivile Käfer-Serienproduktion begann erst Ende 1945 unter britischer Verwaltung.
M M | Welche ZWEI dieser Automarken stammen aus Italien? | Alfa Romeo ; Maserati | Škoda ; Volvo ; Dacia ; Peugeot | Eine sitzt in Turin bzw. Mailand. ; Die andere hat einen Dreizack im Logo. ; Tschechien, Schweden, Rumänien und Frankreich scheiden aus. | Alfa Romeo stammt aus Mailand, Maserati aus Modena (ursprünglich Bologna).
M M | Welche ZWEI dieser Automarken stammen aus Frankreich? | Renault ; Citroën | Seat ; Kia ; Fiat ; Opel | Eine hat eine Raute im Logo. ; Die andere einen Doppelwinkel. ; Spanien, Korea, Italien und Deutschland scheiden aus. | Renault (Raute) und Citroën (Doppelwinkel) gehören neben Peugeot zu den großen französischen Marken.

@ bahn_verkehr_mobilitaet de
C M | Welche Höchstgeschwindigkeit erreicht der ICE 3 im Linienbetrieb in Deutschland? | 300 km/h | 250 km/h ; 350 km/h ; 400 km/h | Auf der Schnellfahrstrecke Köln–Rhein/Main. ; Es ist eine runde Zahl. ; Mehr als 280, weniger als 320. | Auf der Strecke Köln–Frankfurt fahren ICE 3 planmäßig bis zu 300 km/h.
C E | Welche Farbe haben Autobahnschilder in Deutschland? | Blau | Grün ; Gelb ; Weiß | In der Schweiz ist es genau andersherum. ; Bundesstraßen-Wegweiser sind gelb. ; Die Farbe des Himmels. | In Deutschland sind Autobahnwegweiser blau, in der Schweiz und Italien grün.
C E | Was bedeutet ein rundes Verkehrsschild mit rotem Rand und weißer Mitte ohne Symbol? | Verbot der Einfahrt für alle Fahrzeuge | Vorfahrt achten ; Parkverbot ; Ende aller Verbote | Man darf nicht hineinfahren. ; Fußgänger dürfen trotzdem durch. ; Offiziell heißt es „Verbot für Fahrzeuge aller Art“. | Das Zeichen 250 verbietet Fahrzeugen aller Art die Durchfahrt.
C E | Welche Form hat das Stoppschild? | Achteck | Dreieck ; Kreis ; Raute | Es hat mehr Ecken als ein Sechseck. ; Man erkennt es auch von hinten an der Form. ; Acht Kanten. | Die achteckige Form ist weltweit einheitlich, damit man das Schild auch verschmutzt erkennt.
C M | Welche Form hat das Verkehrszeichen „Vorfahrtstraße“? | Gelbe Raute mit weißem Rand | Rotes Dreieck ; Blauer Kreis ; Weißes Achteck | Es steht auf der Spitze. ; Innen ist es gelb. ; Es ist ein auf die Ecke gestelltes Quadrat. | Das Zeichen 306 zeigt eine gelbe, weiß umrandete Raute.
C M | Welche ist mit rund 960 Kilometern die längste Autobahn Deutschlands? | A 7 | A 1 ; A 3 ; A 9 | Sie führt von Flensburg bis Füssen. ; Ungerade Nummern verlaufen meist in Nord-Süd-Richtung. ; Es ist eine einstellige ungerade Zahl. | Die A 7 verbindet die dänische Grenze mit den Alpen und ist rund 960 Kilometer lang.
C H | Welche Stadt hat die einzige hängende Einschienenbahn Deutschlands im Linienverkehr, die seit 1901 fährt? | Wuppertal | Dortmund ; Düsseldorf ; Dresden | Die Bahn schwebt großteils über einem Fluss. ; Der Fluss heißt Wupper. ; Einmal sprang ein Elefant hinaus. | Die Wuppertaler Schwebebahn fährt seit 1901 und gilt als sicherstes Verkehrsmittel Deutschlands.
C H | Wie hieß die erste in Deutschland eingesetzte Dampflok von 1835? | Adler | Falke ; Rocket ; Pfeil | Ein Greifvogel. ; Sie wurde in England gebaut. ; Das Wappentier Deutschlands. | Der „Adler“ kam aus der Werkstatt von Robert Stephenson in Newcastle.
C M | Was bedeutet die Abkürzung „ÖPNV“? | Öffentlicher Personennahverkehr | Österreichischer Personenverkehr ; Öffentliches Parknetzverzeichnis ; Örtlicher Pendlernahverkehr | Busse, Straßenbahnen und U-Bahnen gehören dazu. ; Das erste Wort bedeutet „für alle“. ; Es geht um kurze Strecken. | Zum ÖPNV zählen Busse, Trams, U- und S-Bahnen sowie Regionalzüge.
C H | Welches Land betrieb ab 1964 den ersten Hochgeschwindigkeitszug der Welt? | Japan | Frankreich ; Deutschland ; Italien | Der Zug heißt „Shinkansen“. ; Er startete zu den Olympischen Spielen. ; Die erste Strecke verband Tokio und Osaka. | Der Shinkansen ging im Oktober 1964 kurz vor den Olympischen Spielen in Tokio in Betrieb.
C H | Wie heißt der längste Eisenbahntunnel der Welt, der 2016 in der Schweiz eröffnet wurde? | Gotthard-Basistunnel | Simplontunnel ; Lötschberg-Basistunnel ; Brennertunnel | Er ist rund 57 Kilometer lang. ; Er unterquert ein berühmtes Alpenmassiv. ; Der Pass darüber ist nach einem Heiligen benannt. | Der Gotthard-Basistunnel misst 57,1 Kilometer und liegt bis zu 2300 Meter unter dem Gipfel.
C H | Wie heißt der Tunnel, der seit 1994 Großbritannien und Frankreich unter dem Meer verbindet? | Eurotunnel | Øresundtunnel ; Seikan-Tunnel ; Gotthardtunnel | Er unterquert den Ärmelkanal. ; Die Züge heißen Eurostar und Le Shuttle. ; Er verbindet Folkestone mit Calais. | Der Eurotunnel ist rund 50 Kilometer lang, davon fast 38 Kilometer unter Wasser.
C U | Welche Stadt auf dem europäischen Festland hat die älteste U-Bahn? | Budapest | Paris ; Berlin ; Wien | Sie wurde 1896 zur Tausendjahrfeier des Landes eröffnet. ; Die Stadt liegt an der Donau. ; Sie ist ungarische Hauptstadt. | Die Budapester Földalatti gehört heute zum UNESCO-Welterbe.
C H | Wie viele Punkte in Flensburg führen in Deutschland zum Entzug der Fahrerlaubnis? | 8 | 10 ; 18 ; 6 | Seit 2014 gilt das Fahreignungs-Bewertungssystem. ; Vorher lag die Grenze bei 18. ; Eine einstellige Zahl. | Seit der Reform 2014 ist der Führerschein bei 8 Punkten weg — früher bei 18.
C U ab12 | Wie heißt der Ort in Deutschland, an dem 1998 das schwerste ICE-Unglück geschah? | Eschede | Brühl ; Hordorf ; Bad Aibling | Der Ort liegt in Niedersachsen. ; Ein gebrochener Radreifen war die Ursache. ; Der Zug prallte gegen eine Brücke. | Beim ICE-Unglück von Eschede am 3. Juni 1998 starben 101 Menschen.
C U | Welcher Bahnhof in Deutschland zählt mit täglich rund 500.000 Reisenden und Besuchern zu den meistfrequentierten? | Hamburg Hauptbahnhof | Frankfurt Hauptbahnhof ; München Hauptbahnhof ; Köln Hauptbahnhof | Er liegt im Norden. ; Er steht nahe der Alster. ; Die Stadt hat einen großen Hafen. | Der Hamburger Hauptbahnhof gilt als meistfrequentierter Bahnhof Deutschlands.
W E | In Deutschland gibt es Autobahnabschnitte ohne generelles Tempolimit. | wahr | Auf vielen Abschnitten gilt nur die Richtgeschwindigkeit von 130 km/h.
W M | In Japan herrscht Rechtsverkehr. | falsch | Japan fährt links — wie Großbritannien, Irland, Indien und Australien.
W H | Die Stadt London hat die älteste U-Bahn der Welt. | wahr | Die Metropolitan Railway in London fuhr ab 1863 — anfangs mit Dampfloks.
S M | Wie viele Kilometer ist der Gotthard-Basistunnel ungefähr lang? | 57 | Kilometer | 15 | 5 | 200 | Mehr als 50. ; Es ist der längste Bahntunnel der Welt. ; Knapp unter 60. | Mit 57,1 Kilometern ist der Gotthard-Basistunnel der längste Eisenbahntunnel der Welt.
O H | Sortiere diese Städte danach, wann ihre U-Bahn eröffnet wurde — die älteste zuerst. | London = 1863 ; Budapest = 1896 ; Berlin = 1902 ; München = 1971 | Die älteste fuhr anfangs mit Dampf. ; Die zweite feierte ein Millennium. ; Die bayerische kam kurz vor den Olympischen Spielen. | Die Münchner U-Bahn wurde im Oktober 1971 rechtzeitig zu Olympia 1972 eröffnet.
M M | Welche ZWEI dieser Länder haben Linksverkehr? | Japan ; Australien | Frankreich ; USA ; Brasilien ; Deutschland | Beide liegen fern von Europa. ; Eines ist ein Inselstaat in Asien. ; Das andere ist ein Kontinent. | Linksverkehr gibt es in rund 75 Ländern, oft ehemaligen britischen Kolonien — Japan übernahm ihn trotzdem.

@ energie_umwelttechnik
C E | Welche Energiequelle nutzen Photovoltaikanlagen? | Sonnenlicht | Wind ; Erdwärme ; Wasserkraft | Sie liegen oft auf Dächern. ; Sie funktionieren nur bei Tageslicht. ; „Photo“ bedeutet Licht. | Solarzellen wandeln Licht über den photoelektrischen Effekt direkt in Strom um.
C E | Wie heißen die großen Anlagen mit Rotorblättern, die aus Wind Strom erzeugen? | Windkraftanlagen | Solarparks ; Staudämme ; Kühltürme | Man sieht sie oft an Küsten und auf Feldern. ; Die meisten haben drei Blätter. ; Früher mahlten ähnliche Geräte Korn. | Moderne Windkraftanlagen haben Rotordurchmesser von über 150 Metern.
C E | Welches Gas atmen Pflanzen ein und Menschen aus und gilt als wichtigstes vom Menschen verursachtes Treibhausgas? | Kohlendioxid | Sauerstoff ; Stickstoff ; Helium | Chemisch: CO₂. ; Es entsteht bei jeder Verbrennung. ; Sprudelwasser enthält es. | CO₂ entsteht bei Verbrennung von Kohle, Öl und Gas und verstärkt den Treibhauseffekt.
C M | In welchem Jahr ging in Deutschland das letzte Atomkraftwerk vom Netz? | 2023 | 2011 ; 2020 ; 2022 | Es war im April. ; Isar 2, Emsland und Neckarwestheim 2 waren die letzten. ; Der Ausstieg wurde wegen der Energiekrise einmal verschoben. | Am 15. April 2023 wurden die letzten drei deutschen Kernkraftwerke abgeschaltet.
C E | Welche Einheit gibt die Leistung an, etwa von einem Kraftwerk oder einer Glühbirne? | Watt | Volt ; Ampere ; Ohm | Benannt nach einem schottischen Erfinder. ; Er verbesserte die Dampfmaschine. ; Kilo-... kennt man von Staubsaugern. | Die Einheit Watt ehrt James Watt, der die Dampfmaschine entscheidend verbesserte.
C M | Welches Land erzeugt einen Großteil seines Stroms aus Erdwärme und heißen Quellen? | Island | Norwegen ; Irland ; Finnland | Das Land liegt auf dem Mittelatlantischen Rücken. ; Hier gibt es Geysire. ; Die Hauptstadt heißt Reykjavík. | Island deckt seinen Strom fast komplett aus Wasserkraft und Geothermie.
C M | Was ist ein „Pumpspeicherkraftwerk“? | Ein Speicher, der Wasser bergauf pumpt und später Strom daraus gewinnt | Ein Kraftwerk, das Öl aus dem Boden pumpt ; Ein Heizkraftwerk mit Wärmepumpen ; Ein Atomkraftwerk mit Wasserkühlung | Es braucht zwei Becken. ; Bei Stromüberschuss wird hochgepumpt. ; Bei Bedarf fließt das Wasser durch Turbinen zurück. | Pumpspeicher sind die größten Stromspeicher in Deutschland, etwa Goldisthal in Thüringen.
C M | Wie heißt das Gerät, das Wärme aus Luft, Erde oder Wasser für die Heizung nutzbar macht? | Wärmepumpe | Brennwertkessel ; Nachtspeicherofen ; Durchlauferhitzer | Sie funktioniert wie ein umgekehrter Kühlschrank. ; Sie braucht Strom. ; Sie wird oft mit dem Heizungsgesetz verbunden. | Eine Wärmepumpe liefert aus einer Kilowattstunde Strom oft drei bis vier Kilowattstunden Wärme.
C H | Welches Element wird in den meisten Kernkraftwerken als Brennstoff gespalten? | Uran | Plutonium ; Thorium ; Radium | Das Element ist nach einem Planeten benannt. ; Es hat die Ordnungszahl 92. ; Man nutzt das Isotop 235. | Uran-235 wird für Leichtwasserreaktoren auf rund drei bis fünf Prozent angereichert.
C H | Welches chemische Element bildet den Kern der meisten Solarzellen? | Silizium | Kupfer ; Germanium ; Lithium | Ein Tal in Kalifornien ist danach benannt. ; Man gewinnt es aus Quarzsand. ; Auch Computerchips bestehen daraus. | Rund 95 Prozent aller Solarmodule basieren auf kristallinem Silizium.
C H | Welches Metall steckt namensgebend in den meisten Akkus von E-Autos und Smartphones? | Lithium | Nickel ; Kobalt ; Blei | Es ist das leichteste Metall. ; Es hat die Ordnungszahl 3. ; Große Vorkommen liegen im „Dreieck“ Chile–Argentinien–Bolivien. | Lithium-Ionen-Akkus wurden 2019 mit dem Chemie-Nobelpreis gewürdigt.
C U | Wie heißt das größte Wasserkraftwerk der Welt, das am Jangtsekiang steht? | Drei-Schluchten-Damm | Itaipú ; Hoover Dam ; Assuan-Staudamm | Es liegt in China. ; Der Name nennt eine Zahl. ; Über eine Million Menschen wurden dafür umgesiedelt. | Der Drei-Schluchten-Damm hat eine Leistung von rund 22,5 Gigawatt.
C U ab12 | Welches Reaktorunglück ereignete sich im März 2011 nach einem Tsunami? | Fukushima | Tschernobyl ; Three Mile Island ; Sellafield | Es geschah in Japan. ; Ein Erdbeben der Stärke 9 löste den Tsunami aus. ; Danach beschloss Deutschland den schnellen Atomausstieg. | Nach Fukushima beschloss der Bundestag 2011 den Ausstieg bis 2022 — umgesetzt wurde er 2023.
W E | Windräder erzeugen auch dann Strom, wenn gar kein Wind weht. | falsch | Ohne Wind stehen die Rotoren still; meist starten sie ab etwa 3 Metern pro Sekunde.
W M | Das Reaktorunglück von Tschernobyl ereignete sich 1986 in der heutigen Ukraine. | wahr | Am 26. April 1986 explodierte Block 4 des Kernkraftwerks bei Prypjat.
W H | Die Einheit „Kilowattstunde“ misst eine Leistung. | falsch | Die Kilowattstunde misst Energie (Leistung mal Zeit) — die Leistung selbst misst man in Watt.
S U | Wie viel Prozent des Sonnenlichts wandeln typische moderne Silizium-Solarmodule in Strom um? | 21 | Prozent | 20 | 1 | 80 | Es ist deutlich weniger als die Hälfte. ; Vor 20 Jahren waren es etwa 14. ; Etwa ein Fünftel. | Handelsübliche Module erreichen rund 20 bis 23 Prozent Wirkungsgrad.
O H | Sortiere diese Kraftwerks-Premieren chronologisch — die früheste zuerst. | Erstes Wasserkraft-Haus Cragside = 1878 ; Erstes öffentliches Kohlekraftwerk = 1882 ; Erstes Kernkraftwerk am Netz = 1954 ; Erster Offshore-Windpark = 1991 | Die früheste Premiere nutzte einen Bach in England. ; Edison baute die zweite in New York. ; Windräder im Meer kamen zuletzt. | Cragside wurde 1878 per Wasserkraft beleuchtet, Edisons Pearl Street Station folgte 1882, Obninsk 1954 und Dänemarks Vindeby 1991.
M M | Welche ZWEI dieser Energiequellen zählen zu den erneuerbaren Energien? | Wasserkraft ; Biomasse | Erdgas ; Braunkohle ; Erdöl ; Uran | Beide erneuern sich in menschlichen Zeiträumen. ; Eine nutzt Flüsse. ; Die andere Pflanzenreste. | Fossile Träger und Uran sind endlich; Wasser, Wind, Sonne, Biomasse und Erdwärme gelten als erneuerbar.

@ computer_internet_technik
C E | Wofür steht die Abkürzung „USB“? | Universal Serial Bus | United System Board ; Ultra Speed Band ; Universal Storage Box | Das erste Wort bedeutet „allgemein“. ; Das letzte Wort kennt man auch vom Verkehrsmittel. ; Die Daten fließen seriell. | USB wurde 1996 eingeführt, um viele verschiedene Anschlüsse zu ersetzen.
C M | Wie viele verschiedene Werte lassen sich mit einem Byte darstellen? | 256 | 128 ; 100 ; 1024 | Ein Byte hat acht Bit. ; Zwei hoch acht. ; Die Zahl liegt zwischen 200 und 300. | Mit 8 Bit lassen sich die Werte 0 bis 255 darstellen — also 256 verschiedene.
C E | Welches Tier ist das Maskottchen des Betriebssystems Linux? | Ein Pinguin | Ein Fuchs ; Ein Elefant ; Eine Schlange | Er heißt Tux. ; Er lebt eigentlich in der Antarktis. ; Er kann nicht fliegen. | Linus Torvalds soll von einem Zwergpinguin gebissen worden sein — so kam Tux zu seinem Job.
C H | Welche deutsche Firma aus Paderborn war in den 1980ern einer der größten Computerhersteller Europas? | Nixdorf | Siemens ; Commodore ; Telefunken | Gründer war Heinz ... . ; In Paderborn steht heute ein großes Computermuseum. ; Die Firma ging 1990 an Siemens. | Das Heinz Nixdorf MuseumsForum in Paderborn gilt als eines der größten Computermuseen der Welt.
C U | Welches Programm gilt als erster Computervirus für PCs mit MS-DOS (1986)? | Brain | ILOVEYOU ; Melissa ; Stuxnet | Er stammt aus Pakistan. ; Er befiel Disketten-Bootsektoren. ; Der Name ist ein Körperteil. | „Brain“ wurde von zwei Brüdern aus Lahore geschrieben, die Raubkopien ihrer Software erkennen wollten.
C H | Welche Firma entwickelte die Programmiersprache Java (1995)? | Sun Microsystems | Microsoft ; IBM ; Apple | Der Firmenname enthält einen Himmelskörper. ; 2010 wurde sie von Oracle übernommen. ; James Gosling leitete das Projekt. | Java wurde ursprünglich „Oak“ genannt — nach einer Eiche vor Goslings Büro.
C U | Welcher Brite konstruierte im 19. Jahrhundert die mechanische „Analytical Engine“? | Charles Babbage | Alan Turing ; Michael Faraday ; James Watt | Er gilt als „Vater des Computers“. ; Ada Lovelace schrieb Programme für seine Maschine. ; Sein Nachname beginnt mit B. | Babbages Analytical Engine wurde nie fertig gebaut, war aber bereits programmierbar gedacht.
C U | Welche Zahl hat die Adresse „localhost“ im IPv4-Standard? | 127.0.0.1 | 192.168.0.1 ; 0.0.0.0 ; 255.255.255.255 | Man nennt sie „Loopback“. ; Sie verweist auf den eigenen Rechner. ; Sie beginnt mit 127. | Pakete an 127.0.0.1 verlassen den Rechner nie — „There's no place like 127.0.0.1“.
W M | Die erste Computermaus war aus Holz. | wahr | Douglas Engelbarts Prototyp von 1964 hatte ein Holzgehäuse und zwei Metallräder.
W H | Ein Kilobyte hat nach heutiger SI-Norm genau 1024 Byte. | falsch | Nach SI sind es 1000 Byte; 1024 Byte heißen korrekt ein Kibibyte (KiB).
S H | In welchem Jahr kam der Heimcomputer Commodore 64 auf den Markt? | 1982 | Jahr | 2 | 1970 | 2000 | Anfang der Achtziger. ; Ein Jahr nach dem IBM-PC. ; Das Jahr endet auf 2. | Der C64 erschien 1982 und wurde zum meistverkauften Heimcomputer-Modell.
O H | Sortiere diese Spielkonsolen nach ihrem Erscheinen in Japan bzw. den USA — die älteste zuerst. | Atari 2600 = 1977 ; NES/Famicom = 1983 ; PlayStation = 1994 ; Xbox = 2001 | Die älteste hatte einen Joystick mit einem Knopf. ; Die zweite brachte Super Mario. ; Microsoft kam als Letztes dazu. | Zwischen Atari 2600 und Xbox liegen 24 Jahre Konsolengeschichte.
M H | Welche ZWEI dieser Personen gründeten gemeinsam Apple? | Steve Jobs ; Steve Wozniak | Bill Gates ; Paul Allen ; Larry Page ; Mark Zuckerberg | Beide trugen denselben Vornamen. ; Die Gründung war 1976. ; Microsoft-Gründer sind nicht gemeint. | Apple wurde 1976 von Steve Jobs, Steve Wozniak und Ronald Wayne gegründet.

@ smartphones_gadgets
C E | Wie heißen die Tasten auf einer Handy-Tastatur, auf denen zusätzlich Stern und Raute liegen? | Sonderzeichen-Tasten | Funktionstasten F1 und F2 ; Lautstärketasten ; Menütasten | Sie liegen links und rechts neben der Null. ; Die eine zeigt *, die andere #. ; Man braucht sie für Codes am Telefon. | Die Tasten * und # dienen etwa für Mailbox-Codes und Servicenummern.
C M | Welche Firma brachte 1982 zusammen mit Sony die Audio-CD auf den Markt? | Philips | Panasonic ; Grundig ; Toshiba | Die Firma stammt aus den Niederlanden. ; Sie sitzt in Eindhoven. ; Sie ist auch für Rasierer und Glühbirnen bekannt. | Philips und Sony entwickelten die CD gemeinsam; 74 Minuten Spielzeit sollten für Beethovens Neunte reichen.
C H | Welche finnische Firma war vor dem Smartphone-Zeitalter weltweit größter Handy-Hersteller? | Nokia | Ericsson ; Siemens ; Motorola | Das Modell 3310 gilt als unzerstörbar. ; Die Firma begann einst mit Papier und Gummistiefeln. ; Ihr Klingelton ist legendär. | Nokia war von 1998 bis 2011 Weltmarktführer bei Mobiltelefonen.
W E | Das erste iPhone kam 2010 auf den Markt. | falsch | Steve Jobs stellte das erste iPhone im Januar 2007 vor; in den USA war es ab Juni 2007 erhältlich.
S M | Wie viele Tasten hat eine klassische Handy-Zifferntastatur mit Stern und Raute? | 12 | Tasten | 10 | 6 | 30 | Zehn Ziffern gehören dazu. ; Dazu kommen zwei Sonderzeichen. ; Drei Spalten, vier Reihen. | Die Tastatur 0–9 plus * und # ist in drei Spalten und vier Reihen angeordnet.

@ raumfahrt_technik
C M | Wie hieß die Hündin, die 1957 als erstes Lebewesen die Erde in einer Umlaufbahn umkreiste? | Laika | Belka ; Strelka ; Lassie | Sie flog mit Sputnik 2. ; Sie stammte von den Straßen Moskaus. ; Ihr Name bedeutet „Kläffer“. | Laika überlebte den Flug nicht; 1960 kehrten die Hündinnen Belka und Strelka lebend zurück.
C H | Wo liegt der europäische Weltraumbahnhof Kourou? | Französisch-Guayana | Kanarische Inseln ; Azoren ; Réunion | Er liegt in Südamerika. ; Nähe zum Äquator spart Treibstoff. ; Das Gebiet gehört zu Frankreich und zur EU. | Durch die Äquatornähe liefert die Erddrehung in Kourou zusätzlichen Schwung für Raketenstarts.
C U | Wie hieß der erste Westdeutsche im All, der 1983 mit dem Space Shuttle flog? | Ulf Merbold | Reinhard Furrer ; Thomas Reiter ; Ernst Messerschmid | Er war Physiker aus Stuttgart. ; Er flog mit dem Spacelab. ; Sein Vorname hat drei Buchstaben. | Merbold flog später auch mit russischen Sojus-Raumschiffen.
W H | Die Internationale Raumstation ISS umkreist die Erde etwa alle 90 Minuten. | wahr | Die ISS fliegt mit rund 28.000 km/h und schafft etwa 16 Erdumrundungen pro Tag.
O M | Sortiere diese Raumfahrt-Ereignisse chronologisch. | Sputnik 1 = 1957 ; Juri Gagarin im All = 1961 ; Mondlandung Apollo 11 = 1969 ; Erster ISS-Baustein = 1998 | Zuerst piepte ein Satellit. ; Dann flog der erste Mensch. ; Die Raumstation kam zuletzt. | Vom ersten Satelliten bis zur Mondlandung vergingen nur zwölf Jahre.
@ energie_umwelttechnik
C E | Welche Energiequelle nutzt ein Wasserkraftwerk? | Fließendes oder fallendes Wasser | Wind ; Sonnenlicht ; Erdgas | Oft steht es an einem Staudamm. ; Turbinen werden angetrieben. ; Der Name verrät es. | Wasserkraft ist die älteste großtechnisch genutzte erneuerbare Energie.
C E | Wie nennt man Autos, die ausschließlich mit Strom aus einem Akku fahren? | Elektroautos | Hybridautos ; Dieselautos ; Gasautos | Sie haben keinen Auspuff. ; Man lädt sie an einer Ladesäule. ; Kurz nennt man sie E-Autos. | Hybride kombinieren dagegen Elektro- und Verbrennungsmotor.
C E | Welches Gas entsteht neben Sauerstoff, wenn man Wasser per Elektrolyse spaltet? | Wasserstoff | Stickstoff ; Methan ; Helium | Es ist das leichteste Element. ; Man nennt es „grün“, wenn es mit Ökostrom erzeugt wird. ; Symbol H. | Grüner Wasserstoff gilt als wichtiger Energieträger für Industrie und Schwerlastverkehr.
C M | Welches Land erzeugt rund zwei Drittel seines Stroms aus Kernkraft? | Frankreich | Deutschland ; Japan ; Schweden | Das Land ist ein Nachbar Deutschlands. ; Der Stromkonzern heißt EDF. ; Die Hauptstadt ist Paris. | Frankreich betreibt über 50 Reaktoren — mehr als jedes andere Land Europas.
C H | Wie nennt man die Nutzung von Erdwärme zur Energiegewinnung? | Geothermie | Photovoltaik ; Solarthermie ; Biogas | „Geo“ bedeutet Erde. ; Im Erdinneren ist es sehr heiß. ; Island nutzt sie besonders stark. | Je tiefer man bohrt, desto wärmer wird es — im Schnitt rund 3 °C pro 100 Meter.
C U | Wie hieß das erste Kernkraftwerk der Welt, das 1954 Strom ins öffentliche Netz speiste? | Obninsk | Calder Hall ; Shippingport ; Kahl | Es stand in der Sowjetunion. ; Es lag südwestlich von Moskau. ; Es hatte nur 5 Megawatt Leistung. | Das britische Calder Hall folgte 1956 als erstes kommerzielles Großkraftwerk.
C U | Wie heißt der erste deutsche Offshore-Windpark, der 2010 in der Nordsee in Betrieb ging? | alpha ventus | Baltic 1 ; Nordsee Ost ; BARD Offshore 1 | Er liegt vor Borkum. ; Der Name beginnt mit dem ersten griechischen Buchstaben. ; „Ventus“ ist Latein für Wind. | Alpha ventus bestand aus zwölf Windkraftanlagen der Fünf-Megawatt-Klasse.
C U | In welchem Bundesland steht Deutschlands größtes Pumpspeicherkraftwerk Goldisthal? | Thüringen | Bayern ; Sachsen ; Baden-Württemberg | Das Land nennt sich „grünes Herz Deutschlands“. ; Die Hauptstadt ist Erfurt. ; Das Werk liegt im Schwarzatal. | Goldisthal hat eine Leistung von rund 1060 Megawatt.
W E | Solaranlagen erzeugen auch nachts Strom. | falsch | Ohne Licht liefern Solarzellen keinen Strom — deshalb braucht man Speicher oder andere Quellen.
W M | Eine LED-Lampe braucht für dieselbe Helligkeit deutlich weniger Strom als eine klassische Glühbirne. | wahr | LEDs sparen rund 80 bis 90 Prozent Strom gegenüber Glühbirnen.
W U | Das erste kommerzielle Kernkraftwerk Deutschlands stand in Kahl am Main. | wahr | Das Versuchsatomkraftwerk Kahl in Unterfranken speiste 1961 erstmals Strom ein.
S E | Wie viel Volt hat eine normale Haushaltssteckdose in Deutschland? | 230 | Volt | 5 | 50 | 500 | Früher waren es 220. ; Mehr als 200. ; Weniger als 250. | Die Netzspannung beträgt 230 Volt bei 50 Hertz.
S U | Wie viele Kilowattstunden Strom verbraucht ein Zwei-Personen-Haushalt in Deutschland pro Jahr ungefähr? | 2800 | kWh | 30 | 500 | 10000 | log | Mehr als 2000. ; Weniger als 4000. ; Ein Single-Haushalt braucht etwa 1500 bis 2000. | Je nach Ausstattung liegt der Verbrauch meist zwischen 2500 und 3000 kWh.
S U | Wie viele Meter hoch ist die Nabe moderner Onshore-Windräder in Deutschland typischerweise? | 140 | Meter | 25 | 20 | 400 | Höher als der Kölner Dom ist sie nicht ganz. ; Mehr als 100. ; Die Rotorspitzen reichen über 200 Meter. | Neue Anlagen haben oft Nabenhöhen zwischen 120 und 170 Metern.
O M | Sortiere diese Geräte nach ihrer typischen Leistung — die kleinste zuerst. | LED-Lampe = ≈ 8 W ; Laptop = ≈ 50 W ; Wasserkocher = ≈ 2000 W ; E-Auto-Schnelllader = ≈ 150 kW | Die sparsamste leuchtet. ; Der Computer braucht weniger als das Küchengerät. ; Die Ladesäule ist der Riese. | Ein Schnelllader liefert so viel Leistung wie Dutzende Wasserkocher gleichzeitig.
O H | Sortiere diese Stromquellen nach ihrem CO₂-Ausstoß pro Kilowattstunde über den Lebenszyklus — den niedrigsten zuerst. | Windkraft = ≈ 10 g ; Photovoltaik = ≈ 40 g ; Erdgas = ≈ 450 g ; Braunkohle = ≈ 1100 g | Das Windrad schneidet am besten ab. ; Solarstrom liegt knapp dahinter. ; Die fossile Kohle ist Schlusslicht. | Braunkohle ist der klimaschädlichste Energieträger in Deutschland.
M E | Welche ZWEI dieser Kraftwerke stoßen im Betrieb praktisch kein CO₂ aus? | Windkraftanlage ; Kernkraftwerk | Kohlekraftwerk ; Gaskraftwerk ; Ölkraftwerk ; Müllheizkraftwerk | Eines nutzt Luftbewegung. ; Das andere spaltet Atome. ; Alles, was verbrennt, scheidet aus. | Bei Bau und Brennstoff entstehen trotzdem geringe Emissionen.
M H | Welche ZWEI dieser Metalle stecken typischerweise in Lithium-Ionen-Akkus von E-Autos? | Lithium ; Kobalt | Blei ; Quecksilber ; Zinn ; Gold | Eines steht schon im Namen. ; Das andere wird viel im Kongo abgebaut. ; Blei steckt in Starterbatterien. | Hersteller versuchen, den Kobaltanteil wegen Kosten und Abbaubedingungen zu senken.

C E | An welcher Einrichtung lädt man ein Elektroauto unterwegs auf? | Ladesäule | Zapfsäule ; Parkuhr ; Waschanlage | Sie hat ein Kabel mit Stecker. ; Man findet sie oft auf Parkplätzen. ; Statt Benzin fließt Strom. | Schnellladesäulen laden viele E-Autos in rund 20 bis 30 Minuten auf 80 Prozent.
C H | Wie heißt die Technik, bei der ein Kraftwerk gleichzeitig Strom und nutzbare Wärme erzeugt? | Kraft-Wärme-Kopplung | Pumpspeicherung ; Kernfusion ; Fotosynthese | Die Abwärme wird für Fernwärme genutzt. ; Die Abkürzung ist KWK. ; Blockheizkraftwerke arbeiten so. | Durch die Nutzung der Abwärme erreichen KWK-Anlagen Gesamtwirkungsgrade von bis zu 90 Prozent.
W H | Große Windräder drehen sich schneller als kleine. | falsch | Große Rotoren drehen sich langsamer — oft nur 10 bis 15 Umdrehungen pro Minute —, ihre Blattspitzen sind aber sehr schnell.

@ ki_zukunftstechnik
C U | Wie heißt der humanoide Roboter von SoftBank mit Tablet auf der Brust, der 2014 vorgestellt wurde? | Pepper | Asimo ; Atlas ; Nao | Er soll Gefühle erkennen können. ; Er stand oft in Geschäften und Banken. ; Sein Name ist ein Gewürz auf Englisch. | Pepper wurde in Japan entwickelt; die Produktion endete 2021.
C U | In welchem Film von 1968 verweigert der Bordcomputer HAL 9000 den Gehorsam? | 2001: Odyssee im Weltraum | Blade Runner ; Alien ; Star Trek | Regie führte Stanley Kubrick. ; Der Film beginnt mit Affen und einem Monolithen. ; HAL sagt: „Tut mir leid, Dave.“ | HAL 9000 gilt als eine der berühmtesten Film-KIs.
W M | Der Begriff „Robotik“ wurde vom Science-Fiction-Autor Isaac Asimov geprägt. | wahr | Asimov verwendete das Wort „robotics“ erstmals 1941 in einer Kurzgeschichte.
M H | Welche ZWEI dieser Filme drehen sich um eine künstliche Intelligenz? | Her ; Ex Machina | Titanic ; Forrest Gump ; Rocky ; Grease | In einem verliebt sich ein Mann in ein Betriebssystem. ; Im anderen testet ein Programmierer eine Roboterfrau. ; Die übrigen sind Liebes-, Sport- und Musikfilme. | „Her“ (2013) gewann den Oscar für das beste Originaldrehbuch.
"""
