"""Extra questions: Tiere & Natur (format: see tools/content/merge_extra.py)."""
KAT = "tiere_natur"
REGION = "global"
DATA = r"""
@ wetter_naturphaenomene
C E | Wie heißt die große, hoch aufgetürmte Wolke, aus der Gewitter entstehen? | Cumulonimbus | Cirrus ; Stratus ; Altocumulus | Sie sieht oft aus wie ein Amboss. ; Aus ihr fallen auch Hagelkörner. ; Der Name enthält „nimbus“, lateinisch für Regenwolke. | Cumulonimbus-Wolken können über zehn Kilometer hoch in den Himmel ragen.
C E | Was ist Nebel eigentlich? | Eine Wolke, die am Boden liegt | Rauch aus Schornsteinen ; Verdunstendes Grundwasser ; Staub aus der Wüste | Er besteht aus winzigen Wassertröpfchen. ; Man sieht oft kaum die Hand vor Augen. ; Oben am Berg ist man manchmal mittendrin in dem, was unten Nebel ist. | Nebel entsteht, wenn feuchte Luft abkühlt und Wasserdampf kondensiert.
C E | Wie viele Ecken hat eine typische Schneeflocke? | Sechs | Vier ; Fünf ; Acht | Das liegt an der Struktur von Wassermolekülen im Eis. ; So viele wie ein Bienenwabenfeld. ; Doppelt so viele wie ein Dreieck. | Eiskristalle wachsen wegen der Anordnung der Wassermoleküle sechseckig.
C E | Wo muss die Sonne stehen, damit man einen Regenbogen sieht? | Im Rücken des Betrachters | Direkt vor dem Betrachter ; Genau über dem Kopf ; Hinter einer Wolke | Vor einem muss es regnen. ; Hinter einem scheint es. ; Morgens sieht man ihn im Westen, abends im Osten. | Das Sonnenlicht wird in den Regentropfen gebrochen und zum Betrachter zurückgespiegelt.
C E | Wie nennt man Eiskörner, die bei Gewittern vom Himmel fallen? | Hagel | Graupel ; Raureif ; Tau | Die Körner können so groß wie Tennisbälle werden. ; Er beschädigt Autos und Ernten. ; Das Wort hat fünf Buchstaben. | Hagelkörner wachsen, wenn Aufwinde sie mehrfach durch die unterkühlte Wolke wirbeln.
C E | Was misst ein Thermometer auf einer Wetterstation? | Die Lufttemperatur | Den Luftdruck ; Die Windgeschwindigkeit ; Die Regenmenge | Man liest es in Grad Celsius ab. ; Es hängt im Schatten in einer weißen Hütte. ; Es zeigt, ob es warm oder kalt ist. | Die Lufttemperatur wird in zwei Metern Höhe im Schatten gemessen.
C E | Wie nennt man die Wissenschaft vom Wetter? | Meteorologie | Geologie ; Astronomie ; Ozeanographie | Der Name kommt von „meteoros“, griechisch für „in der Luft schwebend“. ; Wettervorhersagen stammen von ihr. ; Es hat nichts mit Meteoriten zu tun. | Meteorologen werten Messdaten und Computermodelle für Vorhersagen aus.
C M | Welches Messgerät misst die Windgeschwindigkeit? | Anemometer | Hygrometer ; Barometer ; Seismometer | Oft dreht sich ein Schalenkreuz im Wind. ; „Anemos“ ist griechisch für Wind. ; Man findet es auf Masten an Wetterstationen. | Das Schalenkreuz-Anemometer dreht sich umso schneller, je stärker der Wind ist.
C M | Wie heißt die Skala, die die Windstärke von 0 bis 12 einteilt? | Beaufort-Skala | Richter-Skala ; Saffir-Simpson-Skala ; Fujita-Skala | Sie wurde von einem britischen Admiral entwickelt. ; Windstärke 12 heißt Orkan. ; Ursprünglich beschrieb sie die Wirkung auf Segelschiffe. | Francis Beaufort entwickelte die Skala 1806 für die Seefahrt.
C M | Wie nennt man den warmen, trockenen Fallwind an der Nordseite der Alpen? | Föhn | Mistral ; Bora ; Scirocco | Er sorgt in München für klare Fernsicht. ; Manche bekommen davon Kopfschmerzen. ; Der Haartrockner ist nach ihm benannt. | Beim Absteigen erwärmt sich die Luft — der Föhn kann die Temperatur in Stunden stark steigen lassen.
C M | Was verursacht Polarlichter? | Geladene Teilchen der Sonne treffen auf die Atmosphäre | Spiegelungen von Eis ; Blitze über dem Polarmeer ; Mondlicht in Schneekristallen | Man spricht vom Sonnenwind. ; Das Magnetfeld der Erde lenkt sie zu den Polen. ; Sauerstoff leuchtet dabei grün. | Grünes und rotes Polarlicht stammt von Sauerstoff, violett-blaues von Stickstoff.
C M | Wie heißen die kühlen Tage vom 11. bis 15. Mai, nach denen kein Frost mehr droht? | Eisheilige | Hundstage ; Schafskälte ; Rauhnächte | Die Tage sind nach Heiligen benannt. ; Der letzte ist die „Kalte Sophie“. ; Gärtner pflanzen erst danach empfindliche Pflanzen. | Mamertus, Pankratius, Servatius, Bonifatius und Sophie heißen die Eisheiligen.
C H | Nach welchem Stern sind die „Hundstage“ im Hochsommer benannt? | Sirius | Polarstern ; Beteigeuze ; Wega | Er ist der hellste Stern am Nachthimmel. ; Er gehört zum Sternbild Großer Hund. ; In der Antike ging er im Sommer wieder am Morgenhimmel auf. | Die Hundstage dauern etwa vom 23. Juli bis 23. August.
C M | Wie nennt man eine Phase mit sonnigem, mildem Herbstwetter und Spinnfäden in der Luft? | Altweibersommer | Nachsommer der Hexen ; Indianerwinter ; Spätlese | Die Spinnfäden erinnern an graue Haare. ; Er kommt meist im September oder Oktober. ; In Nordamerika heißt er „Indian Summer“. | Ein Gericht entschied 1989, dass der Begriff ältere Frauen nicht diskriminiert.
C M | In welche Richtung weht ein „Westwind“? | Von Westen nach Osten | Von Osten nach Westen ; Von Norden nach Süden ; Immer im Kreis | Winde werden nach ihrer Herkunft benannt. ; Er kommt aus der Richtung des Sonnenuntergangs. ; In Deutschland bringt er oft Regen vom Atlantik. | Bei Winden gibt der Name die Richtung an, aus der sie kommen.
C H | In welcher Stadt hat der Deutsche Wetterdienst seinen Hauptsitz? | Offenbach am Main | Hamburg ; Potsdam ; München | Die Stadt liegt direkt neben Frankfurt. ; Sie ist in Hessen. ; Sie ist für ihr Ledermuseum bekannt. | Der DWD wurde 1952 gegründet und sitzt in Offenbach am Main.
C M | Wie heißt ein tropischer Wirbelsturm, der im Atlantik Hurrikan genannt wird, im Westpazifik? | Taifun | Tornado ; Monsun ; Blizzard | Er trifft oft Japan, die Philippinen und China. ; Im Indischen Ozean spricht man von Zyklon. ; Der Name kommt vermutlich aus dem Chinesischen. | Hurrikan, Taifun und Zyklon sind dasselbe Wetterphänomen — nur in verschiedenen Weltregionen.
C H | Wie heißt die ruhige, oft wolkenfreie Zone im Zentrum eines Hurrikans? | Auge des Sturms | Herz des Sturms ; Stille Zelle ; Windschatten | Sie ist von der gefährlichsten Wand umgeben. ; Dort ist es fast windstill. ; Ein Körperteil steckt im Namen. | Das Auge eines Hurrikans kann 20 bis 60 Kilometer Durchmesser haben.
C H | Wie heißt die unterste Schicht der Erdatmosphäre, in der sich das Wetter abspielt? | Troposphäre | Stratosphäre ; Mesosphäre ; Thermosphäre | Sie reicht etwa 8 bis 17 Kilometer hoch. ; Flugzeuge fliegen an ihrem oberen Rand. ; „Tropos“ bedeutet Wendung. | Über der Troposphäre liegt die Stratosphäre mit der Ozonschicht.
C H | In welcher Schicht der Atmosphäre liegt die Ozonschicht? | Stratosphäre | Troposphäre ; Mesosphäre ; Exosphäre | Sie liegt über der Wetterschicht. ; Rund 15 bis 35 Kilometer hoch. ; Felix Baumgartner sprang 2012 aus ihr. | Das Ozon filtert einen Großteil der gefährlichen UV-Strahlung der Sonne.
C H | Wie heißt der jahreszeitlich wechselnde Wind, der Südasien im Sommer heftige Regenfälle bringt? | Monsun | Passat ; Schirokko ; Mistral | Das Wort kommt vom arabischen Wort für Jahreszeit. ; Indiens Landwirtschaft hängt von ihm ab. ; Im Winter weht er umgekehrt und trocken. | Der Sommermonsun entsteht, weil sich das Land stärker erwärmt als der Indische Ozean.
C H | Wie heißt das Klimaphänomen, bei dem sich der Pazifik vor Südamerika um die Weihnachtszeit stark erwärmt? | El Niño | La Niña ; Monsun ; Passat | Der Name bedeutet „das Christkind“. ; Peruanische Fischer gaben ihm den Namen. ; Das Gegenstück heißt „das Mädchen“. | El Niño verändert Wetter weltweit — von Dürren in Australien bis Starkregen in Peru.
C U | Bei welcher Bauernregel entscheidet das Wetter am 27. Juni angeblich über die nächsten sieben Wochen? | Siebenschläfertag | Johannistag ; Medardustag ; Mariä Heimsuchung | Namensgeber sind sieben Heilige in einer Höhle. ; Nicht das Nagetier ist gemeint. ; Die Zahl Sieben steckt im Namen. | Wegen der Kalenderreform passt die Regel eher auf Anfang Juli — dann stabilisiert sich tatsächlich oft die Großwetterlage.
C H | Wie heißt der Wetterbegriff für eine Wetterlage mit hohem Luftdruck, die meist sonniges Wetter bringt? | Hochdruckgebiet | Tiefdruckgebiet ; Kaltfront ; Trog | Im Wetterbericht wird es mit H markiert. ; Die Luft sinkt dort ab. ; Wolken lösen sich meist auf. | Auf der Nordhalbkugel strömt die Luft im Uhrzeigersinn aus einem Hoch heraus.
C U ab12 | Wie hieß die Sturmflut von 1962, bei der in Hamburg über 300 Menschen starben? | Hamburger Sturmflut | Große Mandränke ; Allerheiligenflut ; Weihnachtsflut | Sie geschah in der Nacht vom 16. auf den 17. Februar. ; Innensenator Helmut Schmidt organisierte die Rettung. ; Die Stadt liegt an der Elbe. | In Hamburg starben 315 Menschen; Helmut Schmidt setzte eigenmächtig Bundeswehr und NATO-Truppen ein.
C U | Wo wurde mit −89,2 °C die tiefste Lufttemperatur der Erde gemessen? | Wostok-Station in der Antarktis | Oimjakon in Sibirien ; Nordpol ; Grönland-Station Summit | Es war 1983. ; Die Station ist russisch. ; Sie liegt auf dem antarktischen Eisschild. | Satelliten maßen an der Oberfläche der Antarktis sogar noch kältere Werte von um −98 °C.
C U | Wie heißt das Wolkenphänomen mit beutelförmigen Ausbuchtungen an der Wolkenunterseite? | Mammatus | Lenticularis ; Kelvin-Helmholtz ; Asperitas | Der Name kommt vom lateinischen Wort für Brust. ; Man sieht sie oft nach schweren Gewittern. ; Sie hängen unter dem Amboss. | Mammatus-Wolken entstehen, wenn kalte, feuchte Luft aus der Wolke absinkt.
W E | Blitze sind heißer als die Oberfläche der Sonne. | wahr | Ein Blitzkanal erreicht rund 30.000 °C — die Sonnenoberfläche nur etwa 5500 °C.
W M | Ein Tornado und ein Hurrikan sind dasselbe. | falsch | Tornados sind kleine, kurzlebige Luftwirbel über Land; Hurrikane sind riesige Wirbelstürme über warmen Ozeanen.
W M | Auf der Nordhalbkugel drehen sich Tiefdruckgebiete gegen den Uhrzeigersinn. | wahr | Die Corioliskraft durch die Erddrehung lässt Tiefs auf der Nordhalbkugel links herum rotieren.
W H | Das Wasser im Abfluss dreht sich auf der Nordhalbkugel wegen der Erddrehung immer in dieselbe Richtung. | falsch | Die Corioliskraft ist für ein Waschbecken viel zu schwach — Form und Restbewegung des Wassers entscheiden.
W H | Bei einem Gewitter ist man unter einer einzeln stehenden Eiche sicherer als unter einer Buche. | falsch | Die Regel „Eichen sollst du weichen, Buchen sollst du suchen“ ist ein Mythos — einzeln stehende Bäume sind immer gefährlich.
S M | Welchen Luftdruck in Hektopascal hat die Normalatmosphäre auf Meereshöhe? | 1013 | hPa | 3 | 800 | 1200 | Früher sagte man Millibar. ; Etwas über 1000. ; Er steht auf vielen Barometern in der Mitte. | Der Normaldruck beträgt 1013,25 Hektopascal.
S H | Ab welcher Windgeschwindigkeit (km/h) spricht man nach Beaufort von einem Orkan? | 118 | km/h | 10 | 50 | 300 | Es ist Windstärke 12. ; Deutlich mehr als 100. ; Unter 120. | Ab 118 km/h (Windstärke 12) spricht man von Orkan — ähnlich der Grenze für Hurrikane.
S U | Wie viele Blitze gibt es weltweit ungefähr pro Sekunde? | 45 | Blitze | 40 | 1 | 1000 | log | Deutlich mehr als zehn. ; Weniger als hundert. ; Satelliten zählen sie. | Satellitenmessungen ergeben rund 40 bis 50 Blitze pro Sekunde — über 1,4 Milliarden pro Jahr.
O M | Sortiere diese Wolken nach ihrer typischen Höhe — die niedrigste zuerst. | Nebel = Bodenniveau ; Stratus = bis ca. 2 km ; Altocumulus = ca. 2–7 km ; Cirrus = ca. 7–12 km | Die erste liegt direkt auf dem Boden. ; Schichtwolken folgen tief darüber. ; Die Federwolken aus Eis liegen am höchsten. | Cirruswolken bestehen komplett aus Eiskristallen.
O M | Sortiere diese Schichten der Atmosphäre von unten nach oben. | Troposphäre = bis ca. 12 km ; Stratosphäre = bis ca. 50 km ; Mesosphäre = bis ca. 85 km ; Thermosphäre = bis ca. 600 km | Das Wetter spielt sich ganz unten ab. ; Die Ozonschicht liegt in der zweiten. ; In der obersten fliegt die ISS. | Die ISS kreist in rund 400 Kilometern Höhe in der Thermosphäre.
O H | Sortiere diese Eisheiligen in ihrer Reihenfolge im Mai — den frühesten zuerst. | Mamertus = 11. Mai ; Pankratius = 12. Mai ; Servatius = 13. Mai ; Kalte Sophie = 15. Mai | Der erste ist nur in Norddeutschland bekannt. ; In der Mitte steht Servatius. ; Die „Kalte“ kommt zuletzt. | Zwischen Servatius und Sophie liegt noch Bonifatius am 14. Mai.
M M | Welche ZWEI dieser Begriffe bezeichnen Wirbelstürme? | Hurrikan ; Taifun | Föhn ; Passat ; Monsun ; Nebel | Beide entstehen über warmen Ozeanen. ; Einer trifft die Karibik. ; Der andere Ostasien. | Hurrikan (Atlantik/Ostpazifik) und Taifun (Westpazifik) sind tropische Wirbelstürme.
M H | Welche ZWEI dieser Wetterelemente misst ein Hygrometer bzw. Barometer? | Luftfeuchtigkeit ; Luftdruck | Windrichtung ; Sonnenscheindauer ; Niederschlagsmenge ; Sichtweite | Das eine Gerät hat „hygro“ (feucht) im Namen. ; Das andere „baros“ (Schwere). ; Wind und Regen misst man anders. | Hygrometer messen Feuchte — früher sogar mit einem gespannten Menschenhaar.

@ heimische_tiere_wald de
C E | Welches heimische Tier hat einen weißen Kopf mit schwarzen Streifen und gräbt große Baue? | Dachs | Iltis ; Marder ; Fuchs | In Fabeln heißt er Grimbart. ; Er ist ein Marder. ; Sein Bau kann über Generationen genutzt werden. | Dachsbaue können über 100 Jahre alt sein und Dutzende Eingänge haben.
C E | Welcher große weiß-schwarze Vogel mit rotem Schnabel bringt der Sage nach die Babys? | Weißstorch | Graureiher ; Kranich ; Silberreiher | Er brütet gern auf Kirchtürmen. ; Er zieht im Winter nach Afrika. ; Man nennt ihn auch Adebar. | Viele Weißstörche überwintern inzwischen auch in Spanien statt in Afrika.
C H | Welche beiden Giftschlangen leben in Deutschland? | Kreuzotter und Aspisviper | Kreuzotter und Ringelnatter ; Aspisviper und Äskulapnatter ; Kreuzotter und Schlingnatter | Ringel-, Äskulap- und Schlingnatter sind ungiftig. ; Eine Art lebt nur im Südschwarzwald. ; Die bekanntere hat ein Zickzackband auf dem Rücken. | Die Aspisviper kommt in Deutschland nur an wenigen Stellen im südlichen Schwarzwald vor.
C M | Woran erkennt man eine harmlose Ringelnatter? | An zwei gelben Halbmondflecken am Hinterkopf | An einem Zickzackband auf dem Rücken ; An roten Augen ; An einer Rassel am Schwanz | Die Flecken sitzen hinter dem Kopf. ; Sie sind gelblich oder weiß. ; Sie schwimmt gern. | Die Ringelnatter stellt sich bei Gefahr tot und verströmt ein übel riechendes Sekret.
C M | Aus welchem Land stammt der Waschbär, der sich heute in Deutschland ausbreitet? | Nordamerika | Südamerika ; Asien ; Australien | Er wurde 1934 am Edersee ausgesetzt. ; Er trägt eine „Räubermaske“. ; In Kanada und den USA ist er heimisch. | Heute leben in Deutschland schätzungsweise über eine Million Waschbären.
C M | Welche Eule erkennt man an ihrem herzförmigen, weißen Gesichtsschleier? | Schleiereule | Waldkauz ; Uhu ; Steinkauz | Sie brütet gern in Scheunen und Kirchtürmen. ; Der Name nennt ein Brautaccessoire. ; Sie jagt vor allem Mäuse. | Die Schleiereule hört so gut, dass sie Mäuse in völliger Dunkelheit fangen kann.
C M | Welches Tier ist Europas größter Käfer? | Hirschkäfer | Nashornkäfer ; Maikäfer ; Goliathkäfer | Die Männchen haben geweihartige Oberkiefer. ; Seine Larven leben jahrelang in morschem Eichenholz. ; Er ist nach einem Waldtier benannt. | Männliche Hirschkäfer werden bis zu neun Zentimeter lang.
C M | Welcher heimische Marder trägt im Winter ein weißes Fell mit schwarzer Schwanzspitze? | Hermelin | Iltis ; Steinmarder ; Mauswiesel | Königsmäntel wurden aus seinem Fell gefertigt. ; Im Sommer ist er braun. ; Er heißt auch Großes Wiesel. | Die schwarzen Tupfen auf Königsmänteln sind Hermelin-Schwanzspitzen.
C M | Welcher Waldvogel warnt mit lautem Rätschen alle anderen Tiere und heißt deshalb „Polizist des Waldes“? | Eichelhäher | Buntspecht ; Kuckuck ; Amsel | Er hat blau gestreifte Flügelfedern. ; Er versteckt Eicheln. ; Er ist ein Rabenvogel. | Eichelhäher vergessen viele versteckte Eicheln — und pflanzen so neue Eichen.
C M | Wie nennt man die jungen Feldhasen, die mit Fell und offenen Augen zur Welt kommen? | Nestflüchter | Nesthocker ; Frischlinge ; Kitze | Junge Kaninchen sind dagegen nackt und blind. ; Sie können bald nach der Geburt laufen. ; Das Gegenteil heißt Nesthocker. | Die Häsin besucht ihre Jungen nur ein- bis zweimal am Tag zum Säugen.
C U | In welchem Bundesland wurde 1934 am Edersee die ersten Waschbären Deutschlands ausgesetzt? | Hessen | Niedersachsen ; Bayern ; Thüringen | Die Hauptstadt ist Wiesbaden. ; Kassel liegt in der Nähe. ; Frankfurt gehört auch dazu. | Kassel gilt bis heute als „Waschbär-Hauptstadt“ Europas.
C H | Wie heißt der Vogel, der im Herbst zu Zehntausenden im brandenburgischen Linum rastet und als „Vogel des Glücks“ gilt? | Kranich | Graugans ; Weißstorch ; Seeadler | Er ist grau mit rotem Scheitel. ; Seine Rufe klingen trompetenartig. ; Sein Tanz ist berühmt. | Kraniche ziehen in keilförmigen Formationen und rasten auf Feuchtwiesen.
C U | Wie viele Jahre leben Maikäfer ungefähr als Engerling im Boden? | Drei bis vier Jahre | Wenige Wochen ; Ein Jahr ; Zehn Jahre | Als Käfer leben sie nur wenige Wochen. ; Sie fressen dabei Wurzeln. ; Maikäferjahre wiederholen sich im selben Rhythmus. | Wegen der mehrjährigen Entwicklung gibt es regional regelrechte „Maikäferjahre“.
C U | Wie heißt Deutschlands größter Greifvogel mit bis zu 2,5 Metern Spannweite? | Seeadler | Steinadler ; Mäusebussard ; Rotmilan | Er lebt an Seen und Küsten. ; Er ist an der Ostseeküste und an der Mecklenburgischen Seenplatte heimisch. ; Er frisst viel Fisch. | Der Seeadler war in Deutschland fast ausgestorben und hat sich seit den 1980ern gut erholt.
W E | Die Blindschleiche ist eine Schlange. | falsch | Die Blindschleiche ist eine beinlose Echse — sie kann blinzeln und ihren Schwanz abwerfen.
W M | Die Kreuzotter ist die einzige Giftschlange Deutschlands. | falsch | Neben der Kreuzotter lebt im Südschwarzwald auch die Aspisviper.
W M | Zecken sind Insekten. | falsch | Zecken sind Spinnentiere — erwachsene Zecken haben acht Beine.
W H | Glühwürmchen sind Käfer. | wahr | Glühwürmchen gehören zur Familie der Leuchtkäfer; oft leuchten vor allem die Weibchen.
S M | Wie viele Kilogramm wiegt ein ausgewachsener männlicher Rothirsch ungefähr? | 150 | kg | 30 | 20 | 500 | Deutlich mehr als ein Mensch. ; Weniger als 300. ; Etwa wie zwei große Männer. | Rothirsche wiegen je nach Region 100 bis 250 Kilogramm; die Weibchen deutlich weniger.
O M | Sortiere diese heimischen Tiere nach ihrem Gewicht — das leichteste zuerst. | Zwergmaus = ≈ 7 g ; Eichhörnchen = ≈ 300 g ; Fuchs = ≈ 7 kg ; Wildschwein = ≈ 100 kg | Das kleinste baut Kugelnester im Getreide. ; Der Nussverstecker ist leichter als der Rotrock. ; Das Borstentier ist das schwerste. | Die Zwergmaus gehört zu den kleinsten Nagetieren Europas.
M M | Welche ZWEI dieser Tiere halten einen echten Winterschlaf? | Igel ; Fledermaus | Eichhörnchen ; Dachs ; Reh ; Fuchs | Beide senken ihre Körpertemperatur stark. ; Einer frisst Insekten am Boden. ; Der andere hängt kopfüber in Höhlen. | Eichhörnchen und Dachse halten nur Winterruhe und wachen regelmäßig auf.

@ pflanzen_baeume
C E | Welche Pflanze brennt auf der Haut, wenn man sie berührt? | Brennnessel | Löwenzahn ; Gänseblümchen ; Klee | Feine Härchen brechen ab. ; Aus ihr kann man Tee kochen. ; Der Name verrät es. | Die Brennhaare enthalten unter anderem Ameisensäure und Histamin.
C E | Welche große gelbe Blume dreht als junge Pflanze ihren Kopf der Sonne nach? | Sonnenblume | Tulpe ; Narzisse ; Rose | Aus ihren Kernen macht man Öl. ; Van Gogh malte sie. ; Der Name enthält unser Zentralgestirn. | Nur junge Sonnenblumen folgen der Sonne; ausgewachsene Blüten schauen meist nach Osten.
C E | Welcher giftige Pilz hat einen roten Hut mit weißen Punkten? | Fliegenpilz | Steinpilz ; Pfifferling ; Champignon | Er ist ein Glückssymbol. ; Er wächst oft unter Birken. ; Er steht in vielen Märchenbildern. | Der Fliegenpilz ist giftig, aber selten tödlich; früher lockte man damit Fliegen in Milch.
C E | Welche Blume ist das Nationalsymbol der Niederlande und kam ursprünglich aus dem Osmanischen Reich? | Tulpe | Rose ; Nelke ; Lilie | Im 17. Jahrhundert gab es einen Spekulationswahn mit ihr. ; Ihre Zwiebeln kommen im Herbst in die Erde. ; Das Wort stammt vom türkischen Wort für Turban. | Auf dem Höhepunkt der Tulpenmanie 1637 kostete eine Zwiebel so viel wie ein Haus.
C E | Aus dem Saft welches Baumes wird Ahornsirup gewonnen? | Zuckerahorn | Bergahorn ; Birke ; Linde | Sein Blatt ist auf der Flagge Kanadas. ; Der Saft wird im Vorfrühling gezapft. ; Der Name verrät die Süße. | Für einen Liter Sirup kocht man rund 40 Liter Saft ein.
C M | Welcher Laubbaum ist der häufigste in Deutschland? | Rotbuche | Stieleiche ; Birke ; Bergahorn | Von Natur aus wäre er fast überall vorherrschend. ; Seine Früchte heißen Bucheckern. ; Seine Rinde ist glatt und grau. | Ohne menschlichen Einfluss wären rund zwei Drittel Deutschlands mit Buchenwald bedeckt.
C E | Wie heißt die fleischfressende Pflanze, deren Fangblätter blitzschnell zuschnappen? | Venusfliegenfalle | Sonnentau ; Kannenpflanze ; Wasserschlauch | Sie stammt aus North und South Carolina. ; Sie schließt sich bei zwei Berührungen der Sinneshaare. ; Eine Göttin steckt im Namen. | Die Falle schließt sich in rund einer Zehntelsekunde.
C M | Zu welchem Reich gehören Pilze biologisch? | Zu einem eigenen Reich | Zu den Pflanzen ; Zu den Tieren ; Zu den Bakterien | Sie betreiben keine Photosynthese. ; Sie sind mit Tieren enger verwandt als mit Pflanzen. ; Ihre Zellwände enthalten Chitin. | Pilze bilden neben Pflanzen und Tieren ein eigenes Reich der Lebewesen.
C M | Wie erkennt man eine Tanne im Unterschied zur Fichte? | Flache Nadeln mit zwei weißen Streifen unten | Nadeln wachsen in Büscheln ; Die Zapfen hängen nach unten ; Sie verliert im Winter die Nadeln | „Die Fichte sticht, die Tanne nicht.“ ; Schau dir die Unterseite der Nadeln an. ; Ihre Zapfen stehen aufrecht. | Tannennadeln sind weich und flach, Fichtennadeln spitz und vierkantig.
C H | Welche Pflanze hat die größte Einzelblüte der Welt? | Rafflesia arnoldii | Titanwurz ; Riesenseerose ; Sonnenblume | Sie wächst in Südostasien. ; Sie riecht nach Aas. ; Sie hat weder Blätter noch Stängel. | Ihre Blüte kann rund einen Meter Durchmesser und bis zu elf Kilogramm Gewicht erreichen.
C H | Welche Blume ist die Nationalblume Japans und wird im Frühjahr mit dem Hanami-Fest gefeiert? | Kirschblüte | Lotosblume ; Chrysantheme ; Orchidee | Die Bäume blühen zartrosa. ; Unter ihnen wird gepicknickt. ; Die Früchte der Zierbäume sind nicht essbar. | Die Chrysantheme ist das Symbol des Kaiserhauses — die Kirschblüte ist die beliebteste Blume des Volkes.
C H | Wie heißt die Pflanze, aus deren Fasern Leinen hergestellt wird? | Flachs | Hanf ; Baumwolle ; Jute | Sie blüht blau. ; Aus ihren Samen gewinnt man Leinöl. ; Das Wort „Lein“ ist ein anderer Name für sie. | Leinen gehört zu den ältesten Textilien der Menschheit.
C U | Wie heißen die Atemwurzeln, mit denen Mangroven aus dem Schlamm ragen? | Pneumatophoren | Rhizome ; Luftknollen ; Haustorien | Das Wort kommt vom griechischen „pneuma“ für Luft. ; Sie wachsen senkrecht nach oben. ; Der Schlamm enthält kaum Sauerstoff. | Über winzige Poren in diesen Wurzeln bekommen Mangroven trotz Salzwasserschlamm Luft.
W E | Kakteen stammen ursprünglich aus Afrika. | falsch | Kakteen sind — bis auf eine Ausnahme — in Amerika heimisch; in Afrika wachsen ähnlich aussehende Wolfsmilchgewächse.
W M | Tomaten- und Kartoffelpflanzen sind eng miteinander verwandt. | wahr | Beide gehören zu den Nachtschattengewächsen — ihre grünen Teile sind giftig.
W H | Der Pfifferling ist ein giftiger Pilz. | falsch | Der Pfifferling ist ein beliebter Speisepilz — Vorsicht nur vor seinem Doppelgänger, dem Falschen Pfifferling.
S U | Wie viele Pflanzenarten gibt es auf der Erde ungefähr (bekannte Gefäßpflanzen, in Tausend)? | 380 | Tausend Arten | 30 | 10 | 5000 | log | Es sind Hunderttausende. ; Weniger als eine Million. ; Knapp 400.000. | Botaniker kennen rund 380.000 Arten von Gefäßpflanzen — jedes Jahr kommen etwa 2000 neue hinzu.
O M | Sortiere diese Blumen nach ihrer typischen Blütezeit im Jahr — die früheste zuerst. | Schneeglöckchen = Februar ; Tulpe = April ; Rose = Juni ; Herbstaster = September | Das erste blüht oft noch im Schnee. ; Die Frühlingszwiebelblume folgt. ; Die Aster schließt das Gartenjahr ab. | Schneeglöckchen können dank eines Frostschutzmittels im Zellsaft auch bei Kälte blühen.
M M | Welche ZWEI dieser Bäume sind Nadelbäume? | Kiefer ; Lärche | Birke ; Ahorn ; Linde ; Esche | Beide tragen Zapfen. ; Einer verliert im Winter seine Nadeln. ; Laubbäume scheiden aus. | Die Lärche ist der einzige heimische Nadelbaum, der im Herbst seine Nadeln abwirft.

@ saeugetiere_haustiere
C E | Wie heißt ein junger Hund? | Welpe | Fohlen ; Kitz ; Ferkel | Er ist noch klein und verspielt. ; Das Wort beginnt mit W. ; Wölfe haben auch welche. | Hundewelpen öffnen ihre Augen erst nach etwa zwei Wochen.
C E | Wie heißt das Jungtier einer Kuh? | Kalb | Fohlen ; Lamm ; Ferkel | Es trinkt Milch bei der Mutter. ; Auch junge Elefanten und Wale heißen so. ; Das Wort hat vier Buchstaben. | Auch Jungtiere von Hirschen, Elefanten, Walen und Giraffen nennt man Kalb.
W M | Ein Koala ernährt sich fast ausschließlich von Eukalyptusblättern. | wahr | Eukalyptus ist nährstoffarm und schwer verdaulich — darum schlafen Koalas bis zu 20 Stunden am Tag.
S H | Wie viele Monate dauert die Tragzeit eines Afrikanischen Elefanten ungefähr? | 22 | Monate | 10 | 5 | 40 | Fast zwei Jahre. ; Deutlich länger als beim Menschen. ; Etwa 22. | Die rund 22-monatige Tragzeit ist die längste unter den Landsäugetieren.

@ ozean_meerestiere
C E | Welches Meerestier hat einen Panzer und läuft seitwärts? | Krabbe | Qualle ; Seestern ; Seepferdchen | Sie hat Scheren. ; Man findet sie am Strand und im Watt. ; Sie gehört zu den Krebstieren. | Krabben laufen seitwärts, weil ihre Beingelenke so am schnellsten funktionieren.
C M | Bei welchem Tier trägt das Männchen die Jungen in einer Bruttasche aus? | Seepferdchen | Pinguin ; Delfin ; Tintenfisch | Es schwimmt aufrecht. ; Sein Kopf erinnert an ein Pferd. ; Es ist ein Fisch. | Beim Seepferdchen legt das Weibchen die Eier in die Bruttasche des Männchens.
W M | Seesterne haben kein Blut, sondern pumpen gefiltertes Meerwasser durch ihren Körper. | wahr | Das sogenannte Wassergefäßsystem versorgt Seesterne mit Sauerstoff und bewegt ihre Saugfüßchen.
O H | Sortiere diese Meerestiere nach ihrer maximalen Länge — das kürzeste zuerst. | Seepferdchen = ≈ 30 cm ; Delfin (Großer Tümmler) = ≈ 4 m ; Weißer Hai = ≈ 6 m ; Blauwal = ≈ 30 m | Das kürzeste ist ein aufrecht schwimmender Fisch. ; Der Tümmler ist kürzer als der Hai. ; Das größte Tier aller Zeiten steht am Ende. | Der Blauwal ist das größte bekannte Tier, das je gelebt hat.

@ insekten_krabbeltiere
C E | Welches Insekt zirpt auf Sommerwiesen, indem es Flügel oder Beine aneinanderreibt? | Grille | Marienkäfer ; Ameise ; Libelle | Es gibt Feld- und Heimchen-Arten. ; Man hört sie vor allem abends. ; Das Wort reimt sich auf „Brille“. | Bei Grillen zirpen nur die Männchen — sie reiben dafür ihre Vorderflügel aneinander.
C M | Wie teilt eine Honigbiene ihren Artgenossen mit, wo Futter zu finden ist? | Mit dem Schwänzeltanz | Mit Brummtönen ; Mit Duftspuren am Boden ; Mit Farbwechseln | Sie tanzt auf der Wabe. ; Der Winkel zeigt die Richtung zur Sonne. ; Karl von Frisch entschlüsselte es. | Karl von Frisch erhielt für die Entschlüsselung der Bienensprache 1973 den Nobelpreis.
W M | Die Anzahl der Punkte eines Marienkäfers verrät sein Alter. | falsch | Die Punktzahl hängt von der Art ab — der Siebenpunkt hat immer sieben.
S M | Wie viele Flügel hat ein Maikäfer insgesamt, die harten Deckflügel mitgezählt? | 4 | Flügel | 25 | 0 | 12 | Käfer haben zwei Flügelpaare. ; Die vorderen sind hart. ; Mehr als zwei. | Die harten Deckflügel schützen die dünnen Hautflügel, mit denen der Käfer tatsächlich fliegt.
O E | Sortiere die Entwicklungsstadien eines Schmetterlings in der richtigen Reihenfolge. | Ei = Stadium 1 ; Raupe = Stadium 2 ; Puppe = Stadium 3 ; Falter = Stadium 4 | Alles beginnt auf einem Blatt. ; Das gefräßige Stadium kommt vor dem ruhenden. ; Zum Schluss schlüpft das geflügelte Tier. | Diese vollständige Verwandlung nennt man Metamorphose.
"""
