"""Extra questions: Wissenschaft (format: see tools/content/merge_extra.py)."""
KAT = "wissenschaft"
REGION = "global"
DATA = r"""
@ physik_chemie
C E | Welches chemische Symbol hat Sauerstoff? | O | S ; Sa ; Ox | Es ist ein einzelner Buchstabe. ; Wasser ist H₂... ; Der Buchstabe ist rund. | Das Symbol O kommt vom lateinischen „Oxygenium“, dem „Säurebildner“.
C E | Bei wie viel Grad Celsius gefriert Wasser unter Normaldruck? | 0 °C | 4 °C ; −10 °C ; 10 °C | Die Celsius-Skala ist daran ausgerichtet. ; Es ist der Nullpunkt der Skala. ; Auf Fahrenheit sind es 32 Grad. | Anders Celsius legte die Skala 1742 fest — ursprünglich sogar umgekehrt, mit 100 für den Gefrierpunkt.
C E | Welches Metall zieht ein Magnet an? | Eisen | Aluminium ; Kupfer ; Gold | Es rostet. ; Aus ihm wird Stahl gemacht. ; Chemisches Symbol Fe. | Eisen, Nickel und Kobalt sind ferromagnetisch; Aluminium und Kupfer bleiben unbeeindruckt.
C E | Wie nennt man den Übergang von fest zu flüssig? | Schmelzen | Verdampfen ; Kondensieren ; Sublimieren | Eis tut das in der Sonne. ; Das Gegenteil heißt Erstarren. ; Auch Schokolade in der Hand macht es. | Der Schmelzpunkt von Eis liegt bei 0 °C.
C E | Welche Farbe entsteht, wenn man Blau und Gelb im Farbkasten mischt? | Grün | Lila ; Orange ; Braun | Die Farbe von Gras. ; Sie steht auf Ampeln für „Gehen“. ; Blätter im Sommer haben sie. | Beim Mischen von Malfarben (subtraktiv) ergeben Blau und Gelb Grün.
C E | Welches Gas füllt man in Luftballons, damit sie nach oben steigen? | Helium | Stickstoff ; Kohlendioxid ; Sauerstoff | Es macht die Stimme hoch und piepsig. ; Es ist ein Edelgas. ; Es ist leichter als Luft. | Helium ist nach Wasserstoff das zweitleichteste Element — und im Gegensatz dazu nicht brennbar.
C E | Welche Farben hat ein Regenbogen, wenn man außen anfängt? | Rot zuerst, Violett innen | Blau zuerst, Rot innen ; Gelb zuerst, Grün innen ; Violett zuerst, Rot innen | Die Farbe mit der längsten Wellenlänge liegt außen. ; Innen liegt die Farbe von Veilchen. ; Außen die Farbe der Liebe. | Im Hauptregenbogen liegt Rot außen und Violett innen; im Nebenregenbogen ist es umgekehrt.
C M | Wie heißt das Element mit dem chemischen Symbol Na? | Natrium | Stickstoff ; Neon ; Nickel | Es steckt im Kochsalz. ; Es reagiert heftig mit Wasser. ; Der lateinische Name steckt im Symbol. | Kochsalz ist Natriumchlorid, NaCl.
C M | Welches chemische Symbol hat Silber? | Ag | Si ; S ; Sr | Es stammt vom lateinischen „argentum“. ; Ein südamerikanisches Land ist danach benannt. ; Zwei Buchstaben, beginnend mit A. | Argentinien heißt übersetzt „Silberland“.
C M | Wie heißt die Einheit der elektrischen Stromstärke? | Ampere | Volt ; Watt ; Ohm | Benannt nach einem französischen Physiker. ; Die Abkürzung ist A. ; Sicherungen im Haus haben z. B. 16 davon. | André-Marie Ampère erforschte um 1820 die Kräfte zwischen stromdurchflossenen Leitern.
C M | Welcher Physiker formulierte die drei Bewegungsgesetze und das Gravitationsgesetz? | Isaac Newton | Galileo Galilei ; Albert Einstein ; Johannes Kepler | Ein Apfel soll ihn inspiriert haben. ; Er war Engländer. ; Die Einheit der Kraft ist nach ihm benannt. | Newtons „Principia“ von 1687 gilt als eines der wichtigsten Bücher der Wissenschaftsgeschichte.
C H | Welche Farbe hat die Flamme, wenn man Kupfersalz in einen Bunsenbrenner hält? | Grün bis blaugrün | Gelb ; Rot ; Violett | Diese Farbe entsteht auch bei manchem Feuerwerk. ; Natrium färbt gelb, Kupfer anders. ; Es ist die Farbe der Grünspan-Patina. | Die Flammenfärbung verrät Elemente: Natrium gelb, Kalium violett, Kupfer grün.
C M | Welches Edelgas leuchtet in klassischen Leuchtreklamen rotorange? | Neon | Argon ; Xenon ; Radon | Solche Reklamen tragen seinen Namen. ; Der Name bedeutet „das Neue“. ; Es steht im Periodensystem direkt nach Fluor. | Neonröhren leuchten nur mit Neon rotorange; andere Farben kommen von anderen Gasen oder Beschichtungen.
C M | Wie nennt man den direkten Übergang von fest zu gasförmig, etwa bei Trockeneis? | Sublimation | Kondensation ; Destillation ; Resublimation | Flüssig wird der Stoff dabei nie. ; Trockeneis ist gefrorenes CO₂. ; Das Gegenteil nennt man Resublimation. | Trockeneis sublimiert bei −78,5 °C direkt zu Kohlendioxidgas.
C M | Was misst man mit einem Barometer? | Luftdruck | Temperatur ; Luftfeuchtigkeit ; Windgeschwindigkeit | Es hilft bei der Wettervorhersage. ; Evangelista Torricelli baute das erste. ; Das griechische „baros“ heißt Schwere. | Fällt der Luftdruck, kündigt sich oft schlechtes Wetter an.
C M | Wie heißt die Kraft, die bei einer Kurvenfahrt scheinbar nach außen drückt? | Zentrifugalkraft | Gravitationskraft ; Reibungskraft ; Auftriebskraft | Sie heißt auch Fliehkraft. ; Wäscheschleudern nutzen sie. ; Das Wort enthält „fliehen vom Zentrum“. | Die Zentrifugalkraft ist eine Scheinkraft, die nur im mitrotierenden Bezugssystem auftritt.
C H | Welches ist das häufigste Element im Universum? | Wasserstoff | Helium ; Sauerstoff ; Kohlenstoff | Es hat die Ordnungszahl 1. ; Sterne bestehen zum großen Teil daraus. ; Es ist Bestandteil von Wasser. | Rund drei Viertel der normalen Materie im Universum bestehen aus Wasserstoff.
C H | Welches ist das häufigste Element in der Erdkruste? | Sauerstoff | Silizium ; Eisen ; Aluminium | Es ist in Gesteinen chemisch gebunden. ; Wir atmen es. ; Es macht fast die Hälfte der Kruste aus. | Sauerstoff macht etwa 46 Prozent der Erdkruste aus, gefolgt von Silizium mit rund 28 Prozent.
C H | Welcher Physiker entdeckte 1831 die elektromagnetische Induktion? | Michael Faraday | James Clerk Maxwell ; Alessandro Volta ; Georg Simon Ohm | Er war ein Brite ohne Studium. ; Nach ihm ist ein Käfig benannt. ; Die Einheit der Kapazität heißt nach ihm. | Faradays Entdeckung ist die Grundlage aller Generatoren und Transformatoren.
C H | Welches Element hat die Ordnungszahl 6? | Kohlenstoff | Stickstoff ; Sauerstoff ; Bor | Alles Leben basiert darauf. ; Diamant und Graphit bestehen daraus. ; Symbol: C. | Kohlenstoff hat sechs Protonen; das Isotop C-14 nutzt man zur Altersbestimmung.
C H | Wie heißt die Einheit der Frequenz? | Hertz | Joule ; Newton ; Tesla | Ein Schwingvorgang pro Sekunde. ; Benannt nach einem Hamburger Physiker. ; Radios zeigen Mega-... an. | Heinrich Hertz wies 1886 in Karlsruhe elektromagnetische Wellen nach.
C H | Welche Physikerin entdeckte zusammen mit ihrem Mann die Elemente Polonium und Radium? | Marie Curie | Lise Meitner ; Irène Joliot-Curie ; Emmy Noether | Sie stammte aus Warschau. ; Polonium benannte sie nach ihrer Heimat. ; Sie war die erste Frau mit Nobelpreis. | Marie und Pierre Curie entdeckten 1898 die beiden Elemente.
C H | Wie heißt das Prinzip, nach dem ein Körper in einer Flüssigkeit so viel Auftrieb erfährt, wie die verdrängte Flüssigkeit wiegt? | Archimedisches Prinzip | Bernoulli-Effekt ; Pascalsches Gesetz ; Hookesches Gesetz | Der Entdecker soll „Heureka!“ gerufen haben. ; Er saß dabei in der Badewanne. ; Er lebte in Syrakus. | Archimedes soll so geprüft haben, ob die Krone des Königs aus reinem Gold war.
C U | Welches Element wurde zuerst auf der Sonne entdeckt, bevor man es auf der Erde fand? | Helium | Neon ; Argon ; Wasserstoff | Man sah es 1868 bei einer Sonnenfinsternis im Spektrum. ; Der Name kommt vom griechischen Sonnengott. ; Es füllt Partyballons. | Helios ist der griechische Sonnengott — erst 1895 wies man Helium auch auf der Erde nach.
C U | Welcher Chemiker gilt als Entdecker des Sauerstoffs, veröffentlichte aber zu spät, sodass Joseph Priestley oft den Ruhm erhält? | Carl Wilhelm Scheele | Antoine Lavoisier ; Robert Boyle ; Henry Cavendish | Er war ein deutsch-schwedischer Apotheker. ; Er nannte das Gas „Feuerluft“. ; Nach ihm ist das grüne Pigment „...sches Grün“ benannt. | Scheele entdeckte Sauerstoff um 1772, sein Buch erschien aber erst 1777.
C U | Wie hieß Lord Kelvin, der Namensgeber der Kelvin-Temperaturskala, mit bürgerlichem Namen? | William Thomson | James Prescott Joule ; William Herschel ; John Dalton | Er stammte aus Belfast. ; Er lehrte über 50 Jahre in Glasgow. ; Sein Adelstitel kommt von einem Fluss namens Kelvin. | William Thomson wurde 1892 zum Baron Kelvin geadelt — benannt nach dem Fluss an seiner Universität.
W E | Schall ist schneller als Licht. | falsch | Licht ist fast eine Million Mal schneller — darum sieht man den Blitz vor dem Donner.
W M | Aluminium ist das häufigste Metall in der Erdkruste. | wahr | Aluminium macht rund 8 Prozent der Erdkruste aus — mehr als Eisen mit etwa 5 Prozent.
W M | Diamanten können verbrennen. | wahr | Diamant ist reiner Kohlenstoff — in reinem Sauerstoff verbrennt er ab etwa 700 °C zu Kohlendioxid.
W H | Aus einem einzigen Gramm Gold lässt sich ein mehrere Kilometer langer Draht ziehen. | wahr | Gold ist das dehnbarste Metall: Ein Gramm reicht für rund zwei bis drei Kilometer feinsten Draht.
S M | Wie viele Protonen hat ein Sauerstoffatom? | 8 | Protonen | 15 | 1 | 30 | Die Ordnungszahl verrät es. ; Kohlenstoff hat sechs, Stickstoff sieben. ; Eine Zweierpotenz. | Sauerstoff hat die Ordnungszahl 8 — also acht Protonen im Kern.
S H | Bei wie viel Grad Celsius schmilzt Eisen ungefähr? | 1538 | °C | 10 | 200 | 4000 | Deutlich heißer als ein Backofen. ; Über 1500 Grad. ; Kupfer schmilzt bei etwa 1085 Grad. | Reines Eisen schmilzt bei rund 1538 °C; Stahl je nach Legierung etwas niedriger.
S U log | Wie viele Kilometer legt Licht im Vakuum ungefähr in einer Sekunde zurück? | 300000 | km | 5 | 1000 | 10000000 | Es umrundet die Erde in einer Sekunde etwa siebenmal. ; Eine Zahl mit fünf Nullen. ; Zum Mond braucht es gut eine Sekunde. | Die Lichtgeschwindigkeit beträgt exakt 299.792,458 km/s.
O M | Sortiere diese Stoffe nach ihrem Siedepunkt — den niedrigsten zuerst. | Stickstoff = −196 °C ; Ethanol (Alkohol) = 78 °C ; Wasser = 100 °C ; Quecksilber = 357 °C | Der erste Stoff siedet schon weit unter null. ; Alkohol verdampft vor Wasser. ; Das flüssige Metall ist am hitzebeständigsten. | Dass Alkohol früher siedet als Wasser, nutzt man beim Schnapsbrennen.
O U | Sortiere diese Teilchen nach ihrer Masse — das leichteste zuerst. | Elektron = ≈ 1/1836 u ; Proton = ≈ 1,007 u ; Neutron = ≈ 1,009 u ; Heliumkern = ≈ 4 u | Das negativ geladene Teilchen ist winzig. ; Das neutrale Teilchen ist minimal schwerer als das positive. ; Der Heliumkern besteht aus vier Kernteilchen. | Ein Proton ist etwa 1836-mal schwerer als ein Elektron.
M M | Welche ZWEI dieser Stoffe sind Edelgase? | Argon ; Xenon | Stickstoff ; Chlor ; Wasserstoff ; Fluor | Beide stehen ganz rechts im Periodensystem. ; Eines macht knapp ein Prozent der Luft aus. ; Das andere steckt in Autoscheinwerfern. | Edelgase (Helium, Neon, Argon, Krypton, Xenon, Radon) reagieren kaum mit anderen Stoffen.
M H | Welche ZWEI dieser Metalle sind bei Raumtemperatur magnetisch (ferromagnetisch)? | Nickel ; Kobalt | Kupfer ; Aluminium ; Gold ; Zink | Beide gehören wie Eisen zur Eisengruppe. ; Eines ist in Euro-Münzen verbaut. ; Das andere färbt Glas blau. | Neben Eisen sind bei Raumtemperatur vor allem Nickel und Kobalt ferromagnetisch.

@ erfindungen_entdeckungen
C U | Welcher Alchemist sollte für August den Starken Gold machen und erfand stattdessen das europäische Hartporzellan mit? | Johann Friedrich Böttger | Johann Joachim Kändler ; Josiah Wedgwood ; Paracelsus | Er wurde auf der Albrechtsburg festgehalten. ; Die Manufaktur entstand in Meißen. ; Sein Vorname ist Johann Friedrich. | Böttger gelang das Porzellan 1708 zusammen mit Ehrenfried Walther von Tschirnhaus; 1710 folgte die Manufaktur.
C E | Welche Brüder gelten als Erfinder des ersten gesteuerten Motorflugs 1903? | Die Brüder Wright | Die Brüder Grimm ; Die Brüder Lumière ; Die Brüder Montgolfier | Sie waren Fahrradmechaniker. ; Sie stammten aus Ohio. ; Ihr Nachname klingt wie „richtig“ auf Englisch. | Orville und Wilbur Wright flogen am 17. Dezember 1903 bei Kitty Hawk.
C M | Wer erfand den Blitzableiter? | Benjamin Franklin | Thomas Edison ; Nikola Tesla ; James Watt | Er war einer der Gründerväter der USA. ; Er ließ 1752 einen Drachen im Gewitter steigen. ; Er ist auf dem 100-Dollar-Schein. | Franklin erkannte, dass Blitze elektrische Entladungen sind, und entwickelte daraus den Blitzableiter.
C E | Welche Brüder ließen 1783 den ersten Heißluftballon aufsteigen? | Die Brüder Montgolfier | Die Brüder Wright ; Die Brüder Lumière ; Die Brüder Grimm | Sie waren Papierfabrikanten. ; Sie stammten aus Frankreich. ; Die ersten Passagiere waren ein Schaf, eine Ente und ein Hahn. | Nach dem Tiertest flogen im November 1783 die ersten Menschen über Paris.
C U | Welcher deutsche Ingenieur baute 1876 eine der ersten Kältemaschinen und erfand später die Luftverflüssigung? | Carl von Linde | Robert Bosch ; Carl Bosch ; Werner von Siemens | Ein heutiger Gase-Konzern trägt seinen Namen. ; Brauereien waren seine ersten Kunden. ; Sein Name ist auch ein Baum. | Lindes Kältemaschinen ermöglichten Bierbrauen unabhängig von Natureis.
C H | Welcher Deutsche erfand 1817 die Laufmaschine, einen Vorläufer des Fahrrads? | Karl Drais | Gottlieb Daimler ; Werner von Siemens ; Carl Benz | Er lebte in Mannheim. ; Das Gerät nennt man nach ihm „Draisine“. ; Es hatte noch keine Pedale. | Drais soll die Laufmaschine erfunden haben, als nach dem „Jahr ohne Sommer“ 1816 Pferde knapp waren.
C M | Wer erfand die Jeans mit Kupfernieten? | Levi Strauss und Jacob Davis | Calvin Klein ; Tommy Hilfiger ; Hugo Boss | Einer stammte aus dem fränkischen Buttenheim. ; Das Patent stammt von 1873. ; Die Hosen waren für Goldgräber gedacht. | Levi Strauss aus Buttenheim und der Schneider Jacob Davis ließen sich 1873 die Nieten-Jeans patentieren.
C M | Welcher Schotte verbesserte ab 1769 die Dampfmaschine so, dass sie die Industrialisierung antrieb? | James Watt | George Stephenson ; Thomas Newcomen ; Richard Trevithick | Die Einheit der Leistung trägt seinen Namen. ; Er fügte einen getrennten Kondensator hinzu. ; Sein Vorname ist James. | Watts Dampfmaschine verbrauchte rund zwei Drittel weniger Kohle als die ältere Newcomen-Maschine.
C E | Wer erfand den nach ihm benannten Code aus Punkten und Strichen? | Samuel Morse | Alexander Graham Bell ; Guglielmo Marconi ; Charles Wheatstone | Er war eigentlich Maler. ; SOS lautet in seinem Code ··· ––– ···. ; Sein Nachname hat fünf Buchstaben. | Samuel Morse schickte 1844 die erste Telegrafennachricht von Washington nach Baltimore.
C U | Welcher Amerikaner entwickelte 1884 einen tropfsicheren Füllfederhalter mit Kapillar-Tintenleiter? | Lewis Waterman | László Bíró ; George Parker ; Günther Wagner | Die Marke trägt noch heute seinen Namen. ; Er war Versicherungsvertreter. ; Angeblich ruinierte ein Tintenklecks einen Vertrag. | Watermans Füller nutzte feine Kanäle, damit Tinte gleichmäßig nachfloss.
C H | Welcher deutsche Arzt entwickelte mit Salvarsan das erste moderne Chemotherapeutikum gegen Syphilis? | Paul Ehrlich | Robert Koch ; Emil von Behring ; Rudolf Virchow | Er prägte den Begriff der „Zauberkugel“. ; Er war auf dem 200-D-Mark-Schein. ; Sein Nachname ist eine Tugend. | Paul Ehrlich brachte Salvarsan 1910 auf den Markt; 1908 hatte er den Medizin-Nobelpreis erhalten.
C U | Welcher Sohn deutscher Einwanderer entwickelte für die US-Volkszählung 1890 eine Lochkarten-Zählmaschine? | Herman Hollerith | Thomas J. Watson ; Charles Babbage ; Konrad Zuse | Seine Firma wurde später Teil von IBM. ; Seine Eltern stammten aus der Pfalz. ; Die Lochkarten tragen oft seinen Namen. | Mit Holleriths Maschinen war die Volkszählung 1890 in einem Bruchteil der früheren Zeit ausgewertet.
C U | Wer erfand 1938 den ersten Kopierer mit dem Xerografie-Verfahren? | Chester Carlson | Thomas Edison ; Edwin Land ; George Eastman | Er war US-Patentanwalt. ; Die Firma Xerox machte das Verfahren groß. ; Seine erste Kopie trug die Aufschrift „10.-22.-38 Astoria“. | Carlson war frustriert vom Abschreiben von Patenten und erfand deshalb die Trockenkopie.
C H | Welcher Deutsche erfand 1885 das erste Motorrad, den „Reitwagen“? | Gottlieb Daimler | Carl Benz ; Nikolaus Otto ; Rudolf Diesel | Er arbeitete in Cannstatt. ; Sein Partner hieß Maybach. ; Er baute den schnell laufenden Benzinmotor. | Der Reitwagen hatte ein Holzgestell und zwei Stützräder.
C H | Wer entwickelte 1796 die erste Pockenimpfung? | Edward Jenner | Louis Pasteur ; Robert Koch ; Ignaz Semmelweis | Er war ein englischer Landarzt. ; Er nutzte harmlose Kuhpocken. ; „Vakzin“ kommt von lateinisch „vacca“, Kuh. | 1980 erklärte die WHO die Pocken für ausgerottet.
C H | Welcher britische Chirurg führte um 1867 mit Karbolsäure die antiseptische Wundbehandlung ein? | Joseph Lister | Edward Jenner ; Alexander Fleming ; John Snow | Ein Mundwasser ist nach ihm benannt. ; Er inspirierte sich an Pasteurs Keimtheorie. ; Sein Nachname beginnt mit L. | Das Mundwasser „Listerine“ trägt seinen Namen.
C H | Welcher Italiener erfand 1800 die erste Batterie? | Alessandro Volta | Luigi Galvani ; Guglielmo Marconi ; Enrico Fermi | Die Einheit der Spannung heißt nach ihm. ; Er stapelte Zink- und Kupferscheiben. ; Man nennt es seine „Säule“. | Die Voltasche Säule lieferte erstmals dauerhaften elektrischen Strom.
C U | Welcher Schotte führte 1926 in London erstmals ein funktionierendes Fernsehsystem vor? | John Logie Baird | Alexander Graham Bell ; James Watt ; Philo Farnsworth | Er nutzte eine mechanische Nipkow-Scheibe. ; Er stammte aus Helensburgh. ; Er hatte zwei Vornamen. | Baird zeigte am 26. Januar 1926 bewegte Bilder; die elektronische Bildröhre setzte sich später durch.
C U | Wer erfand 1884 die Nipkow-Scheibe, die Grundlage des mechanischen Fernsehens? | Paul Nipkow | Karl Ferdinand Braun ; Manfred von Ardenne ; Heinrich Hertz | Die Scheibe trägt seinen Namen. ; Er war Student in Berlin. ; Er stammte aus Lauenburg in Pommern. | Die Nipkow-Scheibe tastete Bilder mit spiralförmig angeordneten Löchern ab.
C U | Welcher deutsche Physiker erfand 1897 die Kathodenstrahlröhre, die Bildröhre alter Fernseher? | Karl Ferdinand Braun | Paul Nipkow ; Wilhelm Röntgen ; Max Planck | Die Röhre trägt seinen Namen. ; Er erhielt 1909 mit Marconi den Physik-Nobelpreis. ; Sein Nachname ist auch eine Farbe. | In Deutschland nennt man die Bildröhre bis heute „braunsche Röhre“.
C U | Wer erfand 1903 den Scheibenwischer? | Mary Anderson | Bertha Benz ; Henry Ford ; Margaret Knight | Sie war eine Amerikanerin aus Alabama. ; Auf einer Straßenbahnfahrt in New York kam ihr die Idee. ; Sie war eine Frau. | Mary Anderson erhielt 1903 das Patent; erst Jahre später wurden Wischer Standard.
W E | Der Phonograph, mit dem man Töne aufnehmen und abspielen konnte, wurde von Alexander Graham Bell erfunden. | falsch | Thomas Edison stellte den Phonographen 1877 vor und sprach „Mary had a little lamb“ hinein.
W M | Das Fahrrad mit Pedalen wurde vor der Laufmaschine erfunden. | falsch | Die Laufmaschine von Karl Drais (1817) kam zuerst; Pedale am Vorderrad folgten in den 1860ern.
W H | Der Klettverschluss wurde nach dem Vorbild von Klettenfrüchten erfunden, die im Hundefell hängen blieben. | wahr | Der Schweizer George de Mestral untersuchte nach einem Spaziergang die Kletten unter dem Mikroskop und ließ sich 1951 den Klettverschluss patentieren.
W H | Das Rad wurde zuerst als Transportmittel, lange vor der Töpferscheibe, erfunden. | falsch | Die Töpferscheibe ist nach heutigem Wissen älter als das Wagenrad.
S M | In welchem Jahr gelang den Brüdern Wright der erste Motorflug? | 1903 | Jahr | 2 | 1850 | 1950 | Anfang des 20. Jahrhunderts. ; Elf Jahre vor dem Ersten Weltkrieg. ; Das Jahr endet auf 3. | Der erste Flug am 17. Dezember 1903 dauerte zwölf Sekunden.
S H | In welchem Jahr veröffentlichte Charles Darwin „Über die Entstehung der Arten“? | 1859 | Jahr | 3 | 1750 | 1950 | Mitte des 19. Jahrhunderts. ; Zwei Jahre vor dem US-Bürgerkrieg. ; Das Jahr endet auf 9. | Die erste Auflage von 1250 Exemplaren war am ersten Tag vergriffen.
O M | Sortiere diese Erfindungen chronologisch — die älteste zuerst. | Buchdruck (Gutenberg) = um 1450 ; Dampfmaschine (Watt) = 1769 ; Telefon (Bell) = 1876 ; Internet (WWW) = 1989 | Die erste stammt aus dem Mittelalter. ; Die zweite leitete die Industrialisierung ein. ; Das World Wide Web kam zuletzt. | Watt erhielt 1769 sein Patent auf die verbesserte Dampfmaschine.
O H | Sortiere diese Transportmittel nach ihrer Erfindung — das älteste zuerst. | Heißluftballon = 1783 ; Dampflokomotive = 1804 ; Automobil (Benz) = 1886 ; Motorflugzeug (Wright) = 1903 | Die erste Erfindung schwebte über Frankreich. ; Die zweite fuhr auf Schienen in Wales. ; Das Flugzeug kam zuletzt. | Richard Trevithicks Dampflok fuhr 1804 im walisischen Penydarren.
M M | Welche ZWEI dieser Erfindungen stammen von Deutschen? | Buchdruck mit beweglichen Lettern ; Automobil mit Verbrennungsmotor | Telefon ; Glühbirne ; Dynamit ; Penicillin | Eine entstand in Mainz. ; Die andere in Mannheim. ; Bell, Edison, Nobel und Fleming waren keine Deutschen. | Gutenberg (Mainz) und Carl Benz (Mannheim) veränderten die Welt.

@ biologie_koerper
C H | Wie heißt die Kniescheibe in der medizinischen Fachsprache? | Patella | Tibia ; Scapula ; Fibula | Sie ist ein sogenanntes Sesambein. ; Das Wort bedeutet „kleine Schüssel“. ; Der Reflex mit dem Hämmerchen trägt ihren Namen. | Beim Patellarsehnenreflex schnellt das Bein nach einem Schlag unterhalb der Kniescheibe nach vorn.
C E | Mit welchem Gerät misst man die Temperatur? | Thermometer | Barometer ; Tachometer ; Hygrometer | „Thermo“ bedeutet Wärme. ; Man steckt es bei Fieber unter die Zunge. ; Früher enthielt es oft Quecksilber. | Quecksilber-Fieberthermometer sind in der EU seit 2009 verboten.
C H | Wie heißt der Teil des Auges, der seine Farbe bestimmt? | Iris | Pupille ; Netzhaut ; Hornhaut | Sie heißt auch Regenbogenhaut. ; Sie umgibt die Pupille. ; Eine griechische Göttin des Regenbogens trägt den Namen. | Die Iris regelt wie eine Blende, wie viel Licht ins Auge fällt.
W E | Das Herz ist ein Muskel. | wahr | Der Herzmuskel arbeitet unermüdlich und schlägt rund 100.000-mal am Tag.
W M | Menschen haben mehr Haare auf dem Kopf als eine Katze auf dem ganzen Körper. | falsch | Menschen haben rund 100.000 Kopfhaare, eine Katze Millionen von Haaren im Fell.
S H | Wie viele Liter Luft fasst die Lunge eines Erwachsenen ungefähr maximal? | 6 | Liter | 25 | 1 | 20 | Mehr als eine große Wasserflasche. ; Weniger als zehn. ; Etwa ein halber Putzeimer. | Die Totalkapazität liegt bei etwa 6 Litern; bei einem ruhigen Atemzug bewegt man nur rund einen halben Liter.
O M | Sortiere diese Knochen nach ihrer Länge — den kürzesten zuerst. | Steigbügel (Ohr) = ≈ 3 mm ; Schlüsselbein = ≈ 15 cm ; Oberarmknochen = ≈ 33 cm ; Oberschenkelknochen = ≈ 45 cm | Der kürzeste sitzt im Ohr. ; Das Schlüsselbein ist kürzer als die Armknochen. ; Der längste steckt im Bein. | Der Oberschenkelknochen ist der längste und stärkste Knochen des Körpers.
M M | Welche ZWEI dieser Organe gibt es im menschlichen Körper paarweise? | Niere ; Lunge | Herz ; Leber ; Milz ; Magen | Beide liegen links und rechts. ; Eines atmet. ; Das andere filtert Blut. | Man kann mit einer Niere gut leben — darum sind Lebendspenden möglich.

@ mathe_logik
C E | Wie viele Ecken hat ein Sechseck? | 6 | 5 ; 8 ; 7 | Bienenwaben haben diese Form. ; Der Name verrät es. ; Mehr als ein Fünfeck. | Das regelmäßige Sechseck lässt sich lückenlos zu einer Fläche legen — wie in einer Bienenwabe.
C M | Wie heißt eine Zahl, die sich vorwärts wie rückwärts gleich liest, etwa 12321? | Zahlenpalindrom | Primzahl ; Quadratzahl ; Kubikzahl | Das Wort „Anna“ ist ein Beispiel bei Wörtern. ; Es kommt aus dem Griechischen: „zurücklaufend“. ; Auch das Wort „Reliefpfeiler“ ist eines. | Jede einstellige Zahl ist ein Palindrom, genau wie 11 oder 121.
C M | Wie nennt man ein Dreieck mit genau zwei gleich langen Seiten? | Gleichschenklig | Gleichseitig ; Rechtwinklig ; Stumpfwinklig | Die zwei gleichen Seiten heißen Schenkel. ; Die dritte Seite ist die Basis. ; Das Wort beschreibt die Schenkel. | Im gleichschenkligen Dreieck sind auch die beiden Basiswinkel gleich groß.
C H | Welches Jahr ergibt die römische Zahl MCMLXXXIV? | 1984 | 1964 ; 1989 ; 1994 | MCM steht für 1900. ; LXXX ist 80. ; IV ist 4. | M (1000) + CM (900) + L (50) + XXX (30) + IV (4) = 1984.
W M | Jede Quadratzahl hat eine ungerade Anzahl an Teilern. | wahr | Teiler kommen in Paaren vor — nur bei Quadratzahlen fällt ein Paar zusammen, etwa 4 = 2 × 2.
S U | Wie viele Diagonalen hat ein Zehneck? | 35 | Diagonalen | 20 | 5 | 100 | Die Formel lautet n·(n−3)/2. ; 10 mal 7 geteilt durch 2. ; Mehr als 30. | Jede Ecke verbindet sich mit sieben anderen, jede Diagonale zählt man dabei doppelt: 10·7/2 = 35.
O E | Sortiere diese Zahlen aufsteigend — die kleinste zuerst. | Ein Dutzend = 12 ; Ein Schock = 60 ; Ein Gros = 144 ; Tausend = 1000 | Ein Dutzend ist die kleinste. ; Ein Schock sind fünf Dutzend. ; Ein Gros ist ein Dutzend Dutzend. | Schock und Gros sind alte Zähleinheiten — ein Gros sind 12 mal 12.
M M | Welche ZWEI dieser Zahlen sind Quadratzahlen? | 81 ; 144 | 50 ; 90 ; 120 ; 200 | Eine ist neun mal neun. ; Die andere ein Gros. ; Die Wurzeln sind ganze Zahlen. | 81 = 9², 144 = 12²; die anderen haben keine ganzzahlige Wurzel.

@ weltraum_astronomie
C M | Welcher Planet hat die kürzeste Umlaufzeit um die Sonne? | Merkur | Venus ; Mars ; Erde | Er ist der kleinste Planet. ; Er ist nach dem Götterboten benannt. ; Er ist der Sonne am nächsten. | Merkur umrundet die Sonne in nur 88 Erdtagen.
C M | Wie heißt der größte Mond des Saturns? | Titan | Europa ; Ganymed ; Triton | Er hat eine dichte Atmosphäre. ; Dort gibt es Seen aus Methan. ; Der Name klingt nach Riesen der Mythologie. | Die Sonde Huygens landete 2005 auf dem Titan.
C H | Welcher Astronom stellte 1543 das heliozentrische Weltbild vor? | Nikolaus Kopernikus | Galileo Galilei ; Johannes Kepler ; Tycho Brahe | Er stammte aus Thorn. ; Sein Werk erschien kurz vor seinem Tod. ; Er war Domherr in Frauenburg. | „De revolutionibus orbium coelestium“ setzte die Sonne ins Zentrum des Planetensystems.
W E | Auf dem Mond gibt es keine Schwerkraft. | falsch | Die Schwerkraft auf dem Mond beträgt etwa ein Sechstel der Erdanziehung.
S M | Wie viele Tage braucht der Mond ungefähr, um von Vollmond zu Vollmond zu kommen? | 29.5 | Tage | 5 | 10 | 60 | Etwa ein Monat. ; Das Wort Monat kommt von Mond. ; Knapp 30. | Ein synodischer Monat dauert 29,53 Tage.
O M | Sortiere diese Planeten nach ihrer Größe — den kleinsten zuerst. | Merkur = ≈ 4.900 km ; Mars = ≈ 6.800 km ; Erde = ≈ 12.700 km ; Jupiter = ≈ 140.000 km | Der kleinste ist der sonnennächste. ; Der Rote Planet ist kleiner als die Erde. ; Der Gasriese ist der größte. | Jupiter hat mehr als elfmal den Durchmesser der Erde.
M M | Welche ZWEI dieser Himmelskörper sind Gasplaneten? | Jupiter ; Saturn | Mars ; Venus ; Merkur ; Mond | Beide sind riesig. ; Einer hat auffällige Ringe. ; Der andere einen großen roten Fleck. | Jupiter und Saturn bestehen vor allem aus Wasserstoff und Helium.

@ alltagswissenschaft
C E | Welches Organ nutzt der Mensch vor allem zum Atmen? | Lunge | Leber ; Milz ; Niere | Sie hat zwei Flügel. ; Sie sitzt im Brustkorb. ; Raucher schädigen sie. | Die Lunge hat eine Oberfläche von rund 100 Quadratmetern — etwa so viel wie eine Wohnung.
C M | Warum kocht Wasser auf der Zugspitze schon unter 100 °C? | Der Luftdruck ist niedriger | Die Luft ist kälter ; Es gibt weniger Sauerstoff ; Das Wasser ist weicher | Es hat mit der Höhe zu tun. ; Mit dem Barometer kann man es messen. ; Auf dem Mount Everest siedet es schon bei etwa 70 °C. | Je geringer der Luftdruck, desto niedriger der Siedepunkt — auf 2962 Metern etwa bei 90 °C.
W E | Ein frisches Ei sinkt in einem Glas Wasser zu Boden, ein sehr altes schwimmt oben. | wahr | Mit der Zeit verdunstet Wasser durch die Schale und die Luftkammer wächst — alte Eier bekommen Auftrieb.
W M | Ein Kilogramm Eis nimmt mehr Platz ein als ein Kilogramm flüssiges Wasser. | wahr | Wasser dehnt sich beim Gefrieren um etwa neun Prozent aus — deshalb schwimmt Eis und Flaschen im Gefrierfach platzen.
S M | Wie viele Liter sollte ein Erwachsener laut Deutscher Gesellschaft für Ernährung täglich ungefähr trinken? | 1.5 | Liter | 30 | 0.1 | 10 | Mehr als ein Liter. ; Etwa sechs große Gläser. ; Weniger als zwei. | Die DGE empfiehlt rund 1,5 Liter am Tag — bei Hitze oder Sport mehr.
O E | Sortiere diese Temperaturen — die kälteste zuerst. | Gefrierfach = −18 °C ; Kühlschrank = 7 °C ; Körpertemperatur = 37 °C ; Kochendes Wasser = 100 °C | Das Kälteste steckt im Eisfach. ; Der Kühlschrank ist knapp über null. ; Siedendes Wasser ist am heißesten. | Tiefkühlkost soll bei −18 °C oder kälter gelagert werden.
M M | Welche ZWEI dieser Stoffe leiten Strom gut? | Kupfer ; Salzwasser | Holz ; Gummi ; Glas ; Plastik | Einer ist ein Metall für Kabel. ; Der andere ist flüssig und salzig. ; Isolatoren scheiden aus. | Salzwasser leitet, weil gelöste Ionen den Strom transportieren.
@ weltraum_astronomie
O E | Sortiere diese Planeten nach ihrer Entfernung von der Sonne — den nächsten zuerst. | Merkur = 1. Planet ; Venus = 2. Planet ; Erde = 3. Planet ; Mars = 4. Planet | Der kleinste ist der innerste. ; Die Venus liegt zwischen Merkur und Erde. ; Der Rote Planet ist der äußerste der vier. | Merkspruch: „Mein Vater erklärt mir jeden Sonntag unseren Nachthimmel.“
M H | Welche ZWEI dieser Planeten haben keinen Mond? | Merkur ; Venus | Erde ; Mars ; Jupiter ; Neptun | Beide liegen innerhalb der Erdbahn. ; Einer ist der sonnennächste. ; Der andere ist der heißeste. | Der Mars hat zwei kleine Monde, Phobos und Deimos.

@ physik_chemie
O M | Sortiere diese Einheitenvorsätze nach ihrer Größe — den kleinsten zuerst. | Milli = 10⁻³ ; Kilo = 10³ ; Mega = 10⁶ ; Giga = 10⁹ | Der kleinste steckt im Millimeter. ; Kilo bedeutet tausend. ; Giga kennt man von Speicherkarten. | Danach folgen Tera, Peta und Exa.
O U | Sortiere diese Elemente nach ihrer Ordnungszahl — die kleinste zuerst. | Wasserstoff = 1 ; Kohlenstoff = 6 ; Eisen = 26 ; Gold = 79 | Das leichteste Element beginnt. ; Das Element des Lebens folgt. ; Das Edelmetall hat die höchste Zahl. | Die Ordnungszahl entspricht der Zahl der Protonen im Kern.
C U | Welches Element hat das chemische Symbol W? | Wolfram | Wasserstoff ; Wismut ; Vanadium | Der Name leitet sich vom schwedischen „Tungsten“ bzw. dem Mineral Wolframit ab. ; Es hat den höchsten Schmelzpunkt aller Metalle. ; Früher steckte es in Glühfäden. | Im Englischen heißt Wolfram „tungsten“ — „schwerer Stein“ auf Schwedisch.
C U | Wie heißt die SI-Einheit der Lichtstärke? | Candela | Lux ; Lumen ; Watt | Der Name ist lateinisch für Kerze. ; Eine Kerze strahlt etwa eine davon ab. ; Sie beginnt mit C. | Lumen misst den Lichtstrom, Lux die Beleuchtungsstärke, Candela die Lichtstärke.
M U | Welche ZWEI dieser Wissenschaftler erhielten zwei Nobelpreise? | Marie Curie ; Linus Pauling | Albert Einstein ; Max Planck ; Niels Bohr ; Wilhelm Röntgen | Eine davon bekam Physik und Chemie. ; Der andere Chemie und Frieden. ; Einstein bekam nur einen. | Auch John Bardeen und Frederick Sanger erhielten je zwei Nobelpreise.

@ biologie_koerper
C E | Wie nennt man Tiere, die sich nur von Pflanzen ernähren? | Pflanzenfresser | Fleischfresser ; Allesfresser ; Aasfresser | Kühe und Kaninchen gehören dazu. ; Der Fachbegriff lautet Herbivoren. ; Sie fressen kein Fleisch. | Menschen und Bären sind dagegen Allesfresser.
M E | Welche ZWEI dieser Tiere sind Säugetiere? | Wal ; Fledermaus | Hai ; Pinguin ; Krokodil ; Frosch | Eines lebt im Meer, atmet aber Luft. ; Das andere fliegt nachts. ; Fisch, Vogel, Reptil und Amphibie scheiden aus. | Säugetiere säugen ihre Jungen mit Milch.
S U | Aus wie vielen Knochen besteht ein menschlicher Fuß? | 26 | Knochen | 10 | 5 | 60 | Mehr als 20. ; Beide Füße zusammen haben über 50. ; Weniger als 30. | Rund ein Viertel aller Knochen des Körpers steckt in den Füßen.
"""
