import Foundation

/// Core UI strings (onboarding, tabs, home, settings, servers, errors).
/// Feature-specific strings live in ChatL10n / GamesL10n / MemoriesL10n.
enum CoreStrings {
    static let table: [String: LText] = [
        // Common
        "common.ok": LText(de: "OK", en: "OK"),
        "common.cancel": LText(de: "Abbrechen", en: "Cancel"),
        "common.save": LText(de: "Speichern", en: "Save"),
        "common.delete": LText(de: "Löschen", en: "Delete"),
        "common.edit": LText(de: "Bearbeiten", en: "Edit"),
        "common.done": LText(de: "Fertig", en: "Done"),
        "common.retry": LText(de: "Nochmal versuchen", en: "Retry"),
        "common.close": LText(de: "Schließen", en: "Close"),
        "common.add": LText(de: "Hinzufügen", en: "Add"),
        "common.error": LText(de: "Ups, das hat nicht geklappt", en: "Oops, that didn't work"),
        "common.loading": LText(de: "Lädt…", en: "Loading…"),
        "common.back": LText(de: "Zurück", en: "Back"),
        "common.share": LText(de: "Teilen", en: "Share"),
        "common.copy": LText(de: "Kopieren", en: "Copy"),
        "common.copied": LText(de: "Kopiert!", en: "Copied!"),
        "common.today": LText(de: "Heute", en: "Today"),
        "common.days": LText(de: "Tage", en: "days"),
        "common.day": LText(de: "Tag", en: "day"),

        // Compact relative times (see L10n.relativeShort)
        "time.justNow": LText(de: "gerade eben", en: "just now"),
        "time.minutesAgo": LText(de: "vor {n} Min.", en: "{n} min ago"),
        "time.hoursAgo": LText(de: "vor {n} Std.", en: "{n} h ago"),
        "time.yesterday": LText(de: "gestern", en: "yesterday"),
        "time.daysAgo": LText(de: "vor {n} Tagen", en: "{n} days ago"),
        "common.you": LText(de: "Du", en: "You"),
        "common.partner": LText(de: "Schatz", en: "Sweetheart"),
        "common.send": LText(de: "Senden", en: "Send"),

        // Tabs
        "tab.home": LText(de: "Zuhause", en: "Home"),
        "tab.chat": LText(de: "Chat", en: "Chat"),
        "tab.play": LText(de: "Spielen", en: "Play"),
        "tab.us": LText(de: "Wir", en: "Us"),
        "tab.more": LText(de: "Mehr", en: "More"),
        "tab.chat.unreadA11y": LText(de: "Chat, {n} ungelesen", en: "Chat, {n} unread"),

        // Onboarding
        "onboarding.title": LText(de: "SoooDreamy", en: "SoooDreamy"),
        "onboarding.tagline": LText(de: "Die App für euch zwei. Euer Server, eure Daten, eure Welt. 💜",
                                    en: "The app for the two of you. Your server, your data, your world. 💜"),
        "onboarding.feature1": LText(de: "Herzklopfen senden — mit echter Haptik", en: "Send heartbeats — with real haptics"),
        "onboarding.feature2": LText(de: "Chat, Fotos, Sprachnachrichten & Kritzel-Canvas", en: "Chat, photos, voice notes & doodle canvas"),
        "onboarding.feature3": LText(de: "Spiele, Fragen des Tages & Date-Ideen", en: "Games, daily questions & date ideas"),
        "onboarding.feature4": LText(de: "Widgets & Live-Countdowns für eure Momente", en: "Widgets & live countdowns for your moments"),
        "onboarding.start": LText(de: "Los geht's", en: "Let's go"),

        // Intro cutscene (first launch, replayable from About)
        "intro.skip": LText(de: "Überspringen", en: "Skip"),
        "intro.tagline": LText(de: "Die App für euch zwei.", en: "The app for the two of you."),
        "intro.promise1": LText(de: "Jeden Tag ein kleiner Impuls für euch.", en: "A little nudge for the two of you, every day."),
        "intro.promise2": LText(de: "Nachrichten, die nur euch gehören.", en: "Messages that belong to you alone."),
        "intro.promise3": LText(de: "Erinnerungen, die bleiben.", en: "Memories that stay."),
        "intro.privacy": LText(de: "Eure Daten liegen auf eurem eigenen Server — bei niemandem sonst.",
                               en: "Your data lives on your own server — with no one else."),
        "intro.a11y": LText(de: "Intro: Zwei Menschen finden zusammen, ein Herz erscheint. Tippen zum Überspringen.",
                            en: "Intro: two people come together, a heart appears. Tap to skip."),

        // Couple cutscenes
        "cutscene.paired.title": LText(de: "Ihr seid verbunden", en: "You're connected"),
        "cutscene.paired.subtitle": LText(de: "{a} & {b} — zusammen seit heute.", en: "{a} & {b} — together since today."),
        "cutscene.milestone.title": LText(de: "Tag {n}", en: "Day {n}"),
        "cutscene.milestone.subtitle": LText(de: "{n} Tage zusammen, {a} & {b}. Und immer noch ihr.",
                                             en: "{n} days together, {a} & {b}. And still the two of you."),

        // What's new
        "whatsnew.title": LText(de: "Neu in SoooDreamy", en: "What's New in SoooDreamy"),
        "whatsnew.version": LText(de: "Version {v}", en: "Version {v}"),
        "whatsnew.f1.title": LText(de: "Ganz neu gestaltet", en: "Redesigned from the ground up"),
        "whatsnew.f1.body": LText(de: "Liquid Glass, große Titel, echte System-Listen — SoooDreamy fühlt sich an wie eine App von Apple.",
                                  en: "Liquid Glass, large titles, real system lists — SoooDreamy feels like an app made by Apple."),
        "whatsnew.f2.title": LText(de: "Erinnerungen wie in Fotos", en: "Memories like Photos"),
        "whatsnew.f2.body": LText(de: "Galerie mit Auswählen-Modus, Zeitlinie, Highlights und Tagebuch-Suche.",
                                  en: "Gallery with select mode, timeline, highlights and journal search."),
        "whatsnew.f3.title": LText(de: "Spiele in neuem Gewand", en: "Games, refreshed"),
        "whatsnew.f3.body": LText(de: "Alle 16 Spiele auf gemeinsamen Bausteinen — klarer, schneller, fairer.",
                                  en: "All 16 games on shared building blocks — clearer, faster, fairer."),
        "whatsnew.f4.title": LText(de: "Statistiken mit Swift Charts", en: "Stats with Swift Charts"),
        "whatsnew.f4.body": LText(de: "Eure Berührungen und Stimmungen als echte Diagramme.",
                                  en: "Your touches and moods as real charts."),
        "whatsnew.f5.title": LText(de: "Koppeln per Kamera", en: "Pair with the camera"),
        "whatsnew.f5.body": LText(de: "Der QR-Scan nutzt jetzt Apples eigenen Scanner.",
                                  en: "QR scanning now uses Apple's own scanner."),
        "about.whatsNew": LText(de: "Was ist neu", en: "What's New"),
        "about.replayIntro": LText(de: "Intro ansehen", en: "Watch the intro"),
        "onboarding.language": LText(de: "Sprache", en: "Language"),
        "language.system": LText(de: "System", en: "System"),
        "language.de": LText(de: "Deutsch", en: "German"),
        "language.en": LText(de: "Englisch", en: "English"),

        // Server setup
        "server.setupTitle": LText(de: "Euer Server", en: "Your server"),
        "server.setupSubtitle": LText(de: "SoooDreamy läuft auf eurem eigenen kleinen Server — zuhause, auf einem Raspberry Pi oder in der Cloud. Tragt hier seine Adresse ein.",
                                      en: "SoooDreamy runs on your own little server — at home, on a Raspberry Pi or in the cloud. Enter its address here."),
        "server.name": LText(de: "Name (z. B. „Zuhause“)", en: "Name (e.g. “Home”)"),
        "server.url": LText(de: "Adresse, z. B. 192.168.1.20:4321", en: "Address, e.g. 192.168.1.20:4321"),
        "server.test": LText(de: "Verbindung testen", en: "Test connection"),
        "server.testOK": LText(de: "Verbunden! {name} ({version})", en: "Connected! {name} ({version})"),
        "server.testFail": LText(de: "Keine Verbindung: {error}", en: "No connection: {error}"),
        "server.testFailATS": LText(de: "Öffentliche Server brauchen HTTPS. http:// ist nur für private LAN-, Loopback- oder Tailscale-Adressen erlaubt; starte den LAN-Server zusätzlich mit ALLOW_HTTP_PRIVATE_LAN=1.",
                                    en: "Public servers require HTTPS. http:// is allowed only for private LAN, loopback, or Tailscale addresses; also start the LAN server with ALLOW_HTTP_PRIVATE_LAN=1."),
        "server.invalidURL": LText(de: "Das sieht nicht wie eine gültige Adresse aus", en: "That doesn't look like a valid address"),
        "server.buildBadge": LText(de: "App-Build {version} · HTTPS geschützt", en: "App build {version} · HTTPS protected"),
        "server.add": LText(de: "Server hinzufügen", en: "Add server"),
        "server.manage": LText(de: "Server verwalten", en: "Manage servers"),
        "server.active": LText(de: "Aktiv", en: "Active"),
        "server.switch": LText(de: "Zu diesem Server wechseln", en: "Switch to this server"),
        "server.switched": LText(de: "Server gewechselt: {name}", en: "Switched server: {name}"),
        "server.delete": LText(de: "Server entfernen", en: "Remove server"),
        "server.deleteConfirm": LText(de: "„{name}“ wirklich entfernen? Die Kopplung auf diesem Server geht auf diesem Gerät verloren.",
                                      en: "Really remove “{name}”? Your pairing on that server will be lost on this device."),
        "server.paired": LText(de: "Gekoppelt", en: "Paired"),
        "server.notPaired": LText(de: "Noch nicht gekoppelt", en: "Not paired yet"),
        "server.hint": LText(de: "Öffentlich: https:// verwenden. Privat im LAN/Tailscale ist http:// möglich, wenn der Server ausdrücklich mit ALLOW_HTTP_PRIVATE_LAN=1 gestartet wurde.",
                             en: "Public server: use https://. Private LAN/Tailscale may use http:// when the server was explicitly started with ALLOW_HTTP_PRIVATE_LAN=1."),
        "server.continue": LText(de: "Weiter", en: "Continue"),
        "server.pickTitle": LText(de: "Mit welchem Server?", en: "Which server?"),

        // Pairing
        "pairing.title": LText(de: "Findet zueinander", en: "Find each other"),
        "pairing.subtitle": LText(de: "Eine:r von euch erstellt euer Paar, die/der andere tritt mit dem Code bei.",
                                  en: "One of you creates your couple, the other joins with the code."),
        "pairing.create": LText(de: "Paar erstellen", en: "Create couple"),
        "pairing.join": LText(de: "Mit Code beitreten", en: "Join with code"),
        "pairing.codePlaceholder": LText(de: "Code, z. B. H4XK9P", en: "Code, e.g. H4XK9P"),
        "pairing.yourCode": LText(de: "Euer Code", en: "Your code"),
        "pairing.shareCode": LText(de: "Schick den Code deinem Schatz 💌", en: "Send the code to your sweetheart 💌"),
        "pairing.waiting": LText(de: "Warte auf deinen Schatz…", en: "Waiting for your sweetheart…"),
        "pairing.scanQR": LText(de: "QR-Code scannen", en: "Scan QR code"),
        "pairing.scan.unavailable.title": LText(de: "Kamera nicht verfügbar", en: "Camera unavailable"),
        "pairing.scan.unavailable.body": LText(de: "Erlaube SoooDreamy in den Einstellungen den Kamerazugriff, um den Paar-Code zu scannen — oder gib den 6-stelligen Code einfach ein.",
                                              en: "Allow SoooDreamy to use the camera in Settings to scan the pairing code — or just type the 6-digit code."),
        "pairing.scan.openSettings": LText(de: "Einstellungen öffnen", en: "Open Settings"),
        "pairing.showQR": LText(de: "QR-Code zeigen", en: "Show QR code"),
        "pairing.partnerJoined": LText(de: "{name} ist da! 🎉", en: "{name} joined! 🎉"),
        "pairing.unknownCode": LText(de: "Diesen Code kennt der Server nicht", en: "The server doesn't know this code"),
        "pairing.coupleFull": LText(de: "Dieses Paar ist schon komplett", en: "This couple is already complete"),
        "pairing.yourName": LText(de: "Dein Name", en: "Your name"),
        "pairing.avatar": LText(de: "Dein Emoji", en: "Your emoji"),
        "pairing.color": LText(de: "Deine Farbe", en: "Your color"),
        "pairing.profileTitle": LText(de: "Das bist du", en: "This is you"),
        "pairing.qrHint": LText(de: "Dein Schatz kann den Code auch scannen — Server & Code in einem.",
                                en: "Your sweetheart can also scan the code — server & code in one."),

        // Home / dashboard
        "home.daysTogether": LText(de: "Tage zusammen", en: "days together"),
        "home.sinceHint": LText(de: "Jahrestag in den Einstellungen setzen", en: "Set your anniversary in settings"),
        "home.online": LText(de: "online", en: "online"),
        "home.offline": LText(de: "offline", en: "offline"),
        "home.lastSeen": LText(de: "zuletzt {time}", en: "last seen {time}"),
        "home.yourMood": LText(de: "Deine Stimmung", en: "Your mood"),
        "home.moodOf": LText(de: "{name} fühlt sich…", en: "{name} is feeling…"),
        "home.noMood": LText(de: "Noch keine Stimmung geteilt", en: "No mood shared yet"),
        "home.setMood": LText(de: "Stimmung teilen", en: "Share mood"),
        "home.moodNote": LText(de: "Kleine Notiz dazu? (optional)", en: "A little note? (optional)"),
        "home.sendLove": LText(de: "Schick Liebe", en: "Send love"),
        "home.dailyQuestion": LText(de: "Frage des Tages", en: "Question of the day"),
        "home.answerNow": LText(de: "Jetzt antworten", en: "Answer now"),
        "home.waitingPartnerAnswer": LText(de: "Warte auf {name}s Antwort…", en: "Waiting for {name}'s answer…"),
        "home.bothAnswered": LText(de: "Ihr habt beide geantwortet! 💞", en: "You both answered! 💞"),
        "home.shareAnswers": LText(de: "Antworten in den Chat 💬", en: "Send answers to chat 💬"),
        "home.dailyShareHeader": LText(de: "❓ Frage des Tages:", en: "❓ Question of the day:"),
        "home.streak": LText(de: "{n}er-Serie", en: "{n}-day streak"),
        "home.nextEvent": LText(de: "Als Nächstes", en: "Up next"),
        "home.inDays": LText(de: "in {n} Tagen", en: "in {n} days"),
        "home.tomorrow": LText(de: "morgen!", en: "tomorrow!"),
        "home.todayBang": LText(de: "HEUTE! 🎉", en: "TODAY! 🎉"),
        "home.waitingForPartner": LText(de: "Euer Nest ist fast fertig", en: "Your nest is almost ready"),
        "home.waitingForPartnerSub": LText(de: "Teile den Code mit deinem Schatz, dann geht's los:",
                                           en: "Share the code with your sweetheart to get started:"),
        "home.touchSent": LText(de: "Gesendet! {emoji}", en: "Sent! {emoji}"),
        "home.heartTapHint": LText(de: "Tipp aufs Herz, um Herzklopfen zu senden", en: "Tap the heart to send a heartbeat"),

        // Touches
        "touch.heartbeat": LText(de: "Herzklopfen", en: "Heartbeat"),
        "touch.kiss": LText(de: "Kuss", en: "Kiss"),
        "touch.hug": LText(de: "Umarmung", en: "Hug"),
        "touch.missyou": LText(de: "Vermiss dich", en: "Miss you"),
        "touch.tickle": LText(de: "Kitzeln", en: "Tickle"),
        "touch.thinking": LText(de: "Denk an dich", en: "Thinking of you"),
        "touch.received.heartbeat": LText(de: "{name} schickt dir Herzklopfen", en: "{name} sends you a heartbeat"),
        "touch.received.kiss": LText(de: "{name} küsst dich", en: "{name} kisses you"),
        "touch.received.hug": LText(de: "{name} umarmt dich ganz fest", en: "{name} hugs you tight"),
        "touch.received.missyou": LText(de: "{name} vermisst dich", en: "{name} misses you"),
        "touch.received.tickle": LText(de: "{name} kitzelt dich", en: "{name} tickles you"),
        "touch.received.thinking": LText(de: "{name} denkt gerade an dich", en: "{name} is thinking of you"),
        // Floating 💭 quick action on the dashboard (v1.5.3)
        "home.thinkingFabA11y": LText(de: "„Denk an dich“ senden", en: "Send a “thinking of you”"),

        // Settings
        "settings.title": LText(de: "Mehr", en: "More"),
        "settings.profile": LText(de: "Dein Profil", en: "Your profile"),
        "settings.couple": LText(de: "Euer Paar", en: "Your couple"),
        "settings.coupleName": LText(de: "Name eures Paars", en: "Couple name"),
        "settings.anniversary": LText(de: "Jahrestag", en: "Anniversary"),
        "settings.anniversaryHint": LText(de: "Seit wann seid ihr zusammen?", en: "Since when are you together?"),
        "settings.language": LText(de: "Sprache", en: "Language"),
        "settings.sounds": LText(de: "Sounds", en: "Sounds"),
        "settings.soundvol.title": LText(de: "Lautstärke pro Kategorie", en: "Volume per category"),
        "settings.soundvol.moments": LText(de: "Momente", en: "Moments"),
        "settings.soundvol.chat": LText(de: "Chat", en: "Chat"),
        "settings.soundvol.games": LText(de: "Spiele", en: "Games"),
        "settings.soundvol.ui": LText(de: "Interface", en: "Interface"),
        "settings.haptics": LText(de: "Haptik", en: "Haptics"),
        "settings.reminder": LText(de: "Tägliche Erinnerung", en: "Daily reminder"),
        "settings.reminderHint": LText(de: "Erinnert euch abends an die Frage des Tages", en: "Evening nudge for the question of the day"),
        "settings.reminderTime": LText(de: "Uhrzeit", en: "Time"),
        "settings.streakGuard": LText(de: "Serien-Schutz", en: "Streak guard"),
        "settings.streakGuardHint": LText(de: "Zweite Erinnerung um 21:30, wenn eure Antwort-Serie in Gefahr ist",
                                          en: "Second reminder at 9:30 pm when your answer streak is at risk"),
        "settings.unpair": LText(de: "Paar auflösen", en: "Dissolve couple"),
        "settings.unpairConfirm": LText(de: "Wirklich? Das löscht ALLE eure Daten auf dem Server — Chats, Fotos, alles. Das kann nicht rückgängig gemacht werden.",
                                        en: "Really? This deletes ALL your data on the server — chats, photos, everything. This cannot be undone."),
        "settings.leaveDevice": LText(de: "Auf diesem Gerät abmelden", en: "Sign out on this device"),
        "settings.leaveDeviceHint": LText(de: "Eure Daten bleiben auf dem Server. Mit dem Code kommst du nicht wieder rein — hebe den Server gut auf!",
                                          en: "Your data stays on the server. Keep your server safe!"),
        "settings.about": LText(de: "Über SoooDreamy", en: "About SoooDreamy"),
        "settings.version": LText(de: "Version", en: "Version"),
        "settings.madeWith": LText(de: "Mit 💜 gebaut — für euch zwei.", en: "Built with 💜 — for the two of you."),
        "settings.connection": LText(de: "Verbindung", en: "Connection"),
        "settings.serverVersion": LText(de: "Server-Version {version}", en: "Server version {version}"),
        "settings.pairingShow": LText(de: "Paar-Code & QR zeigen", en: "Show couple code & QR"),
        "settings.pairingHint": LText(de: "Zum Koppeln eines neuen Geräts — oder falls dein Schatz den Code nochmal braucht.",
                                      en: "For pairing a new device — or in case your sweetheart needs the code again."),
        "settings.widgets": LText(de: "Widgets", en: "Widgets"),
        "settings.widgetsHint": LText(de: "Lange auf den Homescreen drücken → „Widget hinzufügen“ → SoooDreamy",
                                      en: "Long-press your home screen → “Add widget” → SoooDreamy"),
        "settings.widgetBackground": LText(de: "Widget-Hintergrund", en: "Widget background"),
        "settings.widgetPhotoChrome": LText(de: "Foto als Widget-Hintergrund", en: "Photo as widget backdrop"),
        "settings.widgetPhotoChromeHint": LText(de: "Foto- & Leinwand-Widgets zeigen euer Lieblingsfoto abgedunkelt im Hintergrund",
                                                en: "Photo & canvas widgets show your favorite photo, dimmed, as their backdrop"),
        "settings.widgetBg.night": LText(de: "Nacht", en: "Night"),
        "settings.widgetBg.sunset": LText(de: "Abendrot", en: "Sunset"),
        "settings.widgetBg.ocean": LText(de: "Ozean", en: "Ocean"),
        "settings.widgetBg.blush": LText(de: "Rosé", en: "Blush"),
        "settings.widgetBg.mono": LText(de: "Mono", en: "Mono"),
        "settings.widgetBg.photo": LText(de: "Foto", en: "Photo"),

        // Widget Studio (2.0)
        "settings.widgetStudio": LText(de: "Widget-Studio", en: "Widget Studio"),
        "settings.widgetStudioHint": LText(de: "Themes, Layouts & Datenquellen für alle Widgets — mit Live-Vorschau.",
                                           en: "Themes, layouts & data sources for every widget — with live previews."),
        "la.title": LText(de: "Live Activity", en: "Live Activity"),
        "la.settingsHint": LText(de: "Sperrbildschirm & Dynamic Island anpassen: Theme, Ticker, Inhalte",
                                 en: "Customize lock screen & Dynamic Island: theme, ticker, content"),
        "la.preview": LText(de: "Vorschau", en: "Preview"),
        "la.theme": LText(de: "Farbschema", en: "Color scheme"),
        "la.elements": LText(de: "Angezeigte Elemente", en: "Visible elements"),
        "la.liveTimer": LText(de: "Tickender Countdown", en: "Ticking countdown"),
        "la.progress": LText(de: "Fortschrittsbalken (letzte 48 h)", en: "Progress bar (final 48 h)"),
        "la.presence": LText(de: "Online-Status", en: "Online status"),
        "la.mood": LText(de: "Stimmung & Notiz", en: "Mood & note"),
        "la.touch": LText(de: "Letzte Berührung", en: "Last touch"),
        "la.streak": LText(de: "Antwort-Serie 🔥", en: "Answer streak 🔥"),
        "la.days": LText(de: "Tage zusammen", en: "Days together"),
        "la.startPulse": LText(de: "Couple Pulse starten", en: "Start Couple Pulse"),
        "la.stopPulse": LText(de: "Couple Pulse beenden", en: "Stop Couple Pulse"),
        "la.countdownHintTitle": LText(de: "Countdown zu einem Moment", en: "Countdown to a moment"),
        "la.countdownHint": LText(de: "Starte Countdown-Live-Activities bei euren Momenten: Erinnerungen → Momente → „Live“.",
                                  en: "Start countdown Live Activities from your moments: Memories → Moments → “Live”."),
        "la.limitHint": LText(de: "iOS aktualisiert Live Activities ohne Push nur, solange die App läuft — tickende Timer & Fortschrittsbalken laufen aber immer weiter.",
                              en: "Without push, iOS only updates Live Activities while the app runs — ticking timers & progress bars keep animating regardless."),
        // Haptics composer (v2.0)
        "haptic.studio.title": LText(de: "Haptik-Studio", en: "Haptics Studio"),
        "home.hapticStudio": LText(de: "Haptik-Studio", en: "Haptics Studio"),
        "home.hapticStudio.hint": LText(de: "Eigene Vibration aufnehmen & senden",
                                        en: "Record & send a custom vibe"),
        "haptic.compose.title": LText(de: "Dein Muster", en: "Your pattern"),
        "haptic.pad.idle": LText(de: "Tippe & halte deinen Rhythmus — kurz = Klopfen, lang = sanftes Beben",
                                 en: "Tap & hold your rhythm — short = knock, long = gentle rumble"),
        "haptic.pad.active": LText(de: "Weiter tippen … Pausen gehören zum Rhythmus",
                                   en: "Keep tapping … pauses are part of the rhythm"),
        "haptic.events.count": LText(de: "{n} Impulse", en: "{n} pulses"),
        "haptic.feel": LText(de: "Fühlen", en: "Feel it"),
        "haptic.clear": LText(de: "Neu", en: "Redo"),
        "haptic.send": LText(de: "Senden", en: "Send"),
        "haptic.save.title": LText(de: "Muster speichern", en: "Save pattern"),
        "haptic.save.nameField": LText(de: "Name (z. B. Gute-Nacht-Puls)", en: "Name (e.g. goodnight pulse)"),
        "haptic.sent.toast": LText(de: "Vibration an {name} geschickt 💜", en: "Vibe sent to {name} 💜"),
        "haptic.saved.toast": LText(de: "In eurer Bibliothek gespeichert", en: "Saved to your library"),
        "haptic.presets.title": LText(de: "Presets", en: "Presets"),
        "haptic.library.title": LText(de: "Eure Bibliothek", en: "Your library"),
        "haptic.library.empty": LText(de: "Noch keine eigenen Muster — nimm oben eins auf!",
                                      en: "No saved patterns yet — record one above!"),
        "haptic.history.title": LText(de: "Zuletzt gesendet & empfangen", en: "Recently sent & received"),
        "haptic.history.empty": LText(de: "Noch nichts verschickt — probier ein Preset!",
                                      en: "Nothing sent yet — try a preset!"),
        "haptic.adhoc": LText(de: "Spontan-Vibe", en: "Spontaneous vibe"),
        "haptic.fromYou": LText(de: "von dir", en: "from you"),
        "haptic.fromPartner": LText(de: "von {name}", en: "from {name}"),
        "haptic.rename": LText(de: "Umbenennen", en: "Rename"),
        "haptic.deleteConfirm": LText(de: "Muster löschen?", en: "Delete pattern?"),
        "haptic.sentCount": LText(de: "{n}× gesendet", en: "sent {n}×"),
        "haptic.received.title": LText(de: "Vibration", en: "Vibe"),
        "haptic.received.body": LText(de: "{name} lässt dein Handy für dich vibrieren 💜",
                                      en: "{name} is making your phone buzz for you 💜"),
        "haptic.received.overlay": LText(de: "Eine Vibration von {name}", en: "A vibe from {name}"),
        "haptic.replay": LText(de: "Nochmal fühlen", en: "Feel again"),
        "haptic.deviceHint": LText(de: "Haptik braucht eine Taptic Engine — im Simulator und auf den meisten iPads ist nichts zu spüren.",
                                   en: "Haptics need a Taptic Engine — nothing to feel in the simulator or on most iPads."),
        "haptic.preset.heartbeat": LText(de: "Herzschlag", en: "Heartbeat"),
        "haptic.preset.butterflies": LText(de: "Schmetterlinge", en: "Butterflies"),
        "haptic.preset.rain": LText(de: "Regen", en: "Rain"),
        "haptic.preset.soskiss": LText(de: "SOS-Kuss", en: "SOS kiss"),
        "haptic.preset.ocean": LText(de: "Meeresrauschen", en: "Ocean waves"),
        "haptic.preset.sparkle": LText(de: "Funkeln", en: "Sparkle"),

        // iCloud & backup (v2.0)
        "icloud.title": LText(de: "iCloud & Backup", en: "iCloud & Backup"),
        "icloud.settingsHint": LText(de: "Server-Metadaten & Einstellungen sichern — ohne Sitzungstokens",
                                     en: "Back up server metadata & settings — without session tokens"),
        "icloud.status": LText(de: "iCloud-Status", en: "iCloud status"),
        "icloud.statusCloudKit": LText(de: "CloudKit (privat)", en: "CloudKit (private)"),
        "icloud.statusDrive": LText(de: "iCloud Drive", en: "iCloud Drive"),
        "icloud.available": LText(de: "verfügbar", en: "available"),
        "icloud.unavailable": LText(de: "nicht verfügbar", en: "unavailable"),
        "icloud.noAccount": LText(de: "kein iCloud-Account", en: "no iCloud account"),
        "icloud.restricted": LText(de: "eingeschränkt", en: "restricted"),
        "icloud.backup": LText(de: "iCloud-Backup", en: "iCloud backup"),
        "icloud.whatsIn": LText(de: "Sichert eure Server-Verbindungen (inkl. Kopplung) und deine App-Einstellungen in DEINE private iCloud-Datenbank. Eure gemeinsamen Inhalte liegen sicher auf eurem Server und kommen nach dem Wiederherstellen automatisch zurück.",
                                en: "Backs up your server connections (incl. pairing) and app settings to YOUR private iCloud database. Your shared content lives safely on your server and comes back automatically after restoring."),
        "icloud.lastBackup": LText(de: "Letztes Backup", en: "Last backup"),
        "icloud.never": LText(de: "noch nie", en: "never"),
        "icloud.backupNow": LText(de: "Jetzt in iCloud sichern", en: "Back up to iCloud now"),
        "icloud.backupDone": LText(de: "In iCloud gesichert ☁️", en: "Backed up to iCloud ☁️"),
        "icloud.backupFailed": LText(de: "Backup hat nicht geklappt", en: "Backup didn't work"),
        "icloud.restore": LText(de: "Wiederherstellen", en: "Restore"),
        "icloud.restoreConfirmTitle": LText(de: "Backup wiederherstellen?", en: "Restore backup?"),
        "icloud.restoreConfirmMessage": LText(de: "Ersetzt deine gespeicherten Server und App-Einstellungen durch das Backup. Eure Inhalte auf dem Server bleiben unberührt.",
                                              en: "Replaces your saved servers and app settings with the backup. Your content on the server stays untouched."),
        "icloud.restoreDone": LText(de: "{n} Server wiederhergestellt 🎉", en: "Restored {n} servers 🎉"),
        "icloud.restoreFailed": LText(de: "Wiederherstellen hat nicht geklappt", en: "Restore didn't work"),
        "icloud.noBackup": LText(de: "Kein Backup in iCloud gefunden", en: "No backup found in iCloud"),
        "icloud.export": LText(de: "Datei-Export", en: "File export"),
        "icloud.exportHint": LText(de: "Erstellt eine AES-GCM-verschlüsselte .sooodreamy-Datei mit Server-Metadaten, Einstellungen und einem Schnappschuss von Momenten, Bucket List, Songs & Coupons. Sitzungstokens werden nie exportiert.",
                                   en: "Creates an AES-GCM encrypted .sooodreamy file with server metadata, settings and a snapshot of moments, bucket list, songs & coupons. Session tokens are never exported."),
        "icloud.exportCreate": LText(de: "Verschlüsseltes Backup erstellen", en: "Create encrypted backup"),
        "icloud.exportShare": LText(de: "Backup-Datei teilen/sichern", en: "Share/save backup file"),
        "icloud.exportToDrive": LText(de: "Direkt in iCloud Drive ablegen", en: "Save straight to iCloud Drive"),
        "icloud.exportDone": LText(de: "In iCloud Drive abgelegt 📄", en: "Saved to iCloud Drive 📄"),
        "icloud.exportFailed": LText(de: "Export hat nicht geklappt", en: "Export didn't work"),
        "icloud.importFile": LText(de: "Aus Backup-Datei wiederherstellen", en: "Restore from backup file"),
        "icloud.importFailed": LText(de: "Die Datei ist kein SoooDreamy-Backup", en: "That file isn't a SoooDreamy backup"),
        "icloud.password": LText(de: "Passphrase (mindestens 12 Zeichen)", en: "Passphrase (at least 12 characters)"),
        "icloud.passwordConfirm": LText(de: "Passphrase wiederholen", en: "Repeat passphrase"),
        "icloud.passwordTooShort": LText(de: "Mindestens 12 Zeichen. Die Passphrase wird nirgendwo gespeichert.",
                                         en: "Use at least 12 characters. The passphrase is not stored anywhere."),
        "icloud.passwordMismatch": LText(de: "Die Passphrasen stimmen nicht überein.",
                                         en: "The passphrases do not match."),
        "icloud.passwordWarning": LText(de: "Wichtig: Ohne diese Passphrase ist das Backup endgültig nicht wiederherstellbar.",
                                        en: "Important: Without this passphrase, the backup cannot be recovered."),
        "icloud.importPasswordTitle": LText(de: "Backup entschlüsseln", en: "Decrypt backup"),
        "icloud.importPasswordHint": LText(de: "Gib die Passphrase ein, mit der diese Datei erstellt wurde.",
                                           en: "Enter the passphrase used to create this file."),
        "icloud.importPasswordFailed": LText(de: "Falsche Passphrase oder beschädigte Backup-Datei.",
                                             en: "Wrong passphrase or damaged backup file."),
        "icloud.decrypt": LText(de: "Entschlüsseln", en: "Decrypt"),
        "icloud.hintTitle": LText(de: "Ehrliche Sideload-Info", en: "Honest sideload note"),
        "icloud.sideloadHint": LText(de: "CloudKit und iCloud Drive brauchen iCloud-Entitlements, die das Signieren überleben. App-Store-/Entwickler-Signierung: alles funktioniert. Sideload-Signierer (freie Apple-ID, AltStore & Co.) entfernen sie oft — dann zeigen die Status-Punkte oben Rot und es bleibt der Datei-Export, der immer funktioniert.",
                                    en: "CloudKit and iCloud Drive need iCloud entitlements that survive signing. App-Store/developer signing: everything works. Sideload signers (free Apple ID, AltStore & co.) often strip them — then the status dots above show red and the always-working file export remains."),

        "studio.title": LText(de: "Widget-Studio", en: "Widget Studio"),
        "studio.settingsHint": LText(de: "Widgets live vorschauen & anpassen: Themes, Layouts, Momente, Fotos",
                                     en: "Preview & customize widgets live: themes, layouts, moments, photos"),
        "studio.diag.ok": LText(de: "Widgets erhalten Daten", en: "Widgets are receiving data"),
        "studio.diag.updated": LText(de: "Zuletzt aktualisiert: {time}", en: "Last updated: {time}"),
        "studio.diag.noData": LText(de: "Noch keine Widget-Daten — kurz die App nutzen, dann füllen sich die Widgets.",
                                    en: "No widget data yet — use the app for a moment and the widgets fill up."),
        "studio.diag.noGroup": LText(de: "App-Group nicht verfügbar", en: "App group unavailable"),
        "studio.diag.noGroupHint": LText(de: "Dein Sideload-Tool hat group.app.sooodreamy.shared nicht mitsigniert — Widgets können dann keine Daten der App lesen. AltStore/SideStore signieren die App-Group automatisch mit.",
                                         en: "Your sideload tool didn't sign group.app.sooodreamy.shared — widgets can't read the app's data without it. AltStore/SideStore sign the app group automatically."),
        "studio.globalTheme": LText(de: "Studio-Theme", en: "Studio theme"),
        "studio.globalThemeHint": LText(de: "Gilt für alle Widgets — einzelne Widgets können unten (oder per „Widget bearbeiten“ am Homescreen) abweichen.",
                                        en: "Applies to all widgets — individual widgets can override below (or via “Edit widget” on the home screen)."),
        "studio.theme": LText(de: "Theme", en: "Theme"),
        "studio.themeDefault": LText(de: "Studio", en: "Studio"),
        "studio.layout": LText(de: "Layout", en: "Layout"),
        "studio.layout.auto": LText(de: "Auto", en: "Auto"),
        "studio.layout.classic": LText(de: "Klassisch", en: "Classic"),
        "studio.layout.hero": LText(de: "Groß", en: "Hero"),
        "studio.layout.minimal": LText(de: "Minimal", en: "Minimal"),
        "studio.animated": LText(de: "Live-Ticker (tickende Zeiten)", en: "Live ticker (ticking times)"),
        "studio.countdownEvent": LText(de: "Angezeigter Moment", en: "Pinned moment"),
        "studio.countdownNext": LText(de: "Automatisch: nächster Moment", en: "Automatic: next moment"),
        "studio.photoSource": LText(de: "Fotoquelle", en: "Photo source"),
        "studio.photoSource.favorite": LText(de: "❤️ Favorit", en: "❤️ Favorite"),
        "studio.photoSource.newest": LText(de: "🆕 Neuestes", en: "🆕 Newest"),
        "studio.widget.days": LText(de: "Tage zusammen", en: "Days together"),
        "studio.widget.countdown": LText(de: "Countdown", en: "Countdown"),
        "studio.widget.mood": LText(de: "Stimmung", en: "Mood"),
        "studio.widget.daily": LText(de: "Frage des Tages", en: "Daily question"),
        "studio.widget.streak": LText(de: "Antwort-Serie", en: "Answer streak"),
        "studio.widget.photo": LText(de: "Euer Foto", en: "Your photo"),
        "studio.widget.sendLove": LText(de: "Liebe senden (interaktiv)", en: "Send love (interactive)"),
        "studio.perWidgetHint": LText(de: "Tipp: Jedes Widget lässt sich auch direkt am Homescreen anpassen — lange drücken → „Widget bearbeiten“ (Theme, Layout, Moment, Fotoquelle).",
                                      en: "Tip: every widget can also be tweaked right on the home screen — long-press → “Edit widget” (theme, layout, moment, photo source)."),

        // Couple Pulse Live Activity
        "settings.pulse": LText(de: "Live Activity: Couple Pulse", en: "Live Activity: Couple Pulse"),
        "settings.pulseHint": LText(de: "Stimmung, Online-Status, letzte Berührung & Serie deines Schatzes auf dem Sperrbildschirm & in der Dynamic Island — aktualisiert, solange die App läuft (kein Push).",
                                    en: "Your sweetheart's mood, online status, last touch & streak on the lock screen & Dynamic Island — updated while the app is running (no push)."),
        "settings.pulseStarted": LText(de: "Couple Pulse läuft! 💜", en: "Couple Pulse is live! 💜"),

        // Notifications (couple alerts — local, WebSocket-driven)
        "notif.section": LText(de: "Benachrichtigungen", en: "Notifications"),
        "notif.master": LText(de: "Paar-Benachrichtigungen", en: "Couple alerts"),
        "notif.masterHint": LText(
            de: "Lokal immer bei laufender App. Bei beendeter App nur mit bezahlter/App-Store-Signierung und konfigurierten APNs-Zugangsdaten auf dem Server.",
            en: "Always local while the app runs. When terminated, delivery additionally requires paid/App Store signing and APNs credentials on the server."
        ),
        "notif.sound": LText(de: "Benachrichtigungston", en: "Notification sound"),
        "notif.sound.soft": LText(de: "Sanft", en: "Soft"),
        "notif.sound.chime": LText(de: "Glöckchen", en: "Chime"),
        "notif.sound.heartbeat": LText(de: "Herzschlag", en: "Heartbeat"),
        "notif.sound.kiss": LText(de: "Kuss", en: "Kiss"),
        "notif.sound.sparkle": LText(de: "Funkeln", en: "Sparkle"),
        "notif.sound.whoosh": LText(de: "Wusch", en: "Whoosh"),
        "notif.sound.tada": LText(de: "Tada", en: "Tada"),
        "notif.sound.default": LText(de: "System", en: "System"),
        "notif.type.touch": LText(de: "Berührungen", en: "Touches"),
        "notif.type.message": LText(de: "Nachrichten", en: "Messages"),
        "notif.type.photo": LText(de: "Neue Fotos", en: "New photos"),
        "notif.type.dailyReveal": LText(de: "Frage des Tages gelüftet", en: "Daily question revealed"),
        "notif.type.partnerOnline": LText(de: "Schatz kommt online", en: "Sweetheart comes online"),
        "notif.type.coupon": LText(de: "Gutscheine", en: "Coupons"),
        "notif.message.title": LText(de: "Neue Nachricht von {name}", en: "New message from {name}"),
        "notif.message.letter": LText(de: "Ein Brief für dich 💌", en: "A letter for you 💌"),
        "notif.message.voice": LText(de: "Eine Sprachnachricht für dich 🎤", en: "A voice note for you 🎤"),
        "notif.message.photo": LText(de: "Ein Foto für dich 📸", en: "A photo for you 📸"),
        "notif.photo.title": LText(de: "Neues Foto 📸", en: "New photo 📸"),
        "notif.photo.body": LText(de: "{name} hat ein neues Foto geteilt", en: "{name} shared a new photo"),
        "notif.daily.body": LText(de: "Eure Antworten auf die Frage des Tages sind jetzt sichtbar",
                                  en: "Your answers to the daily question are revealed"),
        "notif.online.title": LText(de: "{name} ist jetzt online 💜", en: "{name} is online now 💜"),
        "notif.online.body": LText(de: "Jetzt wäre ein Herzklopfen perfekt …", en: "Now would be perfect for a heartbeat…"),
        "notif.coupon.title": LText(de: "Neuer Gutschein 🎟️", en: "New coupon 🎟️"),
        "notif.coupon.body": LText(de: "{name} schenkt dir: „{title}“", en: "{name} gives you: “{title}”"),
        "notif.streak.title": LText(de: "Eure Serie ist in Gefahr! 🔥", en: "Your streak is at risk! 🔥"),
        "notif.streak.body": LText(de: "Beantworte noch schnell die Frage des Tages und rette eure {n}er-Serie.",
                                   en: "Answer today's question quickly and save your {n}-day streak."),

        // App lock
        "lock.title": LText(de: "SoooDreamy ist gesperrt", en: "SoooDreamy is locked"),
        "lock.subtitle": LText(de: "Eure Momente gehören nur euch zwei.", en: "Your moments belong to the two of you only."),
        "lock.unlock": LText(de: "Entsperren", en: "Unlock"),
        "lock.reason": LText(de: "Eure gemeinsamen Momente entsperren", en: "Unlock your shared moments"),
        "settings.appLock": LText(de: "App-Sperre", en: "App lock"),
        "settings.appLockHint": LText(de: "Beim Öffnen mit Face ID / Touch ID oder Code entsperren",
                                      en: "Unlock with Face ID / Touch ID or passcode when opening"),

        // Monthiversary
        "home.monthiversary": LText(de: "{n} Monate zusammen — genau heute! 🎉",
                                    en: "{n} months together — today! 🎉"),
        "home.monthiversaryOne": LText(de: "1 Monat zusammen — genau heute! 🎉",
                                       en: "1 month together — today! 🎉"),
        "home.anniversaryYears": LText(de: "{n} Jahre zusammen — happy Jahrestag! 🥂",
                                       en: "{n} years together — happy anniversary! 🥂"),
        "home.anniversaryOneYear": LText(de: "1 Jahr zusammen — happy Jahrestag! 🥂",
                                         en: "1 year together — happy anniversary! 🥂"),

        // Gallery → chat (v1.7 photo messages; lives here — not in MemoriesL10n —
        // because the chat feature owns the flow end to end)
        "gallery.sendToChat": LText(de: "In den Chat senden", en: "Send to chat"),
        "gallery.sentToChat": LText(de: "Foto in den Chat geschickt 💬", en: "Photo sent to chat 💬"),

        // Coupons (global toasts + polish; the coupons screen itself lives in MemoriesL10n)
        "coupon.receivedToast": LText(de: "Neuer Gutschein für dich! 🎟️", en: "A new coupon for you! 🎟️"),
        "coupon.redeemedToast": LText(de: "„{title}“ wurde eingelöst! 🎉", en: "“{title}” was redeemed! 🎉"),
        "coupon.giftAgain": LText(de: "Nochmal schenken", en: "Gift again"),
        "settings.couponReminder": LText(de: "Gutschein-Ablauf-Erinnerung", en: "Coupon expiry reminder"),
        "settings.couponReminderHint": LText(de: "Erinnert dich, bevor ein Gutschein für dich abläuft (bis 48 Stunden vorher)",
                                             en: "Nudges you before a coupon gifted to you expires (up to 48 hours ahead)"),
        "notif.couponExpiry.title": LText(de: "Gutschein läuft bald ab ⏳", en: "Coupon expiring soon ⏳"),
        "notif.couponExpiry.body": LText(de: "„{title}“ läuft bald ab — löse ihn schnell ein! 🎟️",
                                         en: "“{title}” is about to expire — redeem it soon! 🎟️"),

        // Flashback card
        "home.flashback": LText(de: "Erinnerung", en: "Memory"),
        "home.flashbackDaysAgo": LText(de: "vor {n} Tagen", en: "{n} days ago"),
        "home.flashbackQuestion": LText(de: "Eure Frage von damals", en: "Your question back then"),
        "home.flashbackShare": LText(de: "In den Chat senden 💬", en: "Send to chat 💬"),
        "home.flashbackShareHeader": LText(de: "💭 Erinnerung von vor {n} Tagen:",
                                           en: "💭 A memory from {n} days ago:"),
        "home.flashbackShared": LText(de: "Erinnerung im Chat geteilt 💭",
                                      en: "Memory shared to chat 💭"),

        // Streak calendar (sheet behind the dashboard streak pill)
        "home.streakCalendar.title": LText(de: "Serien-Kalender", en: "Streak calendar"),
        "home.streakCalendar.open": LText(de: "Serien-Kalender öffnen", en: "Open streak calendar"),
        "home.streakCalendar.prevMonth": LText(de: "Voriger Monat", en: "Previous month"),
        "home.streakCalendar.nextMonth": LText(de: "Nächster Monat", en: "Next month"),
        "home.streakCalendar.legendBoth": LText(de: "Beide geantwortet", en: "Both answered"),
        "home.streakCalendar.legendMine": LText(de: "Nur du", en: "Only you"),
        "home.streakCalendar.monthCount": LText(de: "{n}× beide geantwortet in diesem Monat",
                                                en: "{n}× both answered this month"),
        "home.streakCalendar.empty": LText(de: "Noch keine gemeinsamen Antworten — beantwortet heute eure erste Frage des Tages! 💫",
                                           en: "No shared answers yet — answer your first daily question today! 💫"),

        // "While you were away" card (missed inbox)
        "home.missedTitle": LText(de: "Während du weg warst", en: "While you were away"),
        "home.missedBody": LText(de: "Tippen, um alles nachzuholen", en: "Tap to catch up"),
        "home.missed.messages": LText(de: "Nachrichten", en: "Messages"),
        "home.missed.touches": LText(de: "Berührungen", en: "Touches"),
        "home.missed.photos": LText(de: "Fotos", en: "Photos"),
        "home.missed.coupons": LText(de: "Gutscheine", en: "Coupons"),
        "home.missed.songs": LText(de: "Songs", en: "Songs"),
        "home.missed.canvas": LText(de: "Leinwand-Kritzeleien", en: "Canvas doodles"),
        "home.missed.games": LText(de: "Spiele: Du bist dran!", en: "Games: you're up!"),
        "home.missed.daily": LText(de: "Frage des Tages beantwortet", en: "Daily question answered"),

        // Check-in (v2.0)
        "checkin.title": LText(de: "Guten-Morgen-/Gutenacht-Check-in", en: "Morning / goodnight check-in"),
        "checkin.morning": LText(de: "Guten Morgen", en: "Good morning"),
        "checkin.morning.done": LText(de: "Guten Morgen gesagt", en: "Said good morning"),
        "checkin.night": LText(de: "Gute Nacht", en: "Good night"),
        "checkin.night.done": LText(de: "Gute Nacht gesagt", en: "Said good night"),
        "checkin.partner.none": LText(de: "{name} hat heute noch nicht eingecheckt",
                                      en: "{name} hasn't checked in today yet"),
        "checkin.partner.morning": LText(de: "{name} ist wach ☀️", en: "{name} is awake ☀️"),
        "checkin.partner.night": LText(de: "{name} schläft schon 🌙", en: "{name} is already asleep 🌙"),
        "checkin.toast.morning": LText(de: "☀️ {name} wünscht dir einen guten Morgen!",
                                       en: "☀️ {name} wishes you a good morning!"),
        "checkin.toast.night": LText(de: "🌙 {name} sagt gute Nacht!",
                                     en: "🌙 {name} says good night!"),

        // Hug queue (v2.0)
        "hug.card.title": LText(de: "Umarmungs-Warteschlange", en: "Hug queue"),
        "hug.card.teaser": LText(de: "Schick eine Umarmung auf Vorrat 🫂",
                                 en: "Queue a hug for later 🫂"),
        "hug.card.pending": LText(de: "{n} ungeöffnete Umarmung(en) für dich! 🎁",
                                  en: "{n} unopened hug(s) for you! 🎁"),
        "hug.compose.body": LText(de: "Auch wenn {name} gerade schläft: Leg eine Umarmung in die Warteschlange — sie wartet wie ein Geschenk. 💜",
                                  en: "Even while {name} is asleep: queue a hug — it waits like a little present. 💜"),
        "hug.compose.placeholder": LText(de: "Kleine Notiz dazu (optional)…",
                                         en: "A little note (optional)…"),
        "hug.compose.send": LText(de: "Umarmung in die Warteschlange 🫂",
                                  en: "Queue the hug 🫂"),
        "hug.compose.sentToast": LText(de: "Umarmung wartet auf {name} 🫂",
                                       en: "Hug is waiting for {name} 🫂"),
        "hug.pending.title": LText(de: "Für dich ({n}) 🎁", en: "For you ({n}) 🎁"),
        "hug.pending.from": LText(de: "Eine Umarmung von {name}", en: "A hug from {name}"),
        "hug.pending.open": LText(de: "Öffnen", en: "Open"),
        "hug.queued.title": LText(de: "Wartet auf {name}", en: "Waiting for {name}"),
        "hug.queued.plain": LText(de: "Eine feste Umarmung", en: "A big warm hug"),
        "hug.queued.hint": LText(de: "{name} bekommt sie beim nächsten App-Besuch.",
                                 en: "{name} will get it on their next visit."),
        "hug.history.title": LText(de: "Geöffnete Umarmungen", en: "Opened hugs"),
        "hug.receivedToast": LText(de: "🫂 Eine Umarmung von {name} wartet auf dich!",
                                   en: "🫂 A hug from {name} is waiting for you!"),
        "hug.openedToast": LText(de: "{name} hat deine Umarmung geöffnet 🥰",
                                 en: "{name} opened your hug 🥰"),
        "notif.hug.title": LText(de: "Eine Umarmung wartet 🫂", en: "A hug is waiting 🫂"),
        "notif.hug.body": LText(de: "{name} hat dir eine Umarmung in die Warteschlange gelegt.",
                                en: "{name} queued a hug for you."),

        // Now playing (v2.0)
        "nowplaying.title": LText(de: "Gerade am Hören", en: "Now playing"),
        "nowplaying.songField": LText(de: "Song…", en: "Song…"),
        "nowplaying.artistField": LText(de: "Artist (optional)…", en: "Artist (optional)…"),
        "nowplaying.set": LText(de: "Status setzen 🎧", en: "Set status 🎧"),
        "nowplaying.clear": LText(de: "Status löschen", en: "Clear status"),
        "nowplaying.hint": LText(de: "Verschwindet automatisch nach 60 Minuten.",
                                 en: "Disappears automatically after 60 minutes."),
        "nowplaying.toast": LText(de: "🎧 {name} hört gerade: {title}",
                                  en: "🎧 {name} is listening to: {title}"),

        // Connection banner
        "conn.connecting": LText(de: "Verbinde…", en: "Connecting…"),
        "conn.offline": LText(de: "Offline — versuche es wieder…", en: "Offline — retrying…"),
        "conn.connected": LText(de: "Verbunden", en: "Connected"),

        // Errors
        "error.invalidURL": LText(de: "Ungültige Server-Adresse", en: "Invalid server address"),
        "error.decoding": LText(de: "Antwort vom Server nicht verstanden", en: "Couldn't understand the server's reply"),
        "error.network": LText(de: "Netzwerkfehler — ist der Server erreichbar?", en: "Network error — is the server reachable?"),
        "error.unauthorized": LText(de: "Anmeldung abgelaufen — bitte neu koppeln", en: "Session expired — please pair again"),

        // Misc
        "misc.partnerDefault": LText(de: "dein Schatz", en: "your sweetheart"),
        "misc.dissolvedTitle": LText(de: "Euer Paar wurde aufgelöst", en: "Your couple was dissolved"),
        "misc.partnerJoinedToast": LText(de: "{name} ist beigetreten! 💞", en: "{name} joined! 💞")
    ]
}
