"""Extra questions, wave 2: Deutschland spezial (format: see tools/content/merge_extra.py)."""
KAT = "deutschland_spezial"
REGION = "de"
DATA = r"""
@ politik_bundestag
E E | Welche Regierungskoalition ist hier gesucht? | 🚦🤝 | Ampelkoalition | Große Koalition ; Jamaika-Koalition ; Kenia-Koalition | Sie regierte ab Dezember 2021. ; Sie bestand aus drei Parteien. ; Die Parteifarben sind Rot, Gelb und Grün. | Die Ampel aus SPD, Grünen und FDP zerbrach im November 2024 — im Februar 2025 folgte eine vorgezogene Neuwahl.
E M | Welches Regierungsbündnis ist hier gesucht? | 🇯🇲🤝 | Jamaika-Koalition | Ampelkoalition ; Kenia-Koalition ; Deutschland-Koalition | Die Farben passen zu einer Karibik-Flagge. ; Beteiligt sind Union, FDP und Grüne. ; Auf Bundesebene scheiterten 2017 die Sondierungen. | In Schleswig-Holstein regierte so ein schwarz-gelb-grünes Bündnis von 2017 bis 2022.
C U | In welchem Gebäude tagte der Bundestag von 1986 bis 1992 übergangsweise? | Im alten Wasserwerk in Bonn | Im Palais Schaumburg ; In der Beethovenhalle ; Im Kölner Gürzenich | Das Gebäude liegt direkt am Rhein. ; Der alte Plenarsaal wurde damals abgerissen und neu gebaut. ; Zuvor diente das Gebäude der Trinkwasserversorgung. | Das frühere Pumpwerk ist heute Teil des World Conference Center Bonn.
C M | Wer wurde im Oktober 2021 zur Präsidentin des Bundestags gewählt? | Bärbel Bas | Katrin Göring-Eckardt ; Claudia Roth ; Petra Pau | Sie gehört zur SPD. ; Sie stammt aus Duisburg. ; Sie war nach Annemarie Renger und Rita Süssmuth die dritte Frau in diesem Amt. | Das Amt des Bundestagspräsidenten ist protokollarisch das zweithöchste im Staat.
C H | Wie heißt die Villa in Bonn, die lange der Amtssitz des Bundespräsidenten war? | Villa Hammerschmidt | Palais Schaumburg ; Villa Hügel ; Haus Doorn | Sie liegt am Rheinufer. ; Heute ist sie der zweite Dienstsitz des Staatsoberhaupts. ; Ihr Name klingt nach einem Handwerk. | Seit 1994 residiert der Bundespräsident vorrangig im Berliner Schloss Bellevue — das Palais Schaumburg war das Bonner Kanzleramt.
C U | In welcher Stadt hat das Bundesarbeitsgericht seinen Sitz? | Erfurt | Kassel ; Leipzig ; München | Die Stadt ist eine Landeshauptstadt. ; Sie liegt in Ostdeutschland. ; Dort steht der Dom St. Marien. | Leipzig ist Sitz des Bundesverwaltungsgerichts, Kassel des Bundessozialgerichts und München des Bundesfinanzhofs.
W H | Ein Bundesminister muss zugleich Mitglied des Bundestags sein. | falsch | Das Grundgesetz verlangt kein Bundestagsmandat — immer wieder werden auch Parteilose oder Landespolitiker Bundesminister.
W M | Das Grundgesetz war 1949 als Übergangslösung bis zur Wiedervereinigung gedacht. | wahr | Deshalb heißt es nicht „Verfassung“ — Artikel 146 sieht vor, dass es durch eine vom Volk beschlossene Verfassung abgelöst werden kann.
W M | Bei der Europawahl 2024 durften in Deutschland erstmals schon 16-Jährige wählen. | wahr | Für Bundestagswahlen liegt das Wahlalter dagegen weiterhin bei 18 Jahren.
S H | Auf wie viele Sitze legt das 2023 reformierte Wahlrecht die Größe des Bundestags fest? | 630 | Sitze | 15 | 300 | 1000 | Mehr als 600. ; Weniger als 700. ; Überhang- und Ausgleichsmandate gibt es nicht mehr. | Durch Überhang- und Ausgleichsmandate war der Bundestag 2021 auf 736 Abgeordnete angewachsen.
S E | Wie alt muss man laut Grundgesetz mindestens sein, um zum Bundespräsidenten gewählt zu werden? | 40 | Jahre | 10 | 18 | 80 | Älter als 30. ; Jünger als 50. ; Eine runde Zahl. | Das Mindestalter steht in Artikel 54 — für Bundestagsabgeordnete reichen dagegen 18 Jahre.
O H | Sortiere diese Bundesländer nach ihren Stimmen im Bundesrat — die wenigsten zuerst. | Bremen = 3 Stimmen ; Berlin = 4 Stimmen ; Hessen = 5 Stimmen ; Bayern = 6 Stimmen | Der kleinste Stadtstaat hat am wenigsten. ; Die Hauptstadt folgt. ; Das große Flächenland im Süden hat die Höchstzahl. | Die Stimmenzahl richtet sich grob nach der Einwohnerzahl — jedes Land hat zwischen drei und sechs Stimmen.
M H | Welche ZWEI dieser Bundesgerichte haben ihren Sitz in Karlsruhe? | Bundesverfassungsgericht ; Bundesgerichtshof | Bundesarbeitsgericht ; Bundessozialgericht ; Bundesfinanzhof ; Bundesverwaltungsgericht | Eines wacht über das Grundgesetz. ; Das andere ist oberstes Gericht für Zivil- und Strafsachen. ; Die Stadt nennt sich deshalb „Residenz des Rechts“. | Die übrigen obersten Bundesgerichte verteilen sich auf Erfurt, Kassel, München und Leipzig.

@ tv_shows
E E | Welche TV-Show ist hier gesucht? | 🦁🕳️💼 | Die Höhle der Löwen | Das Supertalent ; Shark Tank ; Wer wird Millionär? | Gründer stellen ihre Geschäftsidee vor. ; Investoren bieten Geld für Firmenanteile. ; Sie läuft bei VOX. | Das Format stammt ursprünglich aus Japan — in Großbritannien heißt es „Dragons' Den“, in den USA „Shark Tank“.
E E | Welche TV-Show ist hier gesucht? | 👨‍🌾🔍👩 | Bauer sucht Frau | Schwiegertochter gesucht ; Adam sucht Eva ; Hochzeit auf den ersten Blick | Landwirte suchen die große Liebe. ; Sie läuft bei RTL. ; Moderiert wird sie von Inka Bause. | Aus der Kuppelshow sind schon mehrere Ehen und Babys hervorgegangen.
E E | Welche Kindersendung ist hier gesucht? | 🦁🦷🌼 | Löwenzahn | Pusteblume ; Sesamstraße ; Die Sendung mit der Maus | Ihr Held wohnte in einem Bauwagen. ; Sie läuft im ZDF. ; Der Titel ist auch eine gelbe Wiesenblume. | Peter Lustig verabschiedete sich am Ende jeder Folge mit dem Rat: „Abschalten!“
C M | In welcher Stadt ermittelt der Polizeihund in der Serie „Kommissar Rex“? | Wien | München ; Salzburg ; Innsbruck | Die Serie ist eine österreichisch-deutsche Produktion. ; Rex liebt Wurstsemmeln. ; Die Stadt liegt an der Donau. | Die Krimiserie startete 1994 und lief in Deutschland bei Sat.1 — später wurde sie weltweit verkauft.
C E | Welche ARD-Serie spielt auf einem Polizeirevier in Hamburg? | Großstadtrevier | Die Rosenheim-Cops ; Hubert und Staller ; SOKO Kitzbühel | Die Serie läuft seit den 1980ern. ; Das Revier liegt nahe der Reeperbahn. ; Im Titel steckt ein Wort für große Stadt. | „Großstadtrevier“ startete 1986 und gehört zu den langlebigsten deutschen Vorabendserien.
C H | Welche beiden Rateteam-Kapitäne treten bei „Wer weiß denn sowas?“ gegeneinander an? | Bernhard Hoëcker und Elton | Joko und Klaas ; Olli Dittrich und Wigald Boning ; Bastian Pastewka und Anke Engelke | Einer der beiden war Rateteam-Mitglied bei „Genial daneben“. ; Der andere war früher Showpraktikant bei Stefan Raab. ; Moderiert wird die Show von Kai Pflaume. | Die ARD-Quizshow läuft seit 2015 im Vorabendprogramm.
C U | Wer übernahm 2006 in „Löwenzahn“ die Nachfolge von Peter Lustig? | Guido Hammesfahr | Ralph Caspers ; Armin Maiwald ; Christoph Biemann | Seine Figur heißt Fritz Fuchs. ; Er zog in den berühmten Bauwagen ein. ; Sein Nachname beginnt mit H. | Peter Lustig hatte „Löwenzahn“ seit 1981 geprägt — rund 25 Jahre lang.
W H | „Wetten, dass..?“ wurde 2014 eingestellt, kehrte aber später für Sonderausgaben zurück. | wahr | Nach dem Aus 2014 moderierte Thomas Gottschalk von 2021 bis 2023 noch einmal große Jubiläumsausgaben.
W E | In der „Sendung mit der Maus“ spricht die Maus mit den Zuschauern. | falsch | Die Maus bleibt stumm — sie klimpert mit den Augen und macht Geräusche, gesprochen wird nur von den Moderatoren.
S E | Wie viele Minuten dauert die Hauptausgabe der „Tagesschau“ um 20 Uhr regulär? | 15 | Minuten | 20 | 1 | 60 | Weniger als eine halbe Stunde. ; Mehr als zehn Minuten. ; Danach folgt meist direkt der Wetterbericht. | Deshalb beginnt der Hauptfilm im Ersten traditionell um 20:15 Uhr.
S H | In welchem Jahr ging das ZDF auf Sendung? | 1963 | Jahr | 3 | 1945 | 1990 | Mehr als zehn Jahre nach dem Start der ARD-Tagesschau. ; In den 1960er-Jahren. ; Im Jahr, in dem John F. Kennedy Berlin besuchte. | Das ZDF sendete ab dem 1. April 1963 aus Mainz — und das war kein Aprilscherz.
O H | Sortiere diese TV-Angebote nach ihrem Start in Deutschland — das älteste zuerst. | ProSieben = 1989 ; VOX = 1993 ; Netflix = 2014 ; Disney+ = 2020 | Der Sender aus Unterföhring kommt zuerst. ; Der Kochshow-Sender folgt. ; Der Streamingdienst mit der Maus ist am jüngsten. | Disney+ startete in Deutschland im März 2020 — mitten im ersten Corona-Lockdown.
M M | Welche ZWEI dieser Serien spielen in Bayern? | Die Rosenheim-Cops ; Der Bulle von Tölz | Großstadtrevier ; SOKO Wismar ; In aller Freundschaft ; Notruf Hafenkante | Eine spielt in einer Stadt am Inn. ; Die andere in einem Kurort an der Isar. ; Die falschen spielen im Norden oder in Sachsen. | „In aller Freundschaft“ spielt in der Leipziger Sachsenklinik, „SOKO Wismar“ an der Ostsee.

@ promis_boulevard
E M | Welcher Promi ist hier gesucht? | 🕶️🐈👔 | Karl Lagerfeld | Wolfgang Joop ; Harald Glööckler ; Guido Maria Kretschmer | Er war Modeschöpfer. ; Er trug stets Sonnenbrille, Zopf und Stehkragen. ; Seine Katze hieß Choupette. | Der gebürtige Hamburger war 36 Jahre lang Kreativdirektor von Chanel.
C M | Welcher Modeschöpfer nennt seine Marke „Pompöös“? | Harald Glööckler | Wolfgang Joop ; Guido Maria Kretschmer ; Michael Michalsky | Er ist für Krönchen und viel Glitzer bekannt. ; Er verkaufte seine Mode oft im Teleshopping. ; Sein Nachname enthält ein doppeltes ö. | Mit Glamour und Strass wurde Glööckler zu einer der schillerndsten Figuren des deutschen Boulevards.
C E | Welcher Comedian wurde mit „Was guckst du?!“ bekannt? | Kaya Yanar | Bülent Ceylan ; Michael Mittermeier ; Atze Schröder | Die Show lief ab 2001 bei Sat.1. ; Eine seiner Figuren ist der Türsteher Hakan. ; Er wurde in Frankfurt am Main geboren. | Yanar spielte mit Klischees über Herkunft — sein Türsteher Hakan wurde mit „Du kommst hier nit rein!“ Kult.
C H | Welcher Schauspieler verkörpert in der „heute-show“ den Choleriker Gernot Hassknecht? | Hans-Joachim Heist | Christian Ehring ; Olaf Schubert ; Martin Klempnow | Er gehört seit 2009 zum Ensemble. ; Seine Figur brüllt sich regelmäßig in Rage. ; Sein Vorname ist ein Doppelname. | Mit seinen Wutreden tourt Heist als Hassknecht auch durch die Theater des Landes.
C E | Welcher TV-Koch tritt in „Kitchen Impossible“ gegen Kolleginnen und Kollegen an? | Tim Mälzer | Tim Raue ; Steffen Henssler ; Johann Lafer | Die Show läuft bei VOX. ; Er stammt aus Norddeutschland. ; Er betreibt die „Bullerei“ in Hamburg. | Bei „Kitchen Impossible“ müssen Köche ein fremdes Gericht allein nach Geschmack nachkochen.
W H | Heidi Klum wurde in Bergisch Gladbach geboren. | wahr | Das Topmodel wuchs im Rheinland auf, bevor es in New York und Los Angeles Karriere machte.
W M | Michael „Bully“ Herbig ist Österreicher. | falsch | Herbig wurde 1968 in München geboren — sein „Schuh des Manitu“ wurde einer der erfolgreichsten deutschen Kinofilme.
S M | Wie alt wurde Modeschöpfer Karl Lagerfeld? | 85 | Jahre | 10 | 40 | 110 | Älter als 80. ; Jünger als 90. ; Er starb 2019. | Lagerfeld machte um sein Geburtsjahr lange ein Geheimnis — geboren wurde er 1933 in Hamburg.
S U | Wie alt wurde die Sängerin und Schauspielerin Hildegard Knef? | 76 | Jahre | 10 | 30 | 110 | Älter als 70. ; Jünger als 80. ; Sie starb 2002. | Knef (1925–2002) sorgte 1951 mit einer kurzen Nacktszene in „Die Sünderin“ für einen Skandal.
O H | Sortiere diese „DSDS“-Gewinner nach ihrem Siegerjahr — den frühesten zuerst. | Alexander Klaws = 2003 ; Mark Medlock = 2007 ; Pietro Lombardi = 2011 ; Beatrice Egli = 2013 | Der allererste Superstar kommt zuerst. ; Der Sieger aus Mannheim kam kurz vor der Schlagersängerin. ; Die Schweizerin ist die jüngste Siegerin in der Liste. | Beatrice Egli wurde nach ihrem Sieg zu einem der größten Schlagerstars im deutschsprachigen Raum.
O H | Sortiere diese Filme mit Til Schweiger nach ihrem Erscheinen — den ältesten zuerst. | Manta, Manta = 1991 ; Knockin' on Heaven's Door = 1997 ; Zweiohrküken = 2009 ; Honig im Kopf = 2014 | Die Autokomödie aus dem Ruhrgebiet kommt zuerst. ; Das Roadmovie zweier Todkranker folgt. ; Der Film über einen demenzkranken Großvater ist der jüngste. | „Honig im Kopf“ mit Dieter Hallervorden lockte über sieben Millionen Menschen ins Kino.
M E | Welche ZWEI dieser Promis stammen aus Österreich? | Christoph Waltz ; Arnold Schwarzenegger | Til Schweiger ; Heidi Klum ; Karl Lagerfeld ; Michael Schumacher | Einer gewann zwei Oscars mit Tarantino-Filmen. ; Der andere wurde Gouverneur von Kalifornien. ; Einer ist Wiener, der andere Steirer. | Waltz wurde in Wien geboren, Schwarzenegger stammt aus Thal bei Graz.

@ alltag_buerokratie
E E | Welches deutsche Wort ist hier gesucht? | 🎉🌆 | Feierabend | Wochenende ; Mittagspause ; Brückentag | Er kommt nach getaner Arbeit. ; Viele begrüßen ihn mit einem kühlen Bier. ; Eine genaue Entsprechung gibt es in vielen Sprachen nicht. | Das Wort ist so typisch deutsch, dass es im Englischen oft einfach übernommen oder umschrieben wird.
C M | Unter welcher Telefonnummer erreicht man in Deutschland den ärztlichen Bereitschaftsdienst? | 116117 | 110 ; 115 ; 118118 | Die Nummer ist bundesweit gleich. ; Man ruft sie an, wenn die Hausarztpraxis geschlossen ist. ; Die Ziffernfolge wiederholt sich fast. | Bei Lebensgefahr gilt dagegen die 112 — die 115 ist die Behördennummer.
C M | Wie heißt das Online-Portal der deutschen Finanzämter für die Steuererklärung? | ELSTER | FINDUS ; STEUERBOT ; TAXI | Es trägt den Namen eines Vogels. ; Der Name ist eine Abkürzung. ; Der Vogel gilt als diebisch. | Der Name steht für „Elektronische Steuererklärung“ — und der schwarz-weiße Vogel ist gleich das Logo.
C E | Welche Farbe hat die Umweltplakette für die sauberste Schadstoffgruppe? | Grün | Gelb ; Rot ; Blau | Sie erlaubt die Fahrt in alle Umweltzonen. ; Es ist die Farbe für „freie Fahrt“ an der Ampel. ; Es ist auch die Farbe von Gras. | Mit roten und gelben Plaketten darf man in die meisten Umweltzonen nicht mehr hineinfahren.
C E | Welche Farbe haben die Briefkästen der Deutschen Post? | Gelb | Rot ; Blau ; Grün | Es ist die Farbe des Post-Logos. ; Auch die Postautos tragen sie. ; In Großbritannien sind Briefkästen dagegen rot. | Das schwarze Posthorn auf gelbem Grund ist seit Jahrzehnten das Markenzeichen der Post.
W M | Die Hundesteuer wird in Deutschland vom Bund erhoben. | falsch | Die Hundesteuer ist eine Gemeindesteuer — ihre Höhe unterscheidet sich deshalb stark von Ort zu Ort.
W H | In Deutschland muss man seinen Personalausweis immer bei sich tragen. | falsch | Es gibt eine Ausweispflicht, aber keine Mitführpflicht — man muss den Ausweis besitzen und auf Verlangen vorlegen können.
W H | Kinder bis zum vollendeten achten Lebensjahr müssen mit dem Fahrrad auf dem Gehweg fahren. | wahr | Bis zum zehnten Geburtstag dürfen sie den Gehweg noch nutzen — eine Aufsichtsperson darf sie dabei begleiten.
S H | Aus wie vielen Ziffern besteht die steuerliche Identifikationsnummer? | 11 | Ziffern | 20 | 5 | 30 | Mehr als acht. ; Weniger als 15. ; Eine zweistellige Zahl. | Die Steuer-ID bekommt jeder schon als Baby — sie gilt ein Leben lang.
S H | Wie viele Stunden darf die werktägliche Arbeitszeit laut Arbeitszeitgesetz im Regelfall höchstens betragen? | 8 | Stunden | 20 | 1 | 24 | Mehr als sechs. ; Weniger als zehn. ; Ein klassischer Vollzeit-Arbeitstag. | Mit Ausgleich sind bis zu zehn Stunden erlaubt — im Durchschnitt muss man aber wieder auf acht kommen.
S M | Wie viel Gramm darf ein Standardbrief der Deutschen Post höchstens wiegen? | 20 | Gramm | 20 | 1 | 1000 | Mehr als zehn Gramm. ; Weniger als 50 Gramm. ; Etwa drei Blatt Papier samt Umschlag. | Schwerere Briefe bis 50 Gramm verschickt man als Kompaktbrief.
O E | Sortiere diese Papierformate nach ihrer Größe — das kleinste zuerst. | DIN A6 = 105 × 148 mm ; DIN A5 = 148 × 210 mm ; DIN A4 = 210 × 297 mm ; DIN A3 = 297 × 420 mm | Je größer die Zahl, desto kleiner das Blatt. ; Das Postkartenformat ist am kleinsten. ; Das doppelte Schreibblatt kommt zuletzt. | Jedes DIN-Format entsteht durch Halbieren des nächstgrößeren — DIN A0 ist genau einen Quadratmeter groß.
M M | Welche ZWEI dieser Dinge gehören nicht in eine Haustonne, sondern zu einer Sammelstelle? | Batterien ; Energiesparlampen | Bananenschale ; Joghurtbecher ; Zeitung ; Kaffeefilter | Beide enthalten Schadstoffe. ; Man kann sie im Handel zurückgeben. ; Die falschen gehören in Bio-, Gelbe oder Papiertonne. | Batterien enthalten Schwermetalle, Energiesparlampen Quecksilber — Händler müssen sie zurücknehmen.
M M | Welche ZWEI dieser Dokumente muss man beim Autofahren in Deutschland dabeihaben? | Führerschein ; Fahrzeugschein | Fahrzeugbrief ; Reisepass ; TÜV-Bericht ; Versicherungspolice | Eines beweist, dass man fahren darf. ; Das andere gehört zum Auto. ; Offiziell heißt eines „Zulassungsbescheinigung Teil I“. | Den Fahrzeugbrief — die Zulassungsbescheinigung Teil II — bewahrt man dagegen sicher zu Hause auf.

@ dialekte_sprache
E E | Welche Redewendung ist hier gesucht? | 🍅👀 | Tomaten auf den Augen haben | Rot sehen ; Große Augen machen ; Ein Auge zudrücken | Man übersieht etwas Offensichtliches. ; Etwas Rotes versperrt den Blick. ; Gesagt wird es oft vorwurfsvoll. | Die Wendung spielt vermutlich auf gerötete, verquollene Augen an, mit denen man schlecht sieht.
E E | Welche Redewendung ist hier gesucht? | 🚉🤷 | Ich verstehe nur Bahnhof | Ich glaub, mein Schwein pfeift ; Da ist der Zug abgefahren ; Ich bin im falschen Film | Man versteht überhaupt nichts. ; Es hat mit der Eisenbahn zu tun. ; Soldaten sollen es im Ersten Weltkrieg geprägt haben. | Kriegsmüde Soldaten wollten angeblich nur noch eines hören: den Bahnhof für die Heimfahrt.
E E | Welche Redewendung ist hier gesucht? | 🐱🛍️💰 | Die Katze im Sack kaufen | Die Katze aus dem Sack lassen ; Für die Katz sein ; Katzenwäsche machen | Es geht um einen Kauf. ; Man sieht die Ware vorher nicht. ; Betrüger sollen auf Märkten statt eines Ferkels ein Tier mit Schnurrhaaren verkauft haben. | Wer die Katze im Sack kauft, erwirbt etwas ungeprüft — und erlebt womöglich eine böse Überraschung.
E M | Welche Redewendung ist hier gesucht? | 🐕⚰️📍 | Da liegt der Hund begraben | Da steppt der Bär ; Auf den Hund gekommen ; Schlafende Hunde wecken | Man hat den Kern eines Problems gefunden. ; Ein Tier kommt darin vor. ; Es geht um eine Stelle unter der Erde. | Die Herkunft ist umstritten — eine Deutung sieht im „Hund“ den Wächter eines vergrabenen Schatzes.
E U | Welche Redewendung ist hier gesucht? | 🦉🏛️ | Eulen nach Athen tragen | Den Vogel abschießen ; Eine Nachteule sein ; Mit den Hühnern schlafen gehen | Man tut etwas völlig Überflüssiges. ; Die Wendung stammt aus der Antike. ; Das Tier war Symbol einer griechischen Stadt. | In Athen gab es Eulen im Überfluss — und die Eule der Göttin Athene zierte sogar die Münzen.
C M | Was ist im Rheinland ein „I-Dötzchen“? | Ein Schulanfänger | Ein kleiner Karnevalsorden ; Ein Stück Kuchen ; Ein neugeborenes Kalb | Man sieht es mit großer Schultüte. ; Es ist klein und jung. ; Der erste Schultag ist sein großer Tag. | „Dötz“ bedeutet im Rheinischen kleines Kind — das „I“ soll auf den ersten Buchstaben verweisen, den man früher schreiben lernte.
C M | Was ist in Norddeutschland ein „Feudel“? | Ein Wischlappen | Ein Fischernetz ; Ein Regenmantel ; Ein Kopfkissen | Man braucht ihn beim Putzen. ; Er wird feucht über den Boden gezogen. ; Seeleute schrubben damit das Deck. | Im Süden sagt man eher „Putzlumpen“ — der Feudel ist typisch für Hamburg und die Küste.
C H | Was meint man, wenn man einen Kaffee als „Plörre“ bezeichnet? | Er ist dünn und schmeckt wässrig | Er ist extrem stark ; Er ist mit Schnaps versetzt ; Er wird eiskalt serviert | Es ist kein Lob. ; Das Wort ist vor allem im Norden und Westen verbreitet. ; Gemeint ist eine trübe, dünne Brühe. | „Plörre“ nennt man jedes fade, verwässerte Getränk — am häufigsten schlechten Kaffee.
W E | „Servus“ sagt man in Bayern nur zur Begrüßung. | falsch | „Servus“ — lateinisch für „Diener“ — passt zum Hallo genauso wie zum Tschüss.
W M | In der Pfalz und im Saarland nennt man Kartoffeln „Grumbeere“. | wahr | Das Wort geht auf „Grundbirne“ zurück — eine Frucht, die man aus dem Boden holt.
S U log | Wie viele Sorben leben ungefähr in Deutschland? | 60000 | Menschen | 30 | 1000 | 1000000 | Mehr als 10.000. ; Weniger als 100.000. ; Etwa so viele, wie eine mittelgroße Stadt Einwohner hat. | Die westslawische Minderheit lebt vor allem in der Lausitz — Ortsschilder sind dort zweisprachig.
O H | Sortiere diese „Wörter des Jahres“ chronologisch — das früheste zuerst. | Wutbürger = 2010 ; GroKo = 2013 ; postfaktisch = 2016 ; Zeitenwende = 2022 | Der Protestbürger kam zuerst. ; Die Regierungsabkürzung folgte drei Jahre später. ; Das Wort aus einer Kanzlerrede zum Ukraine-Krieg ist am jüngsten. | Die Gesellschaft für deutsche Sprache kürt das Wort des Jahres seit 1971.
M M | Welche DREI dieser deutschen Wörter benutzt man auch im Englischen? | Angst ; Zeitgeist ; Wanderlust | Handy ; Beamer ; Oldtimer | Eines beschreibt eine Furcht. ; Eines den Geist einer Epoche. ; Eines die Lust am Reisen. | Handy, Beamer und Oldtimer klingen englisch, sind aber deutsche Scheinanglizismen.
M U | Welche DREI dieser Wörter stammen aus dem Jiddischen? | Schlamassel ; meschugge ; pleite | Kuddelmuddel ; Firlefanz ; Klimbim | Eines beschreibt eine verfahrene Lage. ; Eines bedeutet verrückt. ; Eines beschreibt jemanden ohne Geld. | Viele jiddische Wörter kamen über die Händlersprache ins Deutsche — auch „Tacheles“ und „Ganove“.

@ werbung_slogans
E U | Welche Werbefigur ist hier gesucht? | 🦎👞📖 | Lurchi | Mainzelmännchen ; HB-Männchen ; Meister Proper | Die Figur wirbt seit den 1930ern für Schuhe. ; Ihre Abenteuer erschienen als Comichefte. ; Ihr Ruf lautet „Salamander lebe hoch!“. | Lurchi ist das Maskottchen der Schuhfirma Salamander aus Kornwestheim.
C M | Für welche Marke warb der Slogan „Ich will so bleiben, wie ich bin“? | Du darfst | Lätta ; Rama ; Actimel | Es ist eine Lebensmittelmarke. ; Sie steht für kalorienreduzierte Produkte. ; Ihr Name klingt wie eine Erlaubnis. | Der Werbespruch lief ab den 1970er-Jahren und wurde zum geflügelten Wort.
C E | Welcher Baumarkt fragte in der Werbung „Wie, wo, was weiß …?“ | OBI | Hornbach ; Toom ; Bauhaus | Sein Logo ist orange. ; Der Name klingt wie ein Spitzname. ; Er hat nur drei Buchstaben. | Der Jingle gehört zu den bekanntesten Baumarkt-Melodien Deutschlands.
C E | Welche Firma reimt in ihrer Radiowerbung „… repariert, … tauscht aus“? | Carglass | ATU ; Pitstop ; Vergölst | Es geht um Autoscheiben. ; Die Firma repariert Steinschläge. ; Der Name enthält das englische Wort für Glas. | Der Jingle gilt als einer der hartnäckigsten Ohrwürmer im deutschen Radio.
C H | Mit welchem Slogan warb Mercedes-Benz jahrzehntelang vor „Das Beste oder nichts“? | Ihr guter Stern auf allen Straßen | Freude am Fahren ; Vorsprung durch Technik ; Aus Liebe zum Automobil | Der Slogan bezieht sich auf das Markenlogo. ; Er lief über viele Jahrzehnte. ; Die falschen gehören zu BMW, Audi und Volkswagen. | Der dreizackige Stern steht für Motoren zu Lande, zu Wasser und in der Luft.
W E | „Wie das Land, so das Jever“ ist der Slogan einer friesischen Biermarke. | wahr | Jever aus Friesland wirbt seit Jahrzehnten mit Dünen, Strand und dem Versprechen „friesisch herb“.
W M | Der Slogan „Respekt, wer's selber macht“ gehört zu OBI. | falsch | Mit „Respekt, wer's selber macht“ wirbt die Baumarktkette Toom.
S U | In welchem Jahr lief im deutschen Fernsehen der erste Werbespot? | 1956 | Jahr | 3 | 1930 | 1990 | Wenige Jahre nach dem Start des Fernsehens. ; In den 1950er-Jahren. ; Im Jahr der Olympischen Spiele von Melbourne. | Am 3. November 1956 warben Liesl Karlstadt und Beppo Brem im Bayerischen Rundfunk für Persil.
S U | Seit welchem Jahr ist Zigarettenwerbung im deutschen Fernsehen verboten? | 1975 | Jahr | 3 | 1950 | 2010 | Lange vor dem Rauchverbot in Kneipen. ; In den 1970er-Jahren. ; Zur Mitte des Jahrzehnts. | Im Kino und auf Plakaten durfte dagegen noch Jahrzehnte länger für Zigaretten geworben werden.
O U | Sortiere diese Werbefiguren nach ihrem ersten Auftritt — die älteste zuerst. | Lurchi (Salamander) = 1937 ; HB-Männchen = 1957 ; Frau Antje = 1961 ; Lila Milka-Kuh = 1972 | Der Schuh-Salamander ist am ältesten. ; Das cholerische Zigaretten-Männchen folgt. ; Die lila Kuh ist die jüngste. | Frau Antje brachte als freundliche Holländerin jahrzehntelang Käse aus den Niederlanden ins deutsche Fernsehen.
M E | Welche ZWEI dieser Slogans gehören zu Biermarken? | Eine Perle der Natur ; Das einzig Wahre | Da weiß man, was man hat ; Wer hat's erfunden? ; Quadratisch. Praktisch. Gut. ; Nichts ist unmöglich | Einer gehört zu einer Brauerei aus dem Siegerland. ; Der andere zu einer aus dem Sauerland. ; Die falschen werben für Waschmittel, Kräuterbonbons, Schokolade und Autos. | „Eine Perle der Natur“ ist Krombacher, „Das einzig Wahre“ Warsteiner.

@ feiertage_traditionen
E E | Welche Stadt ist hier gesucht? | 🎭⛪🍺 | Köln | Mainz ; Düsseldorf ; Aachen | Im Karneval ruft man hier „Alaaf“. ; Ihr Wahrzeichen ist eine gotische Kathedrale. ; Das Bier wird in schmalen Stangen serviert. | Der Kölner Dom war bei seiner Fertigstellung 1880 für kurze Zeit das höchste Gebäude der Welt.
E E | Welche Tradition ist hier gesucht? | 🎄🍷🛍️ | Weihnachtsmarkt | Oktoberfest ; Flohmarkt ; Kirmes | Er findet im Advent statt. ; Es duftet nach gebrannten Mandeln. ; Man trinkt Glühwein aus Tassen. | Viele Märkte geben den Glühwein in eigenen Sammeltassen mit Pfand aus — beliebte Souvenirs.
E M | Welcher Brauch ist hier gesucht? | 🧙‍♀️🧹⛰️🔥 | Walpurgisnacht | Halloween ; Fastnacht ; Johannisnacht | Er findet in der Nacht zum 1. Mai statt. ; Im Harz tanzen dann Hexen. ; Der Brocken ist sein berühmtester Schauplatz. | Goethe verewigte die Hexennacht auf dem Brocken in seinem „Faust“.
E H | Welche Stadt ist hier gesucht? | 🎄👼🌭 | Nürnberg | Dresden ; Aachen ; Augsburg | Hier eröffnet ein Christkind den Weihnachtsmarkt. ; Die Stadt ist für kleine Rostbratwürste bekannt. ; Sie liegt in Franken. | Beim Christkindlesmarkt spricht das Nürnberger Christkind jedes Jahr einen feierlichen Prolog.
C M | Was unternimmt man in Norddeutschland bei einer „Kohlfahrt“? | Eine Winterwanderung mit Bollerwagen und anschließendem Grünkohlessen | Eine Bootsfahrt zu den Kohlfeldern ; Eine Kutschfahrt zum Weihnachtsmarkt ; Eine Wallfahrt zu einer Kirche | Sie findet im Winter statt. ; Unterwegs gibt es Spiele und Schnaps. ; Am Ende wird ein „Kohlkönig“ gekürt. | Besonders beliebt ist die Kohlfahrt in Bremen und Oldenburg — gern mit Pinkel zum Grünkohl.
C U | In welcher Region schmückt man zu Ostern traditionell Brunnen mit bemalten Eiern? | In der Fränkischen Schweiz | Im Allgäu ; Im Spreewald ; Im Sauerland | Die Region liegt in Oberfranken. ; Der Brauch ehrt das Wasser in einer wasserarmen Karstlandschaft. ; Einer der bekanntesten Brunnen steht in Bieberbach. | Mit Tausenden bemalten Eiern und Girlanden locken die Osterbrunnen jedes Jahr Busladungen voller Besucher an.
C E | Was schenkt man in Deutschland traditionell zum Einzug in eine neue Wohnung? | Brot und Salz | Eier und Mehl ; Wein und Käse ; Kerzen und Blumen | Es sind zwei Grundnahrungsmittel. ; Eines davon wird gebacken. ; Das andere würzt fast jedes Essen. | Brot soll dafür sorgen, dass nie Hunger herrscht — Salz war früher kostbar und steht für Würze im Leben.
C E | Welches Gericht kommt an Heiligabend in deutschen Familien am häufigsten auf den Tisch? | Kartoffelsalat mit Würstchen | Gänsebraten ; Karpfen blau ; Raclette | Es ist ein einfaches Gericht. ; Es lässt sich gut vorbereiten. ; Dazu gehören Wiener oder Frankfurter. | Das schnelle Essen lässt Zeit für die Bescherung — der Festtagsbraten folgt meist am ersten Feiertag.
W M | Der Internationale Frauentag am 8. März ist in Berlin ein gesetzlicher Feiertag. | wahr | Berlin führte ihn 2019 als Feiertag ein, Mecklenburg-Vorpommern folgte 2023.
W E | Der Nikolaustag am 6. Dezember ist in Bayern ein gesetzlicher Feiertag. | falsch | Der Nikolaustag ist in keinem Bundesland ein gesetzlicher Feiertag — gearbeitet wird ganz normal.
S M | Wie viele Tage liegen zwischen Aschermittwoch und Ostersonntag? | 46 | Tage | 10 | 10 | 100 | Mehr als 40. ; Weniger als 50. ; Die Sonntage zählen bei der Fastenzeit nicht mit. | Ohne die sechs Sonntage bleiben genau 40 Fastentage — nach dem Vorbild von Jesu Fasten in der Wüste.
S H | Wie viele Millionen Besucher kamen 2023 auf das Münchner Oktoberfest? | 7.2 | Mio. | 20 | 1 | 20 | Mehr als fünf Millionen. ; Weniger als zehn Millionen. ; Es war ein Rekordjahr. | 2023 dauerte die Wiesn wegen des Feiertags am 3. Oktober ausnahmsweise 18 Tage.
O M | Sortiere diese Hochzeitstage nach der Zahl der Ehejahre — den frühesten zuerst. | Hölzerne Hochzeit = 5 Jahre ; Rosenhochzeit = 10 Jahre ; Rubinhochzeit = 40 Jahre ; Diamantene Hochzeit = 60 Jahre | Holz kommt zuerst. ; Die Blumen folgen. ; Der härteste Edelstein kommt zuletzt. | Silber (25) und Gold (50) kennt jeder — nach 65 Jahren folgt sogar die Eiserne Hochzeit.
O E | Ordne diese Bräuche nach ihrem Termin im Jahreslauf — vom Jahresanfang an. | Sternsingen = um den 6. Januar ; Weiberfastnacht = im Februar oder März ; Walpurgisnacht = 30. April ; Martinsumzug = um den 11. November | Die Könige kommen zuerst. ; Der Karneval folgt. ; Die Laternen leuchten zuletzt. | Sternsinger sammeln als Heilige Drei Könige verkleidet Spenden für Kinder in Not.
M E | Welche ZWEI dieser Städte gelten als Karnevalshochburgen am Rhein? | Düsseldorf ; Mainz | München ; Hamburg ; Leipzig ; Rostock | In einer ruft man „Helau“ und feiert Altweiber. ; Die andere ist Landeshauptstadt von Rheinland-Pfalz. ; Beide liegen direkt am Rhein. | Zusammen mit Köln bilden Düsseldorf und Mainz das Dreigestirn der großen Rosenmontagszüge.

@ made_in_germany
E E | Welches Mitbringsel ist hier gesucht? | 🐦🕰️🌲 | Kuckucksuhr | Standuhr ; Spieluhr ; Sonnenuhr | Sie stammt aus einem Mittelgebirge im Südwesten. ; Zur vollen Stunde ruft ein Vogel. ; Sie hängt an der Wand. | Viele Kuckucksuhren werden bis heute von Gewichten in Tannenzapfenform angetrieben.
E E | Welche Erfindung ist hier gesucht? | 🏖️🧺🪑 | Strandkorb | Liegestuhl ; Sonnenschirm ; Hängematte | Man findet ihn an Nord- und Ostsee. ; Er schützt vor Wind. ; Er ist aus Geflecht gebaut. | Der Rostocker Korbmacher Wilhelm Bartelmann baute den ersten für eine rheumakranke Dame.
E M | Welche Erfindung ist hier gesucht? | ⛽🔥🚛 | Dieselmotor | Ottomotor ; Dampfmaschine ; Elektromotor | Er zündet ohne Zündkerze. ; Er wurde in den 1890ern bei MAN in Augsburg entwickelt. ; Er trägt den Namen seines Erfinders. | Rudolf Diesel wurde in Paris geboren — 1913 verschwand er bei einer Überfahrt nach England von Bord eines Dampfers.
C H | In welcher sächsischen Stadt ist die deutsche Feinuhrmacherei zu Hause? | Glashütte | Freiberg ; Meißen ; Chemnitz | Die Kleinstadt liegt im Osterzgebirge. ; Hier sitzt die Manufaktur A. Lange & Söhne. ; Im Namen steckt ein Werkstoff für Fenster. | Seit Ferdinand Adolph Lange 1845 hier seine Werkstatt gründete, gilt der Ort als Zentrum edler Uhren.
C M | In welcher hessischen Stadt sitzt der Kamerahersteller Leica? | Wetzlar | Jena ; Darmstadt ; Kassel | Die Stadt liegt an der Lahn. ; Hier entstand in den 1920ern die erste Kleinbildkamera in Serie. ; Der Name beginnt mit W. | Die Ur-Leica von Oskar Barnack machte das Kleinbildformat mit 35-Millimeter-Film weltweit populär.
C U | In welcher Stadt hat der Schreibgerätehersteller Lamy seinen Sitz? | Heidelberg | Nürnberg ; Stein bei Nürnberg ; Hannover | Die Stadt liegt am Neckar. ; Sie hat eine berühmte Schlossruine. ; Dort steht die älteste Universität Deutschlands. | Der Lamy-Füller „safari“ von 1980 ist bis heute ein Schulklassiker.
W U | Die ersten Porsche-356-Sportwagen wurden in Österreich gebaut. | wahr | Porsche fertigte die ersten 356 ab 1948 im Kärntner Gmünd — erst danach zog die Produktion nach Stuttgart.
W M | Die Kameramarke Leica ist nach ihrem Erfinder Oskar Leica benannt. | falsch | Der Name setzt sich aus „Leitz“ und „Camera“ zusammen — erfunden hat die Kamera Oskar Barnack.
S U | In welchem Jahr baute Wilhelm Bartelmann in Rostock den ersten Strandkorb? | 1882 | Jahr | 5 | 1800 | 1950 | Im 19. Jahrhundert. ; In der Kaiserzeit. ; Gut zehn Jahre nach der Reichsgründung. | Schon ein Jahr später vermietete seine Frau Strandkörbe in Warnemünde — der Beginn eines Geschäftsmodells.
O H | Sortiere diese Autohersteller nach ihrem Gründungsjahr — den ältesten zuerst. | Audi = 1909 ; BMW = 1916 ; Porsche = 1931 ; Volkswagen = 1937 | August Horch gründete den ältesten. ; Die Bayern folgten im Ersten Weltkrieg. ; Der Volkswagen-Konzern ist der jüngste. | „Audi“ ist Latein für „Horch!“ — August Horch durfte seinen eigenen Namen nicht mehr als Marke verwenden.
O H | Sortiere diese Marken nach ihrem Gründungsjahr — die älteste zuerst. | Nivea = 1911 ; Haribo = 1920 ; Adidas = 1949 ; Playmobil = 1974 | Die Hautcreme kommt zuerst. ; Die Goldbären-Firma folgt. ; Die Spielfiguren sind die jüngsten. | Die ersten Playmobil-Figuren waren Ritter, Indianer und Bauarbeiter.
M M | Welche DREI dieser Alltagshelfer wurden in Deutschland erfunden? | MP3 ; Dübel ; Kaffeefilter | Kugelschreiber ; Reißverschluss ; Haftnotizzettel | Einer entstand an einem Fraunhofer-Institut. ; Einer hält Schrauben in der Wand. ; Einen erfand eine Dresdner Hausfrau. | Den Kugelschreiber machte László Bíró bekannt, Reißverschluss und Haftnotizen wurden in den USA marktreif.
M H | Welche DREI dieser Unternehmen stammen aus Baden-Württemberg? | Bosch ; Steiff ; Märklin | Miele ; Haribo ; Siemens | Eines begann mit Zündanlagen für Motoren. ; Eines näht Teddybären. ; Eines baut Modelleisenbahnen. | Miele sitzt in Gütersloh, Haribo in Grafschaft bei Bonn und Siemens in München.
"""
