"""Extra questions, wave 2: Essen & Trinken (format: see tools/content/merge_extra.py)."""
KAT = "essen_trinken"
REGION = "global"
DATA = r"""
@ deutsche_kueche de
E E | Welches Gericht ist hier gesucht? | 🧊🦵🐷 | Eisbein | Kassler ; Sülze ; Leberkäse | Es ist ein Stück vom Schwein. ; Der Name klingt nach Winter. ; In Berlin isst man es mit Sauerkraut und Erbspüree. | Eisbein ist gepökelte, gekochte Schweinshaxe — der Name kommt vermutlich vom Knochen, aus dem man früher Kufen für Schlittschuhe schnitzte.
E E | Welche Torte ist hier gesucht? | 🌲🌲🍒🎂 | Schwarzwälder Kirschtorte | Frankfurter Kranz ; Donauwelle ; Prinzregententorte | Sie ist nach einem Mittelgebirge benannt. ; Sie besteht aus Schokobiskuit und Sahne. ; Obenauf liegen rote Früchte und Schokoraspeln. | Laut den Leitsätzen für Feine Backwaren muss der Kirschwasser-Geschmack einer echten Schwarzwälder deutlich wahrnehmbar sein.
E E | Welches Gericht ist hier gesucht? | 🧀🐦🧅 | Käsespätzle | Käsefondue ; Zwiebelkuchen ; Flammkuchen | Es stammt aus Schwaben und dem Allgäu. ; Obenauf kommen Röstzwiebeln. ; Der Vogel verrät die Teigwaren. | Der Name Spätzle wird meist als „kleine Spatzen“ gedeutet — für Käsespätzle schichtet man sie mit würzigem Bergkäse.
E M | Welcher Kuchen ist hier gesucht? | 🐝💉🍰 | Bienenstich | Honigkuchen ; Butterkuchen ; Donauwelle | Er wird meist als Blechkuchen gebacken. ; Obenauf liegt eine knusprige Mandelschicht. ; Ein Insekt steckt im Namen. | Unter der karamellisierten Mandel-Honig-Kruste steckt beim Bienenstich meist eine Vanillecreme.
C E | Was sind Schupfnudeln? | Fingerdicke Nudeln aus Kartoffelteig | Dünne Bandnudeln aus Hartweizen ; Mit Fleisch gefüllte Teigtaschen ; Kleine Klöße aus Grieß | Man brät sie gern mit Sauerkraut an. ; Sie sind an beiden Enden spitz. ; Die Hauptzutat ist eine Knolle. | In Baden und Schwaben heißen Schupfnudeln wegen ihrer Form auch „Bubespitzle“.
C E | Was ist ein „Hackepeter“? | Rohes, gewürztes Schweinehackfleisch | Ein Fleischklops in Kapernsoße ; Eine Bratwurst aus Rind ; Ein gefüllter Kohlkopf | Man isst es auf Brötchen. ; Oft kommen rohe Zwiebeln dazu. ; Anderswo heißt es Mett. | Hackepeter ist vor allem in Nord- und Ostdeutschland der Name für Mett — klassisch mit Zwiebeln auf dem Brötchen.
C M | Woraus werden echte Thüringer Klöße hergestellt? | Aus rohen und gekochten Kartoffeln | Aus altbackenen Brötchen ; Aus Grieß und Milch ; Aus Mehl und Hefe | Sie sind hellgelb und etwas zäh. ; In der Mitte steckt oft ein gerösteter Brotwürfel. ; Die Hauptzutat wächst unter der Erde. | Für Thüringer Klöße wird geriebene rohe Kartoffelmasse ausgepresst und mit heißem Kartoffelbrei gebrüht.
C H | Was verstand man in der DDR unter einem „Jägerschnitzel“? | Eine panierte, gebratene Scheibe Jagdwurst | Ein Schnitzel aus Wildschweinfleisch ; Ein Schweineschnitzel mit Pilzsoße ; Ein Hackbraten mit Speck | Es war besonders in Schulkantinen beliebt. ; Dazu gab es oft Nudeln mit Tomatensoße. ; Die Hauptzutat stammt aus der Wursttheke. | Im Westen steht „Jägerschnitzel“ für ein Schnitzel mit Pilzsoße — im Osten für panierte Jagdwurst mit Makkaroni.
C U | Welche Stadt in Sachsen-Anhalt ist als „Baumkuchenstadt“ berühmt? | Salzwedel | Quedlinburg ; Wernigerode ; Dessau | Sie liegt in der Altmark. ; Der Kuchen wird dort Schicht für Schicht am Drehspieß gebacken. ; Im Namen steckt ein Mineral aus der Küche. | Baumkuchen ist auch in Japan beliebt — dort machte ihn der deutsche Konditor Karl Juchheim ab 1919 bekannt.
W U | Das Gebäck „Leipziger Lerche“ ersetzte im 19. Jahrhundert ein echtes Gericht aus Singvögeln. | wahr | Nachdem Sachsen 1876 den Lerchenfang verboten hatte, backten Konditoren die Lerche aus Mürbeteig, Marzipan und einer Kirsche nach.
W H | „Dresdner Stollen“ darf nur in Dresden und der umliegenden Region gebacken werden. | wahr | Der Name ist in der EU als geschützte geografische Angabe eingetragen — ein Schutzverband wacht über das Stollensiegel.
W E | Spätzle werden traditionell aus Kartoffelteig gemacht. | falsch | Spätzleteig besteht aus Mehl, Eiern, Wasser und Salz — Kartoffelteig gehört zu Schupfnudeln.
S M log | Wie viele Brotspezialitäten sind im Deutschen Brotregister eingetragen (Stand 2020er-Jahre)? | 3200 | Sorten | 30 | 100 | 50000 | Es sind mehr als 1.000. ; Es sind weniger als 5.000. ; Die Zahl beginnt mit einer 3. | Das Deutsche Brotinstitut zählt über 3.200 Brote — seit 2014 ist die deutsche Brotkultur immaterielles Kulturerbe.
S H | Wie viele Kilogramm Fleisch isst ein Mensch in Deutschland im Schnitt pro Jahr (Stand 2023)? | 52 | kg | 20 | 10 | 150 | Mehr als 30 Kilogramm. ; Weniger als 70 Kilogramm. ; Etwa ein Kilogramm pro Woche. | 2023 lag der Pro-Kopf-Verzehr bei knapp 52 Kilogramm — so niedrig wie seit Jahrzehnten nicht.
O M | Sortiere diese Gerichte nach ihrer Heimatstadt — die nördlichste zuerst. | Hamburger Pannfisch = Hamburg ; Leipziger Allerlei = Leipzig ; Frankfurter Grüne Soße = Frankfurt am Main ; Weißwurst = München | Der Fisch kommt aus dem hohen Norden. ; Das Gemüsegericht stammt aus Sachsen. ; Die Wurst liegt am weitesten im Süden. | Hamburg liegt auf gut 53,5 Grad Nord, München auf 48 Grad — Leipzig und Frankfurt liegen dazwischen.
M E | Welche DREI dieser Spezialitäten stammen traditionell aus Bayern? | Weißwurst ; Obatzda ; Leberkäse | Labskaus ; Maultaschen ; Handkäs mit Musik | Eine isst man vor dem Mittagsläuten. ; Eine ist ein Käseaufstrich. ; Eine enthält trotz Namen meist weder Leber noch Käse. | Labskaus stammt aus Norddeutschland, Maultaschen aus Schwaben und Handkäs aus Hessen.

@ internationale_kueche
E E | Welches Gericht ist hier gesucht? | 🐟🍟🇬🇧 | Fish and Chips | Fischstäbchen ; Backfisch mit Remoulade ; Kibbeling | Früher wurde es in Zeitungspapier eingewickelt. ; Man träufelt Malzessig darüber. ; Der Fisch ist meist Kabeljau oder Schellfisch. | Fish and Chips gilt seit dem 19. Jahrhundert als britisches Nationalgericht — oft mit Erbsenpüree, den „Mushy Peas“.
E E | Welche Süßspeise ist hier gesucht? | 👑🥞🇦🇹 | Kaiserschmarrn | Palatschinken ; Apfelstrudel ; Germknödel | Man serviert ihn gern mit Zwetschgenröster. ; Der Teig wird in der Pfanne zerrupft. ; Ein Herrscher steckt im Namen. | Der Legende nach wurde der Kaiserschmarrn für Kaiser Franz Joseph I. erfunden.
E E | Welche Pizza ist hier gesucht? | 🍕👸🇮🇹 | Pizza Margherita | Pizza Quattro Stagioni ; Pizza Marinara ; Pizza Capricciosa | Ihre Farben erinnern an die italienische Flagge. ; Belegt ist sie mit Tomate, Mozzarella und Basilikum. ; Sie trägt den Namen einer Königin. | Der Legende nach wurde sie 1889 in Neapel für Königin Margherita von Savoyen gebacken.
C E | Welche Zutat färbt die osteuropäische Suppe Borschtsch tiefrot? | Rote Bete | Tomaten ; Paprika ; Rotkohl | Es ist ein Wurzelgemüse. ; Es färbt beim Schneiden die Finger. ; Es steckt auch im norddeutschen Labskaus. | Die ukrainische Borschtsch-Kultur steht seit 2022 auf der UNESCO-Liste des dringend zu erhaltenden Kulturerbes.
C E | Aus welchem Land stammen die Blätterteig-Törtchen „Pastéis de Nata“? | Portugal | Spanien ; Brasilien ; Italien | Man bekommt sie in jeder Bäckerei in Lissabon. ; Sie sind mit Eiercreme gefüllt. ; Das Land liegt ganz im Westen Europas. | Erfunden haben sie der Überlieferung nach Mönche des Hieronymus-Klosters in Belém.
C H | Mit welcher Nudelsorte wird Ragù alla bolognese in Bologna traditionell serviert? | Tagliatelle | Spaghetti ; Penne ; Farfalle | Es sind Bandnudeln. ; Sie werden meist mit Ei gemacht. ; Sie sind schmaler als Pappardelle. | In Bologna gehört das Ragù auf breite Eierbandnudeln — das offizielle Rezept wurde 1982 bei der Handelskammer hinterlegt.
C H | Welche Nudelform bedeutet übersetzt „kleine Würmer“? | Vermicelli | Linguine ; Orecchiette ; Farfalle | Die Nudeln sind sehr dünn. ; In Asien gibt es sie auch aus Reismehl. ; Das italienische Wort „verme“ steckt darin. | Linguine sind „kleine Zungen“, Orecchiette „Öhrchen“ und Farfalle „Schmetterlinge“.
C U | Wie heißt das philippinische Schmorgericht, bei dem Fleisch in Essig, Sojasoße und Knoblauch gegart wird? | Adobo | Lechon ; Sinigang ; Pancit | Es gilt als inoffizielles Nationalgericht der Philippinen. ; Meist nimmt man Huhn oder Schwein. ; Den Namen gaben ihm spanische Kolonialherren. | Das spanische Wort „adobo“ heißt Marinade — die Kochtechnik gab es auf den Philippinen aber schon vorher.
W M | In Wien heißen Wiener Würstchen „Frankfurter“. | wahr | Der Metzger Johann Georg Lahner lernte in Frankfurt und verkaufte seine Würstchen ab 1805 in Wien als „Frankfurter“.
W E | Stäbchen senkrecht in eine Reisschale zu stecken gilt in Japan als höflich. | falsch | Senkrecht im Reis steckende Stäbchen erinnern an Opfergaben bei Beerdigungen und gelten als Tabu.
S H | In welchem Jahr eröffnete in Würzburg die erste Pizzeria Deutschlands? | 1952 | Jahr | 3 | 1900 | 2000 | Nach dem Zweiten Weltkrieg. ; In der frühen Bundesrepublik. ; Anfang der 1950er-Jahre. | Nicolino di Camillo eröffnete 1952 das „Sabbie di Capri“ — seine Gäste waren anfangs vor allem US-Soldaten.
O M | Sortiere diese Nudelsorten nach ihrer Breite — die schmalste zuerst. | Capellini = ≈ 1 mm ; Spaghetti = ≈ 2 mm ; Tagliatelle = ≈ 7 mm ; Pappardelle = ≈ 2–3 cm | Die dünnsten heißen „Engelshaar“. ; Die bekanntesten runden Nudeln kommen danach. ; Die breitesten passen gut zu Wildragù. | Capellini werden wegen ihrer Feinheit auch „Capelli d’angelo“ — Engelshaar — genannt.
M M | Welche DREI dieser Speisen gehören zur japanischen Küche? | Okonomiyaki ; Yakitori ; Tempura | Bibimbap ; Pho ; Dim Sum | Eine ist ein herzhafter Pfannkuchen. ; Eine sind gegrillte Hähnchenspieße. ; Die falschen stammen aus Korea, Vietnam und China. | Tempura brachten übrigens portugiesische Missionare im 16. Jahrhundert nach Japan.
M M | Welche ZWEI dieser Käse sind italienische Spezialitäten? | Gorgonzola ; Taleggio | Manchego ; Gouda ; Roquefort ; Appenzeller | Einer ist ein Blauschimmelkäse. ; Beide stammen aus der Lombardei. ; Die falschen kommen aus Spanien, den Niederlanden, Frankreich und der Schweiz. | Gorgonzola ist nach einem Ort bei Mailand benannt, Taleggio nach einem Tal bei Bergamo.

@ suessigkeiten_snacks
E E | Welche Süßigkeit ist hier gesucht? | 🐻🍬🌈 | Gummibärchen | Lakritzschnecken ; Brausebonbons ; Kaubonbons | Sie sind bunt und durchsichtig. ; Sie wurden 1922 in Bonn erfunden. ; Sie haben die Form eines Tieres. | Hans Riegel erfand 1922 den „Tanzbären“ — der Vorläufer der heutigen Goldbären.
E M | Welcher Wintersnack ist hier gesucht? | 🔥🌰❄️ | Heiße Maronen | Gebrannte Mandeln ; Bratäpfel ; Kartoffelpuffer | Man bekommt sie in Papiertüten auf dem Weihnachtsmarkt. ; Vor dem Rösten ritzt man die Schale ein. ; Es sind die Früchte der Edelkastanie. | Maronen stammen von der Edelkastanie — die Früchte der Rosskastanie sind dagegen ungenießbar.
E H | Welche Süßigkeit ist hier gesucht? | 🐌🖤🍬 | Lakritzschnecke | Schokoröllchen ; Zimtschnecke ; Salmiakpastille | Sie ist im Norden besonders beliebt. ; Man kann sie abrollen. ; Sie wird aus Süßholzsaft gemacht. | Aufgerollt ist eine Lakritzschnecke oft über einen Meter lang — in der Mitte steckt meist ein bunter Zuckerknopf.
C E | Wie heißen die winzigen bunten Zuckerkugeln, die oft in kleinen Plastikfläschchen verkauft werden? | Liebesperlen | Nonstop-Perlen ; Zuckerkristalle ; Brausekugeln | Man streut sie auch auf Kuchen. ; Sie sind kleiner als Erbsen. ; Ihr Name hat mit Zuneigung zu tun. | Liebesperlen bestehen fast nur aus Zucker und Lebensmittelfarbe — das Fläschchen mit Nuckel ist ein Kioskklassiker.
C E | In welcher Stadt steht das Schokoladenmuseum mit einem begehbaren Schokoladenbrunnen? | Köln | Hamburg ; Berlin ; München | Es liegt direkt am Rhein. ; Es wurde 1993 eröffnet. ; Vom Museum aus sieht man den Dom. | Im Kölner Schokoladenmuseum sprudelt ein rund drei Meter hoher Brunnen voller flüssiger Schokolade.
C H | Nach welchem Ort ist die Praline Ferrero Rocher benannt? | Nach einer Felsengrotte im Wallfahrtsort Lourdes | Nach einem Berg in den Dolomiten ; Nach einem Stadtteil von Turin ; Nach einem Weingut im Piemont | Der Firmenchef Michele Ferrero war sehr gläubig. ; „Rocher“ ist Französisch für Fels. ; Der Ort liegt in den Pyrenäen. | Michele Ferrero verehrte die Marienerscheinungen an der Grotte „Rocher de Massabielle“ in Lourdes.
C U | Wie hieß der Junge, dessen Foto von 1973 bis 2005 auf der Kinderschokolade-Packung zu sehen war? | Günter Euringer | Michael Kowalski ; Stefan Reuter ; Martin Wagner | Sein Vorname beginnt mit G. ; Er teilt den Vornamen mit dem Schriftsteller Grass. ; Sein Nachname beginnt mit E. | 2005 ersetzte Ferrero das Kultfoto durch ein neues Kindergesicht — Euringer wurde als „Kinderschokolade-Junge“ bekannt.
W M | Das Wort „Praline“ geht auf einen französischen Adligen zurück. | wahr | Der Koch des Grafen du Plessis-Praslin soll im 17. Jahrhundert gebrannte Mandeln erfunden haben — nach dem Grafen heißen sie „Praline“.
W M | Das klassische Kinder-Überraschungsei ist in den USA verboten. | wahr | US-Recht verbietet unessbare Gegenstände, die in Süßigkeiten eingeschlossen sind — erlaubt ist nur „Kinder Joy“ mit getrennter Spielzeughälfte.
W E | Weingummi enthält üblicherweise Wein. | falsch | Der Name stammt aus früheren Rezepturen — heutiges Weingummi enthält in aller Regel keinen Tropfen Wein.
S M | Bei ungefähr wie viel Grad Celsius platzt ein Popcorn-Maiskorn auf? | 180 | °C | 20 | 50 | 400 | Deutlich heißer als kochendes Wasser. ; Weniger als 300 Grad. ; Ungefähr die Temperatur eines Backofens für Kuchen. | Bei rund 180 °C steht das Wasser im Korn so unter Druck, dass die Schale platzt und die Stärke aufschäumt.
S U | In welchem Jahr kam der Oreo-Keks in den USA auf den Markt? | 1912 | Jahr | 5 | 1850 | 2000 | Vor dem Ersten Weltkrieg. ; Im Jahr des Titanic-Untergangs. ; Anfang des 20. Jahrhunderts. | Oreo wurde 1912 in New York von der National Biscuit Company eingeführt — heute Nabisco.
O U | Ordne diese Naschwerk-Spezialitäten geografisch: Die Stadt ganz im Norden kommt zuerst. | Lübecker Marzipan = Lübeck ; Dresdner Christstollen = Dresden ; Aachener Printen = Aachen ; Nürnberger Lebkuchen = Nürnberg | Die erste Stadt liegt an der Ostsee. ; Die sächsische Stadt liegt knapp nördlich der Kaiserstadt. ; Die fränkische Stadt liegt am weitesten im Süden. | Dresden liegt auf etwa 51,0 Grad Nord, Aachen auf 50,8 — ein knappes Rennen.
O M | Sortiere diese Lebensmittel nach ihrem Zuckeranteil — den niedrigsten zuerst. | Cola = ≈ 11 g pro 100 ml ; Tomatenketchup = ≈ 23 g pro 100 g ; Goldbären = ≈ 46 g pro 100 g ; Nutella = ≈ 56 g pro 100 g | Das Getränk kommt zuerst. ; Die Tomatensoße hat überraschend viel Zucker. ; Der Brotaufstrich ist mehr als zur Hälfte Zucker. | Nutella besteht zu gut 56 Prozent aus Zucker — mehr als Gummibärchen.
M U | Welche ZWEI dieser Süßigkeiten enthalten klassisch Marzipan? | Mozartkugel ; Bethmännchen | Toffifee ; Hanuta ; Raffaello ; Ferrero Küsschen | Eine stammt aus Salzburg. ; Die andere ist ein Frankfurter Weihnachtsgebäck. ; Die falschen setzen auf Haselnuss oder Kokos. | Die Mozartkugel hat einen Kern aus Pistazienmarzipan, Bethmännchen bestehen aus Marzipanmasse mit Mandelhälften.

@ bier_wein_getraenke
E E | Welcher Cocktail ist hier gesucht? | 🍍🥥🍹 | Piña Colada | Mai Tai ; Swimming Pool ; Blue Hawaiian | Er ist cremig und süß. ; Er enthält weißen Rum. ; Er stammt aus Puerto Rico. | Die Piña Colada ist seit 1978 das offizielle Nationalgetränk von Puerto Rico.
E M | Welcher Cocktail ist hier gesucht? | 🥃🍊🌅 | Tequila Sunrise | Mai Tai ; Aperol Spritz ; Campari Orange | Er schimmert von Gelb nach Rot. ; Grenadine sinkt im Glas nach unten. ; Die Spirituose stammt aus Mexiko. | Der Farbverlauf entsteht, weil der schwere Grenadinesirup unter den Orangensaft sinkt.
E H | Welcher Cocktail ist hier gesucht? | 🩸👸🍅 | Bloody Mary | Cosmopolitan ; Negroni ; Campari Soda | Er gilt als Katerdrink. ; Oft steckt eine Selleriestange im Glas. ; Neben Wodka ist Tomatensaft die Hauptzutat. | Wer die Namensgeberin war, ist umstritten — oft wird die englische Königin Maria I. genannt.
C H | Wie heißt der graue, blau bemalte Steinzeugkrug für Apfelwein in Hessen? | Bembel | Humpen ; Karaffe ; Stiefel | Man stellt ihn in Apfelweinwirtschaften auf den Tisch. ; Aus ihm schenkt man ins „Gerippte“ ein. ; Der Name beginnt mit B. | Das „Gerippte“ ist das typische Apfelweinglas mit Rautenmuster — der Bembel ist sein Nachschub.
C M | Wie heißt das schlanke 0,2-Liter-Glas, in dem Kölsch serviert wird? | Stange | Tulpe ; Willibecher ; Seidel | Es ist zylindrisch und schmal. ; Der Kellner, der „Köbes“, trägt sie im Kranz. ; Der Name klingt nach einem langen, geraden Stück Holz. | Der Köbes stellt so lange frische Stangen hin, bis man einen Bierdeckel aufs Glas legt.
C M | Wofür steht die Bierstil-Abkürzung „IPA“? | India Pale Ale | International Pilsner Ale ; Imperial Porter Ale ; Irish Pale Amber | Es ist ein stark gehopftes Bier. ; Der Stil entstand für lange Schiffsreisen. ; Das erste Wort ist ein Land in Asien. | Viel Hopfen machte das Bier im 19. Jahrhundert haltbar für die Reise von England in die Kolonie Indien.
C U | In welchem Land liegen die meisten offiziell anerkannten Trappistenbrauereien? | Belgien | Niederlande ; Deutschland ; Frankreich | Das Land ist berühmt für Pralinen und Pommes. ; Dort brauen Mönche in Chimay und Orval. ; Die Hauptstadt ist Sitz der EU-Kommission. | Echtes Trappistenbier muss unter Aufsicht von Trappistenmönchen in einem Kloster gebraut werden.
W E | Prosecco ist ein Schaumwein aus Spanien. | falsch | Prosecco stammt aus Venetien und Friaul in Italien — der bekannte spanische Schaumwein heißt Cava.
W H | Roséwein wird in der EU meist durch Mischen von Rot- und Weißwein hergestellt. | falsch | Stiller Rosé darf in der EU nicht aus Rot- und Weißwein verschnitten werden — die Farbe stammt aus kurzem Kontakt mit roten Traubenschalen.
W M | Tonic Water leuchtet unter Schwarzlicht. | wahr | Das Chinin im Tonic Water fluoresziert unter UV-Licht bläulich — ein beliebter Partytrick.
S H | Wie viele bestimmte Anbaugebiete für Qualitätswein gibt es in Deutschland? | 13 | Anbaugebiete | 20 | 1 | 50 | Mehr als zehn. ; Weniger als 20. ; Eine Zahl, die manchen Unglück bringt. | Von Ahr bis Württemberg — das größte der 13 Gebiete ist Rheinhessen.
S H | Wie viel bar Druck herrscht ungefähr in einer geschlossenen Champagnerflasche? | 6 | bar | 20 | 1 | 30 | Deutlich mehr als in einem Autoreifen. ; Weniger als zehn. ; Etwa zweieinhalbmal so viel wie in einem Autoreifen. | Rund 6 bar lassen einen Korken mit bis zu 40 km/h herausschießen.
O E | Sortiere diese Biergefäße nach ihrem üblichen Fassungsvermögen — das kleinste zuerst. | Kölschstange = 0,2 l ; Stubbi-Flasche = 0,33 l ; Weißbierglas = 0,5 l ; Maßkrug = 1 l | Das schmalste Glas stammt aus Köln. ; Die kleine braune Flasche folgt. ; Der Krug vom Oktoberfest ist am größten. | Die Stubbi-Flasche wurde in den 1960er-Jahren als handliche Einwegflasche populär.
O M | Sortiere diese Kaffeegetränke nach ihrem Milchanteil — den geringsten zuerst. | Espresso = keine Milch ; Espresso macchiato = ein Tupfer Milchschaum ; Cappuccino = etwa zwei Drittel Milch und Schaum ; Latte macchiato = überwiegend Milch | Einer kommt ganz ohne Milch aus. ; „Macchiato“ heißt „befleckt“. ; Das Schichtgetränk im hohen Glas hat am meisten. | Beim Latte macchiato wird die Milch mit Espresso „befleckt“, beim Espresso macchiato umgekehrt.
M H | Welche DREI dieser Biersorten sind obergärig? | Kölsch ; Altbier ; Weißbier | Pils ; Helles ; Export | Eine stammt aus Köln. ; Eine aus Düsseldorf. ; Die dritte wird aus Weizenmalz gebraut. | Obergärige Hefe arbeitet bei 15 bis 20 °C, untergärige wie beim Pils bei kühlen 4 bis 9 °C.
M E | Welche DREI dieser Getränke sind Schaumweine? | Champagner ; Cava ; Crémant | Sherry ; Portwein ; Chianti | Alle drei prickeln. ; Einer stammt aus Spanien. ; Einer kommt aus einer berühmten französischen Region. | Sherry und Portwein sind verstärkte Weine, Chianti ist ein stiller Rotwein aus der Toskana.

@ fastfood_marken
E E | Welches Fast Food ist hier gesucht? | 🔥🐶 | Hot Dog | Currywurst ; Corn Dog ; Bratwurst im Brötchen | Man bekommt es an Imbissständen und im Stadion. ; Eine Wurst liegt in einem länglichen Brötchen. ; Der Name ist englisch. | Der Name ist seit etwa 1900 belegt — angeblich eine Anspielung auf die Dackelform der Würstchen.
E M | Welche Fast-Food-Kette ist hier gesucht? | 🚇🥪🥖 | Subway | McDonald's ; Nordsee ; Pizza Hut | Man stellt sich sein Sandwich selbst zusammen. ; Die Kette wurde 1965 in den USA gegründet. ; Der Name ist auch ein Wort für U-Bahn. | Subway wurde 1965 in Bridgeport (Connecticut) gegründet und hieß anfangs „Pete's Super Submarines“.
C E | Welche zwei Getränke mischt Mezzo Mix? | Cola und Orangenlimonade | Cola und Zitronenlimonade ; Cola und Apfelschorle ; Orangensaft und Mineralwasser | Es gehört zum Coca-Cola-Konzern. ; Es kam 1973 in Deutschland auf den Markt. ; Die eine Zutat ist braun, die andere orange. | Mezzo Mix wurde für den deutschen Markt erfunden — Spezi war schon seit 1956 ein Erfolg.
C M | In welcher Stadt eröffnete 1971 das erste Starbucks-Café? | Seattle | San Francisco ; New York ; Chicago | Sie liegt an der Westküste der USA. ; Dort sitzt auch Amazon. ; Das Café liegt am Pike Place Market. | Starbucks verkaufte anfangs nur Bohnen und Geräte — Kaffee zum Mitnehmen kam erst später.
C H | Wie nennt man das gelbe M im McDonald's-Logo auf Englisch? | Golden Arches | Big M ; Yellow Gate ; Happy Curves | Das M steht für zwei gebogene Formen. ; Sie waren ursprünglich echte Bögen am Restaurantdach. ; Übersetzt heißt es „goldene Bögen“. | Die ersten McDonald's-Restaurants hatten zwei gelbe Bögen am Gebäude — aus ihnen wurde später das M.
C U | Wie heißt das Maskottchen von Pringles? | Mr. P | Mr. Crunch ; Captain Chips ; Pringo | Er trägt einen großen Schnurrbart. ; Sein Gesicht prangt auf jeder Dose. ; Sein Name besteht aus einer Anrede und einem Buchstaben. | Der Schnurrbart-Mann wurde ursprünglich „Julius Pringles“ genannt.
W M | In Indien verkauft McDonald's keine Burger mit Rindfleisch. | wahr | Aus Rücksicht auf die hinduistische Mehrheit gibt es dort etwa den Chicken Maharaja Mac statt Big Mac.
W H | Das Taurin in Energy-Drinks wird aus Stierhoden gewonnen. | falsch | Taurin wird heute synthetisch hergestellt — es wurde 1827 nur zuerst in Ochsengalle entdeckt.
S H | In welchem Jahr führte McDonald's in den USA das Happy Meal ein? | 1979 | Jahr | 3 | 1950 | 2000 | Mehr als 20 Jahre nach der Gründung von McDonald's. ; Vor den 1980er-Jahren. ; Am Ende eines Jahrzehnts. | Das erste Happy Meal kam 1979 in einer Zirkuswagen-Box mit Spielzeug.
S H | In welchem Jahr kam Red Bull in Österreich auf den Markt? | 1987 | Jahr | 3 | 1950 | 2010 | In den 1980er-Jahren. ; Nach Tschernobyl. ; Zwei Jahre vor dem Mauerfall. | Dietrich Mateschitz startete Red Bull am 1. April 1987.
O H | Welcher Marken-Klassiker kam zuerst? Bringe sie in die richtige zeitliche Reihenfolge. | Heinz Tomato Ketchup = 1876 ; Coca-Cola = 1886 ; Big Mac = 1967 ; Chicken McNuggets = 1983 | Die rote Soße ist am ältesten. ; Das Getränk folgt zehn Jahre später. ; Die Hähnchenstücke sind das jüngste Produkt. | Den Big Mac erfand Franchisenehmer Jim Delligatti 1967 in Pittsburgh.
M M | Welche DREI dieser Limonaden stammen aus dem Hause Coca-Cola? | Sprite ; Fanta ; Mezzo Mix | 7Up ; Mirinda ; Schwip Schwap | Eine ist eine Zitronenlimonade. ; Eine wurde im Zweiten Weltkrieg in Deutschland erfunden. ; Eine mischt Cola mit Orange. | 7Up, Mirinda und Schwip Schwap werden in Deutschland von PepsiCo vertrieben.
M M | Welche DREI dieser Produkte gehören zum Sortiment von McDonald's (Stand 2024)? | Big Mac ; McFlurry ; Chicken McNuggets | Whopper ; Zinger ; Crunchwrap | Eines ist ein Eisbecher. ; Eines ist ein doppelstöckiger Burger. ; Die falschen stammen von Burger King, KFC und Taco Bell. | Der Whopper gehört zu Burger King, der Zinger zu KFC und der Crunchwrap zu Taco Bell.

@ kochen_zutaten
E E | Was ist hier gesucht? | 🪞🥚 | Spiegelei | Rührei ; Omelett ; Pochiertes Ei | Man brät es in der Pfanne. ; Das Eigelb bleibt ganz. ; Der Name hat mit einem Badezimmergegenstand zu tun. | Der Name kommt vermutlich vom glänzenden, spiegelnden Eigelb.
E E | Was ist hier gesucht? | 🥚❄️ | Eischnee | Eierlikör ; Eiscreme ; Rührei | Man braucht dafür einen Schneebesen. ; Er ist die Basis von Baiser. ; Man schlägt nur das Eiweiß. | Ist der Eischnee fest genug, kann man die Schüssel umdrehen, ohne dass etwas herausfällt.
C M | Was bedeutet es, Fleisch zu „plattieren“? | Es flach klopfen | Es auf einem Teller anrichten ; Es mit Speck umwickeln ; Es in Scheiben schneiden | Man braucht dafür einen Fleischklopfer. ; Man macht das vor allem mit Schnitzeln. ; Danach ist das Fleisch dünner. | Beim Plattieren wird das Fleisch gleichmäßig dünn, damit es schnell und gleichmäßig gart.
C M | Was ist ein „Bouquet garni“? | Ein Kräutersträußchen zum Mitkochen | Ein Blumengesteck für den Tisch ; Eine indische Gewürzmischung ; Ein Salatdressing mit Senf | Es stammt aus der französischen Küche. ; Man bindet es mit Küchengarn zusammen. ; Vor dem Servieren fischt man es wieder heraus. | Klassisch gehören Thymian, Lorbeer und Petersilie hinein — gebunden, damit nichts in der Soße schwimmt.
C H | Aus welcher Pflanze wird Tapioka gewonnen? | Maniok | Mais ; Reis ; Kartoffel | Es ist eine tropische Knolle. ; Sie heißt auch Cassava. ; Roh ist sie giftig. | Aus der Stärke der Maniokwurzel entstehen auch die Perlen im Bubble Tea.
C U | Welches Kraut gehört NICHT zu den klassischen französischen „Fines herbes“? | Rosmarin | Kerbel ; Estragon ; Schnittlauch | Die Mischung ist zart und frisch. ; Zu ihr gehört auch Petersilie. ; Das gesuchte Kraut hat harte, nadelartige Blätter. | Fines herbes bestehen aus Petersilie, Schnittlauch, Kerbel und Estragon — zarte Kräuter, die man erst zum Schluss zugibt.
W E | Salz im Nudelwasser lässt das Wasser deutlich schneller kochen. | falsch | Salz erhöht den Siedepunkt sogar minimal — es dient allein dem Geschmack.
W M | Scharfes Anbraten verschließt die Poren im Fleisch, sodass es saftiger bleibt. | falsch | Fleisch hat keine Poren, die sich schließen — beim Anbraten entstehen vor allem Röstaromen.
W M | Ein Ei, das im Wasserglas oben schwimmt, ist meist schon älter. | wahr | Mit der Zeit verdunstet Feuchtigkeit durch die Schale, die Luftkammer wächst — und das Ei bekommt Auftrieb.
S E | Wie viele Teelöffel ergeben einen Esslöffel? | 3 | Teelöffel | 20 | 1 | 10 | Mehr als einer. ; Weniger als fünf. ; Eine ungerade Zahl. | Ein Esslöffel fasst rund 15 Milliliter, ein Teelöffel etwa 5.
S H | Wie viele Milliliter fasst ein amerikanischer Messbecher, eine „Cup“? | 237 | ml | 15 | 50 | 1000 | Weniger als ein halber Liter. ; Mehr als 200 Milliliter. ; Etwa ein Viertelliter. | Eine US-Cup entspricht acht Flüssigunzen, also rund 237 Millilitern.
S U log | Wie viele Liter Wasser stecken laut Water Footprint Network im Schnitt in einem Kilogramm Rindfleisch? | 15400 | Liter | 30 | 100 | 1000000 | Mehr als 1.000 Liter. ; Weniger als 50.000 Liter. ; Mehr als 10.000 Liter. | Der Großteil des „virtuellen Wassers“ steckt im Futter — für ein Kilo Weizen sind es nur rund 1.800 Liter.
O E | Sortiere diese Küchen-Mengenangaben nach Größe — die kleinste zuerst. | Prise = was zwischen zwei Finger passt ; Teelöffel = ≈ 5 ml ; Esslöffel = ≈ 15 ml ; Tasse = ≈ 150–250 ml | Die kleinste nimmt man mit den Fingern. ; Der kleine Löffel kommt danach. ; Aus der größten trinkt man Kaffee. | In alten Rezepten sind „Prise“ und „Messerspitze“ bewusst ungenau — sie richten sich nach Gefühl.
O U | Sortiere diese Weizenmehltypen nach ihrem Mineralstoffgehalt — den niedrigsten zuerst. | Type 405 = ≈ 405 mg je 100 g ; Type 550 = ≈ 550 mg je 100 g ; Type 812 = ≈ 812 mg je 100 g ; Type 1050 = ≈ 1050 mg je 100 g | Die Typenzahl verrät die Lösung. ; Das typische Haushaltsmehl kommt zuerst. ; Das dunkelste Mehl hat die höchste Zahl. | Die Typenzahl gibt an, wie viele Milligramm Mineralstoffe beim Verbrennen von 100 Gramm Mehl übrig bleiben.
M M | Welche DREI dieser Zutaten gehören in eine klassische Sauce hollandaise? | Eigelb ; Butter ; Zitronensaft | Sahne ; Mehl ; Tomatenmark | Die Soße ist gelb. ; Sie wird über dem Wasserbad aufgeschlagen. ; Eine säuerliche Zutat rundet sie ab. | Die Hollandaise ist eine Emulsion — wird sie zu heiß, gerinnt das Eigelb.

@ obst_gemuese
E E | Welche Frucht ist hier gesucht? | 🌍🫐 | Erdbeere | Himbeere ; Heidelbeere ; Brombeere | Sie reift in Deutschland im Frühsommer. ; Ihre Samen sitzen außen. ; Sie wächst dicht über dem Boden. | Die Erdbeere ist ein Rosengewächs — genau wie Apfel, Kirsche und Himbeere.
E E | Welches Gemüse ist hier gesucht? | 🌹🥬 | Rosenkohl | Blumenkohl ; Grünkohl ; Wirsing | Er wächst an einem langen Stiel. ; Viele Kinder mögen ihn nicht. ; Die Röschen sehen aus wie Mini-Kohlköpfe. | Rosenkohl wird erst nach dem ersten Frost richtig mild, weil sich dann Stärke in Zucker umwandelt.
E E | Welcher Salat ist hier gesucht? | 🧊⛰️🥗 | Eisbergsalat | Kopfsalat ; Romanasalat ; Feldsalat | Er ist besonders knackig. ; Er besteht zu über 95 Prozent aus Wasser. ; Früher wurde er für den Transport mit Eis gekühlt. | Den Namen bekam der Salat, weil er in Kalifornien für lange Bahnfahrten unter Eis verpackt wurde.
E H | Welche Frucht ist hier gesucht? | 🌵🫐 | Stachelbeere | Johannisbeere ; Brombeere ; Physalis | Sie ist meist grün und leicht durchscheinend. ; Auf Englisch heißt sie „Gooseberry“. ; Der Strauch hat spitze Dornen. | Stachelbeeren sind eng mit Johannisbeeren verwandt — gekreuzt ergeben sie die Jostabeere.
C H | Wie heißt Blumenkohl in Österreich? | Karfiol | Kohlsprossen ; Fisolen ; Kren | Das Wort stammt aus dem Italienischen. ; Er ist weiß und hat Röschen. ; Es beginnt mit K und hat sieben Buchstaben. | Kohlsprossen sind in Österreich Rosenkohl, Fisolen grüne Bohnen und Kren ist Meerrettich.
C M | Welches Obst enthält das Enzym Bromelain, das Götterspeise am Festwerden hindern kann? | Ananas | Banane ; Apfel ; Kiwi | Sie ist eine tropische Frucht. ; Sie hat eine Krone aus Blättern. ; Aus der Dose gibt es sie oft in Ringen. | Bromelain spaltet Eiweiß — auch die Gelatine. Beim Kochen wird das Enzym zerstört, daher klappt es mit Dosenfrüchten.
C H | Welches Land ist der größte Bananenexporteur der Welt? | Ecuador | Indien ; Brasilien ; Costa Rica | Es liegt in Südamerika. ; Zu ihm gehören die Galápagos-Inseln. ; Sein Name bedeutet auf Spanisch Äquator. | Größter Produzent ist Indien — doch dort werden fast alle Bananen im eigenen Land gegessen.
C U | Welches Wintergemüse wird auch „Arme-Leute-Spargel“ genannt? | Schwarzwurzel | Pastinake ; Petersilienwurzel ; Topinambur | Die Stangen haben eine dunkle Schale. ; Beim Schälen tritt ein klebriger Milchsaft aus. ; Geschält ist sie weiß wie Spargel. | Die Schwarzwurzel heißt auch „Winterspargel“ — zum Schälen trägt man am besten Handschuhe.
W E | Tomaten stammen ursprünglich aus Italien. | falsch | Die Tomate stammt aus Mittel- und Südamerika und kam erst im 16. Jahrhundert nach Europa.
W U | Die Kiwi wurde früher „Chinesische Stachelbeere“ genannt. | wahr | Die Frucht stammt aus China — neuseeländische Exporteure tauften sie 1959 nach dem Nationalvogel Kiwi.
S M log | Wie viele Samen sitzen im Schnitt auf einer Erdbeere? | 200 | Samen | 30 | 10 | 2000 | Mehr als 50. ; Weniger als 500. ; Eine runde Zahl im niedrigen Hunderterbereich. | Die kleinen gelben Nüsschen sind die eigentlichen Früchte — das rote Fruchtfleisch ist nur der Blütenboden.
S U log | Wie viele Kilogramm wog der schwerste Kürbis der Welt (Weltrekord, Stand 2023)? | 1247 | kg | 25 | 50 | 10000 | Mehr als eine halbe Tonne. ; Weniger als zwei Tonnen. ; Etwa so viel wie ein Kleinwagen. | Travis Gienger aus Minnesota stellte 2023 mit „Michael Jordan“ den Rekord auf — rund 1.247 Kilogramm.
O M | Sortiere dieses Obst und Gemüse nach dem Beginn der Haupternte in Deutschland — das früheste zuerst. | Spargel = ab April ; Erdbeere = ab Mai ; Zwetschge = ab August ; Grünkohl = ab November | Das weiße Stangengemüse beginnt im Frühling. ; Die rote Frucht folgt kurz danach. ; Das Kohlgemüse erntet man nach dem ersten Frost. | Grünkohl gilt als typisches Wintergemüse — traditionell wird er erst nach dem ersten Frost geerntet.
O H | Sortiere diese Nüsse und Früchte nach ihrem Fettgehalt — den niedrigsten zuerst. | Esskastanie = ≈ 2 g pro 100 g ; Erdnuss = ≈ 48 g pro 100 g ; Walnuss = ≈ 65 g pro 100 g ; Macadamia = ≈ 75 g pro 100 g | Die Winterfrucht vom Weihnachtsmarkt ist fast fettfrei. ; Die Hülsenfrucht liegt im Mittelfeld. ; Die australische Nuss ist Spitzenreiter. | Maronen bestehen vor allem aus Stärke — darum wurden sie früher zu Mehl gemahlen.
M E | Welche DREI dieser Früchte zählen zum Steinobst? | Kirsche ; Pfirsich ; Aprikose | Apfel ; Birne ; Quitte | Sie haben einen einzigen harten Kern. ; Die falschen haben ein Kerngehäuse. ; Die falschen heißen Kernobst. | Steinobst hat einen verholzten Kern, Kernobst ein Gehäuse mit mehreren kleinen Kernen.
M H | Welche DREI dieser Gemüse gehören zu den Kreuzblütlern? | Rucola ; Radieschen ; Meerrettich | Spinat ; Karotte ; Sellerie | Zu dieser Familie gehören auch alle Kohlsorten. ; Viele schmecken scharf oder senfartig. ; Die falschen sind Fuchsschwanz- und Doldenblütler. | Die Schärfe von Rucola, Radieschen und Meerrettich stammt von Senfölen — typisch für Kreuzblütler.
"""
