"""Extra questions, wave 2: Filme & Serien (format: see tools/content/merge_extra.py)."""
KAT = "filme_serien"
REGION = "global"
DATA = r"""
@ blockbuster_hollywood
E E | Welche Filmreihe ist hier gesucht? | 🤠🐍🏺 | Indiana Jones | Die Mumie ; Tomb Raider ; Das Vermächtnis der Tempelritter | Der Held trägt Hut und Peitsche. ; Er ist Archäologe. ; Gespielt wird er von Harrison Ford. | Der erste Teil „Jäger des verlorenen Schatzes“ kam 1981 ins Kino — Regie führte Steven Spielberg.
E E | Welcher Film ist hier gesucht? | 💗👱‍♀️🏠 | Barbie | Pretty Woman ; Natürlich blond ; Mean Girls | Er kam 2023 ins Kino. ; Die Hauptfigur lebt in einem Traumhaus. ; Ryan Gosling spielt Ken. | Der Film löste 2023 zusammen mit „Oppenheimer“ das Kino-Phänomen „Barbenheimer“ aus.
C M | Welcher Film gewann 2024 den Oscar als bester Film? | Oppenheimer | Barbie ; Killers of the Flower Moon ; Poor Things | Er erzählt von einem Physiker. ; Es geht um die Entwicklung der Atombombe. ; Cillian Murphy spielt die Titelrolle. | Christopher Nolan erhielt dafür auch seinen ersten Regie-Oscar.
C H | Wer führte Regie bei „Barbie“ (2023)? | Greta Gerwig | Sofia Coppola ; Kathryn Bigelow ; Olivia Wilde | Sie ist auch Schauspielerin. ; Zuvor drehte sie „Lady Bird“ und „Little Women“. ; Ihr Lebenspartner ist Regisseur Noah Baumbach. | Mit „Barbie“ drehte sie den ersten Film einer Regisseurin allein, der über eine Milliarde Dollar einspielte.
C E | Welcher Regisseur drehte „Inception“, „Interstellar“ und „Oppenheimer“? | Christopher Nolan | Steven Spielberg ; Denis Villeneuve ; Ridley Scott | Er ist Brite. ; Er dreht am liebsten auf echtem Film statt digital. ; Auch die „The Dark Knight“-Trilogie stammt von ihm. | Nolan ist berühmt für verschachtelte Zeitebenen und handgemachte Spezialeffekte.
C U | Welcher Film von Ang Lee erzählt von einem Jungen, der mit einem Tiger in einem Rettungsboot treibt? | Life of Pi – Schiffbruch mit Tiger | Das Dschungelbuch ; Cast Away – Verschollen ; Der Sturm | Er kam 2012 ins Kino. ; Er basiert auf einem Roman von Yann Martel. ; Der Tiger heißt Richard Parker. | Der Tiger wurde größtenteils am Computer erschaffen — die Effekte gewannen einen Oscar.
C U | Welcher männliche Schauspieler erhielt die meisten Oscar-Nominierungen? | Jack Nicholson | Denzel Washington ; Daniel Day-Lewis ; Leonardo DiCaprio | Er wurde zwölfmal nominiert. ; Er spielte den Joker im „Batman“ von 1989. ; In „Shining“ schlägt er eine Tür mit der Axt ein. | Nicholson gewann drei Oscars — mehr Nominierungen hat unter allen Schauspielern nur Meryl Streep.
W M | „Der Super Mario Bros. Film“ war 2023 der weltweit erfolgreichste Kinofilm des Jahres. | falsch | Knapp vorn lag „Barbie“ mit rund 1,4 Milliarden US-Dollar — Mario folgte mit etwa 1,36 Milliarden auf Platz zwei.
W H | Meryl Streep hat mehr Oscar-Nominierungen als jeder andere Schauspieler. | wahr | Streep kommt auf 21 Nominierungen und drei Oscars — ein Rekord unter allen Darstellerinnen und Darstellern.
W H | „Pulp Fiction“ gewann den Oscar als bester Film. | falsch | 1995 gewann „Forrest Gump“ — Quentin Tarantino bekam für „Pulp Fiction“ aber den Oscar für das beste Originaldrehbuch.
S H | Wie viele Oscars gewann „Oppenheimer“ bei der Verleihung 2024? | 7 | Oscars | 20 | 1 | 15 | Mehr als fünf. ; Weniger als zehn. ; Darunter bester Film und beste Regie. | Auch Cillian Murphy und Robert Downey Jr. wurden für ihre Rollen ausgezeichnet.
S U | Wie viele Oscars gewann „Ben Hur“ (1959) — bis heute Rekord, den nur zwei Filme einstellten? | 11 | Oscars | 15 | 1 | 20 | Mehr als acht. ; Weniger als 14. ; Genauso viele wie später „Titanic“. | Das Wagenrennen gilt als eine der aufwendigsten Actionszenen der Filmgeschichte.
O M | Sortiere diese Filme von Christopher Nolan nach ihrem Erscheinen — den ältesten zuerst. | Memento = 2000 ; The Dark Knight = 2008 ; Inception = 2010 ; Oppenheimer = 2023 | Der rückwärts erzählte Thriller kommt zuerst. ; Der Batman-Film folgt. ; Der Film über die Atombombe ist der jüngste. | In „Memento“ erzählt Nolan die Geschichte rückwärts — so wie sein Held ohne Kurzzeitgedächtnis sie erlebt.
O U | Sortiere diese Filme nach ihrem weltweiten Einspielergebnis — den erfolgreichsten zuerst (Stand 2024). | Avatar = ≈ 2,9 Mrd. US-Dollar ; Avengers: Endgame = ≈ 2,8 Mrd. US-Dollar ; Titanic = ≈ 2,3 Mrd. US-Dollar ; Der König der Löwen (2019) = ≈ 1,7 Mrd. US-Dollar | Der Film mit den blauen Wesen führt. ; Der Marvel-Film liegt knapp dahinter. ; Die Neuverfilmung mit den Löwen kommt zuletzt. | Zwei der vier Spitzenreiter stammen von James Cameron: „Avatar“ und „Titanic“.
M H | Welche DREI dieser Schauspieler spielten im Kino den Joker? | Heath Ledger ; Joaquin Phoenix ; Jack Nicholson | Christian Bale ; Robert Pattinson ; Michael Keaton | Einer bekam den Oscar posthum. ; Einer gewann ihn 2020 für einen Solofilm. ; Einer spielte ihn 1989 neben Michael Keaton. | Christian Bale, Robert Pattinson und Michael Keaton spielten dagegen Batman.

@ animationsfilme
E E | Welcher Disney-Film ist hier gesucht? | 🐻🐯🐍👦 | Das Dschungelbuch | Tarzan ; Robin Hood ; König der Löwen | Die Hauptfigur ist ein Menschenjunge. ; Ein gemütlicher Bär singt über Gemütlichkeit. ; Ein Tiger ist der Bösewicht. | Die Vorlage schrieb Rudyard Kipling — der Menschenjunge heißt Mogli.
E E | Welcher Disney-Film ist hier gesucht? | 🐘👂🪶 | Dumbo | Bambi ; Pinocchio ; Susi und Strolch | Die Hauptfigur arbeitet im Zirkus. ; Sie wird wegen ihrer Ohren verspottet. ; Eine Feder soll ihr beim Fliegen helfen. | In Wahrheit braucht der kleine Elefant die „Zauberfeder“ gar nicht — er kann aus eigener Kraft fliegen.
E E | Welcher Pixar-Film ist hier gesucht? | 🦸‍♂️👨‍👩‍👧‍👦🔴 | Die Unglaublichen | Megamind ; Big Hero 6 ; Ich – Einfach unverbesserlich | Es geht um eine ganze Familie. ; Alle haben Superkräfte. ; Sie tragen rote Anzüge. | Die Modedesignerin Edna Mode besteht in dem Film eisern darauf: „Keine Capes!“
C E | Welches Tier ist Sid aus „Ice Age“? | Ein Faultier | Ein Mammut ; Ein Säbelzahntiger ; Ein Eichhörnchen | Er ist tollpatschig. ; Er redet ununterbrochen. ; Seine Artgenossen hängen heute gern kopfüber an Bäumen. | Manni ist das Mammut, Diego der Säbelzahntiger und Scrat das Säbelzahn-Eichhörnchen.
C E | Wie heißt Elsas berühmtes Lied in der deutschen Fassung von „Die Eiskönigin“? | Lass jetzt los | Frei wie der Wind ; Endlich frei ; Zeig dich | Im Original heißt es „Let It Go“. ; Elsa singt es auf dem Berg. ; Dabei baut sie ihren Eispalast. | „Let It Go“ gewann 2014 den Oscar für den besten Filmsong.
C H | Wie heißt der aufblasbare Gesundheitsroboter aus dem Disney-Film von 2014? | Baymax | WALL-E ; EVE ; Bolt | Er ist weiß und knuddelig. ; Er lebt in der Stadt San Fransokyo. ; Der deutsche Filmtitel beginnt mit seinem Namen. | Der Film „Baymax — Riesiges Robowabohu“ gewann 2015 den Oscar als bester Animationsfilm.
C H | Wie heißt der sprechende Hund in Pixars „Oben“? | Dug | Doug ; Bolt ; Rex | Er trägt ein Halsband, das seine Gedanken übersetzt. ; Er ruft ständig „Eichhörnchen!“. ; Sein Name ist sehr kurz. | Dug schließt sich dem alten Carl und dem Pfadfinder Russell auf ihrer Reise an.
W M | Walt Disney sprach Micky Maus anfangs selbst. | wahr | Disney lieh der Maus ab 1928 fast zwei Jahrzehnte lang seine Stimme.
W U | In der Buchvorlage von Felix Salten ist Bambi ein Reh. | wahr | Für den Film von 1942 machte Disney daraus einen amerikanischen Weißwedelhirsch.
W E | Stitch aus „Lilo & Stitch“ ist ein Hund. | falsch | Stitch ist ein außerirdisches Experiment, das sich auf Hawaii nur als Hund ausgibt.
S M | In welchem Jahr kam „Die Eiskönigin — Völlig unverfroren“ ins Kino? | 2013 | Jahr | 2 | 1995 | 2024 | In den 2010er-Jahren. ; Kurz vor Weihnachten. ; Ein Jahr vor „Baymax“. | Der Film wurde damals der erfolgreichste Animationsfilm aller Zeiten.
S U | Für wie viele Milliarden US-Dollar kaufte Disney 2006 das Studio Pixar? | 7.4 | Mrd. US-Dollar | 20 | 1 | 50 | Mehr als fünf Milliarden. ; Weniger als zehn Milliarden. ; Ungefähr siebeneinhalb. | Pixar-Mitgründer Steve Jobs wurde durch den Deal größter Einzelaktionär von Disney.
O H | Sortiere diese DreamWorks-Filme nach ihrem Erscheinen — den ältesten zuerst. | Antz = 1998 ; Madagascar = 2005 ; Kung Fu Panda = 2008 ; Drachenzähmen leicht gemacht = 2010 | Der Ameisenfilm kam zuerst. ; Die Zootiere folgen. ; Der Wikingerjunge mit Drachen ist der jüngste. | „Antz“ war der erste computeranimierte Film von DreamWorks.
M E | Welche ZWEI dieser Filme stammen von Pixar? | Cars ; Oben | Shrek ; Madagascar ; Ice Age ; Ich – Einfach unverbesserlich | Einer handelt von sprechenden Autos. ; Im anderen fliegt ein Haus an Luftballons. ; Die falschen stammen von DreamWorks, Blue Sky und Illumination. | Pixar gehört seit 2006 zu Disney.
M E | Welche DREI dieser Filmfiguren sind Hunde? | Strolch ; Pongo ; Bolt | Simba ; Stitch ; Nala | Einer liebt Spaghetti mit seiner Susi. ; Einer ist Vater von 99 Welpen. ; Einer hält sich für einen Superhelden. | In „101 Dalmatiner“ ist Pongo der Vater — zusammen mit Perdita hat er 15 eigene Welpen und adoptiert 84 weitere.

@ anime
E E | Welche Anime-Serie ist hier gesucht? | 🏴‍☠️👒🍖 | One Piece | Naruto ; Dragon Ball ; Fairy Tail | Der Held ist ein Pirat. ; Er trägt einen Strohhut. ; Er liebt Fleisch über alles. | Die Serie läuft seit 1999 im japanischen Fernsehen und hat weit über 1.000 Folgen.
E M | Welche Anime-Serie ist hier gesucht? | 🍥🦊🥷 | Naruto | Boruto ; Bleach ; Hunter × Hunter | Der Held ist ein junger Ninja. ; In ihm ist ein Fuchsgeist versiegelt. ; Er liebt Ramen. | Das Fischküchlein mit Spirale, das auf Ramen liegt, heißt auf Japanisch „Naruto“.
E H | Welche Anime-Serie ist hier gesucht? | 📓💀🍎 | Death Note | Tokyo Ghoul ; Code Geass ; Bleach | Ein Schüler findet ein Notizbuch. ; Ein Todesgott begleitet ihn. ; Dieser liebt eine bestimmte Frucht. | Der Schüler Light Yagami liefert sich ein Duell mit dem genialen Detektiv L.
C E | Was bedeutet das japanische Wort „kawaii“, das man oft im Zusammenhang mit Anime hört? | Niedlich | Gefährlich ; Cool ; Traurig | Man sagt es über Katzenbabys. ; Es passt gut zu Hello Kitty. ; Es ist ein Kompliment. | Die „Kawaii“-Kultur prägt in Japan Mode, Werbung und sogar Behördenmaskottchen.
C H | Wie heißt der blaue Roboterkater aus dem 22. Jahrhundert, der aus seiner Bauchtasche Wundergeräte zieht? | Doraemon | Astro Boy ; Totoro ; Hello Kitty | Er hat keine Ohren mehr, seit Mäuse sie abgenagt haben. ; Er liebt süße Bohnenkuchen. ; Sein Name beginnt mit D. | In Japan ist die Figur so berühmt, dass sie 2008 zum „Anime-Botschafter“ ernannt wurde.
C M | Wie heißt der Held von „One Punch Man“, der jeden Gegner mit einem einzigen Schlag besiegt? | Saitama | Genos ; Gon ; Goku | Er hat eine Glatze. ; Er langweilt sich, weil er zu stark ist. ; Er ist „Held aus Hobby“. | Das Training, mit dem er angeblich so stark wurde: täglich 100 Liegestütze, 100 Sit-ups, 100 Kniebeugen und zehn Kilometer Laufen.
C U | Wie heißt das gedankenlesende Mädchen in „Spy × Family“? | Anya | Yor ; Nezuko ; Mikasa | Sie wurde aus einem Waisenhaus adoptiert. ; Ihr Vater ist ein Spion. ; Ihr Name hat vier Buchstaben. | In der Familie verbirgt jeder ein Geheimnis — nur Anya kennt sie alle, weil sie Gedanken liest.
W M | Das Wort „Otaku“ bezeichnet in Japan einen besessenen Fan. | wahr | Der Begriff war in Japan lange eher abwertend — im Westen nennen sich viele Anime-Fans stolz selbst so.
W E | Manga werden in Japan traditionell von links nach rechts gelesen. | falsch | Japanische Manga liest man von rechts nach links — auch viele deutsche Ausgaben behalten diese Leserichtung bei.
S H | Wie viele Folgen hat die Anime-Serie „Neon Genesis Evangelion“? | 26 | Folgen | 20 | 5 | 100 | Mehr als 20. ; Weniger als 30. ; Doppelt so viele wie 13. | Das umstrittene Serienfinale wurde später mit dem Kinofilm „The End of Evangelion“ neu erzählt.
S U | In welchem Jahr startete der Manga „Detektiv Conan“ in Japan? | 1994 | Jahr | 3 | 1970 | 2010 | In den 1990er-Jahren. ; Vor der Anime-Serie. ; Mitte des Jahrzehnts. | Gosho Aoyama zeichnet die Reihe bis heute — sie gehört zu den am längsten laufenden Manga überhaupt.
O U | Sortiere diese Filme von Makoto Shinkai nach ihrem Erscheinen — den ältesten zuerst. | 5 Centimeters per Second = 2007 ; Your Name. = 2016 ; Weathering with You = 2019 ; Suzume = 2022 | Der Film über Kirschblüten und Abschied ist der älteste. ; Der Körpertausch-Hit folgt. ; Der Film über eine Reise und Türen ist der jüngste. | Shinkai gilt wegen seiner Lichtstimmungen als einer der wichtigsten Anime-Regisseure seit Miyazaki.
O H | Sortiere diese Anime-Figuren nach ihrem ersten Auftritt im Manga — den frühesten zuerst. | Astro Boy = 1952 ; Doraemon = 1969 ; Son Goku = 1984 ; Monkey D. Ruffy = 1997 | Der Roboterjunge von Osamu Tezuka kommt zuerst. ; Der Roboterkater folgt. ; Der Pirat mit Strohhut ist der jüngste. | Osamu Tezuka gilt als „Gott des Manga“ — seine Figuren prägten den typischen großäugigen Stil.
M E | Welche DREI dieser Figuren gehören zur Strohhutbande? | Ruffy ; Zorro ; Nami | Naruto ; Vegeta ; Light Yagami | Einer ist der Kapitän. ; Einer kämpft mit drei Schwertern. ; Eine ist die Navigatorin. | Naruto ist ein Ninja, Vegeta ein Saiyajin aus „Dragon Ball“ und Light der Held aus „Death Note“.
M E | Welche ZWEI dieser Anime drehen sich um Sport? | Haikyu!! ; Captain Tsubasa | Death Note ; Naruto ; Sailor Moon ; Detektiv Conan | Einer handelt von Volleyball. ; Der andere von Fußball. ; Beide spielen an Schulen. | „Captain Tsubasa“ inspirierte angeblich sogar Fußballprofis wie Alessandro Del Piero.

@ streaming_serien
E E | Welche Serie ist hier gesucht? | 🦑🎮🔺 | Squid Game | Alice in Borderland ; Kingdom ; All of Us Are Dead | Sie stammt aus Südkorea. ; Verschuldete Menschen spielen um ihr Leben. ; Die Wachen tragen Masken mit Symbolen. | Die Wachen tragen je nach Rang Kreis, Dreieck oder Quadrat auf ihren Masken.
E M | Welche Serie ist hier gesucht? | 🧢🔪🥃 | Peaky Blinders | Boardwalk Empire ; Gangs of London ; The Crown | Sie spielt in Birmingham. ; Die Gangster tragen flache Mützen. ; Im Mützenschirm sollen Rasierklingen stecken. | Die Serie erzählt vom Aufstieg der Shelby-Familie nach dem Ersten Weltkrieg.
E M | Welche Serie ist hier gesucht? | ⬛🪞📱 | Black Mirror | Westworld ; The Twilight Zone ; Severance | Jede Folge erzählt eine eigene Geschichte. ; Es geht um die dunklen Seiten der Technik. ; Der Titel meint einen ausgeschalteten Bildschirm. | Viele Folgen wirken inzwischen erschreckend prophetisch — etwa zu Bewertungs-Apps und Deepfakes.
C M | Welche Schauspielerin spielt die Titelrolle in der Netflix-Serie „Wednesday“? | Jenna Ortega | Millie Bobby Brown ; Christina Ricci ; Zendaya | Sie ist US-Amerikanerin. ; Ihr Tanz aus der Serie ging 2022 viral. ; Sie spielte auch in „Scream“ (2022). | Christina Ricci, die Wednesday 1991 im Kino spielte, ist in der Serie als Lehrerin zu sehen.
C M | Wie heißt das grüne Wesen, das in „The Mandalorian“ als „Baby Yoda“ berühmt wurde? | Grogu | Yaddle ; Babu Frik ; Wicket | Es gehört zu Yodas Spezies. ; Es kann die Macht nutzen. ; Sein Name hat fünf Buchstaben. | Den echten Namen erfuhren Fans erst in der zweiten Staffel — bis dahin hieß es nur „das Kind“.
C H | Welche Apple-TV+-Serie handelt von einem US-Footballtrainer, der einen englischen Fußballklub übernimmt? | Ted Lasso | Shrinking ; Welcome to Wrexham ; Sunderland 'Til I Die | Die Hauptfigur ist unerschütterlich optimistisch. ; Der Klub heißt AFC Richmond. ; Die Serie ist nach ihrem Trainer benannt. | Die Figur entstand ursprünglich für Werbespots zur Premier League im US-Fernsehen.
C U | Welche HBO-Serie erzählt vom Machtkampf der Medienmogul-Familie Roy? | Succession | Billions ; Dallas ; Yellowstone | Der Patriarch heißt Logan Roy. ; Die Kinder kämpfen um sein Erbe. ; Der Titel bedeutet „Nachfolge“. | Für ihre vierte und letzte Staffel gewann die Serie den Emmy als beste Dramaserie.
W M | Tim Burton führte bei mehreren Folgen der Netflix-Serie „Wednesday“ Regie. | wahr | Burton inszenierte die ersten vier Folgen der ersten Staffel und war als Produzent beteiligt.
W U | „Haus des Geldes“ lief zuerst im spanischen Fernsehsender Antena 3. | wahr | Erst nachdem Netflix die Serie 2017 übernommen hatte, wurde sie zum weltweiten Hit.
W E | „Friends“ lief ursprünglich auf Netflix. | falsch | „Friends“ lief von 1994 bis 2004 beim US-Sender NBC — Netflix zeigte die Serie erst Jahre später.
S M | Wie viele Folgen hat die erste Staffel von „Squid Game“? | 9 | Folgen | 20 | 3 | 30 | Weniger als zehn. ; Mehr als fünf. ; Eine Folge mehr als acht. | Die erste Staffel wurde 2021 zur meistgesehenen Netflix-Serie ihrer Zeit.
S E | Wie viele Staffeln hat die Serie „The Crown“? | 6 | Staffeln | 20 | 1 | 15 | Mehr als vier. ; Weniger als acht. ; Eine gerade Zahl. | Alle zwei Staffeln wechselte die komplette Besetzung, damit die Figuren glaubhaft altern.
O H | Welche Netflix-Serie startete zuerst? Bringe diese Hits in die zeitliche Reihenfolge. | Narcos = 2015 ; Stranger Things = 2016 ; Squid Game = 2021 ; Wednesday = 2022 | Die Serie über Pablo Escobar kommt zuerst. ; Die Kinder aus Hawkins folgen. ; Die Addams-Tochter ist die jüngste. | „Narcos“ erzählt vom Aufstieg des kolumbianischen Drogenbarons Pablo Escobar.
O E | Sortiere diese Serien nach der Zahl ihrer Staffeln — die wenigsten zuerst. | Chernobyl = 1 Staffel ; Breaking Bad = 5 Staffeln ; Game of Thrones = 8 Staffeln ; The Big Bang Theory = 12 Staffeln | Die Miniserie über ein Reaktorunglück ist am kürzesten. ; Die Drogen-Serie folgt. ; Die Nerd-Sitcom lief am längsten. | „The Big Bang Theory“ ist mit 279 Folgen die am längsten laufende Multi-Kamera-Sitcom der US-Fernsehgeschichte.
M M | Welche ZWEI dieser Serien sind Netflix-Eigenproduktionen? | Stranger Things ; Wednesday | Game of Thrones ; The Mandalorian ; Ted Lasso ; The Boys | Eine spielt in den 1980ern. ; Die andere an der Nevermore Academy. ; Die falschen laufen bei HBO, Disney+, Apple TV+ und Prime Video. | Game of Thrones stammt von HBO, The Mandalorian von Disney+, Ted Lasso von Apple und The Boys von Amazon.

@ scifi_fantasy
E E | Welche Filmreihe ist hier gesucht? | ⭐⚔️🌌 | Star Wars | Star Trek ; Guardians of the Galaxy ; Dune | Es gibt Lichtschwerter. ; Sie spielt „vor langer Zeit in einer weit, weit entfernten Galaxis“. ; George Lucas erfand sie. | Der erste Film startete 1977 in den USA — in Deutschland hieß er „Krieg der Sterne“.
E M | Welche Serie ist hier gesucht? | 👨‍⚕️❓📞 | Doctor Who | Star Trek ; Sherlock ; Torchwood | Die Hauptfigur reist durch Raum und Zeit. ; Das Raumschiff sieht aus wie eine Notrufzelle. ; Die Serie stammt von der BBC. | Die Serie startete 1963 — der Doktor kann sich regenerieren, so wechselt immer wieder die Besetzung.
C E | Wie heißt Luke Skywalkers Zwillingsschwester? | Leia | Padmé ; Rey ; Mon Mothma | Sie ist Prinzessin. ; Sie trägt berühmte Haarschnecken. ; Carrie Fisher spielte sie. | Dass Luke und Leia Geschwister sind, erfahren die Zuschauer erst in „Die Rückkehr der Jedi-Ritter“.
C E | Wie heißt der Hauself, der Harry Potter immer wieder zu Hilfe kommt? | Dobby | Kreacher ; Winky ; Griphook | Er trägt anfangs einen alten Kissenbezug. ; Eine Socke macht ihn frei. ; Sein Name hat fünf Buchstaben. | Dobby dient zunächst den Malfoys, bis Harry ihn mit einer List befreit.
C M | Wer spielt Paul Atreides in den „Dune“-Filmen von Denis Villeneuve? | Timothée Chalamet | Tom Holland ; Austin Butler ; Robert Pattinson | Er spielte auch Willy Wonka. ; Er ist Franzose und US-Amerikaner zugleich. ; Sein Vorname hat einen Akzent auf dem e. | Austin Butler spielt im zweiten Teil den Gegenspieler Feyd-Rautha Harkonnen.
C H | Wer spielte Gollum in „Der Herr der Ringe“ per Motion Capture? | Andy Serkis | Elijah Wood ; Ian Holm ; Billy Boyd | Er spielte auch Caesar in „Planet der Affen“. ; Er ist Brite. ; Auch King Kong verkörperte er per Motion Capture. | Serkis gilt als Pionier der Motion-Capture-Schauspielerei.
C U | Welcher Infinity-Stein steckt in der Stirn des Androiden Vision? | Der Gedankenstein | Der Seelenstein ; Der Zeitstein ; Der Raumstein | Er ist gelb. ; Er steckte zuvor in Lokis Zepter. ; Er beeinflusst den Verstand. | Um alle sechs Steine zu bekommen, reißt Thanos ihn in „Infinity War“ aus Visions Stirn.
W M | Darth Vader wird im Original von James Earl Jones gesprochen. | wahr | Im Kostüm steckte der Bodybuilder David Prowse — die tiefe Stimme lieferte James Earl Jones.
W E | Die „Herr der Ringe“-Filme wurden überwiegend in Irland gedreht. | falsch | Gedreht wurde in Neuseeland, der Heimat von Regisseur Peter Jackson — das Hobbit-Dorf Hobbingen kann man dort bis heute besuchen.
W E | Die Na'vi im Film „Avatar“ haben grüne Haut. | falsch | Die Na'vi sind blau — ihre Haut ist mit leuchtenden Punkten gemustert.
S E | Wie viele Infinity-Steine gibt es im Marvel-Filmuniversum? | 6 | Steine | 20 | 1 | 20 | Mehr als vier. ; Weniger als zehn. ; Genau so viele, wie ein Würfel Seiten hat. | Raum, Gedanken, Realität, Macht, Zeit und Seele — Thanos sammelt sie alle in seinem Handschuh.
S U | Wie viele Minuten dauert die Kinofassung von „Der Herr der Ringe: Die Rückkehr des Königs“? | 201 | Minuten | 15 | 60 | 400 | Mehr als drei Stunden. ; Weniger als vier Stunden. ; Etwas mehr als 200 Minuten. | Die erweiterte Fassung dauert sogar mehr als vier Stunden.
O H | Sortiere diese Star-Wars-Figuren nach ihrem ersten Kinoauftritt — den frühesten zuerst. | Darth Vader = 1977 ; Yoda = 1980 ; Jar Jar Binks = 1999 ; Rey = 2015 | Der dunkle Lord ist von Anfang an dabei. ; Der kleine Jedi-Meister folgt im zweiten Film. ; Die Schrottsammlerin von Jakku ist die jüngste. | Yoda war im ersten Auftritt eine Puppe, gesteuert und gesprochen von Frank Oz.
M E | Welche DREI dieser Figuren stammen aus dem DC-Universum? | Batman ; Wonder Woman ; Aquaman | Iron Man ; Thor ; Spider-Man | Einer lebt in Gotham City. ; Eine ist eine Amazone. ; Einer herrscht unter Wasser. | Iron Man, Thor und Spider-Man gehören zum Konkurrenten Marvel.
M M | Welche ZWEI dieser Bücher schrieb J. R. R. Tolkien? | Der Hobbit ; Das Silmarillion | Der König von Narnia ; Die unendliche Geschichte ; Eragon ; Das Lied von Eis und Feuer | Eines erzählt von Bilbos Reise. ; Das andere von der Frühgeschichte Mittelerdes. ; Die falschen stammen von Lewis, Ende, Paolini und Martin. | „Das Silmarillion“ gab Tolkiens Sohn Christopher erst 1977 nach dem Tod seines Vaters heraus.

@ deutsche_filme_serien de
E M | Welcher deutsche Film ist hier gesucht? | 🐰🚫👂 | Keinohrhasen | Zweiohrküken ; Kokowääh ; Honig im Kopf | Die Komödie kam 2007 ins Kino. ; Til Schweiger spielt einen Boulevardreporter. ; Ein Stofftier ohne Ohren spielt eine Rolle. | Die Fortsetzung heißt passend „Zweiohrküken“ (2009).
E E | Welcher deutsche Film ist hier gesucht? | 🍯🧠 | Honig im Kopf | Keinohrhasen ; Das Leben der Anderen ; Toni Erdmann | Dieter Hallervorden spielt einen Großvater. ; Seine Enkelin reist mit ihm nach Venedig. ; Der Titel beschreibt Vergesslichkeit. | Über sieben Millionen Menschen sahen die Tragikomödie 2014/15 im Kino.
C H | Wie heißt die Netflix-Serie über einen Schüler, der aus seinem Kinderzimmer heraus Drogen im Internet verkauft? | How to Sell Drugs Online (Fast) | Dark ; Biohackers ; Wir sind die Welle | Sie startete 2019. ; Der Held heißt Moritz Zimmermann. ; Der Titel ist englisch und klingt wie eine Anleitung. | Die Serie beruht lose auf einem echten Fall aus Leipzig, der 2015 aufflog.
C U | Wer führte Regie bei der Tragikomödie „Toni Erdmann“ (2016)? | Maren Ade | Caroline Link ; Doris Dörrie ; Nora Fingscheidt | Sie ist eine Frau. ; Der Film lief im Wettbewerb von Cannes. ; Ihr Nachname hat drei Buchstaben. | „Toni Erdmann“ wurde für den Oscar als bester fremdsprachiger Film nominiert.
C H | Wer spielte in der Kinoverfilmung „Heidi“ von 2015 den Alm-Öhi? | Bruno Ganz | Mario Adorf ; Armin Mueller-Stahl ; Klaus Maria Brandauer | Er war Schweizer. ; Er spielte auch Hitler in „Der Untergang“. ; Er war ein Engel in „Der Himmel über Berlin“. | Der Film über das Schweizer Waisenmädchen war einer der erfolgreichsten deutschsprachigen Filme seines Jahrgangs.
C E | An welchem Wochentag taucht das Sams bei Herrn Taschenbier auf? | An einem Samstag | An einem Montag ; An einem Freitag ; An einem Sonntag | Paul Maar erfand die Figur. ; Der Wochentag gab dem Sams den Namen. ; Es ist der Tag vor Sonntag. | Das Sams hat Wunschpunkte im Gesicht — jeder erfüllt einen Wunsch.
C H | Welcher Schauspieler spielte 1956 den „Hauptmann von Köpenick“? | Heinz Rühmann | Hans Albers ; Gert Fröbe ; Curd Jürgens | Er war einer der beliebtesten deutschen Filmstars. ; Er spielte auch in „Die Feuerzangenbowle“. ; Sein Vorname ist Heinz. | Die Geschichte beruht auf dem Schuster Wilhelm Voigt, der sich 1906 als Offizier verkleidete.
W M | „Lola rennt“ spielt in München. | falsch | Lola rennt durch Berlin — Regisseur Tom Tykwer drehte an vielen bekannten Orten der Hauptstadt.
W H | „Das Boot“ wurde für sechs Oscars nominiert. | wahr | Wolfgang Petersens U-Boot-Drama erhielt 1983 sechs Nominierungen, darunter Regie — gewonnen hat es keinen.
S H | Wie viele Millionen Kinobesucher hatte „Der Schuh des Manitu“ in Deutschland? | 11.7 | Mio. | 15 | 1 | 50 | Mehr als zehn Millionen. ; Weniger als 15 Millionen. ; Es ist der erfolgreichste deutsche Film seit der Wiedervereinigung. | Bully Herbigs Western-Parodie von 2001 lockte fast zwölf Millionen Menschen ins Kino.
S M | Wie viele Folgen hat die Netflix-Serie „Dark“ insgesamt? | 26 | Folgen | 20 | 5 | 100 | Mehr als 20. ; Weniger als 30. ; Drei Staffeln. | Die erste Staffel hatte zehn Folgen, die zweite und dritte jeweils acht.
S H | Wie viele Millionen Menschen sahen „Fack ju Göhte“ (2013) in deutschen Kinos? | 7.4 | Mio. | 20 | 1 | 30 | Mehr als fünf Millionen. ; Weniger als zehn Millionen. ; Mehr als sieben Millionen. | Die Schulkomödie mit Elyas M'Barek wurde danach zu einer Trilogie ausgebaut.
O M | Sortiere diese deutschen Filme nach ihrem Erscheinen — den ältesten zuerst. | Metropolis = 1927 ; Das Boot = 1981 ; Lola rennt = 1998 ; Das Leben der Anderen = 2006 | Der Stummfilm kommt zuerst. ; Das U-Boot-Drama folgt. ; Das Stasi-Drama ist der jüngste. | Fritz Langs „Metropolis“ wurde 2001 als erster Film in das UNESCO-Weltdokumentenerbe aufgenommen.
O H | Sortiere diese Filme von Michael „Bully“ Herbig nach ihrem Erscheinen — den ältesten zuerst. | Der Schuh des Manitu = 2001 ; (T)Raumschiff Surprise – Periode 1 = 2004 ; Lissi und der wilde Kaiser = 2007 ; Ballon = 2018 | Die Western-Parodie kommt zuerst. ; Die Weltraum-Parodie folgt. ; Das ernste Drama über eine DDR-Flucht ist der jüngste. | „Ballon“ erzählt die wahre Geschichte zweier Familien, die 1979 mit einem selbst gebauten Heißluftballon aus der DDR flohen.
M H | Welche ZWEI dieser Hollywood-Filme drehte der deutsche Regisseur Wolfgang Petersen? | Troja ; Air Force One | Independence Day ; Gladiator ; Titanic ; Der Soldat James Ryan | In einem kämpft Brad Pitt als Achilles. ; Im anderen verteidigt Harrison Ford als US-Präsident sein Flugzeug. ; „Independence Day“ stammt von einem anderen Deutschen: Roland Emmerich. | Petersen ging nach dem Welterfolg von „Das Boot“ nach Hollywood und drehte dort Blockbuster mit Clint Eastwood, Harrison Ford und Brad Pitt.

@ filmzitate_emoji
E M | Welcher Film ist hier gesucht? | 🕺🐺 | Der mit dem Wolf tanzt | Wolfsblut ; Der Wolf von Wall Street ; Die Wolfsfrau | Es ist ein Western. ; Ein Soldat freundet sich mit den Lakota an. ; Kevin Costner führte Regie und spielte die Hauptrolle. | Das Epos von 1990 gewann sieben Oscars, darunter bester Film und beste Regie.
E H | Welcher James-Bond-Film ist hier gesucht? | 🥇👆 | Goldfinger | Goldeneye ; Der Mann mit dem goldenen Colt ; Octopussy | Er stammt aus den 1960ern. ; Sean Connery spielt Bond. ; Eine Frau wird mit Goldfarbe überzogen. | In „Goldfinger“ fährt Bond erstmals seinen berühmten Aston Martin DB5.
E M | Welcher Film ist hier gesucht? | 🌊1️⃣1️⃣🎰 | Ocean's Eleven | Casino ; Die Unfassbaren ; Rain Man | Es geht um einen Raubzug. ; Ziel sind Casinos in Las Vegas. ; Eine Zahl steckt im Titel. | Die Neuverfilmung von 2001 mit George Clooney bekam zwei Fortsetzungen mit den Zahlen 12 und 13.
E M | Welcher Hitchcock-Film ist hier gesucht? | 🐦🐦🐦😱 | Die Vögel | Psycho ; Vertigo ; Das Fenster zum Hof | Der Film kam 1963 heraus. ; Eine Kleinstadt wird angegriffen. ; Die Angreifer kommen aus der Luft. | Für die Angriffe setzte Hitchcock echte und mechanische Vögel ein — Hauptdarstellerin Tippi Hedren wurde dabei verletzt.
E E | Welcher Film ist hier gesucht? | ✈️😎🏐 | Top Gun | Pearl Harbor ; Air Force One ; Der Stählerne Adler | Tom Cruise spielt einen Kampfpiloten. ; Sonnenbrillen und Lederjacken wurden danach Kult. ; Eine Szene zeigt ein Beachvolleyballspiel. | 2022 kam mit „Top Gun: Maverick“ eine späte Fortsetzung ins Kino.
C E | In welchem Film ruft Bruce Willis in der deutschen Fassung „Yippie-Ya-Yeah, Schweinebacke!“? | Stirb langsam | Armageddon ; Das fünfte Element ; Pulp Fiction | Er spielt einen New Yorker Polizisten. ; Die Handlung spielt an Heiligabend. ; Terroristen besetzen ein Hochhaus. | Im Original heißt der Satz „Yippee-ki-yay“ — die deutsche Synchronfassung machte daraus einen Kultspruch.
C M | Aus welchem Film stammt der Satz „Offen gesagt, meine Liebe, ist mir das gleichgültig.“? | Vom Winde verweht | Casablanca ; Der Zauberer von Oz ; Citizen Kane | Der Film kam 1939 heraus. ; Er spielt im Amerikanischen Bürgerkrieg. ; Rhett Butler sagt ihn zu Scarlett O'Hara. | Im Original lautet der Satz „Frankly, my dear, I don't give a damn“ — damals ein kleiner Skandal.
C U | Aus welchem Film stammt der Schlusssatz „Nobody is perfect“ („Niemand ist vollkommen“)? | Manche mögen's heiß | Frühstück bei Tiffany ; Das Appartement ; Der Clou | Marilyn Monroe spielt mit. ; Zwei Musiker verkleiden sich als Frauen. ; Regie führte Billy Wilder. | Der Satz fällt, als sich Jack Lemmons Figur als Mann zu erkennen gibt — und sein Verehrer gelassen bleibt.
W M | Der Satz „Beam me up, Scotty“ fällt in der Originalserie „Raumschiff Enterprise“ genau so. | falsch | Genau diese Worte sagt Captain Kirk nie — ähnliche Formulierungen gibt es, der Kultsatz entstand erst durch Fans.
W H | Der Satz „Elementar, mein lieber Watson“ steht so in keinem Roman von Arthur Conan Doyle. | wahr | In den Büchern sagt Holmes zwar „Elementar“ und „mein lieber Watson“ — die berühmte Kombination machten erst Filme populär.
S M | Wie viele Jahre lagen zwischen „Top Gun“ und der Fortsetzung „Top Gun: Maverick“? | 36 | Jahre | 10 | 5 | 60 | Mehr als 30 Jahre. ; Weniger als 40 Jahre. ; Die Fortsetzung kam 2022. | Tom Cruise bestand darauf, dass viele Flugszenen in echten Kampfjets gedreht wurden.
S M | Wie viele Filme umfasst die Hauptreihe von „Fast & Furious“ bis einschließlich „Fast X“ (2023)? | 10 | Filme | 20 | 3 | 30 | Mehr als acht. ; Weniger als zwölf. ; Der Titel des letzten Films verrät es. | Die Reihe begann 2001 mit illegalen Straßenrennen in Los Angeles — später wurden daraus globale Agentenabenteuer.
O M | Sortiere diese Filmzitate nach dem Erscheinungsjahr ihres Films — das älteste zuerst. | „Nach Hause telefonieren.“ = 1982 ; „Hasta la vista, Baby.“ = 1991 ; „Ich sehe tote Menschen.“ = 1999 ; „Warum so ernst?“ = 2008 | Der Außerirdische kommt zuerst. ; Der Cyborg aus der Zukunft folgt. ; Der Joker spricht zuletzt. | Die Sätze stammen aus „E.T.“, „Terminator 2“, „The Sixth Sense“ und „The Dark Knight“.
M E | Welche ZWEI dieser Sätze stammen aus „Der Herr der Ringe“? | „Du kannst nicht vorbei!“ ; „Ein Ring, sie zu knechten.“ | „Möge die Macht mit dir sein.“ ; „Ich bin Groot.“ ; „Winter is coming.“ ; „Nach Hause telefonieren.“ | Einen ruft Gandalf auf einer Brücke. ; Der andere steht auf dem Einen Ring. ; Die falschen stammen aus Star Wars, Marvel, Game of Thrones und E.T. | Gandalf stellt sich in Moria dem Balrog mit „Du kannst nicht vorbei!“ entgegen.
M M | Welche DREI dieser Filme stammen von Quentin Tarantino? | Pulp Fiction ; Kill Bill ; Django Unchained | Fight Club ; Sieben ; Memento | Einer spielt in einem Diner und einer Gangsterwelt. ; Einer ist ein Rachefilm in zwei Teilen. ; Einer ist ein Western über einen befreiten Sklaven. | „Fight Club“ und „Sieben“ drehte David Fincher, „Memento“ Christopher Nolan.
"""
