"""Extra questions, wave 2: Gaming without LoL (format: see tools/content/merge_extra.py)."""
KAT = "gaming"
REGION = "global"
DATA = r"""
@ pokemon
E E | Welches Pokémon ist hier gesucht? | 🐭⚡💛 | Pikachu | Raichu ; Pichu ; Evoli | Es ist das bekannteste Pokémon überhaupt. ; Es sitzt meist auf Ashs Schulter. ; Seine Nummer im Pokédex ist 25. | Pikachu ist seit dem Anime das Maskottchen der gesamten Pokémon-Marke.
E M | Welches Pokémon ist hier gesucht? | 🦎🔥🧡 | Glumanda | Glurak ; Vulpix ; Fukano | Es ist ein Feuer-Starter aus Kanto. ; Seine Schwanzspitze brennt. ; Es entwickelt sich zu Glutexo. | Erlischt die Flamme an Glumandas Schwanz, stirbt es der Legende nach — darum meidet es Regen.
E M | Welches Pokémon ist hier gesucht? | 🐢💧🕶️ | Schiggy | Turtok ; Enton ; Quapsel | Es ist ein Wasser-Starter aus Kanto. ; Im Anime hat es eine Bande mit Sonnenbrillen. ; Es entwickelt sich zu Schillok. | Die „Schiggy-Bande“ trägt im Anime coole Sonnenbrillen.
E M | Welches Pokémon ist hier gesucht? | 😴🛌🍔🚧 | Relaxo | Snorlax-Junior ; Pummeluff ; Walraisa | Es blockiert in Pokémon Rot und Blau einen Weg. ; Nur eine Flöte weckt es auf. ; Es frisst täglich 400 Kilogramm Nahrung. | Relaxo schläft fast immer und wacht nur zum Essen auf.
E H | Welches Pokémon ist hier gesucht? | 🐟💦😵‍💫 | Karpador | Goldini ; Remoraid ; Barschwa | Es gilt als das nutzloseste Pokémon. ; Seine Attacke „Platscher“ bewirkt nichts. ; Es entwickelt sich zu einem mächtigen Drachen. | Aus dem hilflosen Karpador wird ab Level 20 das furchterregende Garados.
E H | Welches Pokémon ist hier gesucht? | 🎤🩷😴🖊️ | Pummeluff | Piepi ; Knuddeluff ; Mauzi | Es ist rund und rosa. ; Sein Lied schläfert alle ein. ; Im Anime bemalt es wütend die Gesichter der Schlafenden. | Pummeluff singt im Anime ständig — und ärgert sich, weil alle einschlafen.
C E | Welche Farbe hat die obere Hälfte eines klassischen Pokéballs? | Rot | Blau ; Grün ; Gelb | Die untere Hälfte ist weiß. ; In der Mitte sitzt ein Knopf. ; Die Farbe der ersten Edition „Pokémon …“. | Pokébälle gibt es in vielen Varianten — der rot-weiße ist das Original.
C M | Wie heißt die Ausgangsregion der allerersten Pokémon-Spiele? | Kanto | Johto ; Hoenn ; Sinnoh | Sie ist einer echten Region in Japan nachempfunden. ; Dort liegt Alabastia. ; Tokio liegt in der echten gleichnamigen Region. | Kanto ist der japanischen Region um Tokio nachempfunden.
C M | In welches Pokémon entwickelt sich Karpador? | Garados | Dragoran ; Lapras ; Seeper | Es ist riesig und schlangenartig. ; Es ist ein Wasser-Flug-Pokémon. ; Es gilt als extrem aggressiv. | Die Entwicklung erinnert an die chinesische Legende vom Karpfen, der zum Drachen wird.
C M | Welches Pokémon wurde im ersten Pokémon-Film von Wissenschaftlern aus dem Erbgut von Mew geklont? | Mewtu | Deoxys ; Celebi ; Lugia | Es ist ein legendäres Psycho-Pokémon. ; Im Namen steckt eine Zahl. ; Es ist die Nummer 150. | „Pokémon — Der Film: Mewtu gegen Mew“ kam 1999 in Deutschland ins Kino.
C H | Welches Land stand Pate für die Region Kalos aus Pokémon X und Y? | Frankreich | Italien ; Spanien ; Großbritannien | In der Hauptstadt steht ein großer Turm. ; Die Spiele erschienen 2013. ; Der Name klingt nach „schön“ auf Griechisch. | Die Kalos-Hauptstadt Illumina City ist Paris nachempfunden — samt Prismaturm.
C H | Welcher Pokémon-Typ kam 2013 mit Pokémon X und Y neu hinzu? | Fee | Stahl ; Unlicht ; Drache | Er ist besonders stark gegen Drachen. ; Piepi gehört seitdem zu ihm. ; Sein Symbol ist rosa. | Mit dem Fee-Typ stieg die Zahl der Pokémon-Typen auf 18.
C U | Wie heißt der Erfinder von Pokémon, der als Kind leidenschaftlich Insekten sammelte? | Satoshi Tajiri | Shigeru Miyamoto ; Hideo Kojima ; Satoru Iwata | Er gründete das Studio Game Freak. ; Der Vorname ist auch der japanische Name von Ash. ; Der Nachname beginnt mit T. | Aus Tajiris Sammelleidenschaft wurde das Prinzip „Schnapp sie dir alle!“.
W E | Pikachu entwickelt sich mit einem Donnerstein zu Raichu. | wahr | Ein Donnerstein verwandelt Pikachu in Raichu — Ashs Pikachu lehnte das im Anime allerdings ab.
W M | Bisasam trägt in Pokédex Nummer 1. | wahr | Bisasam steht auf Platz 1 des nationalen Pokédex, gefolgt von Bisaknosp und Bisaflor.
W H | Garados ist ein Pokémon vom Typ Wasser und Drache. | falsch | Trotz seines Drachen-Looks ist Garados Wasser/Flug — erst Mega-Garados wird zu Wasser/Unlicht.
S M | Wie viele Pokémon-Typen gibt es seit Pokémon X und Y (2013)? | 18 | Typen | 10 | 5 | 40 | Mehr als 15. ; Zuletzt kam der Fee-Typ hinzu. ; Weniger als 20. | Die 18 Typen reichen von Normal über Feuer und Wasser bis Fee.
S H | Wie viele Entwicklungen hat Evoli (Stand 2024)? | 8 | Entwicklungen | 15 | 1 | 20 | Mehr als fünf. ; Eine für fast jedes Element. ; Weniger als zehn. | Aquana, Blitza, Flamara, Psiana, Nachtara, Folipurba, Glaziola und Feelinara.
O M | Sortiere diese Pokémon-Regionen nach ihrem ersten Auftritt — die älteste zuerst. | Kanto = Rot/Blau (1996) ; Johto = Gold/Silber (1999) ; Hoenn = Rubin/Saphir (2002) ; Sinnoh = Diamant/Perl (2006) | Die erste liegt um Tokio. ; Die zweite grenzt direkt an sie. ; Diamant und Perl sind die jüngsten. | Jede neue Pokémon-Generation brachte eine neue Region mit.
M M | Welche DREI dieser Pokémon sind die legendären Vögel aus der ersten Generation? | Arktos ; Zapdos ; Lavados | Tauboss ; Ibitak ; Dragoran | Einer ist aus Eis. ; Einer ist elektrisch. ; Einer brennt. | Arktos (Eis), Zapdos (Elektro) und Lavados (Feuer) sind in Rot und Blau fangbar.
M H | Welche ZWEI dieser Regionen sind echten Ländern außerhalb Japans nachempfunden? | Galar ; Alola | Kanto ; Johto ; Hoenn ; Sinnoh | Eine ist eine Inselgruppe im Pazifik. ; Die andere hat Fußballstadien und Nebel. ; Die ersten vier Regionen basieren auf Japan. | Alola ist Hawaii nachempfunden, Galar Großbritannien.

@ minecraft
E E | Welcher Minecraft-Gegner ist hier gesucht? | 🟩💣💥😐 | Creeper | Zombie ; Skelett ; Enderman | Er schleicht sich lautlos an. ; Er zischt kurz, bevor es knallt. ; Er ist grün. | Der Creeper entstand aus einem Programmierfehler beim Modell des Schweins.
E M | Welches Spiel ist hier gesucht? | ⛏️🧱🐷🧟 | Minecraft | Terraria ; Roblox ; Fortnite | Alles besteht aus Würfeln. ; Nachts kommen Monster. ; Es stammt aus Schweden. | Minecraft ist das meistverkaufte Videospiel aller Zeiten.
C E | Womit handeln Dorfbewohner in Minecraft? | Smaragden | Diamanten ; Goldbarren ; Kohle | Die Währung ist grün. ; Man findet sie selten in Bergbiomen. ; Es ist ein Edelstein. | Mit Smaragden kann man bei Dorfbewohnern Werkzeuge, Bücher und Nahrung kaufen.
C E | Wie heißen die beiden Standard-Spielfiguren in Minecraft? | Steve und Alex | Tom und Jerry ; Max und Moritz ; Notch und Herobrine | Einer hat ein türkisfarbenes Shirt. ; Die andere hat orangefarbene Haare. ; Einer der Namen ist sehr häufig in den USA. | Seit 2022 gibt es neben Steve und Alex noch weitere Standard-Skins.
C M | Aus welchem Material muss ein Portal in den Nether gebaut werden? | Obsidian | Bruchstein ; Netherrack ; Eisenblöcke | Es ist schwarz-violett. ; Es entsteht, wenn Wasser auf Lava trifft. ; Man braucht mindestens eine Diamantspitzhacke. | Der Rahmen wird mit Feuerzeug entzündet und leuchtet dann lila.
C M | Welches Tier schützt in Minecraft die Dörfer vor Monstern? | Eisengolem | Schneegolem ; Wolf ; Lama | Er ist groß und grau. ; Er schenkt Dorfkindern manchmal Mohnblumen. ; Er besteht aus Metall. | Man kann einen Eisengolem aus vier Eisenblöcken und einem Kürbis selbst bauen.
C H | Welches Update brachte 2020 das Material Netherit in Minecraft? | Das Nether-Update | Das Caves-&-Cliffs-Update ; Das Aquatic-Update ; Das Wild-Update | Das Material findet man in einer anderen Dimension. ; Es ist stärker als Diamant. ; Die Version war 1.16. | Netherit-Ausrüstung verbrennt nicht in Lava.
C H | Wer spielte in „Ein Minecraft Film“ (2025) die Rolle des Steve? | Jack Black | Jason Momoa ; Chris Pratt ; Ryan Reynolds | Er ist auch Musiker der Band Tenacious D. ; Er sprach Bowser im Mario-Film. ; Er spielte in „School of Rock“. | Jack Black spielte Steve, Jason Momoa den Ex-Gamer Garrett.
C U | Wie heißt die Enderperlen-Kombination, mit der man in Minecraft Endportale findet? | Enderauge | Endstein-Kompass ; Wither-Rose ; Lohenstaub | Es fliegt in Richtung der Festung. ; Man mischt eine Enderperle mit Lohenstaub. ; Es sieht aus wie ein grünes Auge. | Zwölf Enderaugen braucht man, um ein Endportal komplett zu aktivieren.
W E | In Minecraft wird es nachts dunkel und es tauchen Monster auf. | wahr | Im Überlebensmodus spawnen nachts Zombies, Skelette, Spinnen und Creeper.
W M | Endermen werden wütend, wenn man ihnen direkt in die Augen schaut. | wahr | Wer einen Enderman anblickt, provoziert ihn — ein Kürbis auf dem Kopf schützt davor.
W M | Man kann Diamanten in Minecraft mit einer Steinspitzhacke abbauen. | falsch | Für Diamanterz braucht man mindestens eine Eisenspitzhacke.
W H | Minecraft wurde ursprünglich in der Programmiersprache Java geschrieben. | wahr | Die Java Edition ist das Original — die Bedrock Edition ist in C++ geschrieben.
S M | Wie viele Minuten Echtzeit dauert ein vollständiger Tag-Nacht-Zyklus in Minecraft? | 20 | Minuten | 15 | 5 | 60 | Weniger als eine halbe Stunde. ; Etwa zwei Drittel davon ist es hell. ; Mehr als eine Viertelstunde. | Ein Minecraft-Tag dauert 20 Minuten: etwa 10 Minuten Tag, Dämmerung und 7 Minuten Nacht.
S M | Wie viele Blöcke der meisten Sorten passen in Minecraft auf einen Inventarplatz? | 64 | Blöcke | 10 | 10 | 200 | Eine Zweierpotenz. ; Mehr als 50. ; Eier und Schilder stapeln sich nur bis 16. | 64 ist die Standard-Stapelgröße — Werkzeuge stapeln sich gar nicht.
S U | Für wie viele Milliarden US-Dollar kaufte Microsoft 2014 das Minecraft-Studio Mojang? | 2.5 | Mrd. US-Dollar | 20 | 0.5 | 10 | Mehr als eine Milliarde. ; Weniger als drei. ; Zweieinhalb. | Microsoft zahlte 2014 rund 2,5 Milliarden Dollar für Mojang.
O M | Sortiere diese Minecraft-Werkzeugmaterialien nach ihrer Haltbarkeit — das schwächste zuerst. | Gold = 32 Nutzungen ; Stein = 131 Nutzungen ; Eisen = 250 Nutzungen ; Diamant = 1561 Nutzungen | Das glänzendste Material ist das schwächste. ; Stein schlägt Gold deutlich. ; Der Edelstein hält am längsten. | Goldwerkzeuge sind zwar schnell, gehen aber nach 32 Nutzungen kaputt.
M E | Welche ZWEI dieser Minecraft-Wesen greifen den Spieler an? | Zombie ; Skelett | Kuh ; Schaf ; Dorfbewohner ; Schwein | Beide erscheinen nachts. ; Einer schießt mit Pfeilen. ; Nutztiere sind harmlos. | Zombies und Skelette verbrennen im Sonnenlicht — es sei denn, sie tragen einen Helm.
M M | Welche DREI Dimensionen gibt es in Minecraft? | Oberwelt ; Nether ; Ende | Unterwasserwelt ; Himmelreich ; Traumwelt | Eine ist die normale Welt. ; Eine ist voller Lava. ; In der dritten wartet ein Drache. | Der Enderdrache im Ende gilt als Endgegner von Minecraft.

@ fortnite_battle_royale ab12
E E ab0 | Welches Spiel ist hier gesucht? | 🚌🪂🏝️🔨 | Fortnite | PUBG ; Apex Legends ; Roblox | Man springt aus einem fliegenden Bus. ; Man kann in Sekunden Wände bauen. ; Es stammt von Epic Games. | Fortnite Battle Royale erschien im September 2017 und wurde zum Welthit.
E M ab0 | Welches Spiel ist hier gesucht? | 🫘👑🏃‍♂️🤸 | Fall Guys | Among Us ; Stumble Guys ; Gang Beasts | Die Figuren sehen aus wie Bohnen. ; Es ist ein Hindernis-Parcours. ; Nur einer holt die Krone. | Fall Guys erschien 2020 und ist seit 2022 kostenlos spielbar.
C E | Wie heißt die Spielwährung in Fortnite? | V-Bucks | Robux ; Coins ; Credits | Man kauft damit Skins und Tänze. ; Der erste Buchstabe ist ein V. ; „Bucks“ ist Umgangssprache für Dollar. | V-Bucks gibt es nur für kosmetische Gegenstände.
C E | Wie viele Spieler starten normalerweise in eine Fortnite-Battle-Royale-Runde? | 100 | 50 ; 64 ; 200 | Eine runde Zahl. ; Dreistellig. ; Ein Hundert… | Aus 100 Spielern bleibt am Ende nur einer (oder ein Team) übrig.
C M | Was verkleinert in Fortnite im Laufe einer Runde die Spielfläche? | Der Sturm | Die Flut ; Ein Vulkan ; Der Nebel | Er ist lila. ; Wer drin steht, verliert Leben. ; Er zieht sich in Kreisen zusammen. | Der Sturm treibt alle Spieler in eine immer kleinere Zone.
C M | Welcher Rapper gab im April 2020 ein virtuelles Konzert in Fortnite? | Travis Scott | Drake ; Eminem ; Kanye West | Er ist aus Houston. ; Sein Album heißt „Astroworld“. ; Seine Figur wurde riesig. | Über zwölf Millionen Spieler sahen das Konzert „Astronomical“ gleichzeitig.
C H | Welcher Spieler gewann 2019 die erste Fortnite-Weltmeisterschaft im Einzel? | Bugha | Ninja ; Tfue ; Mongraal | Er war erst 16 Jahre alt. ; Er stammt aus den USA. ; Er gewann 3 Millionen Dollar. | Kyle „Bugha“ Giersdorf gewann das Solo-Turnier in New York.
C H | Was verschlang im Oktober 2019 beim Event „The End“ die komplette Fortnite-Karte? | Ein Schwarzes Loch | Ein Tsunami ; Ein Meteor ; Ein Drache | Tagelang sahen Spieler nur einen dunklen Bildschirm. ; Danach begann Kapitel 2. ; Es kommt aus der Astronomie. | Fast zwei Tage lang war Fortnite nicht spielbar — nur das Schwarze Loch war zu sehen.
C U | Wie hieß der ursprüngliche Spielmodus von Fortnite, in dem man gemeinsam gegen Zombies kämpft? | Rette die Welt | Kreativmodus ; Nullbauen ; Party Royale | Er kam 2017 vor dem Battle-Royale-Modus. ; Er war kostenpflichtig. ; Man verteidigt Basen. | Der Battle-Royale-Modus war zunächst nur ein Ableger von „Rette die Welt“.
W E | Fortnite wird von Epic Games entwickelt. | wahr | Epic Games aus North Carolina entwickelt auch die Unreal Engine.
W M | In Fortnite kann man Wände, Treppen und Rampen bauen. | wahr | Das schnelle Bauen unterscheidet Fortnite von PUBG — seit 2023 gibt es auch „Null Bauen“.
W M | PUBG erschien nach Fortnite Battle Royale. | falsch | PUBG erschien im März 2017 im Early Access, Fortnite Battle Royale erst im September 2017.
S H | Wie viele Millionen US-Dollar Preisgeld gewann Bugha beim Fortnite World Cup 2019? | 3 | Mio. US-Dollar | 20 | 0.5 | 10 | Mehr als eine Million. ; Weniger als fünf. ; Eine ungerade Zahl. | Das Gesamtpreisgeld des World Cups lag bei rund 30 Millionen Dollar.
O H | Sortiere diese Spiele von Epic Games nach ihrem Erscheinen — das älteste zuerst. | Jazz Jackrabbit = 1994 ; Unreal = 1998 ; Gears of War = 2006 ; Fortnite = 2017 | Ein grüner Hase macht den Anfang. ; Der Ego-Shooter gab einer berühmten Engine ihren Namen. ; Das Bau-und-Baller-Spiel ist das jüngste. | Epic Games hieß anfangs Epic MegaGames — die Unreal Engine aus dem Shooter von 1998 treibt heute auch Fortnite an.
M M | Welche ZWEI dieser Spiele sind Battle-Royale-Spiele? | Apex Legends ; PUBG | Die Sims ; Stardew Valley ; Tetris ; Mario Kart | In beiden bleibt am Ende nur einer übrig. ; Eines stammt von Respawn. ; Beim anderen gibt es ein „Chicken Dinner“. | Beim Battle Royale überlebt der Letzte auf einer schrumpfenden Karte.

@ nintendo_universum
E E | Welches Spiel ist hier gesucht? | 🏎️🍌🐢🏁 | Mario Kart | Super Mario Bros. ; Crash Team Racing ; Need for Speed | Man rutscht auf Schalen aus. ; Panzer fliegen durch die Gegend. ; Die Fahrer sind Nintendo-Figuren. | Das erste Mario Kart erschien 1992 für das Super Nintendo.
E E | Welches Spiel ist hier gesucht? | 👨‍🔧🍄🐢👸 | Super Mario Bros. | Donkey Kong ; Luigi's Mansion ; Wario Land | Der Held ist Klempner. ; Pilze lassen ihn wachsen. ; Er rettet eine Prinzessin. | Super Mario Bros. von 1985 gehört zu den meistverkauften Spielen aller Zeiten.
E M | Welche Spielereihe ist hier gesucht? | 🧝🗡️👸🔺 | The Legend of Zelda | Final Fantasy ; Fire Emblem ; Kingdom Hearts | Der Held trägt eine grüne Mütze. ; Die Prinzessin gibt der Reihe den Namen. ; Das Dreieck heißt Triforce. | Viele halten den Helden Link fälschlich für Zelda.
E M | Welches Spiel ist hier gesucht? | 🏝️🦝🍑🏠 | Animal Crossing | Stardew Valley ; Harvest Moon ; Die Sims | Ein Waschbär verkauft Häuser. ; Man lebt auf einer Insel. ; Tiere sind die Nachbarn. | „Animal Crossing: New Horizons“ wurde 2020 zum Lockdown-Hit.
E M | Welches Spiel ist hier gesucht? | 🦍🛢️👨👸 | Donkey Kong | King Kong ; Diddy Kong Racing ; Rampage | Ein Affe wirft Fässer. ; Es erschien 1981 in Spielhallen. ; Mario hatte hier seinen ersten Auftritt. | Mario hieß in Donkey Kong noch „Jumpman“ und war Zimmermann.
E H | Welche Nintendo-Figur ist hier gesucht? | 💗⭐🌬️😋 | Kirby | Jigglypuff ; Yoshi ; Toad | Sie ist eine rosa Kugel. ; Sie saugt Gegner ein und übernimmt deren Kräfte. ; Ihr Heimatland heißt Dreamland. | Kirby wurde von Masahiro Sakurai erfunden, der auch Smash Bros. erschuf.
E H | Welches Spiel ist hier gesucht? | 🦑🎨🔫🟧 | Splatoon | Octodad ; Paint the Town Red ; Squid Game | Man färbt den Boden in Teamfarbe. ; Die Figuren sind Tintenfische. ; Es erschien 2015 für die Wii U. | Bei Splatoon zählt nicht, wer die meisten Treffer landet, sondern wer mehr Fläche einfärbt.
E M | Welches Spiel ist hier gesucht? | 🎳🎾⛳🥊 | Wii Sports | Mario Party ; Kinect Sports ; Just Dance | Man schwingt einen Controller wie einen Schläger. ; Es lag der Konsole bei. ; Selbst Großeltern spielten Bowling damit. | Wii Sports verkaufte sich über 80 Millionen Mal — meist als Beigabe zur Konsole.
E U | Welches Spiel ist hier gesucht? | 🎲⭐🍄🎉 | Mario Party | Mario Kart ; Super Mario Galaxy ; Paper Mario | Es ist ein Brettspiel auf der Konsole. ; Zwischen den Runden gibt es Minispiele. ; Wer die meisten Sterne hat, gewinnt. | Die Minispiel-Reihe gibt es seit 1998.
C E | Wie heißt Marios Bruder, der ein grünes Outfit trägt? | Luigi | Wario ; Toad ; Waluigi | Er ist größer als Mario. ; Er hat ein eigenes Geisterspiel. ; Sein Name klingt italienisch. | Luigi bekam 2001 mit „Luigi's Mansion“ sein erstes großes eigenes Spiel.
C E | Wie heißt der grüne Dinosaurier, auf dem Mario reiten kann? | Yoshi | Rex ; Dino ; Birdo | Er hat eine lange Zunge. ; Er legt Eier. ; Er erschien erstmals in „Super Mario World“. | Yoshi debütierte 1990 in „Super Mario World“ für das Super Nintendo.
C M | Welcher Game Designer erfand Mario, Donkey Kong und Zelda? | Shigeru Miyamoto | Hideo Kojima ; Satoru Iwata ; Yuji Naka | Er ist Japaner. ; Er ließ sich von Streifzügen durch Wälder und Höhlen zu Zelda inspirieren. ; Sein Vorname beginnt mit S. | Miyamoto gilt als einer der einflussreichsten Spieleentwickler überhaupt.
C M | Wie heißt das Königreich, in dem Prinzessin Peach herrscht? | Pilz-Königreich | Hyrule ; Traumland ; Blumenreich | Seine Bewohner heißen Toads. ; Sie sehen aus wie Pilze. ; Hyrule gehört zu Zelda. | Im Pilz-Königreich leben die Toads mit ihren gepunkteten Pilzköpfen.
C H | In welchem Spiel von 1986 stellte sich am Ende heraus, dass die Heldin Samus eine Frau ist? | Metroid | Kid Icarus ; Castlevania ; Mega Man | Die Heldin trägt einen Kampfanzug. ; Ein Planet heißt Zebes. ; Der Name mischt „Metro“ und „Android“. | Samus Aran gilt als eine der ersten Heldinnen der Videospielgeschichte.
C H | Welcher Mario-Film von Illumination spielte 2023 über eine Milliarde US-Dollar ein? | Der Super Mario Bros. Film | Super Mario Galaxy ; Mario und das Pilz-Königreich ; Super Mario: Das Abenteuer | Chris Pratt spricht im Original Mario. ; Jack Black singt „Peaches“. ; Er erschien im April 2023. | Der Film wurde einer der erfolgreichsten Animationsfilme aller Zeiten.
C U | In welchem Spiel hatte Wario 1992 seinen ersten Auftritt? | Super Mario Land 2 | Super Mario World ; Wario Ware ; Mario Kart 64 | Es erschien für den Game Boy. ; Wario hatte Marios Schloss besetzt. ; Es trägt eine Zahl im Titel. | Wario ist Marios gieriger Gegenspieler — das W ist ein umgedrehtes M.
W E | Mario war ursprünglich Klempner und ist es bis heute. | falsch | In „Donkey Kong“ (1981) war Mario noch Zimmermann — Klempner wurde er erst 1983 in „Mario Bros.“.
W M | Die Nintendo Switch kann man sowohl am Fernseher als auch unterwegs spielen. | wahr | Die Switch (2017) ist eine Hybridkonsole: Aus dem Dock genommen, wird sie zum Handheld.
W M | Link ist der Name der Prinzessin in „The Legend of Zelda“. | falsch | Link ist der Held — Zelda ist die Prinzessin.
W H | Der Game Boy kam 1989 mit Tetris im Paket auf den Markt. | wahr | Tetris als Beigabe machte den Game Boy weltweit zum Verkaufsschlager.
S M | In welchem Jahr erschien die Nintendo Switch? | 2017 | Jahr | 2 | 2005 | 2025 | Nach der Wii U. ; In der zweiten Hälfte der 2010er. ; Im März jenes Jahres. | Die Switch kam am 3. März 2017 auf den Markt.
S H | In welchem Jahr erschien der erste Game Boy? | 1989 | Jahr | 2 | 1975 | 2005 | Ende der 1980er. ; Im Jahr des Mauerfalls. ; Kurz vor 1990. | Der Game Boy verkaufte sich zusammen mit dem Game Boy Color über 118 Millionen Mal.
O M | Sortiere diese Nintendo-Konsolen nach ihrem Erscheinen — die älteste zuerst. | NES = 1983 ; Nintendo 64 = 1996 ; GameCube = 2001 ; Wii U = 2012 | Die erste hieß in Japan Famicom. ; Die Zahl im Namen verrät die 64-Bit-Konsole. ; Der Wii-Nachfolger ist der jüngste. | Die Wii U war ein Flop — ihre Spiele kamen später für die Switch neu heraus.
O H | Sortiere diese Zelda-Spiele nach ihrem Erscheinen — das älteste zuerst. | Ocarina of Time = 1998 ; The Wind Waker = 2002 ; Breath of the Wild = 2017 ; Tears of the Kingdom = 2023 | Das erste der vier ist für das Nintendo 64. ; Das Cartoon-Segelabenteuer folgte. ; Tears of the Kingdom ist der Nachfolger von Breath of the Wild. | Breath of the Wild erschien zum Start der Switch 2017.
M M | Welche DREI dieser Figuren stammen aus dem Mario-Universum? | Bowser ; Toad ; Yoshi | Link ; Samus ; Pikachu | Einer ist ein Drache mit Stachelpanzer. ; Einer hat einen Pilzkopf. ; Einer ist ein grüner Dino. | Link stammt aus Zelda, Samus aus Metroid, Pikachu aus Pokémon.

@ retro_arcade
E E | Welcher Spieleklassiker ist hier gesucht? | 🟡👻🍒 | Pac-Man | Space Invaders ; Frogger ; Galaga | Der Held ist ein gelber Kreis. ; Er frisst Punkte im Labyrinth. ; Vier Geister jagen ihn. | Pac-Man erschien 1980 und ist eines der bekanntesten Arcade-Spiele überhaupt.
E E | Welches Spiel ist hier gesucht? | 🟦🟨🟥⬇️🔄 | Tetris | Candy Crush ; Bejeweled ; Puzzle Bobble | Die Steine fallen von oben. ; Volle Reihen verschwinden. ; Es stammt aus der Sowjetunion. | Alexei Paschitnow programmierte Tetris 1984 in Moskau.
E E | Welche Spielfigur ist hier gesucht? | 🦔💨💍💙 | Sonic | Crash Bandicoot ; Knuckles ; Spyro | Er ist sehr schnell. ; Er sammelt Ringe. ; Er ist das Maskottchen von Sega. | Sonic the Hedgehog erschien 1991 als Segas Antwort auf Mario.
E M | Welcher Spieleklassiker ist hier gesucht? | 👾🛸🚀💥 | Space Invaders | Asteroids ; Galaga ; Defender | Aliens rücken Reihe für Reihe vor. ; Man schießt von unten nach oben. ; Es erschien 1978 von Taito. | Space Invaders löste Ende der 1970er einen weltweiten Arcade-Boom aus.
E M | Welcher Spieleklassiker ist hier gesucht? | 🐸🚗🚚🪵 | Frogger | Crossy Road ; Toad Rush ; Pond Hopper | Die Figur muss über eine Straße. ; Danach hüpft sie über Baumstämme im Fluss. ; Es erschien 1981 von Konami. | Frogger inspirierte später das Handyspiel Crossy Road.
E H | Welcher Spieleklassiker ist hier gesucht? | 🏓📺⬜ | Pong | Tennis for Two ; Breakout ; Arkanoid | Es war der erste große Arcade-Erfolg. ; Zwei Balken spielen sich einen Punkt zu. ; Es stammt von Atari. | Pong erschien 1972 und machte Atari groß.
E H | Welche Spielereihe ist hier gesucht? | 🥋👊🔥🌍 | Street Fighter | Mortal Kombat ; Tekken ; Tekken Tag | Ein berühmter Angriff heißt „Hadouken“. ; Die Kämpfer kommen aus aller Welt. ; Teil II erschien 1991. | Street Fighter II machte Prügelspiele in Spielhallen weltweit populär.
C E | Wie heißen die Gegner, die Pac-Man durchs Labyrinth jagen? | Geister | Zombies ; Roboter ; Aliens | Sie sind bunt. ; Frisst Pac-Man eine Kraftpille, werden sie blau. ; Einer heißt Blinky. | Blinky, Pinky, Inky und Clyde haben jeweils ein eigenes Jagdverhalten.
C M | Welche Tastenfolge ist als „Konami-Code“ berühmt? | Hoch, hoch, runter, runter, links, rechts, links, rechts, B, A | A, B, A, B, hoch, runter, links, rechts ; Links, rechts, links, rechts, A, B, Start ; Start, Select, A, B, hoch, hoch | Er gab in „Contra“ 30 Leben. ; Er beginnt zweimal mit derselben Richtung. ; Er endet mit zwei Buchstaben. | Der Code ist heute ein Easter Egg auf vielen Webseiten.
C M | Welches Spiel war 1997 auf dem Nokia-Handy 6110 vorinstalliert und wurde Kult? | Snake | Tetris ; Space Impact ; Bounce | Man steuert eine wachsende Linie. ; Man darf sich nicht selbst beißen. ; Das Tier im Namen hat keine Beine. | Snake wurde auf Hunderten Millionen Nokia-Handys gespielt.
C M | Welcher Heimcomputer von 1982 gilt als meistverkauftes Computermodell aller Zeiten? | Commodore 64 | Amiga 500 ; ZX Spectrum ; Atari 800 | Er hieß im Volksmund „Brotkasten“. ; Die Zahl steht für den Arbeitsspeicher in Kilobyte. ; Die Firma begann mit Schreibmaschinen. | Vom C64 wurden je nach Quelle 12 bis 17 Millionen Stück verkauft.
C H | Welches Atari-Spiel von 1982 wurde so ein Flop, dass Kassetten in der Wüste von New Mexico vergraben wurden? | E.T. | Pac-Man ; Pitfall! ; Missile Command | Es basiert auf einem Spielberg-Film. ; Die Kassetten wurden 2014 ausgegraben. ; Die Hauptfigur will nach Hause telefonieren. | Die Ausgrabung in Alamogordo bestätigte 2014 die jahrzehntealte Legende.
C H | In welchem Atari-Spiel von 1979 versteckte Entwickler Warren Robinett das erste berühmte Easter Egg? | Adventure | Pong ; Asteroids ; Breakout | In einem geheimen Raum stand sein Name. ; Atari nannte Entwickler damals nirgends. ; Der Titel bedeutet „Abenteuer“. | Weil Atari keine Namen nannte, versteckte Robinett seinen eigenen im Spiel.
C U | Wie heißt der Erfinder von Pac-Man? | Toru Iwatani | Shigeru Miyamoto ; Tomohiro Nishikado ; Hideo Kojima | Er arbeitete bei Namco. ; Angeblich inspirierte ihn eine Pizza mit fehlendem Stück. ; Sein Nachname beginnt mit I. | Iwatani wollte ein Spiel entwickeln, das auch Frauen in die Spielhallen lockt.
W E | Sonic ist das Maskottchen von Nintendo. | falsch | Sonic ist das Maskottchen von Sega — Mario gehört zu Nintendo.
W M | Tetris wurde in der Sowjetunion erfunden. | wahr | Alexei Paschitnow entwickelte Tetris 1984 an der Akademie der Wissenschaften in Moskau.
W M | In „Duck Hunt“ für das NES lacht ein Hund den Spieler aus, wenn er daneben schießt. | wahr | Der kichernde Hund gehört zu den meistgehassten Figuren der Spielegeschichte.
W H | Die Sega Dreamcast war die letzte Heimkonsole, die Sega herstellte. | wahr | Nach der Dreamcast (1998) zog sich Sega 2001 aus dem Konsolengeschäft zurück.
S M | In welchem Jahr erschien Pac-Man in Japan? | 1980 | Jahr | 2 | 1965 | 2000 | Am Anfang eines Jahrzehnts. ; Zwei Jahre nach Space Invaders. ; Eine runde Zahl. | Pac-Man hieß in Japan zuerst „Puck Man“.
S H | Wie viele Geister jagen Pac-Man im Original-Spiel? | 4 | Geister | 25 | 1 | 10 | Mehr als zwei. ; Weniger als fünf. ; Blinky, Pinky … | Blinky, Pinky, Inky und Clyde — rot, rosa, türkis und orange.
O M | Sortiere diese Arcade-Klassiker nach ihrem Erscheinen — den ältesten zuerst. | Pong = 1972 ; Space Invaders = 1978 ; Pac-Man = 1980 ; Street Fighter II = 1991 | Der erste simuliert Tischtennis. ; Die Aliens kamen vor dem gelben Kreis. ; Das Prügelspiel ist das jüngste. | Space Invaders und Pac-Man läuteten das goldene Zeitalter der Spielhallen ein.
O H | Sortiere diese Konsolen nach ihrem Erscheinen — die älteste zuerst. | Atari 2600 = 1977 ; Sega Mega Drive = 1988 ; Sega Dreamcast = 1998 ; Xbox 360 = 2005 | Die älteste hatte einen Joystick mit einem Knopf. ; Das Sonic-Zuhause folgt. ; Segas letzte Konsole kommt vor der Microsoft-Konsole. | Das Mega Drive hieß in Nordamerika „Genesis“.
M M | Welche DREI dieser Namen gehören zu den Geistern aus Pac-Man? | Blinky ; Pinky ; Clyde | Casper ; Slimer ; Boo | Alle haben einen Namen auf -y oder -e. ; Einer ist rot, einer rosa. ; Die falschen stammen aus Filmen und Mario. | Der vierte Geist heißt Inky.

@ esport_gaming_kultur
E E | Welches Spiel ist hier gesucht? | 🚀👨‍🚀🔪🗳️ | Among Us | Fall Guys ; Lethal Company ; Space Station 13 | Einer im Team ist ein Verräter. ; Man stimmt ab, wen man rauswirft. ; Die Figuren sehen aus wie Bohnen mit Visier. | Among Us erschien 2018 und wurde 2020 durch Streamer weltberühmt.
E E | Welches Handyspiel ist hier gesucht? | 🍉🥷🍍⚔️ | Fruit Ninja | Cut the Rope ; Candy Crush ; Temple Run | Man wischt über den Bildschirm. ; Das Obst fliegt hoch. ; Bomben darf man nicht treffen. | Fruit Ninja erschien 2010 und war einer der ersten großen Touch-Hits.
E E | Welches Spiel ist hier gesucht? | 💃🕺🎵📺 | Just Dance | SingStar ; Guitar Hero ; Dance Dance Revolution | Man tanzt Figuren auf dem Bildschirm nach. ; Es stammt von Ubisoft. ; Jedes Jahr erscheint eine neue Ausgabe. | Just Dance gibt es seit 2009 — es wertet die Bewegung des Controllers oder Handys aus.
E M | Welches Handyspiel ist hier gesucht? | 🚇🏃🛹👮 | Subway Surfers | Temple Run ; Crossy Road ; Jetpack Joyride | Man rennt über Gleise. ; Ein Wachmann und sein Hund jagen einen. ; Es ist ein Endlos-Läufer aus Dänemark. | Subway Surfers war das erste Spiel, das im Google Play Store eine Milliarde Downloads erreichte.
E M | Welches Handyspiel ist hier gesucht? | 🏃🏛️🐒💰 | Temple Run | Subway Surfers ; Tomb Raider Go ; Jungle Run | Man hat ein Idol aus einem Tempel gestohlen. ; Affenartige Wesen jagen einen. ; Man wischt, um abzubiegen. | Temple Run erschien 2011 und machte Endlos-Läufer populär.
E M | Welches Spiel ist hier gesucht? | 🌻🌱🧟🏠 | Pflanzen gegen Zombies | Zombie Farm ; Garden Warfare Kids ; Die Sims | Man verteidigt den Rasen. ; Erbsen werden verschossen. ; Die Gegner wollen Gehirne. | „Plants vs. Zombies“ von PopCap erschien 2009.
E H | Welches Spiel ist hier gesucht? | 🌀🔵🟠🎂 | Portal | Half-Life ; Prey ; The Talos Principle | Man schießt zwei Löcher, die verbunden sind. ; Eine KI namens GLaDOS führt Tests durch. ; „Der Kuchen ist eine Lüge.“ | Portal von Valve erschien 2007 in der „Orange Box“.
E H | Welches Spiel ist hier gesucht? | 🌾🐔🏡⛏️ | Stardew Valley | Farmville ; Harvest Moon ; Minecraft | Man erbt einen Bauernhof. ; Ein einziger Entwickler hat es programmiert. ; Es erschien 2016. | Eric Barone entwickelte Stardew Valley über vier Jahre komplett allein.
E U | Welche Spielereihe ist hier gesucht? | 🎸🟢🔴🟡🔵 | Guitar Hero | Rock Band ; SingStar ; Rocksmith | Man spielt auf einem Plastikinstrument. ; Die Farben entsprechen Tasten am Griffbrett. ; Der erste Teil erschien 2005. | Guitar Hero machte Plastikgitarren Mitte der 2000er zum Partyhit.
C E | Wofür steht die Abkürzung „GG“ am Ende einer Gaming-Runde? | Good Game | Get Going ; Great Goal ; Game Gone | Man sagt es aus Fairness. ; Es ist Englisch. ; Es ist ein Lob fürs Spiel. | „GG“ gilt als Zeichen von Sportsgeist — egal, wer gewonnen hat.
C E | Was bedeutet die Abkürzung „AFK“ im Gaming? | Nicht an der Tastatur | Alle Feinde getötet ; Angriff fertig ; Auf freiem Kurs | Die englische Langform ist „away from keyboard“. ; Der Spieler ist kurz weg. ; Seine Figur steht still. | AFK-Spieler ärgern ihre Teams — manche Spiele werfen sie automatisch raus.
C M | Welcher Streaming-Dienst für Gamer wurde 2014 von Amazon gekauft? | Twitch | YouTube Gaming ; Mixer ; Kick | Sein Logo ist lila. ; Er ging 2011 an den Start. ; Er ging aus Justin.tv hervor. | Amazon zahlte rund 970 Millionen US-Dollar für Twitch.
C M | Was versteht man unter einem „Speedrun“? | Ein Spiel so schnell wie möglich durchspielen | Ein Rennen in einem Rennspiel ; Ein Turnier mit Zeitlimit ; Eine Pause-Taste drücken | Die Zeit läuft vom Start bis zum Abspann. ; Oft werden Fehler im Spiel genutzt. ; Es gibt dafür Weltranglisten. | Beim Charity-Event „Games Done Quick“ sammeln Speedrunner Millionen für gute Zwecke.
C M | Welche KI führt die Tests im Spiel „Portal“ durch? | GLaDOS | HAL 9000 ; Cortana ; SHODAN | Sie spricht mit ruhiger, kalter Stimme. ; Sie verspricht einen Kuchen. ; Der Name klingt fast wie ein Gewächs. | GLaDOS gilt als eine der besten Bösewichtinnen der Spielegeschichte.
C H | Welches Spiel hält den Rekord für das höchste Preisgeld eines einzelnen E-Sport-Turniers (über 40 Mio. US-Dollar, 2021)? | Dota 2 | Fortnite ; Counter-Strike ; Call of Duty | Das Turnier heißt „The International“. ; Das Preisgeld wird durch Spielerkäufe aufgestockt. ; Es stammt von Valve. | Beim International 2021 lag der Preispool bei über 40 Millionen Dollar.
C H | Welches Studio aus Seattle entwickelt die „Halo“-Nachfolger nach Bungie? | 343 Industries | Respawn ; Infinity Ward ; Valve | Der Name ist eine Zahl. ; Er stammt von einer Figur aus Halo. ; Es gehört zu Microsoft. | 343 Industries übernahm Halo, nachdem Bungie 2010 eigenständig wurde. Seit 2024 heißt das Studio Halo Studios.
C U | Welches Spiel gilt mit Geräten wie „Tennis for Two“ (1958) als eines der ersten Videospiele überhaupt? | Spacewar! | Pong ; Computer Space ; OXO | Es lief 1962 auf einem Großrechner am MIT. ; Zwei Raumschiffe kämpfen gegeneinander. ; Im Titel steckt ein Ausrufezeichen. | Spacewar! wurde auf einem PDP-1-Computer programmiert.
W E | „Among Us“ spielt auf einem Raumschiff, auf dem sich ein Verräter versteckt. | wahr | Die „Impostors“ sabotieren das Schiff und schalten Crewmitglieder aus.
W M | Twitch gehört zum Google-Konzern. | falsch | Twitch gehört seit 2014 zu Amazon — YouTube gehört zu Google.
W M | Stardew Valley wurde von einem einzigen Entwickler programmiert. | wahr | Eric Barone schrieb Code, Musik und Grafiken fast komplett allein.
W H | Das Wort „Noob“ stammt vom englischen „newbie“ für Neuling. | wahr | „Newbie“ wurde im Internet zu „Noob“ verkürzt — heute oft abwertend gemeint.
W U | Das erste Videospiel-Easter-Egg versteckte ein Nintendo-Entwickler. | falsch | Als erstes berühmtes Easter Egg gilt Warren Robinetts Name im Atari-Spiel „Adventure“ von 1979.
S M | In welchem Jahr ging die Streaming-Plattform Twitch an den Start? | 2011 | Jahr | 2 | 2000 | 2020 | Anfang der 2010er. ; Drei Jahre vor dem Kauf durch Amazon. ; Das Jahr endet auf 1. | Twitch entstand als Gaming-Ableger von Justin.tv.
S H | Wie viele Millionen Spieler sahen im April 2020 gleichzeitig das Travis-Scott-Konzert in Fortnite? | 12.3 | Mio. | 25 | 1 | 50 | log | Mehr als zehn Millionen. ; Weniger als 20 Millionen. ; Gut zwölf. | Über alle Wiederholungen hinweg sahen fast 28 Millionen Spieler zu.
O M | Sortiere diese Konsolen nach ihrem Erscheinungsjahr — die älteste zuerst. | Xbox 360 = 2005 ; PlayStation 4 = 2013 ; Xbox Series X = 2020 ; Nintendo Switch 2 = 2025 | Die erste hat eine Zahl mit drei Stellen. ; Sony folgt. ; Die Nintendo-Konsole ist die jüngste. | Die Switch 2 erschien im Juni 2025.
O H | Sortiere diese Spiele nach ihrem Erscheinungsjahr — das älteste zuerst. | Portal = 2007 ; Minecraft = 2011 ; Among Us = 2018 ; Fall Guys = 2020 | Das Löcherspiel mit dem Kuchen kam zuerst. ; Die Würfelwelt erschien 2011 in Version 1.0. ; Die Bohnen-Parcours sind die jüngsten. | Among Us erschien schon 2018 — berühmt wurde es erst zwei Jahre später.
M E | Welche ZWEI dieser Spiele sind Handyspiele mit Endlos-Lauf? | Subway Surfers ; Temple Run | Minecraft ; Tetris ; Die Sims ; Portal | Man rennt, bis man scheitert. ; Einer spielt auf Gleisen. ; Der andere an einem Tempel. | Endlos-Läufer eignen sich perfekt für kurze Pausen am Handy.
M H | Welche ZWEI dieser Spiele stammen von Valve? | Portal ; Half-Life | Halo ; Fortnite ; The Witcher ; Overwatch | Beide spielen in derselben fiktiven Welt. ; Eine Firma namens Aperture taucht in beiden auf. ; Valve betreibt auch Steam. | Halo gehört zu Microsoft, Fortnite zu Epic, The Witcher zu CD Projekt, Overwatch zu Blizzard.

@ deutsche_gaming_szene de
C E | In welcher Stadt findet die Gamescom statt? | Köln | Leipzig ; Berlin ; Hamburg | Die Stadt hat einen berühmten Dom. ; Sie liegt am Rhein. ; Vor 2009 fand die Vorgängermesse in Sachsen statt. | Die Gamescom zieht jedes Jahr im August Hunderttausende Besucher nach Köln.
C E | Welche Organisation vergibt in Deutschland die Altersfreigaben für Videospiele? | USK | FSK ; TÜV ; GEMA | Die Filmfreigaben kommen von einer ähnlichen Stelle. ; Der Name enthält „Unterhaltungssoftware“. ; Die Abkürzung hat drei Buchstaben. | Die Unterhaltungssoftware Selbstkontrolle sitzt in Berlin.
C M | Welches Moorhuhn-Spiel wurde um 2000 in deutschen Büros zum Massenphänomen? | Moorhuhn | Wildgans ; Fasanenjagd ; Entenhausen | Man schießt auf Vögel. ; Es war ursprünglich Werbung für einen Whisky. ; Der Name nennt das Tier. | Die Moorhuhn-Jagd war ein Werbespiel für Johnnie Walker und wurde millionenfach kopiert.
C M | In welcher Stadt fand vor der Gamescom die „Games Convention“ statt? | Leipzig | Dresden ; Hannover ; Frankfurt | Die Stadt liegt in Sachsen. ; Sie hat eine berühmte Buchmesse. ; Bis 2008. | Nach der Games Convention in Leipzig (2002–2008) zog die Messe als Gamescom nach Köln.
C M | Welches deutsche Studio entwickelte die Aufbauspielreihe „Die Siedler“? | Blue Byte | Crytek ; Piranha Bytes ; Daedalic | Das Studio sitzt in Nordrhein-Westfalen. ; Es gehört heute zu Ubisoft. ; Die Farbe steckt im Namen. | „Die Siedler“ erschien 1993 für den Amiga.
C H | Aus welchem Ruhrgebiets-Studio stammt die Rollenspielreihe „Gothic“? | Piranha Bytes | Blue Byte ; Ascaron ; Deck13 | Ein Raubfisch steckt im Namen. ; Der erste Teil erschien 2001. ; Auch „Risen“ und „ELEX“ stammen von dort. | Gothic ist in Deutschland ein Kultspiel mit rauem Ruhrpott-Charme.
C H | Aus welchem Land stammt das Studio Giants Software, Macher des „Landwirtschafts-Simulators“? | Schweiz | Deutschland ; Österreich ; Niederlande | Das Land ist berühmt für Käse und Uhren. ; Der Firmensitz liegt bei Zürich. ; Es ist kein EU-Land. | Der Landwirtschafts-Simulator verkauft sich besonders gut in Deutschland.
C H | Wie hieß die MTV-Sendung über Videospiele, aus deren Team 2015 Rocket Beans TV entstand? | Game One | GIGA Games ; Gamestar TV ; Level Up | Sie lief von 2006 bis 2014. ; Sie war für ihre Sketche bekannt. ; Im Namen steckt eine Zahl. | Die Macher von Game One gründeten danach den Sender Rocket Beans TV.
C U | Welcher deutsche Entwickler machte mit „Far Cry“ (2004) international Furore, bevor er „Crysis“ entwickelte? | Crytek | Yager ; Related Designs ; Spellbound | Er stammt aus Frankfurt am Main. ; Gegründet von den Brüdern Yerli. ; Die eigene Grafik-Engine heißt CryEngine. | Die Rechte an Far Cry gingen später an Ubisoft.
W E | Die Gamescom gilt als eine der größten Messen für Computerspiele der Welt. | wahr | Die Gamescom in Köln zählt jedes Jahr über 300.000 Besucher.
W M | Die Altersstufen der USK sind 0, 6, 12, 16 und 18 Jahre. | wahr | Die fünf Stufen sind mit farbigen Kennzeichen von weiß bis rot markiert.
W H | Die Anno-Reihe wird in Hamburg entwickelt. | falsch | Anno entsteht bei Ubisoft Mainz, dem früheren Studio Related Designs.
S M | Wie viele Besucher kamen 2024 ungefähr zur Gamescom (in Tausend)? | 335 | Tausend | 15 | 50 | 1000 | Mehr als 300.000. ; Weniger als eine halbe Million. ; Ein neuer Rekord damals. | 2024 kamen rund 335.000 Besucher aus über 120 Ländern.
S H | In welchem Jahr erschien das Aufbauspiel „Anno 1602“? | 1998 | Jahr | 2 | 1985 | 2010 | Ende der 1990er. ; Kurz vor der Jahrtausendwende. ; Das Jahr endet auf 8. | Anno 1602 wurde in Deutschland zum Verkaufsschlager.
O M | Sortiere die USK-Altersfreigaben von der niedrigsten zur höchsten. | USK 0 = weiß ; USK 6 = gelb ; USK 12 = grün ; USK 16 = blau | Die niedrigste Stufe ist weiß. ; Die zweite ist gelb. ; Die höchste der vier ist blau — ab 18 wäre rot. | Die Farben helfen Eltern, die Freigabe schnell zu erkennen.
M M | Welche ZWEI dieser Spiele hat Nintendo selbst entwickelt? | Mario Kart 8 ; Animal Crossing: New Horizons | Minecraft ; Fortnite ; Pokémon Go ; Tetris | Eines ist ein Rennspiel. ; Das andere spielt auf einer Insel. ; Pokémon Go stammt von einer anderen Firma. | Pokémon Go entwickelte Niantic, Minecraft Mojang und Fortnite Epic Games.
"""
