"""Extra questions, wave 2: Geographie (format: see tools/content/merge_extra.py)."""
KAT = "geographie"
REGION = "global"
DATA = r"""
@ laender_hauptstaedte
E E | Welche Hauptstadt ist hier gesucht? | 🧜‍♀️🚲🇩🇰 | Kopenhagen | Oslo ; Stockholm ; Helsinki | Am Hafen sitzt eine berühmte kleine Bronzefigur. ; Die Stadt gilt als eine der fahrradfreundlichsten der Welt. ; Sie liegt auf den Inseln Seeland und Amager. | Die Kleine Meerjungfrau misst nur gut einen Meter — und ist trotzdem eines der meistfotografierten Wahrzeichen Nordeuropas.
E M | Welche Hauptstadt ist hier gesucht? | 🍁🏛️⛸️ | Ottawa | Toronto ; Montreal ; Vancouver | Viele halten eine andere, größere Stadt des Landes für die Hauptstadt. ; Im Winter wird hier ein Kanal zur Eislaufbahn. ; Sie liegt in der Provinz Ontario. | Der zugefrorene Rideau-Kanal wird jeden Winter zu einer knapp acht Kilometer langen Schlittschuhstrecke mitten durch die Stadt.
C E | Welche Stadt ist die Hauptstadt Irlands? | Dublin | Cork ; Belfast ; Galway | Sie liegt an der Ostküste der Insel. ; Durch die Stadt fließt der Liffey. ; Hier wird seit 1759 ein berühmtes dunkles Bier gebraut. | Arthur Guinness pachtete die Brauerei am St. James's Gate damals für sagenhafte 9.000 Jahre.
C M | Von welchem Land ist Montevideo die Hauptstadt? | Uruguay | Paraguay ; Argentinien ; Chile | Das Land liegt in Südamerika. ; Die Stadt liegt am Río de la Plata. ; Das Land wurde 1930 erster Fußball-Weltmeister. | Montevideo liegt so weit südlich, dass es die südlichste Hauptstadt Amerikas ist.
C E | Wie heißt die Hauptstadt Vietnams? | Hanoi | Ho-Chi-Minh-Stadt ; Da Nang ; Hue | Es ist nicht die größte Stadt des Landes. ; Sie liegt im Norden am Roten Fluss. ; Ihr Name bedeutet „Stadt innerhalb der Flüsse“. | Die größte Stadt Vietnams ist das frühere Saigon im Süden, das heute Ho-Chi-Minh-Stadt heißt.
C H | Welche Hauptstadt liegt am Kongo-Fluss direkt gegenüber von Kinshasa? | Brazzaville | Luanda ; Libreville ; Bangui | Sie ist die Hauptstadt der Republik Kongo. ; Sie ist nach einem französisch-italienischen Entdecker benannt. ; Zwischen den beiden Städten liegen nur wenige Kilometer Wasser. | Abgesehen von Rom und dem Vatikan liegen nirgends zwei Hauptstädte so nah beieinander.
C H | Welche Hauptstadt liegt nur rund 25 Kilometer südlich des Äquators auf fast 2.900 Metern Höhe? | Quito | Bogotá ; Lima ; La Paz | Das Land ist nach dem Äquator benannt. ; Die Stadt liegt am Fuß des Vulkans Pichincha. ; Ihre Altstadt war 1978 eine der ersten UNESCO-Welterbestätten. | Trotz Äquatornähe ist es in Quito dank der Höhenlage das ganze Jahr über frühlingshaft mild.
C U | Wie heißt die geplante neue Hauptstadt Indonesiens auf der Insel Borneo? | Nusantara | Jakarta Baru ; Balikpapan ; Samarinda | Die bisherige Hauptstadt versinkt langsam im Meer. ; Das Gesetz zum Umzug wurde 2022 beschlossen. ; Ihr Name bedeutet auf Altjavanisch etwa „Inselreich“. | Teile Jakartas sinken durch das Abpumpen von Grundwasser um mehrere Zentimeter pro Jahr.
W M | Die Hauptstadt Kasachstans heißt Astana. | wahr | Von 2019 bis 2022 hieß die Stadt Nur-Sultan — dann bekam sie ihren alten Namen Astana zurück.
W M | Die Hauptstadt von Myanmar ist Rangun. | falsch | Seit 2005 ist die eigens erbaute Planstadt Naypyidaw Regierungssitz — Rangun ist nur noch die größte Stadt des Landes.
W H | Die Regierung Boliviens hat ihren Sitz in Sucre. | falsch | Sucre ist die verfassungsmäßige Hauptstadt — Regierung und Parlament sitzen aber in La Paz.
S E | Wie viele Millionen Menschen leben ungefähr in der Stadt Paris (ohne Umland)? | 2.1 | Mio. | 25 | 0.5 | 15 | Deutlich weniger als in Berlin. ; Mehr als eine Million. ; Knapp über zwei Millionen. | Mit Umland zählt der Großraum Paris dagegen über zwölf Millionen Einwohner.
S M | Auf wie vielen Metern Höhe liegt La Paz ungefähr? | 3640 | m | 15 | 1000 | 6000 | Höher als die Zugspitze. ; Weniger als 4.000 Meter. ; Deutlich über 3.000 Meter. | In La Paz brennt Feuer schlechter und Wasser kocht schon bei rund 87 Grad — die Luft ist dort sehr dünn.
S H | An wie vielen Hauptstädten fließt die Donau direkt vorbei? | 4 | Hauptstädte | 25 | 1 | 10 | Mehr als zwei. ; Weniger als sechs. ; Wien ist eine davon. | Wien, Bratislava, Budapest und Belgrad liegen alle an der Donau — kein anderer Fluss verbindet so viele Hauptstädte.
O M | Sortiere diese Hauptstädte von Nord nach Süd — die nördlichste zuerst. | Reykjavík = ≈ 64° N ; Oslo = ≈ 60° N ; Berlin = ≈ 52,5° N ; Rom = ≈ 42° N | Die Hauptstadt auf der Vulkaninsel liegt am weitesten im Norden. ; Die norwegische folgt. ; Die italienische liegt am südlichsten. | Reykjavík ist die nördlichste Hauptstadt eines souveränen Staates der Welt.
O H | Sortiere diese Hauptstädte nach ihrer Höhenlage — die tiefste zuerst. | Amsterdam = ≈ 0 m ; Madrid = ≈ 650 m ; Mexiko-Stadt = ≈ 2.240 m ; Bogotá = ≈ 2.640 m | Die Stadt der Grachten liegt fast auf Meereshöhe. ; Die spanische Hauptstadt liegt auf einer Hochebene. ; Die kolumbianische liegt am höchsten. | Madrid ist die höchstgelegene Hauptstadt der Europäischen Union.
M E | Welche ZWEI dieser Hauptstädte liegen in Südamerika? | Lima ; Caracas | Havanna ; Panama-Stadt ; San José ; Managua | Eine liegt am Pazifik unterhalb der Anden. ; Die andere liegt nahe der Karibikküste im Norden des Kontinents. ; Die übrigen liegen in Mittelamerika oder in der Karibik. | Lima ist die Hauptstadt Perus, Caracas die Hauptstadt Venezuelas.
M H | Welche ZWEI dieser Hauptstädte liegen auf einer Insel? | Reykjavík ; Wellington | Oslo ; Lissabon ; Buenos Aires ; Kairo | Eine liegt auf einer Vulkaninsel im Nordatlantik. ; Die andere liegt an der Südspitze der Nordinsel eines Pazifikstaats. ; Beide sind Hauptstädte von Inselstaaten. | Wellington ist die südlichste Hauptstadt eines souveränen Staates — Reykjavík die nördlichste.

@ flaggen_erkennen
E E | Zu welchem Land gehört diese Flagge? | 🇯🇵🍣 | Japan | China ; Südkorea ; Vietnam | Der rote Kreis steht für die Sonne. ; Das Land besteht aus vielen Inseln. ; Die Hauptstadt ist Tokio. | Die Flagge heißt auf Japanisch „Hinomaru“ — „Sonnenscheibe“.
E E | Zu welchem Land gehört diese Flagge? | 🇨🇦🍁 | Kanada | USA ; Dänemark ; Österreich | Die Flagge ist rot-weiß. ; In der Mitte prangt ein Blatt. ; Das Land ist das zweitgrößte der Erde. | Die Ahornblatt-Flagge weht erst seit 1965 — vorher war der Union Jack Teil der kanadischen Flagge.
E E | Zu welchem Land gehört diese Flagge? | 🇯🇲🏝️ | Jamaika | Kuba ; Bahamas ; Barbados | Ein goldenes Diagonalkreuz teilt die Flagge. ; Sie zeigt Schwarz, Grün und Gold. ; Hier wurde Usain Bolt geboren. | Jamaikas Flagge ist die einzige Nationalflagge, die weder Rot noch Weiß noch Blau enthält.
E M | Zu welchem Land gehört diese Flagge? | 🇮🇸🌋 | Island | Norwegen ; Finnland ; Schweden | Die Flagge zeigt ein nordisches Kreuz. ; Der Grund ist blau, das Kreuz rot mit weißem Rand. ; Das Land liegt mitten im Nordatlantik. | Norwegens Flagge sieht aus wie die isländische mit vertauschten Farben: rotes Feld, blaues Kreuz.
E E | Zu welchem Land gehört diese Flagge? | 🇮🇪☘️ | Irland | Elfenbeinküste ; Italien ; Indien | Die Flagge ist eine senkrechte Trikolore. ; Grün liegt am Mast, Orange außen. ; Das Kleeblatt ist das Nationalsymbol. | Die Elfenbeinküste hat fast dieselbe Flagge — nur mit Orange am Mast und Grün außen.
E M | Zu welchem Land gehört diese Flagge? | 🇵🇪🦙 | Peru | Bolivien ; Chile ; Ecuador | Die Flagge zeigt senkrecht Rot, Weiß, Rot. ; In den Anden dieses Landes liegt Machu Picchu. ; Die Hauptstadt ist Lima. | Das Wappen auf der Staatsflagge zeigt ein Vikunja, einen Chinarindenbaum und ein Füllhorn.
E H | Zu welchem Land gehört diese Flagge? | 🇲🇳🐎 | Mongolei | Kasachstan ; Kirgisistan ; Usbekistan | Am Mast steht ein goldenes Symbol namens Soyombo. ; Die Flagge ist rot-blau-rot. ; Das Land liegt zwischen Russland und China. | In der Mongolei leben mehr Pferde als Menschen.
E U | Zu welchem Land gehört diese Flagge? | 🇰🇬⛺ | Kirgisistan | Kasachstan ; Tadschikistan ; Turkmenistan | Die rote Flagge zeigt eine gelbe Sonne mit 40 Strahlen. ; In der Sonne sieht man das Dachgitter einer Jurte. ; Das Land liegt im Tian-Shan-Gebirge. | Die 40 Strahlen stehen für die 40 Stämme, die der Nationalheld Manas der Sage nach vereinte.
C E | Welche Farben zeigt die Flagge Österreichs von oben nach unten? | Rot-Weiß-Rot | Rot-Gelb-Rot ; Weiß-Rot-Weiß ; Rot-Blau-Rot | Sie hat drei waagerechte Streifen. ; Die äußeren beiden sind gleichfarbig. ; Der mittlere Streifen ist hell. | Der Legende nach war der Waffenrock von Herzog Leopold V. nach einer Schlacht blutrot — nur unter dem Gürtel blieb ein weißer Streifen.
C H | Wie viele Speichen hat das blaue Rad in der Mitte der indischen Flagge? | 24 | 12 ; 16 ; 32 | Es sind mehr als 20. ; Es sind so viele, wie der Tag Stunden hat. ; Das Rad heißt Ashoka-Chakra. | Das Rad geht auf eine Säule des Kaisers Ashoka aus dem 3. Jahrhundert vor Christus zurück.
C U | Auf der Flagge welches Karibikstaates ist ein Papagei abgebildet? | Dominica | Grenada ; St. Lucia ; Barbados | Der Vogel ist eine Kaiseramazone. ; Das Land liegt zwischen Guadeloupe und Martinique. ; Es ist nicht mit der Dominikanischen Republik zu verwechseln. | Dominicas Flagge ist eine der wenigen der Welt, die die Farbe Violett zeigt — im Gefieder des Papageis.
W E | Die Flagge der Schweiz zeigt ein rotes Kreuz auf weißem Grund. | falsch | Es ist umgekehrt: ein weißes Kreuz auf Rot — das Symbol des Roten Kreuzes ist die Umkehrung zu Ehren der Schweiz.
W M | Die Flagge Australiens zeigt insgesamt sechs Sterne. | wahr | Fünf Sterne bilden das Kreuz des Südens, dazu kommt der große siebenzackige Commonwealth-Stern unter dem Union Jack.
W H | Das Ahornblatt auf der Flagge Kanadas hat genau 13 Zacken. | falsch | Das stilisierte Blatt hat elf Zacken — es wurde bewusst vereinfacht, damit es auch im Wind gut erkennbar bleibt.
S U | In welchem Jahr führte der Europarat die blaue Europaflagge mit dem Sternenkreis ein? | 1955 | Jahr | 3 | 1900 | 2000 | Nach dem Zweiten Weltkrieg. ; Noch vor den Römischen Verträgen. ; In der Mitte der 1950er-Jahre. | Die Europäische Gemeinschaft übernahm die Flagge erst 1985 — die Zahl der Sterne ändert sich nie.
O M | Sortiere diese Flaggen nach der Zahl ihrer Streifen — die wenigsten zuerst. | Ukraine = 2 ; Deutschland = 3 ; Thailand = 5 ; USA = 13 | Die blau-gelbe Flagge hat die wenigsten. ; Schwarz-Rot-Gold folgt. ; Die amerikanische hat mit Abstand die meisten. | Die 13 Streifen der US-Flagge stehen für die 13 Gründungskolonien.
M M | Welche ZWEI dieser Flaggen zeigen einen Stern? | Vietnam ; Chile | Japan ; Kanada ; Schweiz ; Frankreich | Eine ist rot mit einem gelben Stern. ; Die andere ähnelt der Flagge von Texas. ; Beide Länder liegen an einem Ozean, aber auf verschiedenen Kontinenten. | Chiles weißer Stern auf blauem Feld heißt „Estrella Solitaria“ — der einsame Stern.
M H | Welche ZWEI dieser Flaggen zeigen eine Sonne mit Gesicht? | Argentinien ; Uruguay | Peru ; Italien ; Schweden ; Brasilien | Beide Länder liegen am Río de la Plata. ; Die Sonne heißt „Sol de Mayo“. ; Sie erinnert an die Mairevolution von 1810. | Die Maisonne soll bei der Revolution in Buenos Aires durch die Wolken gebrochen sein.

@ deutschland_geographie de
E E | Welche Insel ist hier gesucht? | 🔴🪨🦭 | Helgoland | Sylt ; Föhr ; Rügen | Sie ist Deutschlands einzige Hochseeinsel. ; Ihr roter Felsen heißt „Lange Anna“. ; Am Strand der Nebeninsel Düne liegen oft Kegelrobben. | Auf Helgoland gibt es keine Autos — und Einkäufe sind dort zollfrei.
E M | Welches Gebirge ist hier gesucht? | 🧙‍♀️🧹⛰️ | Harz | Schwarzwald ; Erzgebirge ; Eifel | Hier feiert man die Walpurgisnacht. ; Sein höchster Gipfel ist der Brocken. ; Es liegt in Niedersachsen, Sachsen-Anhalt und Thüringen. | Goethe verlegte in seinem „Faust“ die Hexenversammlung der Walpurgisnacht auf den Brocken.
E M | Welche Landschaft ist hier gesucht? | 🥒🛶🌲 | Spreewald | Schwarzwald ; Bayerischer Wald ; Teutoburger Wald | Sie liegt in Brandenburg. ; Man erkundet sie mit dem Kahn. ; Berühmt sind ihre sauren Gurken. | Im Spreewald wird in manchen Dörfern die Post bis heute per Kahn ausgeliefert.
C E | Welches Bundesland grenzt an Dänemark? | Schleswig-Holstein | Niedersachsen ; Mecklenburg-Vorpommern ; Hamburg | Es ist das nördlichste Bundesland. ; Es liegt zwischen Nord- und Ostsee. ; Die Landeshauptstadt ist Kiel. | Die deutsch-dänische Landgrenze ist nur rund 68 Kilometer lang.
C M | Welche Stadt wird „Dreiflüssestadt“ genannt, weil hier Donau, Inn und Ilz zusammenfließen? | Passau | Regensburg ; Ingolstadt ; Ulm | Sie liegt in Niederbayern. ; Sie grenzt direkt an Österreich. ; Ihr Dom hat eine der größten Kirchenorgeln der Welt. | Wo die Flüsse zusammenkommen, fließt die grüne Donau neben dem hellen Inn und der dunklen Ilz — dreifarbig.
C H | An welchem Fluss liegt die Stadt Frankfurt, die NICHT am Main liegt? | Oder | Elbe ; Spree ; Neiße | Die Stadt liegt in Brandenburg. ; Der Fluss bildet die Grenze zu Polen. ; Auf der anderen Seite liegt die polnische Stadt Słubice. | Die polnische Nachbarstadt Słubice war bis 1945 ein Stadtteil von Frankfurt.
C U | Welcher Ort gilt nach der gängigsten Berechnung als geografischer Mittelpunkt Deutschlands? | Niederdorla | Kassel ; Fulda ; Göttingen | Er liegt in Thüringen. ; Er gehört heute zur Gemeinde Vogtei. ; An der Stelle wurde eine Kaiserlinde gepflanzt. | Je nach Berechnungsmethode gibt es in Deutschland über ein Dutzend Orte, die sich „Mittelpunkt“ nennen.
C U | Welcher ist der tiefste See, der vollständig in Deutschland liegt? | Königssee | Starnberger See ; Chiemsee ; Müritz | Er liegt im Berchtesgadener Land. ; Er ist rund 190 Meter tief. ; Auf ihm fahren nur Elektro- und Ruderboote. | Berühmt ist das Echo am Königssee: Ein Trompeter auf dem Boot spielt es den Fahrgästen vor.
W E | Berlin ist die flächenmäßig größte Stadt Deutschlands. | wahr | Mit rund 891 Quadratkilometern ist Berlin nicht nur die bevölkerungsreichste, sondern auch die flächenmäßig größte Stadt.
W E | Die Mosel mündet in den Main. | falsch | Die Mosel fließt am Deutschen Eck in Koblenz in den Rhein.
W E | Die Elbe mündet bei Cuxhaven in die Nordsee. | wahr | Nach rund 1.100 Kilometern von Tschechien aus erreicht die Elbe bei Cuxhaven die Nordsee.
S H | Wie viele Meter hoch ist der Fichtelberg im Erzgebirge? | 1215 | m | 10 | 500 | 3000 | Mehr als 1.000 Meter. ; Weniger als 1.300 Meter. ; Er ist der höchste Berg Sachsens. | Der Fichtelberg war bis 1990 der höchste Berg der DDR — auf seinem Gipfel steht Deutschlands älteste Schwebebahn.
S M | Wie viele Quadratkilometer groß ist der Bodensee ungefähr? | 536 | km² | 15 | 100 | 2000 | Mehr als 400. ; Weniger als 600. ; Gut ein halbes Tausend. | Am Bodensee grenzen Deutschland, Österreich und die Schweiz — eine offizielle Grenzziehung im See gibt es bis heute nicht.
S U | Wie viele Kilometer misst Deutschland von seinem nördlichsten bis zum südlichsten Punkt (Luftlinie)? | 876 | km | 15 | 300 | 2000 | Mehr als 800. ; Weniger als 1.000. ; Von List auf Sylt bis zum Haldenwanger Eck im Allgäu. | Von West nach Ost sind es dagegen nur rund 640 Kilometer.
O E | Sortiere diese Städte von Nord nach Süd — die nördlichste zuerst. | Kiel = ≈ 54,3° N ; Hannover = ≈ 52,4° N ; Frankfurt am Main = ≈ 50,1° N ; München = ≈ 48,1° N | Die Landeshauptstadt an der Förde liegt am weitesten im Norden. ; Die niedersächsische Hauptstadt folgt. ; Die bayerische liegt am südlichsten. | Zwischen Kiel und München liegen rund 700 Kilometer Luftlinie.
O H | Sortiere diese deutschen Gipfel nach ihrer Höhe — den niedrigsten zuerst. | Brocken = 1.141 m ; Großer Arber = 1.456 m ; Feldberg = 1.493 m ; Zugspitze = 2.962 m | Der Hexenberg im Harz ist der niedrigste. ; Der König des Bayerischen Waldes folgt. ; Der einzige Alpengipfel der Liste ist der höchste. | Der Feldberg im Schwarzwald ist der höchste deutsche Berg außerhalb der Alpen.
M M | Welche ZWEI dieser Städte sind Landeshauptstädte? | Wiesbaden ; Schwerin | Frankfurt am Main ; Köln ; Rostock ; Nürnberg | Eine liegt in Hessen. ; Die andere in Mecklenburg-Vorpommern. ; Die falschen sind jeweils die größten Städte ihres Bundeslandes. | Schwerin ist mit rund 100.000 Einwohnern die kleinste Landeshauptstadt eines Flächenlandes.

@ europa
E E | Welches Land ist hier gesucht? | 🌷🚲🧀 | Niederlande | Belgien ; Dänemark ; Schweiz | Hier gibt es mehr Fahrräder als Einwohner. ; Große Teile liegen unter dem Meeresspiegel. ; Die Hauptstadt ist Amsterdam. | Rund ein Viertel der Niederlande liegt unter dem Meeresspiegel — geschützt durch Deiche und Pumpwerke.
E M | Welches Land ist hier gesucht? | 🍫🧇🍟 | Belgien | Niederlande ; Frankreich ; Luxemburg | Hier sitzt die EU-Kommission. ; Man spricht Niederländisch, Französisch und Deutsch. ; Das Land beansprucht die Erfindung der Pommes für sich. | In Belgien gibt es eigene Pommesbuden mit dem Namen „Frituur“ oder „Friterie“.
E H | Welches Land ist hier gesucht? | 🎅🦌❄️ | Finnland | Norwegen ; Schweden ; Island | Hier soll der Weihnachtsmann offiziell wohnen. ; Das Land hat rund 188.000 Seen. ; Die Hauptstadt ist Helsinki. | Im Weihnachtsmanndorf bei Rowaniemi kreuzt man den nördlichen Polarkreis.
C E | Welches Gebirge trennt Spanien von Frankreich? | Pyrenäen | Alpen ; Apenninen ; Karpaten | Es reicht vom Atlantik bis zum Mittelmeer. ; Die Tour de France fährt oft hindurch. ; In ihm liegt der Kleinstaat Andorra. | Die Pyrenäen sind rund 430 Kilometer lang — ihr höchster Gipfel ist der Aneto mit gut 3.400 Metern.
C M | In welchem Land liegen die Plitvicer Seen? | Kroatien | Slowenien ; Bosnien und Herzegowina ; Montenegro | 16 Seen sind über Wasserfälle verbunden. ; Hier wurden Karl-May-Filme gedreht. ; Das Land liegt an der Adria. | Der Nationalpark gehört seit 1979 zum UNESCO-Welterbe.
C M | Welche Meerenge trennt Dänemark und Schweden? | Öresund | Skagerrak ; Kattegat ; Fehmarnbelt | An ihr liegen Kopenhagen und Malmö. ; Seit 2000 überspannt sie eine Brücke mit Tunnel. ; Die Brücke wurde durch eine Krimiserie weltberühmt. | Die Öresundverbindung beginnt als Tunnel, führt über eine künstliche Insel und endet als Brücke.
C H | Welches Land grenzt sowohl an die Ostsee als auch an das Schwarze Meer? | Russland | Polen ; Ukraine ; Rumänien | Es ist das größte Land der Erde. ; An der Ostsee liegt seine zweitgrößte Stadt. ; Am Schwarzen Meer liegt der Badeort Sotschi. | Außerdem grenzt Russland an den Arktischen und den Pazifischen Ozean.
C U | Wie heißt der längste Fjord Norwegens? | Sognefjord | Geirangerfjord ; Hardangerfjord ; Oslofjord | Er ist rund 200 Kilometer lang. ; Er ist auch bis zu 1.300 Meter tief. ; Er liegt nördlich von Bergen. | Nur der Scoresbysund in Grönland ist als Fjord noch länger.
W E | Norwegen ist Mitglied der Europäischen Union. | falsch | Die Norwegerinnen und Norweger lehnten den Beitritt 1972 und 1994 in Volksabstimmungen ab.
W M | Island liegt auf zwei Kontinentalplatten. | wahr | Mitten durch die Insel verläuft die Grenze zwischen Nordamerikanischer und Eurasischer Platte — im Nationalpark Þingvellir sieht man die Spalte.
W H | Die Donau fließt durch mehr Länder als jeder andere Fluss der Erde. | wahr | Die Donau durchfließt oder berührt zehn Staaten — von Deutschland bis zur Ukraine.
S M | Wie viele Tausend Menschen leben ungefähr in Island? | 390 | Tsd. | 20 | 50 | 3000 | Weniger als eine halbe Million. ; Mehr als 300.000. ; Etwa so viele wie in Bochum. | Rund zwei Drittel aller Isländer leben im Großraum Reykjavík.
S H | Wie viele Meter hoch ist der Ätna ungefähr? | 3350 | m | 10 | 1000 | 6000 | Mehr als 3.000 Meter. ; Weniger als 3.500 Meter. ; Die Höhe ändert sich durch Ausbrüche ständig. | Der Ätna auf Sizilien ist der höchste aktive Vulkan Europas.
S U | Wie viele Kilometer lang ist der Eurotunnel unter dem Ärmelkanal ungefähr? | 50 | km | 15 | 10 | 200 | Mehr als 40. ; Weniger als 60. ; Knapp 40 Kilometer davon liegen unter dem Meer. | Kein anderer Unterwassertunnel der Welt hat einen so langen Abschnitt unter dem Meeresboden.
O M | Sortiere diese Länder nach ihrer Fläche — das kleinste zuerst. | Malta = ≈ 316 km² ; Luxemburg = ≈ 2.590 km² ; Belgien = ≈ 30.700 km² ; Portugal = ≈ 92.000 km² | Der Inselstaat im Mittelmeer ist am kleinsten. ; Das Großherzogtum folgt. ; Das Land am Atlantik ist am größten. | Malta ist der kleinste Mitgliedsstaat der EU.
O H | Sortiere diese Vulkane nach ihrer Höhe — den niedrigsten zuerst. | Stromboli = 924 m ; Vesuv = ≈ 1.280 m ; Hekla = ≈ 1.490 m ; Teide = 3.715 m | Der Vulkan auf der Liparischen Insel ist der niedrigste. ; Der Vulkan am Golf von Neapel folgt. ; Der Gipfel auf den Kanaren ist der höchste. | Der Teide auf Teneriffa ist zugleich der höchste Berg Spaniens.
M M | Welche ZWEI dieser Länder haben keinen Zugang zum Meer? | Ungarn ; Tschechien | Kroatien ; Slowenien ; Bulgarien ; Litauen | Eine Hauptstadt liegt an der Donau. ; Die andere an der Moldau. ; Slowenien hat einen kurzen Küstenstreifen an der Adria. | Ungarn hat mit dem Balaton aber das „Ungarische Meer“ — den größten See Mitteleuropas.
M H | Welche ZWEI dieser EU-Länder zahlen NICHT mit dem Euro? | Polen ; Dänemark | Kroatien ; Finnland ; Slowakei ; Irland | Ein Land zahlt mit dem Złoty. ; Das andere mit der Krone. ; Kroatien führte den Euro 2023 ein. | Dänemark hat sich vertraglich das Recht gesichert, den Euro nicht einführen zu müssen.

@ erd_rekorde
E E | Welche Wüste ist hier gesucht? | 🐪🏜️☀️ | Sahara | Gobi ; Kalahari ; Atacama | Sie ist die größte heiße Wüste der Erde. ; Sie liegt in Nordafrika. ; Ihr Name bedeutet auf Arabisch einfach „Wüste“. | Nur ein kleiner Teil der Sahara besteht aus Sanddünen — der Großteil ist Stein- und Geröllwüste.
E M | Welcher Ozean ist hier gesucht? | ☮️🌊 | Pazifik | Atlantik ; Indischer Ozean ; Arktischer Ozean | Er ist der größte Ozean. ; Sein Name bedeutet „der Friedliche“. ; Magellan gab ihm 1520 diesen Namen. | Der Pazifik ist größer als alle Landflächen der Erde zusammen.
E H | Welcher Fluss ist hier gesucht? | 🐊🔺🏜️ | Nil | Kongo ; Niger ; Sambesi | Er fließt durch eine Wüste. ; An seinem Ufer stehen Pyramiden. ; Er mündet ins Mittelmeer. | Der Nil speist sich aus zwei Hauptarmen — dem Weißen und dem Blauen Nil, die sich in Khartum treffen.
C M | Welches ist das flächenmäßig größte Land Afrikas? | Algerien | Sudan ; Demokratische Republik Kongo ; Libyen | Es liegt in Nordafrika. ; Über 80 Prozent seiner Fläche sind Wüste. ; Die Hauptstadt ist Algier. | Algerien wurde erst 2011 zum größten Land Afrikas — als sich der Südsudan vom Sudan abspaltete.
C M | Welcher ist nach Fläche der größte Süßwassersee der Erde? | Oberer See | Victoriasee ; Baikalsee ; Huronsee | Er gehört zu den Großen Seen Nordamerikas. ; Er liegt an der Grenze zwischen Kanada und den USA. ; Sein Name verrät, dass er ganz oben liegt. | Das Kaspische Meer ist zwar größer — sein Wasser ist aber salzig.
C U | Welches Land hat inklusive seiner Überseegebiete die meisten Zeitzonen? | Frankreich | Russland ; USA ; China | Es ist ein europäisches Land. ; Zu ihm gehören Inseln in Karibik, Pazifik und Indischem Ozean. ; Seine Hauptstadt ist Paris. | Mit Französisch-Polynesien, Réunion, Guadeloupe und Co. kommt Frankreich auf zwölf Zeitzonen.
C H | Welcher Wasserfall hat die größte Fallhöhe der Welt? | Salto Ángel | Victoriafälle ; Niagarafälle ; Iguazú-Fälle | Er liegt in Venezuela. ; Er stürzt rund 979 Meter in die Tiefe. ; Er ist nach einem US-Piloten benannt. | Jimmie Angel landete 1937 mit seinem Flugzeug auf dem Tafelberg über dem Wasserfall — und blieb im Sumpf stecken.
C U | Welches ist der größte Binnenstaat der Welt? | Kasachstan | Mongolei ; Tschad ; Bolivien | Das Land liegt in Zentralasien. ; Es ist größer als ganz Westeuropa. ; Von hier starten die russischen Raumflüge. | Das Kaspische Meer an seiner Westgrenze gilt als See — deshalb zählt Kasachstan als Binnenstaat.
C U | Wie heißt die tiefste bekannte Stelle der Weltmeere im Marianengraben? | Challengertief | Horizontief ; Sirenatief ; Kermadectief | Sie liegt im westlichen Pazifik. ; Sie ist rund 11.000 Meter tief. ; Sie ist nach einem britischen Forschungsschiff benannt. | 2012 tauchte Filmregisseur James Cameron als erster Mensch allein bis zum Grund hinab.
W E | Der Mount Everest wird durch die Plattenbewegung jedes Jahr ein kleines Stück höher. | wahr | Die Indische Platte schiebt sich unter die Eurasische — der Himalaya wächst dadurch um wenige Millimeter pro Jahr.
W E | Der Nil fließt von Norden nach Süden. | falsch | Der Nil fließt nach Norden — von Ostafrika bis ins Mittelmeer.
W H | Vom Erdmittelpunkt aus gemessen ist der Mount Everest der höchste Berg der Erde. | falsch | Wegen des Äquatorwulstes ragt der Gipfel des Chimborazo in Ecuador am weitesten ins All hinaus.
S H | Wie viele Meter hoch ist der Aconcagua, der höchste Berg Amerikas? | 6961 | m | 10 | 3000 | 10000 | Weniger als 7.000 Meter. ; Mehr als 6.500 Meter. ; Er ist der höchste Berg außerhalb Asiens. | Der Aconcagua in Argentinien lässt sich über die Normalroute ohne Kletterausrüstung besteigen.
S U log | Wie viele Quadratkilometer groß ist der Baikalsee ungefähr? | 31700 | km² | 20 | 1000 | 1000000 | Mehr als 20.000. ; Weniger als 50.000. ; Etwa so groß wie Belgien. | Der Baikalsee enthält rund ein Fünftel des gesamten flüssigen Süßwassers auf der Erdoberfläche.
O M | Sortiere diese Seen nach ihrer größten Tiefe — den flachsten zuerst. | Victoriasee = ≈ 80 m ; Bodensee = 251 m ; Tanganjikasee = ≈ 1.470 m ; Baikalsee = ≈ 1.640 m | Der riesige afrikanische See ist erstaunlich flach. ; Der See an der deutschen Südgrenze folgt. ; Der sibirische See ist der tiefste der Welt. | Der Victoriasee ist der flächengrößte See Afrikas — und trotzdem kaum tiefer als ein Hochhaus hoch ist.
O M | Sortiere diese Länder nach ihrer Einwohnerzahl — das bevölkerungsärmste zuerst. | Kanada = ≈ 40 Mio. ; Deutschland = ≈ 84 Mio. ; USA = ≈ 335 Mio. ; Indien = ≈ 1,4 Mrd. | Das zweitgrößte Land der Erde hat die wenigsten Einwohner. ; Deutschland folgt. ; Das Land am Ganges hat die meisten. | Indien hat China 2023 als bevölkerungsreichstes Land der Erde abgelöst.
M H | Welche ZWEI dieser Länder liegen auf zwei Kontinenten? | Türkei ; Ägypten | Italien ; Griechenland ; Marokko ; Iran | Eines verbindet Europa und Asien. ; Das andere verbindet Afrika und Asien. ; Bei einem gehört die Sinai-Halbinsel zu Asien. | Istanbul ist die einzige Millionenstadt, die auf zwei Kontinenten liegt.

@ staedte_wahrzeichen
E E | Welches Wahrzeichen ist hier gesucht? | 🏰🦢👑 | Schloss Neuschwanstein | Schloss Linderhof ; Burg Hohenzollern ; Schloss Sanssouci | Es wurde für den „Märchenkönig“ gebaut. ; Es diente als Vorbild für ein berühmtes Disney-Schloss. ; Es steht im Allgäu bei Füssen. | König Ludwig II. wohnte nur rund 170 Tage in seinem Schloss — fertig wurde es nie.
E M | Welches Wahrzeichen ist hier gesucht? | 🕰️🔔🇬🇧 | Big Ben | Tower Bridge ; London Eye ; Westminster Abbey | Eigentlich trägt nur die Glocke diesen Namen. ; Der Turm steht am Parlament. ; Er steht an der Themse. | Der Turm heißt offiziell seit 2012 „Elizabeth Tower“ — zu Ehren von Königin Elisabeth II.
E H | Welche Stadt ist hier gesucht? | 🦘🎭⛵ | Sydney | Melbourne ; Brisbane ; Perth | Das Opernhaus sieht aus wie geblähte Segel. ; Die Stadt ist NICHT die Hauptstadt ihres Landes. ; Hier steht die „Harbour Bridge“. | Das Opernhaus entwarf der Däne Jørn Utzon — die Eröffnung erlebte er nicht mehr vor Ort.
C M | In welcher Stadt steht das Atomium? | Brüssel | Antwerpen ; Amsterdam ; Luxemburg | Es wurde für eine Weltausstellung gebaut. ; Es zeigt einen stark vergrößerten Eisenkristall. ; Die Stadt ist Sitz der EU-Kommission. | Das Atomium von 1958 stellt einen Eisenkristall in 165-milliardenfacher Vergrößerung dar.
C M | In welcher Stadt überquert die Karlsbrücke die Moldau? | Prag | Wien ; Budapest ; Krakau | Die Brücke ist mit 30 Statuen geschmückt. ; Kaiser Karl IV. ließ sie bauen. ; Die Stadt ist die Hauptstadt Tschechiens. | Der Legende nach wurde dem Mörtel der Karlsbrücke Eigelb beigemischt, um sie stabiler zu machen.
C M | In welcher Stadt steht die Alhambra? | Granada | Sevilla ; Córdoba ; Málaga | Die Stadt liegt in Andalusien. ; Die Burg wurde von maurischen Herrschern erbaut. ; Im Hintergrund erhebt sich die Sierra Nevada. | Der Name Alhambra kommt vom arabischen „die Rote“ — wegen der rötlichen Mauern.
C H | In welcher Stadt stehen die Petronas Towers? | Kuala Lumpur | Singapur ; Jakarta ; Bangkok | Die Zwillingstürme sind durch eine Himmelsbrücke verbunden. ; Sie waren von 1998 bis 2004 die höchsten Gebäude der Welt. ; Die Stadt ist die Hauptstadt Malaysias. | Der Grundriss der Türme folgt einem achtzackigen Stern aus der islamischen Kunst.
C H | In welcher Stadt steht die Space Needle? | Seattle | Portland ; San Francisco ; Vancouver | Sie wurde für die Weltausstellung 1962 gebaut. ; Die Stadt liegt im Nordwesten der USA. ; Hier wurde 1971 Starbucks gegründet. | Seit 2018 hat die Space Needle den ersten drehbaren Glasboden der Welt.
W M | Der Schiefe Turm von Pisa neigte sich schon während der Bauzeit. | wahr | Schon nach dem dritten Stockwerk sackte der weiche Boden ab — die Baumeister bauten die oberen Etagen deshalb leicht gekrümmt weiter.
W M | Die Christusstatue in Rio de Janeiro ist ohne Sockel größer als die Freiheitsstatue ohne Sockel. | falsch | Ohne Sockel misst Cristo Redentor rund 30 Meter, die Freiheitsstatue gut 46 Meter — beide stehen aber erhöht und wirken riesig.
W H | Der Kölner Dom war nach seiner Fertigstellung 1880 kurzzeitig das höchste Gebäude der Welt. | wahr | Erst 1884 überholte ihn das Washington Monument in den USA.
S H | In welchem Jahr wurde die Golden Gate Bridge eröffnet? | 1937 | Jahr | 3 | 1900 | 1990 | In den 1930er-Jahren. ; Nach der Weltwirtschaftskrise. ; Kurz vor dem Zweiten Weltkrieg. | Bei der Eröffnung war sie die längste Hängebrücke der Welt.
S H | In welchem Jahr wurde die Tower Bridge in London eröffnet? | 1894 | Jahr | 3 | 1800 | 1990 | Im 19. Jahrhundert. ; Zur Regierungszeit von Königin Victoria. ; In den 1890er-Jahren. | Ihre Klappen wurden anfangs von dampfbetriebenen Hydraulikpumpen angehoben.
S U | In welchem Jahr wurde der Grundstein der Sagrada Família in Barcelona gelegt? | 1882 | Jahr | 5 | 1700 | 1990 | Im 19. Jahrhundert. ; Antoni Gaudí übernahm ein Jahr später die Bauleitung. ; In den 1880er-Jahren. | Gaudí arbeitete über 40 Jahre an der Kirche — begraben ist er in ihrer Krypta.
O M | Sortiere diese Bauwerke nach ihrer Höhe — das niedrigste zuerst. | Freiheitsstatue (mit Sockel) = 93 m ; Kölner Dom = 157 m ; Eiffelturm = 330 m ; Burj Khalifa = 828 m | Die New Yorker Statue ist am niedrigsten. ; Die Kathedrale am Rhein folgt. ; Der Wolkenkratzer in Dubai ist der höchste. | Der Burj Khalifa ist höher als die anderen drei Bauwerke übereinandergestapelt.
O H | Sortiere diese Wahrzeichen nach ihrer Fertigstellung — das älteste zuerst. | Kolosseum = 80 n. Chr. ; White Tower (Tower of London) = ≈ 1100 ; Taj Mahal = ≈ 1650 ; Eiffelturm = 1889 | Das römische Amphitheater ist am ältesten. ; Die normannische Festung in London folgt. ; Der eiserne Turm in Paris ist der jüngste. | Der Taj Mahal ist ein Grabmal — Großmogul Shah Jahan ließ ihn für seine verstorbene Frau errichten.
M E | Welche ZWEI dieser Wahrzeichen stehen in Paris? | Eiffelturm ; Arc de Triomphe | Big Ben ; Brandenburger Tor ; Kolosseum ; Atomium | Beide stehen in der französischen Hauptstadt. ; Eines ist ein eiserner Turm. ; Das andere ist ein Triumphbogen. | Vom Arc de Triomphe gehen zwölf Straßen sternförmig ab — der Platz hieß lange „Place de l'Étoile“.
M E | Welche ZWEI dieser Wahrzeichen stehen in Rom? | Trevi-Brunnen ; Pantheon | Rialtobrücke ; Schiefer Turm ; Mailänder Scala ; Ponte Vecchio | Beide stehen in der italienischen Hauptstadt. ; In einen wirft man Münzen. ; Das andere hat eine Kuppel mit einem Loch in der Mitte. | Aus dem Trevi-Brunnen werden jedes Jahr über eine Million Euro an Münzen gefischt — das Geld geht an die Caritas.
M H | Welche ZWEI dieser Bauwerke stehen in Barcelona? | Sagrada Família ; Park Güell | Alhambra ; Prado ; Guggenheim-Museum ; Mezquita | Beide stammen vom selben Architekten. ; Er hieß Antoni Gaudí. ; Die Stadt ist die Hauptstadt Kataloniens. | Der Park Güell sollte ursprünglich eine Gartenstadt für wohlhabende Familien werden — verkauft wurden nur zwei Grundstücke.
"""
