"""Extra questions, wave 2: Geschichte (format: see tools/content/merge_extra.py)."""
KAT = "geschichte"
REGION = "global"
DATA = r"""
@ antike
C E | Welcher griechische Gott herrschte nach dem Glauben der alten Griechen über das Meer? | Poseidon | Hermes ; Apollon ; Hades | Er trägt einen Dreizack. ; Sein Bruder ist Zeus. ; Die Römer nannten ihn Neptun. | Poseidon galt auch als Verursacher von Erdbeben — die Griechen nannten ihn deshalb den „Erderschütterer“.
C M | Welches Weltwunder der Antike war eine riesige Bronzestatue des Sonnengottes Helios? | Koloss von Rhodos | Zeusstatue von Olympia ; Mausoleum von Halikarnassos ; Artemistempel von Ephesos | Sie war über 30 Meter hoch. ; Sie stand nur wenige Jahrzehnte. ; Die gleichnamige Insel liegt vor der türkischen Küste. | Um 226 v. Chr. brachte ein Erdbeben den Koloss zum Einsturz — er stand damit nur gut ein halbes Jahrhundert.
C E | Welcher Kalender, den Julius Cäsar 45 v. Chr. einführte, galt in Europa rund 1600 Jahre lang? | Julianischer Kalender | Gregorianischer Kalender ; Maya-Kalender ; Mondkalender | Er hatte bereits alle vier Jahre ein Schaltjahr. ; 1582 löste ihn eine päpstliche Reform ab. ; Sein Name leitet sich vom Vornamen seines Stifters ab. | Einige orthodoxe Kirchen richten sich bis heute nach diesem Kalender — deshalb feiern sie Weihnachten erst im Januar.
C H | Welche Pharaonin ließ sich im 15. Jahrhundert v. Chr. mit einem künstlichen Königsbart darstellen? | Hatschepsut | Nofretete ; Kleopatra VII. ; Teje | Sie regierte rund 20 Jahre. ; Ihr Totentempel liegt in Deir el-Bahari. ; Ihr Name bedeutet „Die Erste der edlen Damen“. | Ihr Nachfolger Thutmosis III. ließ später viele ihrer Bilder und Namen aus den Tempeln tilgen.
C U | Welcher griechische Gelehrte bestimmte um 240 v. Chr. den Erdumfang erstaunlich genau? | Eratosthenes | Archimedes ; Pythagoras ; Ptolemäus | Er leitete die Bibliothek von Alexandria. ; Er verglich den Sonnenstand in zwei ägyptischen Städten. ; Nach ihm ist ein Sieb zum Finden von Primzahlen benannt. | Er maß den Schattenwinkel in Alexandria, während die Sonne in Syene (heute Assuan) zur Sommersonnenwende mittags senkrecht stand.
E M | Welcher Begriff aus der Antike ist hier gesucht? | 👑🗡️🧵 | Damoklesschwert | Gordischer Knoten ; Achillesferse ; Trojanisches Pferd | Es geht um eine ständig drohende Gefahr. ; Ein Höfling durfte kurz auf dem Thron eines Tyrannen sitzen. ; Die Waffe hing nur an einem Pferdehaar. | Cicero erzählt, wie der Tyrann Dionysios von Syrakus dem neidischen Damokles so vorführte, wie gefährlich ein Leben voller Macht ist.
E M | Welcher Begriff aus der Antike ist hier gesucht? | 🏆⚔️😵 | Pyrrhussieg | Olympiasieg ; Triumphzug ; Lorbeerkranz | Es ist ein Erfolg, der teuer bezahlt wird. ; Der Namensgeber war ein König von Epirus. ; Er kämpfte 280 und 279 v. Chr. gegen Rom. | König Pyrrhos soll nach der Schlacht bei Asculum gesagt haben: „Noch ein solcher Sieg, und wir sind verloren.“
E M | Welche antike Legende ist hier gesucht? | 🪢⚔️👑 | Gordischer Knoten | Damoklesschwert ; Büchse der Pandora ; Trojanisches Pferd | Wer ihn löst, sollte Herrscher über Asien werden. ; Er befand sich in der phrygischen Stadt Gordion. ; Der Legende nach durchschlug Alexander der Große ihn mit dem Schwert. | Bis heute sagt man „den gordischen Knoten durchschlagen“, wenn jemand ein kniffliges Problem mit einem kühnen Schritt löst.
E H | Welcher antike Philosoph ist hier gesucht? | 🏺🧔☀️ | Diogenes | Sokrates ; Platon ; Aristoteles | Er lebte bewusst in Armut. ; Er wohnte der Überlieferung nach in einem großen Tonfass. ; Alexander den Großen bat er nur, ihm aus der Sonne zu gehen. | Diogenes von Sinope gilt als berühmtester Kyniker — sein „Fass“ war wohl ein großes Vorratsgefäß aus Ton.
W E | Der Monat Juli ist nach Julius Cäsar benannt. | wahr | Der Monat hieß früher Quintilis und wurde nach Cäsars Tod zu seinen Ehren umbenannt — der August erhielt später den Namen von Kaiser Augustus.
W E | Alexander der Große wurde über 70 Jahre alt. | falsch | Alexander starb 323 v. Chr. in Babylon mit nur 32 Jahren — da reichte sein Reich bereits bis nach Indien.
W H | Julius Cäsar kam per Kaiserschnitt zur Welt. | falsch | Seine Mutter Aurelia lebte noch Jahrzehnte nach seiner Geburt — ein Kaiserschnitt endete damals für die Mutter fast immer tödlich.
S H | Wie viele Jahre regierte Pharao Ramses II. ungefähr? | 66 | Jahre | 3 | 10 | 100 | Mehr als ein halbes Jahrhundert. ; Er wurde wohl rund 90 Jahre alt. ; Zwischen 60 und 70 Jahren. | Ramses II. ließ unter anderem die Felsentempel von Abu Simbel errichten — kaum ein Pharao hinterließ mehr Bauwerke.
S H | Wie viele Kilometer lang war der Obergermanisch-Raetische Limes ungefähr? | 550 | Kilometer | 15 | 100 | 2000 | Mehr als 300 Kilometer. ; Weniger als 1000 Kilometer. ; Er reichte vom Rhein bis zur Donau. | Der Grenzwall ist seit 2005 UNESCO-Welterbe und gilt als längstes Bodendenkmal Europas.
S U | In welchem Jahr v. Chr. besiegte Scipio den Hannibal in der Schlacht bei Zama? | 202 | Jahr v. Chr. | 3 | 100 | 400 | Es war im Zweiten Punischen Krieg. ; Rund 15 Jahre nach Hannibals Alpenüberquerung. ; Kurz vor dem Jahr 200 v. Chr. | Mit dem Sieg bei Zama im heutigen Tunesien endete der Zweite Punische Krieg — Karthago musste seine Kriegsflotte fast vollständig abgeben.
O M | Ordne diese griechischen Denker nach ihrem Geburtsjahr — den frühesten zuerst. | Pythagoras = um 570 v. Chr. ; Sokrates = 469 v. Chr. ; Aristoteles = 384 v. Chr. ; Archimedes = um 287 v. Chr. | Der Mann mit dem Satz über rechtwinklige Dreiecke kommt zuerst. ; Dann folgt der Philosoph, der zum Schierlingsbecher verurteilt wurde. ; Der Erfinder aus Syrakus kommt zuletzt. | Aristoteles war Schüler Platons, der wiederum bei Sokrates gelernt hatte — eine der berühmtesten Lehrerketten der Geschichte.
O M | Ordne diese römischen Kaiser nach ihrem Regierungsantritt — den frühesten zuerst. | Augustus = 27 v. Chr. ; Nero = 54 n. Chr. ; Trajan = 98 n. Chr. ; Konstantin der Große = 306 n. Chr. | Der erste Kaiser kommt zuerst. ; Der Kaiser des großen Brandes folgt. ; Der Förderer des Christentums regierte zuletzt. | Konstantin machte 330 das alte Byzanz zur neuen Hauptstadt, die fortan Konstantinopel hieß.
M E | Welche ZWEI dieser Städte lagen im antiken Griechenland? | Sparta ; Korinth | Karthago ; Memphis ; Babylon ; Persepolis | Eine war für ihre harten Krieger berühmt. ; Die andere liegt an einer schmalen Landenge. ; Städte in Nordafrika und im Orient scheiden aus. | Nach Korinth ist der Kanal benannt, der seit 1893 die Landenge zwischen Festland und Peloponnes durchschneidet.

@ mittelalter_ritter
C E | Wie nannte man einen adligen Jungen, der ab etwa sieben Jahren an einem fremden Hof erzogen wurde, bevor er Knappe wurde? | Page | Lakai ; Novize ; Herold | Er diente bei Tisch und lernte gutes Benehmen. ; Er stand auf der ersten Stufe der Ritterausbildung. ; Das Wort lebt heute in einer Frisur weiter. | Mit etwa 14 Jahren wurde aus dem Pagen ein Knappe, mit rund 21 Jahren konnte er zum Ritter werden.
C M | Wie nannte man im Mittelalter Verfahren wie die Feuer- oder Wasserprobe, die über Schuld oder Unschuld entscheiden sollten? | Gottesurteil | Hexenhammer ; Scherbengericht ; Femegericht | Man glaubte, der Himmel selbst zeige die Wahrheit. ; Ein anderes Wort dafür ist Ordal. ; Auch ein gerichtlicher Zweikampf zählte dazu. | Das Vierte Laterankonzil verbot Geistlichen 1215 die Mitwirkung — danach verschwanden die Proben allmählich.
C M | Welcher Wikinger gründete um 985 die erste nordische Siedlung auf Grönland? | Erik der Rote | Harald Blauzahn ; Ragnar Lodbrok ; Knut der Große | Er war zuvor aus Island verbannt worden. ; Sein Sohn Leif erreichte später Amerika. ; Sein Beiname bezieht sich wohl auf seine Haarfarbe. | Den Namen „Grünland“ soll Erik bewusst gewählt haben, um Siedler auf die eisige Insel zu locken.
C H | In welcher südfranzösischen Stadt residierten die Päpste von 1309 bis 1377? | Avignon | Marseille ; Lyon ; Toulouse | Die Stadt liegt an der Rhône. ; Dort steht ein riesiger Papstpalast. ; Ihre berühmte Brücke ist nur noch teilweise erhalten. | Die Zeit ging als „Babylonische Gefangenschaft der Kirche“ in die Geschichte ein.
C U | Wie hieß der bedeutende Wikinger-Handelsplatz bei Schleswig, der heute UNESCO-Welterbe ist? | Haithabu | Birka ; Jorvik ; Kaupang | Er lag an der Schlei. ; Er gehörte zeitweise zum dänischen Reich. ; Auf Dänisch heißt der Ort Hedeby. | Im 9. und 10. Jahrhundert war der Ort einer der wichtigsten Handelsplätze Nordeuropas — seit 2018 ist er zusammen mit dem Danewerk Welterbe.
E E | Welche historische Persönlichkeit ist hier gesucht? | 🦁❤️👑 | Richard Löwenherz | Heinrich der Löwe ; Karl der Große ; Wilhelm der Eroberer | Er war König von England. ; Er zog in den Dritten Kreuzzug. ; Seinen Beinamen verdankte er seinem Mut im Kampf. | Richard verbrachte nur rund ein halbes Jahr seiner zehnjährigen Regierungszeit in England — seine Muttersprache war Französisch.
E E | Welches Volk ist hier gesucht? | 🪓⛵🛡️ | Wikinger | Hunnen ; Mongolen ; Kelten | Sie kamen aus Skandinavien. ; Sie überfielen Klöster an den Küsten Englands. ; Ihre Langschiffe trugen oft geschnitzte Drachenköpfe. | Viele von ihnen waren eher Händler und Bauern als Krieger — ihre Handelswege reichten bis nach Bagdad.
E E | Welche Sagengestalt ist hier gesucht? | 🍎🏹👦 | Wilhelm Tell | Robin Hood ; Arnold Winkelried ; Wilhelm von Oranien | Er ist der Nationalheld der Schweiz. ; Er soll sich dem Vogt Gessler widersetzt haben. ; Er musste einen Apfel vom Kopf seines Sohnes schießen. | Ob Tell je gelebt hat, ist unbelegt — die Überlieferung datiert den Apfelschuss auf das Jahr 1307.
E E | Welches historische Ereignis ist hier gesucht? | ✝️⚔️🐎🏜️ | Die Kreuzzüge | Die Völkerwanderung ; Die Reconquista ; Der Hundertjährige Krieg | Sie begannen Ende des 11. Jahrhunderts. ; Ritter aus ganz Europa zogen ins Heilige Land. ; Papst Urban II. rief 1095 zum ersten auf. | Die Teilnehmer nähten sich ein Stoffkreuz auf die Kleidung — daher stammt der Name.
W M | Ritter in Plattenrüstung mussten mit einem Kran auf ihr Pferd gehoben werden. | falsch | Versuche zeigen, dass geübte Träger einer Plattenrüstung ohne Hilfe aufsteigen und sogar rennen konnten — der Kran ist eine Erfindung aus Filmen.
W M | Schon im Mittelalter gab es Brillen. | wahr | Die ersten Lesebrillen entstanden um 1280 bis 1300 in Norditalien — Mönche und Gelehrte gehörten zu den ersten Trägern.
W H | Kaiser Friedrich Barbarossa ertrank während eines Kreuzzugs in einem Fluss. | wahr | Er starb 1190 auf dem Dritten Kreuzzug im Fluss Saleph in Kleinasien — sein Heer löste sich danach weitgehend auf.
S U | In welchem Jahr plünderten Kreuzfahrer des Vierten Kreuzzugs die christliche Stadt Konstantinopel? | 1204 | Jahr | 5 | 1000 | 1500 | Es war Anfang des 13. Jahrhunderts. ; Venedig war maßgeblich beteiligt. ; Wenige Jahre nach 1200. | Die berühmten Bronzepferde von San Marco in Venedig stammen aus dieser Beute.
S M | In welchem Jahr wurde der Grundstein des Kölner Doms gelegt? | 1248 | Jahr | 5 | 1000 | 1500 | Mitten im 13. Jahrhundert. ; Die Gotik war damals gerade modern. ; Zwischen 1240 und 1260. | Weil der Bau im 16. Jahrhundert stockte, stand jahrhundertelang ein hölzerner Kran auf dem unfertigen Südturm — er wurde zum Wahrzeichen der Stadt.
O M | Ordne diese Schlachten des Mittelalters chronologisch — die früheste zuerst. | Schlacht bei Tours und Poitiers = 732 ; Schlacht auf dem Lechfeld = 955 ; Schlacht bei Hastings = 1066 ; Schlacht bei Crécy = 1346 | Zuerst stoppte ein Frankenherrscher ein arabisches Heer. ; Dann siegte Otto der Große über die Ungarn. ; Die Schlacht der englischen Langbogenschützen kommt zuletzt. | Hastings ist so berühmt, dass in England fast jedes Schulkind die Jahreszahl 1066 kennt.
O U | Ordne diese Herrscherhäuser nach dem Beginn ihrer Königsherrschaft — das früheste zuerst. | Karolinger = 751 ; Ottonen = 919 ; Salier = 1024 ; Staufer = 1138 | Zuerst kam die Familie Karls des Großen. ; Dann folgten die Sachsenherrscher um Otto. ; Barbarossas Familie kommt zuletzt. | Die Staufer sind nach ihrer Stammburg auf dem Hohenstaufen bei Göppingen benannt.
M E | Welche ZWEI dieser Dinge gehörten zur typischen Ausrüstung eines Ritters? | Lanze ; Kettenhemd | Muskete ; Revolver ; Bajonett ; Gasmaske | Eines ist eine lange Stoßwaffe. ; Das andere besteht aus unzähligen Metallringen. ; Feuerwaffen scheiden aus. | Rüstung, Waffen und Streitross waren so teuer, dass sich nur wohlhabende Adlige ein Leben als Ritter leisten konnten.
M H | Welche ZWEI dieser Gemeinschaften waren geistliche Ritterorden? | Johanniter ; Deutscher Orden | Benediktiner ; Franziskaner ; Zisterzienser ; Dominikaner | Einer entstand aus einem Pilgerhospital in Jerusalem. ; Der andere baute im Baltikum einen eigenen Staat auf. ; Reine Mönchsorden scheiden aus. | Aus dem Johanniterorden gingen der heutige Malteserorden und der evangelische Johanniterorden samt Johanniter-Unfall-Hilfe hervor.

@ zwanzigstes_jahrhundert
C E | Wofür steht die Abkürzung UdSSR? | Union der Sozialistischen Sowjetrepubliken | Union der Slawischen Sowjetrepubliken ; Union der Sozialistischen Staaten Russlands ; Union der Sowjetischen Staatsrepubliken | Sie wurde 1922 gegründet und 1991 aufgelöst. ; Ihr Symbol waren Hammer und Sichel. ; Das erste „S“ steht für eine politische Richtung. | Die Sowjetunion bestand zuletzt aus 15 Unionsrepubliken — von Estland bis Tadschikistan.
C E | Welcher Staat wurde 1918 aus den Ländern der Tschechen und Slowaken gegründet? | Tschechoslowakei | Jugoslawien ; Österreich-Ungarn ; Polen | Sein erster Präsident war Tomáš Masaryk. ; Die Hauptstadt war Prag. ; 1993 teilte er sich friedlich in zwei Staaten. | Die friedliche Trennung zum 1. Januar 1993 nennt man auch „Samtene Scheidung“.
C M | Wer rief 1923 die Republik Türkei aus und wurde ihr erster Präsident? | Mustafa Kemal Atatürk | İsmet İnönü ; Enver Pascha ; Recep Tayyip Erdoğan | Er war zuvor Offizier im Osmanischen Reich. ; Er führte die lateinische Schrift in der Türkei ein. ; Sein Beiname bedeutet „Vater der Türken“. | Er machte Ankara zur Hauptstadt und führte 1934 sogar Familiennamen in der Türkei ein.
C H | Welche Hauptstadt war nach 1945 neben Berlin ebenfalls in vier Besatzungssektoren aufgeteilt? | Wien | Prag ; Budapest ; Warschau | Die Stadt liegt an der Donau. ; Der Film „Der dritte Mann“ spielt dort. ; Ihr Land erhielt 1955 mit einem Staatsvertrag die volle Souveränität zurück. | Die Innenstadt verwalteten die vier Mächte gemeinsam — Streifen mit je einem Soldaten jeder Macht hießen „Vier im Jeep“.
C U | Welcher UN-Generalsekretär kam 1961 bei einem Flugzeugabsturz in Afrika ums Leben? | Dag Hammarskjöld | U Thant ; Trygve Lie ; Kurt Waldheim | Er stammte aus Schweden. ; Er war der zweite Generalsekretär der UN. ; Er starb im heutigen Sambia. | Er ist bis heute der einzige Mensch, dem der Friedensnobelpreis nach seinem Tod verliehen wurde.
E E | Welches historische Ereignis ist hier gesucht? | 👨‍🚀🌕👣 | Mondlandung | Mauerfall ; Erster Weltraumflug ; Start von Sputnik | Es geschah im Juli 1969. ; Hunderte Millionen Menschen sahen live im Fernsehen zu. ; Die Mission hieß Apollo 11. | Die Astronauten hinterließen eine Plakette mit der Botschaft, sie seien in Frieden für die ganze Menschheit gekommen.
E E | Welcher historische Konflikt ist hier gesucht? | 🥶⚔️☢️🚀 | Kalter Krieg | Koreakrieg ; Vietnamkrieg ; Krimkrieg | Er dauerte von etwa 1947 bis 1991. ; Zwei Supermächte rüsteten gegeneinander auf. ; Zu einem direkten Kampf zwischen den Hauptgegnern kam es nie. | Populär machte den Begriff der US-Journalist Walter Lippmann 1947 mit seinem Buch „The Cold War“.
E H | Welche Bewegung ist hier gesucht? | 👩🗳️✊🇬🇧 | Suffragetten | Hippies ; Chartisten ; Luddisten | Sie kämpften Anfang des 20. Jahrhunderts. ; Emmeline Pankhurst war ihre bekannteste Anführerin. ; Sie forderten das Wahlrecht für Frauen. | In Großbritannien durften Frauen ab 1918 wählen — gleichberechtigt mit den Männern ab 21 Jahren aber erst ab 1928.
W E | Im Ersten Weltkrieg kamen noch keine Flugzeuge zum Einsatz. | falsch | Flugzeuge dienten schon ab 1914 zur Aufklärung — bald darauf entstanden eigene Jagdflieger-Staffeln.
W M | Beim sogenannten Weihnachtsfrieden 1914 legten Soldaten an Teilen der Westfront spontan die Waffen nieder. | wahr | Britische und deutsche Soldaten sangen gemeinsam Lieder, tauschten kleine Geschenke und spielten mancherorts sogar Fußball.
W M | Michail Gorbatschow war der erste Präsident Russlands. | falsch | Gorbatschow war der erste und einzige Präsident der Sowjetunion — erster Präsident Russlands wurde 1991 Boris Jelzin.
S E | In welchem Jahr gab Großbritannien Hongkong an China zurück? | 1997 | Jahr | 2 | 1950 | 2020 | Ende der 1990er-Jahre. ; Damals lief ein Pachtvertrag über 99 Jahre aus. ; Kurz vor der Jahrtausendwende. | Seitdem gilt der Grundsatz „Ein Land, zwei Systeme“ — Hongkong behielt etwa eigene Gesetze und eine eigene Währung.
S H | In welchem Jahr begann der Koreakrieg? | 1950 | Jahr | 2 | 1930 | 1980 | Wenige Jahre nach dem Zweiten Weltkrieg. ; Er dauerte rund drei Jahre. ; Genau zur Jahrhundertmitte. | Der Krieg endete 1953 nur mit einem Waffenstillstand — einen Friedensvertrag gibt es bis heute nicht.
S M | In welchem Jahr fand die Konferenz von Jalta statt? | 1945 | Jahr | 1 | 1920 | 1970 | Gegen Ende des Zweiten Weltkriegs. ; Sie fand im Februar auf der Krim statt. ; Wenige Monate vor Kriegsende in Europa. | Roosevelt, Churchill und Stalin berieten im Liwadija-Palast über die Nachkriegsordnung — Roosevelt starb nur zwei Monate später.
O U | Ordne diese Staaten nach dem Jahr ihrer Unabhängigkeit — den frühesten zuerst. | Finnland = 1917 ; Indien = 1947 ; Algerien = 1962 ; Namibia = 1990 | Der nordische Staat löste sich von Russland. ; Dann folgte der Subkontinent. ; Das Land im Südwesten Afrikas war zuletzt dran. | Namibia war bis 1915 deutsche Kolonie und wurde danach jahrzehntelang von Südafrika verwaltet.
O M | Ordne diese internationalen Organisationen und Bündnisse nach ihrer Gründung — die früheste zuerst. | Völkerbund = 1920 ; Vereinte Nationen = 1945 ; NATO = 1949 ; Warschauer Pakt = 1955 | Die Vorgängerin der UN kommt zuerst. ; Die Weltorganisation folgt direkt nach dem Zweiten Weltkrieg. ; Das östliche Militärbündnis entstand als Antwort auf das westliche. | Der Warschauer Pakt wurde im Mai 1955 gegründet — wenige Tage nachdem die Bundesrepublik der NATO beigetreten war.
M H | Welche ZWEI dieser Politiker standen an der Spitze der Sowjetunion? | Nikita Chruschtschow ; Leonid Breschnew | Boris Jelzin ; Josip Broz Tito ; Erich Honecker ; Lech Wałęsa | Einer rechnete 1956 in einer Geheimrede mit Stalin ab. ; Der andere regierte rund 18 Jahre bis 1982. ; Staatschefs anderer Länder scheiden aus. | Breschnews lange Amtszeit gilt heute als Ära der Stagnation — erst Gorbatschow versuchte, das System grundlegend zu reformieren.
M M | Welche ZWEI dieser Länder waren im Ersten Weltkrieg Verbündete des Deutschen Reiches? | Österreich-Ungarn ; Osmanisches Reich | Frankreich ; Großbritannien ; Russland ; Italien | Eines war ein Vielvölkerstaat mit der Hauptstadt Wien. ; Das andere herrschte vom Bosporus aus. ; Auch Bulgarien gehörte zu diesem Bündnis. | Italien war vor dem Krieg zwar mit Deutschland verbündet, trat 1915 aber auf der Seite der Gegner in den Krieg ein.

@ deutsche_geschichte de
C E | Wie hieß das Herrscherhaus der preußischen Könige und der deutschen Kaiser ab 1871? | Hohenzollern | Habsburger ; Wittelsbacher ; Welfen | Seine Stammburg steht auf der Schwäbischen Alb. ; Auch Friedrich der Große gehörte dazu. ; Der Name steckt in einer Burg bei Hechingen. | Ursprünglich war die Familie ein schwäbisches Grafengeschlecht — Kurfürsten von Brandenburg wurde sie erst 1415.
C M | Welche ehemalige Nonne heiratete Martin Luther im Jahr 1525? | Katharina von Bora | Katharina von Siena ; Elisabeth von Thüringen ; Hildegard von Bingen | Sie war aus einem Kloster geflohen. ; Luther nannte sie liebevoll „Herr Käthe“. ; Das Paar hatte sechs Kinder. | Ihre Flucht aus dem Kloster Nimbschen gelang 1523 angeblich versteckt zwischen Heringsfässern.
C H | Welcher Humanist und enge Mitstreiter Luthers wurde „Lehrer Deutschlands“ genannt? | Philipp Melanchthon | Ulrich Zwingli ; Erasmus von Rotterdam ; Johannes Calvin | Er lehrte in Wittenberg Griechisch. ; Er verfasste 1530 das Augsburger Bekenntnis. ; Sein Nachname ist eine griechische Übersetzung von „Schwarzerdt“. | Wegen seiner Verdienste um Schulen und Universitäten nannte man ihn lateinisch „Praeceptor Germaniae“.
C U | Welcher Kaiser legte 1806 die Krone des Heiligen Römischen Reiches nieder? | Franz II. | Joseph II. ; Leopold II. ; Karl VI. | Er stammte aus dem Haus Habsburg. ; Er hatte sich schon 1804 zum Kaiser von Österreich erklärt. ; Unter dem Druck Napoleons beendete er das über 800 Jahre alte Reich. | Als Kaiser von Österreich regierte er unter anderer Nummer weiter — deshalb nennt man ihn auch den „Doppelkaiser“.
C E | Welcher Bundeskanzler folgte 1974 auf Willy Brandt? | Helmut Schmidt | Helmut Kohl ; Hans-Dietrich Genscher ; Hans-Jochen Vogel | Er war zuvor Verteidigungs- und Finanzminister. ; Er stammte aus Hamburg. ; Er war für seine Mentholzigaretten bekannt. | Schon 1962 hatte er sich als Hamburger Polizeisenator bei der großen Sturmflut einen Namen als Krisenmanager gemacht.
E M | Welche Persönlichkeit ist hier gesucht? | 🪖👞🏛️💰 | Hauptmann von Köpenick | Der Rote Baron ; Baron Münchhausen ; Schinderhannes | Er war eigentlich ein arbeitsloser Schuster. ; 1906 besetzte er in falscher Uniform ein Rathaus bei Berlin. ; Er ließ sich die Stadtkasse aushändigen. | Wilhelm Voigt machte das Kaiserreich weltweit lächerlich — sogar Kaiser Wilhelm II. soll über den Streich gelacht haben.
E E | Welches historische Ereignis ist hier gesucht? | 3️⃣0️⃣📅⚔️ | Dreißigjähriger Krieg | Siebenjähriger Krieg ; Hundertjähriger Krieg ; Deutsch-Französischer Krieg | Er begann 1618. ; Er wütete vor allem auf deutschem Boden. ; Er endete mit dem Westfälischen Frieden. | Weite Teile Deutschlands verloren im Krieg ein Drittel oder mehr ihrer Bevölkerung — manche Regionen erholten sich erst nach Generationen.
E E | Welcher Begriff der Nachkriegsgeschichte ist hier gesucht? | ✈️🍫🍇 | Rosinenbomber | Zeppelin ; Tante Ju ; Concorde | Er gehört zur Berlin-Blockade 1948/49. ; Piloten warfen Süßigkeiten an kleinen Fallschirmen ab. ; So nannten die Berliner die Versorgungsflugzeuge der Alliierten. | Die Süßigkeiten-Abwürfe begann der US-Pilot Gail Halvorsen — die Kinder nannten ihn „Onkel Wackelflügel“.
W H | Konrad Adenauer war bei seiner Wahl zum ersten Bundeskanzler jünger als 60 Jahre. | falsch | Adenauer war bei seiner Wahl 1949 bereits 73 Jahre alt — und blieb danach noch 14 Jahre im Amt.
W U | Der Bayerische Landtag lehnte das Grundgesetz 1949 ab. | wahr | Bayern hielt das Grundgesetz für zu wenig föderal — erkannte aber zugleich an, dass es auch in Bayern gelten würde.
W M | Napoleon ließ die Quadriga vom Brandenburger Tor nach Paris bringen. | wahr | 1806 wurde die Figurengruppe als Kriegsbeute nach Paris gebracht — 1814 kehrte sie im Triumph nach Berlin zurück.
S M | In welchem Jahr hielt der Bundestag seine erste Sitzung im umgebauten Reichstagsgebäude in Berlin ab? | 1999 | Jahr | 2 | 1980 | 2015 | Ende der 1990er-Jahre. ; Einige Jahre nach der Verhüllung durch Christo. ; Kurz vor der Jahrtausendwende. | Zuvor tagte das Parlament in Bonn — den Umzug nach Berlin hatte der Bundestag 1991 nur knapp beschlossen.
S H | In welchem Jahr trat das Bürgerliche Gesetzbuch (BGB) in Kraft? | 1900 | Jahr | 3 | 1850 | 1950 | Es war zur Zeit des Kaiserreichs. ; Um die Jahrhundertwende. ; Am 1. Januar eines runden Jahres. | Mit dem BGB galt erstmals im ganzen Deutschen Reich ein einheitliches Zivilrecht — viele seiner Paragrafen gelten bis heute.
S M | In welchem Jahr wurde das Brandenburger Tor fertiggestellt? | 1791 | Jahr | 5 | 1600 | 1900 | Im späten 18. Jahrhundert. ; Wenige Jahre nach dem Tod Friedrichs des Großen. ; Zwei Jahre nach Beginn der Französischen Revolution. | Architekt Carl Gotthard Langhans nahm sich die Propyläen der Athener Akropolis zum Vorbild.
O M | Ordne diese Ereignisse des 19. Jahrhunderts chronologisch — das früheste zuerst. | Ende des Heiligen Römischen Reiches = 1806 ; Völkerschlacht bei Leipzig = 1813 ; Deutscher Zollverein tritt in Kraft = 1834 ; Frankfurter Nationalversammlung = 1848 | Zuerst legte der letzte römisch-deutsche Kaiser die Krone nieder. ; Dann wurde Napoleon entscheidend geschlagen. ; Das erste gesamtdeutsche Parlament kommt zuletzt. | Der Zollverein gilt als wirtschaftlicher Vorläufer der deutschen Einheit von 1871.
O H | Ordne diese Preußenkönige nach ihrem Regierungsantritt — den frühesten zuerst. | Friedrich I. = 1701 ; Friedrich Wilhelm I. = 1713 ; Friedrich II. = 1740 ; Friedrich Wilhelm II. = 1786 | Der erste König krönte sich selbst in Königsberg. ; Dann folgte der sparsame Soldatenkönig. ; Der Neffe des Alten Fritz kommt zuletzt. | Friedrich II. regierte 46 Jahre lang — keiner seiner Nachfolger saß länger auf dem preußischen Thron.
M E | Welche ZWEI dieser Politiker waren Bundeskanzler der Bundesrepublik? | Kurt Georg Kiesinger ; Gerhard Schröder | Franz Josef Strauß ; Hans-Dietrich Genscher ; Johannes Rau ; Rainer Barzel | Einer führte ab 1966 die erste Große Koalition. ; Der andere regierte von 1998 bis 2005. ; Kanzlerkandidaten, Minister und Bundespräsidenten scheiden aus. | Rainer Barzel scheiterte 1972 mit dem ersten konstruktiven Misstrauensvotum der Bundesrepublik um nur zwei Stimmen.
M U | Welche ZWEI dieser Kaiser stammten aus dem Geschlecht der Staufer? | Friedrich I. Barbarossa ; Friedrich II. | Otto der Große ; Heinrich IV. ; Karl IV. ; Maximilian I. | Einer trug einen rötlichen Bart. ; Der andere residierte am liebsten in Sizilien. ; Ottonen, Salier, Luxemburger und Habsburger scheiden aus. | Friedrich II. war der Enkel Barbarossas und wuchs in Palermo auf.

@ ddr_wiedervereinigung de
C E | Welcher Ruf der Leipziger Montagsdemonstranten wurde im Herbst 1989 zum Motto der friedlichen Revolution? | „Wir sind das Volk!“ | „Wir sind die Zukunft!“ ; „Frieden und Brot!“ ; „Freiheit ohne Grenzen!“ | Die Demonstranten wandten sich damit an die Staatsführung. ; Später wurde daraus ein Ruf nach Einheit. ; Aus einem Artikel wurde dabei „ein“. | Ab Ende 1989 hieß es immer häufiger „Wir sind ein Volk!“ — Ausdruck des Wunsches nach Wiedervereinigung.
C E | Welche Stadt war die Hauptstadt der DDR? | Ost-Berlin | Leipzig ; Dresden ; Potsdam | Dort stand der Palast der Republik. ; Die Stadt war durch eine Mauer geteilt. ; Der Fernsehturm am Alexanderplatz steht dort. | Die Westmächte erkannten sie nie offiziell als Hauptstadt an, weil für ganz Berlin der Viermächte-Status galt.
C M | Welcher Liedermacher wurde 1976 nach einem Konzert in Köln aus der DDR ausgebürgert? | Wolf Biermann | Reinhard Mey ; Hannes Wader ; Konstantin Wecker | Er war ein scharfer Kritiker der SED. ; Er sang politische Lieder zur Gitarre. ; Er war 1953 als junger Kommunist aus Hamburg in die DDR übergesiedelt. | Gegen seine Ausbürgerung protestierten zahlreiche DDR-Künstler — viele verließen danach selbst das Land.
C M | Wer löste Erich Honecker im Oktober 1989 als SED-Generalsekretär ab? | Egon Krenz | Hans Modrow ; Günter Schabowski ; Willi Stoph | Er war zuvor im Politbüro für Sicherheitsfragen zuständig. ; Er galt lange als Honeckers Kronprinz. ; Er blieb nur rund sieben Wochen im Amt. | Bei seinem Amtsantritt kündigte er eine „Wende“ an — das Wort wurde zum Namen der ganzen Umbruchzeit.
C H | Welche Bürgerrechtsbewegung wurde im September 1989 unter anderem von Bärbel Bohley gegründet? | Neues Forum | Demokratie Jetzt ; Charta 77 ; Solidarność | Sie war die bekannteste Oppositionsgruppe der Wendezeit. ; Ihr Gründungsaufruf hieß „Aufbruch 89“. ; Der Name erinnert an einen Versammlungsplatz im alten Rom. | Obwohl die Behörden die Zulassung zunächst ablehnten, unterschrieben binnen Wochen Zehntausende den Gründungsaufruf.
C U | Wer war nach Egon Krenz der letzte Staatsratsvorsitzende der DDR? | Manfred Gerlach | Hans Modrow ; Lothar de Maizière ; Sabine Bergmann-Pohl | Er gehörte nicht der SED, sondern der LDPD an. ; Er übernahm das Amt im Dezember 1989. ; Er amtierte bis zur Abschaffung des Staatsrats im April 1990. | Danach nahm Volkskammerpräsidentin Sabine Bergmann-Pohl die Aufgaben des Staatsoberhaupts wahr.
E E | Welches historische Ereignis ist hier gesucht? | 🧱🔨🎉 | Mauerfall | Mauerbau ; Luftbrücke ; Volksaufstand | Es geschah im Herbst 1989. ; Menschen tanzten in Berlin auf einem Bauwerk. ; Plötzlich durften DDR-Bürger frei in den Westen reisen. | In der Nacht zum 10. November feierten Ost- und West-Berliner gemeinsam — viele kletterten am Brandenburger Tor sogar auf die Mauer.
E M | Welche Verkehrsregel aus der DDR ist hier gesucht? | 🟢➡️🚦 | Grüner Pfeil | Kreisverkehr ; Zebrastreifen ; Tempo 30 | Sie gilt nur an manchen Ampeln. ; Man darf trotz Rot nach rechts abbiegen. ; Vorher muss man trotzdem anhalten. | Das Blechschild durfte nach der Wende bleiben — seit 1994 ist es sogar in ganz Deutschland erlaubt.
E H | Welches Gremium der Wendezeit ist hier gesucht? | ⭕🪑🪑🗣️ | Runder Tisch | Politbüro ; Staatsrat ; Volkskammer | Es tagte ab Dezember 1989 in Ost-Berlin. ; Regierung und Opposition saßen gleichberechtigt beisammen. ; Es erarbeitete sogar einen Verfassungsentwurf. | Das Vorbild stammte aus Polen, wo Regierung und Solidarność schon Anfang 1989 auf diese Weise verhandelt hatten.
W E | Die DDR gehörte dem Warschauer Pakt an. | wahr | Die DDR war 1955 Gründungsmitglied — ihre Nationale Volksarmee wurde ein Jahr später aufgestellt.
W H | In der DDR wurde die allgemeine Wehrpflicht erst nach dem Mauerbau eingeführt. | wahr | Die Wehrpflicht kam im Januar 1962 — vorher hätten sich viele junge Männer ihr durch Flucht in den Westen entziehen können.
W U | Erich Honecker starb in Deutschland. | falsch | Honecker durfte 1993 aus gesundheitlichen Gründen ausreisen und starb 1994 im chilenischen Exil in Santiago.
S H log | Wie viele Menschen demonstrierten am 9. Oktober 1989 in Leipzig ungefähr? | 70000 | Menschen | 25 | 1000 | 1000000 | Mehr als 10.000. ; Weniger als 200.000. ; Mehrere Zehntausend. | Obwohl Sicherheitskräfte bereitstanden, blieb es friedlich — der Tag gilt als Wendepunkt der friedlichen Revolution.
S M | In welchem Jahr wurde der Berliner Fernsehturm eröffnet? | 1969 | Jahr | 2 | 1950 | 1990 | Ende der 1960er-Jahre. ; Pünktlich zum 20. Jahrestag der DDR. ; Im Jahr der ersten Mondlandung. | Scheint die Sonne auf die Kugel, erscheint ein Lichtkreuz — die Berliner tauften es spöttisch „Rache des Papstes“.
O H | Ordne diese Wegmarken des Wendejahres 1989 chronologisch — die früheste zuerst. | Paneuropäisches Picknick an der ungarischen Grenze = 19. August 1989 ; Genscher verkündet in Prag die Ausreise = 30. September 1989 ; Rücktritt Erich Honeckers = 18. Oktober 1989 ; Großdemonstration auf dem Alexanderplatz = 4. November 1989 | Das Ereignis im Sommer kommt zuerst. ; Dann sprach ein Außenminister von einem Botschaftsbalkon. ; Die Kundgebung in Ost-Berlin kommt zuletzt. | Zur Kundgebung am Alexanderplatz kamen Hunderttausende — es war die größte nicht staatlich gelenkte Demonstration der DDR.
M E | Welche ZWEI dieser Bundesländer gehören zu den „neuen Ländern“, die 1990 der Bundesrepublik beitraten? | Thüringen ; Mecklenburg-Vorpommern | Hessen ; Saarland ; Bayern ; Schleswig-Holstein | Eines hat Erfurt als Hauptstadt. ; Das andere liegt an der Ostsee. ; Die übrigen gehörten alle zur alten Bundesrepublik. | Die DDR hatte ihre Länder 1952 durch Bezirke ersetzt — erst 1990 wurden die fünf Länder wiedergegründet.
M U | Welche ZWEI dieser Politiker führten als Vorsitzende des Ministerrats die Regierung der DDR? | Willi Stoph ; Hans Modrow | Egon Bahr ; Hans-Dietrich Genscher ; Wolfgang Schäuble ; Oskar Lafontaine | Einer war insgesamt über zwei Jahrzehnte Regierungschef. ; Der andere übernahm das Amt im November 1989. ; Die übrigen waren westdeutsche Politiker. | Stoph traf sich 1970 in Erfurt und Kassel mit Willy Brandt — es waren die ersten deutsch-deutschen Gipfeltreffen.

@ persoenlichkeiten_entdecker
C H | Welcher portugiesische Seefahrer nahm im Jahr 1500 Brasilien für Portugal in Besitz? | Pedro Álvares Cabral | Vasco da Gama ; Bartolomeu Diaz ; Ferdinand Magellan | Er war eigentlich auf dem Weg nach Indien. ; Seine Flotte segelte dabei weit nach Westen hinaus. ; Sein Vorname lautet Pedro. | Deshalb spricht man in Brasilien bis heute Portugiesisch — als einzigem Land Südamerikas.
C M | Welcher portugiesische Prinz förderte im 15. Jahrhundert die Entdeckungsfahrten entlang der Küste Afrikas, obwohl er selbst kaum zur See fuhr? | Heinrich der Seefahrer | Manuel I. ; Johann II. ; Alfons V. | Sein Beiname passt eigentlich gar nicht zu ihm. ; Er lebte von 1394 bis 1460. ; Er war ein Sohn König Johanns I. | Seinen berühmten Beinamen erhielt er erst im 19. Jahrhundert von deutschen und englischen Historikern.
C U | Welcher US-Amerikaner leitete 1929 den ersten Flug über den Südpol? | Richard E. Byrd | Charles Lindbergh ; Lincoln Ellsworth ; Robert Peary | Er war Marineoffizier. ; Seine Basis in der Antarktis hieß „Little America“. ; Pilot des Flugs war der Norweger Bernt Balchen. | Schon 1926 hatte er behauptet, den Nordpol überflogen zu haben — daran gibt es bis heute große Zweifel.
C H | Welcher Schweizer Physiker stieg 1931 mit einem Ballon und einer Druckkabine in die Stratosphäre auf? | Auguste Piccard | Jacques Piccard ; Bertrand Piccard ; Ferdinand von Zeppelin | Er startete in Augsburg. ; Seine Kabine war eine Kugel aus Aluminium. ; Er war das Vorbild für Professor Bienlein in „Tim und Struppi“. | Er erreichte fast 16 Kilometer Höhe — später konstruierte er auch Tiefseetauchboote, darunter die Trieste.
C E | Welche englische Königin regierte von 1558 bis 1603 und blieb zeitlebens unverheiratet? | Elisabeth I. | Maria Stuart ; Victoria ; Anne Boleyn | Ihr Vater war Heinrich VIII. ; In ihrer Zeit wirkte William Shakespeare. ; Unter ihr besiegte England 1588 die spanische Armada. | Man nannte sie die „jungfräuliche Königin“ — der US-Bundesstaat Virginia ist nach ihr benannt.
E E | Welcher Entdecker ist hier gesucht? | 🥚⛵🌎 | Christoph Kolumbus | Marco Polo ; Vasco da Gama ; James Cook | Er segelte im Auftrag Spaniens. ; Er glaubte, Indien erreicht zu haben. ; Nach ihm ist ein berühmtes Ei benannt. | Der Legende nach brachte er ein Ei zum Stehen, indem er die Spitze eindrückte — seitdem steht das „Ei des Kolumbus“ für eine verblüffend einfache Lösung.
E E | Welcher Reisende ist hier gesucht? | 🇮🇹🐫🇨🇳📖 | Marco Polo | Christoph Kolumbus ; Ibn Battuta ; Zheng He | Er stammte aus Venedig. ; Er reiste im 13. Jahrhundert nach China. ; Seinen Reisebericht diktierte er im Gefängnis. | Aufgeschrieben hat den Bericht sein Mitgefangener Rustichello da Pisa, während beide in Genua in Kriegsgefangenschaft saßen.
E H | Welcher Meeresforscher ist hier gesucht? | 🌊🤿🚢🇫🇷 | Jacques-Yves Cousteau | Hans Hass ; Thor Heyerdahl ; Jacques Piccard | Er war Franzose. ; Sein Forschungsschiff hieß Calypso. ; In den 1940er-Jahren entwickelte er das moderne Tauchgerät mit. | Sein Film „Die schweigende Welt“ brachte Millionen Menschen die Unterwasserwelt nahe und gewann 1956 die Goldene Palme in Cannes.
W H | James Cook war der erste Europäer, der Australien betrat. | falsch | Schon 1606 landete der Niederländer Willem Janszoon an der Nordküste — Cook erreichte 1770 als erster Europäer die Ostküste.
W U | Roald Amundsen überflog 1926 mit einem Luftschiff den Nordpol. | wahr | Mit dem Luftschiff „Norge“ gelang ihm zusammen mit Umberto Nobile und Lincoln Ellsworth die erste nachgewiesene Überquerung des Nordpols.
W M | Marco Polo brachte die Nudeln aus China nach Italien. | falsch | Nudelgerichte gab es in Italien schon vor seiner Rückkehr 1295 — die Legende stammt wohl aus einer US-Branchenzeitschrift der 1920er-Jahre.
S M | In welchem Jahr krönte sich Napoleon Bonaparte zum Kaiser der Franzosen? | 1804 | Jahr | 2 | 1750 | 1850 | Anfang des 19. Jahrhunderts. ; Die Zeremonie fand in Notre-Dame statt. ; Zwei Jahre vor seinem Sieg bei Jena und Auerstedt. | Den Papst hatte er eigens nach Paris geholt — die Krone setzte er sich dann aber selbst auf.
S M | Wie viele Kinder brachte Kaiserin Maria Theresia zur Welt? | 16 | Kinder | 15 | 1 | 30 | Mehr als zehn. ; Weniger als 20. ; Darunter war die spätere französische Königin Marie Antoinette. | Trotz der vielen Schwangerschaften regierte sie 40 Jahre lang ein riesiges Reich — die Ehen ihrer Kinder nutzte sie geschickt für ihre Politik.
O E | Ordne diese Flugpioniere nach ihrer berühmtesten Leistung — die früheste zuerst. | Otto Lilienthal: erste Gleitflüge = 1891 ; Brüder Wright: erster Motorflug = 1903 ; Louis Blériot: Flug über den Ärmelkanal = 1909 ; Charles Lindbergh: Atlantik-Alleinflug = 1927 | Ein deutscher Ingenieur mit Gleitern kommt zuerst. ; Dann folgen zwei Brüder aus den USA. ; Der Atlantikflug nach Paris kommt zuletzt. | Lilienthal gilt als erster Mensch, der wiederholt und nachweisbar mit einem Gleitflugzeug flog — die Wrights studierten seine Arbeiten genau.
O H | Ordne diese Freiheitskämpfer nach ihrem Geburtsjahr — den frühesten zuerst. | George Washington = 1732 ; Simón Bolívar = 1783 ; Giuseppe Garibaldi = 1807 ; Mahatma Gandhi = 1869 | Der erste US-Präsident kommt zuerst. ; Dann folgt der Befreier Südamerikas. ; Der Inder kommt zuletzt. | Bolívar führte gleich sechs heutige Staaten in die Unabhängigkeit: Venezuela, Kolumbien, Ecuador, Peru, Panama und Bolivien.
M M | Welche ZWEI dieser Entdecker stammten aus Portugal? | Vasco da Gama ; Ferdinand Magellan | Christoph Kolumbus ; James Cook ; Amerigo Vespucci ; Abel Tasman | Einer fand den Seeweg nach Indien. ; Der andere segelte später im Dienst Spaniens. ; Italiener, Briten und Niederländer scheiden aus. | Magellan hieß auf Portugiesisch Fernão de Magalhães — weil sein König ihn abwies, bot er seine Dienste Spanien an.
M E | Welche ZWEI dieser Männer waren Präsidenten der USA? | Thomas Jefferson ; Theodore Roosevelt | Benjamin Franklin ; Alexander Hamilton ; Henry Ford ; Martin Luther King | Einer schrieb die Unabhängigkeitserklärung. ; Nach dem anderen ist der Teddybär benannt. ; Wer auf einem Dollarschein abgebildet ist, war nicht automatisch Präsident. | Franklin (100-Dollar-Schein) und Hamilton (10-Dollar-Schein) gehören zu den Gründervätern, wurden aber nie Präsident.
"""
