"""Extra questions, wave 2: Internet & Memes (format: see tools/content/merge_extra.py)."""
KAT = "internet_memes"
REGION = "global"
DATA = r"""
@ meme_klassiker
E E | Welches Meme ist hier gesucht? | 🐱🌈🎶 | Nyan Cat | Keyboard Cat ; Grumpy Cat ; Pusheen | Es ist eine animierte Pixel-Grafik. ; Die Figur fliegt durchs Weltall. ; Ihr Körper sieht aus wie ein Gebäckstück. | Die Pixel-Katze von Chris Torres flog 2011 zu einem japanischen Popsong in Endlosschleife durchs All.
E M | Welches Meme ist hier gesucht? | 🐶🔥☕ | This is fine | Doge ; Keep calm and carry on ; Everything is awesome | Ein Comic-Hund sitzt mit Hut am Tisch. ; Um ihn herum brennt das Zimmer. ; Er bleibt trotzdem völlig gelassen. | Der Comic von KC Green ist heute das Symbol für gespielte Gelassenheit mitten im Chaos.
E M | Welcher Internet-Streich ist hier gesucht? | 🔗🕺🎤 | Rickroll | Trollface ; Clickbait ; Phishing | Man klickt auf einen harmlos wirkenden Link. ; Stattdessen läuft ein Musikvideo aus den 1980ern. ; Der Sänger verspricht, einen niemals aufzugeben. | Beim Rickroll landet man überraschend bei Rick Astleys „Never Gonna Give You Up“.
E E | Welches Meme ist hier gesucht? | ⚰️🕺🎶 | Coffin Dance | Harlem Shake ; Thriller-Tanz ; Macarena | Es wurde zum Symbol für spektakuläre Fails. ; Männer in Anzügen tanzen mit einem Sarg auf den Schultern. ; Die Tänzer stammen aus Ghana. | Die ghanaischen Sargträger um Benjamin Aidoo bieten tanzende Beerdigungen als fröhlichen Abschied an.
C E | Welches Pokémon zeigt das Meme für gespielte Überraschung mit weit offenem Mund? | Pikachu | Evoli ; Pummeluff ; Mauzi | Es ist gelb. ; Es hat rote Backen. ; Es ist das Maskottchen der Pokémon-Reihe. | Das „Surprised Pikachu“-Bild stammt aus dem Anime — es passt, wenn jemand von vorhersehbaren Folgen „überrascht“ ist.
C E | Was machen die beiden Spider-Men im bekannten Meme aus einer Zeichentrickserie? | Sie zeigen aufeinander | Sie klatschen sich ab ; Sie kämpfen miteinander ; Sie schwingen gemeinsam an einem Netz | Beide sehen völlig gleich aus. ; Es geht um eine Verwechslung. ; Man nutzt es, wenn sich zwei Dinge gleichen. | Das Bild passt, wenn zwei Menschen einander verblüffend ähneln — oder sich gegenseitig die Schuld geben.
C M | Welcher Raumschiff-Captain schlägt im bekannten „Facepalm“-Meme die Hand vors Gesicht? | Jean-Luc Picard | James T. Kirk ; Kathryn Janeway ; Benjamin Sisko | Er stammt aus „Star Trek: The Next Generation“. ; Er ist Franzose. ; Gespielt wird er von Patrick Stewart. | Der „Picard Facepalm“ steht für Fassungslosigkeit angesichts großer Dummheit.
C M | Aus welchem Film stammt das Meme, in dem Leonardo DiCaprio lächelnd mit einem Champagnerglas zuprostet? | Der große Gatsby | Titanic ; The Wolf of Wall Street ; Catch Me If You Can | Der Film kam 2013 ins Kino. ; Er spielt in den 1920er-Jahren. ; Die Romanvorlage schrieb F. Scott Fitzgerald. | DiCaprio spielt den geheimnisvollen Millionär Jay Gatsby — der Toast bedeutet im Netz „Gut gemacht!“.
C U | Welcher Fernsehmoderator mit wild abstehender Frisur wurde als „Ancient Aliens“-Meme berühmt? | Giorgio A. Tsoukalos | Erich von Däniken ; Graham Hancock ; David Childress | Er tritt in einer Doku-Reihe des History Channel auf. ; Unter seinem Bild steht meist nur „Aliens“. ; Er ist Schweizer mit griechischen Wurzeln. | Tsoukalos erklärt rätselhafte Bauwerke gern mit Besuchern aus dem All — daher das Meme.
C U | Aus welchem Land stammt die Telenovela, aus der das Meme „Confused Math Lady“ stammt? | Brasilien | Mexiko ; Argentinien ; Portugal | Die Serie lief 2004 im Fernsehen. ; Die Schauspielerin heißt Renata Sorrah. ; Die Serie hieß „Senhora do Destino“. | Über das Gesicht der verwirrten Frau legte das Netz Matheformeln — heute Symbol für angestrengtes Grübeln.
W H | Im Meme „But that's none of my business“ trinkt Kermit der Frosch Kaffee. | falsch | Kermit nippt an einem Tee — das Bild stammt aus einem Werbespot für Lipton-Eistee von 2014.
W E | Das Meme „Big Chungus“ zeigt Daffy Duck. | falsch | „Big Chungus“ ist ein dicker Bugs Bunny aus dem Cartoon „Wabbit Twouble“ von 1941.
W H | Die Musik unter dem „Coffin Dance“-Meme ist der Track „Astronomia“. | wahr | Das Stück „Astronomia“ von Tony Igy, im Remix von Vicetone, wurde 2020 zur Hymne der tanzenden Sargträger.
W M | Das Meme „Gru's Plan“ stammt aus dem Film „Ich – Einfach unverbesserlich“. | wahr | Gru präsentiert auf einem Flipchart seinen Plan — im letzten Bild merkt er erschrocken, dass etwas nicht aufgeht.
S U | Aus welchem Jahr stammt die Zeichentrickserie, aus der das Meme „Spider-Man zeigt auf Spider-Man“ kommt? | 1967 | Jahr | 3 | 1950 | 2010 | Lange vor den Kinofilmen. ; In den 1960er-Jahren. ; Zwei Jahre vor der Mondlandung. | Die Szene stammt aus der Folge „Double Identity“ der ersten „Spider-Man“-Zeichentrickserie.
S H | In welchem Jahr hielt Michael Jordan die tränenreiche Rede zur Aufnahme in die Hall of Fame, aus der das Meme „Crying Jordan“ stammt? | 2009 | Jahr | 2 | 1990 | 2020 | Nach seinem Karriereende. ; In den 2000er-Jahren. ; Im selben Jahr wurde Barack Obama US-Präsident. | Das Foto seines weinenden Gesichts wurde in den 2010ern zum Symbol für jede Niederlage.
S H | Wie viele Jahre alt wurde die Shiba-Inu-Hündin Kabosu, das Gesicht des „Doge“-Memes? | 18 | Jahre | 20 | 5 | 30 | Älter, als Hunde meist werden. ; Sie starb im Mai 2024. ; Sie wurde volljährig. | Kabosu stammte aus einem Tierheim in Japan — ihr Gesicht zierte auch die Kryptowährung Dogecoin.
S U | Wie viele Monate alt war Sammy Griner auf dem Strandfoto, das ihn als „Success Kid“ berühmt machte? | 11 | Monate | 20 | 1 | 60 | Er war noch ein Baby. ; Jünger als zwei Jahre. ; Knapp ein Jahr. | Seine Mutter fotografierte ihn 2007 mit einer Faust voller Sand — das Netz deutete die Geste als Siegerpose.
O U | Sortiere diese Meme-Vorlagen nach dem Entstehungsjahr ihres Originalbilds — das älteste zuerst. | Picard Facepalm = 1990 ; Success Kid = 2007 ; DiCaprio-Toast (Der große Gatsby) = 2013 ; Distracted Boyfriend = 2015 | Die Star-Trek-Szene ist am ältesten. ; Das Babyfoto folgt. ; Das Stockfoto ist das jüngste. | Viele Meme-Vorlagen sind viel älter als das Meme selbst — Picards Facepalm stammt aus der Folge „Déjà Q“.
O M | Sortiere diese Memes nach dem Jahr ihres Durchbruchs — das früheste zuerst. | Hampster Dance = 1998 ; Dat Boi = 2016 ; Big Chungus = 2018 ; Coffin Dance = 2020 | Die tanzenden Nager gab es schon im Web der 90er. ; Der Frosch auf dem Einrad folgt. ; Die Sargträger sind am jüngsten. | Die „Hampster Dance“-Seite von 1998 gilt als eines der ersten viralen Phänomene überhaupt.
M E | Welche DREI dieser Memes zeigen eine echte Katze? | Grumpy Cat ; Keyboard Cat ; Smudge the Cat | Doge ; Success Kid ; Bad Luck Brian | Eine schaut immer mürrisch. ; Eine spielt Keyboard. ; Eine sitzt vor einem Salatteller am Esstisch. | Smudge ist die weiße Katze aus dem Meme „Woman Yelling at a Cat“.
M E | Welche DREI dieser Meme-Figuren sind Frösche? | Pepe ; Kermit ; Dat Boi | Doge ; Big Chungus ; Nyan Cat | Einer stammt aus dem Comic „Boy's Club“. ; Einer ist ein Muppet. ; Einer fährt Einrad. | Dat Boi stammt aus einer alten Clip-Art-Animation und wurde 2016 mit „Here come dat boi!“ viral.
M H | Welche DREI dieser Memes stammen aus Filmen oder Serien? | One does not simply walk into Mordor ; Winter is coming ; Hello there | Distracted Boyfriend ; Success Kid ; Disaster Girl | Einer stammt aus Mittelerde. ; Einer aus Westeros. ; Einer aus „Star Wars“. | Boromir sagt den Mordor-Satz, Ned Stark warnt vor dem Winter und Obi-Wan grüßt in „Episode III“.

@ deutsche_internet_kultur de
E E | Welcher Partyklassiker ist hier gesucht? | 🥩🦔 | Mettigel | Käseigel ; Frikadellenberg ; Schinkenröllchen | Er stand auf Partybuffets der 1970er. ; Seine Stacheln sind Zwiebelstücke. ; Er besteht aus rohem Hackfleisch. | Im Netz ist der Mettigel Kult — Fans teilen Fotos kunstvoller Varianten bis hin zu Mett-Drachen.
E M | Welche Kultfigur ist hier gesucht? | 🍞😒📺 | Bernd das Brot | Chili das Schaf ; Briegel der Busch ; Das Sandmännchen | Er ist eine Puppe aus dem Kinderfernsehen. ; Er hat fast immer schlechte Laune. ; Nachts lief er im KiKA in Endlosschleife. | Die nächtlichen Bernd-Schleifen im KiKA wurden in den 2000ern zum Kult — besonders bei Studenten.
E E | Welcher Netz-Hit ist hier gesucht? | 🐊🎶👶 | Schnappi, das kleine Krokodil | Die Biene Maja ; Das kleine Nilpferd ; Kroko der Kleine | Das Lied stürmte Mitte der 2000er die Charts. ; Gesungen hat es ein kleines Mädchen. ; Die Titelfigur beißt gern zu. | „Schnappi“ wurde erst im Netz populär und erreichte dann Platz 1 der deutschen Charts.
E M | Welches Jugendwort ist hier gesucht? | 🧟📱🚶 | Smombie | Selfie ; Onlinegeist ; Couchpotato | Gemeint sind Menschen im Straßenverkehr. ; Sie starren nur aufs Handy. ; Es ist ein Kofferwort aus zwei englischen Wörtern. | Für Smombies testete Augsburg 2016 sogar Ampel-Lichter im Boden an Straßenbahnhaltestellen.
C E | Was bedeutet die Chat-Abkürzung „gn8“? | Gute Nacht | Gib nach ; Genug ; Geht nicht | Die Zahl wird ausgesprochen. ; Man schreibt es spät am Abend. ; „Acht“ steckt im gesuchten Wort. | Solche Zahlen-Kürzel stammen aus der SMS-Zeit, als jede Nachricht nur 160 Zeichen hatte.
C E | Welcher Wochentag heißt im deutschen Netz-Humor „Mettwoch“? | Mittwoch | Montag ; Freitag ; Sonntag | Er liegt in der Wochenmitte. ; Der Name klingt fast gleich. ; Nur ein Buchstabe ist ausgetauscht. | Am „Mettwoch“ posten Fans Fotos von Mettbrötchen — ein typisch deutscher Running Gag.
C H | Welcher französische Komiker ruft im deutschen Kult-Clip „Nein! – Doch! – Ohhh!“? | Louis de Funès | Pierre Richard ; Jacques Tati ; Jean-Paul Belmondo | Er war für seine Grimassen berühmt. ; Er spielte den Gendarmen von Saint-Tropez. ; In Deutschland liefen viele seiner Filme als „Balduin“. | Der Dialog stammt aus der deutschen Fassung von „Hasch mich – ich bin der Mörder“ (1971).
C M | Welche beiden Unternehmen entwickelten 2020 die deutsche Corona-Warn-App? | SAP und Deutsche Telekom | Siemens und Bosch ; Google und Apple ; Vodafone und Allianz | Beide sind DAX-Konzerne. ; Einer sitzt in Walldorf. ; Der andere hat ein magentafarbenes T im Logo. | Google und Apple lieferten nur die Schnittstelle — 2023 wurde die App in den Ruhemodus versetzt.
C H | Welcher Satiriker behauptete 2015, das „Stinkefinger“-Video des griechischen Finanzministers Varoufakis gefälscht zu haben? | Jan Böhmermann | Oliver Welke ; Martin Sonneborn ; Christian Ehring | Er moderierte damals das „Neo Magazin Royale“. ; Die Aktion lief unter dem Hashtag #varoufake. ; Heute moderiert er das „ZDF Magazin Royale“. | Am Ende war nicht das Video der Fake, sondern die Fälschungs-Behauptung selbst — ein Satire-Coup.
C M | Welches Wort wurde zum Jugendwort des Jahres 2023 gekürt? | goofy | sus ; wild ; slay | Es stammt aus dem Englischen. ; Es beschreibt jemanden, der tollpatschig oder albern ist. ; So heißt auch eine Disney-Figur. | Nach „cringe“ (2021) und „smash“ (2022) setzte sich 2023 „goofy“ durch.
W M | Die deutschsprachige Wikipedia ist die größte Sprachversion der Wikipedia. | falsch | Die englische Wikipedia ist mit Abstand die größte — die deutsche zählt mit rund 2,9 Millionen Artikeln (Stand 2024) aber zu den größten.
W M | Den Podcast „Fest & Flauschig“ machen Jan Böhmermann und Olli Schulz. | wahr | Der Podcast startete 2016 bei Spotify und gehört seitdem zu den erfolgreichsten deutschen Podcasts.
W E | Das Jugendwort des Jahres 2024 lautet „cringe“. | falsch | 2024 gewann „Aura“ — „cringe“ war schon 2021 Jugendwort des Jahres.
S U | Wie viele Millionen .de-Domains waren Ende 2023 registriert? | 17.7 | Mio. | 20 | 1 | 100 | Mehr als zehn Millionen. ; Weniger als 25 Millionen. ; Ungefähr eine pro fünf Einwohner. | .de gehört zu den größten Länderendungen der Welt — verwaltet wird sie von der DENIC in Frankfurt.
S H | In welchem Jahr wurde das allererste „Jugendwort des Jahres“ gekürt? | 2008 | Jahr | 2 | 1990 | 2020 | Vor dem Smartphone-Boom in Deutschland. ; Im Jahr der Finanzkrise. ; Ende der 2000er-Jahre. | Die Wahl rief der Langenscheidt-Verlag ins Leben — seit 2020 stimmen Jugendliche selbst online ab.
S H | In welchem Jahr stürmte „Schnappi, das kleine Krokodil“ auf Platz 1 der deutschen Charts? | 2005 | Jahr | 2 | 1990 | 2020 | Mitte der 2000er-Jahre. ; Im Jahr, in dem Angela Merkel Kanzlerin wurde. ; Kurz nach dem Jahreswechsel. | Das Lied sang die damals kleine Joy Gruttmann — es war schon Jahre zuvor aufgenommen worden.
O M | Sortiere diese deutschen Satire-Marken nach ihrem Start — die älteste zuerst. | Titanic (Magazin) = 1979 ; Der Postillon = 2008 ; heute-show = 2009 ; ZDF Magazin Royale = 2020 | Das gedruckte Heft ist am ältesten. ; Das Online-Portal startete knapp vor der TV-Show. ; Böhmermanns ZDF-Format ist das jüngste. | Beim Postillon fallen bis heute regelmäßig Leser auf die erfundenen Meldungen herein.
O H | Bringe diese deutschen Netz-Momente in die zeitliche Reihenfolge — den frühesten zuerst. | Merkels „Neuland“-Satz = 2013 ; Rezos „Die Zerstörung der CDU“ = 2019 ; Start der Corona-Warn-App = 2020 ; Jugendwort „cringe“ = 2021 | Die Kanzlerin kommt zuerst. ; Das YouTube-Video erschien vor einer Europawahl. ; Das Jugendwort ist am jüngsten. | Rezos Video wurde innerhalb weniger Wochen mehr als zehn Millionen Mal angeklickt.
M H | Welche DREI dieser Begriffe waren schon einmal „Jugendwort des Jahres“? | Babo ; Läuft bei dir ; Ehrenmann | Digga ; Krass ; Alter | Einer bedeutet Boss oder Anführer. ; Einer lobt, wenn es bei jemandem gut klappt. ; Einer steht für einen anständigen Kerl. | Babo gewann 2013, „Läuft bei dir“ 2014 und „Ehrenmann/Ehrenfrau“ 2018.
M E | Welche ZWEI dieser Chat-Abkürzungen verwendet man zum Verabschieden? | cu ; bb | lol ; omg ; imho ; afk | Eine klingt wie „see you“. ; Die andere verdoppelt einen Buchstaben. ; Die falschen drücken Lachen, Staunen, Meinung oder Abwesenheit aus. | „cu“ steht für „see you“, „bb“ für „bye bye“ — „afk“ heißt „away from keyboard“.

@ youtuber_streamer
E E | Welche Plattform ist hier gesucht? | ▶️📺🔴 | YouTube | Twitch ; Netflix ; Vimeo | Sie wurde 2005 gegründet. ; Sie gehört zu Google. ; Das Logo ist ein weißes Dreieck auf Rot. | Der Name verbindet „You“ mit „Tube“ — einem englischen Umgangswort für den Fernseher.
E E | Welche Videoart ist hier gesucht? | 📦✂️🎥 | Unboxing | Haul ; Let's Play ; Vlog | Oft sieht man nur Hände. ; Neue Technik oder Spielzeug wird gezeigt. ; Eine Verpackung wird geöffnet. | Unboxing-Videos wurden mit neuen Smartphones groß — manche Kinderkanäle öffnen ausschließlich Überraschungseier.
E M | Welches Video-Genre ist hier gesucht? | 🎧👂🤫 | ASMR | Podcast ; Hörspiel ; Meditation | Man schaut es am besten mit Kopfhörern. ; Es wird oft geflüstert. ; Es soll ein angenehmes Kribbeln auslösen. | Typische ASMR-Geräusche sind Flüstern, Kratzen oder das Knistern von Papier.
E H | Welches Video-Genre ist hier gesucht? | 🍜🍗📹🇰🇷 | Mukbang | Food-Porn ; Kochshow ; Food-Truck | Die Streamer plaudern dabei mit dem Chat. ; Man sieht jemandem beim Essen zu. ; Oft werden riesige Portionen verspeist. | Das Wort verbindet die koreanischen Begriffe für „essen“ und „Übertragung“.
C H | Wie heißt der jährliche Charity-Livestream deutscher Streamer wie Gronkh und PietSmiet? | Friendly Fire | Stream for Charity ; Zocken hilft ; Spendenmarathon | Er findet meist im Dezember statt. ; Das Geld geht an gemeinnützige Projekte. ; Der Name stammt aus dem Militär-Jargon für Beschuss durch eigene Leute. | Seit 2015 kamen bei „Friendly Fire“ insgesamt viele Millionen Euro für gute Zwecke zusammen.
C E | Was macht ein Streamer bei einem „Raid“ auf Twitch? | Er schickt seine Zuschauer am Ende zu einem anderen Kanal | Er sperrt alle Zuschauer aus ; Er spielt gegen andere Streamer ; Er verlost Abonnements | Es passiert meistens am Ende eines Streams. ; Es ist eine Geste der Unterstützung. ; Die Zuschauer ziehen gemeinsam weiter. | Ein Raid kann kleinen Kanälen auf einen Schlag Hunderte neue Zuschauer bringen.
C E | Wofür steht die Abkürzung „VOD“, mit der Streamer aufgezeichnete Streams bezeichnen? | Video on Demand | Video over DSL ; Viewer on Display ; Visual Online Diary | Man kann es jederzeit abrufen. ; Auch Mediatheken bieten es an. ; Das letzte Wort heißt „Nachfrage“. | Auf Twitch bleiben VODs je nach Konto nur einige Tage bis Wochen gespeichert.
C H | Wie heißt die Snack- und Schokoladenmarke, die MrBeast 2022 gründete? | Feastables | Beast Bites ; Jimmy's Chocs ; MrBeast Bars | Die ersten Produkte waren Schokoriegel. ; Der Name spielt auf ein Festmahl an. ; Er klingt wie „Beast“ mit „F“. | Zum Start versteckte MrBeast wie bei Willy Wonka goldene Tickets in den Riegeln.
C H | Unter welchem Namen kennt man den deutschen Streamer Kevin Teller? | Papaplatte | HandOfBlood ; Trymacs ; Rewinside | Er streamt vor allem auf Twitch. ; Er gehört zu den meistgesehenen deutschen Streamern der 2020er. ; Im Namen steckt ein Kinderwort für Vater. | Papaplatte ist neben Twitch auch mit YouTube-Videos und Formaten mit anderen Creatorn erfolgreich.
C U | Welcher spanische Streamer stellte mit seinem Box-Event „La Velada del Año“ Twitch-Zuschauerrekorde auf? | Ibai | Rubius ; AuronPlay ; TheGrefg | Er stammt aus Bilbao. ; Er gründete den E-Sport-Club KOI mit. ; Sein Nachname ist Llanos. | Bei „La Velada del Año“ boxen Streamer gegeneinander — zeitweise schauen Millionen Menschen gleichzeitig zu.
W E | MrBeast heißt mit bürgerlichem Namen Jimmy Donaldson. | wahr | James Stephen „Jimmy“ Donaldson stammt aus North Carolina und lud schon als Teenager 2012 erste Videos hoch.
W H | Die Streaming-Plattform Kick ist ein Ableger von Twitch. | falsch | Kick startete 2022 als unabhängige Konkurrenz — hinter der Plattform stehen die Gründer eines Online-Casinos.
W H | ASMR steht für „Autonomous Sensory Meridian Response“. | wahr | Der Begriff entstand 2010 in einem Internetforum — wissenschaftlich ist das Phänomen bis heute kaum erforscht.
S U log | Wie viele Abonnenten brauchte ein Kanal ab 2018 mindestens, um ins YouTube-Partnerprogramm zu kommen? | 1000 | Abonnenten | 30 | 10 | 100000 | Mehr als 100. ; Weniger als 10.000. ; Eine glatte Zahl mit drei Nullen. | Zusätzlich verlangte YouTube 4.000 Stunden Wiedergabezeit im Jahr — erst dann gab es Geld aus der Werbung.
S U log | Wie viele Millionen US-Dollar verdiente MrBeast laut Forbes im Jahr 2021? | 54 | Mio. US-Dollar | 30 | 1 | 500 | Mehr als 20 Millionen. ; Weniger als 100 Millionen. ; Etwa eine Million pro Woche. | Damit führte er 2022 die Forbes-Liste der bestverdienenden YouTuber an — das meiste Geld steckt er in neue Videos.
O M | Sortiere diese YouTube-Auszeichnungen nach der nötigen Abonnentenzahl — die niedrigste zuerst. | Silberner Play Button = 100.000 ; Goldener Play Button = 1 Million ; Diamant-Play-Button = 10 Millionen ; Roter Diamant = 100 Millionen | Der erste Award ist silbern. ; Gold gibt es für die erste Million. ; Der rote Award ist extrem selten. | Den roten Diamanten für 100 Millionen Abos bekamen 2019 als Erste T-Series und PewDiePie.
O U | Sortiere diese Webvideo-Stars nach ihrem Geburtsjahr — den ältesten zuerst. | Gronkh = 1977 ; PewDiePie = 1989 ; Rezo = 1992 ; MrBeast = 1998 | Der deutsche Let's-Play-Pionier ist am ältesten. ; Der Schwede folgt. ; Der US-Amerikaner ist der jüngste. | Gronkh war schon über 30, als er 2010 mit Let's Plays auf YouTube durchstartete.
M E | Welche ZWEI dieser deutschen Webvideo-Stars sind vor allem für Let's Plays bekannt? | Gronkh ; PietSmiet | Bibi ; Mai Thi Nguyen-Kim ; LeFloid ; Dagi Bee | Einer gilt als Pionier des Genres. ; Der andere ist auch der Name einer Gruppe. ; Die falschen machen Beauty-, Wissens- oder News-Videos. | Beim Let's Play kommentiert man ein Videospiel, während man es spielt.
M E | Welche ZWEI dieser Plattformen sind vor allem für Livestreams bekannt? | Twitch ; Kick | Netflix ; Spotify ; Pinterest ; LinkedIn | Eine gehört zu Amazon. ; Die andere startete 2022. ; Beide leben von Live-Übertragungen mit Chat. | Twitch dominiert den Markt — Kick lockte einige Stars mit hoch dotierten Verträgen.

@ internet_geschichte
E E | Welche Plattform ist hier gesucht? | 🐦💬#️⃣ | Twitter | Facebook ; Tumblr ; Snapchat | Ihr Logo war jahrelang blau. ; Beiträge waren anfangs auf 140 Zeichen begrenzt. ; Seit 2023 heißt sie anders. | Der Logo-Vogel hieß intern „Larry“ — nach dem Basketballstar Larry Bird.
E E | Welches soziale Netzwerk ist hier gesucht? | 📘👍👥 | Facebook | Twitter ; LinkedIn ; MySpace | Es wurde 2004 an einer US-Uni gegründet. ; Sein Gründer heißt Mark Zuckerberg. ; Der Daumen steht für „Gefällt mir“. | Den „Gefällt mir“-Button gibt es erst seit 2009 — vorher konnte man Beiträge nur kommentieren.
E M | Welcher Browser ist hier gesucht? | 🦊🔥🌐 | Firefox | Chrome ; Opera ; Safari | Er wird von einer gemeinnützigen Organisation entwickelt. ; Version 1.0 erschien 2004. ; Sein Name ist ein Spitzname des Roten Pandas. | Firefox hieß zuerst „Phoenix“, dann „Firebird“ — beide Namen waren schon vergeben.
E M | Welches Online-Projekt ist hier gesucht? | 📚🌍🧩 | Wikipedia | Google Books ; Encyclopaedia Britannica ; Wiktionary | Jeder kann mitschreiben. ; Das Logo ist eine Kugel aus Puzzleteilen. ; Es wurde 2001 gegründet. | Oben am Logo fehlen ein paar Puzzleteile — ein Zeichen, dass das Wissen nie vollständig ist.
C E | Wofür steht das „S“ in „HTTPS“? | Secure | Server ; Speed ; System | Man erkennt es am Schloss-Symbol im Browser. ; Die Verbindung ist verschlüsselt. ; Übersetzt heißt es „sicher“. | Bei HTTPS werden alle Daten zwischen Browser und Server verschlüsselt übertragen.
C M | Welcher Microsoft-Messenger wurde 2013 zugunsten von Skype abgeschaltet? | MSN Messenger | ICQ ; AIM ; Yahoo Messenger | Er hieß zuletzt „Windows Live Messenger“. ; Man konnte Kontakte per „Nudge“ durchrütteln. ; Die Abkürzung steht für „Microsoft Network“. | In den 2000ern war der Messenger mit Emoticons und Statuszeilen der Treffpunkt einer ganzen Schülergeneration.
C H | Welche Organisation betreibt die „Wayback Machine“, ein riesiges Archiv alter Webseiten? | Internet Archive | Google ; Wikimedia Foundation ; UNESCO | Sie sitzt in San Francisco. ; Sie ist gemeinnützig. ; Sie archiviert auch Bücher, Filme und Software. | Die Organisation sammelt seit 1996 Schnappschüsse des Webs — der Name spielt auf eine Zeichentrick-Zeitmaschine an.
C H | Unter welchem Namen gründete Jeff Bezos 1994 zunächst Amazon? | Cadabra | Relentless ; BookWorld ; Everything Store | Der Name erinnert an einen Zauberspruch. ; Er hat sieben Buchstaben. ; Er wurde verworfen, weil er am Telefon wie das englische Wort für „Leiche“ klang. | Wer relentless.com eintippt, landet übrigens bis heute bei Amazon.
C U | Welcher scherzhafte HTTP-Statuscode stammt aus einem Aprilscherz von 1998? | 418 I'm a teapot | 404 Not Found ; 451 Unavailable For Legal Reasons ; 503 Service Unavailable | Er gehört zum „Hyper Text Coffee Pot Control Protocol“. ; Es geht um ein Küchengerät. ; Die Zahl liegt zwischen 404 und 451. | Laut dem Scherz-Standard antwortet eine Teekanne so, wenn man sie Kaffee kochen lassen will.
C U | Was zeigte eines der allerersten Fotos im World Wide Web (1992)? | Eine Parodie-Band von CERN-Mitarbeiterinnen | Tim Berners-Lee an seinem Computer ; Das CERN-Gebäude bei Genf ; Eine Kaffeemaschine | Es wurde am CERN aufgenommen. ; Die vier Abgebildeten posieren im Stil der 1960er. ; Die Gruppe hieß „Les Horribles Cernettes“. | Tim Berners-Lee bat um ein Bild der Doo-Wop-Band — es gilt als eines der ersten Fotos im Web.
W M | Tim Berners-Lee ließ das World Wide Web patentieren und verdiente an jeder Webseite mit. | falsch | Das CERN gab die Web-Technik 1993 lizenzfrei für alle frei — ein Grund für ihren rasanten Erfolg.
W E | Das @-Zeichen wurde eigens für E-Mail-Adressen erfunden. | falsch | Das Zeichen gab es schon Jahrhunderte vorher — Kaufleute nutzten es etwa als Maßeinheit oder für „zu je“.
W E | E-Mails gab es schon vor dem World Wide Web. | wahr | Die erste E-Mail wurde 1971 verschickt — das Web entstand erst ab 1989 am CERN.
W H | Das Wort „Wiki“ bedeutet auf Hawaiisch „schnell“. | wahr | Ward Cunningham benannte sein erstes Wiki 1995 nach dem „Wiki Wiki“-Shuttlebus am Flughafen von Honolulu.
S M | Wie viele Milliarden Menschen nutzten laut der UN-Fernmeldeunion ITU im Jahr 2023 das Internet? | 5.4 | Mrd. | 15 | 1 | 8 | Mehr als die Hälfte der Menschheit. ; Weniger als sechs Milliarden. ; Etwa zwei Drittel der Weltbevölkerung. | Rund 2,6 Milliarden Menschen waren 2023 laut ITU noch offline.
S U | In welchem Jahr verschickte ein Marketingmann die erste Massen-Werbemail — den ersten Spam — über das ARPANET? | 1978 | Jahr | 3 | 1960 | 2000 | Lange vor dem World Wide Web. ; Ende der 1970er-Jahre. ; Gut sechs Jahre nach der ersten E-Mail. | Gary Thuerk bewarb 1978 neue Computer bei rund 400 Empfängern — und erntete prompt Beschwerden.
S M | Für wie viele Milliarden US-Dollar kaufte Elon Musk 2022 Twitter? | 44 | Mrd. US-Dollar | 20 | 1 | 200 | Mehr als 20 Milliarden. ; Weniger als 50 Milliarden. ; Mehr als doppelt so viel, wie Facebook für WhatsApp zahlte. | Nach der Übernahme benannte Musk die Plattform 2023 in X um.
O H | Sortiere diese Tech-Übernahmen nach ihrem Kaufpreis — die günstigste zuerst. | Instagram durch Facebook (2012) = ≈ 1 Mrd. US-Dollar ; GitHub durch Microsoft (2018) = ≈ 7,5 Mrd. US-Dollar ; WhatsApp durch Facebook (2014) = ≈ 19 Mrd. US-Dollar ; LinkedIn durch Microsoft (2016) = ≈ 26 Mrd. US-Dollar | Die Foto-App war ein Schnäppchen. ; Die Programmier-Plattform liegt auf Platz zwei. ; Das Karrierenetzwerk war am teuersten. | Instagram hatte beim Kauf nur 13 Mitarbeiter — heute nutzen es weit über eine Milliarde Menschen.
O U | Sortiere diese Online-Dienste nach dem Jahr ihrer Abschaltung — den frühesten zuerst. | GeoCities (USA) = 2009 ; Vine = 2017 ; Internet Explorer = 2022 (Support-Ende) ; ICQ = 2024 | Die Homepage-Baukästen der 90er verschwanden zuerst. ; Die Sechs-Sekunden-Videos folgten. ; Der „Uh-oh“-Messenger hielt am längsten durch. | ICQ wurde im Juni 2024 nach fast 28 Jahren abgeschaltet.
O M | Sortiere diese Internetanschlüsse nach ihrer typischen Geschwindigkeit — den langsamsten zuerst. | Analog-Modem = 56 kbit/s ; ISDN = 64 kbit/s ; DSL 16000 = 16 Mbit/s ; Glasfaser = 1 Gbit/s | Das piepende Gerät war am langsamsten. ; Knapp darüber lag der digitale Telefonanschluss. ; Das Lichtkabel ist am schnellsten. | Mit einem 56k-Modem dauerte der Download eines einzigen MP3-Songs rund zehn Minuten.
M H | Welche DREI dieser Abkürzungen bezeichnen Internet-Protokolle? | HTTP ; FTP ; SMTP | HTML ; JPEG ; USB | Eines regelt den Abruf von Webseiten. ; Eines überträgt Dateien. ; Eines verschickt E-Mails. | HTML ist eine Auszeichnungssprache, JPEG ein Bildformat und USB eine Geräteschnittstelle.
M M | Welche ZWEI dieser Dienste gehören zum Konzern Meta? | Instagram ; WhatsApp | YouTube ; Twitch ; LinkedIn ; Snapchat | Einer ist eine Foto-App. ; Der andere ist ein Messenger. ; Der Konzern hieß bis 2021 Facebook. | Facebook benannte sich 2021 in Meta um — der Name spielt auf das „Metaverse“ an.

@ virale_trends
E E | Welche Mitmach-Aktion ist hier gesucht? | 🧊🪣💦 | Ice Bucket Challenge | Mannequin Challenge ; Bottle Flip Challenge ; Cinnamon Challenge | Sie lief im Sommer 2014. ; Man wurde von Freunden nominiert. ; Es ging um Spenden für die Forschung. | Selbst Ex-US-Präsident George W. Bush ließ sich 2014 einen Eimer über den Kopf kippen.
E M | Welches Trend-Gefährt ist hier gesucht? | 🛹⚡🔥 | Hoverboard | E-Scooter ; Segway ; Waveboard | Es hat zwei Räder und keinen Lenker. ; Man steuert es durch Gewichtsverlagerung. ; 2015 sorgten brennende Akkus für Schlagzeilen. | Den Namen lieh sich das Gefährt vom schwebenden Brett aus „Zurück in die Zukunft II“ — echte Hoverboards schweben aber nicht.
E E | Welches Kult-Spielzeug ist hier gesucht? | 🥚🐣📟 | Tamagotchi | Furby ; Game Boy ; Nintendogs | Es kam in den 1990ern aus Japan. ; Man musste ein virtuelles Haustier füttern. ; Das Gerät ist eiförmig. | Der Name verbindet das japanische „tamago“ (Ei) mit „uotchi“ — der japanischen Aussprache von „Watch“.
E M | Welcher Trend ist hier gesucht? | 🧍❄️🎥 | Mannequin Challenge | Ice Bucket Challenge ; Planking ; Harlem Shake | Er lief Ende 2016. ; Alle bleiben regungslos stehen. ; Nur die Kamera bewegt sich. | Selbst Hillary Clinton machte kurz vor der US-Wahl 2016 mit.
C E | Welche Zeitung kaufte 2022 das Worträtsel Wordle? | The New York Times | The Guardian ; The Washington Post ; Die Zeit | Sie hat ihren Sitz in Manhattan. ; Sie ist berühmt für ihre Kreuzworträtsel. ; Ihr Spitzname ist „The Gray Lady“. | Der Kaufpreis lag laut der Zeitung im niedrigen siebenstelligen Dollarbereich.
C E | Wie heißt das bunte Silikon-Spielzeug mit Noppen zum Eindrücken, das 2021 die Schulhöfe eroberte? | Pop It | Fidget Spinner ; Squishy ; Slime | Beim Drücken macht es ein leises Ploppen. ; Man kann es umdrehen und von vorn beginnen. ; Es erinnert an Luftpolsterfolie. | Die Idee hatte schon in den 1970ern das israelische Ehepaar Coster — bekannt für das Spiel „Wer ist es?“.
C M | In welchem Land ging 2012 die missglückte Restaurierung des Freskos „Ecce Homo“ um die Welt? | Spanien | Italien ; Portugal ; Mexiko | Das Bild zeigt Jesus mit Dornenkrone. ; Eine ältere Kirchgängerin wollte das verblasste Bild auffrischen. ; Die Kirche steht in der Nähe von Saragossa. | Das Netz taufte das Ergebnis „Ecce Mono“ — „Seht den Affen“. Heute pilgern Touristen nach Borja.
C H | Welcher Moderator verkündete 2015 bei der Miss-Universe-Wahl versehentlich die falsche Siegerin? | Steve Harvey | Ryan Seacrest ; Jimmy Kimmel ; Billy Bush | Er ist auch als Komiker bekannt. ; Er moderierte die Show „Family Feud“. ; Statt Miss Philippinen rief er Miss Kolumbien aus. | Die Krone musste auf offener Bühne umgesetzt werden — die Panne wurde zum Dauer-Meme.
C M | Welcher US-Senator wurde 2021 mit dicken Fäustlingen bei der Amtseinführung von Joe Biden zum Meme? | Bernie Sanders | Chuck Schumer ; Mitch McConnell ; Ted Cruz | Er trat zweimal bei den Vorwahlen der Demokraten an. ; Er vertritt den Bundesstaat Vermont. ; Die Handschuhe hatte eine Lehrerin aus alten Pullovern genäht. | Sanders verkaufte das Motiv auf Pullovern und sammelte so rund 1,8 Millionen Dollar für Hilfsorganisationen in Vermont.
C H | Welche Moderatorin postete 2014 bei der Oscar-Verleihung das Gruppen-Selfie, das zum damals meistgeteilten Tweet wurde? | Ellen DeGeneres | Oprah Winfrey ; Whoopi Goldberg ; Tina Fey | Sie hatte eine eigene Talkshow. ; Auf dem Foto sind Bradley Cooper und Meryl Streep. ; Sie sprach Dorie in „Findet Nemo“. | Bradley Cooper drückte ab — der Tweet wurde über drei Millionen Mal geteilt.
W M | Die Foto-App BeReal stammt aus Frankreich. | wahr | Die App aus Paris fordert einmal am Tag zu einem spontanen Foto mit Front- und Rückkamera auf — 2022 war sie ein Hype.
W M | 2019 wurde das Foto eines Eis zum meistgelikten Instagram-Beitrag der Welt. | wahr | Das „World Record Egg“ überholte im Januar 2019 ein Babyfoto von Kylie Jenner.
W H | Der Dalgona-Kaffee-Trend von 2020 stammt aus Italien. | falsch | Der aufgeschlagene Instantkaffee wurde in Südkorea populär — benannt nach einer koreanischen Zuckerwaben-Süßigkeit.
W H | Die Klingelton-Figur Crazy Frog stammt aus Deutschland. | falsch | Animiert hat sie der Schwede Erik Wernquist, das Geräusch stammt vom Schweden Daniel Malmedahl.
S M | Wie viele Tage blockierte das Containerschiff „Ever Given“ im März 2021 den Suezkanal? | 6 | Tage | 30 | 1 | 60 | Mehr als drei Tage. ; Weniger als zwei Wochen. ; Knapp eine Woche. | Ein kleiner Bagger, der neben dem Riesen winzig wirkte, wurde zum Meme für jede überwältigende Aufgabe.
S U | Wie alt war die Hobbymalerin, als sie 2012 das Fresko „Ecce Homo“ in Borja „restaurierte“? | 81 | Jahre | 10 | 20 | 110 | Sie war bereits im Rentenalter. ; Älter als 75. ; Jünger als 90. | Cecilia Giménez wurde durch ihren Fehlgriff weltberühmt — ihr Werk lockt seither Zehntausende Besucher an.
S M | In welchem Jahr ging das Worträtsel Wordle online? | 2021 | Jahr | 1 | 2000 | 2024 | Nach Beginn der Corona-Pandemie. ; Im Herbst jenes Jahres. ; Im selben Jahr startete der „Squid Game“-Hype. | Josh Wardle programmierte das Spiel zunächst für seine Partnerin — im Oktober 2021 machte er es öffentlich.
O M | Sortiere diese Spielzeug-Trends nach dem Jahr ihres großen Hypes — den frühesten zuerst. | Zauberwürfel = um 1980 ; Loom Bands = 2014 ; Fidget Spinner = 2017 ; Pop It = 2021 | Der bunte Würfel kam zuerst. ; Die Gummiringe folgten. ; Das Noppen-Spielzeug ist das jüngste. | Der Zauberwürfel von Ernő Rubik wurde Anfang der 1980er zum meistverkauften Spielzeug der Welt.
O H | Sortiere diese viralen Pannen chronologisch — die früheste zuerst. | „Ecce Homo“-Restaurierung = 2012 ; Falsche Miss-Universe-Siegerin = 2015 ; Oscar-Umschlag-Panne = 2017 ; Ever Given im Suezkanal = 2021 | Das Fresko kam zuerst. ; Die Schönheitskönigin folgte. ; Das Schiff steckte zuletzt fest. | Bei den Oscars 2017 wurde erst „La La Land“ als bester Film verkündet — gewonnen hatte „Moonlight“.
M E | Welche DREI dieser Trends waren Tanz-Trends? | Macarena ; Harlem Shake ; Floss | Ice Bucket Challenge ; Mannequin Challenge ; Bottle Flip | Einer stammt aus den 1990ern. ; Einer beginnt mit einer einzelnen tanzenden Person. ; Bei einem schwingt man Arme und Hüften gegenläufig. | Bei der Mannequin Challenge bewegt sich gerade niemand — beim Bottle Flip nur eine Flasche.
M E | Welche ZWEI dieser Hypes waren Smartphone-Spiele? | Flappy Bird ; Pokémon GO | Loom Bands ; Fidget Spinner ; Pop It ; Zauberwürfel | Bei einem steuert man einen Vogel durch Röhren. ; Beim anderen fängt man Monster auf der Straße. ; Die falschen sind Spielzeuge zum Anfassen. | Flappy Bird stammte von einem einzelnen Entwickler aus Vietnam, Pokémon GO von der US-Firma Niantic.
"""
