"""Extra questions, wave 2: Kunst & Literatur (format: see tools/content/merge_extra.py)."""
KAT = "kunst_literatur"
REGION = "global"
DATA = r"""
@ gemaelde_erkennen
E E | Welches Gemälde ist hier gesucht? | 🌌🌀🌙🏘️ | Sternennacht | Caféterrasse am Abend ; Der Schrei ; Seerosen | Der Himmel über einem Dorf scheint zu wirbeln. ; Der Maler schuf es 1889 in einer Heilanstalt in Südfrankreich. ; Es stammt von Vincent van Gogh. | Van Gogh malte die „Sternennacht“ im Juni 1889 in Saint-Rémy — heute hängt sie im Museum of Modern Art in New York.
E E | Welches Kunstwerk ist hier gesucht? | 🌊🗻🚣 | Die große Welle vor Kanagawa | Das Eismeer ; Impression, Sonnenaufgang ; Der Wanderer über dem Nebelmeer | Es ist ein japanischer Farbholzschnitt. ; Im Hintergrund ist klein der Fuji zu sehen. ; Der Künstler heißt Hokusai. | Hokusais Holzschnitt entstand um 1831 als Teil der Serie „36 Ansichten des Berges Fuji“ und gehört zu den meistreproduzierten Bildern der Welt.
E H | Welches Gemälde ist hier gesucht? | 🕰️🧀🏜️ | Die Beständigkeit der Erinnerung | Der Garten der Lüste ; Der Sohn des Menschen ; Die Toteninsel | Es entstand 1931. ; Weiche Taschenuhren hängen über einem Ast und einer Tischkante. ; Der Maler war ein spanischer Surrealist mit gezwirbeltem Schnurrbart. | Salvador Dalí soll die zerfließenden Uhren nach dem Anblick eines in der Sonne schmelzenden Camemberts erfunden haben.
W M | Rembrandts „Nachtwache“ zeigt eigentlich gar keine nächtliche Szene. | wahr | Der Name kam erst später auf: Nachgedunkelter Firnis ließ das Gruppenbild der Amsterdamer Bürgerwehr wie eine Nachtszene wirken.
W H | Michelangelo malte die Decke der Sixtinischen Kapelle im Liegen auf dem Rücken. | falsch | Er arbeitete stehend auf einem eigens entworfenen Gerüst, den Kopf in den Nacken gelegt — und beklagte sich darüber sogar in einem Spottgedicht.
S M | In welchem Jahr malte Edvard Munch die erste Fassung seines Bildes „Der Schrei“? | 1893 | Jahr | 3 | 1850 | 1950 | Ende des 19. Jahrhunderts. ; Wenige Jahre nach van Goghs Tod (1890). ; Zwischen 1890 und 1895. | Munch schuf mehrere Fassungen — die bekannte gemalte Version von 1893 hängt heute im Nationalmuseum in Oslo.
S U | In welchem Jahr gründeten Kirchner, Heckel und Schmidt-Rottluff in Dresden die Künstlergruppe „Die Brücke“? | 1905 | Jahr | 3 | 1850 | 1950 | Zu Beginn des 20. Jahrhunderts. ; Im selben Jahr veröffentlichte Einstein seine spezielle Relativitätstheorie. ; Zwischen 1900 und 1910. | Die Gründer waren eigentlich Architekturstudenten — „Die Brücke“ gilt als Keimzelle des deutschen Expressionismus.
O M | Sortiere diese Kunstrichtungen nach ihrer Entstehung — die früheste zuerst. | Romantik = um 1800 ; Impressionismus = ab den 1870ern ; Kubismus = ab 1907 ; Pop-Art = ab Mitte der 1950er | Caspar David Friedrich gehört zur ältesten. ; Monet kommt vor Picasso. ; Andy Warhol ist der Jüngste im Bunde. | Die Pop-Art entstand Mitte der 1950er in Großbritannien und wurde in den USA durch Warhol und Lichtenstein berühmt.
O H | Sortiere diese Gemälde nach ihrer Breite — das schmalste zuerst. | Mona Lisa = ca. 53 cm ; Sternennacht = ca. 92 cm ; Die Nachtwache = über 4 m ; Guernica = ca. 7,8 m | Das berühmteste Bild ist auch das kleinste. ; Van Goghs Nachthimmel ist knapp einen Meter breit. ; Picassos Antikriegsbild ist das größte. | Rembrandts „Nachtwache“ war einst noch größer: 1715 wurde sie beschnitten, damit sie in einen Saal des Amsterdamer Rathauses passte.
M M | Welche DREI dieser Gemälde stammen von Vincent van Gogh? | Die Kartoffelesser ; Caféterrasse am Abend ; Sonnenblumen | Der Kuss ; Die Nachtwache ; Seerosen | Alle drei entstanden zwischen 1885 und 1889. ; Der Maler war Niederländer und lebte zuletzt in Frankreich. ; Klimt, Rembrandt und Monet malten die übrigen. | Die „Sonnenblumen“ malte van Gogh 1888 in Arles gleich in mehreren Fassungen — als Schmuck für das Zimmer seines Freundes Gauguin.
C E | Wie nennt man ein Gemälde, das unbewegte Dinge wie Obst, Blumen oder Gläser zeigt? | Stillleben | Genrebild ; Historienbild ; Landschaftsbild | Die Motive bewegen sich nicht. ; Besonders beliebt war es im Holland des 17. Jahrhunderts. ; Das Wort enthält dreimal hintereinander denselben Buchstaben. | Im Stillleben zeigten Maler oft auch welke Blumen oder Totenschädel — als Mahnung an die Vergänglichkeit.
C M | In welcher Stadt hängt Botticellis „Die Geburt der Venus“? | Florenz | Rom ; Venedig ; Mailand | Die Stadt war die Heimat der Medici. ; Sie liegt in der Toskana. ; Das Museum heißt Uffizien. | Das Bild entstand um 1485 und gehört zu den Hauptwerken der Uffizien.
C H | Wer malte „Die Freiheit führt das Volk“? | Eugène Delacroix | Jacques-Louis David ; Théodore Géricault ; Gustave Courbet | Das Bild entstand 1830 nach der Julirevolution. ; Eine Frau mit Trikolore stürmt über eine Barrikade. ; Der Maler war der Hauptvertreter der französischen Romantik. | Die barbusige Freiheitsfigur auf dem Bild wurde zum Vorbild für Marianne, die Symbolfigur der Französischen Republik.
C U | Wie heißt Leonardos Maltechnik, bei der Umrisse weich und rauchig ineinander verschwimmen? | Sfumato | Impasto ; Grisaille ; Sgraffito | Der Begriff ist italienisch. ; Er bedeutet sinngemäß „verraucht“. ; Das Lächeln der Mona Lisa ist das bekannteste Beispiel. | Beim Sfumato trug Leonardo hauchdünne Lasuren übereinander — so fehlen harte Konturen völlig.

@ weltliteratur
E E | Welcher Roman ist hier gesucht? | 🐋🚢🦵⚓ | Moby-Dick | Der alte Mann und das Meer ; 20.000 Meilen unter dem Meer ; Die Schatzinsel | Ein Kapitän jagt besessen ein Tier. ; Der Kapitän hat ein Bein aus Walknochen. ; Der Roman beginnt mit „Nennt mich Ismael“. | Herman Melvilles Roman floppte zu Lebzeiten des Autors — heute gilt er als einer der größten amerikanischen Romane.
E E | Welcher Roman ist hier gesucht? | 👁️1️⃣9️⃣8️⃣4️⃣ | 1984 | Fahrenheit 451 ; Schöne neue Welt ; Farm der Tiere | Es ist eine Dystopie. ; Der „Große Bruder“ sieht alles. ; Der Titel ist eine Jahreszahl. | George Orwell schrieb den Roman 1948 — und vertauschte für den Titel angeblich einfach die letzten beiden Ziffern.
E H | Welcher Roman ist hier gesucht? | 👩💔🚂🇷🇺 | Anna Karenina | Krieg und Frieden ; Doktor Schiwago ; Madame Bovary | Eine verheiratete Frau verliebt sich in einen Offizier. ; Ein Bahnhof spielt am Anfang und am Ende eine Rolle. ; Der Autor schrieb auch „Krieg und Frieden“. | Leo Tolstois Roman beginnt mit dem berühmten Satz: „Alle glücklichen Familien gleichen einander, jede unglückliche Familie ist auf ihre eigene Weise unglücklich.“
W E | In Mary Shelleys Roman heißt das Monster Frankenstein. | falsch | Frankenstein ist der Name seines Schöpfers, des Studenten Victor Frankenstein — das Geschöpf selbst bleibt namenlos.
W U | Der Satz „Elementary, my dear Watson“ kommt in keiner Sherlock-Holmes-Geschichte von Arthur Conan Doyle wörtlich vor. | wahr | Holmes sagt zwar „Elementary“ und „my dear Watson“ — die berühmte Kombination stammt aber aus späteren Verfilmungen und Parodien.
W M | Leo Tolstoi erhielt für „Krieg und Frieden“ den Literaturnobelpreis. | falsch | Tolstoi wurde mehrfach nominiert, bekam den Preis aber nie — das gilt bis heute als eines der großen Versäumnisse des Nobelkomitees.
S M | In welchem Jahr erschien „Der kleine Prinz“ von Antoine de Saint-Exupéry? | 1943 | Jahr | 3 | 1880 | 2000 | Mitten im Zweiten Weltkrieg. ; Der Autor lebte damals im Exil in New York. ; Zwischen 1940 und 1945. | Das Buch erschien 1943 in New York — ein Jahr später kehrte Saint-Exupéry von einem Aufklärungsflug nicht zurück.
S H | Wie alt wurde die Schriftstellerin Jane Austen? | 41 | Jahre | 15 | 20 | 90 | Sie starb recht jung. ; Älter als 35. ; Sie erreichte nicht das 50. Lebensjahr. | Austen starb 1817 mit 41 Jahren — ihre Romane waren zu Lebzeiten ohne ihren Namen erschienen.
O M | Sortiere diese Dystopien nach ihrem Erscheinen — die älteste zuerst. | Schöne neue Welt = 1932 ; 1984 = 1949 ; Fahrenheit 451 = 1953 ; Der Report der Magd = 1985 | Aldous Huxley war zuerst dran. ; Orwells Roman erschien kurz vor seinem Tod. ; Margaret Atwoods Roman ist der jüngste. | Alle vier Romane warnen vor totalitärer Kontrolle — „Der Report der Magd“ wurde 2017 als Serie zum Welterfolg.
O M | Sortiere diese Jugend- und Fantasyromane nach ihrem Erscheinen — den ältesten zuerst. | Der Hobbit = 1937 ; Der König von Narnia = 1950 ; Harry Potter und der Stein der Weisen = 1997 ; Die Tribute von Panem – Tödliche Spiele = 2008 | Tolkien war ein Freund und Kollege von C. S. Lewis. ; Der Schrank nach Narnia öffnete sich vor der Zauberschule. ; Die Hungerspiele sind der jüngste Titel. | Tolkien und C. S. Lewis gehörten in Oxford zum Literaturzirkel „Inklings“ und lasen sich gegenseitig aus ihren Manuskripten vor.
M M | Welche ZWEI dieser Romane schrieb Jane Austen? | Stolz und Vorurteil ; Emma | Sturmhöhe ; Jane Eyre ; Große Erwartungen ; Middlemarch | Beide erschienen in den 1810er-Jahren. ; Eine Heldin heißt Elizabeth Bennet. ; Die Brontë-Schwestern, Dickens und George Eliot schrieben die anderen. | Austens erster Roman erschien anonym — auf dem Titelblatt stand nur „By a Lady“.
M H | Welche ZWEI dieser Autoren erhielten den Literaturnobelpreis? | Ernest Hemingway ; Toni Morrison | Mark Twain ; Jules Verne ; Virginia Woolf ; J. R. R. Tolkien | Beide stammen aus den USA. ; Einer schrieb über einen alten Fischer und einen riesigen Marlin. ; Die andere war die erste afroamerikanische Preisträgerin. | Hemingway erhielt den Preis 1954, Toni Morrison 1993 — Twain, Verne, Woolf und Tolkien gingen leer aus.
C E | Wie heißt das Land der winzigen Menschen in „Gullivers Reisen“? | Liliput | Nimmerland ; Utopia ; Narnia | Die Bewohner sind nur etwa 15 Zentimeter groß. ; Jonathan Swift erfand es 1726. ; Nach dem Land ist heute ein Wort für „winzig“ benannt. | Swifts Satire verspottete die englische Politik — in Liliput führt man sogar Krieg darüber, an welchem Ende man ein Ei aufschlägt.
C E | Wie heißt das Pferd von Pippi Langstrumpf? | Kleiner Onkel | Iltschi ; Fury ; Black Beauty | Es ist ein Schimmel mit schwarzen Punkten. ; Pippi hebt es mühelos mit bloßen Händen hoch. ; Der Name klingt nach einem Verwandten. | Das Pferd wohnt auf der Veranda der Villa Kunterbunt — gleich neben Pippis Affen Herrn Nilsson.
C M | Wie heißt der Erzfeind von Sherlock Holmes? | Professor Moriarty | Inspektor Lestrade ; Mycroft Holmes ; Irene Adler | Holmes nennt ihn den „Napoleon des Verbrechens“. ; Er lehrt Mathematik. ; Beide stürzen an den Reichenbachfällen in die Tiefe. | Conan Doyle wollte Holmes 1893 mit Moriartys Hilfe loswerden — nach Leserprotesten ließ er ihn wieder auferstehen.
C U | Wie heißt das Walfangschiff von Kapitän Ahab in „Moby-Dick“? | Pequod | Nautilus ; Hispaniola ; Bounty | Es ist nach einem Volk amerikanischer Ureinwohner benannt. ; Sein Erster Steuermann gab einer Kaffeehauskette den Namen. ; Der Name beginnt mit P. | Am Ende versinkt das Schiff samt Besatzung — nur der Erzähler Ismael überlebt, auf einen Sarg geklammert.

@ deutsche_literatur de
E E | Welches Werk ist hier gesucht? | 👨‍💼🛏️🐛 | Die Verwandlung | Der Process ; Das Schloss ; Der Steppenwolf | Ein Handelsreisender wacht eines Morgens auf. ; Er hat sich über Nacht verändert. ; Der Autor stammt aus Prag. | Franz Kafkas Erzählung von 1915 beginnt damit, dass Gregor Samsa als „ungeheueres Ungeziefer“ erwacht.
E E | Welches Werk ist hier gesucht? | 🧙‍♂️🧹💦🌊 | Der Zauberlehrling | Der Erlkönig ; Die Bürgschaft ; Der Taucher | Es ist eine Ballade. ; Ein Besen schleppt immer mehr Wasser herbei. ; „Die ich rief, die Geister, werd ich nun nicht los.“ | Goethe schrieb die Ballade 1797 — Disney machte sie 1940 in „Fantasia“ mit Micky Maus weltberühmt.
W M | Franz Kafka bat seinen Freund Max Brod, alle unveröffentlichten Manuskripte nach seinem Tod zu verbrennen. | wahr | Brod hielt sich nicht daran — nur deshalb kennen wir heute „Der Process“, „Das Schloss“ und „Amerika“.
W M | Heinrich Heine starb im Londoner Exil. | falsch | Heine lebte ab 1831 in Paris und starb dort 1856 nach jahrelanger Krankheit in seiner „Matratzengruft“.
W U | Friedrich Schiller hatte Medizin studiert und arbeitete zeitweise als Regimentsarzt. | wahr | An der Karlsschule in Stuttgart studierte er Medizin — „Die Räuber“ entstand heimlich noch während dieser Zeit.
S M | In welchem Jahr wurde Johann Wolfgang von Goethe geboren? | 1749 | Jahr | 3 | 1650 | 1850 | Mitte des 18. Jahrhunderts. ; Zehn Jahre vor Schiller. ; Zwischen 1745 und 1755. | Goethe kam am 28. August 1749 in Frankfurt am Main zur Welt und starb 1832 in Weimar.
S H | Wie alt wurde der Dichter Georg Büchner? | 23 | Jahre | 15 | 15 | 60 | Er starb sehr jung. ; Jünger als 30. ; Er erreichte nicht einmal die Mitte der Zwanziger. | Büchner starb 1837 in Zürich an Typhus — „Woyzeck“ blieb Fragment, und der wichtigste deutsche Literaturpreis trägt heute seinen Namen.
O M | Sortiere diese Kinderbücher nach ihrem Erscheinen — das älteste zuerst. | Emil und die Detektive = 1929 ; Der Räuber Hotzenplotz = 1962 ; Momo = 1973 ; Tintenherz = 2003 | Kästners Buch spielt im Berlin der Weimarer Republik. ; Preußlers Räuber kam vor Endes Zeitdieben. ; Cornelia Funkes Roman ist der jüngste. | Alle vier wurden verfilmt — „Emil und die Detektive“ schon 1931, nach einem Drehbuch von Billy Wilder.
O U | Sortiere diese Werke von Thomas Mann nach ihrem Erscheinen — das früheste zuerst. | Buddenbrooks = 1901 ; Der Tod in Venedig = 1912 ; Der Zauberberg = 1924 ; Doktor Faustus = 1947 | Der Familienroman war sein Erstling. ; Die Venedig-Novelle entstand vor dem Ersten Weltkrieg. ; Den Faust-Roman schrieb er im amerikanischen Exil. | Für die „Buddenbrooks“ bekam Thomas Mann 1929 den Literaturnobelpreis — fast 30 Jahre nach dem Erscheinen.
M M | Welche ZWEI dieser Dramen schrieb Friedrich Schiller? | Kabale und Liebe ; Maria Stuart | Nathan der Weise ; Woyzeck ; Emilia Galotti ; Iphigenie auf Tauris | Beide entstanden zwischen 1780 und 1800. ; Eines spielt am englischen Hof. ; Lessing, Büchner und Goethe schrieben die anderen. | „Kabale und Liebe“ (1784) ist ein bürgerliches Trauerspiel, „Maria Stuart“ (1800) zeigt den Machtkampf zweier Königinnen.
M H | Welche DREI dieser Dichter zählen zur Epoche der Romantik? | Novalis ; Joseph von Eichendorff ; Clemens Brentano | Friedrich Schiller ; Bertolt Brecht ; Gotthold Ephraim Lessing | Einer schrieb „Aus dem Leben eines Taugenichts“. ; Einer suchte in seinen Werken die „blaue Blume“. ; Die übrigen gehören zu Klassik, Moderne und Aufklärung. | Brentano sammelte mit Achim von Arnim die Volksliedersammlung „Des Knaben Wunderhorn“.
C E | In welcher Stadt spielt Erich Kästners „Emil und die Detektive“ hauptsächlich? | Berlin | Hamburg ; München ; Dresden | Emil fährt mit dem Zug in die Großstadt. ; Dort wohnt seine Großmutter. ; Es ist die deutsche Hauptstadt. | Emil wird im Zug bestohlen — mit einer Bande Kinder jagt er den Dieb durch die Stadt, bis rund um den Nollendorfplatz.
C M | Wer schrieb den Roman „Kleiner Mann – was nun?“ aus dem Jahr 1932? | Hans Fallada | Erich Kästner ; Kurt Tucholsky ; Alfred Döblin | Der Roman spielt in der Weltwirtschaftskrise. ; Er erzählt vom Angestellten Pinneberg und seinem „Lämmchen“. ; Das Pseudonym des Autors verbindet zwei Grimm-Märchen. | Rudolf Ditzen nannte sich nach „Hans im Glück“ und dem sprechenden Pferd Falada aus „Die Gänsemagd“.
C H | Wer schrieb das Theaterstück „Der Hauptmann von Köpenick“? | Carl Zuckmayer | Gerhart Hauptmann ; Carl Sternheim ; Ödön von Horváth | Das Stück beruht auf einem echten Fall von 1906. ; Ein Schuster erobert in Uniform ein Rathaus. ; Der Autor schrieb auch „Des Teufels General“. | Der echte Wilhelm Voigt besetzte 1906 in Hauptmannsuniform das Rathaus Köpenick — Zuckmayer machte daraus 1931 „ein deutsches Märchen“.
C U | Welcher Dichter schrieb den Briefroman „Hyperion“? | Friedrich Hölderlin | Novalis ; Clemens Brentano ; Jean Paul | Er war Studienfreund von Hegel und Schelling. ; Seine Geliebte nannte er „Diotima“. ; Er verbrachte die zweite Lebenshälfte in einem Turm in Tübingen. | Hölderlin lebte ab 1807 rund 36 Jahre lang geistig verwirrt im Tübinger „Hölderlinturm“ bei einem Schreinermeister.

@ architektur_bauwerke
E E | Welches Bauwerk ist hier gesucht? | 🪨🪨🌅🇬🇧 | Stonehenge | Externsteine ; Carnac ; Newgrange | Es ist ein prähistorischer Steinkreis. ; Er steht in Südengland. ; Zur Sommersonnenwende geht die Sonne genau über einem bestimmten Stein auf. | Die ältesten Teile entstanden um 3000 v. Chr. — einige der sogenannten Blausteine wurden über 200 Kilometer weit aus Wales herangeschafft.
E E | Welches Bauwerk ist hier gesucht? | 🕌💔👸🇮🇳 | Taj Mahal | Rotes Fort ; Goldener Tempel ; Hawa Mahal | Es besteht aus weißem Marmor. ; Ein Herrscher ließ es für seine verstorbene Frau bauen. ; Es steht in Agra. | Großmogul Shah Jahan ließ das Mausoleum ab 1631 für seine Lieblingsfrau Mumtaz Mahal errichten.
E E | Welches Bauwerk ist hier gesucht? | 🌉🔴🌫️🇺🇸 | Golden Gate Bridge | Brooklyn Bridge ; Tower Bridge ; Øresundbrücke | Es ist eine Hängebrücke. ; Oft verschwindet sie im Nebel. ; Sie führt nach San Francisco. | Die Brücke wurde 1937 eröffnet — trotz ihres Namens ist sie nicht golden, sondern im Farbton „International Orange“ gestrichen.
W E | Die Sagrada Família in Barcelona ist bis heute nicht fertiggestellt (Stand 2024). | wahr | Antoni Gaudí arbeitete über 40 Jahre an der Kirche und sagte gelassen: „Mein Auftraggeber hat es nicht eilig.“
W M | Der Kölner Dom ist die höchste Kirche der Welt. | falsch | Mit rund 157 Metern ist er zwar gewaltig — das Ulmer Münster etwa überragt ihn aber mit 161,5 Metern.
S U | Um wie viel Grad neigt sich der Schiefe Turm von Pisa heute ungefähr? | 4 | Grad | 25 | 1 | 30 | Weniger als zehn Grad. ; Vor der Sanierung waren es rund 5,5 Grad. ; Heute sind es weniger als fünf. | Bei der Sanierung von 1990 bis 2001 wurde der Turm um gut 40 Zentimeter aufgerichtet — seitdem gilt er für Jahrhunderte als stabil.
S H | In welchem Jahr wurde der Grundstein für Schloss Neuschwanstein gelegt? | 1869 | Jahr | 5 | 1800 | 1950 | Im 19. Jahrhundert. ; Zwei Jahre vor der Gründung des Deutschen Kaiserreichs. ; Zwischen 1865 und 1875. | König Ludwig II. erlebte die Fertigstellung nie — nur wenige Wochen nach seinem Tod 1886 wurde das Schloss für Besucher geöffnet.
O M | Sortiere diese Wolkenkratzer nach ihrer Höhe — den niedrigsten zuerst. | Empire State Building = 381 m ; Taipei 101 = 508 m ; Shanghai Tower = 632 m ; Burj Khalifa = 828 m | Der New Yorker Klassiker von 1931 ist der kleinste. ; Taiwans Rekordturm folgt. ; Der höchste steht in Dubai. | Gemessen wird bis zur architektonischen Spitze — mit Antenne wäre das Empire State Building 443 Meter hoch.
M H | Welche DREI dieser Bauwerke wurden 2007 zu den „neuen sieben Weltwundern“ gewählt? | Petra ; Machu Picchu ; Christusstatue in Rio de Janeiro | Eiffelturm ; Stonehenge ; Freiheitsstatue | Die Wahl lief über Internet und Telefon. ; Eines ist eine Felsenstadt in Jordanien. ; Eines steht hoch über einer brasilianischen Metropole. | Außerdem gewählt wurden die Chinesische Mauer, das Kolosseum, der Taj Mahal und Chichén Itzá.
M E | Welche ZWEI dieser Bauwerke stehen in Paris? | Sacré-Cœur ; Centre Pompidou | Sagrada Família ; Big Ben ; Atomium ; Hagia Sophia | Eines ist eine weiße Basilika auf dem Montmartre. ; Das andere hat bunte Rohre an der Fassade. ; In derselben Stadt steht der Eiffelturm. | Das Centre Pompidou trägt seine Rohre außen — farbig nach Funktion, etwa Blau für Luft und Grün für Wasser.
C E | Welches Berliner Wahrzeichen trägt oben eine Quadriga? | Brandenburger Tor | Siegessäule ; Reichstagsgebäude ; Rotes Rathaus | Es ist ein Stadttor. ; Es steht am Pariser Platz. ; Es war lange Symbol der deutschen Teilung. | Die Quadriga zeigt eine Göttin im Wagen mit vier Pferden — Napoleon ließ sie 1806 als Beute nach Paris bringen.
C M | Wie nennt man die oft fratzenhaften Figuren an gotischen Kirchen, die Regenwasser vom Dach ableiten? | Wasserspeier | Kapitelle ; Strebepfeiler ; Rosetten | Sie sitzen hoch oben an der Dachkante. ; Oft haben sie die Gestalt von Dämonen oder Tieren. ; Aus ihrem Maul fließt bei Regen Wasser. | Auf Englisch heißen sie „Gargoyles“ — ihre Fratzen sollten der Legende nach böse Geister vom Gotteshaus fernhalten.
C H | Welches Schloss ließ König Ludwig II. nach dem Vorbild von Versailles errichten? | Schloss Herrenchiemsee | Schloss Neuschwanstein ; Schloss Nymphenburg ; Schloss Hohenschwangau | Es steht auf einer Insel. ; Die Insel liegt im „Bayerischen Meer“. ; Auch hier gibt es einen prächtigen Spiegelsaal. | Das Neue Schloss Herrenchiemsee blieb unvollendet — Ludwig II. wohnte dort nur wenige Tage.
C U | Welcher Architekt entwarf das Chrysler Building in New York? | William Van Alen | Raymond Hood ; Cass Gilbert ; Louis Sullivan | Das Gebäude wurde 1930 fertig. ; Seine Spitze ist mit Edelstahl verkleidet. ; Sein Rivale baute gleichzeitig an der Wall Street. | Van Alen ließ die Turmspitze heimlich im Inneren zusammenbauen und dann ausfahren — so überholte das Chrysler Building das Hochhaus 40 Wall Street.

@ comics_graphic_novels
E E | Welche Bildergeschichte ist hier gesucht? | 👦👦🐔🍞 | Max und Moritz | Hänsel und Gretel ; Tim und Struppi ; Fix und Foxi | Zwei Lausbuben spielen üble Streiche. ; Sie stehlen der Witwe Bolte die Brathühner. ; Der Autor heißt Wilhelm Busch. | Wilhelm Buschs Geschichte von 1865 endet böse: Die beiden werden in der Mühle geschrotet und vom Federvieh gefressen.
E E | Welcher Comic ist hier gesucht? | 👦🐕🚀🌕 | Tim und Struppi | Asterix ; Lucky Luke ; Spirou und Fantasio | Der Held ist ein junger Reporter. ; Sein Hund ist weiß. ; Er landete im Comic schon Anfang der 1950er auf dem Mond. | Hergés Zweiteiler „Reiseziel Mond“ und „Schritte auf dem Mond“ erschien 1953 und 1954 als Album — 15 Jahre vor Apollo 11.
E E | Welche Comicfigur ist hier gesucht? | 💪🥫🥬⚓ | Popeye | Käpt'n Blaubär ; Hägar der Schreckliche ; Captain Haddock | Er ist Seemann. ; Er raucht Pfeife. ; Eine Dose Spinat macht ihn bärenstark. | Popeye erschien 1929 zum ersten Mal im Comicstrip „Thimble Theatre“ von E. C. Segar.
W E | Batman besitzt übermenschliche Superkräfte. | falsch | Bruce Wayne hat keine Superkräfte — er setzt auf Training, Intelligenz, Technik und sehr viel Geld.
W H | Der Hulk war bei seinem allerersten Comic-Auftritt 1962 grau statt grün. | wahr | Weil das Grau im Druck ungleichmäßig aussah, wurde der Hulk schon ab der zweiten Ausgabe grün.
W E | Japanische Mangas liest man traditionell von rechts nach links. | wahr | Wie im Japanischen üblich beginnt man „hinten“ — viele deutsche Ausgaben behalten diese Leserichtung bei.
S M | In welchem Jahr hatte Batman seinen ersten Comic-Auftritt? | 1939 | Jahr | 3 | 1900 | 1990 | Ein Jahr nach Superman. ; Kurz vor dem Zweiten Weltkrieg. ; Ende der 1930er. | Batman erschien im Mai 1939 in „Detective Comics“ Nr. 27 — erdacht von Bob Kane und Bill Finger.
S U | In welchem Jahr erschien der erste „Peanuts“-Comicstrip von Charles M. Schulz? | 1950 | Jahr | 3 | 1900 | 2000 | Mitte des 20. Jahrhunderts. ; Wenige Jahre nach dem Zweiten Weltkrieg. ; Eine runde Jahreszahl. | Schulz zeichnete die Peanuts fast 50 Jahre lang allein — der letzte Sonntagsstrip erschien am Tag nach seinem Tod im Februar 2000.
O H | Sortiere diese Manga-Serien nach ihrem Start in Japan — die älteste zuerst. | Dragon Ball = 1984 ; Detektiv Conan = 1994 ; One Piece = 1997 ; Naruto = 1999 | Son Goku war zuerst da. ; Der geschrumpfte Detektiv startete Mitte der 1990er. ; Der Ninja kam als Letzter. | „Detektiv Conan“ und „One Piece“ laufen seit den 1990ern ohne Pause weiter (Stand 2024).
M E | Welche DREI dieser Superhelden stammen aus dem Hause Marvel? | Iron Man ; Thor ; Hulk | Batman ; Wonder Woman ; Aquaman | Alle drei gehören zu den Avengers. ; Einer schwingt einen Hammer. ; Die anderen gehören zur Konkurrenz DC. | Marvel und DC sind die beiden großen US-Comicverlage — Batman, Wonder Woman und Aquaman bilden bei DC die „Justice League“.
M M | Welche ZWEI dieser Figuren leben in Entenhausen? | Gustav Gans ; Daisy Duck | Garfield ; Obelix ; Snoopy ; Lucky Luke | Beide sind Vögel. ; Einer ist ein unverschämter Glückspilz. ; Die andere ist Donalds Freundin. | Gustav Gans findet ständig Geld auf der Straße — sehr zum Ärger seines Vetters Donald Duck.
C E | Wie heißt der Hund in den „Garfield“-Comics? | Odie | Snoopy ; Pluto ; Idefix | Er ist gelb mit braunen Schlappohren. ; Er hat eine riesige, heraushängende Zunge. ; Sein Name hat nur vier Buchstaben. | Der gutmütige, aber nicht sehr helle Hund wird von Garfield ständig vom Tisch geschubst.
C M | Wie heißt der tollpatschige Hund, der Lucky Luke oft begleitet und als dümmster Hund des Westens gilt? | Rantanplan | Idefix ; Struppi ; Odie | Er soll eigentlich Gefängniswächter sein. ; Er verwechselt gern Freund und Feind. ; Sein Name klingt nach einem Trommelwirbel. | Rantanplan ist eine Parodie auf den heldenhaften Filmhund Rin Tin Tin — und bekam später sogar eine eigene Comicserie.
C M | Wie heißt der böse Zauberer, der die Schlümpfe fangen will? | Gargamel | Azrael ; Gundel Gaukeley ; Klaas Klever | Er wohnt in einer verfallenen Hütte im Wald. ; Seine Katze heißt Azrael. ; Sein Name endet auf „-mel“. | Gargamel will die Schlümpfe fangen, um aus ihnen Gold zu machen — oder sie einfach zu verspeisen.
C H | Welche Manga-Serie ist die meistverkaufte der Welt (Stand 2024)? | One Piece | Dragon Ball ; Naruto ; Detektiv Conan | Der Held will König der Piraten werden. ; Er trägt einen Strohhut. ; Sein Körper ist dehnbar wie Gummi. | Mit über 500 Millionen gedruckten Bänden hält „One Piece“ den Guinness-Rekord für die auflagenstärkste Comicreihe eines einzelnen Autors.
C U | Wer erfand den Comicstrip „Calvin und Hobbes“? | Bill Watterson | Charles M. Schulz ; Jim Davis ; Gary Larson | Der Strip lief von 1985 bis 1995. ; Hobbes ist ein Stofftiger. ; Der Zeichner lehnte jegliches Merchandising ab. | Watterson verweigerte Lizenzprodukte — Aufkleber mit dem pinkelnden Calvin sind allesamt Raubkopien.

@ theater_musical
E E | Welches Theaterstück ist hier gesucht? | 🤴💀🏰🇩🇰 | Hamlet | Macbeth ; König Lear ; Othello | Ein Prinz will den Mord an seinem Vater rächen. ; Er hält einen Totenschädel in der Hand. ; „Sein oder Nichtsein …“ | Shakespeares längstes Drama spielt auf Schloss Elsinore — dem echten Schloss Kronborg in Helsingør.
E M | Welches Theaterstück ist hier gesucht? | 🌙💤🧚🌲 | Ein Sommernachtstraum | Der Sturm ; Was ihr wollt ; Wie es euch gefällt | Es ist eine Komödie von Shakespeare. ; Elfen treiben im Wald ihr Unwesen. ; Ein Handwerker bekommt einen Eselskopf. | Mendelssohns Bühnenmusik zum Stück enthält den berühmten Hochzeitsmarsch, zu dem bis heute unzählige Paare heiraten.
E H | Welches Musical ist hier gesucht? | 🧛🩸💃🏰 | Tanz der Vampire | Dracula ; Elisabeth ; Das Phantom der Oper | Es spielt in Transsilvanien. ; Ein Professor jagt mit seinem Assistenten Vampire. ; Es basiert auf einem Film von Roman Polanski. | Das Musical mit Musik von Jim Steinman wurde 1997 in Wien uraufgeführt — „Totale Finsternis“ basiert auf seinem Hit „Total Eclipse of the Heart“.
W U | Shakespeares Globe Theatre brannte 1613 während einer Vorstellung ab. | wahr | Bei „Heinrich VIII.“ setzte eine Theaterkanone das Strohdach in Brand — verletzt wurde niemand ernsthaft, nur einem Mann fing die Hose Feuer.
W H | Das ABBA-Musical „Mamma Mia!“ wurde in Stockholm uraufgeführt. | falsch | Die Uraufführung fand 1999 im Londoner West End statt — auf den Tag genau 25 Jahre nach ABBAs ESC-Sieg mit „Waterloo“.
W M | Andrew Lloyd Webber komponierte das Musical „Les Misérables“. | falsch | Die Musik stammt von Claude-Michel Schönberg — Lloyd Webber schrieb unter anderem „Cats“ und „Das Phantom der Oper“.
S M | In welchem Jahr wurde William Shakespeare geboren? | 1564 | Jahr | 3 | 1450 | 1700 | Im 16. Jahrhundert. ; Im selben Jahr wie Galileo Galilei. ; Zwischen 1560 und 1570. | Shakespeare wurde im April 1564 in Stratford-upon-Avon getauft — sein genauer Geburtstag ist unbekannt.
S H | In welchem Jahr wurde das Opernhaus von Sydney eröffnet? | 1973 | Jahr | 3 | 1900 | 2010 | In den 1970ern. ; Queen Elizabeth II. eröffnete es persönlich. ; Nach 14 Jahren Bauzeit. | Geplant waren vier Jahre Bauzeit — es wurden 14, und die Kosten stiegen auf etwa das Vierzehnfache.
S U | Wie alt wurde Molière, der 1673 kurz nach einer Vorstellung seines Stücks „Der eingebildete Kranke“ starb? | 51 | Jahre | 15 | 20 | 90 | Er starb mitten im Berufsleben. ; Älter als 40. ; Er wurde nicht 60. | Molière spielte selbst die Titelrolle des Hypochonders — er brach auf der Bühne zusammen und starb wenige Stunden später.
O U | Sortiere diese Shakespeare-Dramen nach ihrer Entstehung — das früheste zuerst. | Romeo und Julia = um 1595 ; Hamlet = um 1600 ; Macbeth = um 1606 ; Der Sturm = um 1611 | Die Liebestragödie aus Verona ist die früheste. ; Der Dänenprinz folgt um die Jahrhundertwende. ; Das letzte Stück spielt auf einer Zauberinsel. | „Der Sturm“ gilt als Shakespeares Abschied von der Bühne — sein Zauberer Prospero bricht am Ende seinen Stab.
O M | Welches Musical kam zuerst an den Broadway? Bringe sie in die richtige Reihenfolge — beginne mit dem frühesten. | My Fair Lady = 1956 ; Hair = 1968 ; Chicago = 1975 ; Hamilton = 2015 | Eliza Doolittle lernt zuerst sprechen. ; Das Hippie-Musical folgt Ende der 1960er. ; Das Hip-Hop-Musical ist das jüngste. | „Hamilton“ erzählt die Geschichte der US-Gründerväter mit Rap und Hip-Hop — gespielt von einem überwiegend nicht-weißen Ensemble.
M H | Welche ZWEI dieser Theaterstücke schrieb Friedrich Dürrenmatt? | Die Physiker ; Der Besuch der alten Dame | Biedermann und die Brandstifter ; Andorra ; Der Hauptmann von Köpenick ; Mutter Courage und ihre Kinder | Der Autor war Schweizer. ; Eines spielt in einem Irrenhaus. ; Im anderen kehrt eine Milliardärin in ihr Heimatdorf zurück. | Die beiden anderen Schweizer Klassiker „Biedermann und die Brandstifter“ und „Andorra“ stammen von Max Frisch.
C E | Wie nennt man die Person, die bei einer Inszenierung die künstlerische Leitung hat und den Schauspielern Anweisungen gibt? | Regisseur | Souffleur ; Intendant ; Inspizient | Die Person sitzt bei Proben im Zuschauerraum. ; Sie entwickelt das Konzept der Aufführung. ; Beim Film gibt es sie auch. | Der Intendant leitet dagegen das ganze Theater, der Inspizient sorgt hinter der Bühne für den reibungslosen Ablauf.
C M | Welches Musical spielt im Berlin der frühen 1930er-Jahre im „Kit Kat Klub“? | Cabaret | Chicago ; Evita ; Hair | Die Hauptfigur heißt Sally Bowles. ; Ein Conférencier begrüßt das Publikum mit „Willkommen, Bienvenue, Welcome“. ; Liza Minnelli spielte die Hauptrolle im Film von 1972. | Das Musical von Kander und Ebb basiert auf den Berlin-Erzählungen von Christopher Isherwood.
C H | Wer komponierte die Oper „Der Rosenkavalier“? | Richard Strauss | Johann Strauss (Sohn) ; Richard Wagner ; Gustav Mahler | Die Oper wurde 1911 in Dresden uraufgeführt. ; Das Libretto schrieb Hugo von Hofmannsthal. ; Der Komponist schrieb auch „Also sprach Zarathustra“. | Die Oper spielt im Wien Maria Theresias — mit Walzern, die es damals noch gar nicht gab.
C U | Wie heißt der Kobold, der in Shakespeares „Ein Sommernachtstraum“ mit einem Liebessaft Verwirrung stiftet? | Puck | Ariel ; Caliban ; Oberon | Er dient dem Elfenkönig. ; Er wird auch „Robin Goodfellow“ genannt. ; Sein Name hat nur vier Buchstaben. | Puck verwechselt die Liebenden — Ariel und Caliban stammen dagegen aus Shakespeares „Der Sturm“.

@ maerchen_sagen
E E | Welches Märchen ist hier gesucht? | 👧⭐💰 | Die Sterntaler | Frau Holle ; Das Mädchen mit den Schwefelhölzern ; Hans im Glück | Ein armes Mädchen verschenkt alles, was es hat. ; Zuletzt gibt es sogar sein Hemdchen her. ; Dann fallen Sterne als Silbermünzen vom Himmel. | Das kurze Grimm-Märchen belohnt reine Selbstlosigkeit — das Mädchen bekommt dazu ein neues Hemd aus feinstem Leinen.
E E | Welches Märchen ist hier gesucht? | 👸🛏️🛏️🛏️🟢 | Die Prinzessin auf der Erbse | Dornröschen ; Die Schneekönigin ; Frau Holle | Ein Prinz sucht eine echte Prinzessin. ; Sie schläft auf einem riesigen Matratzenstapel. ; Das Märchen stammt von Hans Christian Andersen. | Obwohl zwanzig Matratzen und zwanzig Eiderdaunenbetten auf der Erbse lagen, bekam die Prinzessin blaue Flecken.
E H | Welches Märchen ist hier gesucht? | 🎣🐟👵🏰 | Vom Fischer und seiner Frau | Der Froschkönig ; Die kleine Meerjungfrau ; Hans im Glück | Ein armer Mann fängt einen verwunschenen Butt. ; Seine Frau wünscht sich immer mehr. ; Am Ende sitzen beide wieder in ihrer alten Hütte. | Das Märchen wurde auf Plattdeutsch aufgeschrieben — der Butt erfüllt Ilsebill fast jeden Wunsch, bis sie werden will wie der liebe Gott.
W H | In der Grimm-Fassung von „Aschenputtel“ schneiden sich die Stiefschwestern Zeh und Ferse ab, damit der Schuh passt. | wahr | Die Tauben verraten den Betrug: „Rucke di guck, rucke di guck, Blut ist im Schuck.“
W E | Im Märchen „Hans im Glück“ wird Hans am Ende steinreich. | falsch | Hans tauscht seinen Goldklumpen so lange ein, bis er nichts mehr hat — und fühlt sich trotzdem als glücklichster Mensch der Welt.
S M | Wie viele Jahre dauerte der Trojanische Krieg laut der griechischen Sage? | 10 | Jahre | 20 | 1 | 50 | Er dauerte sehr lange. ; Mehr als fünf Jahre. ; Eine runde Zahl. | Erst im letzten Kriegsjahr brachte die List mit dem hölzernen Pferd den Griechen den Sieg.
S H | In welchem Jahr wurde Hans Christian Andersen geboren? | 1805 | Jahr | 3 | 1700 | 1900 | Anfang des 19. Jahrhunderts. ; Im Jahr der Schlacht von Austerlitz. ; Zwischen 1800 und 1810. | Andersen kam in Odense als Sohn eines armen Schuhmachers zur Welt — sein Geburtstag, der 2. April, ist heute Internationaler Kinderbuchtag.
O U | Sortiere diese Märchenerzähler nach dem Erscheinen ihrer ersten Märchensammlung — den frühesten zuerst. | Charles Perrault = 1697 ; Brüder Grimm = 1812 ; Wilhelm Hauff = 1825/26 ; Hans Christian Andersen = 1835 | Der Franzose war mehr als ein Jahrhundert früher dran. ; Die „Kinder- und Hausmärchen“ folgten im frühen 19. Jahrhundert. ; Der Däne veröffentlichte zuletzt. | Perrault schrieb am Hof Ludwigs XIV. — viele seiner Stoffe wie „Aschenputtel“ und „Rotkäppchen“ tauchen später auch bei den Grimms auf.
M M | Welche DREI dieser Ritter gehören zur Tafelrunde von König Artus? | Lancelot ; Parzival ; Gawain | Siegfried ; Beowulf ; Robin Hood | Alle drei sitzen in Camelot am runden Tisch. ; Einer verliebt sich in Königin Guinevere. ; Die falschen stammen aus der Nibelungensage, einem altenglischen Epos und der englischen Volkssage. | Wolfram von Eschenbachs „Parzival“ um 1200 zählt zu den wichtigsten Werken der mittelhochdeutschen Literatur.
C E | Was isst Schneewittchen, bevor es wie tot umfällt? | Einen vergifteten Apfel | Eine vergiftete Birne ; Ein Stück Kuchen ; Eine Pflaume | Die böse Königin verkleidet sich als Bäuerin. ; Die Frucht ist halb rot, halb weiß. ; Nur die rote Hälfte ist giftig. | Vorher hatte es die Königin schon mit einem Schnürriemen und einem giftigen Kamm versucht.
C E | Wie heißt das geflügelte Pferd der griechischen Sage? | Pegasus | Bukephalos ; Rosinante ; Iltschi | Es entsprang dem Hals der Medusa. ; Der Held Bellerophon ritt auf ihm. ; Heute ist es auch ein Sternbild. | Pegasus entstieg dem Blut der Medusa, als Perseus ihr den Kopf abschlug.
C E | Welcher junge Mann fliegt in der griechischen Sage mit Flügeln aus Federn und Wachs zu nah an die Sonne? | Ikarus | Dädalus ; Perseus ; Jason | Sein Vater war ein genialer Erfinder. ; Beide flohen so von der Insel Kreta. ; Das Wachs schmolz, und er stürzte ins Meer. | Sein Vater Dädalus hatte die Flügel gebaut — und ihn gewarnt, weder zu hoch noch zu tief zu fliegen.
C H | Wie heißt das achtbeinige Pferd des nordischen Gottes Odin? | Sleipnir | Grani ; Fenrir ; Skinfaxi | Es ist das schnellste Pferd der Götterwelt. ; Seine Mutter ist der Gott Loki in Stutengestalt. ; Der Name bedeutet etwa „der Gleitende“. | Loki hatte sich in eine Stute verwandelt und brachte Sleipnir zur Welt — eines der kuriosesten Kapitel der nordischen Mythologie.
C U | In welcher Stadt beginnt die Deutsche Märchenstraße? | Hanau | Kassel ; Marburg ; Göttingen | Hier wurden die Brüder Grimm geboren. ; Die Stadt liegt in Hessen am Main. ; Auf dem Marktplatz steht ein großes Grimm-Denkmal. | Die Ferienstraße führt rund 600 Kilometer von hier bis nach Bremen zu den Stadtmusikanten.
"""
