"""Extra questions, wave 2: Kurioses & Mixed (format: see tools/content/merge_extra.py)."""
KAT = "kurioses_mixed"
REGION = "global"
DATA = r"""
@ schaetzmeister
S M | Wie viele Augen hat ein normaler Spielwürfel insgesamt, wenn man alle sechs Seiten zusammenzählt? | 21 | Augen | 15 | 6 | 60 | Mehr als 15. ; Weniger als 30. ; Gegenüberliegende Seiten ergeben zusammen immer 7. | Weil gegenüberliegende Seiten immer sieben ergeben, sind es genau 3 × 7 = 21 Augen.
S H | Aus wie vielen Steinen besteht ein klassisches Dominospiel (Doppel-Sechs)? | 28 | Steine | 15 | 5 | 100 | Mehr als 20. ; Weniger als 40. ; Jede Zahlenpaarung von 0 bis 6 kommt genau einmal vor. | Von Doppel-Null bis Doppel-Sechs gibt es genau 28 verschiedene Paarungen — jede steckt einmal im Spiel.
S E | Mit wie vielen Spielsteinen startet jeder Spieler beim Mühlespiel? | 9 | Steine | 20 | 2 | 30 | Weniger als zwölf. ; Mehr als fünf. ; Eine ungerade Zahl. | Wer nur noch zwei Steine hat, hat verloren — mit drei Steinen darf man dafür beliebig „springen“.
S U | Wie viele Zentimeter breit ist eine normale Bankkarte oder Kreditkarte? | 8.56 | cm | 10 | 3 | 20 | Weniger als zehn Zentimeter. ; Mehr als sieben Zentimeter. ; Das Format heißt ID-1 und gilt weltweit. | Das Scheckkartenformat misst 85,60 × 53,98 Millimeter — auch der deutsche Personalausweis hat genau diese Größe.
S E log | Wie viele Kilogramm wiegt ein Kubikmeter Wasser? | 1000 | kg | 15 | 100 | 10000 | Mehr als 500 Kilogramm. ; Weniger als zwei Tonnen. ; Ein Kubikmeter fasst 1.000 Liter. | Ursprünglich war das Kilogramm sogar als Masse eines Liters Wasser festgelegt worden.
S H | Wie viele Gramm wiegt ein einzelnes Blatt normales DIN-A4-Druckerpapier mit 80 g/m²? | 5 | Gramm | 20 | 1 | 50 | Weniger als zehn Gramm. ; Ein DIN-A4-Blatt ist ein Sechzehntel Quadratmeter. ; Zwischen vier und sechs Gramm. | Ein A0-Bogen hat genau einen Quadratmeter — A4 ist davon ein Sechzehntel, also 80 ÷ 16 = 5 Gramm.
S M | Mit wie vielen Steinen spielt jeder Spieler beim Backgammon? | 15 | Steine | 20 | 3 | 50 | Mehr als zehn. ; Weniger als 20. ; Eine ungerade Zahl. | Backgammon gehört zu den ältesten Brettspielen der Welt — Vorläufer spielte man schon vor Jahrtausenden in Mesopotamien und Persien.
S E | Wie viele Spielfiguren hat jeder Spieler bei „Mensch ärgere Dich nicht“? | 4 | Figuren | 25 | 1 | 12 | Weniger als sechs. ; Mehr als zwei. ; Zu Beginn stehen alle im eigenen Häuschen. | Josef Friedrich Schmidt erfand das Spiel 1907/08 — bekannt wurde es, weil er im Ersten Weltkrieg Tausende Exemplare an Lazarette verschenkte.
S U log | Wie viele verschiedene Tippreihen gibt es beim Lotto „6 aus 49“ (ohne Superzahl)? | 13983816 | Tippreihen | 30 | 1000 | 10000000000 | Mehr als eine Million. ; Weniger als 100 Millionen. ; Knapp 14 Millionen. | Wer jede Woche einen Tipp abgibt, bräuchte im Schnitt rund 270.000 Jahre für sechs Richtige — mit Superzahl sogar zehnmal so lange.
O M | Sortiere diese Zahlwörter nach ihrem Wert — den kleinsten zuerst. | Million = 10⁶ ; Milliarde = 10⁹ ; Billion = 10¹² ; Billiarde = 10¹⁵ | Die Million kennt jeder. ; Nach der Million kommt die Milliarde. ; Die „-arde“ ist immer tausendmal größer als die „-ion“ davor. | Vorsicht beim Übersetzen: Das englische „billion“ ist nur eine deutsche Milliarde.
O M | Sortiere diese Bälle nach ihrem Gewicht — den leichtesten zuerst. | Tischtennisball = 2,7 g ; Golfball = ca. 46 g ; Tennisball = ca. 58 g ; Fußball = ca. 430 g | Der Plastikball wiegt fast nichts. ; Der Golfball ist kleiner, aber fast so schwer wie der Tennisball. ; Der größte Ball ist auch der schwerste. | Ein Tischtennisball wiegt weniger als ein Teelöffel Zucker.
O M | Sortiere diese Spiele nach der Zahl der Felder oder Punkte auf ihrem Spielbrett — die wenigsten zuerst. | Tic-Tac-Toe = 9 Felder ; Mühle = 24 Punkte ; Schach = 64 Felder ; Go = 361 Punkte | Beim Kinderspiel mit Kreuzen und Kreisen sind es am wenigsten. ; Beim Mühlespiel zieht man auf Punkten statt Feldern. ; Das asiatische Brettspiel hat 19 × 19 Linien. | Auf dem Go-Brett gibt es mehr mögliche Stellungen, als das sichtbare Universum Atome hat.
C E | Scherzfrage: In wie vielen Monaten des Jahres gibt es einen 28. Tag? | In allen zwölf | Nur im Februar ; In zwei Monaten ; In keinem | Achte genau auf die Formulierung. ; Es geht nicht darum, welcher Monat genau so lang ist. ; Jeder Monat hat mindestens so viele Tage. | Nur der Februar hat genau 28 Tage — einen 28. Tag haben aber alle zwölf Monate.
C H | Wie viele Stück sind ein „Schock“? | 60 | 12 ; 20 ; 144 | Es ist ein altes Zählmaß. ; Es ist mehr als ein Dutzend. ; Es sind fünf Dutzend. | Alte Zählmaße: Ein Dutzend sind 12, ein Schock 60 und ein Gros 144 Stück — daher kennt man noch den „Schock Eier“.
M M | Welche ZWEI dieser Längen sind größer als ein Meter? | Eine Seemeile ; Ein Klafter | Ein Yard ; Ein Fuß ; Eine Elle ; Ein Zoll | Eine ist ein Maß der Seefahrt. ; Die andere entspricht grob der Spannweite ausgestreckter Arme. ; Ein Yard misst gut 91 Zentimeter. | Eine Seemeile misst 1.852 Meter, ein Klafter je nach Region rund 1,7 bis 1,9 Meter.
W M | Ein Tag hat mehr Minuten als eine Stunde Sekunden. | falsch | Ein Tag hat 1.440 Minuten, eine Stunde aber 3.600 Sekunden — die Stunde gewinnt deutlich.

@ stimmts_oder_quatsch
W M | Nach dem Essen muss man eine Stunde warten, bevor man schwimmen geht — sonst droht ein gefährlicher Krampf. | falsch | Für diese Warnung gibt es keine Belege — mit sehr vollem Bauch schwimmt es sich höchstens unbequemer.
W E | Wer mit nassen Haaren nach draußen geht, bekommt davon eine Erkältung. | falsch | Erkältungen lösen Viren aus — kalte, nasse Haare allein machen niemanden krank, auch wenn es unangenehm ist.
W M | Die Farbe Orange wurde nach der Frucht benannt — nicht umgekehrt. | wahr | Der Name der Frucht geht auf das Sanskrit-Wort „naranga“ zurück — als Farbwort wurde „Orange“ erst viel später gebräuchlich.
W M | Die Mona Lisa hat keine sichtbaren Augenbrauen. | wahr | Ob Leonardo sie nie malte oder ob sie bei früheren Reinigungen verblassten, ist umstritten — mit bloßem Auge sieht man jedenfalls keine.
W H | Das Wort „Muskel“ bedeutet ursprünglich „Mäuschen“. | wahr | Es kommt vom lateinischen „musculus“, der Verkleinerung von „mus“ (Maus) — ein zuckender Muskel erinnerte an eine flinke Maus unter der Haut.
W M | Ein Tag auf dem Mars ist nur etwa 40 Minuten länger als ein Tag auf der Erde. | wahr | Ein Marstag — „Sol“ genannt — dauert rund 24 Stunden und 39 Minuten. Rover-Teams auf der Erde arbeiten deshalb zeitweise nach Mars-Zeit.
W E | Schweine schwitzen besonders stark. | falsch | Schweine haben kaum funktionierende Schweißdrüsen — deshalb suhlen sie sich im Schlamm, um sich abzukühlen.
W M | Auf der Erde wachsen mehr Bäume, als es Sterne in der Milchstraße gibt. | wahr | Forscher schätzen rund drei Billionen Bäume — die Milchstraße hat dagegen „nur“ etwa 100 bis 400 Milliarden Sterne.
W E | Wer Nasenbluten hat, sollte den Kopf in den Nacken legen. | falsch | Besser ist es, den Kopf leicht nach vorn zu beugen und die Nasenflügel zusammenzudrücken — sonst läuft das Blut in den Rachen.
W E | Den Mond kann man nie am Tag sehen, sondern nur nachts. | falsch | Der Mond steht oft auch tagsüber am Himmel — er wirkt dann nur blasser, weil das Sonnenlicht alles überstrahlt.
C E | Welche Farbe hat der Flugdatenschreiber, die sogenannte „Black Box“, in Flugzeugen tatsächlich? | Orange | Schwarz ; Silber ; Dunkelblau | Der Name führt in die Irre. ; Die Farbe soll in Trümmern gut auffallen. ; Es ist eine grelle Signalfarbe. | Der Kasten ist meist leuchtend orange und mit Reflektorstreifen beklebt — damit Ermittler ihn nach einem Absturz schnell finden.
C H | Welche Farbe hatten viele Karotten, bevor sich im 17. Jahrhundert die orange Sorte durchsetzte? | Lila | Blau ; Grün ; Rosa | Die Urform stammt aus Zentralasien. ; Die Farbe ähnelt der von Rotkohl. ; Als „Urmöhre“ gibt es sie heute wieder zu kaufen. | Die orange Karotte wurde in den Niederlanden gezüchtet — dass sie dem Haus Oranien zu Ehren entstand, ist allerdings nur eine Legende.
C U | Wie nennt man das Phänomen, dass man etwas neu Gelerntes plötzlich überall wiederzuerkennen glaubt? | Baader-Meinhof-Phänomen | Mandela-Effekt ; Dunning-Kruger-Effekt ; Placebo-Effekt | Man lernt ein neues Wort — und liest es am nächsten Tag gleich zweimal. ; Fachleute sprechen auch von Frequenzillusion. ; Der Name geht auf eine deutsche Terrorgruppe zurück. | Ein Zeitungsleser in Minnesota bemerkte 1994, dass ihm der Name der RAF-Gruppe plötzlich ständig begegnete — so bekam das Phänomen seinen kuriosen Namen.
M M | Welche ZWEI dieser Erfindungen entstanden durch einen Zufall? | Penicillin ; Mikrowellenherd | Buchdruck ; Telefon ; Glühbirne ; Dampfmaschine | Bei der einen wuchs Schimmel in einer vergessenen Bakterienschale. ; Bei der anderen schmolz ein Schokoriegel in der Hosentasche. ; Beide stammen aus dem 20. Jahrhundert. | Percy Spencer bemerkte 1945 an einem Radargerät, dass sein Schokoriegel schmolz — daraus wurde der Mikrowellenherd.
M H | Welche DREI dieser Dinge sind nach einer Person benannt? | Sandwich ; Saxofon ; Diesel | Hamburger ; Jeans ; Tomate | Einer war ein britischer Graf. ; Einer war ein belgischer Instrumentenbauer. ; Einer war ein deutscher Ingenieur. | Der Hamburger ist nach der Stadt Hamburg benannt, die Jeans nach der Stadt Genua — und die Tomate nach dem aztekischen Wort „tomatl“.
O U | Was geschah zuerst? Bringe diese Ereignisse der Menschheitsgeschichte in die richtige Reihenfolge. | Bau der Cheops-Pyramide = um 2560 v. Chr. ; Letzte Mammuts auf der Wrangelinsel = vor rund 4.000 Jahren ; Gründung Roms laut Sage = 753 v. Chr. ; Tod Kleopatras = 30 v. Chr. | Die Pyramide ist das älteste Ereignis. ; Als die Pyramiden schon standen, lebten noch Mammuts. ; Kleopatra ist das jüngste. | Auf der abgelegenen Wrangelinsel im Nordpolarmeer überlebten Wollhaarmammuts noch Jahrhunderte nach dem Bau der großen Pyramiden.
S M | Wie viele Jahre seines Lebens verschläft ein Mensch, der 75 Jahre alt wird, ungefähr? | 25 | Jahre | 20 | 5 | 60 | Mehr als zehn Jahre. ; Rund ein Drittel des Lebens. ; Weniger als 30 Jahre. | Bei rund acht Stunden pro Nacht verbringt man etwa ein Drittel des Lebens im Bett — Neugeborene schlafen sogar bis zu 17 Stunden am Tag.

@ verrueckte_gesetze
C E | Wo bildet man auf einer zweispurigen Autobahn bei Stau die Rettungsgasse? | Zwischen der linken und der rechten Spur | Auf dem Standstreifen ; Ganz rechts am Fahrbahnrand ; Gar nicht, das ist freiwillig | Man muss sie schon bei stockendem Verkehr bilden. ; Einsatzfahrzeuge sollen mittig durchfahren können. ; Wer links fährt, weicht nach links aus. | Bei mehr Spuren gilt: Die Gasse entsteht immer zwischen der ganz linken Spur und allen anderen — wer sie nicht bildet, riskiert Bußgeld und Fahrverbot.
C M | Was ist in Rom seit 2019 an der Spanischen Treppe verboten? | Sich auf die Stufen zu setzen | Dort zu fotografieren ; Die Treppe barfuß zu betreten ; Dort Eis zu verkaufen | Touristen wurden mit Bußgeldern überrascht. ; Früher war die Treppe ein beliebter Rastplatz. ; Es geht um eine ganz alltägliche Tätigkeit auf Treppen. | Wer sich trotzdem hinsetzt, riskiert eine Geldstrafe — die Stadt will das Denkmal vor Schmutz und Abnutzung schützen.
C U | Was müssen Autofahrer in Frankreich seit 2012 laut Gesetz im Auto mitführen — auch wenn es dafür inzwischen kein Bußgeld mehr gibt? | Einen Alkoholtester | Einen Feuerlöscher ; Ein Ersatzlenkrad ; Eine gedruckte Straßenkarte | Das Gerät misst etwas im Atem. ; Es geht um Promille. ; Man pustet hinein. | Die Pflicht besteht weiter, doch das geplante Bußgeld von elf Euro wurde nie dauerhaft durchgesetzt.
C H | Welches Land schrieb 2008 als erstes der Welt eigene Rechte der Natur in seine Verfassung? | Ecuador | Bolivien ; Neuseeland ; Costa Rica | Das Land liegt in Südamerika. ; Die Galápagos-Inseln gehören dazu. ; Sein Name bedeutet „Äquator“. | Die Natur kann dort über Stellvertreter vor Gericht klagen — Neuseeland erklärte 2017 sogar einen Fluss zur juristischen Person.
C U | Wie lange muss man in Deutschland warten, bis man eine beim Fundbüro abgegebene Fundsache behalten darf, wenn sich der Eigentümer nicht meldet? | Sechs Monate | Vier Wochen ; Ein Jahr ; Drei Jahre | Die Frist beginnt mit der Anzeige des Funds. ; Es ist weniger als ein Jahr. ; Es ist ein halbes Jahr. | So regelt es Paragraf 973 des Bürgerlichen Gesetzbuchs — Funde unter zehn Euro muss man gar nicht erst anzeigen.
C H | Welche Frucht darf man in Singapur nicht mit in die U-Bahn nehmen? | Durian | Mango ; Ananas ; Papaya | Sie ist groß und stachelig. ; Ihr Geruch ist extrem stark. ; Man nennt sie auch Stinkfrucht. | Auch viele Hotels in Südostasien verbieten den „König der Früchte“ — sein Duft erinnert manche an Käse, Zwiebeln und Abwasser.
W E | Mit einem grünen Blechpfeil an der Ampel darf man in Deutschland auch bei Rot rechts abbiegen — nach vorherigem Anhalten. | wahr | Der Grünpfeil stammt aus der DDR und wurde nach der Wiedervereinigung bundesweit übernommen.
W H | In der Schweiz ist es gesetzlich verboten, nach 22 Uhr die Toilettenspülung zu betätigen. | falsch | Das ist ein Mythos — ein solches Gesetz gibt es nicht, allenfalls strenge Hausordnungen mit Regeln zur Nachtruhe.
W M | In Deutschland brauchen Kinder im Auto einen Kindersitz, bis sie zwölf Jahre alt oder 1,50 Meter groß sind. | wahr | Was zuerst erreicht wird, zählt — danach dürfen Kinder mit dem normalen Sicherheitsgurt fahren.
W M | In Dänemark dürfen Eltern ihrem Kind jeden beliebigen Vornamen geben. | falsch | Dänemark führt eine amtliche Liste genehmigter Vornamen — wer einen anderen Namen möchte, muss ihn prüfen lassen.
M E | Welche DREI dieser Dinge sind auf deutschen Autobahnen verboten? | Wenden ; Rückwärtsfahren ; Parken auf dem Seitenstreifen | Warnblinker am Stauende ; Eine Rettungsgasse bilden ; Fahren ohne Tempolimit | Alle drei gefährden den fließenden Verkehr. ; Eines davon ist selbst in der Ausfahrt tabu. ; Der Seitenstreifen ist nur für Notfälle da. | Schon wer eine Ausfahrt verpasst und zurücksetzt, riskiert Punkte in Flensburg und ein saftiges Bußgeld.
M H | Welche DREI dieser Länder haben eine allgemeine Wahlpflicht? | Australien ; Belgien ; Brasilien | Deutschland ; Frankreich ; USA | Eines liegt in Ozeanien. ; Eines ist ein kleines Königreich in Westeuropa. ; Eines ist das größte Land Südamerikas. | In Australien kostet das Fernbleiben von der Wahl ein Bußgeld — die Wahlbeteiligung liegt dort meist über 90 Prozent.
O E | Sortiere diese Höchstgeschwindigkeiten in Deutschland — die niedrigste zuerst. | Verkehrsberuhigter Bereich = Schrittgeschwindigkeit ; Tempo-30-Zone = 30 km/h ; Innerorts = 50 km/h ; Landstraße für Pkw = 100 km/h | In der „Spielstraße“ ist man am langsamsten. ; In Wohngebieten gilt oft ein Limit mit einer Drei. ; Außerhalb von Orten darf man am schnellsten fahren. | Schrittgeschwindigkeit bedeutet laut Gerichten etwa 4 bis 10 km/h — ein genauer Wert steht nicht in der Straßenverkehrs-Ordnung.
S H | Ab wie viel Promille Alkohol im Blut gilt man in Deutschland beim Autofahren als absolut fahruntüchtig? | 1.1 | Promille | 10 | 0.1 | 5 | Mehr als ein Promille. ; Weniger als 1,5 Promille. ; Knapp über einem Promille. | Ab 0,5 Promille droht bereits ein Bußgeld, ab 1,1 Promille ist es immer eine Straftat — für Fahranfänger gilt ohnehin 0,0.

@ rekorde_superlative
E E | Welches Buch ist hier gesucht? | 🍺📖🏆 | Guinness-Buch der Rekorde | Duden ; Brockhaus ; Telefonbuch | Es erscheint jedes Jahr neu. ; Es sammelt Höchstleistungen aller Art. ; Es ist nach einer irischen Brauerei benannt. | Die erste Ausgabe erschien 1955 in London und stand schon nach wenigen Monaten an der Spitze der Bestsellerliste.
E E | Welches Gebäude ist hier gesucht? | 🏙️🥇🇦🇪 | Burj Khalifa | Taipei 101 ; Shanghai Tower ; Empire State Building | Es ist das höchste Gebäude der Welt (Stand 2024). ; Es steht am Persischen Golf. ; Es steht in Dubai. | Die Spitze des Wolkenkratzers sieht man bei klarer Sicht noch aus rund 95 Kilometern Entfernung.
C E | Welches Lied gilt laut Guinness-Buch als das bekannteste Lied in englischer Sprache? | Happy Birthday to You | Jingle Bells ; Yesterday ; Auld Lang Syne | Es ist sehr kurz. ; Man singt es für eine einzelne Person. ; Dazu gibt es oft Kuchen und Kerzen. | Die Melodie stammt von den Schwestern Mildred und Patty Hill aus dem 19. Jahrhundert — ursprünglich hieß das Lied „Good Morning to All“.
C H | Welche Sprache sprechen weltweit die meisten Menschen, wenn man Mutter- und Zweitsprachler zusammenzählt (Stand 2024)? | Englisch | Mandarin-Chinesisch ; Spanisch ; Hindi | Die meisten Sprecher lernen sie als Fremdsprache. ; Sie ist die wichtigste Sprache der Luftfahrt. ; Man spricht sie in Großbritannien. | Nach Muttersprachlern liegt Mandarin vorn — zählt man Zweitsprachler mit, kommt Englisch auf rund 1,5 Milliarden Sprecher.
C H | Welches ist das flächenmäßig kleinste Land Afrikas? | Seychellen | Gambia ; São Tomé und Príncipe ; Mauritius | Es ist ein Inselstaat. ; Es liegt im Indischen Ozean. ; Die Hauptstadt heißt Victoria. | Die rund 115 Inseln sind zusammen nur etwa 455 Quadratkilometer groß — kaum mehr als halb so groß wie Hamburg.
C H | Welches unabhängige Land der Erde ist am dünnsten besiedelt? | Mongolei | Kanada ; Australien ; Island | Das Land liegt zwischen zwei Riesenstaaten. ; Viele Menschen leben dort traditionell als Nomaden. ; Die Hauptstadt ist Ulan Bator. | Auf einen Quadratkilometer kommen dort nur rund zwei Menschen — fast die Hälfte der Bevölkerung lebt in der Hauptstadt.
C U | Wo steht die nach Volumen größte Pyramide der Welt? | In Mexiko | In Ägypten ; Im Sudan ; In Peru | Sie ist größer als die Cheops-Pyramide. ; Sie ist heute von Erde und Gras bedeckt. ; Auf ihr steht eine Kirche. | Die Große Pyramide von Cholula hat eine Grundfläche von rund 450 × 450 Metern — auf ihrer Spitze thront heute eine Wallfahrtskirche.
C H | Wer lief 1954 als erster Mensch eine Meile unter vier Minuten? | Roger Bannister | Emil Zátopek ; Jesse Owens ; Paavo Nurmi | Er war ein britischer Medizinstudent. ; Der Lauf fand in Oxford statt. ; Er blieb bei 3:59,4 Minuten stehen. | Viele Experten hielten die Vier-Minuten-Meile für unmöglich — nur gut sechs Wochen später war Bannisters Rekord schon wieder gebrochen.
W H | Der Pazifik ist kleiner als die gesamte Landfläche der Erde. | falsch | Mit rund 165 Millionen Quadratkilometern ist der Pazifik größer als alle Kontinente zusammen (etwa 149 Millionen).
W M | Das Guinness-Buch der Rekorde gehört selbst zu den meistverkauften urheberrechtlich geschützten Büchern der Welt. | wahr | Seit 1955 wurden weit über 100 Millionen Exemplare in Dutzenden Sprachen verkauft.
S U | Wie viele Tage verbrachte der russische Kosmonaut Waleri Poljakow am Stück im All — bis heute Rekord (Stand 2024)? | 437 | Tage | 10 | 50 | 2000 | Mehr als ein Jahr. ; Weniger als 500 Tage. ; Rund 14 Monate. | Poljakow lebte 1994/95 auf der Raumstation Mir — als Arzt wollte er zeigen, dass Menschen einen Flug zum Mars überstehen können.
S M | Wie viele Stockwerke hat der Burj Khalifa über der Erde? | 163 | Stockwerke | 15 | 50 | 500 | Mehr als 100. ; Weniger als 200. ; Mehr als 150. | Die höchste Aussichtsplattform liegt im 148. Stock auf rund 555 Metern Höhe.
S U log | Wie viele Kilometer lang ist die Panamericana, die als längste Straße der Welt gilt? | 30000 | km | 20 | 1000 | 100000 | Mehr als 20.000 Kilometer. ; Sie verbindet Alaska mit Feuerland. ; Weniger als 50.000 Kilometer. | Nur eine rund 100 Kilometer breite Dschungellücke — der Darién Gap zwischen Panama und Kolumbien — unterbricht die Straße.
O H | Sortiere diese Hauptstädte nach ihrer Höhenlage — die tiefstgelegene zuerst. | Berlin = ca. 34 m ; Madrid = ca. 650 m ; Mexiko-Stadt = ca. 2.240 m ; Bogotá = ca. 2.640 m | Die deutsche Hauptstadt liegt fast auf Meereshöhe. ; Madrid ist die höchstgelegene Hauptstadt der EU. ; Beide lateinamerikanischen Städte liegen über 2.000 Metern. | In Bogotá kocht Wasser wegen des geringen Luftdrucks schon bei rund 91 Grad.
O U | Sortiere diese Lebewesen nach dem höchsten bekannten Alter eines Exemplars — das niedrigste zuerst. | Hauskatze = 38 Jahre ; Mensch = 122 Jahre ; Grönlandhai = rund 400 Jahre ; Islandmuschel = 507 Jahre | Das Haustier wurde am wenigsten alt. ; Jeanne Calment hält den Menschen-Rekord. ; Eine Muschel namens „Ming“ schlägt sogar den Hai. | Die Islandmuschel „Ming“ wurde 2006 vor Island gefangen — erst beim Zählen ihrer Wachstumsringe merkte man, wie alt sie war.
O H | Sortiere diese Inseln nach ihrer Fläche — die kleinste zuerst. | Sylt = ca. 99 km² ; Mallorca = ca. 3.640 km² ; Island = ca. 103.000 km² ; Grönland = ca. 2,2 Mio. km² | Die deutsche Nordseeinsel ist die kleinste. ; Die Ferieninsel im Mittelmeer folgt. ; Die größte Insel der Welt kommt zuletzt. | Grönland ist rund zwanzigmal so groß wie Island — und etwa sechsmal so groß wie Deutschland.
M H | Welche ZWEI dieser Länder sind flächenmäßig größer als die USA? | Russland ; Kanada | Brasilien ; Australien ; Indien ; Argentinien | Beide liegen weit im Norden. ; Eines ist das größte Land der Erde. ; Das andere ist der direkte Nachbar der USA. | Die USA liegen mit rund 9,8 Millionen Quadratkilometern je nach Zählweise knapp vor China auf Platz drei.
M M | Welche ZWEI dieser Länder haben mehr Einwohner als Deutschland (Stand 2024)? | Japan ; Nigeria | Frankreich ; Großbritannien ; Kanada ; Spanien | Eines liegt in Ostasien. ; Das andere ist das bevölkerungsreichste Land Afrikas. ; Deutschland hat rund 84 Millionen Einwohner. | Nigeria hat über 220 Millionen Einwohner — Frankreich und Großbritannien kommen jeweils nur auf knapp 70 Millionen.

@ wer_bin_ich
E E | Welche Person ist hier gesucht? | 👑🐕🫖🇬🇧 | Elizabeth II. | Queen Victoria ; Maria Stuart ; Königin Silvia | Ich regierte über 70 Jahre lang. ; Meine Lieblingshunde waren Corgis. ; Mein ältester Sohn heißt Charles. | Elizabeth II. war von 1952 bis 2022 Königin — länger als jeder andere britische Monarch.
E M | Welche Person ist hier gesucht? | 🎩🐇⛓️🔓 | Harry Houdini | David Copperfield ; Siegfried & Roy ; Uri Geller | Ich war der berühmteste Entfesselungskünstler der Welt. ; Ich befreite mich aus Zwangsjacken und Wassertanks. ; Geboren wurde ich 1874 in Budapest. | Houdini hieß eigentlich Erik Weisz — später entlarvte er auch falsche Hellseher und Geisterbeschwörer.
E M | Welche Person ist hier gesucht? | 🛁💡🗣️🏛️ | Archimedes | Pythagoras ; Euklid ; Aristoteles | Ich lebte im antiken Syrakus. ; In der Badewanne kam mir eine geniale Idee. ; Dabei soll ich „Heureka!“ gerufen haben. | Der Legende nach entdeckte Archimedes beim Baden das Prinzip des Auftriebs — und rannte vor Freude nackt durch die Stadt.
E M | Welche Person ist hier gesucht? | 👑💍6️⃣🪓 | Heinrich VIII. | Richard Löwenherz ; Ludwig XIV. ; Karl der Große | Ich war König von England. ; Ich war sechsmal verheiratet. ; Zwei meiner Frauen ließ ich hinrichten. | Weil der Papst seine erste Ehe nicht annullierte, brach Heinrich VIII. mit Rom und gründete die Kirche von England.
E H | Welche Person ist hier gesucht? | 👗🖤5️⃣🇫🇷 | Coco Chanel | Christian Dior ; Yves Saint Laurent ; Karl Lagerfeld | Ich war eine französische Modeschöpferin. ; Ich machte das „kleine Schwarze“ berühmt. ; Mein bekanntestes Parfum trägt eine Nummer. | Gabrielle „Coco“ Chanel befreite die Frauen vom Korsett — ihr Parfum „No. 5“ kam 1921 auf den Markt.
E M | Welche Person ist hier gesucht? | 🕳️🌌🧠🇬🇧 | Stephen Hawking | Albert Einstein ; Isaac Newton ; Carl Sagan | Ich war ein britischer Physiker. ; Ich erforschte Schwarze Löcher. ; Mein Buch „Eine kurze Geschichte der Zeit“ wurde ein Weltbestseller. | Trotz der Nervenkrankheit ALS lebte Hawking noch mehr als 50 Jahre nach der Diagnose und sprach mit einem Sprachcomputer.
E U | Welche Person ist hier gesucht? | 🛋️🧠💭🇦🇹 | Sigmund Freud | Carl Gustav Jung ; Alfred Adler ; Wilhelm Wundt | Ich lebte und arbeitete lange in Wien. ; Meine Patienten legten sich auf eine Couch. ; Ich gelte als Begründer der Psychoanalyse. | Freud nannte Träume den „Königsweg zum Unbewussten“ — 1938 floh er vor den Nationalsozialisten nach London.
C E | Ich bin eine Puppe mit langen blonden Haaren, kam 1959 auf den Markt, hatte schon über 200 Berufe und mein Freund heißt Ken. Wer bin ich? | Barbie | Sindy ; Polly Pocket ; Bratz | Ich stamme von der Firma Mattel. ; Mein voller Name ist Barbara Millicent Roberts. ; Meine Lieblingsfarbe ist Pink. | Erfinderin Ruth Handler benannte die Puppe nach ihrer Tochter Barbara — und Ken nach ihrem Sohn Kenneth.
C E | Ich zeichnete eine Maus mit großen runden Ohren, gründete ein Filmstudio und eröffnete 1955 in Kalifornien meinen ersten Freizeitpark. Wer bin ich? | Walt Disney | Walter Lantz ; Chuck Jones ; Jim Henson | Ich wurde 1901 in Chicago geboren. ; Ich gewann mehr Oscars als jeder andere Mensch. ; Mein Nachname steht heute für einen Weltkonzern. | Disneyland in Anaheim öffnete im Juli 1955 — Micky Maus sprach Walt Disney anfangs sogar selbst.
C M | Ich regierte 63 Jahre lang über Großbritannien, wurde Kaiserin von Indien, und nach mir ist ein ganzes Zeitalter benannt. Wer bin ich? | Queen Victoria | Elizabeth I. ; Maria Stuart ; Anne Boleyn | Ich lebte im 19. Jahrhundert. ; Ein Londoner Museum trägt meinen Namen und den meines Mannes. ; Viele europäische Königshäuser stammen von mir ab. | Wegen ihrer vielen Enkel auf Europas Thronen nannte man Victoria auch die „Großmutter Europas“.
C H | Ich war die einzige Frau an der Spitze der Habsburger Länder, bekam 16 Kinder und verheiratete eine Tochter mit dem späteren französischen König Ludwig XVI. Wer bin ich? | Maria Theresia | Katharina die Große ; Kaiserin Sisi ; Maria Stuart | Ich lebte im 18. Jahrhundert. ; Meine jüngste Tochter hieß Marie Antoinette. ; Ich regierte von Wien aus. | Offiziell war Kaiser ihr Mann Franz Stephan — regiert hat aber sie, und zwar vier Jahrzehnte lang.
C M | Als Pfarrer in Bad Wörishofen kurierte ich mich mit eiskaltem Wasser selbst und entwickelte daraus eine Heilmethode mit Güssen und Wassertreten. Wer bin ich? | Sebastian Kneipp | Samuel Hahnemann ; Vincenz Prießnitz ; Hildegard von Bingen | Ich lebte im 19. Jahrhundert in Bayern. ; Meine Lehre ruht auf fünf Säulen. ; Mein Nachname steckt heute in vielen Kurorten und Badezusätzen. | Kneipp soll sich durch Bäder in der eiskalten Donau von einer schweren Lungenkrankheit erholt haben — so entstand die „Kneippkur“.
C U | Ich erfand mit einem Ingenieur die Aqualunge, erkundete mit meinem Schiff „Calypso“ die Meere und trug stets eine rote Mütze. Wer bin ich? | Jacques-Yves Cousteau | Hans Hass ; Auguste Piccard ; Thor Heyerdahl | Ich war Franzose. ; Meine Filme gewannen Oscars und die Goldene Palme. ; Mein Vorname beginnt mit J. | Cousteaus Film „Die schweigende Welt“ gewann 1956 als Dokumentarfilm die Goldene Palme in Cannes.
C H | Ab 1891 unternahm ich rund 2.000 Gleitflüge mit selbstgebauten Flugapparaten — bis ich 1896 nach einem Absturz starb. Wer bin ich? | Otto Lilienthal | Ferdinand von Zeppelin ; Orville Wright ; Hans Grade | Ich stammte aus Anklam in Pommern. ; Ich gelte als erster Mensch, der wiederholt erfolgreich flog. ; Berlins früherer Flughafen Tegel trug meinen Namen. | Seine Beobachtungen am Storchenflug beschrieb er im Buch „Der Vogelflug als Grundlage der Fliegekunst“.
C U | Schon als Schüler addierte ich blitzschnell die Zahlen von 1 bis 100, und später zierte mein Porträt den 10-D-Mark-Schein. Wer bin ich? | Carl Friedrich Gauß | Gottfried Wilhelm Leibniz ; Leonhard Euler ; Bernhard Riemann | Ich war Mathematiker, Astronom und Physiker. ; Ich lebte und forschte in Göttingen. ; Man nannte mich den „Fürsten der Mathematiker“. | Die Anekdote: Der kleine Gauß rechnete 1 + 100, 2 + 99 und so weiter — 50 Paare zu je 101 ergeben 5.050.
M H | Welche ZWEI dieser Personen erhielten den Friedensnobelpreis? | Martin Luther King ; Malala Yousafzai | Mahatma Gandhi ; Albert Einstein ; Winston Churchill ; Marie Curie | Einer war US-Bürgerrechtler. ; Die andere ist die jüngste Preisträgerin aller Zeiten. ; Einer der falschen bekam den Literaturnobelpreis. | Gandhi wurde fünfmal nominiert, erhielt den Preis aber nie — Churchill bekam 1953 den Nobelpreis für Literatur.
M E | Welche ZWEI dieser Figuren sind frei erfunden und haben nie gelebt? | Pippi Langstrumpf ; Winnetou | Kleopatra ; Marco Polo ; Galileo Galilei ; Florence Nightingale | Beide stammen aus Büchern. ; Eine hat rote Zöpfe. ; Der andere ist ein Apachen-Häuptling. | Pippi erfand Astrid Lindgren, Winnetou der Schriftsteller Karl May — der den Wilden Westen nie gesehen hatte, als er die Bücher schrieb.
O M | Sortiere diese Persönlichkeiten nach ihrem Geburtsjahr — die älteste zuerst. | Leonardo da Vinci = 1452 ; Isaac Newton = 1643 ; Albert Einstein = 1879 ; Stephen Hawking = 1942 | Der Renaissance-Künstler kommt zuerst. ; Der Physiker mit dem fallenden Apfel folgt im 17. Jahrhundert. ; Der Jüngste starb erst 2018. | Hawking kam am 8. Januar 1942 zur Welt — auf den Tag genau 300 Jahre nach dem Tod von Galileo Galilei.

@ buchstaben_woerter
E E | Welche Redewendung ist hier gesucht? | 🧈👌 | Alles in Butter | Butter bei die Fische ; Sich die Butter vom Brot nehmen lassen ; Wie Butter in der Sonne | Alles ist in bester Ordnung. ; Es geht um ein Milchprodukt. ; Das Streichfett schützt hier etwas. | Eine Erklärung: Zerbrechliche Gläser wurden früher für den Transport in flüssige Butter gegossen — war sie erstarrt, konnte nichts mehr kaputtgehen.
E E | Welche Redewendung ist hier gesucht? | 🐘🍽️💥 | Wie ein Elefant im Porzellanladen | Aus einer Mücke einen Elefanten machen ; Ein Gedächtnis wie ein Elefant haben ; Einen Elefanten im Raum übersehen | Jemand benimmt sich sehr ungeschickt. ; Es geht um ein riesiges Tier. ; Zerbrechliches Geschirr ist in Gefahr. | Gemeint ist taktloses, plumpes Verhalten — echte Elefanten bewegen sich übrigens erstaunlich vorsichtig.
E E | Welche Redewendung ist hier gesucht? | ☁️7️⃣😍 | Auf Wolke sieben schweben | Aus allen Wolken fallen ; Das ist ein Buch mit sieben Siegeln ; Seine sieben Sachen packen | Man ist überglücklich. ; Oft ist man frisch verliebt. ; Es geht um etwas am Himmel und eine Zahl. | Ähnlich sagt man „im siebten Himmel sein“ — die Sieben galt schon in der Antike als Zahl der Vollkommenheit.
E E | Welche Redewendung ist hier gesucht? | 🐷🍀😅 | Schwein gehabt | Die Sau rauslassen ; Perlen vor die Säue werfen ; Den inneren Schweinehund überwinden | Man hatte unverdientes Glück. ; Ein rosa Tier gilt als Glücksbringer. ; Bei Wettkämpfen bekam der Letzte früher angeblich ein Ferkel als Trostpreis. | Der Trostpreis-Erklärung zufolge ging der Verlierer mit einem Schwein nach Hause — und hatte so doch noch etwas gewonnen.
E E | Welche Redewendung ist hier gesucht? | 🔨📌🎯 | Den Nagel auf den Kopf treffen | Auf den Putz hauen ; Etwas an den Nagel hängen ; Mit dem Kopf durch die Wand wollen | Man bringt etwas genau auf den Punkt. ; Es geht um Handwerkszeug. ; Der Schlag muss genau sitzen. | Wer den Nagel sauber auf den Kopf trifft, treibt ihn mit einem Schlag gerade ins Holz — genau das ist die Idee hinter dem Bild.
E M | Welche Redewendung ist hier gesucht? | 🔥🥣🗣️🔄 | Um den heißen Brei herumreden | Viele Köche verderben den Brei ; Sich die Finger verbrennen ; Öl ins Feuer gießen | Man spricht nicht direkt aus, worum es geht. ; Es geht um ein warmes Essen. ; Katzen schleichen um etwas herum, das zu heiß ist. | Ursprünglich hieß es „wie die Katze um den heißen Brei schleichen“ — sie will fressen, verbrennt sich aber nicht gern.
E E | Welche Redewendung ist hier gesucht? | 🌲🌲🌲🙈 | Den Wald vor lauter Bäumen nicht sehen | Auf dem Holzweg sein ; Einen Baum ausreißen können ; Wie man in den Wald hineinruft, so schallt es heraus | Man verliert sich in Details. ; Das Offensichtliche bleibt unbemerkt. ; Es geht um sehr viele Pflanzen. | Die Wendung ist schon im 18. Jahrhundert belegt — unter anderem beim Dichter Christoph Martin Wieland.
E H | Welche Redewendung ist hier gesucht? | 💶🪟👋 | Das Geld zum Fenster hinauswerfen | Auf großem Fuß leben ; Geld wie Heu haben ; Jeden Cent zweimal umdrehen | Jemand verschwendet Geld. ; Es geht um ein Fenster. ; Das Geld landet auf der Straße statt in der Tasche. | Wer so mit Geld umgeht, gibt es unüberlegt für Unnützes aus — das Gegenteil ist, jeden Cent zweimal umzudrehen.
E E | Welche Redewendung ist hier gesucht? | 🐻💃🎉 | Da steppt der Bär | Einen Bärendienst erweisen ; Einen Bärenhunger haben ; Auf der Bärenhaut liegen | Irgendwo ist richtig viel los. ; Es geht um ein großes Tier. ; Das Tier tanzt. | Der Ausdruck erinnert an Tanzbären, die früher auf Jahrmärkten vorgeführt wurden.
E E | Welche Redewendung ist hier gesucht? | 🦶🥣😬 | Ins Fettnäpfchen treten | Sich ins Zeug legen ; Einen Fuß in der Tür haben ; Auf großem Fuß leben | Man sagt oder tut etwas Peinliches. ; Es geht um einen kleinen Topf. ; Früher stand in Bauernhäusern ein Topf mit Fett für die Stiefel. | Wer in das Fett zum Einreiben der Stiefel trat, hinterließ Flecken auf dem Boden — und machte sich unbeliebt.
E E | Welche Redewendung ist hier gesucht? | 🥄⬇️⚰️ | Den Löffel abgeben | Die Suppe auslöffeln ; Mit einem goldenen Löffel im Mund geboren sein ; Das Handtuch werfen | Es ist eine saloppe Umschreibung. ; Es geht um das Lebensende. ; Früher besaß jeder einen eigenen Löffel, den er vererbte. | Früher hatte jeder seinen eigenen Löffel — starb jemand, ging dieser an den Nachfolger über.
C E | Wie nennt man Wörter mit entgegengesetzter Bedeutung, etwa „heiß“ und „kalt“? | Antonyme | Synonyme ; Homonyme ; Akronyme | Es ist das Gegenteil von Synonymen. ; Die Vorsilbe „anti“ steckt drin. ; Man sagt auch Gegenwörter. | Synonyme bedeuten dagegen dasselbe — etwa „Samstag“ und „Sonnabend“.
C M | Nach welchem germanischen Gott ist der Donnerstag benannt? | Donar | Wodan ; Freya ; Loki | Er ist der Gott des Donners. ; Im Norden heißt er Thor. ; Er schwingt einen Hammer. | Auch der Freitag trägt einen Götternamen — er geht auf die Göttin Frija zurück.
C M | Was bezeichnet man als „Treppenwitz“? | Eine schlagfertige Antwort, die einem erst zu spät einfällt | Einen Witz über Hausmeister ; Einen Scherz, der sich stufenweise steigert ; Eine Pointe, die nur Kinder verstehen | Es geht um eine verpasste Gelegenheit. ; Der Begriff stammt vom französischen „esprit de l'escalier“. ; Die Idee kommt einem erst beim Hinausgehen auf der Treppe. | Heute spricht man auch vom „Treppenwitz der Geschichte“, wenn sich etwas im Nachhinein als absurde Ironie entpuppt.
C U | Aus welcher Sprache stammt das deutsche Wort „Tollpatsch“? | Ungarisch | Italienisch ; Jiddisch ; Türkisch | Ursprünglich war es ein Spitzname für Soldaten. ; Er bezog sich auf ihr breites, plattes Schuhwerk. ; Die Sprache wird in Budapest gesprochen. | „Talpas“ bedeutet auf Ungarisch etwa „breitfüßig“ — so nannte man ungarische Fußsoldaten.
C U | Welches Wort wurde 2004 in einem internationalen Wettbewerb zum „schönsten deutschen Wort“ gewählt? | Habseligkeiten | Geborgenheit ; Lieben ; Augenblick | Es beschreibt Dinge. ; Meist geht es um wenige, aber liebe Besitztümer. ; Darin stecken „haben“ und „selig“. | Veranstaltet wurde die Wahl vom Deutschen Sprachrat — auf Platz zwei landete „Geborgenheit“, auf Platz drei „lieben“.
W E | Das deutsche Wort „Schadenfreude“ wird auch im Englischen verwendet. | wahr | Wie „Kindergarten“, „Angst“ und „Zeitgeist“ fand es als Lehnwort Eingang in englische Wörterbücher.
S U | Aus wie vielen Buchstaben besteht das Alphabet der Khmer-Sprache in Kambodscha — laut Guinness-Buch das längste der Welt? | 74 | Buchstaben | 20 | 10 | 300 | Deutlich mehr als 26. ; Mehr als 50. ; Weniger als 100. | Als kürzestes Alphabet gilt dagegen das der Sprache Rotokas auf Papua-Neuguinea — mit nur zwölf Buchstaben.
O E | Sortiere diese Wörter alphabetisch, wie im Wörterbuch. | Kiste = Ki-s ; Kiwi = Ki-w ; Klee = Kl ; Knie = Kn | Alle beginnen mit K. ; Bei gleichem Anfang entscheidet der nächste Buchstabe. ; Das „i“ kommt vor „l“ und „n“. | Im Wörterbuch zählt Buchstabe für Buchstabe — erst wenn alle gleich sind, steht das kürzere Wort zuerst.
O M | Bringe diese Buchstaben des griechischen Alphabets in die richtige Reihenfolge. | Alpha = 1. Buchstabe ; Gamma = 3. Buchstabe ; Lambda = 11. Buchstabe ; Omega = 24. Buchstabe | Der erste steht sprichwörtlich für den Anfang. ; Das Gamma folgt kurz nach dem Beta. ; Omega steht ganz am Ende. | Das Wort „Alphabet“ setzt sich aus den Namen der ersten beiden griechischen Buchstaben zusammen: Alpha und Beta.
M M | Welche DREI dieser Wörter ergeben rückwärts gelesen ein anderes sinnvolles Wort? | Nebel ; Gras ; Eis | Tomate ; Katze ; Stuhl | Aus einem wird etwas, das alle Lebewesen haben. ; Aus einem anderen wird ein Behälter für Verstorbene. ; Aus dem dritten wird ein Fürwort. | Nebel wird zu Leben, Gras zu Sarg und Eis zu Sie — solche Wörter nennt man Ananyme.
M H | Welche DREI dieser Wörter kamen über das Arabische ins Deutsche? | Alkohol ; Matratze ; Zucker | Pizza ; Tee ; Kindergarten | Eines entsteht bei der Gärung. ; Auf einem schläft man. ; Eines ist süß. | Auch „Magazin“, „Tarif“ und „Ziffer“ stammen aus dem Arabischen — ebenso wie die Ziffern, mit denen wir rechnen.
"""
