"""Extra questions, wave 2: Musik (format: see tools/content/merge_extra.py)."""
KAT = "musik"
REGION = "global"
DATA = r"""
@ pop_international
E E | Welcher Song ist hier gesucht? | 🟡🚢🌊 | Yellow Submarine | Octopus's Garden ; Lucy in the Sky with Diamonds ; Here Comes the Sun | Er stammt von den Beatles. ; Gesungen hat ihn Ringo Starr. ; Ein Unterwasserfahrzeug hat eine auffällige Farbe. | Der Song von 1966 bekam 1968 einen eigenen Zeichentrickfilm — die Beatles selbst tauchten darin nur ganz kurz am Ende auf.
E E | Welcher Song ist hier gesucht? | 🚀👨‍🚀🎹 | Rocket Man | Space Oddity ; Starman ; Major Tom (völlig losgelöst) | Der Sänger sitzt meist am Klavier. ; Er trägt gern extravagante Brillen. ; Der Song von 1972 handelt von einem Astronauten, der seine Familie vermisst. | Elton John und Texter Bernie Taupin schrieben den Hit — Elton Johns Filmbiografie von 2019 trägt fast denselben Titel.
E M | Welcher Song ist hier gesucht? | 🍉🍬☀️ | Watermelon Sugar | Strawberry Swing ; Sugar ; Peaches | Der Sänger war früher in einer Boyband. ; Der Song gewann 2021 einen Grammy. ; Es geht um eine süße Sommerfrucht. | Harry Styles holte mit dem Song 2021 seinen ersten Grammy — für die beste Pop-Solo-Darbietung.
E U | Welcher Song ist hier gesucht? | 💍🔥⬇️ | Ring of Fire | Walk the Line ; Burning Love ; Great Balls of Fire | Er stammt aus dem Jahr 1963. ; Gesungen hat ihn der „Man in Black“. ; Mitgeschrieben hat ihn June Carter, die spätere Frau des Sängers. | Johnny Cash machte den Song mit mexikanisch klingenden Trompeten zum Country-Klassiker.
W M | Der Bandname ABBA setzt sich aus den Anfangsbuchstaben der Vornamen der vier Mitglieder zusammen. | wahr | Agnetha, Björn, Benny und Anni-Frid ergeben A-B-B-A — der Name gehörte zuvor schon einer schwedischen Fischkonserven-Firma.
W U | Michael Jacksons „Thriller“ wurde als erstes Musikvideo überhaupt in das National Film Registry der USA aufgenommen. | wahr | Die Library of Congress nahm den 14-minütigen Kurzfilm 2009 in ihr Archiv besonders bedeutender Filme auf.
W E | Taylor Swift begann ihre Karriere als Rapperin. | falsch | Swift startete Mitte der 2000er als Country-Sängerin in Nashville — erst später wechselte sie komplett zum Pop.
S M | In welchem Jahr erschien das Beatles-Album „Sgt. Pepper's Lonely Hearts Club Band“? | 1967 | Jahr | 2 | 1955 | 1980 | In den 1960ern. ; Im „Summer of Love“. ; Zwei Jahre vor Woodstock. | Das Album gilt als eines der ersten Konzeptalben — das Cover mit Dutzenden Prominenten wurde selbst zur Ikone.
S U | Wie alt war Justin Bieber, als seine Single „Baby“ Anfang 2010 erschien? | 15 | Jahre | 15 | 8 | 30 | Er war noch ein Teenager. ; Jünger als 18. ; Er war noch nicht 16. | Entdeckt wurde Bieber über YouTube-Videos — sein späterer Manager Scooter Braun stieß zufällig auf sie.
S E | In welchem Jahr starb Michael Jackson? | 2009 | Jahr | 2 | 1990 | 2020 | Im 21. Jahrhundert. ; Kurz vor einer geplanten Konzertreihe in London. ; Ende der 2000er. | Jackson starb im Juni 2009 in Los Angeles — die geplanten 50 Konzerte „This Is It“ fanden nie statt.
O H | Sortiere diese Alben von Taylor Swift nach ihrem Erscheinen — das älteste zuerst. | Fearless = 2008 ; 1989 = 2014 ; Folklore = 2020 ; The Tortured Poets Department = 2024 | Mit dem ältesten gewann sie ihren ersten Grammy fürs Album des Jahres. ; Das Album mit der Jahreszahl im Titel folgt. ; Das jüngste erschien im April 2024. | Weil ihr die Rechte an den alten Aufnahmen nicht gehörten, nahm Swift viele Alben als „Taylor's Version“ neu auf.
O M | Sortiere diese Boybands nach ihrem Gründungsjahr — die älteste zuerst. | Take That = 1990 ; Backstreet Boys = 1993 ; NSYNC = 1995 ; One Direction = 2010 | Die britische Band um Robbie Williams ist die älteste. ; Die beiden US-Bands folgten Mitte der 1990er. ; Die jüngste entstand in einer Castingshow. | One Direction wurde 2010 bei „The X Factor“ aus fünf Solo-Kandidaten zusammengestellt.
M E | Welche DREI dieser Popstars sind Britinnen oder Briten? | Adele ; Ed Sheeran ; Harry Styles | Taylor Swift ; Bruno Mars ; Rihanna | Eine stammt aus London-Tottenham. ; Einer wuchs in Suffolk auf. ; Einer war Mitglied von One Direction. | Taylor Swift und Bruno Mars stammen aus den USA, Rihanna von der Karibikinsel Barbados.
M H | Welche ZWEI dieser Popstars standen als Kinder im „Mickey Mouse Club“ von Disney vor der Kamera? | Britney Spears ; Justin Timberlake | Taylor Swift ; Ed Sheeran ; Adele ; Harry Styles | Beide wurden später ein Paar. ; Einer wurde danach mit einer Boyband berühmt. ; Die andere startete 1998 mit „…Baby One More Time“. | Auch Christina Aguilera und Ryan Gosling gehörten Anfang der 1990er zur Besetzung der Show.
C E | Aus welchem Land stammt die Sängerin Shakira? | Kolumbien | Mexiko ; Spanien ; Argentinien | Sie singt auf Spanisch und Englisch. ; Ihre Heimatstadt Barranquilla liegt an der Karibikküste. ; Das Land liegt im Norden Südamerikas. | Shakiras Vater hat libanesische Wurzeln — daher stammt ihre Leidenschaft für den Bauchtanz.
C E | Wie heißt der Sänger der britischen Band Coldplay? | Chris Martin | Thom Yorke ; Liam Gallagher ; Brandon Flowers | Er spielt oft Klavier. ; Er war mit Gwyneth Paltrow verheiratet. ; Sein Nachname ist auch ein Vorname. | Coldplay gründete sich 1996 in London — der erste große Hit hieß „Yellow“.
C H | Unter welchem Künstlernamen wurde der Kanadier Abel Tesfaye mit „Blinding Lights“ weltberühmt? | The Weeknd | Drake ; Shawn Mendes ; Justin Bieber | Er stammt aus Toronto. ; Seine Eltern kamen aus Äthiopien. ; In seinem Künstlernamen fehlt ein Buchstabe. | Das dritte „e“ ließ er weg, weil es bereits eine kanadische Band namens „The Weekend“ gab.
C H | Welcher Musiker nannte sich ab 1993 jahrelang nur noch mit einem unaussprechlichen Symbol? | Prince | David Bowie ; Michael Jackson ; George Michael | Er stammte aus Minneapolis. ; Er spielte auf seinen Alben fast alle Instrumente selbst. ; Sein bekanntestes Album heißt „Purple Rain“. | Mit dem Symbol protestierte er gegen seine Plattenfirma — im Jahr 2000 kehrte er zu seinem alten Namen zurück.
C U | Wie lautet der bürgerliche Geburtsname von Elton John? | Reginald Kenneth Dwight | Richard Starkey ; David Jones ; Farrokh Bulsara | Er stammt aus Pinner bei London. ; Seinen Künstlernamen nahm er 1972 auch offiziell an. ; Sein Nachname beginnt mit D. | Den Namen Elton John setzte er aus den Vornamen zweier Musikerkollegen zusammen: Elton Dean und Long John Baldry.

@ rock_metal
E E | Welche Band ist hier gesucht? | 🔫🌹🎸 | Guns N' Roses | Bon Jovi ; Mötley Crüe ; Poison | Die Band stammt aus Los Angeles. ; Der Sänger heißt Axl Rose. ; Der Gitarrist trägt stets einen Zylinder. | Der Bandname verbindet die beiden Vorgängerbands L.A. Guns und Hollywood Rose.
E M | Welche Band ist hier gesucht? | 🚪🚪🦎🎹 | The Doors | The Who ; The Byrds ; Jefferson Airplane | Die Band stammt aus Los Angeles. ; Ihr Sänger nannte sich „Lizard King“. ; Er hieß Jim Morrison. | Den Namen entlehnte die Band dem Buch „The Doors of Perception“ von Aldous Huxley.
E M | Welcher Song ist hier gesucht? | 🧱🏫👨‍🏫🚫 | Another Brick in the Wall | Comfortably Numb ; Wish You Were Here ; Money | Er stammt von Pink Floyd. ; Ein Kinderchor singt mit. ; „We don't need no education …“ | Den Chor sang eine Schulklasse aus London — der Song wurde 1979/80 in vielen Ländern zum Nummer-1-Hit.
E E | Welcher Song ist hier gesucht? | 🏨🌴🦅 | Hotel California | Take It Easy ; Desperado ; Life in the Fast Lane | Er erschien Ende 1976. ; Die Band ist nach einem Greifvogel benannt. ; „You can check out any time you like, but you can never leave.“ | Das lange Gitarrenduett am Ende spielten Don Felder und Joe Walsh — es gilt als eines der besten Gitarrensoli überhaupt.
W M | Jimi Hendrix war Linkshänder und spielte meist eine umgedrehte Gitarre für Rechtshänder. | wahr | Er spannte die Saiten einfach andersherum auf — seine weiße Stratocaster aus Woodstock ist heute ein Museumsstück.
W H | Freddie Mercury schrieb den Queen-Hit „We Will Rock You“. | falsch | Den Stampf-und-Klatsch-Song schrieb Gitarrist Brian May — Mercury schrieb dafür „We Are the Champions“.
W E | Die Rolling Stones haben sich schon 1970 aufgelöst. | falsch | Die Band ist bis heute aktiv — 2023 erschien mit „Hackney Diamonds“ sogar ein neues Studioalbum.
S H | Wie viele Minuten dauert „Stairway to Heaven“ von Led Zeppelin ungefähr? | 8 | Minuten | 15 | 2 | 30 | Deutlich länger als ein normaler Radiosong. ; Mehr als sechs Minuten. ; Weniger als zehn Minuten. | Der Song steigert sich über rund acht Minuten von zarter Akustikgitarre bis zum harten Rockfinale.
S U | In welchem Jahr fand das erste Wacken Open Air statt? | 1990 | Jahr | 3 | 1970 | 2010 | Ende des 20. Jahrhunderts. ; Im Jahr der Wiedervereinigung. ; Um 1990. | Beim ersten Mal kamen nur einige Hundert Fans in das Dorf in Schleswig-Holstein — heute sind es jedes Jahr über 80.000.
O M | Sortiere diese Queen-Songs nach ihrem Erscheinen — den ältesten zuerst. | Bohemian Rhapsody = 1975 ; We Will Rock You = 1977 ; Another One Bites the Dust = 1980 ; Radio Ga Ga = 1984 | Die Rock-Oper kam zuerst. ; Die Stadionhymne folgte zwei Jahre später. ; Der Song, der Lady Gaga ihren Namen gab, ist der jüngste. | Mit „Another One Bites the Dust“ landete Queen ihren meistverkauften Single-Hit in den USA.
O U | Sortiere diese Metallica-Alben nach ihrem Erscheinen — das älteste zuerst. | Master of Puppets = 1986 ; …And Justice for All = 1988 ; Metallica (Black Album) = 1991 ; St. Anger = 2003 | Das älteste erschien kurz vor dem Tod von Bassist Cliff Burton. ; Das Album mit „Justice“ im Titel folgt. ; Das Album mit dem schwarzen Cover kommt vor „St. Anger“. | Das „Schwarze Album“ von 1991 verkaufte sich weltweit viele Millionen Mal und machte Metallica endgültig zu Superstars.
M E | Welche DREI dieser Bands stammen aus Großbritannien? | Queen ; Iron Maiden ; Oasis | Nirvana ; Metallica ; AC/DC | Eine davon stammt aus Manchester. ; Eine ist eine Heavy-Metal-Legende aus London. ; Die übrigen kommen aus den USA und Australien. | Großbritannien gilt mit Beatles, Rolling Stones, Led Zeppelin und Black Sabbath als eine der wichtigsten Rock-Nationen.
M H | Welche ZWEI dieser Musiker spielten in der Band Nirvana? | Kurt Cobain ; Krist Novoselic | Eddie Vedder ; Chris Cornell ; Layne Staley ; Billy Corgan | Einer war Sänger und Gitarrist. ; Der andere spielte Bass. ; Die übrigen sangen bei Pearl Jam, Soundgarden, Alice in Chains und den Smashing Pumpkins. | Neben Cobain und Novoselic gehörte ab 1990 Schlagzeuger Dave Grohl zur bekanntesten Besetzung.
C E | Welche britische Band landete 1995 mit „Wonderwall“ einen Welthit? | Oasis | Blur ; Radiohead ; Coldplay | Die Band stammt aus Manchester. ; Sie wurde von zwei zerstrittenen Brüdern angeführt. ; Die Brüder heißen Liam und Noel Gallagher. | Die Gallaghers lieferten sich legendäre Streitereien — 2009 zerbrach die Band hinter der Bühne eines Festivals bei Paris.
C E | Welche Band veröffentlichte 1966 den Song „Paint It Black“? | The Rolling Stones | The Beatles ; The Who ; The Kinks | Der Sänger heißt Mick Jagger. ; Die Band trägt eine Zunge im Logo. ; Brian Jones spielte darauf eine indische Sitar. | Der Song war einer der ersten Rock-Hits mit Sitar — und wurde später zum Titelsong der Kriegsserie „Tour of Duty“.
C H | Wie heißt der Sänger von Iron Maiden, der auch als Linienpilot arbeitete? | Bruce Dickinson | Paul Di'Anno ; Rob Halford ; Ronnie James Dio | Er ist Brite. ; Er flog die Band sogar selbst im eigenen Jet „Ed Force One“ zu Konzerten. ; Er stieß 1981 zur Band. | Dickinson ist außerdem Fechter, Buchautor und Radiomoderator — ein echtes Multitalent.
C M | Wie heißt der dänischstämmige Schlagzeuger von Metallica? | Lars Ulrich | Kirk Hammett ; Robert Trujillo ; Dave Mustaine | Er gründete die Band 1981 mit James Hetfield. ; Er wurde in Dänemark geboren. ; Sein Vater war Tennisprofi. | Ulrich zog als Jugendlicher in die USA — eigentlich sollte er wie sein Vater Torben Tennisprofi werden.
C U | Wie heißt der Konzertfilm, in dem Pink Floyd 1971 in einem antiken Amphitheater ganz ohne Publikum spielten? | Live at Pompeii | The Wall ; Live Aid ; Delicate Sound of Thunder | Das Amphitheater liegt bei Neapel. ; Die Stadt wurde im Jahr 79 vom Vesuv verschüttet. ; Der Film erschien 1972. | Die Band spielte zwischen den antiken Ruinen nur für das Filmteam — der Film gilt als Meilenstein des Konzertfilms.

@ deutschrap_hiphop de
E E | Welcher Song ist hier gesucht? | 🎤🍝😰 | Lose Yourself | Stan ; The Real Slim Shady ; Without Me | Er stammt aus dem Film „8 Mile“. ; Er gewann als erster Rap-Song einen Oscar. ; Im Text klebt „Mom's spaghetti“ auf dem Pullover. | Eminem gewann 2003 den Oscar für den besten Filmsong — die Verleihung soll er einfach verschlafen haben.
E E | Welcher Song ist hier gesucht? | ❓👍👎 | Jein | Nordisch by Nature ; Emanuela ; Schwule Mädchen | Der Song stammt von Fettes Brot. ; Er erschien 1996. ; Der Titel mischt zwei Antworten. | Der Song erzählt von einem Mann, der zwischen Freundin und Affäre schwankt — sein Titel wurde zum geflügelten Wort.
E H | Welcher Song ist hier gesucht? | 🏢🏙️🧍 | Mein Block | Straßenjunge ; Fuffies im Club ; Hey Du | Der Rapper trug früher eine Totenkopfmaske. ; Er beschreibt sein Hochhausviertel in Berlin. ; Das Viertel heißt Märkisches Viertel. | Sido rappte über das Märkische Viertel in Berlin-Reinickendorf — der Song wurde zu einer Hymne des Berliner Straßenraps.
W M | Der Rapper Kool Savas wurde in Aachen geboren. | wahr | Nach Kindheitsjahren in der Türkei zog er als Jugendlicher nach Berlin — dort wurde er zum „King of Rap“.
W H | Das Wort „Rap“ ist ursprünglich eine Abkürzung für „Rhythm and Poetry“. | falsch | Das Akronym wurde erst nachträglich erfunden — das englische „to rap“ bedeutet schlicht „plaudern“ oder „klopfen“.
W M | Capital Bra wurde in Berlin geboren. | falsch | Er kam in Sibirien zur Welt, wuchs in der Ukraine auf und zog als Kind nach Berlin.
S H | Wie viele Grammys hat Eminem gewonnen (Stand 2024)? | 15 | Grammys | 20 | 1 | 50 | Mehr als zehn. ; Weniger als 20. ; Eine ungerade Zahl. | Eminem zählt zu den erfolgreichsten Rappern der Grammy-Geschichte — sechs seiner Alben wurden als bestes Rap-Album ausgezeichnet.
S M | In welchem Jahr wurde der Rapper Tupac Shakur in Las Vegas erschossen? | 1996 | Jahr | 2 | 1980 | 2010 | In den 1990ern. ; Er wurde nur 25 Jahre alt. ; Mitte der 1990er. | Nur ein halbes Jahr später wurde auch sein Rivale The Notorious B.I.G. erschossen — beide Morde prägten den Konflikt zwischen Ost- und Westküste.
O M | Sortiere diese US-Rapper nach ihrem Geburtsjahr — den ältesten zuerst. | Jay-Z = 1969 ; Eminem = 1972 ; Kanye West = 1977 ; Drake = 1986 | Der Ehemann von Beyoncé ist der älteste. ; Slim Shady folgt. ; Der Kanadier ist der jüngste. | Drake begann seine Karriere übrigens als Schauspieler in der kanadischen Teenie-Serie „Degrassi“.
O U | Sortiere diese Hip-Hop-Filme nach ihrem Erscheinen — den ältesten zuerst. | 8 Mile = 2002 ; Notorious B.I.G. = 2009 ; Straight Outta Compton = 2015 ; Rheingold = 2022 | Eminems Filmdebüt ist der älteste. ; Das Biopic über Biggie folgt. ; Der deutsche Film über Xatar ist der jüngste. | In „Straight Outta Compton“ spielte der Sohn eines Gründungsmitglieds seinen eigenen Vater.
M M | Welche ZWEI dieser Rapper gehörten zur Gruppe N.W.A? | Ice Cube ; Eazy-E | Snoop Dogg ; Tupac Shakur ; 50 Cent ; Nas | Einer wurde später Schauspieler in Familienkomödien. ; Der andere gründete das Label Ruthless Records. ; Die Gruppe stammte aus Compton. | Die Gruppe veröffentlichte 1988 das Album „Straight Outta Compton“ und prägte den Gangsta-Rap der Westküste.
M U | Welche DREI dieser Rapper gehörten zum Wu-Tang Clan? | Method Man ; RZA ; Ghostface Killah | Snoop Dogg ; Ice Cube ; Nas | Die Gruppe stammt aus New York. ; Einer ist ihr Produzent und Kopf. ; Einer trägt eine Methode im Namen. | Die Rapper benannten sich nach Kung-Fu-Filmen — ihr Debüt „Enter the Wu-Tang (36 Chambers)“ erschien 1993.
C E | Wie lautet der bürgerliche Name von Eminem? | Marshall Mathers | Curtis Jackson ; Shawn Carter ; Calvin Broadus | Er stammt aus Detroit. ; Sein Künstlername ergibt sich aus seinen Initialen. ; Beide Namensteile beginnen mit M. | Aus den Initialen M. M. wurde „M&M“ — und daraus Eminem.
C M | Welchen Spitznamen gibt sich der Rapper Kollegah? | Der Boss | Der Chef ; Der König ; Der Pate | Er rappt gern über Luxus und Muskeltraining. ; Er studierte zeitweise Jura. ; Das Wort kommt aus dem Englischen und bedeutet Vorgesetzter. | Kollegah heißt eigentlich Felix Blume und stammt aus Hessen.
C M | Welcher Rapper gründete das Plattenlabel „Roc-A-Fella Records“? | Jay-Z | Dr. Dre ; Kanye West ; Sean Combs | Er stammt aus Brooklyn. ; Sein bürgerlicher Name ist Shawn Carter. ; Er ist mit Beyoncé verheiratet. | Jay-Z gilt heute als einer der reichsten Musiker der Welt — Forbes führt ihn als Milliardär.
C H | Wie heißt der Seeed-Sänger Peter Fox mit bürgerlichem Namen? | Pierre Baigorry | Peter Fuchs ; Pierre Schulz ; Paul Fischer | Er ist Berliner. ; Sein Vorname ist französisch. ; Sein Nachname klingt baskisch. | Sein Solo-Album „Stadtaffe“ von 2008 gehört zu den erfolgreichsten deutschen Hip-Hop-Alben.
C U | Welcher DJ gilt als „Vater des Hip-Hop“, weil er 1973 auf einer Party in der Bronx Breakbeats verlängerte? | DJ Kool Herc | Grandmaster Flash ; Afrika Bambaataa ; DJ Premier | Er stammt ursprünglich aus Jamaika. ; Er legte zwei gleiche Platten nebeneinander auf. ; Die Party fand im August 1973 statt. | Die Party in der Sedgwick Avenue gilt als Geburtsstunde des Hip-Hop — deshalb feierte man 2023 den 50. Geburtstag.

@ charts_onehit_esc
E E | Welcher Song ist hier gesucht? | 🏜️🌪️🎹 | Sandstorm | Children ; Blue (Da Ba Dee) ; Better Off Alone | Es ist ein Instrumental-Hit von 1999. ; Er stammt vom finnischen DJ Darude. ; Er wird bis heute in Stadien gespielt. | Der Track wurde später zum Internet-Meme — auf die Frage nach einem Songtitel antworten Scherzbolde gern mit „Darude – Sandstorm“.
E E | Welcher ESC-Siegersong ist hier gesucht? | 🤘👹😇 | Hard Rock Hallelujah | Wild Dances ; Euphoria ; Fairytale | Er gewann 2006. ; Die Band trat in Monstermasken auf. ; Die Band stammt aus Finnland. | Es war Finnlands erster ESC-Sieg — nach über 40 Jahren Teilnahme.
E U | Welcher ESC-Siegersong ist hier gesucht? | 🐔🧸🇮🇱 | Toy | Arcade ; Heroes ; Amar pelos dois | Er gewann 2018 in Lissabon. ; Die Sängerin gackerte auf der Bühne wie ein Huhn. ; Sie heißt Netta. | Netta holte für Israel den vierten ESC-Sieg — der Wettbewerb 2019 fand daraufhin in Tel Aviv statt.
W H | „Last Christmas“ von Wham! stand erst im Januar 2021 zum ersten Mal auf Platz 1 der britischen Charts. | wahr | 36 Jahre nach der Veröffentlichung klappte es endlich — dank Streaming, das den Song jedes Jahr wieder nach oben spült.
W E | Die offiziellen deutschen Charts werden ausschließlich aus CD-Verkäufen ermittelt. | falsch | Heute zählen vor allem Streams und Downloads — CDs und Vinyl fließen nur noch ergänzend ein.
W M | Im ESC-Finale entscheidet allein das Publikum per Televoting über den Sieger. | falsch | Im Finale setzen sich die Punkte je zur Hälfte aus Jury-Wertungen und Zuschauerstimmen zusammen.
S H | Wie viele Länder nahmen 2024 am Eurovision Song Contest teil? | 37 | Länder | 15 | 10 | 80 | Mehr als 30. ; Weniger als 40. ; Eine ungerade Zahl. | Der ESC 2024 fand im schwedischen Malmö statt — den Rekord halten die Jahre 2008, 2011 und 2018 mit je 43 Ländern.
S H | Wie viele Wochen stand „Despacito“ 2017 auf Platz 1 der US-Charts? | 16 | Wochen | 15 | 1 | 52 | Mehr als zehn. ; Weniger als 20. ; Damit stellte der Song den damaligen Rekord ein. | Damit zog der Song mit Mariah Careys „One Sweet Day“ gleich — erst „Old Town Road“ übertraf die Marke.
S M | Wie viele Jahre lagen zwischen Deutschlands beiden ESC-Siegen? | 28 | Jahre | 10 | 1 | 60 | Mehr als 20 Jahre. ; Weniger als 30 Jahre. ; Der zweite Sieg gelang 2010. | Nicole siegte 1982 mit „Ein bisschen Frieden“, Lena 2010 mit „Satellite“ — seitdem wartet Deutschland auf den dritten Titel (Stand 2024).
O M | Sortiere diese Dance-Hits der 1990er nach ihrem Erscheinen — den ältesten zuerst. | Rhythm Is a Dancer = 1992 ; No Limit = 1993 ; Freed from Desire = 1996 ; Blue (Da Ba Dee) = 1998 | Der Hit von Snap! kam zuerst. ; 2 Unlimited folgten ein Jahr später. ; Eiffel 65 ist am jüngsten. | Snap! entstand in Frankfurt — die Stadt war Anfang der 1990er ein Zentrum der Dance-Musik.
O H | Sortiere diese Länder nach ihrer Zahl an ESC-Siegen (Stand 2024) — das Land mit den wenigsten zuerst. | Deutschland = 2 ; Israel = 4 ; Großbritannien = 5 ; Schweden = 7 | Deutschland gewann mit Nicole und Lena. ; Netta holte den bislang letzten Sieg für Israel. ; Die Heimat von ABBA ist Rekordsieger. | Schweden teilt sich den Rekord von sieben Siegen mit Irland — Großbritannien gewann zuletzt 1997 mit Katrina and the Waves.
M E | Welche ZWEI dieser ESC-Sieger traten für Schweden an? | ABBA ; Loreen | Lordi ; Måneskin ; Conchita Wurst ; Netta | Einer der Acts siegte 1974 mit „Waterloo“. ; Die andere gewann gleich zweimal. ; Die übrigen stammen aus Finnland, Italien, Österreich und Israel. | Loreen gewann 2012 mit „Euphoria“ und 2023 mit „Tattoo“ — ABBA 1974 mit „Waterloo“.
M U | Welche ZWEI dieser Länder haben den ESC noch nie gewonnen (Stand 2024)? | Malta ; Zypern | Portugal ; Ukraine ; Serbien ; Aserbaidschan | Beide sind Inselstaaten im Mittelmeer. ; Beide landeten schon auf Platz zwei. ; Die übrigen gewannen alle nach dem Jahr 2000. | Malta wurde schon zweimal Zweiter, Zypern 2018 mit „Fuego“ — zum Sieg reichte es bisher nie.
C E | Welches Land gewann 2024 den Eurovision Song Contest? | Schweiz | Kroatien ; Ukraine ; Frankreich | Der Siegertitel hieß „The Code“. ; Nemo gewann als erste nicht-binäre Person den ESC. ; Das Land siegte schon beim allerersten ESC 1956. | Es war der dritte ESC-Sieg des Landes — und der erste seit 1988.
C E | Welche irische Band landete 1994 mit „Zombie“ einen Welthit? | The Cranberries | U2 ; The Corrs ; Westlife | Die Sängerin hieß Dolores O'Riordan. ; Der Song handelt vom Nordirlandkonflikt. ; Die Band stammt aus Limerick. | Dolores O'Riordan schrieb den Song nach einem Bombenanschlag im englischen Warrington, bei dem 1993 zwei Kinder starben.
C M | Wie viele Punkte bekam Deutschland beim ESC-Finale 2015? | Null | Einen ; Zwölf ; 24 | Es war ein historisches Debakel. ; Auch Gastgeber Österreich ging leer aus. ; Mehr als nichts war es nicht. | Ann Sophie teilte sich 2015 den letzten Platz mit dem Gastgeberland Österreich — beide ohne einen einzigen Punkt.
C E | In welcher Stadt fand der ESC 2023 stellvertretend für die Ukraine statt? | Liverpool | London ; Glasgow ; Dublin | Die Stadt liegt in England. ; Sie ist die Heimat der Beatles. ; Großbritannien war 2022 Zweiter geworden. | Weil in der Ukraine Krieg herrschte, richtete der Zweitplatzierte von 2022 aus — mit ukrainischen Elementen in der ganzen Show.
C H | Welches Land landete beim ESC am häufigsten auf dem letzten Platz? | Norwegen | Deutschland ; Finnland ; Österreich | Das Land liegt in Skandinavien. ; Es gewann trotzdem schon dreimal. ; 1978 holte Jahn Teigen dort legendäre null Punkte. | Norwegen wurde über zehnmal Letzter — und siegte doch dreimal, zuletzt 2009 mit Alexander Rybak.

@ schlager_volksmusik de
E E | Welcher Song ist hier gesucht? | ☁️✈️🕊️ | Über den Wolken | Ein Stern ; Griechischer Wein ; Ich war noch niemals in New York | Der Liedermacher Reinhard Mey veröffentlichte ihn 1974. ; Es geht ums Fliegen. ; „… muss die Freiheit wohl grenzenlos sein.“ | Reinhard Mey ist selbst begeisterter Hobbypilot — das Lied gehört zu den bekanntesten deutschen Liedermacher-Songs.
E E | Welcher Schlager ist hier gesucht? | 🌷🌷🇳🇱 | Tulpen aus Amsterdam | Rote Rosen, rote Lippen, roter Wein ; Heimweh ; Der Junge mit der Mundharmonika | Der Schlager stammt aus den 1950er-Jahren. ; Es geht um Blumen aus den Niederlanden. ; Sie kommen aus der Hauptstadt. | Der Evergreen wurde auch auf Englisch als „Tulips from Amsterdam“ ein großer Hit.
E E | Welcher Schlager ist hier gesucht? | 🛏️🌾☀️ | Ein Bett im Kornfeld | Wahnsinn ; Santa Maria ; Tausendmal du | Der Sänger wurde später „König von Mallorca“ genannt. ; Der Hit stammt aus dem Jahr 1976. ; Es geht um ein Nachtlager unter freiem Himmel. | Jürgen Drews landete damit 1976 seinen größten Hit — das Original „Let Your Love Flow“ stammt von den Bellamy Brothers.
W H | Roland Kaiser heißt mit bürgerlichem Namen Ronald Keiler. | wahr | Der gebürtige Berliner feierte unter seinem Künstlernamen Hits wie „Santa Maria“ und „Joana“.
W M | Die Zillertaler Schürzenjäger stammen aus Bayern. | falsch | Die Band kommt aus dem Zillertal in Tirol, Österreich — ihr größter Hit heißt „Sierra Madre del Sur“.
W M | Beim Jodeln wechselt man in schnellem Tempo zwischen Brust- und Kopfstimme. | wahr | Genau dieser Registerwechsel erzeugt den typischen Kiekser — jodelähnlichen Gesang gibt es übrigens auch bei Völkern in Zentralafrika.
S H | Wie alt war Heintje, als er 1967 mit „Mama“ berühmt wurde? | 12 | Jahre | 20 | 4 | 30 | Er war noch ein Kind. ; Jünger als 15. ; Älter als zehn. | Seine Stimme war damals noch nicht im Stimmbruch — genau das machte den Kinderstar so erfolgreich.
S M | In welchem Jahr wurde Helene Fischer geboren? | 1984 | Jahr | 3 | 1960 | 2000 | In den 1980ern. ; Im Jahr, das George Orwell als Romantitel wählte. ; Mitte der 1980er. | Helene Fischer kam im August 1984 in Sibirien zur Welt und zog als Kind mit ihrer Familie nach Rheinland-Pfalz.
O E | Sortiere diese Instrumente nach ihrer Länge — das kürzeste zuerst. | Mundharmonika = ca. 10 cm ; Gitarre = ca. 1 m ; Kontrabass = ca. 1,8 m ; Alphorn = ca. 3,5 m | Das kleinste passt in die Hosentasche. ; Die Gitarre liegt im Mittelfeld. ; Das Blasinstrument aus den Bergen ist mit Abstand das längste. | Traditionell wird ein Alphorn aus einer einzigen, am Hang krumm gewachsenen Fichte gefertigt.
M M | Welche ZWEI dieser Schlagerstars stammen aus der Schweiz? | Beatrice Egli ; Francine Jordi | Helene Fischer ; Andrea Berg ; Vanessa Mai ; Michelle | Eine gewann 2013 „Deutschland sucht den Superstar“. ; Die andere trat 2002 für ihr Land beim ESC an. ; Beide stammen aus einem Alpenland mit vier Landessprachen. | Beatrice Egli stammt aus dem Kanton Schwyz, Francine Jordi aus dem Kanton Bern.
C E | Wie heißt der Hit von Wolfgang Petry, bei dem das Publikum „Hölle, Hölle, Hölle“ ruft? | Wahnsinn | Verlieben, verloren, vergessen, verzeih'n ; Der Himmel brennt ; Weiß der Geier | Er erschien 1983. ; Der Refrain wird auf jeder Schlagerparty mitgegrölt. ; Der Titel bedeutet so viel wie „Verrücktheit“. | Der Song wurde erst Jahre nach seinem Erscheinen zur Mitgröl-Hymne auf Partys und in Fußballstadien.
C M | Wer sang 1975 den Schlager „Er gehört zu mir“? | Marianne Rosenberg | Nicole ; Mary Roos ; Katja Ebstein | Die Sängerin stammt aus Berlin. ; Sie hat Sinti-Wurzeln. ; Ihr Vorname beginnt mit M. | Der Song wurde zum Dauerbrenner — und Jahrzehnte später zu einer Hymne der queeren Partyszene.
C U | Wer landete 1977 mit „Tanze Samba mit mir“ einen Hit? | Tony Holiday | Roberto Blanco ; Costa Cordalis ; Rex Gildo | Der Hit stammt aus den späten 1970ern. ; Im Titel steckt ein brasilianischer Tanz. ; Der Künstlername des Sängers klingt nach Urlaub. | Der Gute-Laune-Schlager läuft bis heute auf Schlagerpartys und in Discofox-Kursen.
C M | Welches Instrument spielt Schlager-Moderator Florian Silbereisen? | Steirische Harmonika | Trompete ; Zither ; Klarinette | Es ist ein Zuginstrument. ; Man nennt es auch „Quetschn“. ; Er lernte es schon als Kind in Niederbayern. | Die Steirische Harmonika ist eine diatonische Knopfharmonika — typisch für die Volksmusik der Alpen.
C U | Welche Sängerin sang 1951 als Kind den Hit „Pack die Badehose ein“? | Cornelia Froboess | Connie Francis ; Peggy March ; Siw Malmkvist | Sie ging damals noch zur Grundschule. ; Später wurde sie eine gefeierte Theaterschauspielerin. ; Man nannte sie „Conny“. | Das Lied über einen Ausflug an den Berliner Wannsee wurde zum Evergreen der Nachkriegszeit.

@ klassik_filmmusik
E E | Welches Ballett ist hier gesucht? | 🦢🦢🌊🩰 | Schwanensee | Der Nussknacker ; Dornröschen ; Giselle | Die Musik stammt von Tschaikowski. ; Eine Prinzessin wird in einen Vogel verwandelt. ; Die Heldin heißt Odette. | Die Uraufführung 1877 in Moskau war ein Misserfolg — erst die Neufassung von 1895 machte das Ballett weltberühmt.
E E | Welches Klavierstück ist hier gesucht? | 🌙🎹🌊 | Mondscheinsonate | Für Elise ; Pathétique ; Träumerei | Sie stammt von Beethoven. ; Der erste Satz ist langsam und geheimnisvoll. ; Den Beinamen gab ihr erst ein Musikkritiker nach Beethovens Tod. | Der Kritiker Ludwig Rellstab verglich den ersten Satz mit Mondschein über dem Vierwaldstättersee — Beethoven selbst nannte sie „Sonata quasi una fantasia“.
E H | Welches Musikstück ist hier gesucht? | 🏔️👑👹🥁 | In der Halle des Bergkönigs | Morgenstimmung ; Walkürenritt ; Eine Nacht auf dem kahlen Berge | Es stammt aus der „Peer Gynt“-Musik. ; Es wird immer schneller und lauter. ; Trolle jagen darin den Helden. | Edvard Grieg soll das Stück selbst nicht gemocht haben — heute kennt man es aus unzähligen Filmen und Werbespots.
W M | Mozart schrieb seine erste Sinfonie im Alter von acht Jahren. | wahr | Er komponierte sie 1764 in London — als der Vater krank war und die Familie nicht musizieren durfte.
W H | Beethovens „Für Elise“ wurde erst lange nach seinem Tod veröffentlicht. | wahr | Das Albumblatt wurde 1867 entdeckt und herausgegeben — wer „Elise“ war, ist bis heute nicht sicher geklärt.
W H | Ennio Morricone hat nie einen regulären Oscar gewonnen. | falsch | Nach einem Ehrenoscar 2007 bekam er 2016 endlich auch den regulären Preis — für „The Hateful Eight“.
S M | Wie alt wurde Wolfgang Amadeus Mozart? | 35 | Jahre | 15 | 10 | 90 | Er starb sehr jung. ; Jünger als 40. ; Älter als 30. | Mozart starb 1791 in Wien — sein Requiem blieb unvollendet.
S U | Wie viele Minuten dauert eine typische Aufführung von Ravels „Boléro“? | 15 | Minuten | 20 | 2 | 60 | Länger als ein Popsong. ; Mehr als zehn Minuten. ; Weniger als 20 Minuten. | Ravel nannte das Werk selbst ein „Stück für Orchester ohne Musik“ — ein einziges Crescendo über rund eine Viertelstunde.
S U | Wie viele Oscars hat Filmkomponist John Williams gewonnen (Stand 2024)? | 5 | Oscars | 20 | 1 | 30 | Mehr als drei. ; Weniger als zehn. ; Mit über 50 Nominierungen ist er der meistnominierte lebende Mensch. | Seine Oscars gewann er unter anderem für „Der weiße Hai“, „Star Wars“, „E.T.“ und „Schindlers Liste“.
O E | Sortiere diese Epochen der Musikgeschichte — die früheste zuerst. | Barock = ca. 1600–1750 ; Wiener Klassik = ca. 1750–1820 ; Romantik = ca. 1820–1900 ; Moderne = ab ca. 1900 | Bach und Vivaldi gehören zur ältesten. ; Mozart und Haydn folgen. ; Wagner steht für die dritte Epoche. | Das Todesjahr von Johann Sebastian Bach, 1750, gilt oft als Ende des Barock.
O M | Welches Meisterwerk ist das älteste? Bringe diese Kompositionen in die zeitliche Reihenfolge. | Vivaldis „Vier Jahreszeiten“ = 1725 ; Mozarts „Zauberflöte“ = 1791 ; Beethovens 9. Sinfonie = 1824 ; Wagners „Ring des Nibelungen“ (Gesamtaufführung) = 1876 | Das Barockwerk ist am ältesten. ; Mozarts letzte Oper folgt. ; Wagners Zyklus eröffnete das Bayreuther Festspielhaus. | Die Neunte war Beethovens letzte vollendete Sinfonie — er komponierte sie fast völlig taub.
M E | Welche DREI dieser Werke sind Opern? | Die Zauberflöte ; Carmen ; La Traviata | Der Nussknacker ; Die vier Jahreszeiten ; Der Messias | Eines stammt von Mozart. ; Eines spielt in Sevilla. ; Eines stammt von Verdi. | Der Nussknacker ist ein Ballett, die „Vier Jahreszeiten“ sind Violinkonzerte und der „Messias“ ist ein Oratorium.
M H | Welche ZWEI dieser Komponisten schufen Meisterwerke, obwohl sie taub oder fast taub waren? | Ludwig van Beethoven ; Bedřich Smetana | Wolfgang Amadeus Mozart ; Frédéric Chopin ; Antonio Vivaldi ; Peter Tschaikowski | Einer stammte aus Bonn. ; Der andere aus Böhmen. ; Einer der beiden komponierte „Die Moldau“. | Smetana ertaubte 1874 — danach schrieb er seinen berühmten Zyklus „Mein Vaterland“ mit der „Moldau“.
C E | In welcher Stadt steht die Semperoper? | Dresden | Leipzig ; München ; Wien | Die Stadt liegt an der Elbe. ; Sie ist Landeshauptstadt von Sachsen. ; Das Opernhaus ist nach seinem Architekten Gottfried Semper benannt. | Das Gebäude warb jahrelang in einem bekannten Werbespot für eine Brauerei aus Radeberg.
C M | Welcher Komponist schrieb das „Weihnachtsoratorium“ mit dem Eingangschor „Jauchzet, frohlocket“? | Johann Sebastian Bach | Georg Friedrich Händel ; Joseph Haydn ; Felix Mendelssohn Bartholdy | Er war Thomaskantor in Leipzig. ; Das Werk entstand 1734. ; Er stammt aus Eisenach. | Das Oratorium besteht aus sechs Kantaten, die ursprünglich an sechs Festtagen zwischen Weihnachten und dem Dreikönigstag erklangen.
C M | Welches Instrument spielt der Konzertmeister eines Sinfonieorchesters? | Die Violine | Das Cello ; Die Flöte ; Das Klavier | Er sitzt vorne links neben dem Dirigenten. ; Er leitet vor dem Konzert das Einstimmen. ; Sein Instrument ist das höchste Streichinstrument. | Der Konzertmeister gilt als wichtigster Musiker nach dem Dirigenten — oft spielt er auch die Violinsoli.
C H | Welcher Komponist schrieb die „Ungarischen Tänze“? | Johannes Brahms | Franz Liszt ; Béla Bartók ; Antonín Dvořák | Er stammte aus Hamburg. ; Er lebte lange in Wien. ; Er schrieb auch ein berühmtes Wiegenlied. | Die ursprünglich für Klavier zu vier Händen geschriebenen Tänze wurden zu seinem größten Verkaufserfolg.
C U | Wie hieß der Wiener Hofkapellmeister, der im Film „Amadeus“ als eifersüchtiger Rivale Mozarts dargestellt wird? | Antonio Salieri | Joseph Haydn ; Christoph Willibald Gluck ; Leopold Mozart | Er stammte aus Italien. ; Er unterrichtete später Beethoven und Schubert. ; Das Gerücht, er habe Mozart vergiftet, gilt als widerlegt. | Der Film von Miloš Forman gewann acht Oscars — historisch waren Salieri und Mozart eher Kollegen als Todfeinde.
"""
