"""Extra questions, wave 2: Sport (format: see tools/content/merge_extra.py)."""
KAT = "sport"
REGION = "global"
DATA = r"""
@ bundesliga de
E E | Welcher Verein ist hier gesucht? | 🐝🟡⚫🧱 | Borussia Dortmund | Hertha BSC ; Werder Bremen ; VfL Wolfsburg | Er spielt im Ruhrgebiet. ; Seine Südtribüne heißt „Gelbe Wand“. ; Er gewann 1997 die Champions League. | Die Südtribüne des BVB ist die größte Stehplatztribüne Europas — rund 25.000 Fans stehen dort.
E M | Welcher Verein ist hier gesucht? | 🐐⚽⛪ | 1. FC Köln | Fortuna Düsseldorf ; Eintracht Frankfurt ; 1. FC Kaiserslautern | Das Maskottchen heißt Hennes. ; Der Verein spielt im Rheinland. ; Ganz in der Nähe steht eine berühmte Kathedrale. | Seit 1950 begleitet ein lebender Geißbock namens Hennes den FC zu den Heimspielen.
E M | Welcher Verein ist hier gesucht? | 🦅🏦🏆 | Eintracht Frankfurt | Hertha BSC ; FC Augsburg ; SC Freiburg | Das Wappentier ist ein Adler. ; Der Verein gewann 2022 die Europa League. ; Die Stadt ist ein Bankenzentrum am Main. | Frankfurt besiegte im Europa-League-Finale 2022 in Sevilla die Glasgow Rangers im Elfmeterschießen.
W M | Der SC Freiburg hat schon einmal den DFB-Pokal gewonnen. | falsch | Freiburg stand 2022 erstmals im Pokalfinale, verlor in Berlin aber im Elfmeterschießen gegen RB Leipzig.
W H | Bayer 04 Leverkusen wurde 2024 ohne eine einzige Ligapleite deutscher Meister. | wahr | Unter Trainer Xabi Alonso blieb Leverkusen in der Saison 2023/24 in allen 34 Ligaspielen ungeschlagen.
W M | Der VfL Wolfsburg wurde noch nie deutscher Meister. | falsch | Wolfsburg holte 2009 mit Trainer Felix Magath und den Torjägern Grafite und Edin Džeko die Meisterschaft.
S H | Wie viele Zuschauer fasst der Dortmunder Signal Iduna Park bei Bundesliga-Spielen ungefähr? | 81000 | Zuschauer | 10 | 30000 | 120000 | Mehr als 70.000. ; Es ist das größte Fußballstadion Deutschlands. ; Weniger als 90.000. | Bei internationalen Spielen sinkt die Kapazität, weil dort nur Sitzplätze erlaubt sind.
S U | In welchem Jahr wurde der 1. FC Kaiserslautern als Aufsteiger deutscher Meister? | 1998 | Jahr | 2 | 1980 | 2010 | Ende der 1990er-Jahre. ; Trainer war Otto Rehhagel. ; Ein Jahr nach dem Aufstieg. | Als bislang einziger Aufsteiger gewann Lautern 1998 direkt die Meisterschaft.
O M | Sortiere diese Vereine nach ihrem Gründungsjahr — den ältesten zuerst. | TSV 1860 München = 1860 ; Hertha BSC = 1892 ; FC Bayern München = 1900 ; RB Leipzig = 2009 | Einer trägt sein Gründungsjahr im Namen. ; Der Hauptstadtklub folgt. ; Der Verein aus Sachsen ist der jüngste. | RB Leipzig schaffte es in nur sieben Jahren von der fünften Liga in die Bundesliga.
O H | Sortiere diese Vereine nach ihrer ersten Bundesliga-Meisterschaft — den frühesten zuerst. | 1. FC Köln = 1964 ; Borussia Mönchengladbach = 1970 ; VfL Wolfsburg = 2009 ; Bayer 04 Leverkusen = 2024 | Der erste Bundesliga-Meister kommt zuerst. ; Die „Fohlen“ folgen Anfang der 1970er. ; „Vizekusen“ musste am längsten warten. | Leverkusen trug jahrelang den Spottnamen „Vizekusen“ — bis zum ersten Titel 2024.
M M | Welche DREI dieser Vereine gewannen schon den Europapokal der Landesmeister oder die Champions League? | FC Bayern München ; Borussia Dortmund ; Hamburger SV | Bayer 04 Leverkusen ; Borussia Mönchengladbach ; FC Schalke 04 | Einer siegte 1997 in München gegen Juventus. ; Einer gewann 1983 in Athen. ; Der Rekordmeister ist natürlich dabei. | Der HSV schlug 1983 Juventus Turin mit 1:0 — Leverkusen verlor das Finale 2002 gegen Real Madrid.
M M | Welche ZWEI dieser Vereine bestreiten das Revierderby? | Borussia Dortmund ; FC Schalke 04 | Hamburger SV ; Werder Bremen ; 1. FC Köln ; Bayer 04 Leverkusen | Beide stammen aus dem Ruhrgebiet. ; Die Städte liegen nur rund 30 Kilometer auseinander. ; Einer der Klubs heißt „die Knappen“. | Das Revierderby gilt als eines der emotionalsten Duelle im deutschen Fußball.
C E | Welcher Verein wird „die Werkself“ genannt? | Bayer 04 Leverkusen | VfL Wolfsburg ; RB Leipzig ; TSG Hoffenheim | Er wurde von Mitarbeitern eines Chemiekonzerns gegründet. ; Er spielt im Rheinland. ; Sein Stadion heißt BayArena. | Den Verein gründeten 1904 Beschäftigte der Bayer-Werke — daher der Spitzname.
C M | Wie heißt das Stadion des FC St. Pauli? | Millerntor-Stadion | Volksparkstadion ; Weserstadion ; Stadion an der Alten Försterei | Es liegt ganz nahe an der Reeperbahn. ; Der Name geht auf ein altes Stadttor zurück. ; Es liegt mitten im Hamburger Kiez. | Das Volksparkstadion gehört dem HSV, das Weserstadion Werder Bremen, die Alte Försterei Union Berlin.
C H | Welcher Spieler hat die meisten Bundesliga-Einsätze aller Zeiten (Stand 2024)? | Charly Körbel | Manfred Kaltz ; Oliver Kahn ; Klaus Fichtel | Er spielte seine ganze Karriere für einen Verein. ; Er kam auf 602 Spiele. ; Man nannte ihn „die treue Seele“ der Eintracht. | Karl-Heinz „Charly“ Körbel lief von 1972 bis 1991 ausschließlich für Eintracht Frankfurt auf.
C U | Wer trainierte Borussia Dortmund beim Champions-League-Sieg 1997? | Ottmar Hitzfeld | Jürgen Klopp ; Thomas Tuchel ; Matthias Sammer | Er stammt aus Lörrach nahe der Schweizer Grenze. ; Man nannte ihn „den General“. ; 2001 gewann er die Königsklasse auch mit dem FC Bayern. | Hitzfeld gewann die Champions League mit zwei deutschen Klubs — 1997 mit Dortmund, 2001 mit Bayern.

@ dfb_nationalelf de
E M | Welches Spiel ist hier gesucht? | 🇧🇷1️⃣🇩🇪7️⃣ | Das 7:1 gegen Brasilien | Das Wunder von Bern ; Das Wembley-Tor ; Die Schmach von Gijón | Es war ein WM-Halbfinale. ; Es fand 2014 in Belo Horizonte statt. ; Nach einer halben Stunde stand es schon 5:0. | Deutschland schlug Gastgeber Brasilien am 8. Juli 2014 — und wurde fünf Tage später Weltmeister.
E M | Welches Ereignis ist hier gesucht? | 🌧️⚽🏆🇨🇭 | Das Wunder von Bern | Das Sommermärchen ; Die Schmach von Córdoba ; Das Wunder von Lengede | Deutschland wurde zum ersten Mal Weltmeister. ; Im Finale lag man gegen Ungarn schon 0:2 zurück. ; Kapitän Fritz Walter liebte dieses Wetter. | Am 4. Juli 1954 siegte Deutschland in Bern mit 3:2 — Helmut Rahn schoss sechs Minuten vor Schluss das Siegtor.
E E | Welches Turnier ist hier gesucht? | ☀️🇩🇪⚽🎉 | Das Sommermärchen 2006 | Die EM 2024 ; Die WM 1974 ; Die EM 1988 | Deutschland war Gastgeber. ; Die Stimmung im Land war riesig. ; Am Ende wurde Deutschland Dritter. | Die WM 2006 gilt als großes Fußballfest — der Titel ging im Finale von Berlin an Italien.
W M | Die deutsche Frauen-Nationalmannschaft wurde zweimal Weltmeister. | wahr | Die DFB-Frauen gewannen die WM 2003 und 2007 — dazu kommen acht Europameistertitel.
W H | Miroslav Klose ist mit 16 Treffern Rekordtorschütze der WM-Geschichte. | wahr | Klose überholte 2014 im Halbfinale gegen Brasilien den Brasilianer Ronaldo, der 15 WM-Tore erzielt hatte.
W M | Deutschland gewann die Heim-EM 2024. | falsch | Die DFB-Elf schied im Viertelfinale gegen Spanien aus — Spanien wurde später auch Europameister.
S M | Wie viele Länderspiele bestritt Lothar Matthäus für Deutschland — bis heute Rekord? | 150 | Spiele | 10 | 50 | 300 | Mehr als 100. ; Eine runde Zahl. ; Weniger als 200. | Matthäus spielte zwischen 1982 und 1998 bei fünf Weltmeisterschaften — auch das ist Rekord.
S H | In welchem Jahr wurde Deutschland zum ersten Mal Fußball-Europameister? | 1972 | Jahr | 2 | 1950 | 2000 | In den 1970er-Jahren. ; Zwei Jahre vor dem zweiten WM-Titel. ; Das Finale gegen die Sowjetunion endete 3:0. | Die Elf um Beckenbauer, Netzer und Gerd Müller gilt vielen als die beste deutsche Mannschaft aller Zeiten.
O M | Sortiere diese Bundestrainer nach ihrem Amtsantritt — den frühesten zuerst. | Helmut Schön = 1964 ; Franz Beckenbauer = 1984 ; Joachim Löw = 2006 ; Julian Nagelsmann = 2023 | Der Weltmeistertrainer von 1974 kommt zuerst. ; Der „Kaiser“ hieß offiziell Teamchef. ; Der Jüngste übernahm 2023. | Joachim Löw war mit 15 Jahren im Amt der dienstälteste Bundestrainer nach Sepp Herberger.
O H | Sortiere diese Titel der DFB-Männer chronologisch — den frühesten zuerst. | WM-Titel in Bern = 1954 ; EM-Titel in Brüssel = 1972 ; WM-Titel in Rom = 1990 ; EM-Titel in London = 1996 | Der erste Titel kam in der Schweiz. ; Danach folgte der Triumph in Belgien. ; Das Golden Goal von Wembley ist der jüngste Titel. | Oliver Bierhoff entschied das EM-Finale 1996 gegen Tschechien mit dem ersten Golden Goal eines großen Turniers.
M M | Welche DREI dieser Spieler schossen in einem WM-Finale ein Tor für Deutschland? | Helmut Rahn ; Gerd Müller ; Mario Götze | Miroslav Klose ; Thomas Müller ; Philipp Lahm | Einer traf doppelt in Bern. ; Einer schoss 1974 in München das Siegtor. ; Einer traf 2014 in der Verlängerung. | Weitere deutsche Finaltorschützen sind Max Morlock, Paul Breitner und Andreas Brehme.
M H | Welche ZWEI dieser Torhüter standen bei einem WM-Titel im deutschen Tor? | Sepp Maier ; Manuel Neuer | Oliver Kahn ; Jens Lehmann ; Toni Schumacher ; René Adler | Einer hielt 1974 im Münchner Olympiastadion. ; Der andere 2014 in Rio. ; Beide spielten für den FC Bayern. | Beim dritten WM-Titel 1990 stand Bodo Illgner im Tor.
C M | In welchem Stadion gewann Deutschland 2014 das WM-Finale? | Maracanã | Estádio Mineirão ; Arena Corinthians ; Estádio Nacional | Es steht in Rio de Janeiro. ; Es gilt als Tempel des brasilianischen Fußballs. ; Hier fand schon das entscheidende Spiel von 1950 statt. | Deutschland schlug Argentinien am 13. Juli 2014 mit 1:0 nach Verlängerung.
C H | Wer war Kapitän der deutschen Weltmeister von 2014? | Philipp Lahm | Bastian Schweinsteiger ; Manuel Neuer ; Per Mertesacker | Er spielte meist als Außenverteidiger. ; Er trat kurz nach dem Titel aus der Nationalelf zurück. ; Er ist gebürtiger Münchner. | Lahm beendete seine Länderspielkarriere mit 30 Jahren — später wurde er Turnierdirektor der EM 2024.
C U | Wer erzielte im WM-Finale 1954 das erste deutsche Tor? | Max Morlock | Helmut Rahn ; Fritz Walter ; Ottmar Walter | Er spielte für den 1. FC Nürnberg. ; Sein Tor fiel schon in der 10. Minute. ; Das Nürnberger Stadion trägt heute seinen Namen. | Morlock verkürzte auf 1:2 — danach drehte Helmut Rahn mit zwei Treffern das Spiel.
C E | Welche Farbe hat das Heimtrikot der deutschen Nationalmannschaft traditionell? | Weiß | Schwarz ; Rot ; Grün | Dazu gehören schwarze Hosen. ; Die Farben gehen auf Preußen zurück. ; Es ist eine sehr helle Farbe. | Weiß und Schwarz sind die preußischen Landesfarben — die Auswärtstrikots waren lange grün.

@ fussball_international
E E | Welcher Spieler ist hier gesucht? | 🐐🇦🇷🏆 | Lionel Messi | Diego Maradona ; Sergio Agüero ; Ángel Di María | Er gewann 2022 die WM. ; Er spielte lange für den FC Barcelona. ; Er wurde achtmal zum Weltfußballer gekürt (Stand 2024). | Fans nennen Messi „GOAT“ — „Greatest of all time“, daher die Ziege.
E M | Welcher Verein ist hier gesucht? | 👹🔴⚽🏭 | Manchester United | FC Liverpool ; FC Arsenal ; Manchester City | Sein Spitzname lautet „Red Devils“. ; Sein Stadion heißt Old Trafford. ; Sir Alex Ferguson trainierte ihn 26 Jahre lang. | Unter Ferguson gewann United von 1986 bis 2013 unter anderem 13 englische Meistertitel.
E M | Welcher Verein ist hier gesucht? | 👑⚪🇪🇸 | Real Madrid | Atlético Madrid ; FC Sevilla ; FC Valencia | Die Mannschaft spielt ganz in Weiß. ; Ihr Stadion heißt Santiago Bernabéu. ; Sie ist Rekordsieger der Champions League. | „Real“ heißt königlich — den Titel verlieh König Alfons XIII. im Jahr 1920.
W M | Die Fußball-WM 2022 fand erstmals im November und Dezember statt. | wahr | Wegen der Sommerhitze in Katar wurde das Turnier in den Winter verlegt — das Finale war am 18. Dezember.
W H | Pelé wurde mit Brasilien dreimal Weltmeister. | wahr | Pelé gewann 1958, 1962 und 1970 — als einziger Spieler der Geschichte dreimal den WM-Titel.
W M | Italien hat öfter die Fußball-WM gewonnen als Deutschland. | falsch | Beide haben vier Titel — nur Brasilien hat mit fünf WM-Siegen mehr.
S M | Wie viele Mannschaften nehmen ab 2026 an der Fußball-WM der Männer teil? | 48 | Mannschaften | 10 | 16 | 80 | Mehr als bisher 32. ; Das Turnier findet in drei Ländern statt. ; Weniger als 50. | Die WM 2026 wird in den USA, Kanada und Mexiko ausgetragen — mit 104 statt 64 Spielen.
S H | Wie viele Tore erzielte Just Fontaine bei der WM 1958 — bis heute Rekord für ein einzelnes Turnier? | 13 | Tore | 20 | 5 | 30 | Mehr als zehn. ; Er spielte für Frankreich. ; Eine Zahl, die manchen Unglück bringt. | Der Franzose traf in nur sechs Spielen 13-mal — Gerd Müller kam 1970 auf zehn WM-Tore.
O M | Sortiere diese Klubs nach ihrem ersten Titel im Europapokal der Landesmeister bzw. der Champions League — den frühesten zuerst. | Real Madrid = 1956 ; FC Bayern München = 1974 ; FC Barcelona = 1992 ; FC Chelsea = 2012 | Die Spanier aus der Hauptstadt waren beim allerersten Finale dabei. ; Die Münchner folgen in den 1970ern. ; Der Londoner Klub ist der jüngste Sieger. | Chelsea gewann 2012 ausgerechnet in der Münchner Arena — im Elfmeterschießen gegen den FC Bayern.
O H | Sortiere diese Klubs nach der Zahl ihrer Titel im Landesmeister-Wettbewerb bzw. der Champions League — die wenigsten zuerst (Stand 2024). | Borussia Dortmund = 1 ; FC Barcelona = 5 ; AC Mailand = 7 ; Real Madrid = 15 | Der deutsche Klub hat einen Titel. ; Die Katalanen folgen. ; Die „Königlichen“ führen mit großem Abstand. | Real Madrid gewann allein die ersten fünf Ausgaben des Wettbewerbs von 1956 bis 1960.
M M | Welche DREI dieser Länder wurden schon Fußball-Weltmeister der Männer? | Uruguay ; England ; Spanien | Niederlande ; Portugal ; Belgien | Einer war der allererste Weltmeister. ; Einer gewann 1966 im eigenen Land. ; Einer siegte 2010 in Südafrika. | Die Niederlande standen dreimal im WM-Finale — und verloren alle drei.
M H | Welche ZWEI dieser Spieler gewannen den Ballon d'Or? | Luka Modrić ; Karim Benzema | Robert Lewandowski ; Neymar ; Mohamed Salah ; Thomas Müller | Einer ist Kroate. ; Der andere ist Franzose. ; Beide spielten bei Real Madrid. | Modrić gewann 2018, Benzema 2022 — 2020 fiel die Wahl wegen der Pandemie aus.
C M | Welcher Spieler erzielte im WM-Finale 2022 drei Tore und verlor trotzdem? | Kylian Mbappé | Lionel Messi ; Julián Álvarez ; Olivier Giroud | Er spielte für Frankreich. ; Seine Mannschaft verlor das Elfmeterschießen. ; Er stammt aus einem Vorort von Paris. | Nach 3:3 gewann Argentinien — Mbappé traf als zweiter Spieler überhaupt dreimal in einem WM-Finale.
C H | Welcher englische Klub blieb in der Saison 2003/04 in der Premier League ungeschlagen? | FC Arsenal | Manchester United ; FC Chelsea ; FC Liverpool | Man nannte die Mannschaft „The Invincibles“. ; Trainer war Arsène Wenger. ; Der Klub stammt aus Nordlondon. | Arsenal holte in dieser Saison 26 Siege und 12 Unentschieden aus 38 Spielen.
C U | Nach wem ist der Pokal der Fußball-Europameisterschaft benannt? | Henri Delaunay | Jules Rimet ; Gianni Infantino ; Michel Platini | Er war ein französischer Funktionär. ; Er war der erste Generalsekretär der UEFA. ; Er starb 1955, vor der ersten EM. | Die Idee eines europäischen Nationenturniers stammte von Delaunay — die erste EM fand 1960 statt.
C E | Welcher Fußballer wird „CR7“ genannt? | Cristiano Ronaldo | Ronaldinho ; Ronaldo Nazário ; Rafael Leão | Er stammt von der Insel Madeira. ; Er trug meist die Rückennummer 7. ; Er spielte für Manchester United, Real Madrid und Juventus. | Ronaldo ist Rekordtorschütze der Champions League und der Länderspiel-Geschichte (Stand 2024).

@ olympia_wintersport
E E | Welche Sportart ist hier gesucht? | 🥌🧹🧊 | Curling | Eisstockschießen ; Eishockey ; Bobfahren | Man lässt Granitsteine übers Eis gleiten. ; Die Mitspieler wischen vor dem Stein. ; Der Sport stammt aus Schottland. | Durch das Wischen entsteht ein hauchdünner Wasserfilm — der Stein gleitet weiter und gerader.
E E | Welche Sportart ist hier gesucht? | ⛷️🔫🎯 | Biathlon | Nordische Kombination ; Skispringen ; Skilanglauf | Sie verbindet zwei Disziplinen. ; Für jeden Fehlschuss gibt es eine Strafrunde. ; Geschossen wird liegend und stehend. | Biathlon geht auf militärische Patrouillenläufe zurück — olympisch ist es seit 1960.
E M | Welche Sportart ist hier gesucht? | 🏊🚴🏃 | Triathlon | Moderner Fünfkampf ; Duathlon ; Siebenkampf | Es sind drei Disziplinen hintereinander. ; Die längste Variante heißt Ironman. ; Olympisch ist der Sport seit 2000. | Bei Olympia schwimmen die Athleten 1,5 Kilometer, radeln 40 und laufen 10 Kilometer.
W M | Bei den ersten Olympischen Spielen 1896 bekamen die Sieger keine Goldmedaille. | wahr | Die Sieger erhielten eine Silbermedaille und einen Olivenzweig — Gold für Platz eins gibt es erst seit 1904.
W H | Die fünf olympischen Ringe stehen für die fünf bewohnten Kontinente. | wahr | Pierre de Coubertin entwarf das Symbol 1913 — seine Farben finden sich in allen Flaggen der damaligen Teilnehmer.
W M | Deutschland war noch nie Gastgeber Olympischer Winterspiele. | falsch | 1936 fanden die Winterspiele in Garmisch-Partenkirchen statt — im selben Jahr wie die Sommerspiele in Berlin.
S M | In welchem Jahr fanden die ersten Olympischen Winterspiele statt? | 1924 | Jahr | 3 | 1896 | 1960 | In den 1920er-Jahren. ; Austragungsort war Chamonix. ; Nach dem Ersten Weltkrieg. | Die „Internationale Wintersportwoche“ in Chamonix wurde nachträglich zu den ersten Winterspielen erklärt.
S U | Wie viele Meter misst eine Runde auf einer olympischen Eisschnelllaufbahn? | 400 | Meter | 10 | 100 | 1000 | Genauso lang wie eine Stadionrunde in der Leichtathletik. ; Mehr als 300 Meter. ; Eine glatte Hunderterzahl. | Gelaufen wird paarweise auf zwei Bahnen — auf der Gegengeraden wechseln die Läufer die Spur.
O M | Sortiere diese Olympia-Gastgeberstädte chronologisch — die früheste zuerst. | Berlin = 1936 ; München = 1972 ; Sydney = 2000 ; Paris = 2024 | Die deutsche Hauptstadt kommt zuerst. ; Die bayerische Landeshauptstadt folgt. ; Die französische Hauptstadt ist die jüngste. | Paris war 2024 schon zum dritten Mal Gastgeber — nach 1900 und 1924.
O M | Sortiere diese Gastgeber Olympischer Winterspiele chronologisch — den frühesten zuerst. | Chamonix = 1924 ; Innsbruck = 1964 ; Lillehammer = 1994 ; Peking = 2022 | Der französische Ort war der allererste. ; Die Tiroler folgen in den 1960ern. ; Die chinesische Hauptstadt ist die jüngste. | Peking ist die erste Stadt, die sowohl Sommer- (2008) als auch Winterspiele (2022) ausgerichtet hat.
M M | Welche DREI dieser Sportarten gehören zu den Olympischen Winterspielen? | Skeleton ; Rennrodeln ; Nordische Kombination | Triathlon ; Moderner Fünfkampf ; Rudern | Bei einer liegt man kopfüber auf dem Schlitten. ; Bei einer liegt man rücklings auf dem Schlitten. ; Eine verbindet Skispringen und Langlauf. | Deutschland gehört im Rodeln und in der Nordischen Kombination seit Jahrzehnten zur Weltspitze.
M H | Welche ZWEI dieser Länder waren schon Gastgeber Olympischer Winterspiele? | Norwegen ; Japan | Brasilien ; Spanien ; Australien ; Griechenland | Eines richtete 1952 und 1994 aus. ; Das andere 1972 und 1998. ; Beide Länder sind für viel Schnee bekannt. | Norwegen war in Oslo und Lillehammer Gastgeber, Japan in Sapporo und Nagano.
C E | Welche Farbe hat der Ring ganz links im olympischen Symbol? | Blau | Gelb ; Schwarz ; Grün | Oben stehen drei Ringe, unten zwei. ; Der mittlere obere Ring ist schwarz. ; Es ist die Farbe des Himmels. | Die obere Reihe ist blau, schwarz und rot, die untere gelb und grün.
C M | Welcher Sprung im Eiskunstlauf wird als einziger vorwärts abgesprungen? | Axel | Rittberger ; Lutz ; Salchow | Er ist nach einem Norweger benannt. ; Der dreifache hat dreieinhalb Umdrehungen. ; Er gilt als schwierigster Sprung. | Axel Paulsen sprang ihn 1882 zum ersten Mal — 2022 gelang Ilia Malinin im Wettkampf der erste Vierfach-Axel.
C H | Welche deutsche Biathletin gewann 2008, 2010 und 2012 den Gesamtweltcup? | Magdalena Neuner | Laura Dahlmeier ; Kati Wilhelm ; Andrea Henkel | Sie stammt aus Wallgau in Oberbayern. ; Sie beendete ihre Karriere schon mit 25 Jahren. ; Sie gewann 2010 in Vancouver zweimal Gold. | Neuner wurde zwölfmal Weltmeisterin — und hörte 2012 auf dem Höhepunkt ihrer Karriere auf.
C U | Welches Land hat bei Olympischen Winterspielen die meisten Medaillen gewonnen (Stand 2024)? | Norwegen | USA ; Deutschland ; Russland | Das Land ist klein, aber schneereich. ; Langlauf ist dort Volkssport. ; Die Hauptstadt ist Oslo. | Norwegen führt den ewigen Medaillenspiegel der Winterspiele vor den USA und Deutschland an.

@ us_sport
E E | Welches Sportereignis ist hier gesucht? | 🏈🏆🎤📺 | Super Bowl | World Series ; Stanley Cup ; NBA Finals | Es ist das Endspiel einer Football-Liga. ; Die Halbzeitshow ist legendär. ; Es findet meist im Februar statt. | Das NFL-Finale gehört zu den meistgesehenen TV-Ereignissen der USA — Werbespots kosten Millionen.
E M | Welche Trophäe ist hier gesucht? | 🏒🏆❄️ | Stanley Cup | Grey Cup ; Davis Cup ; Commissioner's Trophy | Sie wird im Eishockey vergeben. ; Jeder Spieler des Siegerteams darf sie einen Tag mit nach Hause nehmen. ; Sie ist nach einem britischen Adligen benannt. | Lord Stanley of Preston stiftete den Pokal 1892 — die Namen der Sieger werden eingraviert.
E E | Welche Sportart ist hier gesucht? | ⚾🧢🌭 | Baseball | Cricket ; Rounders ; Lacrosse | Ein Spiel hat neun Innings. ; Der „Home Run“ ist der beste Schlag. ; Die Finalserie heißt World Series. | Im Stadion gehören Hotdogs und Erdnüsse zum Baseball wie Bratwurst zur Bundesliga.
W M | Ein NBA-Basketballkorb hängt rund drei Meter über dem Boden. | wahr | Genau 10 Fuß, also 3,05 Meter — diese Höhe legte Erfinder James Naismith schon 1891 fest.
W H | Dirk Nowitzki gewann mit den Dallas Mavericks die NBA-Meisterschaft. | wahr | 2011 besiegten die Mavericks die Miami Heat — Nowitzki wurde als bester Spieler der Finalserie ausgezeichnet.
W M | Im American Football ist ein Touchdown sieben Punkte wert. | falsch | Ein Touchdown bringt sechs Punkte — mit dem anschließenden Extrapunkt sind es meist sieben.
S H | Wie viele Punkte erzielte Wilt Chamberlain 1962 in einem einzigen NBA-Spiel — bis heute Rekord? | 100 | Punkte | 10 | 40 | 200 | Mehr als 80. ; Eine glatte dreistellige Zahl. ; Kein anderer Spieler schaffte das je. | Chamberlain gelang das am 2. März 1962 gegen die New York Knicks.
S U | Wie viele Yards lang ist ein American-Football-Feld ohne die beiden Endzonen? | 100 | Yards | 5 | 50 | 200 | Eine glatte Zahl. ; Rund 91 Meter. ; Die Endzonen kommen noch hinzu. | Mit den beiden je zehn Yards tiefen Endzonen ist das Feld 120 Yards lang.
O M | Sortiere diese NBA-Legenden nach ihrer ersten NBA-Saison — den frühesten zuerst. | Magic Johnson = 1979 ; Michael Jordan = 1984 ; Kobe Bryant = 1996 ; LeBron James = 2003 | Der Lakers-Spielmacher der 80er beginnt. ; Die Nummer 23 der Bulls folgt. ; Der „King“ aus Akron ist der jüngste. | Kobe Bryant und LeBron James kamen beide direkt von der Highschool in die NBA.
O H | Sortiere diese Basketballer nach der Zahl ihrer NBA-Titel — die wenigsten zuerst. | Dirk Nowitzki = 1 ; LeBron James = 4 ; Michael Jordan = 6 ; Bill Russell = 11 | Der Deutsche hat einen Titel. ; „King James“ folgt. ; Der Celtics-Center der 1960er ist Rekordhalter. | Bill Russell gewann mit den Boston Celtics elf Titel in 13 Jahren.
M M | Welche DREI dieser Teams spielen in der NFL? | Green Bay Packers ; Dallas Cowboys ; Kansas City Chiefs | Chicago Bulls ; New York Yankees ; Boston Celtics | Eines kommt aus einer Kleinstadt in Wisconsin. ; Eines ist nach Viehtreibern benannt. ; Eines gewann den Super Bowl 2023 und 2024. | Die Bulls und die Celtics spielen Basketball, die Yankees Baseball.
M H | Welche ZWEI dieser Deutschen spielten in der NBA? | Dennis Schröder ; Franz Wagner | Dirk Bauermann ; Tim Wiese ; Timo Boll ; Pascal Roller | Einer stammt aus Braunschweig. ; Der andere aus Berlin, sein Bruder spielt ebenfalls in der NBA. ; Beide wurden 2023 Basketball-Weltmeister. | Deutschland gewann 2023 in Manila zum ersten Mal die Basketball-WM.
C M | Welcher Basketballer trug bei den Chicago Bulls die Rückennummer 23? | Michael Jordan | Scottie Pippen ; Dennis Rodman ; Kobe Bryant | Er gewann mit den Bulls sechs Titel. ; Seine Schuhe von Nike sind Kult. ; Zwischendurch spielte er kurz Baseball. | Die ersten Air-Jordan-Schuhe kamen 1985 auf den Markt — heute ein Milliardengeschäft.
C H | Welcher Quarterback gewann die meisten Super Bowls? | Tom Brady | Peyton Manning ; Joe Montana ; Patrick Mahomes | Er gewann sieben Titel. ; Sechs davon mit den New England Patriots. ; Er spielte bis zum Alter von 45 Jahren. | Seinen letzten Super Bowl gewann Brady 2021 mit den Tampa Bay Buccaneers.
C M | Wie heißt die Finalserie der nordamerikanischen Baseball-Profiliga? | World Series | Super Series ; Grand Finals ; Home Run Cup | Obwohl fast nur US-Teams spielen, steckt „Welt“ im Namen. ; Gespielt wird im Modus „Best of seven“. ; Sie findet im Oktober statt. | Die erste World Series fand 1903 statt — die New York Yankees sind Rekordsieger.
C U | Welchen Spitznamen trägt der Eishockeystar Wayne Gretzky? | The Great One | The Iceman ; The Rocket ; Mr. Hockey | Er stammt aus Kanada. ; Seine Rückennummer 99 wurde in der ganzen NHL gesperrt. ; Der Spitzname bedeutet „Der Große“. | Gretzky hält bis heute zahlreiche NHL-Rekorde, etwa für die meisten Scorerpunkte.

@ motorsport_formel1
E E | Welches Rennen ist hier gesucht? | 🏎️🎰🛥️🏙️ | Großer Preis von Monaco | Großer Preis von Singapur ; Großer Preis von Italien ; Großer Preis von Frankreich | Es führt durch enge Straßen. ; Gefahren wird am Hafen mit Jachten und am Casino vorbei. ; Das Land ist der zweitkleinste Staat der Welt. | Monaco gilt als Juwel der Formel 1 — auf dem Stadtkurs ist Überholen fast unmöglich.
E M | Welches Rennen ist hier gesucht? | 🏁2️⃣4️⃣⏰🇫🇷 | 24 Stunden von Le Mans | 24 Stunden vom Nürburgring ; Rallye Dakar ; Indianapolis 500 | Es ist ein Langstreckenrennen. ; Mehrere Fahrer wechseln sich am Steuer ab. ; Es findet in Westfrankreich statt. | Das Rennen gibt es seit 1923 — gefahren wird Tag und Nacht ohne Pause.
E E | Welches Formel-1-Team ist hier gesucht? | 🐂🐂🥤🏎️ | Red Bull Racing | McLaren ; Williams ; Alpine | Das Logo zeigt zwei Stiere. ; Das Team gehört einem Getränkehersteller. ; Sebastian Vettel wurde hier viermal Weltmeister. | Red Bull übernahm 2005 den Jaguar-Rennstall — Vettel gewann dort von 2010 bis 2013 vier Titel in Folge.
W M | Sebastian Vettel wurde viermal in Folge Formel-1-Weltmeister. | wahr | Mit Red Bull gewann Vettel 2010 bis 2013 — beim ersten Titel war er mit 23 Jahren der jüngste Weltmeister.
W H | Der Formel-1-Kalender 2024 umfasste mehr als 20 Rennen. | wahr | Mit 24 Grand Prix gab es 2024 so viele Rennen wie nie zuvor in einer Saison.
W M | Lewis Hamilton fuhr in der Formel 1 immer für Mercedes. | falsch | Hamilton startete 2007 bei McLaren und wurde dort 2008 Weltmeister — ab 2013 fuhr er für Mercedes.
S H | Wie viele Runden hat der Große Preis von Monaco? | 78 | Runden | 10 | 40 | 120 | Mehr als 70. ; Weniger als 80. ; Der Stadtkurs ist nur gut drei Kilometer lang. | Monaco ist das einzige Rennen, das unter der sonst üblichen Distanz von 305 Kilometern bleibt.
S U | In welchem Jahr wurde die erste Formel-1-Weltmeisterschaft ausgetragen? | 1950 | Jahr | 2 | 1920 | 1980 | Wenige Jahre nach dem Zweiten Weltkrieg. ; Eine runde Jahreszahl. ; Das erste Rennen fand in Silverstone statt. | Erster Weltmeister wurde der Italiener Giuseppe Farina auf Alfa Romeo.
O M | Sortiere diese Formel-1-Weltmeister nach ihrem ersten Titel — den frühesten zuerst. | Niki Lauda = 1975 ; Ayrton Senna = 1988 ; Michael Schumacher = 1994 ; Max Verstappen = 2021 | Der Österreicher kommt zuerst. ; Der Brasilianer folgt. ; Der Niederländer ist der jüngste Champion. | Verstappen sicherte sich 2021 den Titel erst in der letzten Runde des letzten Rennens in Abu Dhabi.
O H | Sortiere diese Fahrer nach der Zahl ihrer WM-Titel — die wenigsten zuerst. | Nico Rosberg = 1 ; Fernando Alonso = 2 ; Ayrton Senna = 3 ; Sebastian Vettel = 4 | Der Deutsche trat direkt nach seinem Titel zurück. ; Der Spanier folgt. ; Der Heppenheimer hat am meisten. | Nico Rosberg beendete seine Karriere 2016 nur fünf Tage nach dem WM-Gewinn.
M M | Welche DREI dieser Fahrer wurden Formel-1-Weltmeister? | Kimi Räikkönen ; Jenson Button ; Nigel Mansell | Rubens Barrichello ; Mark Webber ; David Coulthard | Einer ist ein wortkarger Finne. ; Einer siegte 2009 mit einem neuen Team. ; Einer ist ein Brite mit Schnurrbart. | Barrichello, Webber und Coulthard gewannen viele Rennen — aber nie die WM.
M H | Welche ZWEI dieser Fahrer wurden mit Mercedes Formel-1-Weltmeister? | Lewis Hamilton ; Nico Rosberg | Sebastian Vettel ; Max Verstappen ; Fernando Alonso ; Kimi Räikkönen | Einer ist Brite. ; Der andere ist Deutscher. ; Mercedes dominierte ab 2014 die Hybrid-Ära. | Von 2014 bis 2020 holte Mercedes sieben Fahrertitel in Folge — sechs gingen an Hamilton, einer 2016 an Rosberg.
C E | Welche Flagge zeigt im Motorsport das Ende des Rennens an? | Die schwarz-weiß karierte Flagge | Die rote Flagge ; Die gelbe Flagge ; Die grüne Flagge | Sie hat ein Muster. ; Sie wird am Ziel geschwenkt. ; Sie hat zwei Farben ohne Buntton. | Rot bedeutet Rennabbruch, Gelb Gefahr und Grün freie Fahrt.
C M | Für welches Land fährt Max Verstappen? | Niederlande | Belgien ; Österreich ; Dänemark | Geboren wurde er in Belgien. ; Seine Fans tragen Orange. ; Sein Vater Jos fuhr ebenfalls Formel 1. | Beim Heimrennen in Zandvoort färben Verstappens Fans die Tribünen orange.
C H ab12 | Welcher Fahrer verunglückte 1994 beim Großen Preis von San Marino im Rennen tödlich? | Ayrton Senna | Gilles Villeneuve ; Jochen Rindt ; Niki Lauda | Er war dreifacher Weltmeister. ; Er stammte aus São Paulo. ; Er fuhr damals für Williams. | Sennas Unfall in Imola führte zu tiefgreifenden Sicherheitsreformen in der Formel 1.
C U ab12 | Welcher Rennfahrer ist bislang der einzige, der nach seinem Tod Formel-1-Weltmeister wurde? | Jochen Rindt | Niki Lauda ; Gerhard Berger ; Alexander Wurz | Er fuhr für Österreich. ; Er verunglückte 1970 in Monza tödlich. ; Niemand holte danach noch genug Punkte, um ihn zu überholen. | Rindt führte die WM 1970 so deutlich, dass ihn bis Saisonende keiner mehr einholte.

@ sport_rekorde_kurioses
E E | Welche Sportart ist hier gesucht? | 🏓🇨🇳🥇 | Tischtennis | Badminton ; Squash ; Tennis | Der Ball ist klein und leicht. ; Gespielt wird an einer Platte. ; Ein asiatisches Land dominiert den Sport seit Jahrzehnten. | China gewann seit 1988 den Großteil aller olympischen Goldmedaillen im Tischtennis.
E M | Welche Sportart ist hier gesucht? | 🐎🏑👑 | Polo | Lacrosse ; Hockey ; Cricket | Man spielt sie auf Pferderücken. ; Mit Schlägern treibt man einen Ball. ; Sie gilt als Sport der Reichen. | Ein Polospiel ist in Abschnitte namens „Chukka“ eingeteilt — dazwischen wechseln die Spieler die Pferde.
E H | Welche Sportart ist hier gesucht? | 🧗🧱⏱️🏅 | Sportklettern | Turnen ; Gewichtheben ; Parkour | Sie ist seit 2021 olympisch. ; Es gibt die Disziplinen Speed, Bouldern und Lead. ; Man hält sich an bunten Griffen fest. | Beim Speed-Klettern jagen die Athleten in unter fünf Sekunden eine 15 Meter hohe Wand hinauf.
W E | Ein Golfball hat Dellen, damit er weiter fliegt. | wahr | Die Dellen verwirbeln die Luft am Ball — so sinkt der Luftwiderstand, und er fliegt fast doppelt so weit.
W H | Im professionellen Sumo gibt es Gewichtsklassen. | falsch | Im Profi-Sumo kämpft jeder gegen jeden — auch ein leichter Ringer kann auf einen doppelt so schweren Gegner treffen.
W M | Roger Federer ist Rekordsieger von Wimbledon bei den Männern (Stand 2024). | wahr | Federer gewann den Rasenklassiker achtmal — Novak Djoković kommt auf sieben Titel.
S H | Wie viele Minuten dauerte das längste Tennismatch der Geschichte (Wimbledon 2010) ungefähr? | 665 | Minuten | 10 | 200 | 1500 | Mehr als zehn Stunden. ; Es ging über drei Tage. ; Der fünfte Satz endete 70:68. | John Isner besiegte Nicolas Mahut nach 11 Stunden und 5 Minuten reiner Spielzeit.
S U | Wie viele Meter weit sprang Mike Powell 1991 bei seinem Weitsprung-Weltrekord? | 8.95 | Meter | 5 | 6 | 10 | Deutlich mehr als acht Meter. ; Knapp unter neun Metern. ; Der Rekord hält bis heute (Stand 2024). | Powell übertraf bei der WM in Tokio den legendären Rekord von Bob Beamon aus dem Jahr 1968.
O M | Sortiere diese Wurf- und Sportgeräte nach ihrem Gewicht — das leichteste zuerst. | Speer (Männer) = 800 g ; Diskus (Männer) = 2 kg ; Kugel (Männer) = 7,26 kg ; Curlingstein = ca. 19 kg | Das spitze Gerät ist am leichtesten. ; Die Scheibe folgt. ; Der Granitstein vom Eis ist mit Abstand am schwersten. | Die Männerkugel wiegt genau 16 englische Pfund — daher das krumme Gewicht von 7,26 Kilogramm.
O E | Sortiere diese Tennis-Grand-Slams nach ihrem Termin im Jahr — den frühesten zuerst. | Australian Open = Januar ; French Open = Mai/Juni ; Wimbledon = Juni/Juli ; US Open = August/September | Das Turnier auf der Südhalbkugel eröffnet die Saison. ; Paris folgt im Frühsommer. ; New York beschließt das Jahr. | Wer alle vier Turniere in einem Kalenderjahr gewinnt, schafft den „Grand Slam“ — Steffi Graf gelang das 1988.
M E | Welche DREI dieser Sportarten spielt man über ein Netz? | Volleyball ; Badminton ; Tennis | Golf ; Bowling ; Curling | Bei einer schlägt man einen Federball. ; Bei einer darf der Ball nicht den Boden berühren. ; Bei einer spielt man mit Filzball. | Beim Badminton erreicht der Federball Geschwindigkeiten von über 400 Kilometern pro Stunde.
M H | Welche ZWEI dieser Tennisspielerinnen stammen aus Deutschland? | Angelique Kerber ; Andrea Petković | Martina Hingis ; Iga Świątek ; Kim Clijsters ; Monica Seles | Eine gewann 2016 zwei Grand-Slam-Turniere. ; Die andere wurde nach ihrer Karriere TV-Moderatorin. ; Die falschen stammen aus der Schweiz, Polen, Belgien und Serbien. | Kerber gewann 2016 die Australian Open und die US Open sowie 2018 Wimbledon.
C E | Wie heißt die Sportart, bei der man Pfeile auf eine Scheibe wirft? | Darts | Bogenschießen ; Boccia ; Kegeln | Die höchste Aufnahme mit drei Pfeilen ist 180. ; Die WM findet im Londoner „Ally Pally“ statt. ; Die Scheibe hängt 1,73 Meter hoch. | Bei der Darts-WM verkleiden sich die Fans traditionell bunt und singen stundenlang.
C M | Welcher Schwimmstil ist der schnellste? | Kraul | Brust ; Rücken ; Schmetterling | Im Freistil wählen ihn fast alle. ; Die Arme ziehen abwechselnd durchs Wasser. ; Auf Englisch heißt er „Crawl“. | Weil Freistil jeden Stil erlaubt, schwimmen dort praktisch alle Kraul — er ist am schnellsten.
C H | In welcher Disziplin gibt es den „Fosbury-Flop“? | Hochsprung | Stabhochsprung ; Weitsprung ; Turmspringen | Man springt rückwärts über eine Latte. ; Ein Amerikaner machte die Technik 1968 in Mexiko-Stadt berühmt. ; Man braucht keinen Stab. | Dick Fosbury gewann damit Olympiagold — heute springt fast jeder Hochspringer so.
C U | Wie viele Punkte bringt die schwarze Kugel beim Snooker? | 7 | 5 ; 6 ; 10 | Sie ist die wertvollste Kugel. ; Die pinke Kugel bringt einen Punkt weniger. ; Eine Glückszahl. | Das Maximum-Break von 147 Punkten erreicht man mit 15 Roten, 15 Schwarzen und allen Farben.
"""
