"""Extra questions, wave 2: Technik & Autos (format: see tools/content/merge_extra.py)."""
KAT = "technik_autos"
REGION = "global"
DATA = r"""
@ autos_marken
E E | Welche Automarke ist hier gesucht? | 🐆🚗🇬🇧 | Jaguar | Land Rover ; Aston Martin ; Bentley | Die Marke stammt aus England. ; Ihr Markenzeichen ist eine springende Raubkatze. ; Sie gehört heute zum indischen Tata-Konzern. | Die Firma hieß anfangs „SS Cars“ — nach dem Zweiten Weltkrieg wurde das belastete Kürzel 1945 gestrichen.
E E | Welches Automodell ist hier gesucht? | 🐎🇺🇸🏁 | Ford Mustang | Chevrolet Camaro ; Dodge Charger ; Pontiac Firebird | Es ist ein amerikanisches Sportcoupé. ; Es kam 1964 auf den Markt. ; Im Logo galoppiert ein Wildpferd. | Der Mustang begründete die Klasse der „Pony Cars“ — in den ersten zwölf Monaten wurden über 400.000 Stück verkauft.
E M | Welches Auto ist hier gesucht? | 🦆🚗🇫🇷 | Citroën 2CV | Renault 4 ; Peugeot 205 ; Fiat 500 | Das Auto stammt aus Frankreich. ; In Deutschland nennt man es liebevoll „Ente“. ; Es wurde von 1949 bis 1990 gebaut. | Laut Lastenheft sollte der „Döschwo“ vier Personen und einen Korb Eier über einen Acker fahren können, ohne dass ein Ei zerbricht.
E E | Welche Automarke ist hier gesucht? | 🧠🚗🅿️ | Smart | Mini ; Fiat ; Renault | Die Autos sind winzige Zweisitzer. ; Man kann sie quer in Parklücken stellen. ; Der Name bedeutet auf Englisch „schlau“. | Der Markenname steht für „Swatch Mercedes ART“ — die Idee stammte vom Swatch-Chef Nicolas Hayek.
E M | Welche Automarke ist hier gesucht? | 👼🚗👑🇬🇧 | Rolls-Royce | Bentley ; Maybach ; Aston Martin | Die Marke steht für britischen Luxus. ; Auf der Kühlerhaube thront eine geflügelte Figur. ; Heute gehört die Marke zu BMW. | Die Kühlerfigur heißt „Spirit of Ecstasy“ — bei modernen Modellen versinkt sie bei einem Diebstahlversuch blitzschnell in der Haube.
W M | Der Markenname „Audi“ ist die lateinische Übersetzung des Nachnamens von Firmengründer August Horch. | wahr | „Horch!“ heißt auf Lateinisch „Audi!“ — Horch hatte seine erste Firma verlassen und durfte den eigenen Namen nicht mehr verwenden.
W E | Die Automarke Kia stammt aus Japan. | falsch | Kia kommt aus Südkorea und ist eng mit dem Hyundai-Konzern verbunden, der 1998 die Mehrheit übernahm.
S M log | Wie viele Millionen Exemplare des Ford Model T wurden zwischen 1908 und 1927 gebaut? | 15 | Mio. Stück | 20 | 1 | 100 | Mehr als zehn Millionen. ; Weniger als der VW Käfer mit gut 21 Millionen. ; Zwischen 14 und 16 Millionen. | Dank Fließband sank der Preis der „Tin Lizzie“ von rund 850 auf unter 300 Dollar.
S U | Welche Geschwindigkeit erreichte ein Bugatti Chiron bei seiner Rekordfahrt 2019 (in km/h)? | 490 | km/h | 10 | 200 | 800 | Deutlich mehr als 400 km/h. ; Als erstes Auto eines Serienherstellers knackte er 300 Meilen pro Stunde. ; Knapp unter 500. | Die Rekordfahrt mit 490,48 km/h fand auf der VW-Teststrecke Ehra-Lessien bei Wolfsburg statt.
O U | Sortiere diese Länder nach der Zahl der 2023 gebauten Kraftfahrzeuge — das Land mit den wenigsten zuerst. | Deutschland = ca. 4,1 Mio. ; Japan = ca. 9 Mio. ; USA = ca. 10,6 Mio. ; China = ca. 30 Mio. | Das Autoland Deutschland liegt hier ganz hinten. ; Japan und die USA liegen dicht beieinander. ; Ein Land baut fast ein Drittel aller Fahrzeuge weltweit. | China ist seit 2009 der größte Autoproduzent der Welt — 2023 lief dort rund jedes dritte Fahrzeug weltweit vom Band.
M E | Welche DREI dieser Automarken stammen aus Japan? | Mazda ; Subaru ; Suzuki | Kia ; Hyundai ; Škoda | Eine Marke trägt einen Sternhaufen im Logo. ; Eine andere baut auch Motorräder. ; Zwei der falschen stammen aus demselben asiatischen Nachbarland. | Subarus Logo zeigt sechs Sterne — „Subaru“ ist der japanische Name des Sternhaufens der Plejaden.
M H | Welche ZWEI dieser Marken gehören zum Stellantis-Konzern (Stand 2024)? | Peugeot ; Opel | Renault ; Volvo ; Škoda ; Toyota | Der Konzern entstand 2021 aus einer Fusion. ; Eine Marke hat einen Löwen im Logo. ; Die andere trägt einen Blitz. | Stellantis entstand aus PSA und Fiat Chrysler — dazu gehören auch Citroën, Fiat, Jeep und Alfa Romeo.
C E | Wofür steht die Leistungsangabe „PS“ beim Auto? | Pferdestärke | Pferdesport ; Pumpenstärke ; Pleuelschub | Früher verglich man Motoren mit Zugtieren. ; Heute wird die Leistung offiziell in Kilowatt angegeben. ; Das Tier zog einst Kutschen. | Eine Pferdestärke entspricht rund 0,735 Kilowatt — die Einheit gilt offiziell als veraltet, ist im Alltag aber unverwüstlich.
C M | Wie heißt die Sportwagen-Tochter von Mercedes-Benz mit Sitz in Affalterbach? | AMG | Brabus ; M GmbH ; Alpina | Die Firma begann als Rennmotoren-Schmiede. ; Die Buchstaben stehen für zwei Gründer und einen Ort. ; Ihr Motto lautet „One man, one engine“. | AMG steht für Aufrecht, Melcher und Großaspach — den Geburtsort von Hans Werner Aufrecht.
C M | In welcher Stadt steht die „Gläserne Manufaktur“ von Volkswagen? | Dresden | Wolfsburg ; Leipzig ; Zwickau | Die Stadt liegt an der Elbe. ; Früher lief hier die Luxuslimousine Phaeton vom Band. ; Sie ist die Landeshauptstadt Sachsens. | In der gläsernen Fabrik konnten Besucher ab 2002 zusehen, wie der VW Phaeton von Hand montiert wurde.
C U | Wofür steht das Kürzel „GTI“ beim VW Golf? | Gran Turismo Injection | Grand Touring International ; Golf Turbo Intensiv ; Gran Tipo Italiano | Der erste Golf GTI kam 1976. ; Die ersten beiden Buchstaben stammen aus dem Italienischen. ; Das „I“ steht für die Einspritzung. | Der Golf GTI begründete die Klasse der „Hot Hatches“ — sportliche Kompaktwagen für den Alltag.

@ smartphones_gadgets
E E | Welches Gerät ist hier gesucht? | 🥽🌐🎮 | VR-Brille | Smartwatch ; Beamer ; Spielekonsole | Man setzt es auf den Kopf. ; Es schirmt die echte Umgebung ab. ; Man taucht damit in virtuelle Welten ein. | Moderne VR-Brillen verfolgen Kopfbewegungen so genau, dass man sich in der digitalen Welt frei umsehen kann.
E E | Welches Gerät ist hier gesucht? | 📷🖼️👋⏳ | Sofortbildkamera | Spiegelreflexkamera ; Camcorder ; Diaprojektor | Das Foto kommt direkt vorne aus dem Gerät. ; Man muss kurz warten, bis das Bild erscheint. ; Die bekannteste Marke heißt Polaroid. | Die erste Sofortbildkamera von Polaroid kam 1948 auf den Markt — das Wedeln mit dem Foto ist bei modernen Bildern übrigens nutzlos.
E H | Welches Gerät ist hier gesucht? | 📚🔥📱 | Kindle | Tolino ; Kobo ; iPad | Es ist ein E-Book-Reader. ; Er stammt von Amazon. ; Sein Name bedeutet auf Englisch „entfachen“. | Der erste Kindle erschien 2007 und war in den USA innerhalb weniger Stunden ausverkauft.
W H | Samsung verkaufte in seinen Anfangsjahren getrockneten Fisch und Nudeln. | wahr | Samsung begann in Korea als kleine Handelsfirma — Elektronik kam erst Ende der 1960er-Jahre hinzu.
W M | Nokia stellte früher unter anderem Gummistiefel und Autoreifen her. | wahr | Das finnische Unternehmen begann als Papiermühle und war lange ein Mischkonzern — Gummistiefel aus Nokia sind in Finnland bis heute Kult.
W M | Der erste iPod von 2001 konnte schon Videos abspielen. | falsch | Videos kamen erst 2005 mit der fünften iPod-Generation — das Original von 2001 spielte nur Musik.
S M | In welchem Jahr kam der erste Sony Walkman auf den Markt? | 1979 | Jahr | 3 | 1950 | 2000 | Ende der 1970er. ; Wenige Jahre vor der Audio-CD. ; Zwischen 1975 und 1980. | Das erste Modell kam im Juli 1979 in Japan heraus — und hatte zwei Kopfhörerbuchsen, damit man zu zweit hören konnte.
S H | Wie viel wog das Kult-Handy Nokia 3310 ungefähr (in Gramm)? | 133 | Gramm | 15 | 50 | 500 | Deutlich leichter als ein Päckchen Butter. ; Mehr als 100 Gramm. ; Gut ein Achtel Kilo. | Das 3310 aus dem Jahr 2000 galt als nahezu unzerstörbar — und hielt mit einer Akkuladung tagelang durch.
O E | Sortiere diese Bildauflösungen nach ihrer Pixelzahl — die kleinste zuerst. | HD = 1280 × 720 ; Full HD = 1920 × 1080 ; 4K = 3840 × 2160 ; 8K = 7680 × 4320 | „Full“ kommt nach dem einfachen HD. ; Die Zahl vor dem K verrät grob die Breite in Tausend Pixeln. ; 8K ist die größte. | 8K hat 16-mal so viele Pixel wie Full HD — rund 33 Millionen Bildpunkte.
O U | Sortiere diese Elektronik-Firmen nach ihrem Gründungsjahr — die älteste zuerst. | Nokia = 1865 ; Samsung = 1938 ; Apple = 1976 ; Xiaomi = 2010 | Die älteste begann als Papiermühle. ; Die koreanische Firma entstand vor dem Zweiten Weltkrieg. ; Der chinesische Hersteller ist erst seit den 2010ern dabei. | Xiaomi stieg in nur rund zehn Jahren zu einem der drei größten Smartphone-Hersteller der Welt auf.
M M | Welche ZWEI dieser Elektronikkonzerne stammen aus Südkorea? | Samsung ; LG | Sony ; Xiaomi ; Nokia ; HTC | Beide stammen aus demselben asiatischen Land. ; Einer der beiden baut die Galaxy-Smartphones. ; Die übrigen stammen aus Japan, China, Finnland und Taiwan. | LG hieß früher „Lucky-Goldstar“ — 2021 stieg der Konzern aus dem Smartphone-Geschäft aus.
M E | Welche DREI dieser Namen sind Betriebssysteme für Smartphones (heute oder früher)? | Android ; iOS ; Symbian | Photoshop ; Firefox ; Excel | Eines stammt von Google. ; Eines läuft nur auf iPhones. ; Das dritte lief früher auf vielen Nokia-Handys. | Symbian war Anfang der 2000er das meistgenutzte Handy-Betriebssystem — bis iPhone und Android kamen.
C E | Wie nennt man ein Foto des eigenen Bildschirminhalts? | Screenshot | Selfie ; Wallpaper ; Thumbnail | Man braucht dafür keine Kamera. ; Am Smartphone drückt man meist zwei Tasten gleichzeitig. ; Das englische Wort bedeutet wörtlich „Bildschirmschuss“. | Auf Deutsch sagt man auch Bildschirmfoto — am Windows-PC hilft dafür die Taste „Druck“.
C M | Wofür steht die Abkürzung „LED“? | Light Emitting Diode | Low Energy Device ; Light Electric Display ; Linear Energy Diode | Es ist ein elektronisches Bauteil. ; Es leuchtet, wenn Strom hindurchfließt. ; Auf Deutsch heißt es Leuchtdiode. | Blaue LEDs waren lange das fehlende Puzzlestück — ihre Erfinder bekamen 2014 den Physik-Nobelpreis.
C H | Welcher Konzern hat den Fitnessarmband-Hersteller Fitbit 2021 übernommen? | Google | Apple ; Samsung ; Amazon | Der Käufer entwickelt auch Android. ; Er baut eigene Pixel-Smartphones. ; Der Firmenname geht auf eine riesige Zahl zurück. | Rund 2,1 Milliarden US-Dollar kostete die Übernahme — Kartellbehörden prüften den Deal über ein Jahr lang.
C U | Wofür steht die Abkürzung „SIM“ bei der SIM-Karte? | Subscriber Identity Module | Secure Internet Mobile ; System Identification Memory ; Signal Input Module | Die Karte identifiziert den Kunden im Mobilfunknetz. ; Das erste Wort bedeutet „Abonnent“. ; Das letzte Wort bedeutet „Baustein“. | Die erste SIM-Karte von 1991 hatte das Format einer Kreditkarte — später schrumpfte sie über Mini, Micro und Nano bis zur eSIM.

@ computer_internet_technik
E E | Welcher Internetbegriff ist hier gesucht? | 🍪🌐🖱️ | Cookie | Cache ; Captcha ; Firewall | Webseiten speichern damit kleine Dateien im Browser. ; Ständig soll man ihnen per Banner zustimmen. ; Der Begriff klingt nach Gebäck. | Cookies merken sich etwa Log-ins oder Warenkörbe — für viele Zwecke müssen Websites in der EU vorher um Erlaubnis fragen.
E M | Welche Programmiersprache ist hier gesucht? | 🐍💻 | Python | Java ; Ruby ; Perl | Sie gilt als besonders einsteigerfreundlich. ; Ihr Erfinder ist der Niederländer Guido van Rossum. ; Benannt wurde sie nach einer britischen Komikertruppe. | Van Rossum veröffentlichte die Sprache 1991 und benannte sie nach „Monty Python's Flying Circus“ — nicht nach der Schlange.
E E | Welcher Technikbegriff ist hier gesucht? | ☁️💾📁 | Cloud | Festplatte ; USB-Stick ; Diskette | Die Daten liegen nicht mehr auf dem eigenen Gerät. ; Man greift übers Internet darauf zu. ; Das englische Wort bedeutet „Wolke“. | Hinter der „Wolke“ stecken ganz handfeste Rechenzentren — manche davon so groß wie mehrere Fußballfelder.
W M | Das Schloss-Symbol neben der Webadresse beweist, dass eine Website seriös ist. | falsch | Das Schloss zeigt nur, dass die Verbindung per HTTPS verschlüsselt ist — auch Betrüger nutzen verschlüsselte Seiten.
W H | Die Programmiersprache JavaScript ist eine vereinfachte Version von Java. | falsch | Beide haben kaum etwas gemeinsam — der Name war 1995 vor allem ein Marketing-Trick, um vom Java-Hype zu profitieren.
W H | Die erste Internetadresse mit der Endung „.com“ wurde bereits 1985 registriert. | wahr | Am 15. März 1985 sicherte sich die Computerfirma Symbolics die Adresse symbolics.com — lange bevor das World Wide Web erfunden war.
S M | In welchem Jahr gründeten Bill Gates und Paul Allen die Firma Microsoft? | 1975 | Jahr | 3 | 1950 | 2000 | Mitte der 1970er. ; Ein Jahr vor Apple. ; Zwischen 1973 und 1977. | Die beiden gründeten die Firma in Albuquerque — anfangs schrieben sie Software für den Bausatz-Computer Altair 8800.
S U log | Aus wie vielen Transistoren bestand der Intel 4004, der erste Mikroprozessor von 1971? | 2300 | Transistoren | 25 | 100 | 1000000 | Weniger als 10.000. ; Mehr als 1.000. ; Gut 2.000. | Heutige Smartphone-Chips tragen viele Milliarden Transistoren — mehr als eine Million Mal so viele wie der 4004.
O E | Sortiere diese Speichermedien nach ihrer typischen Kapazität — das kleinste zuerst. | 3,5-Zoll-Diskette = 1,44 MB ; CD = ca. 700 MB ; DVD = 4,7 GB ; Blu-ray = 25 GB | Die Scheibe im Plastikquadrat fasst am wenigsten. ; Die Musik-CD kommt vor der Film-DVD. ; Die blaue Scheibe fasst am meisten. | Ihren Namen hat die Blu-ray vom blauvioletten Laser, der feinere Datenspuren lesen kann als der rote Laser der DVD.
O M | Sortiere diese Zahlensysteme nach ihrer Basis — die kleinste zuerst. | Binärsystem = Basis 2 ; Oktalsystem = Basis 8 ; Dezimalsystem = Basis 10 ; Hexadezimalsystem = Basis 16 | Computer rechnen im kleinsten. ; Im Alltag zählen wir mit zehn Fingern. ; „Hexa“ und „dezi“ ergeben zusammen 16. | Im Hexadezimalsystem stehen die Buchstaben A bis F für die Werte 10 bis 15.
M E | Welche DREI dieser Begriffe sind Programmiersprachen? | Java ; Rust ; Swift | Excel ; Photoshop ; Linux | Eine trägt den Namen einer indonesischen Insel. ; Eine heißt wie ein flinker Vogel. ; Eine heißt wie das, was Eisen ansetzt. | Swift stammt von Apple (2014), Rust ursprünglich von Mozilla — Linux ist dagegen ein Betriebssystem.
M E | Welche ZWEI dieser Dateiendungen stehen für Bilddateien? | .jpg ; .png | .mp3 ; .docx ; .exe ; .zip | Man öffnet sie mit einem Fotobetrachter. ; Eine ist typisch für Digitalfotos. ; Die andere unterstützt durchsichtige Hintergründe. | JPEG komprimiert verlustbehaftet und eignet sich für Fotos, PNG verlustfrei — ideal für Grafiken und Logos.
C E | Wie nennt man den kleinen Pfeil, den man mit der Maus über den Bildschirm bewegt? | Mauszeiger | Scrollrad ; Taskleiste ; Desktop | Er folgt jeder Handbewegung. ; Beim Warten verwandelt er sich manchmal in eine Sanduhr. ; Man nennt ihn auch Cursor. | Über Texten wird der Zeiger meist zu einem schmalen senkrechten Strich — der Einfügemarke.
C M | Wie nennt man Schadsoftware, die Dateien verschlüsselt und für die Freigabe Lösegeld fordert? | Ransomware | Adware ; Spyware ; Freeware | Das englische „ransom“ bedeutet Lösegeld. ; Oft verlangen die Täter Kryptowährung. ; Regelmäßige Sicherungskopien sind der beste Schutz. | Solche Angriffe legten schon Krankenhäuser, Stadtverwaltungen und ganze Konzerne tagelang lahm.
C H | Welche Tastenkombination wird im Deutschen scherzhaft „Affengriff“ genannt? | Strg + Alt + Entf | Strg + C ; Alt + F4 ; Windows + L | Man braucht dafür drei Finger. ; Früher startete sie den Computer neu. ; Unter Windows öffnet sie heute ein Sicherheitsmenü. | Erfunden hat die Kombination IBM-Ingenieur David Bradley — absichtlich so, dass man sie nicht aus Versehen drückt.
C U | Welche Programmiersprache wurde 1964 am Dartmouth College als leicht erlernbare Einsteigersprache entwickelt? | BASIC | COBOL ; Pascal ; Fortran | Sie war auf fast jedem Heimcomputer der 1980er vorinstalliert. ; Ihr Name ist eine Abkürzung. ; Er bedeutet übersetzt etwa „grundlegend“. | Mit einer BASIC-Version für den Altair begann 1975 auch die Geschichte von Microsoft.

@ ki_zukunftstechnik
E E | Welches Gerät ist hier gesucht? | 🤖🧹🏠 | Saugroboter | Wischmopp ; Staubwedel ; Laubbläser | Es fährt selbstständig durch die Wohnung. ; Es findet mit Sensoren um Möbel herum. ; Danach fährt es von allein zur Ladestation. | Viele Modelle kartieren die Wohnung per Laser oder Kamera — und lassen sich per App steuern.
E M | Welches Gerät ist hier gesucht? | 🖨️🧊🔧 | 3D-Drucker | Laserdrucker ; Plotter ; Scanner | Er baut Gegenstände Schicht für Schicht auf. ; Meist verwendet er geschmolzenen Kunststoff. ; Damit lassen sich sogar Ersatzteile selbst herstellen. | Mit dieser Technik druckt man heute sogar Häuser aus Beton, Prothesen und Raketenteile.
W H | Das Programm AlphaZero brachte sich Schach allein durch Partien gegen sich selbst bei. | wahr | DeepMind gab der KI 2017 nur die Spielregeln — nach wenigen Stunden Training schlug sie das damals stärkste Schachprogramm Stockfish.
W E | Vollständig fahrerlose Autos der höchsten Automatisierungsstufe 5 kann man in Deutschland ganz normal beim Händler kaufen (Stand 2024). | falsch | Stufe 5 bedeutet: kein Fahrer nötig, überall einsetzbar — solche Autos gibt es bislang nirgends zu kaufen.
W H | Saugroboter gibt es erst seit den 2010er-Jahren zu kaufen. | falsch | Schon 2001 kam der Trilobite von Electrolux auf den Markt, 2002 folgte der bekannte Roomba von iRobot.
S H | In welchem Jahr veröffentlichte Karel Čapek das Theaterstück „R.U.R.“, das dem Wort „Roboter“ zum Durchbruch verhalf? | 1920 | Jahr | 3 | 1850 | 1990 | Nach dem Ersten Weltkrieg. ; Um den Beginn der 1920er. ; Zwischen 1918 und 1923. | Den Begriff hatte Čapeks Bruder Josef vorgeschlagen — abgeleitet vom tschechischen „robota“ für Fronarbeit.
S U log | Wie viele Milliarden Parameter hat das 2020 vorgestellte Sprachmodell GPT-3? | 175 | Milliarden | 25 | 1 | 2000 | Mehr als 100 Milliarden. ; Weniger als 200 Milliarden. ; Zwischen 150 und 200. | Parameter sind die einstellbaren Gewichte eines neuronalen Netzes — der Vorgänger GPT-2 kam 2019 noch mit 1,5 Milliarden aus.
O M | Sortiere diese digitalen Assistenten nach ihrem Start — den ältesten zuerst. | Siri = 2011 ; Alexa = 2014 ; Google Assistant = 2016 ; ChatGPT = 2022 | Apples Assistentin war zuerst da. ; Amazons Lautsprecher-Stimme folgte. ; Der Chatbot kam als Letzter. | Siri stammte ursprünglich von einem Start-up — Apple kaufte es 2010 und baute es 2011 ins iPhone 4S ein.
M E | Welche ZWEI dieser Programme sind KI-Chatbots (Stand 2024)? | ChatGPT ; Gemini | Photoshop ; Excel ; Spotify ; Zoom | Einer stammt von OpenAI. ; Der andere von Google. ; Mit beiden kann man in ganzen Sätzen schreiben. | Googles Chatbot hieß anfangs „Bard“ und wurde Anfang 2024 in Gemini umbenannt.
C M | Wie nennt man die Technik, bei der digitale Objekte in das Livebild der echten Umgebung eingeblendet werden? | Augmented Reality | Virtual Reality ; Deep Learning ; Cloud Computing | Bei „Pokémon Go“ sieht man Monster auf der echten Straße. ; Die Umgebung bleibt sichtbar. ; Übersetzt heißt es „erweiterte Realität“. | Bei Virtual Reality taucht man dagegen komplett in eine künstliche Welt ein.
C M | Wie heißt die kleinste Recheneinheit eines Quantencomputers? | Qubit | Byte ; Quark ; Pixel | Sie kann mehrere Zustände gleichzeitig einnehmen. ; Ihr Name ist ein Kunstwort. ; Er setzt sich aus „Quanten“ und „Bit“ zusammen. | Anders als ein normales Bit ist ein Qubit nicht nur 0 oder 1, sondern kann sich in einer Überlagerung beider Zustände befinden.
C H | Wie heißt der vierbeinige Roboterhund der Firma Boston Dynamics? | Spot | Atlas ; Rex ; Aibo | Er kann Treppen steigen und Türen öffnen. ; Sein Name ist ein klassischer englischer Hundename. ; Er hat nur vier Buchstaben. | Atlas heißt dagegen der zweibeinige Humanoide von Boston Dynamics, Aibo der Roboterhund von Sony.
C U | Welcher KI-Pionier gilt als „Pate der KI“ und erhielt 2024 den Physik-Nobelpreis? | Geoffrey Hinton | Yann LeCun ; Demis Hassabis ; Andrew Ng | Er forschte jahrzehntelang an künstlichen neuronalen Netzen. ; Er teilte sich den Preis mit John Hopfield. ; Er verließ 2023 Google, um freier vor KI-Risiken warnen zu können. | Demis Hassabis bekam 2024 übrigens ebenfalls einen Nobelpreis — den für Chemie, für AlphaFold.

@ raumfahrt_technik
E M | Welches Weltraumteleskop ist hier gesucht? | 🔭🟡🪞🌌 | James-Webb-Teleskop | Hubble-Teleskop ; Kepler-Teleskop ; Spitzer-Teleskop | Es startete am 25. Dezember 2021. ; Seine Spiegel sind mit Gold beschichtet. ; Es ist nach einem früheren NASA-Chef benannt. | Das Teleskop beobachtet im Infraroten und steht rund 1,5 Millionen Kilometer von der Erde entfernt am Lagrange-Punkt L2.
E H | Welches Fluggerät ist hier gesucht? | 🚁🔴🏜️ | Ingenuity | Perseverance ; Curiosity ; Sojourner | Es war ein kleiner Hubschrauber. ; Er flog 2021 als erstes Fluggerät motorisiert auf einem anderen Planeten. ; Er reiste unter dem Bauch eines Rovers zum Mars. | Geplant waren fünf Testflüge — bis Anfang 2024 schaffte der Mini-Hubschrauber insgesamt 72.
W E | Die Fußabdrücke der Apollo-Astronauten sind auf dem Mond vermutlich bis heute erhalten. | wahr | Auf dem Mond gibt es weder Wind noch Regen — Spuren im Mondstaub können Millionen Jahre überdauern.
W M | Das Space Shuttle konnte bis zum Mond fliegen. | falsch | Die Raumfähre war nur für erdnahe Umlaufbahnen gebaut — ihr Höhenrekord lag bei gut 600 Kilometern, beim Aussetzen des Hubble-Teleskops.
W H | Apollo-Astronauten stellten auf dem Mond Spiegel auf, an denen Forscher bis heute Laserstrahlen reflektieren lassen. | wahr | Mit den Reflektoren von Apollo 11, 14 und 15 messen Observatorien die Entfernung zum Mond auf wenige Millimeter genau.
S M | Wie viele Tage dauerte die Mission Apollo 11 vom Start bis zur Wasserung ungefähr? | 8 | Tage | 25 | 1 | 60 | Gut eine Woche. ; Mehr als fünf Tage. ; Weniger als zehn Tage. | Start war am 16. Juli 1969, die Kapsel landete am 24. Juli im Pazifik — danach mussten die Astronauten noch drei Wochen in Quarantäne.
S U log | Wie viele Kilogramm Mondgestein brachten die sechs Apollo-Landungen insgesamt zur Erde? | 382 | kg | 20 | 1 | 10000 | Mehr als 100 Kilogramm. ; Weniger als eine halbe Tonne. ; Etwa so viel, wie fünf Erwachsene wiegen. | Die meisten Proben lagern bis heute im Johnson Space Center in Houston — manche Behälter wurden erst Jahrzehnte später geöffnet.
O M | Sortiere diese Objekte nach ihrer Entfernung von der Erde — das nächste zuerst. | ISS = ca. 400 km ; GPS-Satelliten = ca. 20.200 km ; Geostationäre Satelliten = ca. 35.800 km ; Mond = ca. 384.400 km | Die Raumstation kreist am tiefsten. ; Navigationssatelliten fliegen in mittlerer Höhe. ; Wer vom Boden aus stillzustehen scheint, fliegt höher als GPS. | Geostationäre Satelliten umrunden die Erde genau einmal pro Tag — deshalb scheinen sie vom Boden aus stillzustehen.
O U | Sortiere diese Raumsonden nach ihrem Startjahr — die älteste zuerst. | Voyager 1 = 1977 ; Cassini = 1997 ; New Horizons = 2006 ; Juno = 2011 | Die älteste hat unser Sonnensystem längst verlassen. ; Die Saturn-Sonde startete Ende der 1990er. ; Die Jupiter-Sonde ist die jüngste. | Voyager 1 ist das am weitesten entfernte menschengemachte Objekt — mehr als 20 Lichtstunden von der Erde weg (Stand 2024).
M M | Welche DREI dieser Staaten haben aus eigener Kraft Menschen ins All gebracht (Stand 2024)? | Sowjetunion bzw. Russland ; USA ; China | Indien ; Japan ; Frankreich | Einer davon war 1961 der allererste. ; Einer folgte nur wenige Wochen später. ; Der dritte schaffte es erst 2003. | China schickte 2003 Yang Liwei ins All — Indien bereitet mit „Gaganyaan“ seine erste bemannte Mission vor.
M H | Welche ZWEI dieser Deutschen arbeiteten als Astronauten auf der ISS? | Alexander Gerst ; Matthias Maurer | Ulf Merbold ; Sigmund Jähn ; Reinhold Ewald ; Wernher von Braun | Einer war sogar Kommandant der Station. ; Der andere flog 2021 mit einer SpaceX-Kapsel. ; Die übrigen flogen vor der ISS-Zeit oder nie selbst ins All. | Alexander Gerst übernahm 2018 als erster Deutscher das Kommando über die Internationale Raumstation.
C M | Wie heißt das NASA-Programm, mit dem wieder Menschen auf den Mond fliegen sollen? | Artemis | Apollo ; Gemini ; Orion | Es ist nach der Zwillingsschwester des Apollo benannt. ; 2022 flog eine unbemannte Testmission um den Mond. ; Zum ersten Mal soll eine Frau den Mond betreten. | Orion heißt die Raumkapsel des Programms, gestartet wird sie mit der Riesenrakete SLS.
C M | Welche Raumfahrtfirma gehört Amazon-Gründer Jeff Bezos? | Blue Origin | SpaceX ; Virgin Galactic ; Rocket Lab | Ihre Rakete heißt „New Shepard“. ; Das Logo zeigt eine Feder. ; Der Gründer flog 2021 selbst mit ins All. | Die Rakete ist nach Alan Shepard benannt, dem ersten US-Amerikaner im All.
C H | Wie heißt Boeings Raumkapsel, deren erster bemannter Testflug im Juni 2024 zur ISS führte? | Starliner | Crew Dragon ; Orion ; Sojus | Die Kapsel ist Boeings Konkurrenz zu SpaceX. ; Wegen Triebwerksproblemen kehrte sie ohne ihre Crew zur Erde zurück. ; Ihr Name enthält einen Stern. | Die Astronauten Butch Wilmore und Suni Williams blieben statt acht Tagen über neun Monate auf der ISS.
C U | Wie hieß die europäische Landesonde, die 2005 auf dem Saturnmond Titan aufsetzte? | Huygens | Philae ; Beagle 2 ; Schiaparelli | Sie reiste huckepack auf der Sonde Cassini. ; Sie ist nach einem niederländischen Astronomen benannt. ; Dieser entdeckte 1655 den Mond Titan. | Huygens ist bis heute die am weitesten von der Erde entfernte Landung auf einem Himmelskörper (Stand 2024).

@ bahn_verkehr_mobilitaet de
E E | Welcher Zug ist hier gesucht? | 🚄🗻🇯🇵 | Shinkansen | TGV ; Transrapid ; Eurostar | Er fährt in Japan. ; Er fuhr 1964 erstmals, kurz vor den Olympischen Spielen in Tokio. ; Wegen seiner Form nennt man ihn auch „Bullet Train“. | Seit 1964 gab es im Shinkansen-Netz keinen einzigen tödlichen Unfall durch Entgleisung oder Zusammenstoß — ein weltweit einmaliger Sicherheitsrekord.
E E | Welche Verkehrseinrichtung ist hier gesucht? | 🦓🚶🛣️ | Zebrastreifen | Bahnübergang ; Radweg ; Fußgängerbrücke | Hier haben Fußgänger Vorrang. ; Er besteht aus weißen Streifen auf der Fahrbahn. ; Er ist nach einem gestreiften Tier benannt. | Offiziell heißt er „Fußgängerüberweg“ — Autos müssen dort Fußgängern das Überqueren ermöglichen.
E E | Welches Fahrzeug ist hier gesucht? | 🛴⚡🏙️ | E-Scooter | Segway ; Hoverboard ; Mofa | Man steht beim Fahren darauf. ; Es wird elektrisch angetrieben. ; In Großstädten kann man es per App ausleihen. | In Deutschland sind E-Scooter seit 2019 erlaubt — ab 14 Jahren, ohne Führerschein, aber mit Versicherungskennzeichen.
W E | Das Deutschlandticket kostete bei seiner Einführung im Mai 2023 49 Euro im Monat. | wahr | Es gilt bundesweit im gesamten Nahverkehr — zum Jahr 2025 stieg der Preis auf 58 Euro.
W H | In einem Kreisverkehr haben die Fahrzeuge im Kreis immer Vorfahrt — auch wenn keine Schilder stehen. | falsch | Nur wenn die Schilder „Kreisverkehr“ und „Vorfahrt gewähren“ stehen, hat der Kreis Vorrang — sonst gilt rechts vor links.
S M | Wie viele Kilometer lang ist die klassische Strecke der Transsibirischen Eisenbahn von Moskau nach Wladiwostok? | 9288 | km | 15 | 2000 | 30000 | Mehr als 5.000 Kilometer. ; Die Fahrt dauert rund eine Woche. ; Knapp unter 10.000 Kilometer. | Die Transsib gilt als längste Eisenbahnstrecke der Welt — unterwegs stellt man die Uhr um sieben Stunden vor.
S M | Mit wie vielen km/h stellte ein japanischer Magnetschwebezug 2015 den Geschwindigkeitsweltrekord für Schienenfahrzeuge auf? | 603 | km/h | 10 | 200 | 1200 | Deutlich schneller als jeder ICE. ; Mehr als 550 km/h. ; Gut 600 km/h. | Der Rekord für Züge mit Rädern liegt bei 574,8 km/h — aufgestellt 2007 in Frankreich.
O H | Sortiere diese Eisenbahntunnel nach ihrer Länge — den kürzesten zuerst. | Lötschberg-Basistunnel = ca. 34,6 km ; Eurotunnel = ca. 50,5 km ; Seikan-Tunnel = ca. 53,9 km ; Gotthard-Basistunnel = ca. 57,1 km | Der kürzeste liegt ebenfalls in der Schweiz. ; Der Tunnel unter dem Ärmelkanal ist Nummer zwei der Liste. ; Der längste wurde 2016 eröffnet. | Der japanische Seikan-Tunnel verläuft bis zu 240 Meter unter dem Meeresspiegel und verbindet die Inseln Honshu und Hokkaido.
M E | Welche ZWEI dieser Verkehrszeichen haben eine dreieckige Form? | Vorfahrt gewähren ; Achtung Gefahrstelle | Stoppschild ; Vorfahrtstraße ; Einbahnstraße ; Parkverbot | Beide mahnen zur Vorsicht. ; Eines steht auf der Spitze. ; Das Stoppschild hat acht Ecken. | Gefahrzeichen sind in Deutschland rot umrandete Dreiecke — das Zeichen „Vorfahrt gewähren“ steht dagegen auf dem Kopf.
C E | Wie viel Rabatt gibt die BahnCard 50 auf den Flexpreis der Deutschen Bahn? | 50 Prozent | 25 Prozent ; 75 Prozent ; 100 Prozent | Die Zahl steckt schon im Namen. ; Man zahlt nur einen Teil. ; Es ist genau die Hälfte. | Die BahnCard 100 ist dagegen eine Jahres-Flatrate für alle Züge der Deutschen Bahn.
C M | Wie heißt der französische Hochgeschwindigkeitszug, der seit 1981 fährt? | TGV | Thalys ; Eurostar ; AVE | Die Abkürzung steht für „Zug mit hoher Geschwindigkeit“. ; Die erste Strecke verband Paris und Lyon. ; Er hält den Geschwindigkeitsrekord für Rad-Schiene-Züge. | TGV steht für „Train à Grande Vitesse“ — 2007 raste ein Testzug mit 574,8 km/h über die Schienen.
C M | Wie heißt die Zahnradbahn, die von Garmisch-Partenkirchen auf Deutschlands höchsten Berg fährt? | Bayerische Zugspitzbahn | Wendelsteinbahn ; Brockenbahn ; Drachenfelsbahn | Der Berg ist fast 3.000 Meter hoch. ; Die Endstation liegt auf dem Zugspitzplatt. ; Der Name des Bergs steckt im Bahnnamen. | Die Bahn wurde 1930 eröffnet und fährt im oberen Teil durch einen langen Tunnel im Fels.
C H | Wo liegt der größte Rangierbahnhof Europas? | In Maschen bei Hamburg | In Seelze bei Hannover ; In Mannheim ; In Duisburg | Er liegt südlich der größten deutschen Hafenstadt. ; Der Hafen braucht ihn für den Güterverkehr. ; Er liegt in Niedersachsen. | Auf den Gleisen in Maschen werden täglich Tausende Güterwagen zu neuen Zügen zusammengestellt.
C U | Wie heißt der längste Straßentunnel der Welt (Stand 2024)? | Lærdalstunnel | Gotthard-Straßentunnel ; Mont-Blanc-Tunnel ; Arlberg-Straßentunnel | Er liegt in Norwegen. ; Er ist gut 24 Kilometer lang. ; In ihm gibt es drei beleuchtete Hallen gegen Müdigkeit. | Die blau beleuchteten Höhlen im Tunnel sollen Autofahrern auf der langen Strecke eine Pause für die Augen verschaffen.

@ energie_umwelttechnik
E E | Welche Anlage ist hier gesucht? | 🌬️⚡🌊 | Offshore-Windpark | Gezeitenkraftwerk ; Wellenkraftwerk ; Pumpspeicherkraftwerk | Die Anlagen stehen im Meer. ; Dort weht der Wind stärker und gleichmäßiger als an Land. ; Deutschland betreibt viele davon in Nord- und Ostsee. | Offshore-Windräder gehören zu den größten Maschinen der Welt — ihre Rotoren erreichen Durchmesser von mehr als 200 Metern.
E E | Welches Phänomen ist hier gesucht? | ☀️🌍🌡️🏭 | Treibhauseffekt | Ozonloch ; Saurer Regen ; Polarlicht | Gase in der Atmosphäre halten Wärme fest. ; Ohne ihn wäre die Erde eiskalt. ; Durch Abgase wird er verstärkt. | Ohne den natürlichen Treibhauseffekt läge die Durchschnittstemperatur der Erde bei rund minus 18 statt plus 15 Grad.
W H | Ein Liter Benzin enthält mehr Energie als eine Kilowattstunde. | wahr | In einem Liter Benzin stecken rund neun Kilowattstunden — ein Verbrennungsmotor nutzt davon aber nur einen kleinen Teil.
W H | In Deutschland sterben durch Windräder mehr Vögel als durch Glasscheiben an Gebäuden. | falsch | Glasflächen töten Schätzungen zufolge jährlich rund 100 Millionen Vögel — bei Windrädern geht man von etwa 100.000 aus.
S E | Wie viel Volt Spannung liefert eine normale AA-Batterie (Mignon)? | 1.5 | Volt | 20 | 0.1 | 12 | Deutlich weniger als eine Autobatterie. ; Mehr als ein Volt. ; Zwischen 1 und 2 Volt. | Wiederaufladbare AA-Akkus liefern mit 1,2 Volt etwas weniger — für die meisten Geräte reicht das trotzdem.
S H | Wie viele Tonnen CO₂-Äquivalente verursacht ein Mensch in Deutschland im Schnitt pro Jahr (Stand 2023)? | 10 | Tonnen | 25 | 1 | 50 | Mehr als fünf Tonnen. ; Klimaverträglich wäre weniger als eine Tonne. ; Weniger als 15 Tonnen. | Laut Umweltbundesamt liegt der Durchschnitt bei gut zehn Tonnen — Heizen, Mobilität, Ernährung und Konsum tragen am meisten bei.
S U | Wie viel Prozent des weltweit erzeugten Stroms stammten 2023 aus Kohle? | 35 | Prozent | 15 | 1 | 90 | Kohle war noch immer die wichtigste Einzelquelle. ; Mehr als ein Viertel. ; Gut ein Drittel. | Vor allem China und Indien verfeuern große Mengen Kohle — erneuerbare Energien kamen 2023 zusammen auf rund 30 Prozent.
O U | Sortiere diese Energieträger nach ihrem Energiegehalt pro Kilogramm — den niedrigsten zuerst. | Holz = ca. 15 MJ/kg ; Steinkohle = ca. 30 MJ/kg ; Benzin = ca. 43 MJ/kg ; Wasserstoff = ca. 120 MJ/kg | Das Kaminholz hat am wenigsten. ; Flüssiger Kraftstoff schlägt Kohle. ; Das leichteste Element hat pro Kilo am meisten Energie. | Wasserstoff ist pro Kilogramm unschlagbar — pro Liter braucht er aber riesige, druckfeste oder tiefgekühlte Tanks.
O H | Sortiere diese Länder nach ihrer installierten Windkraft-Leistung Ende 2023 — die geringste zuerst. | Indien = ca. 45 GW ; Deutschland = ca. 69 GW ; USA = ca. 150 GW ; China = über 400 GW | Das Land mit der geringsten Leistung liegt in Südasien. ; Deutschland ist Spitzenreiter in Europa. ; Ein Land hat mehr als alle anderen hier zusammen. | 2023 errichtete China rund zwei Drittel aller neuen Windräder weltweit.
M M | Welche DREI dieser Gase gelten als Treibhausgase? | Kohlendioxid ; Methan ; Lachgas | Stickstoff ; Sauerstoff ; Argon | Eines entsteht beim Verbrennen von Kohle, Öl und Gas. ; Ein anderes stammt zum Beispiel aus Kuhmägen. ; Das dritte kennt man auch als Narkosemittel. | Stickstoff, Sauerstoff und Argon machen zusammen über 99 Prozent der Luft aus — zum Treibhauseffekt tragen sie praktisch nichts bei.
C E | Wie heißt das Gerät im Haus, das den Stromverbrauch misst? | Stromzähler | Sicherungskasten ; Thermostat ; Wechselrichter | Es hängt meist im Keller oder im Flur. ; Es zeigt Kilowattstunden an. ; Neue Modelle heißen „Smart Meter“. | Moderne digitale Zähler können den Verbrauch automatisch an den Netzbetreiber übermitteln.
C M | Wie nennt man das Verhältnis von nutzbarer zu eingesetzter Energie? | Wirkungsgrad | Brennwert ; Leistungsfaktor ; Energiebilanz | Er wird meist in Prozent angegeben. ; Bei einer alten Glühbirne ist er sehr schlecht. ; Er kann nie über 100 Prozent liegen. | Ein Elektromotor erreicht über 90 Prozent — ein Benzinmotor setzt meist nur rund ein Drittel der Energie in Bewegung um.
C H | Wofür steht die Einheit „kWp“ bei Solaranlagen? | Kilowatt-Peak | Kilowatt pro Stunde ; Kilowatt-Pause ; Kilowatt-Produktion | Sie beschreibt die Spitzenleistung. ; Gemessen wird unter genormten Testbedingungen. ; Das „p“ kommt aus dem Englischen und bedeutet „Gipfel“. | Ein Einfamilienhaus-Dach trägt oft rund zehn kWp — das bringt in Deutschland etwa 9.000 bis 10.000 Kilowattstunden im Jahr.
C H | Wie heißt das große internationale Kernfusions-Forschungsprojekt, das in Südfrankreich gebaut wird? | ITER | CERN ; JET ; Fermilab | Der Standort heißt Cadarache. ; Die EU, China, Indien, Japan, Korea, Russland und die USA sind beteiligt. ; Der Name bedeutet auf Lateinisch „der Weg“. | Der Fusionsreaktor vom Typ Tokamak soll zeigen, dass die Energiequelle der Sonne auf der Erde nutzbar ist.
C U | Wie heißt das Kernfusions-Experiment vom Typ Stellarator, das in Greifswald betrieben wird? | Wendelstein 7-X | ASDEX Upgrade ; JET ; ITER | Es ist die größte Anlage ihrer Art weltweit. ; Der Name stammt von einem bayerischen Berg. ; Das Experiment ging 2015 in Betrieb. | Der Stellarator hält das heiße Plasma mit verdrillten Magnetspulen in Form — ganz ohne den Stromfluss im Plasma, den ein Tokamak braucht.
"""
