"""Extra questions, wave 2: Tiere & Natur (format: see tools/content/merge_extra.py)."""
KAT = "tiere_natur"
REGION = "global"
DATA = r"""
@ heimische_tiere_wald de
E E | Welches Tier ist hier gesucht? | 🌰🥐 | Eichhörnchen | Siebenschläfer ; Haselmaus ; Baummarder | Es klettert flink durch die Baumkronen. ; Es hat einen buschigen Schwanz. ; Es legt im Herbst Wintervorräte an. | Eichhörnchen halten keinen Winterschlaf, sondern nur Winterruhe — sie wachen regelmäßig auf, um an ihre Vorräte zu gehen.
E E | Welches Tier ist hier gesucht? | 7️⃣😴 | Siebenschläfer | Murmeltier ; Igel ; Haselmaus | Es ist ein kleines Nagetier. ; Es hält einen langen Winterschlaf. ; Eine Zahl steckt im Namen. | Den Namen trägt er, weil er rund sieben Monate verschläft — der Siebenschläfertag geht dagegen auf eine Legende zurück.
E E | Welches Tier ist hier gesucht? | 🐟🦦 | Fischotter | Biber ; Nutria ; Bisamratte | Es lebt an Flüssen und Seen. ; Es ist ein ausgezeichneter Schwimmer mit dichtem Fell. ; Es gehört zu den Marderartigen. | Fischotter waren in Deutschland fast verschwunden — dank sauberer Gewässer breiten sie sich wieder aus.
C E | Welches Tier heißt in Fabeln „Meister Lampe“? | Der Feldhase | Der Dachs ; Der Fuchs ; Der Igel | Es hat lange Ohren. ; Es ist ein schneller Läufer. ; Zu Ostern ist es besonders beliebt. | Der Fuchs heißt in Fabeln Reineke, der Dachs Grimbart — und der Hase eben Meister Lampe.
C M | Welcher Greifvogel „rüttelt“ oft lange auf der Stelle in der Luft, um Mäuse zu erspähen? | Turmfalke | Mäusebussard ; Rotmilan ; Habicht | Er ist ein kleiner Falke. ; Er brütet gern an Kirchtürmen. ; Sein Name verrät seinen Lieblingsbrutplatz. | Beim Rütteln schlägt der Turmfalke schnell mit den Flügeln und hält den Kopf dabei völlig ruhig.
C U | Welcher Vogel war der „Vogel des Jahres 2024“ in Deutschland? | Kiebitz | Wiedehopf ; Braunkehlchen ; Rotkehlchen | Er lebt auf feuchten Wiesen und Äckern. ; Er trägt eine lange Federholle am Kopf. ; Sein Ruf klingt wie sein Name. | Der Wiesenvogel ist in Deutschland stark gefährdet, weil feuchte Wiesen und Weiden verschwinden.
C U | Wie nennt man die flache Mulde, in der ein Feldhase ruht? | Sasse | Kessel ; Kuhle ; Bau | Der Hase scharrt sie selbst in den Boden. ; Er drückt sich bei Gefahr flach hinein. ; Der Begriff stammt aus der Jägersprache. | Anders als Wildkaninchen graben Feldhasen keine Baue — sie verlassen sich auf Tarnung und Tempo.
W H | Stare können Geräusche wie Handyklingeltöne nachahmen. | wahr | Stare sind begnadete Imitatoren — sie kopieren andere Vögel, Alarmanlagen und sogar Klingeltöne.
W H | Maulwürfe sind völlig blind. | falsch | Maulwürfe haben winzige Augen und können zumindest hell und dunkel unterscheiden — orientieren tun sie sich aber vor allem mit Tasthaaren.
W H | Füchse können Mäuse unter einer geschlossenen Schneedecke hören und orten. | wahr | Mit einem hohen Sprung, dem „Mäuseln“, stürzen sie sich dann kopfüber in den Schnee.
S M log | Wie viele Stacheln trägt ein erwachsener Igel ungefähr? | 7000 | Stacheln | 30 | 500 | 50000 | Mehr als 1.000. ; Weniger als 20.000. ; Einige Tausend. | Die Stacheln sind umgewandelte Haare — bei Gefahr richtet ein Ringmuskel sie auf.
S U | Wie viele Wolfsrudel lebten im Monitoringjahr 2022/23 in Deutschland? | 184 | Rudel | 25 | 10 | 1000 | Mehr als 100. ; Weniger als 300. ; Knapp unter 200. | Die meisten Rudel leben in Brandenburg, Sachsen und Niedersachsen — im Jahr 2000 hatte sich das erste wieder in Deutschland angesiedelt.
O H | Wer bringt seinen Nachwuchs am schnellsten zur Welt? Ordne diese Waldbewohner nach ihrer Trächtigkeit — die kürzeste zuerst. | Feldhase = ≈ 42 Tage ; Rotfuchs = ≈ 52 Tage ; Wildschwein = ≈ 115 Tage ; Rothirsch = ≈ 235 Tage | Das Langohr kommt zuerst. ; Der Rotrock folgt kurz danach. ; Das größte Tier trägt am längsten. | Feldhäsinnen können sogar schon wieder trächtig werden, bevor ihre letzten Jungen geboren sind.
M E | Welche DREI dieser Vögel ziehen im Herbst in den Süden? | Weißstorch ; Kuckuck ; Mauersegler | Haussperling ; Buntspecht ; Kleiber | Einer klappert mit dem Schnabel. ; Einer legt seine Eier in fremde Nester. ; Einer verbringt fast sein ganzes Leben in der Luft. | Mauersegler bleiben nur rund drei Monate bei uns — schon im August fliegen sie zurück nach Afrika.
M M | Welche ZWEI dieser Tiere gehören zu den Marderartigen? | Dachs ; Hermelin | Fuchs ; Waschbär ; Luchs ; Igel | Einer lebt in großen unterirdischen Bauen. ; Einer trägt im Winter weißes Fell. ; Der Fuchs gehört dagegen zu den Hundeartigen. | Auch Fischotter, Iltis und Baummarder zählen zu den Marderartigen.

@ insekten_krabbeltiere
E E | Welches Tier ist hier gesucht? | 👂🪱 | Ohrwurm | Regenwurm ; Holzwurm ; Bandwurm | Es ist ein Insekt mit Zangen am Hinterleib. ; Es versteckt sich gern in engen Spalten. ; Auch ein Lied, das nicht aus dem Kopf geht, trägt diesen Namen. | Der Name stammt vermutlich von einem alten Heilmittel gegen Ohrenleiden, für das man die Tiere zerrieb.
E M | Welches Insekt ist hier gesucht? | 🙏🦗 | Gottesanbeterin | Stabheuschrecke ; Grille ; Wanderheuschrecke | Es ist ein Lauerjäger. ; Seine Fangbeine hält es wie zum Gebet. ; In Deutschland lebt es vor allem in warmen Gegenden am Oberrhein. | Die Gottesanbeterin kann ihren dreieckigen Kopf weit zur Seite drehen und so über die Schulter schauen.
E H | Welches Insekt ist hier gesucht? | 🌾😱 | Heuschrecke | Zikade ; Grille ; Feldwespe | Es springt weit mit kräftigen Hinterbeinen. ; Wanderschwärme vernichten ganze Ernten. ; Viele Arten zirpen im Sommer auf Wiesen. | Der zweite Namensteil kommt vom alten Wort „schrecken“ für „springen“ — die Heuschrecke ist also ein „Heuspringer“.
C E | Welcher heimische Schmetterling trägt vier große Augenflecken auf den Flügeln? | Tagpfauenauge | Zitronenfalter ; Kleiner Fuchs ; Admiral | Er ist rotbraun gefärbt. ; Seine Raupen fressen Brennnesseln. ; Sein Name erinnert an einen Vogel mit prächtigen Schwanzfedern. | Die Augenflecken erschrecken Fressfeinde wie Vögel — der Falter klappt sie bei Gefahr plötzlich auf.
C M | Welcher Käfer galt im alten Ägypten als heilig? | Skarabäus | Hirschkäfer ; Marienkäfer ; Maikäfer | Er rollt Kugeln aus Dung. ; Er galt als Symbol für den Sonnengott. ; Man nennt ihn auch Pillendreher. | Die Ägypter verglichen die rollende Mistkugel mit der Sonne, die über den Himmel gerollt wird.
C M | Welche Ameise baut die großen Hügel aus Nadeln im Wald? | Rote Waldameise | Schwarze Wegameise ; Rossameise ; Pharaoameise | Sie ist in Deutschland besonders geschützt. ; In einem Hügel leben Hunderttausende Tiere. ; Ihr Name verrät Farbe und Lebensraum. | Waldameisen vertilgen große Mengen Schadinsekten — Förster schätzen sie als „Gesundheitspolizei des Waldes“.
C M | Welche Insektengruppe stellt die meisten bekannten Arten der Welt? | Käfer | Schmetterlinge ; Ameisen ; Fliegen | Viele von ihnen haben harte Deckflügel. ; Weltweit kennt man rund 400.000 Arten. ; Auch Marienkäfer und Maikäfer gehören dazu. | Etwa jede vierte bekannte Tierart ist ein Käfer — kein anderes Tier ist so artenreich.
C H | Welches Insekt überträgt die Schlafkrankheit? | Tsetsefliege | Stechmücke ; Sandmücke ; Pferdebremse | Es lebt in Afrika. ; Es ist eine Fliege. ; Sein Name stammt aus einer afrikanischen Sprache. | Die Erreger sind einzellige Trypanosomen, die beim Stich ins Blut gelangen.
W M | Bienen können die Farbe Rot nicht als eigene Farbe sehen. | wahr | Rot erscheint Bienen dunkel — dafür sehen sie ultraviolettes Licht, das für uns unsichtbar ist.
W H | Hummeln können auch bei kühlem Wetter fliegen, weil sie ihre Flugmuskeln aufheizen. | wahr | Durch Muskelzittern erwärmen sie ihren Körper auf über 30 Grad — deshalb fliegen sie früher im Jahr als Honigbienen.
W E | Libellen können Menschen stechen. | falsch | Libellen haben keinen Stachel und sind für Menschen völlig harmlos — Mücken jagen sie dafür sehr erfolgreich.
S U | Wie viele Beine hat eine typische Schmetterlingsraupe, Bauchfüße mitgezählt? | 16 | Beine | 20 | 4 | 60 | Mehr als sechs. ; Weniger als 20. ; Sechs echte Beine plus mehrere Paar Stummelfüße. | Nur die sechs vorderen sind echte Beine — die übrigen sind Bauchfüße, die beim Falter verschwinden.
S U log | Wie viele Kilometer fliegen Honigbienen ungefähr, um 500 Gramm Honig zu sammeln? | 120000 | km | 40 | 1000 | 10000000 | Mehr als einmal um die Erde. ; Weniger als eine Million Kilometer. ; Etwa dreimal um den Äquator. | Dafür steuern die Bienen Millionen Blüten an — eine einzelne Biene trägt in ihrem Leben nur einen winzigen Bruchteil bei.
O M | Sortiere diese Insekten nach der Lebensdauer des erwachsenen Tiers — die kürzeste zuerst. | Eintagsfliege = Stunden bis wenige Tage ; Sommerbiene (Arbeiterin) = ≈ 6 Wochen ; Bienenkönigin = bis ≈ 5 Jahre ; Termitenkönigin = bis ≈ 20 Jahre | Das Insekt mit dem Tag im Namen stirbt zuerst. ; Die Arbeiterin im Sommer lebt nur wenige Wochen. ; Die Königin der Holzfresser wird am ältesten. | Termitenköniginnen gelten als die langlebigsten Insekten — manche sollen mehrere Jahrzehnte alt werden.
M H | Welche ZWEI dieser Tiere sind Spinnentiere? | Skorpion ; Milbe | Tausendfüßer ; Assel ; Silberfischchen ; Ohrwurm | Beide haben acht Beine. ; Einer trägt einen Giftstachel am Schwanz. ; Der andere ist oft winzig und lebt im Hausstaub. | Asseln sind Krebstiere, Tausendfüßer eigene Gliederfüßer, Silberfischchen und Ohrwürmer Insekten.

@ ozean_meerestiere
E E | Welcher Hai ist hier gesucht? | 🔨🦈 | Hammerhai | Tigerhai ; Walhai ; Weißer Hai | Er lebt in warmen Meeren. ; Seine Augen sitzen weit auseinander. ; Sein Kopf sieht aus wie ein Werkzeug. | Der breite Kopf wirkt wie ein Suchgerät: Mit vielen Sinneszellen spürt der Hai im Sand vergrabene Rochen auf.
E H | Welcher Fisch ist hier gesucht? | 🪚🐟 | Sägefisch | Schwertfisch ; Hornhecht ; Barrakuda | Er ist mit Haien und Rochen verwandt. ; Er ist vom Aussterben bedroht. ; Seine lange Schnauze trägt Zähne an beiden Seiten. | Sägefische sind eigentlich Rochen — mit ihrer „Säge“ schlagen sie Beute und spüren sie im Schlamm auf.
E E | Welches Meerestier ist hier gesucht? | 🐋🐴 | Walross | Seelöwe ; Seekuh ; See-Elefant | Es lebt in der Arktis. ; Es hat lange Stoßzähne. ; Im Namen stecken zwei große Tiere. | Seine Stoßzähne nutzt das Walross auch als Haken, um sich aufs Eis zu ziehen.
C E | Welche Robbenart ist im Wattenmeer die häufigste? | Seehund | Kegelrobbe ; Seelöwe ; Walross | Er hat einen runden Kopf. ; Er ist kleiner als die Kegelrobbe. ; Im Namen steckt ein Haustier. | Junge Seehunde rufen mit klagenden Lauten nach ihrer Mutter — deshalb nennt man sie „Heuler“.
C E | Welches stachelige Tier gehört wie der Seestern zu den Stachelhäutern? | Seeigel | Einsiedlerkrebs ; Seeanemone ; Kugelfisch | Es ist fast kugelrund. ; Es weidet Algen von Felsen. ; Barfuß will man nicht darauftreten. | Auch Seegurken und Schlangensterne zählen zu den Stachelhäutern.
C M | Welcher Wal ist berühmt für seine langen, komplexen Gesänge? | Buckelwal | Pottwal ; Blauwal ; Schwertwal | Er springt oft spektakulär aus dem Wasser. ; Er hat sehr lange Brustflossen. ; Seine Lieder reisten 1977 mit der Voyager-Sonde ins All. | Die Lieder der Männchen können über 20 Minuten dauern und verändern sich von Jahr zu Jahr.
C H | Welche Fischgruppe trägt beide Augen auf einer Körperseite? | Plattfische | Knochenhechte ; Mondfische ; Flughähne | Zu ihr gehören Scholle und Seezunge. ; Die Tiere liegen flach am Meeresboden. ; Als Larven sehen sie noch ganz normal aus. | Während der Entwicklung wandert ein Auge auf die andere Kopfseite — ein einzigartiger Umbau.
W U | Seekühe sind näher mit Elefanten verwandt als mit Walen. | wahr | Seekühe und Elefanten haben gemeinsame Vorfahren — die Ähnlichkeit mit Walen entstand erst durch das Leben im Wasser.
W H | Die Portugiesische Galeere ist eine einzelne Qualle. | falsch | Sie ist eine Staatsqualle — eine Kolonie aus vielen spezialisierten Einzeltieren, die gemeinsam wie ein Tier leben.
S M | Wie viele Fangarme hat ein Kalmar, die beiden langen Tentakel mitgezählt? | 10 | Arme | 20 | 4 | 30 | Mehr als ein Oktopus. ; Eine gerade Zahl. ; Weniger als zwölf. | Kraken haben acht Arme, Kalmare und Sepien zusätzlich zwei lange Fangtentakel.
S U | In welchem Jahr wurde der für ausgestorben gehaltene Quastenflosser vor Südafrika wiederentdeckt? | 1938 | Jahr | 3 | 1850 | 2000 | Vor dem Zweiten Weltkrieg. ; In den 1930er-Jahren. ; Ein Jahr vor Kriegsbeginn. | Die Museumskuratorin Marjorie Courtenay-Latimer entdeckte das „lebende Fossil“ im Fang eines Fischkutters.
O M | Sortiere diese Gewässer nach ihrem Salzgehalt — den niedrigsten zuerst. | Ostsee = ≈ 0,8 % ; Nordsee = ≈ 3,5 % ; Mittelmeer = ≈ 3,8 % ; Totes Meer = ≈ 33 % | Das Binnenmeer vor Rostock ist fast Brackwasser. ; Die Nordsee liegt im Durchschnitt der Weltmeere. ; Im Salzsee in Nahost geht niemand unter. | Im Toten Meer ist der Salzgehalt fast zehnmal so hoch wie im offenen Ozean.
O U | Sortiere diese Zonen der Ozeane nach ihrer Tiefe — die flachste zuerst. | Epipelagial = 0–200 m ; Mesopelagial = 200–1000 m ; Bathypelagial = 1000–4000 m ; Abyssopelagial = 4000–6000 m | Die lichtdurchflutete Zone liegt oben. ; Darunter folgt die Dämmerzone. ; Die Zone über der Tiefseeebene kommt zuletzt. | Noch tiefer liegt nur die Hadal-Zone der Tiefseegräben.
M H | Welche DREI dieser Meerestiere sind Weichtiere? | Oktopus ; Miesmuschel ; Wellhornschnecke | Seestern ; Qualle ; Hummer | Eines hat acht Arme. ; Eines lebt zwischen zwei Schalen. ; Eines trägt ein gedrehtes Gehäuse. | Kopffüßer, Muscheln und Schnecken bilden zusammen den Stamm der Weichtiere.
M E | Welche ZWEI dieser Meeresbewohner sind Fische? | Rochen ; Aal | Wal ; Delfin ; Seekuh ; Robbe | Einer ist flach und gleitet über den Grund. ; Der andere ist lang und schlangenartig. ; Die falschen sind Säugetiere. | Wale, Delfine, Seekühe und Robben atmen mit Lungen — Fische mit Kiemen.

@ saeugetiere_haustiere
E E | Welches Tier ist hier gesucht? | 🧼🐻 | Waschbär | Nasenbär ; Dachs ; Marderhund | Es trägt eine schwarze Maske im Gesicht. ; Es stammt aus Nordamerika. ; Es scheint sein Futter im Wasser zu reinigen. | In Wahrheit ertastet der Waschbär seine Nahrung — die Nässe macht seine Pfoten noch empfindlicher.
E E | Welches Tier ist hier gesucht? | 🐜🐻 | Ameisenbär | Gürteltier ; Erdferkel ; Schuppentier | Es lebt in Süd- und Mittelamerika. ; Es hat keine Zähne. ; Seine Zunge ist extrem lang und klebrig. | Ein Großer Ameisenbär verspeist Zehntausende Ameisen und Termiten am Tag.
E E | Welches Tier ist hier gesucht? | 🌵🐷 | Stachelschwein | Igel ; Ameisenigel ; Gürteltier | Es ist ein Nagetier. ; Es kann seine Stacheln aufstellen und rasseln lassen. ; Trotz des Namens ist es nicht mit Schweinen verwandt. | Stachelschweine können ihre Stacheln nicht verschießen — sie lösen sich aber leicht und bleiben im Angreifer stecken.
C M | Wie nennt man ein männliches Kaninchen? | Rammler | Keiler ; Hengst ; Erpel | Es ist ein Begriff aus der Tierzucht. ; Beim Feldhasen sagt man ebenfalls so. ; Das Wort beginnt mit R. | Keiler ist das männliche Wildschwein, Hengst das männliche Pferd und Erpel der Enterich.
C M | Welche Katzenrasse ist für ihre nach vorn gefalteten Ohren bekannt? | Scottish Fold | Maine Coon ; Siam ; Norwegische Waldkatze | Sie stammt ursprünglich aus Schottland. ; Ihr Gesicht wirkt eulenhaft rund. ; Das zweite Wort im Namen heißt „falten“. | Die Ohrfaltung beruht auf einer Genmutation, die auch Knorpelprobleme verursachen kann — die Zucht ist umstritten.
C H | Welches Tier hat Fingerabdrücke, die denen des Menschen verblüffend ähneln? | Koala | Waschbär ; Faultier ; Känguru | Es lebt in Australien. ; Es frisst Eukalyptus. ; Es schläft bis zu 20 Stunden am Tag. | Selbst unter dem Mikroskop sind Koala-Fingerabdrücke kaum von menschlichen zu unterscheiden.
C H | Welches nahezu haarlose Nagetier lebt in unterirdischen Kolonien mit einer Königin? | Nacktmull | Wühlmaus ; Maulwurf ; Präriehund | Es lebt in Ostafrika. ; Es spürt kaum Schmerz und erkrankt fast nie an Krebs. ; Seine Haut ist rosa und runzlig. | Nacktmulle werden über 30 Jahre alt — für ein Nagetier dieser Größe ein Rekord.
W M | Eisbären haben unter ihrem weißen Fell eine schwarze Haut. | wahr | Die schwarze Haut nimmt Wärme auf — die Haare selbst sind eigentlich farblos und hohl.
W E | Pferde können im Stehen dösen, ohne umzufallen. | wahr | Ein Sehnen- und Bänderapparat stabilisiert ihre Beine — für den Tiefschlaf legen sie sich aber hin.
W E | Meerschweinchen sind eng mit Schweinen verwandt. | falsch | Meerschweinchen sind Nagetiere aus Südamerika — ihren Namen haben sie wohl von ihren quiekenden Lauten.
S M | Wie viele Zehen hat eine Hauskatze insgesamt an allen vier Pfoten? | 18 | Zehen | 15 | 8 | 30 | Mehr als 16. ; Weniger als 20. ; Vorne hat sie mehr als hinten. | Vorne sind es je fünf, hinten je vier — Katzen mit zusätzlichen Zehen nennt man polydaktyl.
S H de | Wie viele Millionen Hunde lebten 2023 in deutschen Haushalten? | 10.5 | Mio. | 20 | 1 | 50 | Mehr als fünf Millionen. ; Weniger als 15 Millionen. ; Katzen sind noch zahlreicher. | Beliebtestes Haustier blieb die Katze mit rund 15,7 Millionen Tieren.
O E | Sortiere diese Haustiere nach ihrer typischen Lebenserwartung — die kürzeste zuerst. | Hamster = ≈ 2 Jahre ; Wellensittich = ≈ 8 Jahre ; Hund = ≈ 12 Jahre ; Pferd = ≈ 28 Jahre | Der kleine Nager lebt am kürzesten. ; Der bunte Vogel folgt. ; Das Reittier wird am ältesten. | Große Hunderassen haben übrigens eine deutlich kürzere Lebenserwartung als kleine.
M M | Welche DREI dieser Tiere sind Beuteltiere? | Wombat ; Tasmanischer Teufel ; Opossum | Waschbär ; Faultier ; Gürteltier | Einer gräbt Baue in Australien. ; Einer lebt auf einer Insel südlich von Australien. ; Einer stammt aus Amerika. | Das Opossum zeigt, dass Beuteltiere nicht nur in Australien vorkommen.
M M | Welche DREI dieser Hunderassen stammen aus Deutschland? | Dackel ; Dobermann ; Boxer | Chihuahua ; Beagle ; Husky | Einer ist ein kurzbeiniger Jagdhund. ; Einer ist nach einem Steuereintreiber aus Thüringen benannt. ; Einer wurde in München gezüchtet. | Der Dobermann geht auf Karl Friedrich Louis Dobermann aus Apolda zurück.

@ pflanzen_baeume
E E | Welcher Baum ist hier gesucht? | 🐴🌰 | Rosskastanie | Esskastanie ; Walnuss ; Eiche | Kinder sammeln seine Früchte im Herbst zum Basteln. ; Die Früchte sind für Menschen ungenießbar. ; Im Namen steckt ein großes Tier. | Der Name kommt vermutlich daher, dass man die Früchte früher als Heilmittel für hustende Pferde nutzte.
E E | Welcher Baum ist hier gesucht? | 🦣🌳 | Mammutbaum | Affenbrotbaum ; Drachenbaum ; Eukalyptus | Er stammt aus Kalifornien. ; Er gehört zu den größten Lebewesen der Erde. ; Im Namen steckt ein ausgestorbenes Tier. | Die dicke, schwammige Rinde schützt Mammutbäume vor Waldbränden.
E H | Welcher Baum ist hier gesucht? | 😢🌳 | Trauerweide | Hängebirke ; Zitterpappel ; Blutbuche | Seine Zweige hängen bis zum Boden. ; Er steht gern am Wasser. ; Er wirkt, als ließe er traurig den Kopf hängen. | Weidenrinde enthält Salicin — daraus entwickelte man später den Wirkstoff von Aspirin.
C E | Aus der Rinde welches Baums wird Kork gewonnen? | Korkeiche | Birke ; Kiefer ; Buche | Sie wächst rund ums Mittelmeer. ; Portugal ist der größte Produzent. ; Sie ist ein immergrüner Baum. | Die Rinde wächst nach dem Schälen nach — etwa alle neun Jahre kann man neu ernten.
C H | Welche Giftpflanze trägt den lateinischen Beinamen „belladonna“ — „schöne Frau“? | Tollkirsche | Eisenhut ; Fingerhut ; Stechapfel | Ihre Beeren sind schwarz und glänzend. ; Früher tropften sich Frauen ihren Saft in die Augen. ; Sie erweitert die Pupillen. | Große Pupillen galten als schön — der Wirkstoff Atropin wird noch heute beim Augenarzt eingesetzt.
C M de | Welche Pflanze ist auf der deutschen Seite der 1-, 2- und 5-Cent-Münzen abgebildet? | Ein Eichenzweig | Ein Lindenblatt ; Ein Ahornblatt ; Eine Kornähre | Sie stand schon auf den alten Pfennig-Stücken. ; Die Blätter sind gebuchtet. ; Der Baum gilt als Sinnbild für Stärke. | Die 10-, 20- und 50-Cent-Münzen zeigen dagegen das Brandenburger Tor.
C U de | Welcher Baum war in Deutschland der „Baum des Jahres 2024“? | Echte Mehlbeere | Moorbirke ; Rotbuche ; Flatterulme | Seine Blätter sind unterseits weißfilzig. ; Seine Früchte wurden in Notzeiten getrocknet unters Mehl gemischt. ; Er gehört zu den Rosengewächsen. | Die Mehlbeere verträgt Hitze und Trockenheit gut — ein Baum mit Zukunft im Klimawandel.
C U de | Zu welcher Baumart gehört „Waldtraut vom Mühlwald“, einer der höchsten Bäume Deutschlands? | Douglasie | Fichte ; Weißtanne ; Mammutbaum | Der Baum steht bei Freiburg im Breisgau. ; Die Art stammt aus Nordamerika. ; Sie wurde nach einem schottischen Botaniker benannt. | Die über 60 Meter hohe Douglasie überragt alle heimischen Bäume in ihrer Umgebung deutlich.
W H | Manche Bambusarten blühen nur alle paar Jahrzehnte — und dann alle Pflanzen einer Art gleichzeitig. | wahr | Nach der Massenblüte sterben die Pflanzen oft ab — in Teilen Asiens folgen darauf gefürchtete Rattenplagen.
W E | Tulpen stammen ursprünglich aus den Niederlanden. | falsch | Tulpen stammen aus Zentralasien und kamen im 16. Jahrhundert über das Osmanische Reich nach Europa.
S M log | Wie viele Billionen Bäume gibt es laut einer Studie von 2015 ungefähr auf der Erde? | 3 | Billionen | 30 | 0.1 | 100 | Mehr als eine Billion. ; Weniger als zehn Billionen. ; Rund 400 pro Mensch. | Seit Beginn der Landwirtschaft hat die Menschheit etwa die Hälfte aller Bäume gefällt.
S H | Wie viele Zentimeter kann schnellwachsender Bambus an einem einzigen Tag zulegen? | 90 | cm | 30 | 1 | 500 | Mehr als 30 Zentimeter. ; Weniger als zwei Meter. ; Man könnte ihm fast beim Wachsen zusehen. | Bambus ist ein Gras — und gilt als die am schnellsten wachsende Pflanze der Welt.
O M | Sortiere diese Bäume nach ihrem möglichen Höchstalter — den kurzlebigsten zuerst. | Hängebirke = ≈ 120 Jahre ; Rotbuche = ≈ 300 Jahre ; Linde = ≈ 1000 Jahre ; Eibe = über 2000 Jahre | Der Baum mit weißer Rinde wird nicht alt. ; Die Buche folgt. ; Der giftige Nadelbaum wird am ältesten. | Einige Eiben in Deutschland werden auf weit über 1.000 Jahre geschätzt.
M E | Welche ZWEI dieser Pflanzen fangen Insekten? | Sonnentau ; Kannenpflanze | Kaktus ; Efeu ; Mistel ; Farn | Eine hat klebrige Tröpfchen auf den Blättern. ; Die andere lockt Beute in Fallen aus Blattkannen. ; Beide wachsen oft auf nährstoffarmen Böden. | Fleischfressende Pflanzen holen sich so den Stickstoff, der ihrem Boden fehlt.
M M | Welche DREI dieser Pflanzen sind stark giftig? | Maiglöckchen ; Eisenhut ; Herbstzeitlose | Bärlauch ; Gänseblümchen ; Löwenzahn | Eine blüht im Frühling mit weißen Glöckchen. ; Eine gilt als giftigste Pflanze Europas. ; Eine blüht im Herbst auf Wiesen wie ein Krokus. | Bärlauch wird leicht mit Maiglöckchen oder Herbstzeitlose verwechselt — sein Knoblauchgeruch hilft bei der Unterscheidung.

@ tier_rekorde
E E | Welches Tier ist hier gesucht? | 🥾🦅 | Wanderfalke | Steinadler ; Turmfalke ; Seeadler | Es ist das schnellste Tier der Welt. ; Es jagt andere Vögel im Sturzflug. ; Es brütet gern auf hohen Gebäuden. | Nach dem Verbot des Insektengifts DDT erholten sich die Bestände — heute brütet er sogar auf Kirchtürmen und Kraftwerken.
E H | Welcher Vogel ist hier gesucht? | 💐🐦 | Strauß | Emu ; Nandu ; Kasuar | Er ist der größte Vogel der Welt. ; Er lebt in Afrika. ; Er legt die größten Eier aller Vögel. | Ein einziges Straußenei ersetzt in der Küche etwa zwei Dutzend Hühnereier.
C M | Welches Säugetier gilt nach Körperlänge als kleinstes der Welt? | Hummelfledermaus | Etruskerspitzmaus ; Zwergmaus ; Zwergseidenäffchen | Es kann fliegen. ; Es lebt in Höhlen in Thailand und Myanmar. ; Es wiegt nur etwa zwei Gramm. | Nach Gewicht konkurriert die Hummelfledermaus mit der Etruskerspitzmaus um den Titel.
C U | Wie hieß der Graupapagei, der mit der Forscherin Irene Pepperberg Farben, Formen und Zahlen lernte? | Alex | Polly ; Coco ; Kiki | Sein Name war die Abkürzung eines Forschungsprojekts. ; Er starb 2007. ; Er hat vier Buchstaben. | Alex beherrschte über 100 Wörter und konnte Gegenstände nach Farbe und Material unterscheiden.
C M | Zu welcher Rasse gehörte „Zeus“, laut Guinness-Buch lange der größte Hund der Welt? | Deutsche Dogge | Irischer Wolfshund ; Bernhardiner ; Mastiff | Die Rasse heißt auf Englisch „Great Dane“. ; Zeus lebte in den USA. ; Er maß über 1,10 Meter Schulterhöhe. | Auf den Hinterbeinen stehend war Zeus über zwei Meter groß.
C H | Welcher Fisch überdauert Trockenzeiten jahrelang eingegraben im Schlamm? | Lungenfisch | Schlammspringer ; Wels ; Quastenflosser | Er kann Luft atmen. ; Er lebt in Afrika, Südamerika und Australien. ; Sein Name verrät ein ungewöhnliches Atmungsorgan. | Afrikanische Lungenfische bauen sich im Schlamm einen Schleimkokon und können so mehrere Jahre überleben.
W M | Das Herz einer Giraffe wiegt über zehn Kilogramm. | wahr | Das kräftige Herz muss das Blut über zwei Meter hoch bis ins Gehirn pumpen — der Blutdruck ist etwa doppelt so hoch wie beim Menschen.
W E | Ein Gepard kann sein Höchsttempo über mehrere Kilometer halten. | falsch | Der Gepard ist ein Sprinter — schon nach wenigen Hundert Metern muss er erschöpft abbrechen.
S M | Wie alt wurde die Katze Creme Puff, laut Guinness-Buch die älteste Hauskatze aller Zeiten? | 38 | Jahre | 15 | 10 | 60 | Älter als 30. ; Jünger als 40. ; Sie starb 2005 in Texas. | Ihr Besitzer Jake Perry zog auch den früheren Rekordhalter Grandpa Rexs Allen groß.
S U | Wie alt wurde der australische Hütehund Bluey, jahrzehntelang Rekordhalter als ältester Hund? | 29 | Jahre | 10 | 10 | 50 | Deutlich älter als 20. ; Jünger als 35. ; Er starb 1939. | Bluey hütete fast 20 Jahre lang Rinder und Schafe — sein Rekord hielt über 80 Jahre.
S U | Wie viele Kilogramm wiegt das Gehirn eines Pottwals ungefähr — das schwerste im Tierreich? | 8 | kg | 25 | 1 | 50 | Mehr als das Dreifache eines Menschengehirns. ; Weniger als zehn Kilogramm. ; Mehr als fünf Kilogramm. | Ein menschliches Gehirn wiegt dagegen nur rund 1,4 Kilogramm.
O M | Sortiere diese Tiere nach ihrer Herzfrequenz in Ruhe — die langsamste zuerst. | Blauwal = ≈ 2–10 Schläge/min ; Elefant = ≈ 30 Schläge/min ; Hund = ≈ 90 Schläge/min ; Hausmaus = ≈ 600 Schläge/min | Der größte Tierkoloss hat den langsamsten Takt. ; Der Dickhäuter folgt. ; Das kleinste Tier hat den schnellsten Puls. | Faustregel: Je kleiner ein Säugetier, desto schneller schlägt sein Herz.
O H | Sortiere diese Schlangen nach ihrer maximalen Länge — die kürzeste zuerst. | Kreuzotter = ≈ 0,8 m ; Schwarze Mamba = ≈ 3 m ; Königskobra = ≈ 5,5 m ; Netzpython = über 8 m | Die heimische Giftschlange ist die kürzeste. ; Die schnelle Afrikanerin folgt. ; Die Riesenschlange aus Südostasien ist am längsten. | Die Königskobra ist die längste Giftschlange der Welt — sie frisst vor allem andere Schlangen.
M E | Welche DREI dieser Vögel können nicht fliegen? | Strauß ; Emu ; Kiwi | Kondor ; Albatros ; Pelikan | Einer ist der größte Vogel der Welt. ; Einer lebt in Australien. ; Einer ist das Nationalsymbol Neuseelands. | Laufvögeln fehlt der Kiel am Brustbein, an dem kräftige Flugmuskeln ansetzen könnten.

@ wetter_naturphaenomene
E E | Welches Wetterereignis ist hier gesucht? | ☁️💔 | Wolkenbruch | Nieselregen ; Landregen ; Schneeregen | Es kommt meist plötzlich. ; In kurzer Zeit fällt sehr viel Wasser. ; Die Wolke scheint zu zerbrechen. | Nach einem Wolkenbruch laufen oft Keller voll, weil die Kanalisation die Wassermassen nicht fassen kann.
E E | Welches Wetterphänomen ist hier gesucht? | 🔥🌊 | Hitzewelle | Flächenbrand ; Tsunami ; Föhnsturm | Sie tritt vor allem im Sommer auf. ; Mehrere Tage hintereinander ist es extrem heiß. ; Dann gibt der Wetterdienst Hitzewarnungen heraus. | Tage ab 30 Grad nennen Meteorologen „heiße Tage“, Nächte über 20 Grad „Tropennächte“.
E H | Welches Wetterphänomen ist hier gesucht? | ⚡🧊 | Blitzeis | Hagel ; Raureif ; Graupel | Autofahrer fürchten es besonders. ; Regen gefriert sofort auf dem kalten Boden. ; Es entsteht schlagartig. | Blitzeis entsteht, wenn Regen auf gefrorenen Boden fällt — Straßen werden in Minuten spiegelglatt.
C E | Wie nennt man eine Luftspiegelung, bei der man in der Wüste scheinbar Wasser sieht? | Fata Morgana | Nordlicht ; Halo ; Wetterleuchten | Sie entsteht über heißen Luftschichten. ; Das Licht wird dabei abgelenkt. ; Der Name stammt von einer Fee aus der Artussage. | Auch auf heißen Straßen sieht man im Sommer oft scheinbare Pfützen — eine kleine Fata Morgana.
C M de | Wie nennt man den Kälteeinbruch, der oft Mitte Juni in Mitteleuropa auftritt? | Schafskälte | Eisheilige ; Altweibersommer ; Hundstage | Zu der Zeit sind viele Tiere auf der Weide frisch geschoren. ; Sie folgt im Kalender nach den Eisheiligen. ; Ein Nutztier steckt im Namen. | Die frisch geschorenen Schafe froren früher besonders — daher der Name.
C H | Mit welcher Skala wird die Stärke von Tornados eingeteilt? | Fujita-Skala | Beaufort-Skala ; Richterskala ; Saffir-Simpson-Skala | Sie wurde 1971 eingeführt. ; Sie reicht von F0 bis F5. ; Ihr Erfinder war ein japanisch-amerikanischer Meteorologe. | Weil sich die Windstärke kaum direkt messen lässt, bewertet man Tornados meist anhand der Schäden.
C M | Wie heißt ein Lichtring um Sonne oder Mond, der durch Eiskristalle in hohen Wolken entsteht? | Halo | Aureole ; Glorie ; Korona | Oft kündigt er einen Wetterumschwung an. ; Das Licht wird in winzigen Eiskristallen gebrochen. ; Das Wort kommt aus dem Griechischen. | Der häufigste Halo ist der 22-Grad-Ring — etwa so groß wie eine ausgestreckte Hand am Himmel.
C U de | Welche Institution vergibt seit 1954 in Deutschland die Namen für Hoch- und Tiefdruckgebiete? | Die Freie Universität Berlin | Der Deutsche Wetterdienst ; Die Weltorganisation für Meteorologie ; Das ZDF | Es ist eine Hochschule. ; Seit 2002 kann man dort Wetterpatenschaften kaufen. ; Sie sitzt in der Hauptstadt. | Wer eine Patenschaft kauft, darf ein Hoch oder Tief nach sich benennen — das Geld finanziert Wetterbeobachtungen.
W M | Fallende Regentropfen haben die typische Tränenform mit einer Spitze oben. | falsch | Kleine Tropfen sind kugelrund, größere werden durch den Luftwiderstand unten abgeflacht — ähnlich wie ein Brötchen.
W E | Hagelkörner werden nie größer als eine Murmel. | falsch | Hagel kann größer als Tennisbälle werden — das Rekordkorn aus den USA von 2010 hatte rund 20 Zentimeter Durchmesser.
W M | Wetterleuchten ist ein eigenes Phänomen, das ganz ohne Gewitter entsteht. | falsch | Wetterleuchten sind Blitze eines weit entfernten Gewitters — der Donner ist nur zu weit weg, um ihn zu hören.
S H de | Welche Höchsttemperatur wurde in Deutschland offiziell gemessen? | 41.2 | °C | 10 | 30 | 50 | Mehr als 40 Grad. ; Weniger als 45 Grad. ; Gemessen im Juli 2019. | Den Rekord teilen sich Duisburg-Baerl und Tönisvorst — ein zunächst gemeldeter Wert aus Lingen wurde aberkannt.
S U | Ab welcher Windgeschwindigkeit in km/h beginnt die stärkste Tornado-Stufe EF5? | 322 | km/h | 20 | 50 | 1000 | Mehr als 250 km/h. ; Weniger als 400 km/h. ; Schneller als ein ICE auf voller Fahrt. | EF5-Tornados zerstören selbst massive Häuser bis auf die Grundmauern — zum Glück sind sie extrem selten.
O E | Sortiere diese Farben, wie sie im Hauptregenbogen von außen nach innen erscheinen. | Rot = ganz außen ; Gelb = nach Orange ; Grün = in der Mitte ; Violett = ganz innen | Die wärmste Farbe liegt außen. ; Gelb kommt vor Grün. ; Innen schimmert es violett. | Im schwächeren Nebenregenbogen ist die Reihenfolge der Farben genau umgekehrt.
O H | Sortiere diese Himmelserscheinungen nach ihrer typischen Höhe — die niedrigste zuerst. | Nebel = am Boden ; Cirruswolken = ≈ 8–12 km ; Leuchtende Nachtwolken = ≈ 83 km ; Polarlicht = ≈ 100–300 km | Die tiefste Erscheinung berührt den Boden. ; Die Federwolken folgen. ; Die bunten Vorhänge am Polarhimmel leuchten am höchsten. | Leuchtende Nachtwolken bilden sich in der Mesosphäre — so hoch wie keine anderen Wolken der Erde.
M M | Welche ZWEI dieser Erscheinungen entstehen durch Lichtbrechung an Wassertropfen oder Eiskristallen? | Regenbogen ; Halo | Polarlicht ; Wetterleuchten ; Elmsfeuer ; Blitz | Einer zeigt sieben Farben. ; Der andere bildet einen Ring um die Sonne. ; Die falschen entstehen durch elektrische Vorgänge oder Teilchen aus dem All. | Polarlichter entstehen durch den Sonnenwind, Elmsfeuer, Blitz und Wetterleuchten durch elektrische Entladungen.
"""
