"""Extra questions, wave 2: Wissenschaft (format: see tools/content/merge_extra.py)."""
KAT = "wissenschaft"
REGION = "global"
DATA = r"""
@ physik_chemie
E E | Welcher Begriff ist hier gesucht? | 💧🧵 | Wasserstoff | Sauerstoff ; Stickstoff ; Kohlenstoff | Es ist ein chemisches Element. ; Es ist das leichteste Element überhaupt. ; Zusammen mit Sauerstoff bildet es das, was aus dem Wasserhahn kommt. | Wasserstoff macht rund drei Viertel der Masse aller normalen Materie im Universum aus.
E E | Welcher Begriff ist hier gesucht? | 🌈🔺 | Prisma | Linse ; Lupe ; Spiegel | Es ist ein durchsichtiger Glaskörper. ; Es zerlegt weißes Licht in die Regenbogenfarben. ; Pink Floyd zeigt es auf dem Cover von „The Dark Side of the Moon“. | Isaac Newton zeigte mit Prismen, dass weißes Licht ein Gemisch aus allen Spektralfarben ist.
E E | Welcher Begriff ist hier gesucht? | 🩳🔚⚡ | Kurzschluss | Stromausfall ; Überspannung ; Wackelkontakt | Es ist ein Begriff aus der Elektrik. ; Danach springt oft die Sicherung heraus. ; Plus- und Minuspol sind dabei direkt miteinander verbunden. | Weil der Widerstand fast null ist, fließt ein riesiger Strom — Sicherungen unterbrechen ihn, bevor die Leitungen überhitzen.
E H | Welcher Begriff ist hier gesucht? | ⚛️🤝⚛️ | Kernfusion | Kernspaltung ; Kettenreaktion ; Radioaktiver Zerfall | Sie ist die Energiequelle der Sterne. ; Leichte Atomkerne verschmelzen dabei zu schwereren. ; Der Forschungsreaktor ITER in Südfrankreich soll sie auf der Erde nutzbar machen. | Die Sonne verschmilzt jede Sekunde rund 600 Millionen Tonnen Wasserstoff zu Helium.
C E | Wofür steht das Kürzel Fe im Periodensystem? | Eisen | Blei ; Zinn ; Fermium | Das Kürzel kommt vom lateinischen „ferrum“. ; Rost ist eine Verbindung dieses Metalls mit Sauerstoff. ; Stahl besteht größtenteils daraus. | Eisen ist das häufigste Element der Erde insgesamt — vor allem, weil der Erdkern zum großen Teil daraus besteht.
C M | Aus welchen beiden Metallen besteht klassische Bronze? | Kupfer und Zinn | Kupfer und Zink ; Eisen und Kohlenstoff ; Zinn und Blei | Eine ganze Epoche der Menschheitsgeschichte ist nach ihr benannt. ; Das Hauptmetall ist rötlich. ; Mit Zink statt des zweiten Metalls entsteht Messing. | Bronze ist deutlich härter als reines Kupfer — deshalb verdrängten Bronzewerkzeuge in der Bronzezeit viele Steinwerkzeuge.
C M | Wie nennt man Atome desselben Elements, die sich nur in der Zahl ihrer Neutronen unterscheiden? | Isotope | Ionen ; Isomere ; Moleküle | Sie haben gleich viele Protonen. ; Kohlenstoff-14 ist ein bekanntes Beispiel. ; Ihr Name bedeutet auf Griechisch „am gleichen Ort“ im Periodensystem. | Mit dem radioaktiven Kohlenstoff-14 bestimmen Forscher das Alter von Knochen, Holz und anderen organischen Funden.
C H | Welches chemische Element ist nach Deutschland benannt? | Germanium | Gallium ; Francium ; Polonium | Es ist ein Halbmetall. ; Clemens Winkler entdeckte es 1886 im sächsischen Freiberg. ; Sein Name leitet sich vom lateinischen Namen des Landes ab. | Mendelejew hatte das Element schon 1871 als „Eka-Silizium“ vorhergesagt — samt erstaunlich genauer Eigenschaften.
C U | Nach welchem schwedischen Ort sind gleich vier chemische Elemente benannt? | Ytterby | Uppsala ; Falun ; Kiruna | Er liegt auf einer Insel nahe Stockholm. ; In seiner Grube fand man ein Mineral voller seltener Erden. ; Die Elemente heißen Yttrium, Ytterbium, Terbium und Erbium. | Kein anderer Ort der Welt hat dem Periodensystem so viele Elementnamen geschenkt.
W E | Im Vakuum fallen eine Feder und ein Hammer gleich schnell. | wahr | Apollo-15-Astronaut David Scott führte das 1971 auf dem Mond vor — beide kamen gleichzeitig am Boden an.
W E | Ein Ring aus reinem Gold wird von einem Magneten angezogen. | falsch | Gold ist nicht magnetisch — bleibt ein „Goldring“ am Magneten hängen, steckt ein anderes Metall darin.
W M | Diamant leitet elektrischen Strom sehr gut. | falsch | Diamant ist ein elektrischer Isolator — Wärme leitet er dagegen besser als fast jedes andere Material.
S M | In welchem Jahr veröffentlichte Albert Einstein seine Spezielle Relativitätstheorie? | 1905 | Jahr | 3 | 1850 | 1950 | Anfang des 20. Jahrhunderts. ; Einstein arbeitete damals am Patentamt in Bern. ; Das Jahr gilt als sein „Wunderjahr“. | Im selben Jahr erschienen auch seine Arbeiten zum Photoeffekt und zur Brownschen Bewegung — und die Formel E = mc².
S H | Wie viele Gramm wiegt ein Kubikzentimeter reines Gold? | 19.3 | g | 15 | 1 | 50 | Mehr als zehn Gramm. ; Weniger als 25 Gramm. ; Deutlich mehr als Blei mit gut elf Gramm. | Ein Goldwürfel mit nur 37 Zentimetern Kantenlänge wöge bereits rund eine Tonne.
O E | Sortiere diese Stoffe nach ihrem pH-Wert — den sauersten zuerst. | Zitronensaft = ≈ 2 ; Schwarzer Kaffee = ≈ 5 ; Reines Wasser = 7 ; Rohrreiniger = ≈ 13 | Die gelbe Frucht ist am sauersten. ; Das Morgengetränk ist nur leicht sauer. ; Das Mittel gegen verstopfte Abflüsse ist stark basisch. | Jeder Schritt auf der pH-Skala bedeutet eine zehnfach höhere oder niedrigere Konzentration an Wasserstoff-Ionen.
O U | Sortiere diese Teilchen nach dem Jahr ihrer Entdeckung — das früheste zuerst. | Elektron = 1897 ; Proton = 1919 ; Neutron = 1932 ; Higgs-Boson = 2012 | Das Teilchen des elektrischen Stroms wurde zuerst gefunden. ; Den positiv geladenen Kernbaustein wies Ernest Rutherford nach. ; Das jüngste wurde am Teilchenbeschleuniger LHC bei Genf aufgespürt. | Erst mit James Chadwicks Neutron ließ sich erklären, warum Atomkerne schwerer sind, als ihre Protonen allein vermuten lassen.
M M | Welche ZWEI dieser Elemente sind bei Raumtemperatur gasförmig? | Stickstoff ; Chlor | Brom ; Schwefel ; Iod ; Natrium | Eines macht den Großteil der Luft aus. ; Das andere wird zur Desinfektion von Schwimmbädern eingesetzt. ; Brom ist dagegen eines von nur zwei flüssigen Elementen. | Brom und Quecksilber sind die einzigen Elemente, die bei Raumtemperatur flüssig sind.
M H | Welche ZWEI dieser Maßeinheiten sind nach deutschen Physikern benannt? | Hertz ; Ohm | Volt ; Ampere ; Watt ; Newton | Einer wies als Erster elektromagnetische Wellen nach. ; Der andere fand ein Gesetz über Strom, Spannung und Widerstand. ; Die übrigen Namensgeber stammen aus Italien, Frankreich und Großbritannien. | Heinrich Hertz stammte aus Hamburg, Georg Simon Ohm aus Erlangen.

@ biologie_koerper
E E | Welcher Begriff ist hier gesucht? | 👆🖨️ | Fingerabdruck | Handlinie ; Fingernagel ; Muttermal | Jeder Mensch hat einen einzigartigen. ; Die Polizei sichert ihn am Tatort. ; Er entsteht aus feinen Hautleisten an den Fingerkuppen. | Selbst eineiige Zwillinge haben unterschiedliche Fingerabdrücke.
E E | Welcher Körperteil ist hier gesucht? | 👨🍎 | Adamsapfel | Kehlkopfdeckel ; Stimmband ; Mandel | Er sitzt vorn am Hals. ; Bei Männern tritt er meist deutlich hervor. ; Er ist ein Teil des Kehlkopfs. | Der Name geht auf die Legende zurück, Adam sei ein Stück des verbotenen Apfels im Hals stecken geblieben.
E M | Welcher Knochen ist hier gesucht? | 🛤️🦵 | Schienbein | Wadenbein ; Oberschenkelknochen ; Sprungbein | Er liegt im Unterschenkel. ; Fußballer schützen ihn mit Schonern. ; Stößt man ihn an einer Kante, tut es besonders weh. | Direkt unter der Haut liegen hier kaum Muskeln oder Fett — deshalb schmerzt jeder Stoß so sehr.
C E | Wie nennt man Lebewesen, die nur aus einer einzigen Zelle bestehen? | Einzeller | Mehrzeller ; Viren ; Moleküle | Bakterien gehören dazu. ; Auch Amöben und Pantoffeltierchen zählen dazu. ; Das Wort verrät die Zahl ihrer Zellen. | Die ältesten bekannten Lebensspuren der Erde stammen von Einzellern und sind rund 3,5 Milliarden Jahre alt.
C E | Wie heißen die „Kraftwerke der Zelle“, die aus Nährstoffen Energie gewinnen? | Mitochondrien | Ribosomen ; Chloroplasten ; Lysosomen | Sie besitzen eine eigene DNA. ; Muskelzellen haben besonders viele davon. ; Man erbt sie fast ausschließlich von der Mutter. | Mitochondrien stammen vermutlich von Bakterien ab, die vor über einer Milliarde Jahren in andere Zellen einzogen.
C M | Welches Organ verbraucht rund ein Fünftel der Energie des Körpers, obwohl es nur etwa zwei Prozent des Körpergewichts ausmacht? | Das Gehirn | Das Herz ; Die Lunge ; Die Haut | Es arbeitet auch im Schlaf auf Hochtouren. ; Es wiegt beim Erwachsenen rund 1,4 Kilogramm. ; Es sitzt gut geschützt im Schädel. | Als Brennstoff nutzt das Gehirn fast nur Traubenzucker — deutlich über 100 Gramm am Tag.
C H | Welcher Arzt entdeckte 1901 die Blutgruppen des AB0-Systems? | Karl Landsteiner | Robert Koch ; Paul Ehrlich ; Rudolf Virchow | Er stammte aus Wien. ; Er erhielt dafür 1930 den Nobelpreis für Medizin. ; Sein Geburtstag, der 14. Juni, ist heute Weltblutspendetag. | Erst durch seine Entdeckung wurden Bluttransfusionen sicher — vorher endeten sie oft tödlich.
C U | Wie heißt der Fachbegriff für die Unfähigkeit, Gesichter zu erkennen? | Prosopagnosie | Aphasie ; Amnesie ; Synästhesie | Betroffene erkennen Freunde oft nur an Stimme, Frisur oder Gang. ; Umgangssprachlich spricht man von Gesichtsblindheit. ; Der Begriff beginnt mit dem griechischen Wort „prosopon“ für Gesicht. | Die Störung kann angeboren sein oder nach einer Verletzung bestimmter Hirnregionen entstehen.
W E | Das Herz eines Menschen ist ungefähr so groß wie seine Faust. | wahr | Das Herz wächst mit dem Körper mit — bei Kindern ist es entsprechend kleiner, bei Erwachsenen etwa faustgroß.
W M | Das Gehirn selbst spürt Schmerz, wenn man hineinschneidet. | falsch | Das Hirngewebe hat keine Schmerzrezeptoren — deshalb sind manche Hirnoperationen bei wachen Patienten möglich.
W H | Im Körper eines Erwachsenen leben ungefähr genauso viele Bakterien, wie er eigene Körperzellen hat. | wahr | Die alte Faustregel „zehnmal so viele Bakterien wie Körperzellen“ gilt seit einer Neuberechnung von 2016 als überholt — das Verhältnis liegt eher bei eins zu eins.
S M | Wie viele Millimeter wächst ein Kopfhaar ungefähr in einem Monat? | 12 | mm | 30 | 1 | 50 | Mehr als einen halben Zentimeter. ; Weniger als zwei Zentimeter. ; Gut einen Zentimeter. | Ein einzelnes Kopfhaar wächst meist zwei bis sechs Jahre lang, bevor es ausfällt und ein neues nachkommt.
S H | Wie viele Tage lebt ein rotes Blutkörperchen ungefähr? | 120 | Tage | 20 | 5 | 1000 | Mehr als einen Monat. ; Weniger als ein halbes Jahr. ; Rund vier Monate. | Ausgediente rote Blutkörperchen werden vor allem in Milz und Leber abgebaut — das Knochenmark bildet jede Sekunde Millionen neue.
S U log | Wie viele Milliarden Nervenzellen hat das menschliche Gehirn ungefähr? | 86 | Mrd. | 25 | 1 | 1000 | Mehr als 50 Milliarden. ; Weniger als 100 Milliarden. ; Gut zehnmal so viele, wie Menschen auf der Erde leben. | Die lange zitierte Zahl von 100 Milliarden korrigierte die Forscherin Suzana Herculano-Houzel 2009 auf rund 86 Milliarden.
O M | Sortiere diese Zellen und Erreger nach ihrer Größe — das kleinste zuerst. | Grippevirus = ≈ 0,1 µm ; Darmbakterium E. coli = ≈ 2 µm ; Rotes Blutkörperchen = ≈ 7,5 µm ; Menschliche Eizelle = ≈ 0,1 mm | Viren sind winziger als Bakterien. ; Die Blutzelle ist gut dreimal so groß wie das Bakterium. ; Die größte Zelle des Menschen ist gerade noch mit bloßem Auge sichtbar. | Die Eizelle ist die größte Zelle des menschlichen Körpers — die Samenzelle gehört dagegen zu den kleinsten.
O U | Sortiere diese Lebewesen nach der Zahl der Chromosomen in ihren Körperzellen — die wenigsten zuerst. | Fruchtfliege = 8 ; Mensch = 46 ; Schimpanse = 48 ; Hund = 78 | Das kleine Obst-Insekt hat die wenigsten. ; Unser nächster Verwandter hat zwei mehr als wir. ; Der beste Freund des Menschen hat die meisten. | Die Chromosomenzahl sagt nichts über die Komplexität aus — manche Farne haben über 1.000 Chromosomen.
M M | Welche ZWEI dieser Krankheiten werden durch Viren ausgelöst? | Masern ; Grippe | Tuberkulose ; Malaria ; Scharlach ; Tetanus | Beide Erreger sind viel kleiner als Bakterien. ; Eine der Krankheiten trifft oft Kinder und verursacht rote Hautflecken. ; Die andere rollt fast jeden Winter als Welle heran. | Tuberkulose, Scharlach und Tetanus werden von Bakterien ausgelöst, Malaria von einzelligen Parasiten.
M H | Welche ZWEI dieser Vitamine sind fettlöslich? | Vitamin A ; Vitamin E | Vitamin C ; Vitamin B12 ; Folsäure ; Vitamin B1 | Der Körper kann sie im Fettgewebe und in der Leber speichern. ; Eines steckt als Vorstufe in Karotten. ; Das andere steckt reichlich in Pflanzenölen wie Weizenkeimöl. | Fettlöslich sind die Vitamine A, D, E und K — Merkhilfe: „EDEKA“.

@ weltraum_astronomie
E E | Welcher Begriff ist hier gesucht? | 🥛🛣️ | Milchstraße | Sternbild ; Andromeda ; Sternschnuppe | Man sieht sie in dunklen Nächten als hellen Streifen. ; Sie ist eine Galaxie. ; Auch unser Sonnensystem liegt in ihr. | Die Milchstraße enthält schätzungsweise 100 bis 400 Milliarden Sterne.
E E | Welcher Begriff ist hier gesucht? | 🛰️🗑️ | Weltraumschrott | Meteoritenschauer ; Asteroidengürtel ; Sternenstaub | Er kreist um die Erde. ; Dazu zählen ausgediente Satelliten und abgesprengte Raketenstufen. ; Die ISS muss ihm manchmal ausweichen. | Radarstationen verfolgen Zehntausende Trümmerteile, die größer als zehn Zentimeter sind — kleinere gibt es millionenfach.
E H | Welcher Begriff ist hier gesucht? | ☀️🌬️ | Sonnenwind | Sonnenfleck ; Föhn ; Sonnenfinsternis | Er weht von der Sonne hinaus ins All. ; Er besteht aus elektrisch geladenen Teilchen. ; Trifft er auf das Erdmagnetfeld, entstehen Polarlichter. | Er rast mit mehreren Hundert Kilometern pro Sekunde durchs Sonnensystem.
C E | Welcher Planet ist nach dem römischen Gott des Meeres benannt? | Neptun | Uranus ; Saturn ; Merkur | Er ist der äußerste Planet des Sonnensystems. ; Auf Fotos leuchtet er tiefblau. ; Sein Symbol ist ein Dreizack. | Auch der griechische Meeresgott Poseidon trägt einen Dreizack — daher das Planetensymbol.
C M | Welcher Gasriese dreht sich am schnellsten um die eigene Achse — ein Tag dauert dort keine zehn Stunden? | Jupiter | Saturn ; Uranus ; Neptun | Galileo Galilei entdeckte seine vier großen Monde. ; Sein Großer Roter Fleck ist ein uralter Sturm. ; Er ist der größte Planet überhaupt. | Durch die rasante Drehung ist Jupiter an den Polen deutlich abgeplattet.
C M | Welcher Jupitermond ist der größte Mond des Sonnensystems? | Ganymed | Io ; Europa ; Kallisto | Er ist sogar größer als der Planet Merkur. ; Galileo Galilei entdeckte ihn 1610. ; Er ist nach dem Mundschenk der griechischen Götter benannt. | Ganymed besitzt als einziger bekannter Mond ein eigenes Magnetfeld.
C H | Aus welchem Saturnmond schießen am Südpol Wasserfontänen ins All? | Enceladus | Titan ; Mimas ; Rhea | Er ist von einer hellen Eiskruste überzogen. ; Die Raumsonde Cassini flog mehrfach durch seine Fontänen. ; Unter seinem Eis vermuten Forscher einen Ozean. | Enceladus reflektiert fast das gesamte Sonnenlicht — er ist einer der hellsten Körper im Sonnensystem.
C U | Welcher Stern wird in rund 12.000 Jahren der Polarstern sein? | Wega | Sirius ; Beteigeuze ; Arktur | Er ist der hellste Stern im Sternbild Leier. ; Er bildet mit Deneb und Atair das Sommerdreieck. ; Schuld am Wechsel ist die langsame Kreiselbewegung der Erdachse. | Ein vollständiger Umlauf dieser Präzession dauert rund 26.000 Jahre — dann ist wieder der heutige Polarstern an der Reihe.
W E | Auf dem Mond ist der Himmel auch am helllichten Tag schwarz. | wahr | Ohne Atmosphäre wird das Sonnenlicht nicht gestreut — deshalb bleibt der Himmel dort selbst bei praller Sonne schwarz.
W M | Der Mond ist immer gleich weit von der Erde entfernt. | falsch | Seine Bahn ist elliptisch — der Abstand schwankt zwischen rund 356.000 und 407.000 Kilometern, daher gibt es „Supermonde“.
W H | Auf dem Mars leuchtet der Himmel beim Sonnenuntergang bläulich. | wahr | Feiner Staub in der Marsluft streut blaues Licht rund um die Sonne — Rover wie Curiosity haben die blauen Sonnenuntergänge fotografiert.
S M log | Wie viele Kilometer über der Erde kreist die Internationale Raumstation ISS ungefähr? | 400 | km | 20 | 10 | 5000 | Viel höher als jedes Verkehrsflugzeug. ; Weniger als 1.000 Kilometer. ; Etwa die Luftlinie von Hamburg nach Frankfurt. | Weil die dünne Restatmosphäre sie bremst, muss die ISS regelmäßig mit Triebwerken wieder angehoben werden.
S H log | Mit wie vielen Kilometern pro Stunde bewegt sich ein Punkt am Äquator durch die Erddrehung? | 1670 | km/h | 20 | 100 | 10000 | Schneller als ein Verkehrsflugzeug. ; Weniger als 2.000 km/h. ; Erdumfang geteilt durch 24 Stunden. | In Deutschland sind es wegen der höheren geografischen Breite nur rund 1.000 km/h.
S U log | Wie viele Kilometer pro Sekunde muss ein Körper erreichen, um der Anziehungskraft der Erde ganz zu entkommen? | 11.2 | km/s | 20 | 1 | 100 | Mehr als zehn Kilometer pro Sekunde. ; Weniger als 15 Kilometer pro Sekunde. ; Rund 40.000 km/h. | Vom Mond aus genügen für die Flucht schon rund 2,4 Kilometer pro Sekunde.
O E | Sortiere diese Planeten nach ihrer mittleren Temperatur — den kältesten zuerst. | Neptun = ≈ −200 °C ; Mars = ≈ −60 °C ; Erde = ≈ 15 °C ; Venus = ≈ 460 °C | Der äußerste Planet ist der kälteste. ; Der Rote Planet ist frostig. ; Der Morgenstern ist dank dichter Treibhaus-Atmosphäre der heißeste. | Venus ist sogar heißer als der sonnennähere Merkur — ihre dichte Kohlendioxid-Hülle hält die Wärme fest.
O U | Sortiere diese Sterne nach ihrer Oberflächentemperatur — den kühlsten zuerst. | Beteigeuze = ≈ 3.600 K ; Sonne = ≈ 5.800 K ; Sirius A = ≈ 9.900 K ; Rigel = ≈ 12.000 K | Der rote Schulterstern des Orion ist am kühlsten. ; Unser eigener Stern liegt im Mittelfeld. ; Der blauweiße Fußstern des Orion ist am heißesten. | Die Farbe verrät die Temperatur: Rote Sterne sind vergleichsweise kühl, blauweiße besonders heiß.
M M | Welche ZWEI dieser Himmelskörper gelten offiziell als Zwergplaneten? | Pluto ; Eris | Titan ; Io ; Vesta ; Phobos | Einer war bis 2006 der neunte Planet. ; Der andere ist nach der griechischen Göttin der Zwietracht benannt. ; Beide kreisen jenseits des Neptun. | Die Entdeckung von Eris im Jahr 2005 löste die Debatte aus, die Pluto schließlich den Planetenstatus kostete.
M H | Welche ZWEI dieser Astronauten haben den Mond betreten? | Buzz Aldrin ; Alan Shepard | Michael Collins ; Jim Lovell ; Juri Gagarin ; John Glenn | Einer stieg 1969 kurz nach Neil Armstrong aus der Mondfähre. ; Der andere war zuvor schon der erste Amerikaner im All. ; Collins und Lovell flogen zwar zum Mond, setzten aber nie einen Fuß darauf. | Buzz Aldrin hieß eigentlich Edwin — seinen Spitznamen ließ er 1988 offiziell zum Vornamen machen.

@ mathe_logik
E E | Welcher Begriff ist hier gesucht? | ➕➖✖️➗ | Grundrechenarten | Bruchrechnung ; Algebra ; Kopfrechnen | Man lernt sie in der Grundschule. ; Es gibt genau vier davon. ; Plus, minus, mal und geteilt. | Bei gemischten Aufgaben gilt „Punkt vor Strich“: Mal und geteilt werden vor plus und minus gerechnet.
E M | Welches Diagramm ist hier gesucht? | 🎂📊 | Tortendiagramm | Balkendiagramm ; Liniendiagramm ; Streudiagramm | Es zeigt Anteile an einem Ganzen. ; Es ist kreisrund. ; Seine Stücke erinnern an ein Gebäck zum Geburtstag. | Auf Englisch heißt es „pie chart“ — dort denkt man also an Kuchen statt an Torte.
E H | Welcher Begriff ist hier gesucht? | 0️⃣➕🎲 | Nullsummenspiel | Glücksspiel ; Pattsituation ; Zufallsexperiment | Es ist ein Begriff aus der Spieltheorie. ; Was einer gewinnt, verliert ein anderer. ; Zusammengezählt ergeben alle Gewinne und Verluste genau null. | Der Mathematiker John von Neumann legte 1928 mit einer Arbeit über solche Spiele einen Grundstein der Spieltheorie.
C E | Wie heißt ein Fünfeck in der Fachsprache — genau wie das Gebäude des US-Verteidigungsministeriums? | Pentagon | Hexagon ; Oktagon ; Heptagon | Das Wort stammt aus dem Griechischen. ; „Penta“ bedeutet fünf. ; Das Gebäude steht in Arlington bei Washington. | Das Pentagon hat fünf Seiten, fünf Stockwerke über der Erde und fünf ringförmige Korridore.
C M | Wie viele Grad misst jeder Innenwinkel eines regelmäßigen Sechsecks? | 120 Grad | 90 Grad ; 108 Grad ; 135 Grad | Die Innenwinkelsumme eines Sechsecks beträgt 720 Grad. ; Man teilt sie durch die Zahl der Ecken. ; Es ist ein Drittel eines Vollkreises. | Weil drei solcher Winkel genau 360 Grad ergeben, lassen sich Sechsecke lückenlos aneinanderlegen — wie in Bienenwaben.
C M | Wie heißt das Zahlendreieck, in dem jede Zahl die Summe der beiden direkt darüber stehenden ist? | Pascalsches Dreieck | Sierpinski-Dreieck ; Penrose-Dreieck ; Reuleaux-Dreieck | Es beginnt an der Spitze mit einer einzelnen 1. ; An seinen Rändern stehen nur Einsen. ; Es ist nach einem französischen Mathematiker des 17. Jahrhunderts benannt. | Blaise Pascal beschrieb es um 1654 ausführlich — in China und Persien kannte man das Schema aber schon Jahrhunderte früher.
C H | Beim Ziegenproblem wählt man eine von drei Türen, dann öffnet der Moderator eine andere Tür mit einer Ziege. Was sollte man tun? | Zur anderen geschlossenen Tür wechseln | Bei der ersten Wahl bleiben ; Egal — die Chancen stehen 50 zu 50 ; Eine Münze entscheiden lassen | Der Moderator weiß, wo das Auto steht. ; Die erste Wahl trifft nur mit einem Drittel Wahrscheinlichkeit. ; Beim Wechsel gewinnt man in zwei von drei Fällen. | Als Marilyn vos Savant die Lösung 1990 in einer Zeitschrift erklärte, widersprachen ihr Tausende Leser — darunter viele Mathematiker.
C U | Welcher Mathematiker bewies die Poincaré-Vermutung und lehnte danach die Fields-Medaille und eine Million Dollar Preisgeld ab? | Grigori Perelman | Terence Tao ; Andrew Wiles ; John Nash | Er stammt aus Sankt Petersburg. ; Er veröffentlichte seinen Beweis 2002 und 2003 nur im Internet. ; Er lebt sehr zurückgezogen und meidet die Öffentlichkeit. | Die Poincaré-Vermutung ist bislang das einzige der sieben Millennium-Probleme, das gelöst wurde.
W E | Jedes Quadrat ist auch ein Rechteck. | wahr | Ein Rechteck braucht nur vier rechte Winkel — beim Quadrat sind zusätzlich alle Seiten gleich lang.
W E | Nach fünfmal „Kopf“ beim Münzwurf ist beim sechsten Wurf „Zahl“ wahrscheinlicher. | falsch | Die Münze hat kein Gedächtnis — die Chance bleibt bei jedem Wurf 50 zu 50, der Irrglaube heißt Spielerfehlschluss.
W U | Es gibt mehr natürliche Zahlen als gerade Zahlen. | falsch | Beide Mengen sind gleich groß: Jeder natürlichen Zahl n lässt sich genau die gerade Zahl 2n zuordnen — so zeigt es die Mengenlehre Georg Cantors.
S M log | Auf das erste Feld eines Schachbretts legt man ein Reiskorn, auf jedes weitere doppelt so viele wie auf das vorige. Wie viele Körner liegen auf dem 21. Feld? | 1048576 | Körner | 20 | 1000 | 1000000000 | Mehr als 100.000. ; Weniger als zehn Millionen. ; Es sind 2 hoch 20 — rund eine Million. | Auf dem 64. Feld wären es über neun Trillionen Körner — Hunderte komplette Weltreisernten auf einem einzigen Feld.
S H | Wie viele Primzahlen gibt es zwischen 1 und 100? | 25 | Primzahlen | 20 | 5 | 60 | Mehr als 20. ; Weniger als 30. ; Genau ein Viertel der Zahlen. | Bis 1.000 sind es schon 168 — nach oben hin werden Primzahlen immer seltener, hören aber nie auf.
O M | Sortiere diese Mathematiker nach ihrer Lebenszeit — den frühesten zuerst. | Euklid = um 300 v. Chr. ; Fibonacci = um 1200 ; Leonhard Euler = 1707–1783 ; Carl Friedrich Gauß = 1777–1855 | Der Grieche der „Elemente“ lebte in der Antike. ; Der Italiener mit der berühmten Zahlenfolge folgt im Mittelalter. ; Der Schweizer kam 70 Jahre vor dem „Fürsten der Mathematik“ zur Welt. | Fibonacci machte in Europa die indisch-arabischen Ziffern bekannt, mit denen wir heute rechnen.
O H | Sortiere diese mathematischen Konstanten nach ihrem Wert — die kleinste zuerst. | Wurzel aus 2 = ≈ 1,414 ; Goldener Schnitt = ≈ 1,618 ; Eulersche Zahl e = ≈ 2,718 ; Kreiszahl Pi = ≈ 3,142 | Die Diagonale eines Quadrats mit Seitenlänge 1 ist am kürzesten. ; Das Verhältnis der Schönheit folgt knapp dahinter. ; Die Kreiszahl ist die größte. | Alle vier Zahlen sind irrational — ihre Nachkommastellen enden nie und wiederholen sich nicht.
M E | Welche ZWEI dieser Zahlen sind durch 3 teilbar? | 51 ; 111 | 52 ; 101 ; 77 ; 1000 | Addiere die Ziffern jeder Zahl. ; Ist die Quersumme durch 3 teilbar, ist es auch die Zahl. ; Eine der Lösungen sieht fast wie eine Primzahl aus. | 51 ist 3 mal 17 und 111 ist 3 mal 37 — beide werden oft fälschlich für Primzahlen gehalten.
M H | Welche ZWEI dieser Körper gehören zu den fünf Platonischen Körpern? | Tetraeder ; Ikosaeder | Kugel ; Kegel ; Zylinder ; Quader | Alle ihre Flächen sind gleiche regelmäßige Vielecke. ; Einer besteht aus vier Dreiecken. ; Der andere besteht aus zwanzig Dreiecken. | Neben diesen beiden zählen Würfel, Oktaeder und Dodekaeder dazu — mehr als fünf solcher Körper kann es nicht geben.

@ erfindungen_entdeckungen
E E | Welche Erfindung ist hier gesucht? | 🔥🍐 | Glühbirne | Glühwürmchen ; Taschenlampe ; Leuchtstoffröhre | Sie leuchtet, wenn Strom fließt. ; In ihr glüht ein hauchdünner Draht. ; In der EU verschwand sie ab 2009 schrittweise aus den Regalen. | Nur rund fünf Prozent des Stroms verwandelt eine klassische Glühbirne in Licht — der Rest wird zu Wärme.
E E | Welche Erfindung ist hier gesucht? | ⬇️☂️ | Fallschirm | Regenschirm ; Heißluftballon ; Flugdrachen | Schon Leonardo da Vinci skizzierte eine Version. ; Er bremst einen Sturz durch Luftwiderstand. ; Piloten retten sich mit ihm aus abstürzenden Flugzeugen. | Leonardos pyramidenförmiger Entwurf wurde im Jahr 2000 nachgebaut — und funktionierte tatsächlich.
E M | Welche Erfindung ist hier gesucht? | 🛼🪜 | Rolltreppe | Aufzug ; Laufband ; Paternoster | Man findet sie in Kaufhäusern und Bahnhöfen. ; Ihre Stufen laufen in einer Endlosschleife. ; Auf ihr kann man stehen bleiben und kommt trotzdem nach oben. | Eine der ersten Rolltreppen wurde 1896 als Jahrmarktsattraktion auf Coney Island in New York aufgestellt.
E H | Welche Erfindung ist hier gesucht? | 🎆⚫🇨🇳 | Schwarzpulver | Dynamit ; Nitroglyzerin ; Napalm | Es wurde im alten China erfunden. ; Es besteht aus Salpeter, Holzkohle und Schwefel. ; Früher trieb es Kanonenkugeln und Feuerwerksraketen an. | Chinesische Alchemisten stießen vermutlich bei der Suche nach einem Lebenselixier darauf.
C E | Was entwickelte der Franzose Louis Braille als Jugendlicher? | Eine Blindenschrift | Eine Gebärdensprache ; Eine Kurzschrift ; Einen Blindenstock | Er erblindete als kleines Kind nach einem Unfall. ; Man liest seine Erfindung mit den Fingerspitzen. ; Sie besteht aus erhabenen Punkten. | Braille war erst 15 Jahre alt, als er 1824 sein Punktschrift-System entwickelte.
C M | Wie heißt der erste vollsynthetische Kunststoff, den ein belgisch-amerikanischer Chemiker 1907 erfand? | Bakelit | Nylon ; Zelluloid ; Plexiglas | Er entsteht aus Phenol und Formaldehyd. ; Alte Telefone und Radiogehäuse bestanden oft daraus. ; Sein Name leitet sich vom Erfinder Leo Baekeland ab. | Einmal ausgehärtet, lässt sich Bakelit nicht wieder schmelzen — es gehört zu den Duroplasten.
C M | Welcher Physiker aus Danzig erfand das Quecksilberthermometer und eine bis heute genutzte Temperaturskala? | Daniel Gabriel Fahrenheit | Anders Celsius ; Lord Kelvin ; René-Antoine Réaumur | Er lebte von 1686 bis 1736. ; Seine Skala ist in den USA bis heute üblich. ; Wasser gefriert auf seiner Skala bei 32 Grad. | Den Nullpunkt seiner Skala legte er mit einer Kältemischung aus Eis, Wasser und Salmiak fest.
C H | Welcher Londoner Arzt ließ 1854 während eines Cholera-Ausbruchs den Schwengel einer verseuchten Wasserpumpe abmontieren? | John Snow | Joseph Lister ; Edward Jenner ; Robert Koch | Die Pumpe stand in der Broad Street im Stadtteil Soho. ; Er trug die Todesfälle auf einem Stadtplan ein. ; Er gilt als Begründer der modernen Epidemiologie. | Damals glaubten die meisten Ärzte noch, Cholera werde durch „schlechte Luft“ übertragen.
C U | Welches Element entdeckte der Hamburger Alchemist Hennig Brand 1669 beim Eindampfen von Urin? | Phosphor | Schwefel ; Arsen ; Stickstoff | Brand suchte eigentlich nach dem Stein der Weisen. ; Der Stoff leuchtete im Dunkeln. ; Sein Name bedeutet auf Griechisch „Lichtträger“. | Phosphor gilt als erstes chemisches Element, dessen Entdecker namentlich bekannt ist.
W E | Das Telefon wurde erfunden, bevor Carl Benz sein erstes Automobil baute. | wahr | Bell erhielt sein Telefonpatent 1876 — zehn Jahre bevor Benz 1886 seinen Motorwagen patentieren ließ.
W M | Der Klebstoff der Post-it-Zettel entstand beim Versuch, einen besonders starken Kleber zu entwickeln. | wahr | Der Chemiker Spencer Silver erfand 1968 den schwach haftenden Kleber — erst Jahre später hatte sein Kollege Art Fry die Idee mit den Notizzetteln.
W H | Die ersten Nylonprodukte im Handel waren Damenstrümpfe. | falsch | Schon 1938 kam eine Zahnbürste mit Nylonborsten auf den Markt — die berühmten Nylonstrümpfe folgten erst 1939/40.
S M | Wie viele Jahre lagen zwischen dem ersten Motorflug der Brüder Wright und der ersten Mondlandung? | 66 | Jahre | 10 | 20 | 200 | Weniger als ein Menschenleben. ; Mehr als 50 Jahre. ; Der Motorflug gelang 1903, die Mondlandung 1969. | Viele Menschen erlebten beides — vom ersten Hüpfer über den Sand bis zum ersten Schritt auf dem Mond.
S H | In welchem Jahr gelang Christiaan Barnard in Kapstadt die erste Herztransplantation von Mensch zu Mensch? | 1967 | Jahr | 3 | 1900 | 2000 | In der zweiten Hälfte des 20. Jahrhunderts. ; Vor der ersten Mondlandung. ; Zwei Jahre vor der ersten Mondlandung. | Der Patient Louis Washkansky lebte mit dem neuen Herzen noch 18 Tage.
S U | In welchem Jahr entstand das älteste erhaltene Foto der Welt, aufgenommen von Nicéphore Niépce? | 1826 | Jahr | 3 | 1700 | 1950 | Im 19. Jahrhundert. ; Vor 1850. ; In den 1820er-Jahren. | Die Aufnahme zeigt den Blick aus seinem Fenster — belichtet wurde vermutlich viele Stunden lang.
O M | Ordne diese vier Erfindungen danach, wann sie das Licht der Welt erblickten — die älteste zuerst. | Brille = Ende 13. Jh. ; Fernrohr = 1608 ; Batterie (Volta) = 1800 ; Dynamit = 1867 | Die Sehhilfe entstand im mittelalterlichen Italien. ; Das Instrument für ferne Dinge folgte Anfang des 17. Jahrhunderts. ; Nobels Sprengstoff ist die jüngste Erfindung. | Das Fernrohr wollte der Brillenmacher Hans Lipperhey 1608 patentieren lassen — Galilei baute es kurz darauf nach und richtete es zum Himmel.
M U | Welche ZWEI dieser Dinge wurden von Frauen erfunden? | Kevlar ; Geschirrspülmaschine | Kugelschreiber ; Reißverschluss ; Nähmaschine ; Dynamit | Eine Erfinderin war Chemikerin beim US-Konzern DuPont. ; Die andere wollte ihr feines Porzellan schonender reinigen lassen. ; Eines der Produkte steckt heute in schusssicheren Westen. | Josephine Cochrane ließ ihre Spülmaschine 1886 patentieren, Stephanie Kwolek entwickelte die extrem reißfeste Kevlar-Faser 1965.

@ alltagswissenschaft
E E | Welcher Begriff ist hier gesucht? | ☀️🔥 | Sonnenbrand | Sonnenstich ; Hitzschlag ; Hitzeausschlag | Man holt ihn sich oft im Sommerurlaub. ; Die Haut wird rot, heiß und schmerzt. ; Sonnencreme mit hohem Lichtschutzfaktor schützt davor. | Auch bei bewölktem Himmel erreicht ein großer Teil der UV-Strahlung den Boden — schützen sollte man sich also trotzdem.
E M | Welches Himmelsphänomen ist hier gesucht? | ✈️〰️☁️ | Kondensstreifen | Schleierwolke ; Wetterleuchten ; Luftspiegelung | Man sieht ihn hoch am Himmel. ; Er entsteht hinter Flugzeugen. ; Wasserdampf aus den Triebwerken gefriert dort zu Eiskristallen. | Ob ein Kondensstreifen lange sichtbar bleibt, hängt von der Luftfeuchtigkeit in großer Höhe ab — in trockener Luft verschwindet er schnell.
E H | Welcher Begriff ist hier gesucht? | 🧊🔥 | Gefrierbrand | Frostbeule ; Raureif ; Schockfrosten | Er trifft Lebensmittel in der Tiefkühltruhe. ; Die Oberfläche wird grauweiß, trocken und zäh. ; Schuld ist schlecht verpacktes Gefriergut. | Das Eis an der Oberfläche verdunstet langsam direkt in die trockene Kälte — die Stellen sind ungefährlich, schmecken aber fad.
C E | Warum sollte man sich bei Gewitter nicht unter einen einzeln stehenden Baum stellen? | Blitze schlagen bevorzugt in hohe Punkte ein | Bäume ziehen den Regen an ; Das Laub lädt sich elektrisch auf ; Der Donner lässt Äste abbrechen | Der Baum überragt alles in seiner Umgebung. ; Der Blitz sucht sich den kürzesten Weg zum Boden. ; Auch Kirchtürme und Masten werden oft getroffen. | Der Spruch „Buchen sollst du suchen“ ist ein gefährlicher Irrtum — Blitze schlagen in jede Baumart ein.
C E | Welches Hausmittel löst Kalk im Wasserkocher? | Essig | Speiseöl ; Kochsalz ; Spülmittel | Es ist eine Säure. ; Man kennt es aus der Salatsoße. ; Alternativ hilft auch Zitronensäure. | Kalk ist chemisch Calciumcarbonat — Säuren zersetzen ihn, dabei entweicht Kohlendioxid und es sprudelt.
C M | Warum rostet Edelstahl kaum? | Chrom bildet eine schützende Oxidschicht | Er enthält überhaupt kein Eisen ; Er ist mit Zink überzogen ; Er wird mit Wachs versiegelt | Edelstahl besteht trotzdem größtenteils aus Eisen. ; Ein beigemischtes Metall ist entscheidend. ; Nötig sind mindestens rund 10,5 Prozent davon. | Wird die hauchdünne Schutzschicht verkratzt, bildet sie sich mit Luftsauerstoff von selbst neu.
C H | Warum landet ein vom Tisch fallendes Butterbrot so oft auf der Butterseite? | Die Tischhöhe reicht nur für eine halbe Drehung | Die Butter macht diese Seite schwerer ; Der Luftwiderstand dreht das Brot um ; Das ist reiner Zufall | Das Brot beginnt beim Kippen über die Tischkante zu rotieren. ; Entscheidend ist die Fallhöhe. ; Von einem viel höheren Tisch würde es öfter richtig herum landen. | Der britische Physiker Robert Matthews untersuchte das 1995 und erhielt dafür 1996 den Ig-Nobelpreis.
C U | Welchen körpereigenen Müdigkeits-Botenstoff blockiert Koffein im Gehirn? | Adenosin | Dopamin ; Serotonin ; Melatonin | Er reichert sich im Laufe des Tages im Gehirn an. ; Je mehr davon da ist, desto müder wird man. ; Sein Name erinnert an einen Baustein der DNA. | Koffein besetzt dieselben Andockstellen, ohne sie zu aktivieren — die Müdigkeit wird nur aufgeschoben, nicht beseitigt.
W E | Wasser kocht in einem Topf mit Deckel schneller als ohne. | wahr | Der Deckel hält Wärme und Dampf im Topf — das spart Zeit und eine Menge Energie.
W M | Mit offener Kühlschranktür kann man an heißen Tagen die Küche abkühlen. | falsch | Die Wärme, die er innen abführt, gibt der Kühlschrank hinten wieder ab — dazu kommt die Abwärme des Kompressors, die Küche wird also sogar wärmer.
W H | Einfrieren tötet die meisten Bakterien in Lebensmitteln ab. | falsch | Kälte versetzt die meisten Keime nur in eine Art Winterstarre — nach dem Auftauen vermehren sie sich wieder.
S M | Auf wie viel Grad Celsius erhitzt sich Wasser in einem Schnellkochtopf ungefähr? | 120 | °C | 10 | 50 | 300 | Heißer als kochendes Wasser im offenen Topf. ; Weniger als 150 Grad. ; Etwa 20 Grad mehr als normal. | Der Überdruck im Topf erhöht den Siedepunkt — deshalb garen Kartoffeln darin in einem Bruchteil der Zeit.
S H | Wie heiß wird eine Kerzenflamme an ihrer heißesten Stelle ungefähr — in Grad Celsius? | 1400 | °C | 20 | 100 | 5000 | Mehr als 1.000 Grad. ; Weniger als 2.000 Grad. ; Heißer, als Kupfer zum Schmelzen braucht. | Das gelbe Leuchten der Flamme stammt von winzigen glühenden Rußteilchen.
O M | Sortiere diese Stoffe nach ihrer Dichte — den leichtesten zuerst. | Kork = ≈ 0,2 g/cm³ ; Speiseöl = ≈ 0,92 g/cm³ ; Wasser = 1,0 g/cm³ ; Honig = ≈ 1,4 g/cm³ | Der Flaschenverschluss schwimmt ganz oben. ; Das Salatöl treibt auf dem Wasser. ; Der klebrige Brotaufstrich sinkt nach unten. | Gießt man Flüssigkeiten unterschiedlicher Dichte vorsichtig übereinander, entsteht ein bunter „Dichteturm“ aus stabilen Schichten.
O U | Sortiere diese Lichtquellen nach ihrer Farbtemperatur — die niedrigste zuerst. | Kerzenflamme = ≈ 1.900 K ; Klassische Glühbirne = ≈ 2.700 K ; Mittagssonne = ≈ 5.500 K ; Bedeckter Himmel = ≈ 7.000 K | Das rötlichste Licht hat die niedrigste Farbtemperatur. ; Die alte Lampe leuchtet warm-gelblich. ; Das kühl-bläuliche Licht grauer Tage liegt ganz oben. | Paradox: Lampen mit „warmweißem“ Licht haben eine niedrige Farbtemperatur, „kaltweiße“ eine hohe.
M E | Welche ZWEI dieser Stoffe lösen sich gut in Wasser auf? | Zucker ; Kochsalz | Speiseöl ; Sand ; Kerzenwachs ; Mehl | Beide findet man in der Küche. ; Einer macht den Tee süß. ; Der andere würzt das Nudelwasser. | Warmes Wasser löst Zucker deutlich besser als kaltes — bei Kochsalz macht die Temperatur dagegen kaum einen Unterschied.
M E | Welche ZWEI dieser Dinge haben in einer laufenden Mikrowelle nichts zu suchen, weil es Funken geben kann? | Gabel aus Metall ; Teller mit Goldrand | Glasschüssel ; Porzellanteller ohne Dekor ; Keramiktasse ; Mikrowellen-Abdeckhaube | Beide enthalten Metall. ; Eines davon ist ein Besteckteil. ; Das andere ist Geschirr mit edlem Schmuck. | An Metallkanten und -spitzen ballen sich die elektrischen Felder so stark, dass Funken überspringen können.
"""
